import {MapPin,Navigation,Package,Route,ShieldAlert,ShoppingCart,UserRound} from 'lucide-react'
import type {ReactNode} from 'react'
import {Button} from '../components/actions'
import {Card,KeyValue,ListItem,MetricCard,ProgressRing,StatStrip} from '../components/data'
import {Alert,Badge,StatusBadge,type Tone} from '../components/feedback'
import {SearchInput} from '../components/forms'
import {SectionHeader} from '../components/navigation'
import {Cluster} from '../primitives'
export function ResponsivePageContainer({children}:{children:ReactNode}){return <div className="ng-page-container">{children}</div>}
export function FilterBar({children}:{children?:ReactNode}){return <div className="ng-filter-bar">{children??<><SearchInput label="ط¬ط³طھط¬ظˆ" placeholder="ط¹ط¨ط§ط±طھ ط¬ط³طھط¬ظˆ"/><Button variant="secondary">ظپغŒظ„طھط±ظ‡ط§</Button></>}</div>}
export const SearchFilterBar=FilterBar
export function Toolbar({children}:{children:ReactNode}){return <div className="ng-toolbar">{children}</div>}
export function BulkActionBar({count=3}:{count?:number}){return <div className="ng-bulk"><strong>{count.toLocaleString('fa-IR')} ظ…ظˆط±ط¯ ط§ظ†طھط®ط§ط¨ ط´ط¯ظ‡</strong><span><Button size="sm">ط§ط¬ط±ط§غŒ ط¹ظ…ظ„غŒط§طھ</Button><Button size="sm" variant="ghost">ظ„ط؛ظˆ ط§ظ†طھط®ط§ط¨</Button></span></div>}
export function FormSection({title,description,children}:{title:string;description?:string;children:ReactNode}){return <section className="ng-form-section"><SectionHeader title={title} description={description}/><div>{children}</div></section>}
export function SummaryPanel({title,items}:{title:string;items:Array<{key:string;value:ReactNode}>}){return <aside className="ng-summary-panel"><h3>{title}</h3><KeyValue items={items}/></aside>}
export function ActionFooter({primary='ط«ط¨طھ ظˆ ط§ط¯ط§ظ…ظ‡',secondary='ط°ط®غŒط±ظ‡ ظ¾غŒط´â€Œظ†ظˆغŒط³'}:{primary?:string;secondary?:string}){return <footer className="ng-action-footer"><Button variant="secondary">{secondary}</Button><Button>{primary}</Button></footer>}
export function MasterDetail({master,detail}:{master:ReactNode;detail:ReactNode}){return <div className="ng-master-detail"><aside>{master}</aside><section>{detail}</section></div>}
export function CustomerSummaryCard({name='ظ…ط´طھط±غŒ ظ†ظ…ظˆظ†ظ‡',subtitle='ط´ظ†ط§ط³ظ‡ ظ†ظ…ط§غŒط´غŒ آ· ط¨ط¯ظˆظ† ط¯ط§ط¯ظ‡ ظˆط§ظ‚ط¹غŒ',status='ظپط¹ط§ظ„'}:{name?:string;subtitle?:string;status?:string}){return <Card className="ng-customer-card"><header><span><UserRound/></span><div><strong>{name}</strong><small>{subtitle}</small></div><StatusBadge label={status} tone="success"/></header><StatStrip items={[{label:'ط´ط§ط®طµ غŒع©',value:'â€”'},{label:'ط´ط§ط®طµ ط¯ظˆ',value:'â€”'},{label:'ط¢ط®ط±غŒظ† ظپط¹ط§ظ„غŒطھ',value:'ط§ظ…ط±ظˆط²'}]}/><Cluster><Button size="sm">ظ…ط´ط§ظ‡ط¯ظ‡ ط®ظ„ط§طµظ‡</Button><Button size="sm" variant="secondary">ط¹ظ…ظ„غŒط§طھ ظ…ط¬ط§ط²</Button></Cluster></Card>}
export function RouteStopItem({index=1,title='ط§غŒط³طھع¯ط§ظ‡ ظ†ظ…ظˆظ†ظ‡',meta='ط¨ط§ط²ظ‡ ط²ظ…ط§ظ†غŒ ظ†ظ…ط§غŒط´غŒ',status='ط¨ط±ظ†ط§ظ…ظ‡â€Œط±غŒط²غŒâ€Œط´ط¯ظ‡'}:{index?:number;title?:string;meta?:string;status?:string}){return <div className="ng-route-stop"><span>{index.toLocaleString('fa-IR')}</span><MapPin/><div><strong>{title}</strong><small>{meta}</small></div><StatusBadge label={status} tone="info"/></div>}
export function VisitStatus({label='ط¯ط± ط§ظ†طھط¸ط§ط± ط§ظ‚ط¯ط§ظ…',tone='warning'}:{label?:string;tone?:Tone}){return <StatusBadge label={label} tone={tone}/>} 
export function ProductListRow({title='ظ…ط­طµظˆظ„ ظ†ظ…ظˆظ†ظ‡',subtitle='ع¯ظˆظ†ظ‡ ظ†ظ…ط§غŒط´غŒ',status='ظ‚ط§ط¨ظ„ ط§ظ†طھط®ط§ط¨'}:{title?:string;subtitle?:string;status?:string}){return <ListItem leading={<span className="ng-product-thumb"><Package/></span>} title={title} description={subtitle} trailing={<><StatusBadge label={status} tone="success"/><Button size="sm" variant="secondary">ط§ظپط²ظˆط¯ظ†</Button></>}/>} 
export function ProductCard(){return <Card className="ng-product-card"><div className="ng-product-visual"><Package/></div><Badge tone="premium">ط¨ط±ع†ط³ط¨ ظ†ظ…ط§غŒط´غŒ</Badge><strong>ظ…ط­طµظˆظ„ ظ†ظ…ظˆظ†ظ‡</strong><small>ط§ط·ظ„ط§ط¹ط§طھ ط؛غŒط±طھط¬ط§ط±غŒ ط¨ط±ط§غŒ ط§ط±ط²غŒط§ط¨غŒ ع†غŒط¯ظ…ط§ظ†</small><Button variant="secondary">ط§ظ†طھط®ط§ط¨</Button></Card>}
export function CartRow(){return <div className="ng-cart-row"><ShoppingCart/><span><strong>ظ‚ظ„ظ… ظ†ظ…ظˆظ†ظ‡</strong><small>ظˆط§ط­ط¯ ظ†ظ…ط§غŒط´: ظ†ظ…ظˆظ†ظ‡</small></span><output>غ²</output><Button size="sm" variant="ghost">ظˆغŒط±ط§غŒط´</Button></div>}
export function OrderSummaryShell(){return <Card><SectionHeader title="ط®ظ„ط§طµظ‡ ط¯ط±ط®ظˆط§ط³طھ" description="ط§غŒظ† ط§ظ„ع¯ظˆ ظپط§ظ‚ط¯ ظ…ظ†ط·ظ‚ ظ‚غŒظ…طھطŒ طھط®ظپغŒظپطŒ ط§ط¹طھط¨ط§ط± ظˆ ظ…ظˆط¬ظˆط¯غŒ ط§ط³طھ."/><KeyValue items={[{key:'ط§ظ‚ظ„ط§ظ…',value:'غ² ظ…ظˆط±ط¯ ظ†ظ…ط§غŒط´غŒ'},{key:'ظˆط¶ط¹غŒطھ',value:<StatusBadge label="ظ¾غŒط´â€Œظ†ظˆغŒط³" tone="warning"/>},{key:'ظ†طھغŒط¬ظ‡ ظ†ظ‡ط§غŒغŒ',value:'طھظˆط³ط· ط³ط±ظˆغŒط³ ظ…ط¹طھط¨ط± طھط¹غŒغŒظ† ظ…غŒâ€Œط´ظˆط¯'}]}/><ActionFooter primary="ط§ط¯ط§ظ…ظ‡ ظپط±ط§غŒظ†ط¯"/></Card>}
export function CommercialPreviewShell(){return <Card><SectionHeader title="ظ¾غŒط´â€Œظ†ظ…ط§غŒط´ طھط¬ط§ط±غŒ" description="ط³ط§ط®طھط§ط± ط§ط±ط§ط¦ظ‡ ظپظ‚ط·ط› ط§ط¹ط¯ط§ط¯ ظˆ ظ‚ظˆط§ط¹ط¯ ط§ط² ظ…ظ†ط¨ط¹ ظ…ط¹طھط¨ط± ط¯ط±غŒط§ظپطھ ظ…غŒâ€Œط´ظˆظ†ط¯."/><Alert title="ظ†غŒط§ط²ظ…ظ†ط¯ ط§ط¹طھط¨ط§ط±ط³ظ†ط¬غŒ ط³ط±ظˆغŒط³" tone="info">ظ‡غŒع† ظ…ط­ط§ط³ط¨ظ‡ طھط¬ط§ط±غŒ ط¯ط± ط§غŒظ† ط¬ط²ط، ط§ظ†ط¬ط§ظ… ظ†ظ…غŒâ€Œط´ظˆط¯.</Alert><KeyValue items={[{key:'ظ…ط¨ظ„ط؛ ظ¾ط§غŒظ‡',value:'â€”'},{key:'طھط¹ط¯غŒظ„ط§طھ',value:'â€”'},{key:'ظ…ط¨ظ„ط؛ ظ‚ط§ط¨ظ„ ط§ط±ط§ط¦ظ‡',value:'â€”'}]}/></Card>}
export function WarningBlock(){return <Alert title="ط¹ظ…ظ„غŒط§طھ ظ†غŒط§ط²ظ…ظ†ط¯ ط¨ط±ط±ط³غŒ ط§ط³طھ" tone="warning" action={<Button variant="secondary" size="sm">ط¨ط±ط±ط³غŒ</Button>}>ط´ط±ط­ ط±ظˆط´ظ† ظˆ ظ…ط³طھظ‚ظ„ ط§ط² ط±ظ†ع¯ ط¨ط±ط§غŒ ظˆط¶ط¹غŒطھ ظ‡ط´ط¯ط§ط±.</Alert>}
export function SavedRequestRow(){return <ListItem leading={<Route/>} title="ط¯ط±ط®ظˆط§ط³طھ ط°ط®غŒط±ظ‡â€Œط´ط¯ظ‡ ظ†ظ…ظˆظ†ظ‡" description="ظ¾غŒط´â€Œظ†ظˆغŒط³ ظ…ط­ظ„غŒ آ· ظ‡ظ†ظˆط² ط§ط±ط³ط§ظ„ ظ†ط´ط¯ظ‡" meta="غ±غ° ط¯ظ‚غŒظ‚ظ‡ ظ¾غŒط´" onClick={()=>{}}/>}
export function RouteActionGroup(){return <Cluster><Button startIcon={<Navigation/>}>ط´ط±ظˆط¹ ظ…ط³غŒط±غŒط§ط¨غŒ</Button><Button variant="secondary" startIcon={<MapPin/>}>ظ†ظ…ط§غŒط´ ط±ظˆغŒ ظ†ظ‚ط´ظ‡</Button><Button variant="ghost" startIcon={<ShieldAlert/>}>ع¯ط²ط§ط±ط´ ظ…ط§ظ†ط¹</Button></Cluster>}
export function PatternMetrics(){return <div className="ng-pattern-metrics"><MetricCard label="ط´ط§ط®طµ ظ†ظ…ظˆظ†ظ‡" value="غ±غ²غ¸" detail="ط¯ط§ط¯ظ‡ ط³ط§ط®طھع¯غŒ" trend="+غ¸ظھ" tone="success"/><MetricCard label="ع©غŒظپغŒطھ ظ†ظ…ظˆظ†ظ‡" value="غ¹غ´ظھ" detail="طµط±ظپط§ظ‹ ظ†ظ…ط§غŒط´غŒ"/><MetricCard label="ظ‡ط´ط¯ط§ط±ظ‡ط§" value="غ³" detail="ط¨ط¯ظˆظ† ظ…ط¹ظ†ط§غŒ طھط¬ط§ط±غŒ" tone="warning"/></div>}

export function QuickActionTile({icon,title,meta,tone='premium',onClick}:{icon:ReactNode;title:string;meta?:string;tone?:Tone;onClick?:()=>void}){
  return <button type="button" className={`ng-quick-action ng-tone--${tone}`} onClick={onClick}><span>{icon}</span><strong>{title}</strong>{meta&&<small>{meta}</small>}</button>
}
export function RouteSummaryCard({title='\u0645\u0633\u06cc\u0631 \u0648\u06cc\u0632\u06cc\u062a \u0627\u0645\u0631\u0648\u0632',visited=3,total=5,distance='24 km',eta='\u06f4\u06f5 \u062f\u0642\u06cc\u0642\u0647',children}:{title?:string;visited?:number;total?:number;distance?:string;eta?:string;children?:ReactNode}){
  const percentage=total>0?(visited/total)*100:0
  return <Card className="ng-route-summary"><header><div><span>{'\u0645\u0633\u06cc\u0631 \u0641\u0639\u0627\u0644'}</span><strong>{title}</strong></div><ProgressRing value={percentage} label={'\u0648\u06cc\u0632\u06cc\u062a \u0627\u0645\u0631\u0648\u0632'} detail={`${visited.toLocaleString('fa-IR')} / ${total.toLocaleString('fa-IR')}`}/></header><div className="ng-route-summary__map">{children??<><MapPin/><span>Map / Route Surface</span></>}</div><footer><span><MapPin size={16}/>{distance}</span><span>{eta}</span></footer></Card>
}

