"""Resolve the RPT-14 BatchNo GetList procedure in the approved read-only clone."""
from __future__ import annotations
import argparse,hashlib,json,re,sys
from datetime import datetime
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parent))
from extract_varanegar_org_domain import _assert_safe_target,_connect,_rows  # noqa:E402
def sha(s):return hashlib.sha256(s.encode()).hexdigest()
def main():
 p=argparse.ArgumentParser();p.add_argument("--boundary",required=True,type=Path);p.add_argument("--output",required=True,type=Path);a=p.parse_args();b=json.loads(a.boundary.read_text(encoding="utf-8-sig"));name=b["chain"]["sql_object_candidate"];errors=[];mods=[];con=_connect()
 try:
  cur=con.cursor();ctx=_assert_safe_target(cur);rows=_rows(cur,"SELECT o.object_id,s.name schema_name,o.name,o.type_desc,m.definition,o.modify_date FROM sys.objects o JOIN sys.schemas s ON s.schema_id=o.schema_id LEFT JOIN sys.sql_modules m ON m.object_id=o.object_id WHERE o.name=%s",(name,))
  if len(rows)!=1:errors.append(f"resolution_count_{len(rows)}")
  else:
   r=rows[0];definition=r["definition"] or "";n=" ".join(definition.replace("[","").replace("]","").split()).casefold();params=_rows(cur,"SELECT parameter_id,name parameter_name,TYPE_NAME(user_type_id) data_type,max_length,precision,scale,is_output FROM sys.parameters WHERE object_id=%s ORDER BY parameter_id",(r["object_id"],));deps=_rows(cur,"SELECT DISTINCT COALESCE(referenced_schema_name,'?') referenced_schema,referenced_entity_name FROM sys.sql_expression_dependencies WHERE referencing_id=%s AND referenced_entity_name IS NOT NULL ORDER BY referenced_schema,referenced_entity_name",(r["object_id"],));patterns={"acc_year":r"accyear|acc_year","dc_scope":r"dcref|dc_ref","stock_dc":r"stockdcref|stock_dc","goods_scope":r"goodsref|goodscode","fetch_reason":r"fetchreason","batch_identity":r"batchnoref|batchid|batchno","on_hand":r"onhandqty|allOnHandQty","damaged":r"damagedqty|allDamagedQty","reserved":r"reservedqty","production_date":r"prodate","expiry_date":r"expdate","aggregation":r"\bsum\s*\(|\bgroup\s+by\b"};mods.append({"sql_object":f"{r['schema_name']}.{r['name']}","type_desc":r["type_desc"],"modify_date":r["modify_date"],"definition_sha256":sha(definition),"definition_character_count":len(definition),"parameters":params,"referenced_objects":[f"{x['referenced_schema']}.{x['referenced_entity_name']}" for x in deps],"semantic_profile":{"uses_dynamic_sql":bool(re.search(r"\bsp_executesql\b|\bexec\s*\(@",n)),"write_dml_token_count":len(re.findall(r"\b(insert|update|delete|merge)\b",n)),"semantic_token_counts":{k:len(re.findall(v,n,re.I)) for k,v in patterns.items()}},"definition_persisted":False})
  safe=ctx["updateability"]=="READ_ONLY" and ctx["can_update"]==0 and ctx["denies_data_writes"]==1
  if not safe:errors.append("unsafe_context")
  if len(mods)!=1:errors.append("module_count")
  out={"artifact":"varanegar_production_detail_report_sql_catalog_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not errors else "FAIL","source":{"server_class":"LOCAL_READ_ONLY_CLONE","database":ctx["database_name"],"login":ctx["login_name"],"boundary_sha256":hashlib.sha256(a.boundary.read_bytes()).hexdigest()},"safety":{"database_updateability":ctx["updateability"],"can_update":ctx["can_update"],"denies_data_writes":ctx["denies_data_writes"],"catalog_queries_only":True,"report_or_operational_procedure_executions":0,"raw_definitions_or_business_values_persisted":0,"source_state_changes":0},"summary":{"resolved_module_count":len(mods),"parameter_count":sum(len(x["parameters"]) for x in mods),"dependency_count":sum(len(x["referenced_objects"]) for x in mods),"validation_error_count":len(errors)},"modules":mods,"validation_errors":errors,"confidence":{"identity_signature_dependencies":"CONFIRMED","fetch_reason_formula_and_runtime_results":"UNPROVEN"},"limits":["The procedure was not executed.","FetchReason branch values and result formulas are not persisted or inferred."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2,default=str)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(out["summary"]));return 0 if not errors else 1
 finally:con.close()
if __name__=="__main__":raise SystemExit(main())
