import json,subprocess,sys
from pathlib import Path
R=Path(__file__).resolve().parents[1];B=R/"scripts/windows/build_varanegar_p2_final_evidence_gap_status_matrix_20260829.py";A=R/"artifacts/varanegar_analysis/varanegar_p2_final_evidence_gap_status_matrix_20260829.json"
def load():return json.loads(A.read_text(encoding="utf-8-sig"))
def test_rebuild(tmp_path):o=tmp_path/"g.json";subprocess.run([sys.executable,str(B),"--output",str(o)],check=True);assert json.loads(o.read_text(encoding="utf-8"))["validation"]=="PASS"
def test_partition_and_routes():s=load()["summary"];assert (s["p2_status_packet_count"],s["p2_case_count"],s["pricing_packet_count"],s["treasury_packet_count"])==(6,42,4,2);assert (s["candidate_bearing_packet_count"],s["explicit_none_packet_count"],s["policy_or_lifecycle_review_packet_count"],s["external_alias_or_new_action_decision_packet_count"],s["external_semantic_equivalence_decision_packet_count"])==(5,1,5,1,5)
def test_pair_and_semantic_status():s=load()["summary"];assert (s["same_kind_case_pair_count"],s["failure_injection_pair_count"],s["control_pair_count"])==(73,15,58);assert (s["outcome_exact_pair_count"],s["assertion_list_exact_pair_count"],s["fully_exact_pair_count"],s["exact_effect_family_set_pair_count"],s["zero_effect_family_overlap_pair_count"])==(2,0,0,0,9)
def test_packetization_not_disposition():s=load()["summary"];assert s["analysis_packetization_complete_count"]==6;assert s["semantic_disposition_closed_packet_count"]==s["named_owner_assignment_count"]==s["accepted_alias_or_new_action_decision_count"]==s["accepted_case_disposition_count"]==0
def test_nonadditive_safe():d=load();s=d["summary"];assert s["design_lower_bound_before_p2_status"]==s["design_lower_bound_after_p2_status"]==1404;assert s["executed_case_count"]==s["owner_approved_case_count"]==s["command_ready_module_count"]==s["pilot_ready_module_count"]==0;assert set(d["safety"].values())=={0}
