import json,subprocess,sys
from pathlib import Path
R=Path(__file__).resolve().parents[1];B=R/"scripts/windows/build_varanegar_p4_assertion_effect_family_gap_matrix_20260829.py";A=R/"artifacts/varanegar_analysis/varanegar_p4_assertion_effect_family_gap_matrix_20260829.json"
def load():return json.loads(A.read_text(encoding="utf-8-sig"))
def test_rebuild(tmp_path):o=tmp_path/"e.json";subprocess.run([sys.executable,str(B),"--output",str(o)],check=True);assert json.loads(o.read_text(encoding="utf-8"))["validation"]=="PASS"
def test_pair_family_counts():s=load()["summary"];assert (s["candidate_case_pair_count"],s["effect_family_count"],s["exact_family_set_pair_count"],s["nonempty_family_overlap_pair_count"],s["zero_family_overlap_pair_count"])==(14,18,0,14,0)
def test_asymmetry():s=load()["summary"];assert (s["newer_only_family_assignment_count"],s["baseline_only_family_assignment_count"])==(64,21)
def test_export_specific_gaps():s=load()["summary"];assert (s["newer_file_or_artifact_receipt_pair_count"],s["newer_render_or_export_completion_pair_count"],s["newer_per_item_partial_outcome_pair_count"],s["newer_result_or_content_parity_pair_count"],s["newer_presentation_metric_integrity_pair_count"],s["newer_pinned_query_watermark_pair_count"])==(14,14,14,0,2,6);assert (s["baseline_file_or_artifact_receipt_pair_count"],s["baseline_render_or_export_completion_pair_count"],s["baseline_per_item_partial_outcome_pair_count"],s["baseline_result_or_content_parity_pair_count"],s["baseline_presentation_metric_integrity_pair_count"],s["baseline_pinned_query_watermark_pair_count"])==(12,2,0,4,0,1)
def test_nonadditive_safe():d=load();s=d["summary"];assert s["accepted_family_mapping_count"]==s["accepted_case_pair_count"]==s["result_parity_proven_packet_count"]==0;assert s["design_lower_bound_before_effect_family_matrix"]==s["design_lower_bound_after_effect_family_matrix"]==1404;assert s["executed_case_count"]==s["owner_approved_case_count"]==s["command_ready_module_count"]==s["pilot_ready_module_count"]==0;assert set(d["safety"].values())=={0}
