import hashlib,json,subprocess,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];AUDIT=ROOT/"scripts/windows/audit_varanegar_checkpoint_freshness.py";TOP="artifacts/varanegar_analysis/varanegar_target_erp_contract_portfolio_invariant_audit_checkpoint_20260901.json"
def test_auditor_reports_compact_fresh_graph():
 r=subprocess.run([sys.executable,str(AUDIT),TOP,"--root",str(ROOT)],check=True,text=True,capture_output=True);d=json.loads(r.stdout);assert d["validation"]=="PASS" and d["invalid_json"]==d["stale_references"]==0;assert d["official_bootstrap_exclusions"]==0 and not d["recovery_seed_present"]
def test_auditor_fails_for_missing_checkpoint(tmp_path):
 r=subprocess.run([sys.executable,str(AUDIT),"artifacts/varanegar_analysis/missing_checkpoint.json","--root",str(ROOT)],text=True,capture_output=True);assert r.returncode==1;d=json.loads(r.stdout);assert d["validation"]=="FAIL" and d["stale_references"]==1
def test_auditor_follows_future_dated_checkpoint(tmp_path):
 analysis=tmp_path/"artifacts/varanegar_analysis";analysis.mkdir(parents=True);child=analysis/"varanegar_child_checkpoint_20991231.json";child.write_text(json.dumps({"validation":"PASS","source_manifest":[]}),encoding="utf-8");raw=child.read_bytes();top=analysis/"varanegar_top_checkpoint_20991231.json";rel=child.relative_to(tmp_path).as_posix();top.write_text(json.dumps({"validation":"PASS","previous_checkpoint":{"path":rel,"size_bytes":len(raw),"sha256":hashlib.sha256(raw).hexdigest()},"source_manifest":[]}),encoding="utf-8");official={"runner":{"test_file_count":1,"passed_test_count":1,"bootstrap_excluded_test_file_count":0}};(analysis/"varanegar_25h_final_test_result_20260829.json").write_text(json.dumps(official),encoding="utf-8");r=subprocess.run([sys.executable,str(AUDIT),top.relative_to(tmp_path).as_posix(),"--root",str(tmp_path)],check=True,text=True,capture_output=True);d=json.loads(r.stdout);assert d["reachable_checkpoints"]==2 and d["stale_references"]==0
def test_all_checkpoint_mode_covers_at_least_root_chain():
 root=json.loads(subprocess.run([sys.executable,str(AUDIT),TOP,"--root",str(ROOT)],check=True,text=True,capture_output=True).stdout);all_cp=json.loads(subprocess.run([sys.executable,str(AUDIT),TOP,"--root",str(ROOT),"--all-checkpoints"],check=True,text=True,capture_output=True).stdout);assert root["audit_mode"]=="REACHABLE_FROM_ROOT" and all_cp["audit_mode"]=="ALL_CHECKPOINTS";assert all_cp["reachable_checkpoints"]>=root["reachable_checkpoints"] and all_cp["stale_references"]==0
