import {LoaderCircle} from 'lucide-react'
import {forwardRef,type ButtonHTMLAttributes,type ReactNode} from 'react'
import {cx} from '../utilities'

export type ActionState='default'|'success'|'warning'|'error'|'offline'
export type ButtonProps=ButtonHTMLAttributes<HTMLButtonElement>&{variant?:'primary'|'secondary'|'ghost'|'destructive';size?:'sm'|'md'|'lg';loading?:boolean;state?:ActionState;startIcon?:ReactNode;endIcon?:ReactNode}
export const Button=forwardRef<HTMLButtonElement,ButtonProps>(function Button({variant='primary',size='md',loading=false,state='default',startIcon,endIcon,className,children,disabled,type='button',...props},ref){return <button ref={ref} type={type} className={cx('ng-button',`ng-button--${variant}`,`ng-button--${size}`,`is-${state}`,className)} disabled={disabled||loading} aria-busy={loading||undefined} {...props}>{loading?<LoaderCircle className="ng-spin" size={18}/>:startIcon}<span>{children}</span>{!loading&&endIcon}</button>})
export const IconButton=forwardRef<HTMLButtonElement,ButtonHTMLAttributes<HTMLButtonElement>&{label:string;variant?:'default'|'premium'|'destructive'}>(function IconButton({label,variant='default',className,children,type='button',...props},ref){return <button ref={ref} type={type} className={cx('ng-icon-button',`ng-icon-button--${variant}`,className)} aria-label={label} title={props.title??label} {...props}>{children}</button>})
export function FloatingActionButton({label,children,...props}:ButtonHTMLAttributes<HTMLButtonElement>&{label:string}){return <button type="button" className="ng-fab" aria-label={label} {...props}>{children}<span>{label}</span></button>}
export function SplitAction({label,menuLabel='گزینه‌های بیشتر',onClick,onMenu,disabled}:{label:string;menuLabel?:string;onClick?:()=>void;onMenu?:()=>void;disabled?:boolean}){return <div className="ng-split-action"><Button onClick={onClick} disabled={disabled}>{label}</Button><IconButton label={menuLabel} variant="premium" onClick={onMenu} disabled={disabled}>⌄</IconButton></div>}
