import {Eye,EyeOff,Minus,Plus,Search} from 'lucide-react'
import {forwardRef,useId,useState,type InputHTMLAttributes,type ReactNode,type SelectHTMLAttributes,type TextareaHTMLAttributes} from 'react'
import {IconButton} from './actions'
import {cx} from '../utilities'

type FieldShellProps={id:string;label:string;help?:string;error?:string;required?:boolean;children:ReactNode}
export function Field({id,label,help,error,required,children}:FieldShellProps){const messageId=`${id}-message`;return <div className={cx('ng-field',error&&'is-error')}><label htmlFor={id}>{label}{required&&<span aria-hidden="true"> *</span>}</label>{children}{(error||help)&&<small id={messageId} role={error?'alert':undefined}>{error??help}</small>}</div>}
export type TextInputProps=Omit<InputHTMLAttributes<HTMLInputElement>,'size'>&{label:string;help?:string;error?:string;leading?:ReactNode;trailing?:ReactNode}
export const TextInput=forwardRef<HTMLInputElement,TextInputProps>(function TextInput({label,help,error,leading,trailing,id:given,className,required,...props},ref){const auto=useId(),id=given??auto,messageId=`${id}-message`;return <Field id={id} label={label} help={help} error={error} required={required}><div className={cx('ng-input-wrap',className)}>{leading&&<span aria-hidden="true">{leading}</span>}<input ref={ref} id={id} required={required} aria-invalid={!!error} aria-describedby={error||help?messageId:undefined} {...props}/>{trailing}</div></Field>})
export function PasswordInput(props:Omit<TextInputProps,'type'|'trailing'>){const[visible,setVisible]=useState(false);return <TextInput {...props} type={visible?'text':'password'} trailing={<IconButton className="ng-input-action" label={visible?'پنهان کردن رمز عبور':'نمایش رمز عبور'} aria-pressed={visible} onClick={()=>setVisible(v=>!v)}>{visible?<EyeOff size={18}/>:<Eye size={18}/>}</IconButton>}/>} 
export function SearchInput(props:Omit<TextInputProps,'type'|'leading'>){return <TextInput {...props} type="search" leading={<Search size={18}/>}/>} 
export const TextArea=forwardRef<HTMLTextAreaElement,TextareaHTMLAttributes<HTMLTextAreaElement>&{label:string;help?:string;error?:string}>(function TextArea({label,help,error,id:given,required,...props},ref){const auto=useId(),id=given??auto;return <Field id={id} label={label} help={help} error={error} required={required}><textarea ref={ref} id={id} required={required} aria-invalid={!!error} aria-describedby={error||help?`${id}-message`:undefined} {...props}/></Field>})
export const Select=forwardRef<HTMLSelectElement,SelectHTMLAttributes<HTMLSelectElement>&{label:string;help?:string;error?:string;options:Array<{value:string;label:string}>}>(function Select({label,help,error,options,id:given,required,...props},ref){const auto=useId(),id=given??auto;return <Field id={id} label={label} help={help} error={error} required={required}><select ref={ref} id={id} required={required} aria-invalid={!!error} aria-describedby={error||help?`${id}-message`:undefined} {...props}>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></Field>})
export function Combobox({label,options}:{label:string;options:string[]}){const[list,setList]=useState(false),id=useId();return <div className="ng-combobox"><TextInput label={label} role="combobox" aria-expanded={list} aria-controls={`${id}-list`} onFocus={()=>setList(true)} onChange={()=>setList(true)}/>{list&&<div id={`${id}-list`} role="listbox">{options.map(o=><button type="button" role="option" aria-selected="false" key={o} onMouseDown={e=>e.preventDefault()} onClick={()=>setList(false)}>{o}</button>)}</div>}</div>}
type ChoiceProps={label:string;help?:string}&InputHTMLAttributes<HTMLInputElement>
export function Checkbox({label,help,...props}:ChoiceProps){return <label className="ng-choice"><input type="checkbox" {...props}/><span className="ng-choice__mark"/><span><strong>{label}</strong>{help&&<small>{help}</small>}</span></label>}
export function Radio({label,help,...props}:ChoiceProps){return <label className="ng-choice ng-choice--radio"><input type="radio" {...props}/><span className="ng-choice__mark"/><span><strong>{label}</strong>{help&&<small>{help}</small>}</span></label>}
export function Switch({label,checked,onChange,disabled=false}:{label:string;checked:boolean;onChange:(checked:boolean)=>void;disabled?:boolean}){return <button type="button" className="ng-switch" role="switch" aria-checked={checked} disabled={disabled} onClick={()=>onChange(!checked)}><span/><strong>{label}</strong></button>}
export function SegmentedControl({label,items,value,onChange}:{label:string;items:Array<{id:string;label:string}>;value:string;onChange:(id:string)=>void}){return <div className="ng-segmented" role="group" aria-label={label}>{items.map(i=><button type="button" key={i.id} aria-pressed={i.id===value} onClick={()=>onChange(i.id)}>{i.label}</button>)}</div>}
export function Stepper({label,value,min=0,max=99,onChange}:{label:string;value:number;min?:number;max?:number;onChange:(value:number)=>void}){return <div className="ng-stepper"><span>{label}</span><div><IconButton label={`کاهش ${label}`} disabled={value<=min} onClick={()=>onChange(value-1)}><Minus size={18}/></IconButton><output aria-live="polite">{value.toLocaleString('fa-IR')}</output><IconButton label={`افزایش ${label}`} disabled={value>=max} onClick={()=>onChange(value+1)}><Plus size={18}/></IconButton></div></div>}
export const QuantityControl=Stepper
export function DateTimeField({label='تاریخ و زمان'}:{label?:string}){return <div className="ng-date-field" aria-label={label}><span>{label}</span><div><button type="button">۱۴۰۵/۰۶/۲۰</button><span aria-hidden="true">•</span><button type="button">۰۹:۳۰</button></div></div>}
