import {Bot,ChevronLeft,Home,LayoutGrid,Menu,MoreHorizontal,Search,SlidersHorizontal} from 'lucide-react'
import {useEffect,useId,useRef,type KeyboardEvent,type ReactNode} from 'react'
import {IconButton} from './actions'
import {cx} from '../utilities'
export type NavItem={id:string;label:string;icon:ReactNode}
const defaultNav:NavItem[]=[{id:'home',label:'خانه',icon:<Home/>},{id:'modules',label:'ماژول‌ها',icon:<LayoutGrid/>},{id:'ai',label:'دستیار AI',icon:<Bot/>},{id:'reports',label:'گزارش‌ها',icon:<SlidersHorizontal/>},{id:'more',label:'بیشتر',icon:<MoreHorizontal/>}]
export function TopAppBar({title='Negin AI',subtitle='پلتفرم عملیاتی و هوشمند',actions}:{title?:string;subtitle?:string;actions?:ReactNode}){return <header className="ng-topbar"><div className="ng-brand"><i aria-hidden="true">N</i><span><strong dir="ltr">{title}</strong><small>{subtitle}</small></span></div><div>{actions}</div></header>}
export function PageHeader({eyebrow,title,description,actions}:{eyebrow?:string;title:string;description?:string;actions?:ReactNode}){return <header className="ng-page-header"><div>{eyebrow&&<span>{eyebrow}</span>}<h1>{title}</h1>{description&&<p>{description}</p>}</div>{actions&&<div>{actions}</div>}</header>}
export function SectionHeader({title,description,action}:{title:string;description?:string;action?:ReactNode}){return <header className="ng-section-header"><div><h2>{title}</h2>{description&&<p>{description}</p>}</div>{action}</header>}
export function BottomNavigation({items=defaultNav,activeId,onNavigate}:{items?:NavItem[];activeId:string;onNavigate:(id:string)=>void}){return <nav className="ng-bottom-nav" aria-label="ناوبری اصلی">{items.map(i=><button key={i.id} className={cx(i.id==='ai'&&'is-ai',i.id===activeId&&'is-active')} aria-current={i.id===activeId?'page':undefined} onClick={()=>onNavigate(i.id)}><span>{i.icon}</span><small>{i.label}</small></button>)}</nav>}
export type TabItem={id:string;label:string;disabled?:boolean;panel?:ReactNode}
export function Tabs({items,value,onChange,segmented=false}:{items:TabItem[];value:string;onChange:(id:string)=>void;segmented?:boolean}){const id=useId(),refs=useRef<Array<HTMLButtonElement|null>>([]);function keys(e:KeyboardEvent<HTMLButtonElement>,index:number){if(!['ArrowRight','ArrowLeft','Home','End'].includes(e.key))return;e.preventDefault();const enabled=items.map((x,i)=>({x,i})).filter(v=>!v.x.disabled),at=enabled.findIndex(v=>v.i===index),step=e.key==='ArrowLeft'?1:-1,next=e.key==='Home'?0:e.key==='End'?enabled.length-1:(at+step+enabled.length)%enabled.length,target=enabled[next];onChange(target.x.id);refs.current[target.i]?.focus()}const active=items.find(i=>i.id===value)??items[0];return <div className={cx('ng-tabs',segmented&&'is-segmented')}><div role="tablist">{items.map((i,n)=><button ref={el=>{refs.current[n]=el}} key={i.id} id={`${id}-${i.id}-tab`} role="tab" aria-selected={i.id===active.id} aria-controls={i.panel?`${id}-${i.id}-panel`:undefined} tabIndex={i.id===active.id?0:-1} disabled={i.disabled} onClick={()=>onChange(i.id)} onKeyDown={e=>keys(e,n)}>{i.label}</button>)}</div>{active.panel&&<div id={`${id}-${active.id}-panel`} role="tabpanel" aria-labelledby={`${id}-${active.id}-tab`}>{active.panel}</div>}</div>}
export const SegmentedTabs=(props:Parameters<typeof Tabs>[0])=><Tabs {...props} segmented/>
export function Breadcrumb({items}:{items:string[]}){return <nav aria-label="مسیر صفحه" className="ng-breadcrumb"><ol>{items.map((i,n)=><li key={i}>{i}{n<items.length-1&&<ChevronLeft/>}</li>)}</ol></nav>}
export function CommandSurface(){return <button className="ng-command" type="button"><Search/><span>جستجو در Negin AI یا اجرای فرمان مجاز</span><kbd dir="ltr">Ctrl K</kbd></button>}
export function ContextMenu({items}:{items:string[]}){return <div className="ng-context-menu" role="menu">{items.map(i=><button type="button" role="menuitem" key={i}>{i}</button>)}</div>}
type OverlayProps={open:boolean;title:string;children:ReactNode;onClose:()=>void}
function useDialog(open:boolean){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{if(open&&!ref.current?.open)ref.current?.showModal();if(!open&&ref.current?.open)ref.current.close()},[open]);return ref}
function Overlay({open,title,children,onClose,kind}:{kind:'modal'|'sheet'|'drawer'}&OverlayProps){const ref=useDialog(open);return <dialog ref={ref} className={`ng-${kind}`} onCancel={e=>{e.preventDefault();onClose()}} onClick={e=>{if(e.target===e.currentTarget)onClose()}}><div><header><h2>{title}</h2><IconButton label="بستن" onClick={onClose}>×</IconButton></header><section>{children}</section></div></dialog>}
export const Modal=(p:OverlayProps)=><Overlay {...p} kind="modal"/>;export const BottomSheet=(p:OverlayProps)=><Overlay {...p} kind="sheet"/>;export const AppDrawer=(p:OverlayProps)=><Overlay {...p} kind="drawer"/>
export function MenuButton({onClick}:{onClick:()=>void}){return <IconButton label="باز کردن فهرست" onClick={onClick}><Menu/></IconButton>}

export function ProfileChip({name='\u06a9\u0627\u0631\u0628\u0631 Negin AI',subtitle='\u062d\u0633\u0627\u0628 \u0641\u0639\u0627\u0644',avatar='NA',onClick}:{name?:string;subtitle?:string;avatar?:ReactNode;onClick?:()=>void}){
  return <button type="button" className="ng-profile-chip" onClick={onClick}><span className="ng-profile-chip__avatar">{avatar}</span><span><strong>{name}</strong><small>{subtitle}</small></span><ChevronLeft size={16} aria-hidden="true"/></button>
}
export function NotificationButton({count=0,label='\u0627\u0639\u0644\u0627\u0646\u200c\u0647\u0627',children,onClick}:{count?:number;label?:string;children:ReactNode;onClick?:()=>void}){
  return <button type="button" className="ng-notification-button" aria-label={count>0?`${label} - ${count.toLocaleString('fa-IR')}`:label} onClick={onClick}>{children}{count>0&&<span>{Math.min(count,99).toLocaleString('fa-IR')}</span>}</button>
}
