"""Build evidence-first Pricing Rules expert playbooks."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S={"envelope":"artifacts/varanegar_analysis/varanegar_pricing_rule_outcome_envelope_20260829.json","golden":"artifacts/varanegar_analysis/varanegar_pricing_rule_golden_uat_cases_20260829.json","authoring":"artifacts/varanegar_analysis/domains/discount_rule_authoring_boundary_20260829.json","families":"artifacts/varanegar_analysis/domains/discount_v2_condition_families_20260829.json","linear":"artifacts/varanegar_analysis/ui/varanegar_extension_gap_paths_20260827.json","replication":"artifacts/varanegar_analysis/domains/rule_replication_transport_boundary_20260828.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_pricing_rule_golden_uat_checkpoint_20260829.json"}
COMMON=["capture CommandId, PayloadHash, CorrelationId, aggregate/version, actor/scope, effective window, priority tuple, DSL/schema hash and publication/outbox identity without raw rule text","verify evidence, policy and schema hashes; stop on drift","read aggregate version, compile/explain, calculation provenance, audit, outbox and replication receipts","recompute qualification and precedence from typed inputs; never execute stored rule SQL","classify NATURAL_BEHAVIOR, DATA_DEBT, BUG or UNPROVEN","quarantine unknown, conflicting or unordered effects before retry","stop before publish, close, retry, audit synthesis, priority rewrite or allocator repair","design an isolated synthetic/fault-injection reproduction when the boundary remains unproven"]
BASE=[("PR-PB-01","two rules both qualify or the winner is ambiguous","overlap, effective window and deterministic precedence tuple","compare scope specificity, priority, version/effective time and stable tie breaker; reject an unresolved tie",["R-002","R-005","R-036"]),("PR-PB-02","validation succeeds but publish later fails","side-effect-free compile versus atomic publish","prove validation wrote no business effect; read aggregate/audit/outbox before classifying publish retry",["R-005","R-007","R-023"]),("PR-PB-03","legacy condition works but target DSL result differs","stored executable SQL versus allowlisted AST/DSL","compare normalized AST, schema version, parameters and explain trace; never copy or execute raw SQL",["R-002","R-006","R-036"]),("PR-PB-04","parallel Linear Discount saves collide or skip identity","legacy MAX(Id)+1 allocation","prove unique atomic allocation and one append per CommandId under parallel writers; never repair identity in place",["R-005","R-028","R-034"]),("PR-PB-05","delete or close loses pricing provenance","physical deletion versus immutable closure","trace used calculation receipts; preserve published versions and close with a new audit event",["R-007","R-008","R-036"]),("PR-PB-06","sale price or discount cannot be explained","qualification, precedence and calculation provenance","reconstruct the exact rule version, inputs, intermediate decisions and rounding without exposing business values",["R-002","R-006","R-043"]),("PR-PB-07","replication outcome is partial, missing or unknown","local publication versus asynchronous center delivery","read outbox/package/center receipt, verify ordering and authentication, quarantine unknown and retry the same transport identity",["R-005","R-023","R-036"])]
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 p=argparse.ArgumentParser();p.add_argument("--output",required=True,type=Path);a=p.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};play=[{"id":i,"incident":inc,"focus":focus,"steps":COMMON+[extra],"stop_conditions":["evidence or policy hash drift","write, publish, replay or repair required","owner decision required","raw rule text or sensitive values would be persisted"],"risks":risks,"runtime_diagnosis":"NOT_PERFORMED"} for i,inc,focus,extra,risks in BASE];known={x["id"] for x in d["risk"]["risks"]}
 summary={"playbook_count":len(play),"minimum_step_count":min(len(x["steps"]) for x in play),"command_contract_count":d["envelope"]["summary"]["command_contract_count"],"combined_acceptance_design_count":d["golden"]["summary"]["combined_pricing_acceptance_design_count"],"runtime_incidents_diagnosed_count":0,"repairs_publishes_or_replays_performed_count":0,"owner_approved_count":0,"risk_count":84,"mapped_risk_assignment_count":343,"new_risk_count":0}
 checks={"validated_sources_pass":all(d[k]["validation"]=="PASS" for k in ["envelope","golden","authoring","families","linear","risk","trace","previous"]),"replication_structural_input":d["replication"]["summary"]["target_method_contract_count"]==49,"seven_playbooks":len(play)==7,"nine_steps":all(len(x["steps"])==9 for x in play),"four_way":all("NATURAL_BEHAVIOR, DATA_DEBT, BUG or UNPROVEN" in x["steps"][4] for x in play),"risks_exist":all(r in known for x in play for r in x["risks"]),"seven_and_92":summary["command_contract_count"]==7 and summary["combined_acceptance_design_count"]==92,"allocator_and_replication":any("MAX(Id)+1" in x["focus"] for x in play) and any("asynchronous center delivery" in x["focus"] for x in play),"runtime_zero":summary["runtime_incidents_diagnosed_count"]==summary["repairs_publishes_or_replays_performed_count"]==summary["owner_approved_count"]==0,"base_stable":d["risk"]["summary"]["risk_count"]==84 and d["trace"]["summary"]["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_pricing_rule_expert_playbook_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","safety":{"mode":"OFFLINE_EVIDENCE_SYNTHESIS","database_connections":0,"commands_forms_reports_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"sensitive_values_or_raw_rule_text_persisted":0},"summary":summary,"playbooks":play,"diagnostic_result_contract":{"allowed":["NATURAL_BEHAVIOR","DATA_DEBT","BUG","UNPROVEN"],"requires_named_incident_evidence":True,"repair_publish_close_or_replay_is_separate_authorized_work":True},"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"confidence":{"structure":"HIGH","incident_diagnosis":"REQUIRES_INCIDENT_EVIDENCE"},"limits":["No named incident was diagnosed.","No rule publish, close, retry, replay or repair was executed.","Legacy aggregates are not production-current truth."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(summary,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
