"""Build chained checkpoint for the 14-module command readiness ledger."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
S={"ledger":"artifacts/varanegar_analysis/varanegar_command_readiness_ledger_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_report_surface_closure_checkpoint_20260829.json","builder":"scripts/windows/build_varanegar_command_readiness_ledger_20260829.py","checkpoint_builder":"scripts/windows/build_varanegar_command_readiness_checkpoint_20260829.py","test":"tests/test_varanegar_command_readiness_ledger.py","doc":"docs/varanegar_reconstruction/COMMAND_TRUTH_TABLE_READINESS_LEDGER_20260829_FA.md"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(paths[k]) for k in ("ledger","previous")};c=d["ledger"];s=c["summary"];checks={"sources_pass":all(x["validation"]=="PASS" for x in d.values()),"fourteen_modules":s["module_count"]==14,"static_shapes_pinned":s["legacy_static_command_trace_count"]==11 and s["legacy_mutation_command_count"]==8 and s["legacy_synthetic_golden_case_count"]==77,"owner_runtime_zero":s["owner_approved_golden_case_count"]==0 and s["executed_golden_case_count"]==0 and s["runtime_effect_parity_proven_module_count"]==0,"readiness_zero":s["command_ready_module_count"]==0 and s["pilot_ready_module_count"]==0,"risk_stable":s["risk_count"]==84,"zero_execution":set(v for k,v in c["safety"].items() if k!="mode")=={0}};failed=sorted(k for k,v in checks.items() if not v);out={"artifact":"varanegar_command_readiness_checkpoint_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","previous_checkpoint":{"path":S["previous"],"sha256":sha(paths["previous"])},"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"safety":{"commands_forms_queries_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"database_connections":0,"data_mutations":0,"sensitive_values_persisted":0}};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
