"""Execute deterministic synthetic tax-fiscalization vectors."""
from __future__ import annotations
import argparse,copy,hashlib,importlib.util,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];REFERENCE=ROOT/"scripts/windows/varanegar_tax_fiscalization_reference.py"
S={"tax_contract":"artifacts/varanegar_analysis/varanegar_target_erp_tax_fiscalization_einvoice_clearance_contract_20260829.json","tax_checkpoint":"artifacts/varanegar_analysis/varanegar_target_erp_tax_fiscalization_einvoice_clearance_checkpoint_20260829.json","semantics":"artifacts/varanegar_analysis/varanegar_target_erp_monetary_quantity_temporal_semantics_contract_20260829.json","numbering":"artifacts/varanegar_analysis/varanegar_target_erp_document_numbering_series_void_rollover_contract_20260829.json","integration":"artifacts/varanegar_analysis/varanegar_target_erp_integration_webhook_message_authenticity_replay_deadletter_contract_20260829.json","output":"artifacts/varanegar_analysis/varanegar_target_erp_output_print_pdf_label_barcode_rendering_integrity_contract_20260829.json","tests":"artifacts/varanegar_analysis/varanegar_25h_final_test_result_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def module():s=importlib.util.spec_from_file_location("tax_ref",REFERENCE);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return m
def main():
 p=argparse.ArgumentParser();p.add_argument("--output",required=True,type=Path);a=p.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};m=module();base=m.baseline()
 def changed(**kw):e=copy.deepcopy(base);e.update(kw);return e
 positive=[("POS-DRAFT",base,"FISCAL_DOCUMENT_ACCEPTED_SCHEMA_CALCULATION_AND_IDENTITY"),("POS-ACK",changed(submission_state="ACK"),"SUBMISSION_CLEARED_ACKNOWLEDGED_AND_RECONCILED"),("POS-WARN",changed(submission_state="WARNING"),"SUBMISSION_WARNING_REVIEW_REQUIRED"),("POS-REJECT",changed(submission_state="REJECT"),"SUBMISSION_REJECTED_PROVIDER_CODE_PRESERVED"),("POS-UNKNOWN",changed(submission_state="UNKNOWN"),"SUBMISSION_UNKNOWN_RECONCILIATION_REQUIRED"),("POS-CONTINGENCY",changed(submission_state="CONTINGENCY"),"CONTINGENCY_ACCEPTED_SCOPED_EXPIRING_AND_RECONCILABLE"),("POS-CORRECT",changed(submission_state="CORRECT"),"CORRECTION_OR_CANCELLATION_ACCEPTED_ORIGINAL_PRESERVED"),("POS-CANCEL",changed(submission_state="CANCEL"),"CORRECTION_OR_CANCELLATION_ACCEPTED_ORIGINAL_PRESERVED")]
 negative=[("NEG-EXTRA",dict(base,extra=True),"SCHEMA_INVALID"),("NEG-REGIME",changed(regime_current=False),"FISCAL_DOCUMENT_REJECTED_REGIME_REGISTRATION_OR_SCOPE"),("NEG-REGISTER",changed(registration_current=False),"FISCAL_DOCUMENT_REJECTED_REGIME_REGISTRATION_OR_SCOPE"),("NEG-SCHEMA",changed(schema_current=False),"FISCAL_DOCUMENT_REJECTED_SCHEMA_IDENTIFIER_OR_CLASSIFICATION"),("NEG-ID",changed(identifiers_current=False),"FISCAL_DOCUMENT_REJECTED_SCHEMA_IDENTIFIER_OR_CLASSIFICATION"),("NEG-CLASS",changed(classification_current=False),"FISCAL_DOCUMENT_REJECTED_SCHEMA_IDENTIFIER_OR_CLASSIFICATION"),("NEG-TAX",changed(tax_calculation_current=False),"FISCAL_DOCUMENT_REJECTED_TAX_CALCULATION_OR_ROUNDING"),("NEG-ROUND",changed(rounding_currency_current=False),"FISCAL_DOCUMENT_REJECTED_TAX_CALCULATION_OR_ROUNDING"),("NEG-FISCAL-ID",changed(fiscal_identity_current=False),"FISCAL_DOCUMENT_REJECTED_NUMBER_UUID_TIMESTAMP_OR_DUPLICATE"),("NEG-DIGEST",changed(digest_signature_current=False),"FISCAL_DOCUMENT_REJECTED_DIGEST_SIGNATURE_OR_CERTIFICATE"),("NEG-CERT",changed(certificate_current=False),"FISCAL_DOCUMENT_REJECTED_DIGEST_SIGNATURE_OR_CERTIFICATE"),("NEG-IDEMPOTENCY",changed(idempotency_current=False),"SUBMISSION_REJECTED_IDEMPOTENCY_OR_PAYLOAD_IDENTITY"),("NEG-PARITY",changed(human_machine_parity=False),"OUTPUT_REJECTED_HUMAN_MACHINE_OR_ARCHIVAL_PARITY"),("NEG-ARCHIVE",changed(archive_current=False),"OUTPUT_REJECTED_HUMAN_MACHINE_OR_ARCHIVAL_PARITY"),("NEG-UNKNOWN",changed(blocking_unknown=True),"MANUAL_REVIEW_REQUIRED_BLOCKING_UNKNOWN"),("NEG-ACK-TOTAL",changed(submission_state="ACK",control_totals_reconciled=False),"SUBMISSION_REJECTED_CONTROL_TOTAL_RECONCILIATION"),("NEG-CONT-SCOPE",changed(submission_state="CONTINGENCY",contingency_scope_current=False),"CONTINGENCY_REJECTED_SCOPE_EXPIRY_OR_RECONCILIATION"),("NEG-CONT-EXPIRY",changed(submission_state="CONTINGENCY",contingency_expiry_current=False),"CONTINGENCY_REJECTED_SCOPE_EXPIRY_OR_RECONCILIATION"),("NEG-LINEAGE",changed(submission_state="CORRECT",original_lineage_current=False),"CORRECTION_REJECTED_LINEAGE_PERIOD_OR_PROVIDER_STATE"),("NEG-PERIOD",changed(submission_state="CANCEL",period_state_current=False),"CORRECTION_REJECTED_LINEAGE_PERIOD_OR_PROVIDER_STATE"),("NEG-PROVIDER",changed(submission_state="CORRECT",provider_state_current=False),"CORRECTION_REJECTED_LINEAGE_PERIOD_OR_PROVIDER_STATE")]
 def run(vs):
  r=[]
  for i,e,x in vs:
   y=m.evaluate(e);r.append({"vector_id":i,"expected":x,"actual":y,"status":"PASS" if y==x else "FAIL"})
  return r
 pr=run(positive);nr=run(negative);allr=pr+nr;official=d["tests"];cs=d["tax_contract"]["summary"]
 s={"reference_evaluator_implementation_count":1,"positive_vector_count":len(pr),"positive_pass_count":sum(x["status"]=="PASS" for x in pr),"negative_vector_count":len(nr),"negative_pass_count":sum(x["status"]=="PASS" for x in nr),"total_vector_count":len(allr),"total_pass_count":sum(x["status"]=="PASS" for x in allr),"distinct_typed_outcome_count":len({x["actual"] for x in allr}),"tax_gate_count":cs["gate_count"],"tax_module_gate_assignment_count":cs["module_gate_assignment_count"],"operational_fiscalization_signing_or_clearance_implementation_count":0,"operational_taxpayer_document_value_payload_certificate_or_receipt_read_count":0,"fiscalize_submit_retry_correct_cancel_or_reconcile_run_count":0,"accepted_operational_receipt_count":0,"command_ready_module_count":0,"pilot_ready_module_count":0,"design_lower_bound_before_reference_evaluator":1404,"design_lower_bound_after_reference_evaluator":1404,"official_test_file_count":official["runner"]["test_file_count"],"official_passed_test_count":official["runner"]["passed_test_count"],"risk_count":d["risk"]["summary"]["risk_count"],"mapped_risk_assignment_count":d["trace"]["summary"]["mapped_risk_assignment_count"],"new_risk_count":0}
 checks={"sources_pass":all(d[k].get("validation")=="PASS" for k in ("tax_contract","tax_checkpoint","semantics","numbering","integration","output","tests")),"positive_8_of_8":s["positive_vector_count"]==s["positive_pass_count"]==8,"negative_21_of_21":s["negative_vector_count"]==s["negative_pass_count"]==21,"total_29_of_29":s["total_vector_count"]==s["total_pass_count"]==29,"distinct_outcomes_at_least_18":s["distinct_typed_outcome_count"]>=18,"coverage_24_336":(s["tax_gate_count"],s["tax_module_gate_assignment_count"])==(24,336),"operational_and_readiness_zero":all(s[k]==0 for k in ("operational_fiscalization_signing_or_clearance_implementation_count","operational_taxpayer_document_value_payload_certificate_or_receipt_read_count","fiscalize_submit_retry_correct_cancel_or_reconcile_run_count","accepted_operational_receipt_count","command_ready_module_count","pilot_ready_module_count")),"non_additive_1404":s["design_lower_bound_before_reference_evaluator"]==s["design_lower_bound_after_reference_evaluator"]==1404,"official_tests_pass":official["validation"]=="PASS" and official["runner"]["bootstrap_excluded_test_file_count"]==0,"base_stable":s["risk_count"]==84 and s["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_target_erp_tax_fiscalization_synthetic_reference_evaluator_contract_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","scope":{"mode":"pure_synthetic_jurisdiction_neutral_tax_fiscalization_reference_evaluator","continuation_complete":False,"legal_tax_or_accounting_advice":False,"operational_taxpayer_document_value_payload_certificate_or_receipt_read":False},"safety":{"database_connections":0,"network_reads_or_writes":0,"operational_taxpayer_identifier_document_tax_value_payload_certificate_or_provider_receipt_reads":0,"fiscalize_sign_submit_retry_correct_cancel_or_reconcile_actions_executed":0,"operational_forms_reports_queries_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"credentials_certificates_keys_tokens_pii_or_raw_business_values_read_or_persisted":0},"summary":s,"positive_results":pr,"negative_results":nr,"outcome_precedence":["SCHEMA","REGIME_REGISTRATION","SCHEMA_IDENTIFIERS_CLASSIFICATION","TAX_CALCULATION_ROUNDING","FISCAL_IDENTITY","DIGEST_SIGNATURE_CERTIFICATE","IDEMPOTENCY_PAYLOAD_IDENTITY","HUMAN_MACHINE_ARCHIVE_PARITY","BLOCKING_UNKNOWN","PROVIDER_OUTCOME","CONTINGENCY","CORRECTION_CANCELLATION","RECONCILIATION","ACCEPTED"],"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())]+[{"name":"reference_evaluator","path":REFERENCE.relative_to(ROOT).as_posix(),"size_bytes":REFERENCE.stat().st_size,"sha256":sha(REFERENCE)},{"name":"builder","path":"scripts/windows/build_varanegar_target_erp_tax_fiscalization_synthetic_reference_evaluator_contract_20260829.py","size_bytes":Path(__file__).stat().st_size,"sha256":sha(Path(__file__))}],"limits":["This is jurisdiction-neutral synthetic engineering evidence and not legal tax or accounting advice.","Only fixed booleans and provider-state labels were evaluated; no operational tax data payload certificate or provider was accessed.","Operational fiscalization signing submission correction clearance compliance and readiness remain blocked pending professional review and approved receipts."]}
 a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(s,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
