"""Prioritize the next static-evidence gaps after the completed 25h baseline."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
S={"baseline":"artifacts/varanegar_analysis/varanegar_25h_final_baseline_bundle_20260829.json","commands":"artifacts/varanegar_analysis/varanegar_command_readiness_ledger_20260829.json","reports":"artifacts/varanegar_analysis/varanegar_report_surface_closure_ledger_20260829.json","golden":"artifacts/varanegar_analysis/varanegar_golden_uat_evidence_ledger_20260829.json","voucher_entry":"artifacts/varanegar_analysis/ui/varanegar_accounting_voucher_entrypoint_contracts_20260827.json","voucher_pointer":"artifacts/varanegar_analysis/ui/varanegar_voucher_status_pointer_diagnostic_contract_20260827.json","empty_shell":"artifacts/varanegar_analysis/ui/varanegar_empty_voucher_shell_diagnostic_contract_20260827.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 p=argparse.ArgumentParser();p.add_argument("--output",required=True,type=Path);a=p.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};mods={x["module"]:x for x in d["commands"]["modules"]}
 gaps=[
  {"rank":1,"gap_id":"G24-ACCOUNTING-OUTCOME-LINEAGE","domain":"accounting","class":"STATIC_EVIDENCE_ADVANCEABLE","reason":"target outcome/retry contract is absent while pointer/history forks, detached trailing events and an empty numbered shell require a deterministic diagnostic and outcome envelope","current_evidence":{"entrypoint_candidates":d["voucher_entry"]["summary"]["target_command_candidate_count"],"pointer_not_maximum":d["voucher_pointer"]["summary"]["current_pointer_not_maximum_count"],"detached_trailing_events":d["voucher_pointer"]["summary"]["detached_trailing_event_count"],"empty_numbered_shells":d["empty_shell"]["summary"]["numbered_shell_count"]},"next_artifact":"accounting voucher command/outcome/lineage truth table","risk_links":["R-007","R-021","R-023","R-084"]},
  {"rank":2,"gap_id":"G24-TREASURY-OUTCOME-ENVELOPE","domain":"receivables_treasury","class":"STATIC_EVIDENCE_ADVANCEABLE","reason":"multiple cheque/receipt paths exist but the module-level outcome/retry contract remains absent","risk_links":["R-005","R-007","R-036"]},
  {"rank":3,"gap_id":"G24-REPORT-GOLDEN-FIXTURE-DESIGN","domain":"reporting_documents","class":"DESIGN_ADVANCEABLE_RUNTIME_BLOCKED","reason":"20 owners are closed but result parity and owner-approved values remain zero","risk_links":["R-002","R-017","R-059"]},
  {"rank":4,"gap_id":"G24-DISTRIBUTION-OUTCOME-ENVELOPE","domain":"distribution","class":"STATIC_EVIDENCE_ADVANCEABLE","reason":"exit/distribution evidence is strong but the target outcome/retry contract remains absent","risk_links":["R-005","R-007","R-034"]},
  {"rank":5,"gap_id":"G24-UAT-OWNER-GATES","domain":"cross_cutting","class":"EXTERNAL_AUTHORITY_REQUIRED","reason":"runtime parity and owner acceptance cannot be proven inside the authorized read-only scope","risk_links":["R-002","R-023"]},
 ]
 checks={"baseline_pass":d["baseline"]["validation"]=="PASS","inputs_pass":all(d[k].get("validation")=="PASS" for k in ("commands","reports","golden","voucher_entry","voucher_pointer","empty_shell","risk","trace")),"baseline_fresh":d["baseline"]["baseline"]["stale_checkpoint_manifest_count"]==0,"rank_unique":sorted(x["rank"] for x in gaps)==list(range(1,6)),"first_gap_is_accounting":gaps[0]["gap_id"]=="G24-ACCOUNTING-OUTCOME-LINEAGE","accounting_contract_missing":mods["accounting"]["truth_table_dimensions"]["outcome_retry_idempotency"]["target_contract"] is False,"runtime_gates_not_mislabeled":gaps[-1]["class"]=="EXTERNAL_AUTHORITY_REQUIRED","risk_stable":d["risk"]["summary"]["risk_count"]==84,"trace_stable":d["trace"]["summary"]["mapped_risk_assignment_count"]==343}
 failed=sorted(k for k,v in checks.items() if not v);out={"artifact":"varanegar_24h_continuation_gap_map_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","safety":{"mode":"OFFLINE_FROM_PERSISTED_HASHED_EVIDENCE","database_connections":0,"commands_forms_reports_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"sensitive_values_persisted":0},"baseline":{"path":S["baseline"],"sha256":sha(paths["baseline"]),"checkpoint_count":d["baseline"]["baseline"]["checkpoint_count"],"offline_test_passed_count":d["baseline"]["baseline"]["offline_test_passed_count"],"risk_count":84,"mapped_risk_assignment_count":343},"summary":{"gap_count":len(gaps),"static_or_design_advanceable_count":4,"external_authority_required_count":1,"selected_gap_id":gaps[0]["gap_id"],"new_risk_count":0},"prioritized_gaps":gaps,"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"confidence":{"ranking":"HIGH_WITHIN_CURRENT_EVIDENCE","runtime_parity":"NOT_PROVEN"},"limits":["Ranking prioritizes remaining evidence work, not operational business urgency.","Aggregates do not identify a customer, operator or business document.","No UAT or repair is authorized or performed."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
