"""Checkpoint the P2 baseline candidate shortlist."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
S={"shortlist":"artifacts/varanegar_analysis/varanegar_p2_alias_baseline_candidate_shortlist_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_p1_final_evidence_gap_status_checkpoint_20260829.json","builder":"scripts/windows/build_varanegar_p2_alias_baseline_candidate_shortlist_20260829.py","checkpoint_builder":"scripts/windows/build_varanegar_p2_alias_baseline_candidate_checkpoint_20260829.py","test":"tests/test_varanegar_p2_alias_baseline_candidate_shortlist.py","checkpoint_test":"tests/test_varanegar_p2_alias_baseline_candidate_checkpoint.py","doc":"docs/varanegar_reconstruction/P2_ALIAS_BASELINE_CANDIDATE_SHORTLIST_20260829_FA.md"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};m=load(paths["shortlist"]);prev=load(paths["previous"]);s=m["summary"];checks={"sources_pass":m["validation"]==prev["validation"]=="PASS","p2_6_42":s["p2_packet_count"]==6 and s["p2_case_count"]==42,"split_5_1":(s["candidate_bearing_packet_count"],s["explicit_none_packet_count"])==(5,1),"refs_7_87_38":(s["candidate_baseline_action_reference_count"],s["candidate_baseline_case_reference_count"],s["candidate_case_kind_overlap_reference_count"])==(7,87,38),"search_652":s["searched_baseline_case_reference_count"]==652,"non_additive_1404":s["accepted_candidate_action_count"]==s["accepted_case_disposition_count"]==s["exact_non_duplicated_additive_count"]==0 and s["design_lower_bound_before_shortlist"]==s["design_lower_bound_after_shortlist"]==1404,"execution_readiness_zero":s["executed_case_count"]==s["owner_approved_case_count"]==s["command_ready_module_count"]==s["pilot_ready_module_count"]==0,"base_stable":s["risk_count"]==84 and s["mapped_risk_assignment_count"]==343,"safety_zero":set(m["safety"].values())=={0}};failed=sorted(k for k,v in checks.items() if not v);out={"artifact":"varanegar_p2_alias_baseline_candidate_checkpoint_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","previous_checkpoint":{"path":S["previous"],"sha256":sha(paths["previous"])},"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"safety":{"database_connections":0,"golden_or_uat_execution":0,"data_mutations":0}};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
