"""Execute deterministic synthetic inventory/costing vectors."""
from __future__ import annotations
import argparse,copy,hashlib,importlib.util,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];REFERENCE=ROOT/"scripts/windows/varanegar_inventory_reference.py"
S={"inventory_contract":"artifacts/varanegar_analysis/varanegar_target_erp_inventory_lot_serial_expiry_costing_valuation_contract_20260829.json","inventory_checkpoint":"artifacts/varanegar_analysis/varanegar_target_erp_inventory_lot_serial_expiry_costing_valuation_checkpoint_20260829.json","semantics":"artifacts/varanegar_analysis/varanegar_target_erp_monetary_quantity_temporal_semantics_contract_20260829.json","concurrency":"artifacts/varanegar_analysis/varanegar_target_erp_optimistic_concurrency_version_fencing_contract_20260829.json","fiscal":"artifacts/varanegar_analysis/varanegar_target_erp_fiscal_period_close_reopen_adjustment_lock_contract_20260829.json","tests":"artifacts/varanegar_analysis/varanegar_25h_final_test_result_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def module():s=importlib.util.spec_from_file_location("inv_ref",REFERENCE);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return m
def main():
 p=argparse.ArgumentParser();p.add_argument("--output",required=True,type=Path);a=p.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};m=module();base=m.baseline()
 def changed(**kw):e=copy.deepcopy(base);e.update(kw);return e
 positive=[("POS-MOVE",base,"STOCK_MOVEMENT_ACCEPTED_SCOPED_VERSIONED_AND_BALANCED"),("POS-ALLOCATE",changed(operation="ALLOCATE"),"STOCK_ALLOCATION_ACCEPTED_AVAILABLE_AND_TRACEABLE"),("POS-COST",changed(operation="COST"),"COST_LAYER_ACCEPTED_METHOD_VERSION_AND_LINEAGE"),("POS-TRANSFER",changed(operation="TRANSFER"),"TRANSFER_ACCEPTED_IN_TRANSIT_OWNER_AND_RECEIPT_RECONCILED"),("POS-COUNT",changed(operation="COUNT"),"COUNT_ADJUSTMENT_ACCEPTED_FROZEN_BLIND_AND_APPROVED"),("POS-REVALUE",changed(operation="REVALUE"),"PERIOD_REVALUATION_ACCEPTED_RECONCILED_AND_LINKED"),("POS-RECONCILE",changed(operation="RECONCILE"),"INVENTORY_RECONCILIATION_ACCEPTED_QUANTITY_VALUE_AND_LEDGER")]
 negative=[("NEG-EXTRA",dict(base,extra=True),"SCHEMA_INVALID"),("NEG-SCOPE",changed(scope_current=False),"INVENTORY_REJECTED_SCOPE_UOM_WAREHOUSE_OR_OWNER"),("NEG-IDENTITY",changed(lot_serial_identity_current=False),"LOT_SERIAL_REJECTED_IDENTITY_DATE_OR_TRACEABILITY"),("NEG-DATE",changed(date_semantics_current=False),"LOT_SERIAL_REJECTED_IDENTITY_DATE_OR_TRACEABILITY"),("NEG-VERSION",changed(expected_version_match=False),"STOCK_MOVEMENT_REJECTED_VERSION_OR_IDEMPOTENCY"),("NEG-IDEMPOTENCY",changed(idempotency_current=False),"STOCK_MOVEMENT_REJECTED_VERSION_OR_IDEMPOTENCY"),("NEG-UNKNOWN",changed(unknown_commit=True),"STOCK_MOVEMENT_UNKNOWN_RECONCILIATION_REQUIRED"),("NEG-STATE",changed(stock_state_current=False),"STOCK_MOVEMENT_REJECTED_STATE_RESERVATION_OR_ALLOCATION"),("NEG-QUANTITY",changed(quantity_invariants_current=False),"STOCK_MOVEMENT_REJECTED_STATE_RESERVATION_OR_ALLOCATION"),("NEG-NEGATIVE",changed(negative_stock_policy_current=False),"STOCK_MOVEMENT_REJECTED_NEGATIVE_BACKDATE_OR_UNKNOWN"),("NEG-BLOCK",changed(blocking_unknown=True),"MANUAL_REVIEW_REQUIRED_BLOCKING_UNKNOWN"),("NEG-EXPIRY",changed(operation="ALLOCATE",expiry_recall_quarantine_clear=False),"STOCK_REJECTED_EXPIRY_RECALL_QUARANTINE_OR_DAMAGE"),("NEG-COST-METHOD",changed(operation="COST",cost_method_current=False),"COST_LAYER_REJECTED_METHOD_SCOPE_QUANTITY_OR_ROUNDING"),("NEG-COST-LINEAGE",changed(operation="COST",cost_layer_lineage_current=False),"COST_LAYER_REJECTED_METHOD_SCOPE_QUANTITY_OR_ROUNDING"),("NEG-COST-QTY",changed(operation="COST",cost_layer_quantity_nonnegative=False),"COST_LAYER_REJECTED_METHOD_SCOPE_QUANTITY_OR_ROUNDING"),("NEG-LANDED",changed(operation="COST",landed_cost_reconciled=False),"LANDED_COST_REJECTED_ALLOCATION_OR_RESIDUAL"),("NEG-TRANSFER",changed(operation="TRANSFER",transfer_ownership_current=False),"TRANSFER_REJECTED_SCOPE_OWNER_OR_RECEIPT"),("NEG-COUNT-FREEZE",changed(operation="COUNT",count_frozen_blind=False),"COUNT_ADJUSTMENT_REJECTED_VARIANCE_APPROVAL_OR_VERSION"),("NEG-COUNT-APPROVAL",changed(operation="COUNT",variance_approved=False),"COUNT_ADJUSTMENT_REJECTED_VARIANCE_APPROVAL_OR_VERSION"),("NEG-REVALUE-PERIOD",changed(operation="REVALUE",period_current=False),"PERIOD_REVALUATION_REJECTED_PERIOD_OR_RECONCILIATION"),("NEG-RECONCILE",changed(operation="RECONCILE",stock_cost_gl_reconciled=False),"INVENTORY_RECONCILIATION_REJECTED_QUANTITY_VALUE_OR_LEDGER")]
 def run(vs):
  r=[]
  for i,e,x in vs:
   y=m.evaluate(e);r.append({"vector_id":i,"expected":x,"actual":y,"status":"PASS" if y==x else "FAIL"})
  return r
 pr=run(positive);nr=run(negative);allr=pr+nr;official=d["tests"];cs=d["inventory_contract"]["summary"]
 s={"reference_evaluator_implementation_count":1,"positive_vector_count":len(pr),"positive_pass_count":sum(x["status"]=="PASS" for x in pr),"negative_vector_count":len(nr),"negative_pass_count":sum(x["status"]=="PASS" for x in nr),"total_vector_count":len(allr),"total_pass_count":sum(x["status"]=="PASS" for x in allr),"distinct_typed_outcome_count":len({x["actual"] for x in allr}),"inventory_gate_count":cs["gate_count"],"inventory_module_gate_assignment_count":cs["module_gate_assignment_count"],"operational_inventory_costing_or_traceability_implementation_count":0,"operational_item_lot_serial_quantity_cost_value_or_ledger_read_count":0,"move_allocate_cost_transfer_count_revalue_or_reconcile_run_count":0,"accepted_operational_receipt_count":0,"command_ready_module_count":0,"pilot_ready_module_count":0,"design_lower_bound_before_reference_evaluator":1404,"design_lower_bound_after_reference_evaluator":1404,"official_test_file_count":official["runner"]["test_file_count"],"official_passed_test_count":official["runner"]["passed_test_count"],"risk_count":d["risk"]["summary"]["risk_count"],"mapped_risk_assignment_count":d["trace"]["summary"]["mapped_risk_assignment_count"],"new_risk_count":0}
 checks={"sources_pass":all(d[k].get("validation")=="PASS" for k in ("inventory_contract","inventory_checkpoint","semantics","concurrency","fiscal","tests")),"positive_7_of_7":s["positive_vector_count"]==s["positive_pass_count"]==7,"negative_21_of_21":s["negative_vector_count"]==s["negative_pass_count"]==21,"total_28_of_28":s["total_vector_count"]==s["total_pass_count"]==28,"distinct_outcomes_at_least_19":s["distinct_typed_outcome_count"]>=19,"coverage_24_336":(s["inventory_gate_count"],s["inventory_module_gate_assignment_count"])==(24,336),"operational_and_readiness_zero":all(s[k]==0 for k in ("operational_inventory_costing_or_traceability_implementation_count","operational_item_lot_serial_quantity_cost_value_or_ledger_read_count","move_allocate_cost_transfer_count_revalue_or_reconcile_run_count","accepted_operational_receipt_count","command_ready_module_count","pilot_ready_module_count")),"non_additive_1404":s["design_lower_bound_before_reference_evaluator"]==s["design_lower_bound_after_reference_evaluator"]==1404,"official_tests_pass":official["validation"]=="PASS" and official["runner"]["bootstrap_excluded_test_file_count"]==0,"base_stable":s["risk_count"]==84 and s["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_target_erp_inventory_synthetic_reference_evaluator_contract_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","scope":{"mode":"pure_synthetic_inventory_costing_reference_evaluator","continuation_complete":False,"operational_item_lot_serial_quantity_cost_value_or_ledger_read":False},"safety":{"database_connections":0,"network_reads_or_writes":0,"operational_item_lot_serial_stock_quantity_cost_value_or_ledger_reads":0,"stock_move_reserve_transfer_count_cost_revalue_or_reconcile_actions_executed":0,"operational_forms_reports_queries_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"credentials_pii_or_raw_business_values_read_or_persisted":0},"summary":s,"positive_results":pr,"negative_results":nr,"outcome_precedence":["SCHEMA","SCOPE","LOT_SERIAL_DATE","VERSION_IDEMPOTENCY","UNKNOWN_COMMIT","STATE_QUANTITY","NEGATIVE_POLICY","BLOCKING_UNKNOWN","EXPIRY_QUARANTINE","COST_LAYER","LANDED_COST","TRANSFER","COUNT","PERIOD_REVALUE","RECONCILIATION","ACCEPTED"],"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())]+[{"name":"reference_evaluator","path":REFERENCE.relative_to(ROOT).as_posix(),"size_bytes":REFERENCE.stat().st_size,"sha256":sha(REFERENCE)},{"name":"builder","path":"scripts/windows/build_varanegar_target_erp_inventory_synthetic_reference_evaluator_contract_20260829.py","size_bytes":Path(__file__).stat().st_size,"sha256":sha(Path(__file__))}],"limits":["Only fixed synthetic booleans and operation labels were evaluated.","The evaluator is not an inventory warehouse costing scanner or accounting provider.","Operational movement allocation costing transfer count revaluation reconciliation and readiness remain blocked pending isolated receipts and owner approval."]}
 a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(s,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
