"""Execute deterministic synthetic concurrency decision vectors."""
from __future__ import annotations
import argparse,copy,hashlib,importlib.util,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];REFERENCE=ROOT/"scripts/windows/varanegar_concurrency_reference.py"
S={"concurrency":"artifacts/varanegar_analysis/varanegar_target_erp_optimistic_concurrency_version_fencing_contract_20260829.json","concurrency_checkpoint":"artifacts/varanegar_analysis/varanegar_target_erp_optimistic_concurrency_version_fencing_checkpoint_20260829.json","idempotency":"artifacts/varanegar_analysis/varanegar_target_erp_command_idempotency_outbox_inbox_convergence_contract_20260829.json","transaction":"artifacts/varanegar_analysis/varanegar_target_erp_transaction_owner_saga_compensation_contract_20260829.json","tests":"artifacts/varanegar_analysis/varanegar_25h_final_test_result_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def module():
 s=importlib.util.spec_from_file_location("concurrency_ref",REFERENCE);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return m
def main():
 p=argparse.ArgumentParser();p.add_argument("--output",required=True,type=Path);a=p.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};m=module();base=m.baseline()
 commit=copy.deepcopy(base);replay=copy.deepcopy(base);replay["idempotency_receipt_exists"]=True;deadlock=copy.deepcopy(base);deadlock["deadlock_or_timeout_before_commit"]=True;deadlock["compare_and_swap_match_count"]=0
 positive=[("POS-COMMIT",commit,"COMMIT_ACCEPTED_EXPECTED_VERSION_MATCHED"),("POS-REPLAY",replay,"IDEMPOTENT_REPLAY_EXISTING_RECEIPT"),("POS-DEADLOCK-RETRY",deadlock,"RETRY_ALLOWED_SAME_COMMAND_IDENTITY")]
 specs=[("NEG-EXTRA","extra",1,"SCHEMA_INVALID"),("NEG-TYPE","expected_version","7","SCHEMA_INVALID"),("NEG-FINGERPRINT","idempotency_receipt_exists",True,"CONFLICT_FINGERPRINT_OR_IDEMPOTENCY_KEY","same_command_fingerprint",False),("NEG-UNKNOWN","commit_status","UNKNOWN","RECONCILIATION_REQUIRED_UNKNOWN_COMMIT"),("NEG-RETRY-ID","deadlock_or_timeout_before_commit",True,"RETRY_REJECTED_COMMAND_IDENTITY_CHANGED","command_identity_preserved",False),("NEG-VERSION","observed_version",8,"CONFLICT_EXPECTED_VERSION_MISMATCH"),("NEG-CAS-ZERO","compare_and_swap_match_count",0,"CONFLICT_COMPARE_AND_SWAP_CARDINALITY"),("NEG-CAS-MULTI","compare_and_swap_match_count",2,"CONFLICT_COMPARE_AND_SWAP_CARDINALITY"),("NEG-INVARIANT","business_invariant_version_current",False,"CONFLICT_BUSINESS_INVARIANT_VERSION_SET"),("NEG-SEQUENCE","candidate_sequence",10,"CONFLICT_SEQUENCE_NOT_MONOTONIC"),("NEG-LEASE","lease_valid_and_owned",False,"CONFLICT_LEASE_INVALID_OR_WRONG_OWNER"),("NEG-FENCE","candidate_fencing_token",20,"CONFLICT_FENCING_TOKEN_STALE"),("NEG-BULK","bulk_atomic_or_quarantined",False,"BULK_REJECTED_MIXED_VERSION_PARTIAL_POLICY")]
 negative=[]
 for spec in specs:
  i,key,value,expected,*extra=spec;e=copy.deepcopy(base);e[key]=value
  if extra:e[extra[0]]=extra[1]
  negative.append((i,e,expected))
 def run(vs):return [{"vector_id":i,"expected":x,"actual":m.evaluate(e),"status":"PASS" if m.evaluate(e)==x else "FAIL"} for i,e,x in vs]
 pr=run(positive);nr=run(negative);o=d["tests"]
 s={"reference_evaluator_implementation_count":1,"positive_vector_count":len(pr),"positive_pass_count":sum(x["status"]=="PASS" for x in pr),"negative_vector_count":len(nr),"negative_pass_count":sum(x["status"]=="PASS" for x in nr),"total_vector_count":len(pr)+len(nr),"total_pass_count":sum(x["status"]=="PASS" for x in pr+nr),"distinct_typed_outcome_count":len({x["actual"] for x in pr+nr}),"target_command_count":d["concurrency"]["summary"]["target_command_count"],"command_gate_assignment_count":d["concurrency"]["summary"]["command_gate_assignment_count"],"operational_concurrency_implementation_count":0,"runtime_version_lock_lease_or_fencing_read_count":0,"command_conflict_retry_or_reconciliation_run_count":0,"accepted_operational_receipt_count":0,"command_ready_count":0,"pilot_ready_module_count":0,"design_lower_bound_before_reference_evaluator":1404,"design_lower_bound_after_reference_evaluator":1404,"official_test_file_count":o["runner"]["test_file_count"],"official_passed_test_count":o["runner"]["passed_test_count"],"risk_count":d["risk"]["summary"]["risk_count"],"mapped_risk_assignment_count":d["trace"]["summary"]["mapped_risk_assignment_count"],"new_risk_count":0}
 checks={"sources_pass":all(d[k].get("validation")=="PASS" for k in ("concurrency","concurrency_checkpoint","idempotency","transaction","tests")),"positive_3_of_3":s["positive_vector_count"]==s["positive_pass_count"]==3,"negative_13_of_13":s["negative_vector_count"]==s["negative_pass_count"]==13,"total_16_of_16":s["total_vector_count"]==s["total_pass_count"]==16,"coverage_49_882":(s["target_command_count"],s["command_gate_assignment_count"])==(49,882),"operational_and_readiness_zero":s["operational_concurrency_implementation_count"]==s["runtime_version_lock_lease_or_fencing_read_count"]==s["command_conflict_retry_or_reconciliation_run_count"]==s["accepted_operational_receipt_count"]==s["command_ready_count"]==s["pilot_ready_module_count"]==0,"non_additive_1404":s["design_lower_bound_before_reference_evaluator"]==s["design_lower_bound_after_reference_evaluator"]==1404,"official_tests_pass":o["validation"]=="PASS" and o["runner"]["bootstrap_excluded_test_file_count"]==0,"base_stable":s["risk_count"]==84 and s["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_target_erp_concurrency_synthetic_reference_evaluator_contract_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","scope":{"mode":"pure_synthetic_concurrency_state_decision_reference","continuation_complete":False,"runtime_version_transaction_lock_lease_or fence_read":False},"safety":{"database_connections":0,"network_reads_or_writes":0,"runtime_versions_transactions_locks_leases_or_fencing_tokens_read":0,"commands_conflicts_deadlocks_retries_or_reconciliations_executed":0,"operational_forms_reports_queries_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"credentials_endpoints_pii_or_raw_business_values_read_or_persisted":0},"summary":s,"positive_results":pr,"negative_results":nr,"outcome_precedence":["SCHEMA","IDEMPOTENCY_RECEIPT","UNKNOWN_COMMIT","DEADLOCK_RETRY","EXPECTED_VERSION","CAS_CARDINALITY","BUSINESS_INVARIANT","SEQUENCE","LEASE","FENCING","BULK_POLICY","COMMIT"],"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())]+[{"name":"reference_evaluator","path":REFERENCE.relative_to(ROOT).as_posix(),"size_bytes":REFERENCE.stat().st_size,"sha256":sha(REFERENCE)},{"name":"builder","path":"scripts/windows/build_varanegar_target_erp_concurrency_synthetic_reference_evaluator_contract_20260829.py","size_bytes":Path(__file__).stat().st_size,"sha256":sha(Path(__file__))}],"limits":["Only fixed synthetic versions counts booleans sequence and fencing numbers were evaluated.","The evaluator is not a repository transaction lock lease sequence or command implementation.","Operational command acceptance remains blocked pending authenticated runtime receipts."]}
 a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(s,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
