"""Build the static accounting command/outcome/lineage truth table."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
S={"gap":"artifacts/varanegar_analysis/varanegar_24h_continuation_gap_map_20260829.json","entry":"artifacts/varanegar_analysis/ui/varanegar_accounting_voucher_entrypoint_contracts_20260827.json","atomicity":"artifacts/varanegar_analysis/domains/voucher_creation_atomicity_and_policy_20260828.json","pointer":"artifacts/varanegar_analysis/ui/varanegar_voucher_status_pointer_diagnostic_contract_20260827.json","shell":"artifacts/varanegar_analysis/ui/varanegar_empty_voucher_shell_diagnostic_contract_20260827.json","stock":"artifacts/varanegar_analysis/domains/stock_voucher_state_runtime_boundary_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_24h_continuation_gap_checkpoint_20260829.json"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def row(cid,ui,business,adapter,procedure,tx,outcome,retry,confidence,limits):return {"command_id":cid,"ui_action":ui,"permission_scope":"read list is session AccYear/DC scoped; action-specific server authorization not proven","business_handler":business,"adapter":adapter,"procedure_or_sql":procedure,"transaction_owner":tx,"mutation_and_lineage":"voucher/pre-voucher/current-pointer/history effects must be correlated by immutable command/source identity","outcome_contract":outcome,"retry_contract":retry,"confidence":confidence,"unproven":limits,"owner_approved":False,"runtime_effect_parity_proven":False}
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};rows=[
 row("accounting.external_voucher.generate","FormExternalVoucher.DoWorkSave","ExternalVoucherHeaderHandler.DoExternalVoucher","ExternalVoucherHeaderAdapter.DoExternalVoucher","dbo.usp_DoExternalVoucher -> dbo.usp_DoPreVoucher","managed outer DataContext transaction; client Commit after adapter","VALIDATION_REJECTED before confirm when MessageType=1; ISSUED only from MessageType=0 header identity","same source/DC is source-immutable, but no explicit command id; retry requires read-back before reissue","HIGH_STATIC",["direct/nonstandard caller atomicity","runtime authorization","policy preflight race"]),
 row("accounting.external_voucher.confirm","FormExternalVoucher.DoWorkSave or DoWorkConfirmed","ExternalVoucherHeaderHandler.DoExternalVoucherConfirmed","ExternalVoucherHeaderAdapter.DoExternalVoucherConfirmed","dbo.usp_DoExternalVoucherConfirmed","managed outer DataContext transaction","CONFIRMED only after adapter completion and Commit; validation stops transfer chain","read current state and prior command outcome before retry; no blind replay","HIGH_STATIC",["action permission","runtime branch/effect parity"]),
 row("accounting.external_voucher.delete","FormExternalVoucher.DoWorkDelete","ExternalVoucherHeaderHandler.DoExternalVoucherDelete","ExternalVoucherHeaderAdapter.DoExternalVoucherDelete","dbo.usp_DoExternalVoucherDelete","managed outer DataContext transaction","DELETED only for unconfirmed/untransferred batch; regeneration is a new outcome","retry must distinguish already-deleted from never-issued and preserve tombstone/audit","HIGH_STATIC",["action permission","historical delete reason"]),
 row("accounting.external_voucher.transfer","FormExternalVoucher.DoWorkSave or DoWorkTransfer","ExternalVoucherHeaderHandler.DoExternalVoucherTransfer","ExternalVoucherHeaderAdapter.DoExternalVoucherTransfer","dbo.usp_DoExternalVoucherTransfer","managed outer DataContext transaction","TRANSFERRED on success; BUSINESS_ERROR may coexist with committed SetVoucherNo cleanup","never infer rollback from error text; reconcile durable cleanup and voucher pointer before retry","HIGH_STATIC",["exact runtime affected batch","authorization","business-error effect parity"]),
 row("stock_voucher.confirm_or_unconfirm","FormConfirmVocher filtered worklist","VocherHdrHandler Confirm/UnConfirm or MainConfirmVocher","VocherHdrAdapter Confirm/UnConfirm plus possible direct dynamic update route","dbo.USP_SDSNET_ConfirmVocher / dbo.USP_SDSNET_UnConfirmVocher or hash-only dynamic update","adapter path commits locally; shared enlistment of main dynamic route unproven","CONFIRMED or UNCONFIRMED only after validation, durable header state and projection/cardex reconciliation","retry requires expected version/state and read-back; route ambiguity forbids blind replay","MEDIUM_STATIC_ROUTE_AMBIGUITY",["MainConfirm overload callsite","shared physical transaction","branch selection"]),
 row("accounting.manual_voucher.save","FormManualVoucherDataEntry2.SaveCommand","unresolved from scoped entrypoint evidence","unresolved","unresolved","not proven","balanced debit/credit command candidate; no committed outcome claimed","do not retry until command identity, persistence boundary and read-back key are extracted","LOW_CANDIDATE_ONLY",["business handler","adapter/procedure","authorization","mutation set","transaction"]),
 row("accounting.manual_voucher.cancel","FormManualVoucherDataEntry2.InternalCancelCommand","unresolved from scoped entrypoint evidence","unresolved","unresolved","not proven","cancel/reversal candidate; deletion versus reversal semantics not claimed","no retry contract until lineage/tombstone behavior is statically resolved","LOW_CANDIDATE_ONLY",["business handler","adapter/procedure","reversal lineage","transaction"]),
 ]
 known={x["id"] for x in d["risk"]["risks"]};risks=["R-005","R-007","R-021","R-023","R-084"];checks={"gap_selected":d["gap"]["summary"]["selected_gap_id"]=="G24-ACCOUNTING-OUTCOME-LINEAGE","validated_sources":all(d[k].get("validation")=="PASS" for k in ("gap","entry","pointer","shell","stock","risk","previous")),"seven_candidates":len(rows)==d["entry"]["summary"]["target_command_candidate_count"]==7,"unique_commands":len({x["command_id"] for x in rows})==7,"four_external_exact_procedures":sum(x["procedure_or_sql"].startswith("dbo.usp_DoExternalVoucher") for x in rows)==4,"manual_gaps_honest":sum(x["confidence"]=="LOW_CANDIDATE_ONLY" for x in rows)==2,"no_runtime_claims":not any(x["runtime_effect_parity_proven"] or x["owner_approved"] for x in rows),"lineage_findings_pinned":d["pointer"]["summary"]["current_pointer_not_maximum_count"]==1094 and d["pointer"]["summary"]["detached_trailing_event_count"]==14946 and d["shell"]["summary"]["numbered_shell_count"]==1,"risk_links_exist":set(risks)<=known}
 failed=sorted(k for k,v in checks.items() if not v);out={"artifact":"varanegar_accounting_command_outcome_truth_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","safety":{"mode":"OFFLINE_STATIC_AND_PERSISTED_EVIDENCE","database_connections":0,"commands_forms_reports_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"sensitive_values_persisted":0},"summary":{"command_candidate_count":7,"exact_external_procedure_command_count":4,"route_ambiguous_stock_command_count":1,"candidate_only_manual_command_count":2,"target_outcome_contract_count":7,"runtime_effect_parity_proven_count":0,"owner_approved_count":0,"risk_count":84,"new_risk_count":0},"outcome_vocabulary":["VALIDATION_REJECTED","ISSUED","CONFIRMED","UNCONFIRMED","TRANSFERRED","DELETED","BUSINESS_ERROR_WITH_DURABLE_EFFECT_POSSIBLE","ALREADY_APPLIED","STALE_STATE","UNPROVEN"],"lineage_diagnostic":{"current_pointer_not_maximum_count":1094,"detached_trailing_event_count":14946,"empty_numbered_shell_count":1,"rules":["current pointer is not equivalent to MAX(history)","error text is not rollback evidence","never synthesize missing lines or reuse a number without owner-approved disposition"]},"truth_table":rows,"erp_target_contract":{"command_envelope":["command_id","actor_and_scope","fiscal_and_operation_date","expected_version","policy_snapshot_version","source_identity"],"outcome_envelope":["outcome_code","committed","aggregate_version","durable_effect_summary","retryable","correlation_id"],"required_guards":["deny-first action authorization","one explicit unit of work","immutable audit/outbox","read-back reconciliation before retry","quarantine for pointer/history forks and empty shells"]},"risk_links":risks,"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"confidence":{"external_voucher_static_path":"HIGH","stock_route_selection":"MEDIUM","manual_voucher_path":"LOW_CANDIDATE_ONLY","runtime_parity":"NOT_PROVEN"},"limits":["No accounting command or procedure was executed.","Exact table mutation sets are not inferred where source evidence is only an entrypoint candidate.","Aggregate diagnostics do not identify or classify a particular voucher."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
