"""Build a portable, read-only handoff capsule for the ten-hour continuation."""
from __future__ import annotations
import argparse,hashlib,json
from collections import deque
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
S={"top_checkpoint":"artifacts/varanegar_analysis/varanegar_target_erp_contract_portfolio_invariant_audit_checkpoint_20260901.json","official_tests":"artifacts/varanegar_analysis/varanegar_25h_final_test_result_20260829.json","final_bundle":"artifacts/varanegar_analysis/varanegar_25h_final_baseline_bundle_20260829.json","wave_bundle":"artifacts/varanegar_analysis/varanegar_24h_continuation_wave01_bundle_20260829.json","consolidated_audit":"artifacts/varanegar_analysis/varanegar_24h_continuation_consolidated_audit_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json","knowledge":"docs/VARANEGAR_KNOWLEDGE_FA.md","discovery":"docs/varanegar_reconstruction/DISCOVERY_LOG_FA.md","readme":"docs/varanegar_reconstruction/README_FA.md","settler":"scripts/windows/settle_varanegar_analysis_chain_20260831.ps1","official_runner":"scripts/windows/run_varanegar_25h_final_tests.py","freshness_auditor":"scripts/windows/audit_varanegar_checkpoint_freshness.py"}
FAMILIES=[
 {"family":"golden_uat_result_parity_and_promotion_guard","status":"DESIGN_AND_OFFLINE_REFERENCE_COMPLETE_RUNTIME_EXTERNAL","capabilities":["frozen fixture output manifest","result parity receipt and mismatch diagnostic","adjudication plus promotion guard","capture authorization and redaction","hash-only custody retention revocation","freshness invalidation reopen propagation","offline comparison adapter conformance"]},
 {"family":"resilience_and_command_integrity","status":"DESIGN_COMPLETE_RUNTIME_EXTERNAL","capabilities":["backup restore rehearsal","restore dependency waves","idempotency outbox inbox","transaction owner saga compensation","authorization scope decision trace","evidence logging redaction retention"]},
 {"family":"migration_release_and_operations","status":"DESIGN_PLUS_SYNTHETIC_REFERENCES","capabilities":["migration snapshot delta reconciliation","environment isolation write fence token","release promotion rollback","observability slo incident","configuration immutability","provenance read model rebuild","capacity backpressure degradation"]},
 {"family":"core_semantics_identity_and_governance","status":"DESIGN_PLUS_SYNTHETIC_REFERENCES","capabilities":["monetary quantity temporal semantics","optimistic concurrency fencing","master data identity dedup merge supersession","document numbering void rollover","file attachment integrity","fiscal close reopen","privacy rights","approval delegation sod breakglass"]},
 {"family":"integration_output_tax_inventory","status":"DESIGN_PLUS_SYNTHETIC_REFERENCES","capabilities":["webhook authenticity replay deadletter","print pdf label barcode integrity","tax fiscalization einvoice clearance","lot serial expiry costing valuation"]},
 {"family":"end_to_end_erp_cycles_added_last","status":"DESIGN_PLUS_SYNTHETIC_REFERENCES","capabilities":["procure to pay and three way match","order to cash credit receivables collections","workforce time payroll","fixed asset lifecycle and depreciation","manufacturing mrp shopfloor and quality","project job costing progress billing and revenue recognition"]},
]
NEXT=["isolated owner-authorized Golden/UAT result-parity receipts; operational execution is still outside this capsule","provider and platform selection with explicit security privacy residency and support evidence","country/customer-specific tax payroll banking and regulatory policy acceptance","performance recovery concurrency and failure-injection execution in an isolated non-production environment","business-owner sign-off on tolerances formulas mappings roles and exception ownership"]
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def graph(top):
 q=deque([top]);seen=set();stale=[];passing=0
 while q:
  rel=q.popleft().replace("\\","/")
  if rel in seen:continue
  seen.add(rel);p=ROOT/rel
  if not p.is_file():stale.append({"path":rel,"reason":"missing_checkpoint"});continue
  d=load(p);passing+=d.get("validation")=="PASS";refs=list(d.get("source_manifest",[]));prev=d.get("previous_checkpoint")
  if isinstance(prev,dict) and prev.get("path"):refs.append(prev)
  for x in refs:
   r=str(x.get("path","")).replace("\\","/");t=ROOT/r
   if not t.is_file():stale.append({"path":r,"reason":"missing"});continue
   if x.get("size_bytes") is not None and x["size_bytes"]!=t.stat().st_size:stale.append({"path":r,"reason":"size"})
   if x.get("sha256") and x["sha256"]!=sha(t):stale.append({"path":r,"reason":"sha256"})
   if Path(r).name.startswith("varanegar_") and "_checkpoint_" in Path(r).stem:q.append(r)
 return {"reachable_checkpoint_count":len(seen),"passing_checkpoint_count":passing,"stale_reference_count":len(stale),"stale_sample":stale[:10]}
def main():
 p=argparse.ArgumentParser();p.add_argument("--output",required=True,type=Path);a=p.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items() if S[k].endswith(".json")};official=d["official_tests"];g=graph(S["top_checkpoint"]);json_files=list((ROOT/"artifacts/varanegar_analysis").glob("*.json"));invalid=[]
 for f in json_files:
  try:load(f)
  except Exception:invalid.append(f.relative_to(ROOT).as_posix())
 runner=official["runner"];summary={"knowledge_root":ROOT.as_posix(),"json_artifact_count":len(json_files),"invalid_json_count":len(invalid),**g,"official_test_file_count":runner["test_file_count"],"official_passed_test_count":runner["passed_test_count"],"official_bootstrap_exclusion_count":runner["bootstrap_excluded_test_file_count"],"risk_count":d["risk"]["summary"]["risk_count"],"mapped_risk_assignment_count":d["trace"]["summary"]["mapped_risk_assignment_count"],"design_lower_bound":1404,"runtime_result_parity_proven_count":0,"command_ready_module_count":0,"pilot_ready_module_count":0,"database_connection_count":0,"network_read_or_write_count":0,"operational_execution_count":0,"data_mutation_count":0,"assembly_load_or_execution_count":0,"sensitive_value_persisted_count":0}
 checks={"top_and_bundles_pass":all(d[k].get("validation")=="PASS" for k in ("top_checkpoint","official_tests","final_bundle","wave_bundle","consolidated_audit")),"all_json_parse":summary["invalid_json_count"]==0,"checkpoint_graph_pass_and_fresh":summary["reachable_checkpoint_count"]==summary["passing_checkpoint_count"] and summary["stale_reference_count"]==0,"official_tests_pass_no_exclusion":official["validation"]=="PASS" and runner["exit_code"]==0 and runner["bootstrap_excluded_test_file_count"]==0,"baseline_stable":summary["risk_count"]==84 and summary["mapped_risk_assignment_count"]==343 and summary["design_lower_bound"]==1404,"runtime_and_readiness_zero":all(summary[k]==0 for k in ("runtime_result_parity_proven_count","command_ready_module_count","pilot_ready_module_count","database_connection_count","network_read_or_write_count","operational_execution_count","data_mutation_count","assembly_load_or_execution_count","sensitive_value_persisted_count")),"handoff_files_present":all(x.is_file() for x in paths.values())};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_10h_continuation_handoff_capsule_20260901","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","scope":{"mode":"READ_ONLY_DOCUMENTED_REPRODUCIBLE_HANDOFF","portable_project_root":ROOT.as_posix(),"operational_runtime_certification":False,"continuation_capsule_complete":True},"current_resume_point":{"top_checkpoint":S["top_checkpoint"],"freshness_command":".venv\\Scripts\\python.exe scripts/windows/audit_varanegar_checkpoint_freshness.py "+S["top_checkpoint"],"full_settle_command":"powershell.exe -NoProfile -ExecutionPolicy Bypass -File scripts/windows/settle_varanegar_analysis_chain_20260831.ps1","knowledge_index":"docs/VARANEGAR_KNOWLEDGE_FA.md","reconstruction_index":"docs/varanegar_reconstruction/README_FA.md","discovery_log":"docs/varanegar_reconstruction/DISCOVERY_LOG_FA.md"},"summary":summary,"completed_families":FAMILIES,"next_authorized_work_backlog":NEXT,"truth_boundaries":{"static_and_persisted_evidence":"HIGH_CONFIDENCE","synthetic_reference_behavior":"PROVEN_ONLY_FOR_FIXED_SYNTHETIC_VECTORS","runtime_result_parity":"NOT_PROVEN","business_owner_acceptance":"NOT_OBSERVED","provider_selection":"NOT_MADE"},"safety":{"database_connections":0,"network_reads_or_writes":0,"operational_records_or_business_values_read":0,"operational_forms_reports_queries_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"credentials_pii_or_raw_business_values_persisted":0},"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())]+[{"name":"builder","path":"scripts/windows/build_varanegar_10h_continuation_handoff_capsule_20260901.py","size_bytes":Path(__file__).stat().st_size,"sha256":sha(Path(__file__))}],"limits":["This capsule transfers documented static knowledge, contracts, synthetic references, tests and checkpoint lineage only.","It does not certify runtime parity, production safety, regulatory correctness, provider suitability or business-owner acceptance.","Any operational UAT requires separate authorization, isolated environment, approved fixtures and evidence receipts."]}
 a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(summary,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
