"""Build non-duplicating Master Data Golden/UAT delta cases."""
from __future__ import annotations
import argparse,collections,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S={"envelope":"artifacts/varanegar_analysis/varanegar_master_data_outcome_envelope_20260829.json","readiness":"artifacts/varanegar_analysis/varanegar_master_data_readiness_delta_20260829.json","master":"artifacts/varanegar_analysis/ui/negin_erp_customer_goods_master_golden_cases_20260827.json","foundation":"artifacts/varanegar_analysis/ui/negin_erp_foundation_context_pricing_golden_cases_20260827.json","extension":"artifacts/varanegar_analysis/ui/varanegar_extension_golden_cases_20260827.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_master_data_readiness_checkpoint_20260829.json"}
F={"MD-QUAR":("master_data.duplicate_quarantine","weak/sentinel duplicate candidate quarantine"),"MD-XW":("master_data.crosswalk_version","typed source namespace and mode-aware crosswalk"),"MD-MERGE":("master_data.reversible_merge","independent approval and reversible reference redirect"),"MD-CHILD":("master_data.structured_child_relations","barcode/supplier/package/batch/DC/contact/accounting child sets"),"MD-ROLE":("master_data.party_role_privacy","customer/supplier/personnel/subscriber role separation and PII minimization")}
CASES=[("AUTH_DENIED","authorization","REJECTED_NO_EFFECT"),("STALE_VERSION","concurrency","REJECTED_NO_EFFECT"),("DUPLICATE_COMMAND","idempotency","ORIGINAL_RECEIPT_ONLY_ONCE"),("AMBIGUOUS_OR_INVALID","validation","QUARANTINED_OR_REJECTED"),("FAIL_AFTER_REDIRECT_OR_OUTBOX","failure_injection","ROLLED_BACK_OR_UNKNOWN_REQUIRES_READBACK"),("PARALLEL_DECISION","concurrency","ONE_VERSIONED_DECISION_WITH_NO_IDENTITY_COLLAPSE"),("SUCCESS","success","COMMITTED_WITH_RECONCILIATION_AND_AUDIT_RECEIPTS")]
SPECIAL={"MD-QUAR":"weak barcode/contact/name/route similarity and sentinels remain quarantined; automatic merge is forbidden","MD-XW":"source system/entity/mode and target type are explicit; manual integer path code is not a route-master identity","MD-MERGE":"all transaction and child references reconcile before an independently approved reversible redirect event","MD-CHILD":"aggregate and structured child-set versions commit atomically or not at all","MD-ROLE":"typed party roles remain separate and receipts contain only opaque hashes, never PII or raw master values"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};old=d["master"]["cases"]+[x for x in d["foundation"]["cases"] if x["target_module"]=="master_data"]+[x for x in d["extension"]["cases"] if x["target_module"]=="master_data"];cases=[]
 for prefix,(surface,focus) in F.items():
  for code,kind,expected in CASES:cases.append({"case_id":f"{prefix}-{code}","surface":surface,"case_kind":kind,"focus":focus,"expected_outcome":expected,"assertions":["CommandId, PayloadHash, ExpectedVersion, CandidateSetHash and PolicyVersion govern replay","aggregate/child/crosswalk/redirect, audit and outbox effects reconcile atomically",SPECIAL[prefix],"no PII, barcode, contact, credential or raw master value is present","source Varanegar and read-only evidence remain untouched"],"status":"DESIGNED_NOT_EXECUTED"})
 summary={"existing_reused_case_count":len(old),"existing_reused_command_count":7,"delta_surface_count":len(F),"delta_case_count":len(cases),"combined_master_data_acceptance_design_count":len(old)+len(cases),"case_count_per_delta_surface":7,"case_kind_counts":dict(sorted(collections.Counter(x["case_kind"] for x in cases).items())),"executed_delta_case_count":0,"passed_runtime_case_count":0,"owner_approved_case_count":0,"merge_executed_count":0,"runtime_master_effect_parity_proven_module_count":0,"command_ready_module_count":0,"pilot_ready_module_count":0,"risk_count":84,"mapped_risk_assignment_count":343,"new_risk_count":0};checks={"sources_pass":all(v["validation"]=="PASS" for v in d.values()),"reuse_114":len(old)==114 and len({x["case_id"] for x in old})==114,"delta_35":len(cases)==35 and all(sum(x["surface"]==surface for x in cases)==7 for surface,_ in F.values()),"unique_ids":len({x["case_id"] for x in cases})==35,"no_old_collision":not ({x["case_id"] for x in cases}&{x["case_id"] for x in old}),"combined_149":summary["combined_master_data_acceptance_design_count"]==149,"all_unexecuted":{x["status"] for x in cases}=={"DESIGNED_NOT_EXECUTED"},"thirteen_contract_modules":d["readiness"]["summary"]["outcome_target_contract_module_count_after"]==13,"runtime_zero":summary["executed_delta_case_count"]==summary["passed_runtime_case_count"]==summary["owner_approved_case_count"]==summary["merge_executed_count"]==summary["runtime_master_effect_parity_proven_module_count"]==summary["command_ready_module_count"]==summary["pilot_ready_module_count"]==0,"base_stable":d["risk"]["summary"]["risk_count"]==84 and d["trace"]["summary"]["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_master_data_golden_uat_cases_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","safety":{"mode":"OFFLINE_SYNTHETIC_DESIGN","database_connections":0,"network_reads_or_writes":0,"master_data_commands_or_forms_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"pii_barcode_contact_or_raw_master_values_read_or_persisted":0},"summary":summary,"reuse_manifest":{"sources":[S["master"],S["foundation"],S["extension"]],"policy":"reuse 114 unique customer/goods/supplier/subscriber cases; do not duplicate them"},"execution_gate":{"environment":"isolated target only","requirements":["synthetic opaque master identities and child relations","steward-approved duplicate, sentinel, crosswalk, privacy and role policies","parallel quarantine/crosswalk/merge decision harness","fault injection at child/redirect/audit/outbox boundaries","full reference reconciliation and merge reversal harness"],"promotion_rule":"all 149 reused plus delta obligations execute with zero unexplained identity/reference difference and owner approval"},"cases":cases,"checks":checks,"failed_checks":failed,"risk_links":["R-002","R-004","R-005","R-006","R-007","R-008","R-010","R-011","R-037","R-038"],"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"confidence":{"design":"HIGH","runtime":"NOT_EXECUTED"},"limits":["These are acceptance designs, not UAT results.","No master, quarantine, crosswalk or merge command was executed.","No PII, barcode, contact or raw master value appears in fixtures or artifacts."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(summary,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
