"""Build the chained checkpoint for the RPT-15 stock report binding slice."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
SOURCES={"contract":"artifacts/varanegar_analysis/domains/stock_report_reference_contract_20260829.json","il":"artifacts/varanegar_analysis/domains/stock_report_query_bindings_20260829.json","catalog":"artifacts/varanegar_analysis/domains/stock_report_sql_catalog_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_25h_gap_checkpoint_20260829.json","il_extractor":"scripts/windows/extract_varanegar_stock_report_query_bindings_20260829.py","catalog_extractor":"scripts/sql/extract_varanegar_stock_report_sql_catalog_20260829.py","contract_builder":"scripts/windows/build_varanegar_stock_report_reference_contract_20260829.py","checkpoint_builder":"scripts/windows/build_varanegar_stock_report_checkpoint_20260829.py","test":"tests/test_varanegar_stock_report_reference_contract.py","doc":"docs/varanegar_reconstruction/STOCK_REFERENCE_REPORT_BINDINGS_AND_RECONCILIATION_20260829_FA.md"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 p=argparse.ArgumentParser();p.add_argument("--output",required=True,type=Path);a=p.parse_args();paths={k:ROOT/v for k,v in SOURCES.items()};missing=[SOURCES[k] for k,x in paths.items() if not x.is_file()]
 if missing:raise AssertionError({"missing":missing})
 contract,il,catalog,previous=(load(paths[k]) for k in("contract","il","catalog","previous"));checks={"chain_source_pass":previous["validation"]=="PASS","all_slice_artifacts_pass":contract["validation"]==il["validation"]==catalog["validation"]=="PASS","ten_query_bindings":contract["summary"]["exact_method_sql_binding_count"]==10,"ten_parameter_sets_match":contract["summary"]["parameter_set_match_count"]==10,"result_parity_not_claimed":contract["summary"]["result_parity_proven_count"]==0,"risk_not_inflated":contract["summary"]["risk_count"]==84,"safe_database_context":catalog["safety"]["database_updateability"]=="READ_ONLY" and catalog["safety"]["can_update"]==0 and catalog["safety"]["denies_data_writes"]==1,"zero_operational_execution":catalog["safety"]["operational_report_or_procedure_executions"]==0 and il["safety"]["assembly_loads_or_executions"]==0}
 failed=sorted(k for k,v in checks.items() if not v);payload={"artifact":"varanegar_stock_report_checkpoint_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","previous_checkpoint":{"path":SOURCES["previous"],"sha256":sha(paths["previous"])},"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":SOURCES[k],"size_bytes":x.stat().st_size,"sha256":sha(x)} for k,x in sorted(paths.items())],"safety":{"operational_report_or_procedure_executions":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"sensitive_values_persisted":0},"confidence":"CONFIRMED_QUERY_BINDING_RESULT_PARITY_UNPROVEN"}
 a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(payload,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(payload["validation"]);return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
