"""Execute deterministic synthetic fixed-asset vectors."""
from __future__ import annotations
import argparse,copy,hashlib,importlib.util,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];REFERENCE=ROOT/"scripts/windows/varanegar_fixed_asset_reference.py"
S={"asset_contract":"artifacts/varanegar_analysis/varanegar_target_erp_fixed_asset_lifecycle_depreciation_contract_20260901.json","asset_checkpoint":"artifacts/varanegar_analysis/varanegar_target_erp_fixed_asset_lifecycle_depreciation_checkpoint_20260901.json","accounting":"artifacts/varanegar_analysis/varanegar_accounting_expert_playbook_contract_20260829.json","semantics":"artifacts/varanegar_analysis/varanegar_target_erp_monetary_quantity_temporal_semantics_contract_20260829.json","fiscal":"artifacts/varanegar_analysis/varanegar_target_erp_fiscal_period_close_reopen_adjustment_lock_contract_20260829.json","tests":"artifacts/varanegar_analysis/varanegar_25h_final_test_result_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def module():s=importlib.util.spec_from_file_location("fa_ref",REFERENCE);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return m
def main():
 p=argparse.ArgumentParser();p.add_argument("--output",required=True,type=Path);a=p.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};m=module();base=m.baseline()
 def changed(**kw):e=copy.deepcopy(base);e.update(kw);return e
 positive=[("POS-CAP",base,"CAPITALIZATION_ACCEPTED_THRESHOLD_DATE_AND_LINEAGE"),("POS-DEPR",changed(operation="DEPRECIATE"),"DEPRECIATION_ACCEPTED_METHOD_PERIOD_PRORATION_AND_BALANCED"),("POS-IMPAIR",changed(operation="IMPAIR"),"IMPAIRMENT_ACCEPTED_TEST_AMOUNT_AND_LINEAGE"),("POS-REVALUE",changed(operation="REVALUE"),"REVALUATION_ACCEPTED_RESERVE_AND_COMPONENT_ALLOCATION"),("POS-TRANSFER",changed(operation="TRANSFER"),"TRANSFER_ACCEPTED_SCOPE_OWNER_AND_VERSION"),("POS-DISPOSE",changed(operation="DISPOSE"),"DISPOSAL_ACCEPTED_PROCEEDS_GAIN_LOSS_AND_DERECOGNITION"),("POS-RECON",changed(operation="RECONCILE"),"ASSET_RECONCILIATION_ACCEPTED_REGISTER_SUBLEDGER_AND_GL")]
 negative=[("NEG-EXTRA",dict(base,extra=True),"SCHEMA_INVALID"),("NEG-SCOPE",changed(scope_current=False),"ASSET_EVENT_REJECTED_IDENTITY_SCOPE_OR_COMPONENT"),("NEG-COMPONENT",changed(component_identity_current=False),"ASSET_EVENT_REJECTED_IDENTITY_SCOPE_OR_COMPONENT"),("NEG-VERSION",changed(expected_version_match=False),"ASSET_EVENT_REJECTED_VERSION_OR_IDEMPOTENCY"),("NEG-IDEMPOTENCY",changed(idempotency_current=False),"ASSET_EVENT_REJECTED_VERSION_OR_IDEMPOTENCY"),("NEG-UNKNOWN",changed(unknown_commit=True),"ASSET_EVENT_UNKNOWN_RECONCILIATION_REQUIRED"),("NEG-BLOCK",changed(blocking_unknown=True),"MANUAL_REVIEW_REQUIRED_BLOCKING_UNKNOWN"),("NEG-NBV",changed(nbv_invariants_current=False),"ASSET_INVARIANT_REJECTED_NEGATIVE_NBV_OR_EXCESS_DEPRECIATION"),("NEG-CAP-LINEAGE",changed(acquisition_cip_lineage_current=False),"CAPITALIZATION_REJECTED_THRESHOLD_CIP_POLICY_OR_PERIOD"),("NEG-CAP-BOOK",changed(book_method_policy_current=False),"CAPITALIZATION_REJECTED_THRESHOLD_CIP_POLICY_OR_PERIOD"),("NEG-CAP-PERIOD",changed(period_current=False),"CAPITALIZATION_REJECTED_THRESHOLD_CIP_POLICY_OR_PERIOD"),("NEG-DEPR-METHOD",changed(operation="DEPRECIATE",book_method_policy_current=False),"DEPRECIATION_REJECTED_METHOD_LIFE_RESIDUAL_PERIOD_OR_ROUNDING"),("NEG-DEPR-INPUT",changed(operation="DEPRECIATE",depreciation_inputs_current=False),"DEPRECIATION_REJECTED_METHOD_LIFE_RESIDUAL_PERIOD_OR_ROUNDING"),("NEG-IMPAIR",changed(operation="IMPAIR",impairment_lineage_current=False),"IMPAIRMENT_REJECTED_TEST_LINEAGE_OR_PERIOD"),("NEG-REVALUE",changed(operation="REVALUE",revaluation_reserve_current=False),"REVALUATION_REJECTED_RESERVE_COMPONENT_OR_PERIOD"),("NEG-TRANSFER",changed(operation="TRANSFER",transfer_scope_current=False),"TRANSFER_REJECTED_SCOPE_OWNER_OR_VERSION"),("NEG-DISPOSE",changed(operation="DISPOSE",disposal_lineage_approval_current=False),"DISPOSAL_REJECTED_PERIOD_LINEAGE_OR_APPROVAL"),("NEG-DISPOSE-PERIOD",changed(operation="DISPOSE",period_current=False),"DISPOSAL_REJECTED_PERIOD_LINEAGE_OR_APPROVAL"),("NEG-RECON",changed(operation="RECONCILE",register_gl_reconciled=False),"ASSET_RECONCILIATION_REJECTED_REGISTER_DEPRECIATION_OR_GL")]
 def run(vs):
  r=[]
  for i,e,x in vs:
   y=m.evaluate(e);r.append({"vector_id":i,"expected":x,"actual":y,"status":"PASS" if y==x else "FAIL"})
  return r
 pr=run(positive);nr=run(negative);allr=pr+nr;official=d["tests"];cs=d["asset_contract"]["summary"]
 s={"reference_evaluator_implementation_count":1,"positive_vector_count":len(pr),"positive_pass_count":sum(x["status"]=="PASS" for x in pr),"negative_vector_count":len(nr),"negative_pass_count":sum(x["status"]=="PASS" for x in nr),"total_vector_count":len(allr),"total_pass_count":sum(x["status"]=="PASS" for x in allr),"distinct_typed_outcome_count":len({x["actual"] for x in allr}),"fixed_asset_gate_count":cs["gate_count"],"fixed_asset_module_gate_assignment_count":cs["module_gate_assignment_count"],"operational_fixed_asset_tax_depreciation_or_accounting_implementation_count":0,"operational_asset_cost_depreciation_impairment_value_or_ledger_read_count":0,"capitalize_depreciate_impair_revalue_transfer_dispose_or_reconcile_run_count":0,"accepted_operational_receipt_count":0,"command_ready_module_count":0,"pilot_ready_module_count":0,"design_lower_bound_before_reference_evaluator":1404,"design_lower_bound_after_reference_evaluator":1404,"official_test_file_count":official["runner"]["test_file_count"],"official_passed_test_count":official["runner"]["passed_test_count"],"risk_count":d["risk"]["summary"]["risk_count"],"mapped_risk_assignment_count":d["trace"]["summary"]["mapped_risk_assignment_count"],"new_risk_count":0}
 checks={"sources_pass":all(d[k].get("validation")=="PASS" for k in ("asset_contract","asset_checkpoint","accounting","semantics","fiscal","tests")),"positive_7_of_7":s["positive_vector_count"]==s["positive_pass_count"]==7,"negative_19_of_19":s["negative_vector_count"]==s["negative_pass_count"]==19,"total_26_of_26":s["total_vector_count"]==s["total_pass_count"]==26,"distinct_outcomes_at_least_19":s["distinct_typed_outcome_count"]>=19,"coverage_24_336":(s["fixed_asset_gate_count"],s["fixed_asset_module_gate_assignment_count"])==(24,336),"operational_and_readiness_zero":all(s[k]==0 for k in ("operational_fixed_asset_tax_depreciation_or_accounting_implementation_count","operational_asset_cost_depreciation_impairment_value_or_ledger_read_count","capitalize_depreciate_impair_revalue_transfer_dispose_or_reconcile_run_count","accepted_operational_receipt_count","command_ready_module_count","pilot_ready_module_count")),"non_additive_1404":s["design_lower_bound_before_reference_evaluator"]==s["design_lower_bound_after_reference_evaluator"]==1404,"official_tests_pass":official["validation"]=="PASS" and official["runner"]["bootstrap_excluded_test_file_count"]==0,"base_stable":s["risk_count"]==84 and s["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_target_erp_fixed_asset_synthetic_reference_evaluator_contract_20260901","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","scope":{"mode":"pure_synthetic_fixed_asset_reference_evaluator","continuation_complete":False,"operational_asset_cost_depreciation_impairment_value_or_ledger_read":False},"safety":{"database_connections":0,"network_reads_or_writes":0,"operational_asset_cost_depreciation_impairment_value_or_ledger_reads":0,"capitalize_depreciate_impair_revalue_transfer_dispose_or_reconcile_actions_executed":0,"operational_forms_reports_queries_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"credentials_pii_or_raw_business_values_read_or_persisted":0},"summary":s,"positive_results":pr,"negative_results":nr,"outcome_precedence":["SCHEMA","SCOPE_COMPONENT","VERSION_IDEMPOTENCY","UNKNOWN_COMMIT","BLOCKING_UNKNOWN","NBV_INVARIANT","OPERATION_POLICY_PERIOD_LINEAGE","RECONCILIATION","ACCEPTED"],"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())]+[{"name":"reference_evaluator","path":REFERENCE.relative_to(ROOT).as_posix(),"size_bytes":REFERENCE.stat().st_size,"sha256":sha(REFERENCE)},{"name":"builder","path":"scripts/windows/build_varanegar_target_erp_fixed_asset_synthetic_reference_evaluator_contract_20260901.py","size_bytes":Path(__file__).stat().st_size,"sha256":sha(Path(__file__))}],"limits":["Only fixed synthetic booleans and operation labels were evaluated.","No operational asset cost depreciation impairment tax value or ledger was used.","Operational capitalization depreciation impairment revaluation transfer disposal reconciliation and readiness remain blocked."]}
 a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(s,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
