"""Build evidence-first integration/migration expert playbooks."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S={"envelope":"artifacts/varanegar_analysis/varanegar_integration_migration_outcome_envelope_20260829.json","golden":"artifacts/varanegar_analysis/varanegar_integration_migration_golden_uat_cases_20260829.json","pos":"artifacts/varanegar_analysis/ui/negin_erp_pos_receipt_replication_contract_20260827.json","sale":"artifacts/varanegar_analysis/domains/ngt_sale_replication_boundary_20260829.json","payment":"artifacts/varanegar_analysis/domains/ngt_payment_replication_runtime_boundary_20260829.json","compensation":"artifacts/varanegar_analysis/domains/ngt_replication_compensation_boundary_20260829.json","transport":"artifacts/varanegar_analysis/domains/rule_replication_transport_boundary_20260828.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_integration_migration_golden_uat_checkpoint_20260829.json"}
COMMON=["capture CommandId, package/capture identity, content/contract hash, source watermark, sequence, previous receipt hash, center/scope and deadline without payload or business values","verify binary/evidence/policy/schema hashes and stop on drift","read staging, item, effect, crosswalk, reconciliation, acknowledgement, compensation and quarantine receipts separately","compare requested, transported, applied, reconciled and acknowledged states; transport completion is not business success","classify NATURAL_BEHAVIOR, DATA_DEBT, BUG or UNPROVEN","quarantine unknown, forked, unordered, unauthenticated or cross-scope outcomes before retry","stop before replay, acknowledgement synthesis, crosswalk repair, compensation, import resume or source write-back","design isolated signed-package and fault-injection reproduction when the boundary remains unproven"]
BASE=[("IM-PB-01","transport completed but package authentication or center scope is unproven","transport success versus trusted package acceptance","verify content signature, contract hash and target scope before any apply or acknowledgement",["R-006","R-023","R-036"]),("IM-PB-02","duplicate, gap, fork or out-of-order package is observed","sequence and idempotent receipt","compare sequence/previous hash and original receipt; never advance over a gap or create a second acknowledgement",["R-005","R-007","R-034"]),("IM-PB-03","database effect may have committed but external acknowledgement failed","unknown cross-boundary outcome","read every durable local receipt and external acknowledgement before retry; keep UNKNOWN_BLOCKING",["R-005","R-007","R-023"]),("IM-PB-04","POS batch has accepted and failed children","per-receipt effects and batch fold","retain reconciled successes, quarantine every other item and never derive batch success from the last child",["R-005","R-008","R-036"]),("IM-PB-05","NGT history duplicates, target is missing or crosswalk differs","history versus target-effect identity","separate multiple histories to one target from multiple target effects; missing or conflicting crosswalk is blocking",["R-002","R-029","R-043"]),("IM-PB-06","compensation is requested or repeated","append-only reversal linked to original receipt","prove the original outcome and blockers, issue one idempotent compensation receipt and retain both histories",["R-005","R-007","R-029"]),("IM-PB-07","migration rerun differs or a later slice begins after partial failure","snapshot consistency and ordered slice checkpoints","compare capture/mapping/importer hashes, block mixed snapshots and resume only after the prior slice reconciles",["R-002","R-029","R-036"])]
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 p=argparse.ArgumentParser();p.add_argument("--output",required=True,type=Path);a=p.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};play=[{"id":i,"incident":inc,"focus":focus,"steps":COMMON+[extra],"stop_conditions":["evidence, signature or policy hash drift","write, replay, ack, repair, compensation or import required","owner/cutover authority required","raw package or sensitive values would be persisted"],"risks":risks,"runtime_diagnosis":"NOT_PERFORMED"} for i,inc,focus,extra,risks in BASE];known={x["id"] for x in d["risk"]["risks"]};summary={"playbook_count":len(play),"minimum_step_count":min(len(x["steps"]) for x in play),"command_contract_count":d["envelope"]["summary"]["command_contract_count"],"combined_acceptance_design_count":d["golden"]["summary"]["combined_integration_acceptance_design_count"],"runtime_incidents_diagnosed_count":0,"repairs_acks_compensations_or_imports_performed_count":0,"owner_approved_count":0,"risk_count":84,"mapped_risk_assignment_count":343,"new_risk_count":0}
 checks={"validated_sources_pass":all(d[k]["validation"]=="PASS" for k in ["envelope","golden","pos","sale","payment","compensation","risk","trace","previous"]),"transport_structural_input":d["transport"]["summary"]["target_method_contract_count"]==49,"seven_playbooks":len(play)==7,"nine_steps":all(len(x["steps"])==9 for x in play),"four_way":all("NATURAL_BEHAVIOR, DATA_DEBT, BUG or UNPROVEN" in x["steps"][4] for x in play),"risks_exist":all(r in known for x in play for r in x["risks"]),"scope":summary["command_contract_count"]==6 and summary["combined_acceptance_design_count"]==69,"unknown_and_migration":any("UNKNOWN_BLOCKING" in x["steps"][-1] for x in play) and any("ordered slice checkpoints" in x["focus"] for x in play),"runtime_zero":summary["runtime_incidents_diagnosed_count"]==summary["repairs_acks_compensations_or_imports_performed_count"]==summary["owner_approved_count"]==0,"base_stable":d["risk"]["summary"]["risk_count"]==84 and d["trace"]["summary"]["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_integration_migration_expert_playbook_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","safety":{"mode":"OFFLINE_EVIDENCE_SYNTHESIS","database_connections":0,"network_reads_or_writes":0,"packages_or_transfers_executed":0,"commands_forms_reports_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"sensitive_values_or_payloads_persisted":0},"summary":summary,"playbooks":play,"diagnostic_result_contract":{"allowed":["NATURAL_BEHAVIOR","DATA_DEBT","BUG","UNPROVEN"],"requires_named_incident_evidence":True,"replay_ack_repair_compensation_or_import_is_separate_authorized_work":True},"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"confidence":{"structure":"HIGH","incident_diagnosis":"REQUIRES_INCIDENT_EVIDENCE"},"limits":["No named incident was diagnosed.","No package replay, acknowledgement, compensation, repair or import was executed.","No production-current transport or cutover state is claimed."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(summary,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
