from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S={"boundary":"artifacts/varanegar_analysis/varanegar_identity_integration_transaction_mutation_boundary_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_24h_continuation_consolidated_checkpoint_20260829.json","builder":"scripts/windows/build_varanegar_identity_integration_transaction_mutation_boundary_20260829.py","checkpoint_builder":"scripts/windows/build_varanegar_identity_integration_transaction_mutation_checkpoint_20260829.py","test":"tests/test_varanegar_identity_integration_transaction_mutation_boundary.py","checkpoint_test":"tests/test_varanegar_identity_integration_transaction_mutation_checkpoint.py","doc":"docs/varanegar_reconstruction/IDENTITY_INTEGRATION_TRANSACTION_MUTATION_BOUNDARY_20260829_FA.md"}
def L(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def H(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();p={k:ROOT/v for k,v in S.items()};d=L(p["boundary"]);prev=L(p["previous"]);s=d["summary"];checks={"sources_pass":d["validation"]==prev["validation"]=="PASS","twelve_target":s["command_count"]==s["command_with_target_transaction_design_count"]==s["command_with_target_mutation_effect_design_count"]==12,"legacy_static_zero":s["command_with_complete_legacy_static_proof_count"]==0,"runtime_zero":s["implemented_command_count"]==s["runtime_atomicity_proven_command_count"]==s["runtime_effect_parity_proven_command_count"]==0,"base_stable":s["risk_count"]==84 and s["mapped_risk_assignment_count"]==343,"safety_zero":set(v for k,v in d["safety"].items() if k!="mode")=={0}};failed=sorted(k for k,v in checks.items() if not v);out={"artifact":"varanegar_identity_integration_transaction_mutation_checkpoint_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","previous_checkpoint":{"path":S["previous"],"sha256":H(p["previous"])},"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":H(v)} for k,v in sorted(p.items())],"safety":{"database_connections":0,"operational_actions":0,"data_mutations":0}};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
