"""Chain the target ERP observability/SLO/incident evidence contract."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
S={"contract":"artifacts/varanegar_analysis/varanegar_target_erp_observability_slo_incident_evidence_contract_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_target_erp_release_promotion_change_rollback_evidence_checkpoint_20260829.json","builder":"scripts/windows/build_varanegar_target_erp_observability_slo_incident_evidence_contract_20260829.py","checkpoint_builder":"scripts/windows/build_varanegar_target_erp_observability_slo_incident_evidence_checkpoint_20260829.py","test":"tests/test_varanegar_target_erp_observability_slo_incident_evidence_contract.py","checkpoint_test":"tests/test_varanegar_target_erp_observability_slo_incident_evidence_checkpoint.py","doc":"docs/varanegar_reconstruction/TARGET_ERP_OBSERVABILITY_SLO_INCIDENT_EVIDENCE_20260829_FA.md"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 p=argparse.ArgumentParser();p.add_argument("--output",required=True,type=Path);a=p.parse_args();paths={k:ROOT/v for k,v in S.items()};c=load(paths["contract"]);prev=load(paths["previous"]);s=c["summary"]
 checks={"sources_pass":c["validation"]==prev["validation"]=="PASS","coverage_14_168_168":(s["module_count"],s["module_signal_assignment_count"],s["module_stage_assignment_count"])==(14,168,168),"failure_gate_role_coverage":(s["module_failure_assignment_count"],s["module_gate_assignment_count"],s["module_role_assignment_count"])==(196,280,84),"runtime_and_readiness_zero":s["telemetry_source_read_or_queried_count"]==s["sli_implemented_count"]==s["slo_approved_count"]==s["alert_route_activated_count"]==s["runtime_incident_observed_count"]==s["incident_closed_count"]==s["command_ready_module_count"]==s["pilot_ready_module_count"]==0,"base_stable":s["risk_count"]==84 and s["mapped_risk_assignment_count"]==343 and s["design_lower_bound_after_observability_contract"]==1404,"safety_zero":set(c["safety"].values())=={0}};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_target_erp_observability_slo_incident_evidence_checkpoint_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","previous_checkpoint":{"path":S["previous"],"sha256":sha(paths["previous"])},"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"safety":{"database_connections":0,"network_reads_or_writes":0,"telemetry_metrics_logs_traces_or_runtime_health_samples_read_or_queried":0,"alerts_sent_or_incidents_created":0,"operational_forms_reports_queries_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"credentials_endpoints_pii_or_raw_business_values_read_or_persisted":0}}
 a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
