"""Build the non-duplicating Pricing Rules Golden/UAT delta."""
from __future__ import annotations
import argparse,collections,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S={"envelope":"artifacts/varanegar_analysis/varanegar_pricing_rule_outcome_envelope_20260829.json","readiness":"artifacts/varanegar_analysis/varanegar_pricing_rule_readiness_delta_20260829.json","existing":"artifacts/varanegar_analysis/ui/negin_erp_foundation_context_pricing_golden_cases_20260827.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_pricing_rule_readiness_checkpoint_20260829.json"}
FAMILIES={"PR-PRI":{"surface":"pricing_rules.contextual_price.change_priority","focus":"deterministic precedence and overlap"},"PR-VAL":{"surface":"pricing_rules.discount_rule.validate_or_compile_condition","focus":"side-effect-free allowlisted DSL compile/explain"},"PR-LIN":{"surface":"pricing_rules.linear_discount.allocate_and_save","focus":"atomic id allocation and append"},"PR-PUB":{"surface":"pricing_rules.publish_version_and_replicate","focus":"atomic local publish plus asynchronous idempotent replication"}}
CASES=[("AUTH_DENIED","authorization","REJECTED_NO_EFFECT"),("STALE_VERSION","concurrency","REJECTED_NO_EFFECT"),("DUPLICATE_COMMAND","idempotency","ORIGINAL_RECEIPT_ONLY_ONCE"),("INVALID_OR_AMBIGUOUS","validation","REJECTED_NO_EFFECT"),("FAIL_AFTER_LOCAL_STAGE","failure_injection","ROLLED_BACK_OR_UNKNOWN_REQUIRES_READBACK"),("PARALLEL_OR_RETRY","concurrency","UNIQUE_DETERMINISTIC_OUTCOME"),("SUCCESS","success","EXPECTED_TYPED_RECEIPT")]
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 p=argparse.ArgumentParser();p.add_argument("--output",required=True,type=Path);a=p.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};old=[x for x in d["existing"]["cases"] if x.get("target_module")=="pricing_rules"]
 special={"PR-PRI":"two equal legacy priorities resolve by the approved stable tuple or reject; never by iteration order","PR-VAL":"compile returns no aggregate, audit, outbox or business-row mutation and never stores executable SQL","PR-LIN":"parallel writers receive unique identities and exactly one aggregate version each; MAX(Id)+1 is forbidden","PR-PUB":"local publication is not repeated; unknown transport is quarantined and retried from the same outbox identity"};cases=[]
 for prefix,profile in FAMILIES.items():
  for code,kind,expected in CASES:cases.append({"case_id":f"{prefix}-{code}","surface":profile["surface"],"case_kind":kind,"focus":profile["focus"],"expected_outcome":expected,"assertions":["authorization and scope are rechecked in the application service","CommandId, PayloadHash and ExpectedVersion govern replay","aggregate/audit/outbox effects reconcile exactly",special[prefix],"source Varanegar and read-only evidence remain untouched"],"status":"DESIGNED_NOT_EXECUTED"})
 old_commands=collections.Counter(x["command"] for x in old);summary={"existing_reused_case_count":len(old),"existing_reused_command_count":len(old_commands),"delta_surface_count":len(FAMILIES),"delta_case_count":len(cases),"combined_pricing_acceptance_design_count":len(old)+len(cases),"case_count_per_delta_surface":7,"case_kind_counts":dict(sorted(collections.Counter(x["case_kind"] for x in cases).items())),"executed_delta_case_count":0,"passed_runtime_case_count":0,"owner_approved_case_count":0,"runtime_retry_idempotency_proven_module_count":0,"command_ready_module_count":0,"pilot_ready_module_count":0,"risk_count":84,"mapped_risk_assignment_count":343,"new_risk_count":0}
 checks={"sources_pass":all(x["validation"]=="PASS" for x in d.values()),"reuse_64_four_commands":len(old)==64 and len(old_commands)==4 and set(old_commands.values())=={16},"delta_28":len(cases)==28 and all(sum(x["surface"]==f["surface"] for x in cases)==7 for f in FAMILIES.values()),"unique_ids":len({x["case_id"] for x in cases})==28,"no_duplicate_old_ids":not ({x["case_id"] for x in cases}&{x["case_id"] for x in old}),"combined_92":summary["combined_pricing_acceptance_design_count"]==92,"all_unexecuted":{x["status"] for x in cases}=={"DESIGNED_NOT_EXECUTED"},"eight_contract_modules":d["readiness"]["summary"]["outcome_target_contract_module_count_after"]==8,"runtime_zero":summary["executed_delta_case_count"]==summary["passed_runtime_case_count"]==summary["owner_approved_case_count"]==summary["runtime_retry_idempotency_proven_module_count"]==summary["command_ready_module_count"]==summary["pilot_ready_module_count"]==0,"base_stable":d["risk"]["summary"]["risk_count"]==84 and d["trace"]["summary"]["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_pricing_rule_golden_uat_cases_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","safety":{"mode":"OFFLINE_SYNTHETIC_DESIGN","database_connections":0,"commands_forms_reports_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"sensitive_values_or_raw_rule_text_persisted":0},"summary":summary,"reuse_manifest":{"source":S["existing"],"commands":dict(sorted(old_commands.items())),"policy":"reuse the 64 existing save/delete cases; do not duplicate them"},"execution_gate":{"environment":"isolated target only","requirements":["synthetic rule ASTs and contexts","parallel-writer harness","fault injection at aggregate/audit/outbox/transport boundaries","legacy/target explain and effect comparator","owner-approved precedence and qualification policy"],"promotion_rule":"all 92 reused plus delta obligations execute with zero unexplained durable-effect difference and owner approval"},"cases":cases,"checks":checks,"failed_checks":failed,"risk_links":["R-002","R-005","R-006","R-007","R-008","R-023","R-028","R-034","R-036","R-043"],"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"confidence":{"design":"HIGH","runtime":"NOT_EXECUTED"},"limits":["These are acceptance designs, not UAT results.","No rule or replication command was executed.","The four publication cases are durable-effect obligations, not a claim of a distinct legacy UI command."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(summary,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
