"""Build additive configuration evidence and risk traceability."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S={"envelope":"artifacts/varanegar_analysis/varanegar_configuration_outcome_envelope_20260829.json","readiness":"artifacts/varanegar_analysis/varanegar_configuration_readiness_delta_20260829.json","golden":"artifacts/varanegar_analysis/varanegar_configuration_golden_uat_cases_20260829.json","playbook":"artifacts/varanegar_analysis/varanegar_configuration_expert_playbook_20260829.json","precedence":"artifacts/varanegar_analysis/domains/configuration_precedence_boundary_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_configuration_expert_playbook_checkpoint_20260829.json"}
E=["CF-E-01-version-precedence-rollout-envelope","CF-E-02-readiness-delta","CF-E-03-golden-uat-delta","CF-E-04-expert-playbook","CF-E-05-static-precedence-consumer-boundary"]
REQ=[("CF-RQ-01","typed allowlisted configuration schema"),("CF-RQ-02","immutable version lifecycle and expected-version concurrency"),("CF-RQ-03","deterministic scope and precedence tuple"),("CF-RQ-04","typed INHERIT/EXPLICIT_NULL/VALUE semantics"),("CF-RQ-05","removed-reference quarantine"),("CF-RQ-06","vault reference with no secret value exposure"),("CF-RQ-07","atomic version pointer audit and outbox"),("CF-RQ-08","per-consumer rollout acknowledgement"),("CF-RQ-09","rollback by new immutable version"),("CF-RQ-10","effective value ResolutionTrace and read-back before retry")]
MODULES=["configuration","organization_context","identity_authorization","sales","accounting","integration_migration"]
RISKS=["R-002","R-005","R-006","R-007","R-008","R-023","R-031","R-034","R-036"]
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 p=argparse.ArgumentParser();p.add_argument("--output",required=True,type=Path);a=p.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};known={x["id"] for x in d["risk"]["risks"]};ml=[{"evidence":e,"module":m,"relationship":"CONFIGURATION_DESIGN_EVIDENCE"} for e in E for m in MODULES];rl=[{"evidence":e,"risk":r,"relationship":"MITIGATION_DESIGN_NOT_CLOSURE"} for e in E for r in RISKS];req=[{"id":i,"requirement":text,"status":"DESIGNED_NOT_RUNTIME_PROVEN","evidence":E} for i,text in REQ]
 summary={"configuration_evidence_count":len(E),"requirement_contract_delta_count":len(req),"module_evidence_link_count":len(ml),"risk_evidence_link_count":len(rl),"unique_linked_risk_count":len(RISKS),"base_risk_count":d["risk"]["summary"]["risk_count"],"base_mapped_risk_assignment_count":d["trace"]["summary"]["mapped_risk_assignment_count"],"new_risk_count":0,"runtime_readiness_promotions":0};checks={"sources_pass":all(v["validation"]=="PASS" for v in d.values()),"five_ten":len(E)==5 and len(req)==10,"links":len(ml)==30 and len(rl)==45 and len(RISKS)==9,"risks_exist":set(RISKS)<=known,"scope":d["envelope"]["summary"]["command_contract_count"]==5 and d["golden"]["summary"]["combined_configuration_acceptance_design_count"]==82 and d["playbook"]["summary"]["playbook_count"]==7,"base_stable":summary["base_risk_count"]==84 and summary["base_mapped_risk_assignment_count"]==343,"no_promotion":summary["new_risk_count"]==summary["runtime_readiness_promotions"]==0};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_configuration_traceability_delta_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","safety":{"mode":"OFFLINE_EVIDENCE_SYNTHESIS","database_connections":0,"network_reads_or_writes":0,"configuration_commands_or_forms_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"secret_or_business_values_read_or_persisted":0},"summary":summary,"policy":{"relationship":"ADDITIVE_EVIDENCE_DELTA_ONLY","base_registers_unchanged":True,"no_risk_closure_or_runtime_promotion":True},"evidence":E,"requirements":req,"module_links":ml,"risk_links":rl,"linked_existing_risks":RISKS,"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"confidence":{"design_trace":"HIGH","runtime_effective_value_and_rollout_parity":"UNPROVEN"},"limits":["Risk links do not close risks.","The 84-risk and 343-assignment base registers remain unchanged.","No runtime configuration or incident result is claimed."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(summary,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
