"""Build additive Organization Context evidence and risk traceability."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S={"envelope":"artifacts/varanegar_analysis/varanegar_organization_context_outcome_envelope_20260829.json","readiness":"artifacts/varanegar_analysis/varanegar_organization_context_readiness_delta_20260829.json","golden":"artifacts/varanegar_analysis/varanegar_organization_context_golden_uat_cases_20260829.json","playbook":"artifacts/varanegar_analysis/varanegar_organization_context_expert_playbook_20260829.json","date":"artifacts/varanegar_analysis/domains/ngt_operation_date_boundary_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_organization_context_expert_playbook_checkpoint_20260829.json"}
E=["OC-E-01-context-snapshot-date-envelope","OC-E-02-readiness-delta","OC-E-03-golden-uat-delta","OC-E-04-expert-playbook","OC-E-05-static-operation-date-boundary"]
REQ=[("OC-RQ-01","immutable versioned ContextSnapshot per command"),("OC-RQ-02","separate operational and fiscal year lifecycle"),("OC-RQ-03","same-scope active DC sale-office stock ship and account relation"),("OC-RQ-04","typed event boundary selector and server-clock date concepts"),("OC-RQ-05","missing or null boundary rejects or quarantines without ambient default"),("OC-RQ-06","server-side authorization for context and operation-date changes"),("OC-RQ-07","atomic context version pointer audit and outbox"),("OC-RQ-08","narrow special-order exception with other consumers preserved"),("OC-RQ-09","retirement preserves historical reference lineage"),("OC-RQ-10","validation trace and immutable read-back before retry")]
MODULES=["organization_context","platform","identity_authorization","configuration","sales","inventory","accounting"]
RISKS=["R-002","R-005","R-006","R-007","R-008","R-023","R-024","R-033","R-034"]
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};known={x["id"] for x in d["risk"]["risks"]};ml=[{"evidence":e,"module":m,"relationship":"ORGANIZATION_CONTEXT_DESIGN_EVIDENCE"} for e in E for m in MODULES];rl=[{"evidence":e,"risk":r,"relationship":"MITIGATION_DESIGN_NOT_CLOSURE"} for e in E for r in RISKS];req=[{"id":i,"requirement":text,"status":"DESIGNED_NOT_RUNTIME_PROVEN","evidence":E} for i,text in REQ]
 summary={"organization_context_evidence_count":len(E),"requirement_contract_delta_count":len(req),"module_evidence_link_count":len(ml),"risk_evidence_link_count":len(rl),"unique_linked_risk_count":len(RISKS),"base_risk_count":d["risk"]["summary"]["risk_count"],"base_mapped_risk_assignment_count":d["trace"]["summary"]["mapped_risk_assignment_count"],"new_risk_count":0,"runtime_readiness_promotions":0};checks={"sources_pass":all(v["validation"]=="PASS" for v in d.values()),"five_ten":len(E)==5 and len(req)==10,"links":len(ml)==35 and len(rl)==45 and len(RISKS)==9,"risks_exist":set(RISKS)<=known,"scope":d["envelope"]["summary"]["command_contract_count"]==6 and d["golden"]["summary"]["combined_organization_context_acceptance_design_count"]==99 and d["playbook"]["summary"]["playbook_count"]==7,"date_boundary_pinned":d["date"]["summary"]["selected_method_count"]==643 and d["date"]["summary"]["sql_consumer_count"]==11,"base_stable":summary["base_risk_count"]==84 and summary["base_mapped_risk_assignment_count"]==343,"no_promotion":summary["new_risk_count"]==summary["runtime_readiness_promotions"]==0};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_organization_context_traceability_delta_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","safety":{"mode":"OFFLINE_EVIDENCE_SYNTHESIS","database_connections":0,"network_reads_or_writes":0,"organization_context_commands_or_forms_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"business_values_read_or_persisted":0},"summary":summary,"policy":{"relationship":"ADDITIVE_EVIDENCE_DELTA_ONLY","base_registers_unchanged":True,"no_risk_closure_or_runtime_promotion":True},"evidence":E,"requirements":req,"module_links":ml,"risk_links":rl,"linked_existing_risks":RISKS,"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"confidence":{"design_trace":"HIGH","runtime_context_and_date_parity":"UNPROVEN"},"limits":["Risk links do not close risks.","The 84-risk and 343-assignment base registers remain unchanged.","No runtime context, date or incident result is claimed."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(summary,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
