"""Build additive identity/authorization evidence and risk traceability."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S={"envelope":"artifacts/varanegar_analysis/varanegar_identity_authorization_outcome_envelope_20260829.json","readiness":"artifacts/varanegar_analysis/varanegar_identity_authorization_readiness_delta_20260829.json","golden":"artifacts/varanegar_analysis/varanegar_identity_authorization_golden_uat_cases_20260829.json","playbook":"artifacts/varanegar_analysis/varanegar_identity_authorization_expert_playbook_20260829.json","effective":"artifacts/varanegar_analysis/domains/ngt_authorization_effective_boundary_20260828.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_identity_authorization_expert_playbook_checkpoint_20260829.json"}
E=["IA-E-01-decision-session-outcome-envelope","IA-E-02-readiness-delta","IA-E-03-golden-uat-delta","IA-E-04-expert-playbook","IA-E-05-static-endpoint-owner-scope-boundary"]
REQ=[("IA-RQ-01","deny-first versioned capability policy"),("IA-RQ-02","opaque principal reference and no identity/credential persistence"),("IA-RQ-03","explicit deny precedence over direct group inherited and admin allow"),("IA-RQ-04","separate application owner action and data scopes"),("IA-RQ-05","owner-filtered permission repository and decision trace"),("IA-RQ-06","mechanical endpoint declaration plus application-service authorization"),("IA-RQ-07","atomic assignment or revocation audit outbox and session epoch"),("IA-RQ-08","SoD no-self-grant and independent privileged approval"),("IA-RQ-09","time-bounded non-renewing break-glass lifecycle"),("IA-RQ-10","immutable read-back receipt before retry and stale-token denial")]
MODULES=["identity_authorization","platform","organization_context","configuration","sales","accounting","integration_migration"]
RISKS=["R-002","R-003","R-004","R-006","R-007","R-024","R-057","R-058","R-059"]
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};known={x["id"] for x in d["risk"]["risks"]};ml=[{"evidence":e,"module":m,"relationship":"IDENTITY_AUTHORIZATION_DESIGN_EVIDENCE"} for e in E for m in MODULES];rl=[{"evidence":e,"risk":r,"relationship":"MITIGATION_DESIGN_NOT_CLOSURE"} for e in E for r in RISKS];req=[{"id":i,"requirement":text,"status":"DESIGNED_NOT_RUNTIME_PROVEN","evidence":E} for i,text in REQ]
 summary={"identity_authorization_evidence_count":len(E),"requirement_contract_delta_count":len(req),"module_evidence_link_count":len(ml),"risk_evidence_link_count":len(rl),"unique_linked_risk_count":len(RISKS),"base_risk_count":d["risk"]["summary"]["risk_count"],"base_mapped_risk_assignment_count":d["trace"]["summary"]["mapped_risk_assignment_count"],"new_risk_count":0,"runtime_readiness_promotions":0};checks={"validated_sources_pass":all(d[k]["validation"]=="PASS" for k in ["envelope","readiness","golden","playbook","risk","trace","previous"]),"five_ten":len(E)==5 and len(req)==10,"links":len(ml)==35 and len(rl)==45 and len(RISKS)==9,"risks_exist":set(RISKS)<=known,"scope":d["envelope"]["summary"]["command_contract_count"]==6 and d["golden"]["summary"]["combined_identity_acceptance_design_count"]==226 and d["playbook"]["summary"]["playbook_count"]==7,"static_boundary_pinned":d["effective"]["summary"]["mutating_endpoint_without_named_manual_authorization_decision_signal_count"]==38 and d["effective"]["summary"]["admin_role_short_circuits_base_authorization"] is True,"base_stable":summary["base_risk_count"]==84 and summary["base_mapped_risk_assignment_count"]==343,"no_promotion":summary["new_risk_count"]==summary["runtime_readiness_promotions"]==0};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_identity_authorization_traceability_delta_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","safety":{"mode":"OFFLINE_EVIDENCE_SYNTHESIS","database_connections":0,"network_reads_or_writes":0,"identity_or_authorization_commands_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"identity_values_credentials_or_raw_grants_read_or_persisted":0},"summary":summary,"policy":{"relationship":"ADDITIVE_EVIDENCE_DELTA_ONLY","base_registers_unchanged":True,"no_risk_closure_or_runtime_promotion":True},"evidence":E,"requirements":req,"module_links":ml,"risk_links":rl,"linked_existing_risks":RISKS,"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"confidence":{"design_trace":"HIGH","effective_runtime_grant_scope_and_session_parity":"UNPROVEN"},"limits":["Risk links do not close risks.","The 84-risk and 343-assignment base registers remain unchanged.","No effective identity, grant, authorization decision or runtime incident result is claimed."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(summary,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
