"""Checkpoint the P4 final export evidence-gap status."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
S={"matrix":"artifacts/varanegar_analysis/varanegar_p4_final_evidence_gap_status_matrix_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_p4_assertion_effect_family_gap_checkpoint_20260829.json","builder":"scripts/windows/build_varanegar_p4_final_evidence_gap_status_matrix_20260829.py","checkpoint_builder":"scripts/windows/build_varanegar_p4_final_evidence_gap_status_checkpoint_20260829.py","test":"tests/test_varanegar_p4_final_evidence_gap_status_matrix.py","checkpoint_test":"tests/test_varanegar_p4_final_evidence_gap_status_checkpoint.py","doc":"docs/varanegar_reconstruction/P4_FINAL_EVIDENCE_GAP_STATUS_MATRIX_20260829_FA.md"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};m=load(paths["matrix"]);prev=load(paths["previous"]);s=m["summary"];checks={"sources_pass":m["validation"]==prev["validation"]=="PASS","three_21":s["p4_status_packet_count"]==3 and s["p4_case_count"]==21,"packetized_not_disposed":s["analysis_packetization_complete_count"]==3 and s["semantic_disposition_closed_packet_count"]==s["result_parity_proven_packet_count"]==0,"candidate_split":(s["candidate_bearing_packet_count"],s["read_model_candidate_packet_count"],s["export_file_candidate_packet_count"],s["external_export_effect_and_result_parity_decision_packet_count"])==(3,1,2,3),"pairs":(s["same_kind_case_pair_count"],s["failure_injection_pair_count"],s["control_pair_count"])==(14,6,8),"semantic_zero":s["outcome_exact_pair_count"]==s["assertion_list_exact_pair_count"]==s["fully_exact_pair_count"]==s["exact_effect_family_set_pair_count"]==s["zero_effect_family_overlap_pair_count"]==0,"non_additive_1404":s["accepted_case_disposition_count"]==s["exact_non_duplicated_additive_count"]==0 and s["design_lower_bound_before_p4_status"]==s["design_lower_bound_after_p4_status"]==1404,"execution_readiness_zero":s["executed_case_count"]==s["owner_approved_case_count"]==s["command_ready_module_count"]==s["pilot_ready_module_count"]==0,"base_stable":s["risk_count"]==84 and s["mapped_risk_assignment_count"]==343,"safety_zero":set(m["safety"].values())=={0}};failed=sorted(k for k,v in checks.items() if not v);out={"artifact":"varanegar_p4_final_evidence_gap_status_checkpoint_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","previous_checkpoint":{"path":S["previous"],"sha256":sha(paths["previous"])},"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"safety":{"database_connections":0,"golden_or_uat_execution":0,"data_mutations":0}};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
