"""Execute synthetic Decimal, allocation, conversion, reversal, and temporal vectors."""
from __future__ import annotations
import argparse,hashlib,importlib.util,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];REFERENCE=ROOT/"scripts/windows/varanegar_monetary_temporal_reference.py"
S={"semantics":"artifacts/varanegar_analysis/varanegar_target_erp_monetary_quantity_temporal_semantics_contract_20260829.json","semantics_checkpoint":"artifacts/varanegar_analysis/varanegar_target_erp_monetary_quantity_temporal_semantics_checkpoint_20260829.json","configuration":"artifacts/varanegar_analysis/varanegar_target_erp_configuration_policy_immutability_change_audit_contract_20260829.json","provenance":"artifacts/varanegar_analysis/varanegar_target_erp_data_provenance_read_model_rebuild_contract_20260829.json","tests":"artifacts/varanegar_analysis/varanegar_25h_final_test_result_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def module():
 s=importlib.util.spec_from_file_location("numeric_ref",REFERENCE);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return m
def main():
 p=argparse.ArgumentParser();p.add_argument("--output",required=True,type=Path);a=p.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};m=module()
 positive_specs=[("ROUND-01",m.quantize_decimal,("1.005",2,"HALF_UP"),"1.01"),("ROUND-02",m.quantize_decimal,("1.005",2,"HALF_EVEN"),"1.00"),("ROUND-03",m.quantize_decimal,("-1.005",2,"HALF_UP"),"-1.01"),("ROUND-04",m.quantize_decimal,("2.675",2,"HALF_EVEN"),"2.68"),("ROUND-05",m.quantize_decimal,("0",2,"HALF_EVEN"),"0.00"),("ROUND-06",m.quantize_decimal,("999999.999",2,"HALF_EVEN"),"1000000.00"),("ALLOC-01",m.allocate_largest_remainder,("100.00",["1","1","1"],2),["33.34","33.33","33.33"]),("ALLOC-02",m.allocate_largest_remainder,("0.05",["1","1"],2),["0.03","0.02"]),("ALLOC-03",m.allocate_largest_remainder,("10.00",["3","2"],2),["6.00","4.00"]),("ALLOC-04",m.allocate_largest_remainder,("1",["0","1"],2),["0.00","1.00"]),("CONVERT-01",m.convert_decimal,("10","3","2",2,"HALF_EVEN"),"15.00"),("CONVERT-02",m.convert_decimal,("1","1","3",4,"HALF_UP"),"0.3333"),("CONVERT-03",m.convert_decimal,("-2.5","4","1",2,"HALF_EVEN"),"-10.00"),("CONVERT-04",m.convert_decimal,("100","1","1000",6,"HALF_EVEN"),"0.100000"),("REVERSE-01",m.reverse_amount,("10.25",2),"-10.25"),("REVERSE-02",m.reverse_amount,("-10.25",2),"10.25"),("REVERSE-03",m.reverse_amount,("0",3),"0.000"),("TIME-01",m.temporal_status,("2026-01-15T12:00:00+03:30","Asia/Tehran","2026-01-15","2026-01-15",True,"PRESENTATION_ONLY"),"TEMPORAL_SEMANTICS_ACCEPTED"),("TIME-02",m.temporal_status,("2026-07-01T00:00:00+03:30","Asia/Tehran","2026-07-01","2026-06-30",True,"PRESENTATION_ONLY"),"TEMPORAL_SEMANTICS_ACCEPTED"),("TIME-03",m.temporal_status,("2026-12-31T23:59:59+03:30","Asia/Tehran","2027-01-01","2026-12-31",True,"PRESENTATION_ONLY"),"TEMPORAL_SEMANTICS_ACCEPTED")]
 negative_specs=[("NEG-TYPE",m.quantize_decimal,(1.2,2,"HALF_EVEN"),"INVALID_DECIMAL_TYPE"),("NEG-FORMAT",m.quantize_decimal,("x",2,"HALF_EVEN"),"INVALID_DECIMAL_FORMAT"),("NEG-NONFINITE",m.quantize_decimal,("NaN",2,"HALF_EVEN"),"NON_FINITE_DECIMAL"),("NEG-SCALE",m.quantize_decimal,("1",-1,"HALF_EVEN"),"INVALID_SCALE"),("NEG-MODE",m.quantize_decimal,("1",2,"UNKNOWN"),"UNSUPPORTED_ROUNDING_MODE"),("NEG-WEIGHTS-EMPTY",m.allocate_largest_remainder,("1",[],2),"INVALID_WEIGHT_SET"),("NEG-WEIGHTS-ZERO",m.allocate_largest_remainder,("1",["0","0"],2),"INVALID_WEIGHT_SET"),("NEG-ALLOC-TOTAL",m.allocate_largest_remainder,("-1",["1"],2),"NEGATIVE_ALLOCATION_TOTAL"),("NEG-DENOM",m.convert_decimal,("1","1","0",2,"HALF_EVEN"),"ZERO_CONVERSION_DENOMINATOR"),("NEG-NAIVE",m.temporal_status,("2026-01-01T00:00:00","Asia/Tehran","2026-01-01","2026-01-01",True,"PRESENTATION_ONLY"),"NAIVE_INSTANT"),("NEG-ZONE",m.temporal_status,("2026-01-01T00:00:00+03:30","Invalid/Zone","2026-01-01","2026-01-01",True,"PRESENTATION_ONLY"),"UNKNOWN_TIMEZONE"),("NEG-OFFSET",m.temporal_status,("2026-01-01T00:00:00+00:00","Asia/Tehran","2026-01-01","2026-01-01",True,"PRESENTATION_ONLY"),"TIMEZONE_OFFSET_MISMATCH"),("NEG-FISCAL",m.temporal_status,("2026-01-01T00:00:00+03:30","Asia/Tehran","2026-01-01","2026-01-01",False,"PRESENTATION_ONLY"),"FISCAL_PERIOD_NOT_OPEN"),("NEG-CALENDAR",m.temporal_status,("2026-01-01T00:00:00+03:30","Asia/Tehran","2026-01-01","2026-01-01",True,"AUTHORITATIVE"),"CALENDAR_ROLE_NOT_PRESENTATION_ONLY")]
 def run_positive():
  out=[]
  for i,f,args,expected in positive_specs:
   try:actual=f(*args);status="PASS" if actual==expected else "FAIL"
   except Exception as e:actual=type(e).__name__;status="FAIL"
   out.append({"vector_id":i,"expected":expected,"actual":actual,"status":status})
  return out
 def run_negative():
  out=[]
  for i,f,args,expected in negative_specs:
   try:f(*args);actual="NO_ERROR"
   except m.ReferenceValidationError as e:actual=str(e)
   except Exception as e:actual=type(e).__name__
   out.append({"vector_id":i,"expected":expected,"actual":actual,"status":"PASS" if actual==expected else "FAIL"})
  return out
 pr=run_positive();nr=run_negative();o=d["tests"];s={"reference_evaluator_implementation_count":1,"positive_vector_count":len(pr),"positive_pass_count":sum(x["status"]=="PASS" for x in pr),"negative_vector_count":len(nr),"negative_pass_count":sum(x["status"]=="PASS" for x in nr),"total_vector_count":len(pr)+len(nr),"total_pass_count":sum(x["status"]=="PASS" for x in pr+nr),"rounding_vector_count":6,"allocation_vector_count":4,"conversion_vector_count":4,"reversal_vector_count":3,"temporal_positive_vector_count":3,"distinct_error_code_count":len({x["actual"] for x in nr}),"operational_numeric_or_temporal_implementation_count":0,"operational_value_read_count":0,"calculation_conversion_posting_or command_run_count":0,"accepted_operational_receipt_count":0,"command_ready_module_count":0,"pilot_ready_module_count":0,"design_lower_bound_before_reference_evaluator":1404,"design_lower_bound_after_reference_evaluator":1404,"official_test_file_count":o["runner"]["test_file_count"],"official_passed_test_count":o["runner"]["passed_test_count"],"risk_count":d["risk"]["summary"]["risk_count"],"mapped_risk_assignment_count":d["trace"]["summary"]["mapped_risk_assignment_count"],"new_risk_count":0}
 checks={"sources_pass":all(d[k].get("validation")=="PASS" for k in ("semantics","semantics_checkpoint","configuration","provenance","tests")),"positive_20_of_20":s["positive_vector_count"]==s["positive_pass_count"]==20,"negative_14_of_14":s["negative_vector_count"]==s["negative_pass_count"]==14,"total_34_of_34":s["total_vector_count"]==s["total_pass_count"]==34,"families_6_4_4_3_3":(s["rounding_vector_count"],s["allocation_vector_count"],s["conversion_vector_count"],s["reversal_vector_count"],s["temporal_positive_vector_count"])==(6,4,4,3,3),"operational_and_readiness_zero":s["operational_numeric_or_temporal_implementation_count"]==s["operational_value_read_count"]==s["calculation_conversion_posting_or command_run_count"]==s["accepted_operational_receipt_count"]==s["command_ready_module_count"]==s["pilot_ready_module_count"]==0,"non_additive_1404":s["design_lower_bound_before_reference_evaluator"]==s["design_lower_bound_after_reference_evaluator"]==1404,"official_tests_pass":o["validation"]=="PASS" and o["runner"]["bootstrap_excluded_test_file_count"]==0,"base_stable":s["risk_count"]==84 and s["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_target_erp_monetary_temporal_synthetic_reference_evaluator_contract_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","scope":{"mode":"pure_synthetic_decimal_allocation_conversion_reversal_temporal_reference","continuation_complete":False,"operational_amount_quantity_rate_date_or timestamp_read":False},"safety":{"database_connections":0,"network_reads_or_writes":0,"operational_amount_quantity_rate_date_timestamp_or_calendar_value_reads":0,"calculations_conversions_postings_or_business_commands_executed":0,"operational_forms_reports_queries_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"credentials_endpoints_pii_or_raw_business_values_read_or_persisted":0},"summary":s,"positive_results":pr,"negative_results":nr,"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())]+[{"name":"reference_evaluator","path":REFERENCE.relative_to(ROOT).as_posix(),"size_bytes":REFERENCE.stat().st_size,"sha256":sha(REFERENCE)},{"name":"builder","path":"scripts/windows/build_varanegar_target_erp_monetary_temporal_synthetic_reference_evaluator_contract_20260829.py","size_bytes":Path(__file__).stat().st_size,"sha256":sha(Path(__file__))}],"limits":["All amounts weights rates dates and timestamps are fixed synthetic vectors; no operational value was read.","The reference evaluator is not a pricing accounting inventory treasury fiscal or posting implementation.","Operational semantic parity and readiness remain blocked pending authenticated current receipts."]}
 a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(s,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
