"""Execute deterministic synthetic file-metadata safety vectors."""
from __future__ import annotations
import argparse,copy,hashlib,importlib.util,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];REFERENCE=ROOT/"scripts/windows/varanegar_file_metadata_reference.py"
S={"file_contract":"artifacts/varanegar_analysis/varanegar_target_erp_file_attachment_import_export_integrity_contract_20260829.json","file_checkpoint":"artifacts/varanegar_analysis/varanegar_target_erp_file_attachment_import_export_integrity_checkpoint_20260829.json","redaction":"artifacts/varanegar_analysis/varanegar_target_erp_evidence_logging_redaction_retention_contract_20260829.json","authorization":"artifacts/varanegar_analysis/varanegar_target_erp_command_authorization_scope_decision_trace_contract_20260829.json","tests":"artifacts/varanegar_analysis/varanegar_25h_final_test_result_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def module():
 s=importlib.util.spec_from_file_location("file_ref",REFERENCE);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return m
def main():
 p=argparse.ArgumentParser();p.add_argument("--output",required=True,type=Path);a=p.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};m=module();base=m.baseline()
 def changed(**kw):e=copy.deepcopy(base);e.update(kw);return e
 positive=[("POS-CLEAN",base,"FILE_ACCEPTED_CLEAN_AUTHORIZED_AND_CURRENT"),("POS-MALWARE-QUARANTINE",changed(scanner_status="MALWARE",quarantined=True),"FILE_QUARANTINED_SCAN_OR_DLP"),("POS-SCANNER-UNKNOWN",changed(scanner_status="UNKNOWN",quarantined=True),"FILE_QUARANTINED_SCAN_OR_DLP"),("POS-QUARANTINE-BLOCK",changed(scanner_status="MALWARE",quarantined=True,access_requested=True),"QUARANTINED_ACCESS_BLOCKED"),("POS-DERIVATIVE",changed(sanitized_derivative=True),"SANITIZED_DERIVATIVE_ACCEPTED_ORIGINAL_PRESERVED")]
 negative=[("NEG-EXTRA",dict(base,extra=1),"SCHEMA_INVALID"),("NEG-PATH",changed(canonical_name="../secret.txt"),"FILE_REJECTED_NAME_OR_PATH"),("NEG-SIZE",changed(size_bytes=1048577),"FILE_REJECTED_SIZE_LIMIT"),("NEG-HASH",changed(content_sha256="x"),"FILE_REJECTED_DIGEST_INVALID"),("NEG-MIME",changed(detected_media_type="application/zip"),"FILE_REJECTED_MEDIA_TYPE_MISMATCH"),("NEG-ENTRIES",changed(archive_entry_count=101),"FILE_REJECTED_ARCHIVE_SAFETY"),("NEG-DEPTH",changed(archive_depth=4),"FILE_REJECTED_ARCHIVE_SAFETY"),("NEG-RATIO",changed(archive_ratio_ok=False),"FILE_REJECTED_ARCHIVE_SAFETY"),("NEG-ZIPSLIP",changed(archive_paths_safe=False),"FILE_REJECTED_ARCHIVE_SAFETY"),("NEG-AUTH",changed(access_requested=True,authorization_current=False),"DOWNLOAD_REJECTED_AUTHORIZATION_OR_EXPIRY"),("NEG-LINK",changed(access_requested=True,signed_link_current=False),"DOWNLOAD_REJECTED_AUTHORIZATION_OR_EXPIRY"),("NEG-DERIVATIVE",changed(sanitized_derivative=True,derivative_digest_distinct=False),"DERIVATIVE_REJECTED_LINEAGE_OR_DIGEST"),("NEG-FORMULA",changed(export_formula_safe=False),"EXPORT_REJECTED_FORMULA_INJECTION"),("NEG-RETENTION",changed(retention_current=False),"DISPOSITION_REJECTED_RETENTION_OR_HOLD")]
 def run(vs):return [{"vector_id":i,"expected":x,"actual":m.evaluate(e),"status":"PASS" if m.evaluate(e)==x else "FAIL"} for i,e,x in vs]
 pr=run(positive);nr=run(negative);o=d["tests"]
 s={"reference_validator_implementation_count":1,"positive_vector_count":len(pr),"positive_pass_count":sum(x["status"]=="PASS" for x in pr),"negative_vector_count":len(nr),"negative_pass_count":sum(x["status"]=="PASS" for x in nr),"total_vector_count":len(pr)+len(nr),"total_pass_count":sum(x["status"]=="PASS" for x in pr+nr),"distinct_typed_outcome_count":len({x["actual"] for x in pr+nr}),"file_gate_count":d["file_contract"]["summary"]["gate_count"],"file_module_gate_assignment_count":d["file_contract"]["summary"]["module_gate_assignment_count"],"operational_file_scanner_or_parser_implementation_count":0,"operational_file_body_or_archive_read_count":0,"scan_quarantine_download_export_or_disposition_run_count":0,"accepted_operational_receipt_count":0,"command_ready_module_count":0,"pilot_ready_module_count":0,"design_lower_bound_before_reference_validator":1404,"design_lower_bound_after_reference_validator":1404,"official_test_file_count":o["runner"]["test_file_count"],"official_passed_test_count":o["runner"]["passed_test_count"],"risk_count":d["risk"]["summary"]["risk_count"],"mapped_risk_assignment_count":d["trace"]["summary"]["mapped_risk_assignment_count"],"new_risk_count":0}
 checks={"sources_pass":all(d[k].get("validation")=="PASS" for k in ("file_contract","file_checkpoint","redaction","authorization","tests")),"positive_5_of_5":s["positive_vector_count"]==s["positive_pass_count"]==5,"negative_14_of_14":s["negative_vector_count"]==s["negative_pass_count"]==14,"total_19_of_19":s["total_vector_count"]==s["total_pass_count"]==19,"coverage_22_308":(s["file_gate_count"],s["file_module_gate_assignment_count"])==(22,308),"operational_and_readiness_zero":s["operational_file_scanner_or_parser_implementation_count"]==s["operational_file_body_or_archive_read_count"]==s["scan_quarantine_download_export_or_disposition_run_count"]==s["accepted_operational_receipt_count"]==s["command_ready_module_count"]==s["pilot_ready_module_count"]==0,"non_additive_1404":s["design_lower_bound_before_reference_validator"]==s["design_lower_bound_after_reference_validator"]==1404,"official_tests_pass":o["validation"]=="PASS" and o["runner"]["bootstrap_excluded_test_file_count"]==0,"base_stable":s["risk_count"]==84 and s["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_target_erp_file_metadata_synthetic_reference_validator_contract_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","scope":{"mode":"pure_synthetic_file_metadata_reference_validator","continuation_complete":False,"file_body_archive_or operational_content_read":False},"safety":{"database_connections":0,"network_reads_or_writes":0,"operational_file_attachment_import_export_archive_or_body_reads":0,"scanner_parser_quarantine_download_export_or_disposition_actions_executed":0,"operational_forms_reports_queries_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"credentials_endpoints_pii_or_raw_business_values_read_or_persisted":0},"summary":s,"positive_results":pr,"negative_results":nr,"outcome_precedence":["SCHEMA","NAME_PATH","SIZE","DIGEST","MEDIA_TYPE","ARCHIVE_SAFETY","SCAN_DLP_QUARANTINE","DOWNLOAD_AUTHORIZATION","DERIVATIVE_LINEAGE","EXPORT_FORMULA","RETENTION","ACCEPTED"],"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())]+[{"name":"reference_validator","path":REFERENCE.relative_to(ROOT).as_posix(),"size_bytes":REFERENCE.stat().st_size,"sha256":sha(REFERENCE)},{"name":"builder","path":"scripts/windows/build_varanegar_target_erp_file_metadata_synthetic_reference_validator_contract_20260829.py","size_bytes":Path(__file__).stat().st_size,"sha256":sha(Path(__file__))}],"limits":["Only fixed synthetic metadata was evaluated; no file body archive document or payload was opened.","The validator is not a malware scanner parser DLP engine quarantine store or download service.","Operational file release remains blocked pending authenticated current scanner authorization lineage and retention receipts."]}
 a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(s,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
