from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S={"cases":"artifacts/varanegar_analysis/varanegar_platform_golden_uat_cases_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_platform_readiness_checkpoint_20260829.json","builder":"scripts/windows/build_varanegar_platform_golden_uat_cases_20260829.py","checkpoint_builder":"scripts/windows/build_varanegar_platform_golden_uat_checkpoint_20260829.py","test":"tests/test_varanegar_platform_golden_uat_cases.py","checkpoint_test":"tests/test_varanegar_platform_golden_uat_checkpoint.py","doc":"docs/varanegar_reconstruction/PLATFORM_GOLDEN_UAT_DELTA_20260829_FA.md"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d=load(paths["cases"]);p=load(paths["previous"]);s=d["summary"];checks={"sources_pass":d["validation"]==p["validation"]=="PASS","forty_two":s["delta_case_count"]==s["combined_platform_acceptance_design_count"]==42,"six_surfaces":s["delta_surface_count"]==6,"runtime_zero":s["executed_delta_case_count"]==s["owner_approved_case_count"]==s["deployment_restore_or_rollback_executed_count"]==0,"base_stable":s["risk_count"]==84 and s["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v);out={"artifact":"varanegar_platform_golden_uat_checkpoint_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","previous_checkpoint":{"path":S["previous"],"sha256":sha(paths["previous"])},"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"safety":{"platform_or_recovery_actions_executed":0,"database_connections":0,"data_mutations":0}};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
