"""Build chained checkpoint for RPT-16/RPT-17 selector routing."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
S={"contract":"artifacts/varanegar_analysis/domains/stock_report_selector_contract_20260829.json","boundary":"artifacts/varanegar_analysis/domains/stock_report_selector_boundary_20260829.json","rpt14":"artifacts/varanegar_analysis/domains/production_detail_report_contract_20260829.json","rpt15":"artifacts/varanegar_analysis/domains/stock_report_reference_contract_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_production_detail_report_checkpoint_20260829.json","extractor":"scripts/windows/extract_varanegar_stock_report_selector_boundary_20260829.py","builder":"scripts/windows/build_varanegar_stock_report_selector_contract_20260829.py","checkpoint_builder":"scripts/windows/build_varanegar_stock_report_selector_checkpoint_20260829.py","test":"tests/test_varanegar_stock_report_selector_contract.py","doc":"docs/varanegar_reconstruction/STOCK_REPORT_SELECTOR_ROUTING_BOUNDARY_20260829_FA.md"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(paths[k]) for k in ("contract","boundary","rpt14","rpt15","previous")};c=d["contract"];checks={"sources_pass":all(x["validation"]=="PASS" for x in d.values()),"two_selectors_no_queries":c["summary"]["selector_count"]==2 and c["summary"]["query_owner_count"]==0,"no_independent_result_set":c["summary"]["independent_result_set_count"]==0,"two_downstream_routes":c["summary"]["downstream_route_count"]==2 and c["summary"]["downstream_contract_count"]==2,"routing_parity_reframed":c["classification_correction"]["routing_parity_required_count"]==2,"six_golden_cases":len(c["golden_cases"])==6,"risk_stable":c["summary"]["risk_count"]==84,"zero_execution":set(v for k,v in c["safety"].items() if k!="mode")=={0}};failed=sorted(k for k,v in checks.items() if not v);out={"artifact":"varanegar_stock_report_selector_checkpoint_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","previous_checkpoint":{"path":S["previous"],"sha256":sha(paths["previous"])},"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"safety":{"selectors_dialogs_reports_or_queries_executed":0,"assemblies_loaded_or_executed":0,"database_connections":0,"data_mutations":0,"sensitive_values_persisted":0}};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
