"""Execute deterministic synthetic capacity-budget decision vectors."""
from __future__ import annotations
import argparse,copy,hashlib,importlib.util,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];REFERENCE=ROOT/"scripts/windows/varanegar_capacity_budget_reference.py"
S={"capacity":"artifacts/varanegar_analysis/varanegar_target_erp_capacity_timeout_backpressure_degradation_contract_20260829.json","capacity_checkpoint":"artifacts/varanegar_analysis/varanegar_target_erp_capacity_timeout_backpressure_degradation_checkpoint_20260829.json","observability":"artifacts/varanegar_analysis/varanegar_target_erp_observability_slo_incident_evidence_contract_20260829.json","idempotency":"artifacts/varanegar_analysis/varanegar_target_erp_command_idempotency_outbox_inbox_convergence_contract_20260829.json","tests":"artifacts/varanegar_analysis/varanegar_25h_final_test_result_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def module():
 s=importlib.util.spec_from_file_location("capacity_ref",REFERENCE);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return m
def main():
 p=argparse.ArgumentParser();p.add_argument("--output",required=True,type=Path);a=p.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};m=module();base=m.baseline()
 def changed(**kw):e=copy.deepcopy(base);e.update(kw);return e
 positive=[("POS-CAPACITY",base,"CAPACITY_ACCEPTED_WITHIN_ENVELOPE"),("POS-BACKPRESSURE",changed(queue_depth=20),"QUEUE_BACKPRESSURE_APPLIED"),("POS-RETRY",changed(retries_used=1),"RETRY_ALLOWED_WITHIN_BUDGET_AND_IDEMPOTENCY"),("POS-CIRCUIT",changed(dependency_healthy=False,circuit_open=True),"CIRCUIT_OPEN_DEPENDENCY_SHED"),("POS-DEGRADED",changed(degraded_mode_requested=True),"DEGRADED_MODE_ACCEPTED_INVARIANTS_PRESERVED"),("POS-RECOVERY",changed(overload_recovery_requested=True),"RECOVERY_ACCEPTED_DRAIN_AND_RECONCILIATION_COMPLETE")]
 negative=[("NEG-EXTRA",dict(base,extra=1),"SCHEMA_INVALID"),("NEG-TYPE",changed(parent_budget_ms="1000"),"SCHEMA_INVALID"),("NEG-UNKNOWN-GATE",changed(blocking_unknown_count=1),"BLOCKING_UNKNOWN_PRESENT"),("NEG-COMMIT",changed(commit_status="UNKNOWN"),"RECONCILIATION_REQUIRED_UNKNOWN_COMMIT"),("NEG-PARENT",changed(elapsed_ms=500,local_timeout_ms=600),"TIMEOUT_BUDGET_INVALID"),("NEG-DOWNSTREAM",changed(downstream_timeout_ms=700),"TIMEOUT_BUDGET_INVALID"),("NEG-INFLIGHT",changed(inflight=10),"REQUEST_REJECTED_CONCURRENCY_LIMIT"),("NEG-RETRY-IDEMPOTENCY",changed(retries_used=1,idempotent=False),"RETRY_BLOCKED_UNSAFE_OR_UNBOUNDED"),("NEG-RETRY-BACKOFF",changed(retries_used=1,backoff_and_jitter_valid=False),"RETRY_BLOCKED_UNSAFE_OR_UNBOUNDED"),("NEG-RETRY-LIMIT",changed(retries_used=3),"RETRY_BUDGET_EXHAUSTED"),("NEG-CIRCUIT",changed(dependency_healthy=False,circuit_open=False),"DEPENDENCY_FAILURE_CIRCUIT_NOT_OPEN"),("NEG-DEGRADED",changed(degraded_mode_requested=True,degraded_invariants_preserved=False),"DEGRADED_MODE_REJECTED_INVARIANT"),("NEG-RECOVERY",changed(overload_recovery_requested=True,drain_complete=False),"RECOVERY_PENDING_DRAIN_OR_RECONCILIATION")]
 def run(vs):return [{"vector_id":i,"expected":x,"actual":m.evaluate(e),"status":"PASS" if m.evaluate(e)==x else "FAIL"} for i,e,x in vs]
 pr=run(positive);nr=run(negative);o=d["tests"]
 s={"reference_evaluator_implementation_count":1,"positive_vector_count":len(pr),"positive_pass_count":sum(x["status"]=="PASS" for x in pr),"negative_vector_count":len(nr),"negative_pass_count":sum(x["status"]=="PASS" for x in nr),"total_vector_count":len(pr)+len(nr),"total_pass_count":sum(x["status"]=="PASS" for x in pr+nr),"distinct_typed_outcome_count":len({x["actual"] for x in pr+nr}),"capacity_gate_count":d["capacity"]["summary"]["gate_count"],"capacity_module_gate_assignment_count":d["capacity"]["summary"]["module_gate_assignment_count"],"operational_capacity_implementation_count":0,"operational_traffic_metric_queue_or_resource_read_count":0,"load_fault_overload_or_degradation_run_count":0,"accepted_operational_receipt_count":0,"command_ready_module_count":0,"pilot_ready_module_count":0,"design_lower_bound_before_reference_evaluator":1404,"design_lower_bound_after_reference_evaluator":1404,"official_test_file_count":o["runner"]["test_file_count"],"official_passed_test_count":o["runner"]["passed_test_count"],"risk_count":d["risk"]["summary"]["risk_count"],"mapped_risk_assignment_count":d["trace"]["summary"]["mapped_risk_assignment_count"],"new_risk_count":0}
 checks={"sources_pass":all(d[k].get("validation")=="PASS" for k in ("capacity","capacity_checkpoint","observability","idempotency","tests")),"positive_6_of_6":s["positive_vector_count"]==s["positive_pass_count"]==6,"negative_13_of_13":s["negative_vector_count"]==s["negative_pass_count"]==13,"total_19_of_19":s["total_vector_count"]==s["total_pass_count"]==19,"coverage_20_280":(s["capacity_gate_count"],s["capacity_module_gate_assignment_count"])==(20,280),"operational_and_readiness_zero":s["operational_capacity_implementation_count"]==s["operational_traffic_metric_queue_or_resource_read_count"]==s["load_fault_overload_or_degradation_run_count"]==s["accepted_operational_receipt_count"]==s["command_ready_module_count"]==s["pilot_ready_module_count"]==0,"non_additive_1404":s["design_lower_bound_before_reference_evaluator"]==s["design_lower_bound_after_reference_evaluator"]==1404,"official_tests_pass":o["validation"]=="PASS" and o["runner"]["bootstrap_excluded_test_file_count"]==0,"base_stable":s["risk_count"]==84 and s["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_target_erp_capacity_budget_synthetic_reference_evaluator_contract_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","scope":{"mode":"pure_synthetic_capacity_timeout_retry_backpressure_degradation_reference","continuation_complete":False,"operational_traffic_metric_queue_or resource_read":False},"safety":{"database_connections":0,"network_reads_or_writes":0,"operational_traffic_metric_queue_resource_or_dependency_reads":0,"load_fault_overload_degradation_or_recovery_actions_executed":0,"operational_forms_reports_queries_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"credentials_endpoints_pii_or_raw_business_values_read_or_persisted":0},"summary":s,"positive_results":pr,"negative_results":nr,"outcome_precedence":["SCHEMA","BLOCKING_UNKNOWN","UNKNOWN_COMMIT","TIMEOUT_BUDGET","CONCURRENCY_LIMIT","QUEUE_BACKPRESSURE","RETRY_SAFETY_AND_BUDGET","DEPENDENCY_AND_CIRCUIT","DEGRADATION_INVARIANT","RECOVERY_DRAIN_AND_RECONCILIATION","ACCEPTED"],"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())]+[{"name":"reference_evaluator","path":REFERENCE.relative_to(ROOT).as_posix(),"size_bytes":REFERENCE.stat().st_size,"sha256":sha(REFERENCE)},{"name":"builder","path":"scripts/windows/build_varanegar_target_erp_capacity_budget_synthetic_reference_evaluator_contract_20260829.py","size_bytes":Path(__file__).stat().st_size,"sha256":sha(Path(__file__))}],"limits":["Only fixed synthetic budgets counts booleans and states were evaluated.","The evaluator is not a load balancer queue rate limiter circuit breaker autoscaler or runtime capacity implementation.","Operational capacity degradation and recovery remain blocked pending authenticated current receipts."]}
 a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(s,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
