"""Build evidence-first identity and authorization incident playbooks."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S={"envelope":"artifacts/varanegar_analysis/varanegar_identity_authorization_outcome_envelope_20260829.json","golden":"artifacts/varanegar_analysis/varanegar_identity_authorization_golden_uat_cases_20260829.json","endpoint":"artifacts/varanegar_analysis/domains/ngt_authorization_endpoint_coverage_20260828.json","effective":"artifacts/varanegar_analysis/domains/ngt_authorization_effective_boundary_20260828.json","owner":"artifacts/varanegar_analysis/domains/ngt_owner_scope_effective_boundary_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_identity_authorization_golden_uat_checkpoint_20260829.json"}
COMMON=["capture incident time, route/command, policy and assignment versions, session epoch, capability and hashed application/owner/data scopes without names, identifiers, credentials or raw grants","verify artifact, policy, schema and deployment hashes and stop on drift","read immutable decision, assignment/revocation, approval, audit and outbox receipts using opaque references","recompute deny-first decision order including authentication, explicit deny, owner boundary, capability, data scope, SoD and expiry","classify NATURAL_BEHAVIOR, DATA_DEBT, BUG or UNPROVEN","quarantine ambiguous allow, cross-owner, stale-session, missing-audit or expired-break-glass outcomes before retry","stop before grant, revoke, role edit, session invalidation, token access, impersonation or permission repair","design isolated synthetic-principal and fault-injection reproduction when the boundary remains unproven"]
BASE=[
 ("IA-PB-01","the same capability is allowed by one path and denied by another","explicit deny versus direct/group/inherited allow","compare hashed decision sources; explicit deny wins and missing explain evidence is UNPROVEN",["R-003","R-024","R-059"]),
 ("IA-PB-02","a mutating endpoint accepts or rejects without a named authorization decision","endpoint default-deny coverage","pin route metadata and application-service decision; no declaration or manual signal cannot be treated as implicit allow",["R-002","R-057","R-024"]),
 ("IA-PB-03","admin succeeds outside ordinary resource/action checks","ambient admin short-circuit","treat admin as explicit scoped capabilities with SoD, expiry and audit; never infer universal authority",["R-003","R-058","R-024"]),
 ("IA-PB-04","a principal sees or mutates data across an owner/application boundary","owner-filter and data scope","compare owner hierarchy and assignment scope hashes; quarantine repository results produced without owner filtering",["R-002","R-004","R-059"]),
 ("IA-PB-05","a revoked principal continues through an existing token or session","revocation and session epoch","compare revoke receipt, epoch and token issue epoch; stale epoch fails closed without reading token contents",["R-006","R-007","R-024"]),
 ("IA-PB-06","assignment exists but audit/outbox/approval evidence is partial","atomic assignment receipt","read back every effect before retry and classify an incomplete fold as UNKNOWN_REQUIRES_READBACK",["R-006","R-007","R-057"]),
 ("IA-PB-07","self-grant, incompatible duties or expired break-glass remains effective","SoD and break-glass lifecycle","verify independent approval and expiry receipt; never extend, renew or repair an emergency grant during diagnosis",["R-003","R-004","R-058"]),
]
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};play=[{"id":i,"incident":inc,"focus":focus,"steps":COMMON+[extra],"stop_conditions":["evidence/policy/deployment hash drift","grant, revoke, role edit, session invalidation, impersonation or repair required","identity/security owner decision required","identity, credential or raw grant data would be persisted"],"risks":risks,"runtime_diagnosis":"NOT_PERFORMED"} for i,inc,focus,extra,risks in BASE];known={x["id"] for x in d["risk"]["risks"]};summary={"playbook_count":len(play),"minimum_step_count":min(len(x["steps"]) for x in play),"command_contract_count":d["envelope"]["summary"]["command_contract_count"],"combined_acceptance_design_count":d["golden"]["summary"]["combined_identity_acceptance_design_count"],"endpoint_gap_count":d["endpoint"]["summary"]["endpoint_with_no_ngt_standard_claims_or_anonymous_declaration_count"],"scope_mismatch_count":d["owner"]["summary"]["scope_consistency_mismatch_count"],"runtime_incidents_diagnosed_count":0,"grants_revokes_session_or_permission_repairs_performed_count":0,"owner_approved_count":0,"identity_values_persisted_count":0,"risk_count":84,"mapped_risk_assignment_count":343,"new_risk_count":0};checks={"validated_sources_pass":all(d[k]["validation"]=="PASS" for k in ["envelope","golden","owner","risk","trace","previous"]),"seven_playbooks":len(play)==7,"nine_steps":all(len(x["steps"])==9 for x in play),"four_way":all("NATURAL_BEHAVIOR, DATA_DEBT, BUG or UNPROVEN" in x["steps"][4] for x in play),"risks_exist":all(r in known for x in play for r in x["risks"]),"scope":summary["command_contract_count"]==6 and summary["combined_acceptance_design_count"]==226 and summary["endpoint_gap_count"]==60 and summary["scope_mismatch_count"]==58,"deny_admin_session_sod":any("explicit deny" in x["focus"] for x in play) and any("admin" in x["focus"] for x in play) and any("session epoch" in x["focus"] for x in play) and any("SoD" in x["focus"] for x in play),"runtime_zero":summary["runtime_incidents_diagnosed_count"]==summary["grants_revokes_session_or_permission_repairs_performed_count"]==summary["owner_approved_count"]==summary["identity_values_persisted_count"]==0,"base_stable":d["risk"]["summary"]["risk_count"]==84 and d["trace"]["summary"]["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_identity_authorization_expert_playbook_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","safety":{"mode":"OFFLINE_EVIDENCE_SYNTHESIS","database_connections":0,"network_reads_or_writes":0,"identity_or_authorization_commands_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"identity_values_credentials_or_raw_grants_read_or_persisted":0},"summary":summary,"playbooks":play,"diagnostic_result_contract":{"allowed":["NATURAL_BEHAVIOR","DATA_DEBT","BUG","UNPROVEN"],"requires_named_incident_evidence":True,"grant_revoke_session_or_permission_repair_is_separate_authorized_work":True},"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"confidence":{"structure":"HIGH","incident_diagnosis":"REQUIRES_INCIDENT_EVIDENCE"},"limits":["No named incident was diagnosed.","No grant, revoke, session, token, role, scope or permission operation was performed.","No current effective identity or grant is claimed."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(summary,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
