"""Design synthetic Golden/UAT cases for the twelve-command treasury envelope."""
from __future__ import annotations
import argparse,collections,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
S={"envelope":"artifacts/varanegar_analysis/varanegar_treasury_command_outcome_envelope_20260829.json","readiness":"artifacts/varanegar_analysis/varanegar_treasury_command_readiness_delta_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_treasury_command_readiness_checkpoint_20260829.json"}
BASE=[("AUTH_DENIED","authorization","actor lacks capability","REJECTED_NO_EFFECT"),("STALE_VERSION","concurrency","expected_version is stale","REJECTED_NO_EFFECT"),("DUPLICATE_COMMAND_ID","idempotency","same command_id and payload is submitted twice","COMMITTED_ORIGINAL_OUTCOME_ONLY_ONCE"),("FAULT_AFTER_FIRST_WRITE","failure_injection","inject failure after first durable-stage candidate","REJECTED_NO_EFFECT_OR_TYPED_DURABLE_EFFECT"),("SCOPE_DENIED","scope","resource/DC/fiscal scope is outside actor grant","REJECTED_NO_EFFECT"),("SUCCESS","success","valid command with current policy and expected_version","COMMITTED")]
SPECIAL={
"cash_receipt.edit":("RECEIPT_AMOUNT_CROSS_OBJECT","reconciliation","receipt and cash detail totals disagree","REJECTED_NO_EFFECT"),
"received_cheque.edit":("CHEQUE_CUSTOMER_LINK","validation","cheque/customer/detail link is inconsistent","REJECTED_NO_EFFECT"),
"received_bank_draft.edit":("DRAFT_AMOUNT_VALIDATION","validation","draft validation side effect disagrees with requested amount","UNKNOWN_REQUIRES_READBACK"),
"received_cheque.undo":("UNDO_HISTORY_BRANCH","workflow","requested history leaf is not current or cession branch is ambiguous","REJECTED_NO_EFFECT"),
"received_cheque.delete":("DELETE_TRANSACTION_UNKNOWN","reconciliation","transport fails after dataset delete/update boundary","UNKNOWN_REQUIRES_READBACK"),
"tour_payment.save_changes":("UNDERALLOCATION","reconciliation","payment detail sum is below header amount","REJECTED_NO_EFFECT"),
"tour_payment.replicate_and_write_crosswalk":("CROSSWALK_PARTIAL_WRITE","failure_injection","back-office receipt exists but local crosswalk writeback is interrupted","REJECTED_WITH_DURABLE_EFFECT"),
"bank_reconciliation.MatchInstrument":("MATCH_TOLERANCE_POLICY","policy","candidate amount exceeds owner-approved tolerance","REJECTED_NO_EFFECT"),
"bank_reconciliation.UnmatchInstrument":("UNMATCH_LINK_SCOPE","scope","link_id lacks a trusted instrument/session scope","REJECTED_NO_EFFECT"),
"bank_reconciliation.ConfirmSession":("CONFIRM_PARTIAL_INSTRUMENT","failure_injection","fault occurs between linked-instrument updates","REJECTED_NO_EFFECT"),
"bank_reconciliation.CancelSession":("CANCEL_OWNER_DECISION","policy","cancel policy decision is not approved/versioned","REJECTED_NO_EFFECT"),
"bank_reconciliation.ReverseConfirmedSession":("REVERSAL_SOD","authorization","request violates authenticated separation of duties","REJECTED_NO_EFFECT"),
}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};cases=[]
 for command in d["envelope"]["commands"]:
  rows=BASE+[SPECIAL[command["command"]]]
  for code,kind,setup,expected in rows:
   cases.append({"case_id":f"TR-G-{command['id'].split('-')[-1]}-{code}","command_id":command["id"],"command":command["command"],"case_kind":kind,"setup":setup,"expected_outcome":expected,"assertions":["typed outcome matches durable evidence","aggregate version changes at most once","audit/outbox/crosswalk state is reconciled before retry","no out-of-scope effect"],"status":"DESIGNED_NOT_EXECUTED"})
 counts=dict(sorted(collections.Counter(x["case_kind"] for x in cases).items()));s={"command_count":len(d["envelope"]["commands"]),"case_count":len(cases),"case_kind_counts":counts,"executed_case_count":0,"passed_runtime_case_count":0,"owner_approved_case_count":0,"runtime_retry_idempotency_proven_module_count":0,"command_ready_module_count":0,"pilot_ready_module_count":0,"risk_count":84,"mapped_risk_assignment_count":343,"new_risk_count":0}
 checks={"sources_pass":all(x["validation"]=="PASS" for x in d.values()),"twelve_commands":s["command_count"]==12,"seven_each":len(cases)==84 and all(sum(x["command_id"]==c["id"] for x in cases)==7 for c in d["envelope"]["commands"]),"unique_ids":len({x["case_id"] for x in cases})==84,"every_command_special":set(SPECIAL)=={x["command"] for x in d["envelope"]["commands"]},"durable_and_unknown_covered":any(x["expected_outcome"]=="REJECTED_WITH_DURABLE_EFFECT" for x in cases) and any(x["expected_outcome"]=="UNKNOWN_REQUIRES_READBACK" for x in cases),"designed_not_executed":set(x["status"] for x in cases)=={"DESIGNED_NOT_EXECUTED"},"runtime_zero":s["executed_case_count"]==s["passed_runtime_case_count"]==s["owner_approved_case_count"]==s["runtime_retry_idempotency_proven_module_count"]==s["command_ready_module_count"]==s["pilot_ready_module_count"]==0,"risk_trace_stable":d["risk"]["summary"]["risk_count"]==84 and d["trace"]["summary"]["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_treasury_golden_uat_cases_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","safety":{"mode":"OFFLINE_SYNTHETIC_DESIGN","database_connections":0,"commands_forms_reports_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"sensitive_values_persisted":0},"summary":s,"execution_gate":{"environment":"isolated target only","requirements":["seeded synthetic fixtures","deny-first test identities","fault injection at every durable boundary","legacy/target readback comparator","owner-approved policies for tolerance/cancel/reversal"],"promotion_rule":"all 84 cases executed with zero unexplained effect difference and owner approval"},"cases":cases,"risk_links":["R-002","R-005","R-006","R-007","R-008","R-023","R-036","R-043"],"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"confidence":{"case_design":"HIGH","runtime_result":"NOT_EXECUTED"},"limits":["These are synthetic designs, not UAT results.","Owner policies for bank tolerance, cancel and reversal are unapproved.","No production or target command was executed."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(s,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
