"""Aggregate P0-P4 alias evidence gaps into one cross-lane closure-route matrix."""
from __future__ import annotations
import argparse,hashlib,json
from collections import Counter
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
S={**{f"p{i}":f"artifacts/varanegar_analysis/varanegar_p{i}_final_evidence_gap_status_matrix_20260829.json" for i in range(5)},"previous":"artifacts/varanegar_analysis/varanegar_p4_final_evidence_gap_status_checkpoint_20260829.json","priority":"artifacts/varanegar_analysis/varanegar_action_alias_handoff_priority_matrix_20260829.json","owner":"artifacts/varanegar_analysis/varanegar_action_alias_owner_evidence_packet_matrix_20260829.json","tests":"artifacts/varanegar_analysis/varanegar_25h_final_test_result_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json"}
FIELDS=["lane_and_source_packet_id","case_set_hash","candidate_or_explicit_none","evidence_gap_class","decision_route","precondition_disposition","outcome_vocabulary_mapping","assertion_effect_disposition","failure_stage_receipts","transaction_or_source_immutability_receipts","file_render_export_receipts","frozen_fixture_result_parity_receipt","accountable_role_receipts","policy_version_expiry","conflict_supersession_reference"]
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};rows=[];lanes=[]
 for i in range(5):
  src=d[f"p{i}"];s=src["summary"]
  for x in src[f"p{i}_status_packets"]:
   rows.append({"cross_lane_status_id":f"CL-{len(rows)+1:02d}","lane":f"P{i}","source_packet_id":x["source_packet_id"],"module":x["module"],"newer_action_or_surface":x["newer_action_or_surface"],"case_count":x["case_count"],"candidate_baseline_action_count":x["candidate_baseline_action_count"],"same_kind_case_pair_count":x["same_kind_case_pair_count"],"failure_injection_pair_count":x["failure_injection_pair_count"],"control_pair_count":x["control_pair_count"],"evidence_gap_class":x["evidence_gap_class"],"required_decision_route":x["required_decision_route"],"semantic_disposition_status":x["semantic_disposition_status"],"result_parity_status":x.get("result_parity_status","NOT_APPLICABLE_TO_THIS_PACKET_CLASS"),"required_cross_lane_closure_fields":FIELDS,"accepted_case_disposition_count":0,"counting_effect":"ZERO"})
  lanes.append({"lane":f"P{i}","packet_count":s[f"p{i}_status_packet_count"],"case_count":s[f"p{i}_case_count"],"candidate_bearing_packet_count":s["candidate_bearing_packet_count"],"explicit_none_packet_count":s.get("explicit_none_packet_count",0),"same_kind_case_pair_count":s["same_kind_case_pair_count"],"failure_injection_pair_count":s["failure_injection_pair_count"],"control_pair_count":s["control_pair_count"],"outcome_exact_pair_count":s["outcome_exact_pair_count"],"assertion_list_exact_pair_count":s["assertion_list_exact_pair_count"],"fully_exact_pair_count":s["fully_exact_pair_count"],"exact_effect_family_set_pair_count":s["exact_effect_family_set_pair_count"],"zero_effect_family_overlap_pair_count":s["zero_effect_family_overlap_pair_count"],"accountable_role_assignment_count":s["accountable_role_assignment_count"],"required_closure_field_count":s["required_closure_field_count"],"semantic_disposition_closed_packet_count":s["semantic_disposition_closed_packet_count"],"result_parity_proven_packet_count":s.get("result_parity_proven_packet_count",0),"executed_case_count":s["executed_case_count"],"command_ready_module_count":s["command_ready_module_count"]})
 routes=Counter(x["required_decision_route"] for x in rows);gaps=Counter(x["evidence_gap_class"] for x in rows);s={"lane_count":len(lanes),"status_packet_count":len(rows),"case_count":sum(x["case_count"] for x in lanes),"candidate_bearing_packet_count":sum(x["candidate_bearing_packet_count"] for x in lanes),"explicit_none_packet_count":sum(x["explicit_none_packet_count"] for x in lanes),"external_alias_or_new_action_decision_packet_count":routes["EXTERNAL_ALIAS_OR_NEW_ACTION_DECISION_REQUIRED"],"external_semantic_equivalence_decision_packet_count":routes["EXTERNAL_SEMANTIC_EQUIVALENCE_DECISION_REQUIRED"],"external_semantic_effect_and_result_parity_decision_packet_count":routes["EXTERNAL_SEMANTIC_EFFECT_AND_RESULT_PARITY_DECISION_REQUIRED"],"external_export_effect_and_result_parity_decision_packet_count":routes["EXTERNAL_EXPORT_EFFECT_AND_RESULT_PARITY_DECISION_REQUIRED"],"same_kind_case_pair_count":sum(x["same_kind_case_pair_count"] for x in lanes),"failure_injection_pair_count":sum(x["failure_injection_pair_count"] for x in lanes),"control_pair_count":sum(x["control_pair_count"] for x in lanes),"outcome_exact_pair_count":sum(x["outcome_exact_pair_count"] for x in lanes),"assertion_list_exact_pair_count":sum(x["assertion_list_exact_pair_count"] for x in lanes),"fully_exact_pair_count":sum(x["fully_exact_pair_count"] for x in lanes),"exact_effect_family_set_pair_count":sum(x["exact_effect_family_set_pair_count"] for x in lanes),"zero_effect_family_overlap_pair_count":sum(x["zero_effect_family_overlap_pair_count"] for x in lanes),"accountable_role_assignment_count":sum(x["accountable_role_assignment_count"] for x in lanes),"required_closure_field_assignment_count":sum(x["packet_count"]*x["required_closure_field_count"] for x in lanes),"semantic_disposition_closed_packet_count":sum(x["semantic_disposition_closed_packet_count"] for x in lanes),"result_parity_proven_packet_count":sum(x["result_parity_proven_packet_count"] for x in lanes),"accepted_case_disposition_count":0,"exact_non_duplicated_additive_count":0,"design_lower_bound_before_cross_lane_matrix":1404,"design_lower_bound_after_cross_lane_matrix":1404,"executed_case_count":sum(x["executed_case_count"] for x in lanes),"owner_approved_case_count":0,"command_ready_module_count":sum(x["command_ready_module_count"] for x in lanes),"pilot_ready_module_count":0,"official_test_file_count":d["tests"]["runner"]["test_file_count"],"official_passed_test_count":d["tests"]["runner"]["passed_test_count"],"risk_count":d["risk"]["summary"]["risk_count"],"mapped_risk_assignment_count":d["trace"]["summary"]["mapped_risk_assignment_count"],"new_risk_count":0}
 checks={"sources_pass":all(x.get("validation")=="PASS" for x in d.values()),"five_29_203":(s["lane_count"],s["status_packet_count"],s["case_count"])==(5,29,203),"candidate_20_none_9":(s["candidate_bearing_packet_count"],s["explicit_none_packet_count"])==(20,9),"routes_9_12_5_3":(s["external_alias_or_new_action_decision_packet_count"],s["external_semantic_equivalence_decision_packet_count"],s["external_semantic_effect_and_result_parity_decision_packet_count"],s["external_export_effect_and_result_parity_decision_packet_count"])==(9,12,5,3),"pairs_246_78_168":(s["same_kind_case_pair_count"],s["failure_injection_pair_count"],s["control_pair_count"])==(246,78,168),"semantic_exactness_4_0_0_0_10":(s["outcome_exact_pair_count"],s["assertion_list_exact_pair_count"],s["fully_exact_pair_count"],s["exact_effect_family_set_pair_count"],s["zero_effect_family_overlap_pair_count"])==(4,0,0,0,10),"roles_fields_58_385":(s["accountable_role_assignment_count"],s["required_closure_field_assignment_count"])==(58,385),"all_routes_open_zero":s["semantic_disposition_closed_packet_count"]==s["result_parity_proven_packet_count"]==s["accepted_case_disposition_count"]==0 and all(x["counting_effect"]=="ZERO" for x in rows),"non_additive_1404":s["exact_non_duplicated_additive_count"]==0 and s["design_lower_bound_before_cross_lane_matrix"]==s["design_lower_bound_after_cross_lane_matrix"]==1404,"execution_readiness_zero":s["executed_case_count"]==s["owner_approved_case_count"]==s["command_ready_module_count"]==s["pilot_ready_module_count"]==0,"official_tests_pass":d["tests"]["runner"]["exit_code"]==0 and s["official_passed_test_count"]>0,"base_stable":s["risk_count"]==84 and s["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_alias_cross_lane_closure_route_matrix_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","scope":{"mode":"OFFLINE_P0_P4_CROSS_LANE_CLOSURE_ROUTE_AGGREGATION","continuation_complete":False},"safety":{"database_connections":0,"golden_uat_or_operational_execution":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"write_access_created":0,"raw_business_values_identity_or_credentials_persisted":0},"summary":s,"lane_summaries":lanes,"route_distribution":dict(sorted(routes.items())),"gap_class_distribution":dict(sorted(gaps.items())),"required_cross_lane_closure_fields":FIELDS,"cross_lane_packet_routes":rows,"closure_rule":"packetization and routing are complete for the 29 alias-required actions, while all semantic, result-parity, owner, execution and readiness promotions remain evidence-gated","checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":p.stat().st_size,"sha256":sha(p)} for k,p in sorted(paths.items())]+[{"name":"builder","path":"scripts/windows/build_varanegar_alias_cross_lane_closure_route_matrix_20260829.py","size_bytes":Path(__file__).stat().st_size,"sha256":sha(Path(__file__))}],"limits":["This aggregates closed analysis packetization, not closed semantic decisions.","Four outcome-label matches do not imply any full or effect-family equivalence.","No owner receipt, result parity, UAT execution, command readiness or pilot readiness is accepted."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(s,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
