"""Prioritize the 29 unresolved action-alias packets for role-based evidence handoff."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
S={"matrix":"artifacts/varanegar_analysis/varanegar_action_alias_owner_evidence_packet_matrix_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_action_alias_owner_evidence_packet_checkpoint_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json"}
FIELDS=["source_packet_id_and_case_set_hash","priority_lane_and_rationale","candidate_baseline_action_or_explicit_none","versioned_alias_id","precondition_outcome_assertion_mapping","accountable_role_disposition","conflict_or_supersession_reference","policy_version_and_expiry","review_receipt_hash"]
LANES={
 "ALIAS_REVIEW_P0_IRREVERSIBLE_REVERSAL_REPLICATION":{"rank":0,"ids":["AAP-01","AAP-02","AAP-04","AAP-06","AAP-14","AAP-18","AAP-20"],"rationale":"irreversible, reversal, cross-module, or replication effect boundary"},
 "ALIAS_REVIEW_P1_FINANCIAL_STATE_TRANSITION":{"rank":1,"ids":["AAP-03","AAP-05","AAP-11","AAP-12","AAP-13","AAP-15","AAP-16","AAP-17"],"rationale":"financial creation, edit, match, confirm, cancel, or unmatch transition"},
 "ALIAS_REVIEW_P2_POLICY_AND_INTEGRATION_INPUT":{"rank":2,"ids":["AAP-07","AAP-08","AAP-09","AAP-10","AAP-19","AAP-21"],"rationale":"pricing policy, editable instrument, or integration input boundary"},
 "ALIAS_REVIEW_P3_STATEFUL_REPORT_COMMAND":{"rank":3,"ids":["AAP-25","AAP-26","AAP-27","AAP-28","AAP-29"],"rationale":"import, command, render, or print stateful boundary"},
 "ALIAS_REVIEW_P4_READ_ONLY_EXPORT":{"rank":4,"ids":["AAP-22","AAP-23","AAP-24"],"rationale":"read-only export surface; result parity remains independently unproven"},
}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};src=d["matrix"];assigned={i:(name,v) for name,v in LANES.items() for i in v["ids"]};rows=[]
 for packet in src["action_alias_packets"]:
  lane,meta=assigned[packet["packet_id"]];rows.append({"handoff_id":f"AHP-{len(rows)+1:02d}","source_packet_id":packet["packet_id"],"module":packet["module"],"newer_action_or_surface":packet["newer_action_or_surface"],"alias_class":packet["alias_class"],"review_priority_lane":lane,"priority_rank":meta["rank"],"priority_rationale":meta["rationale"],"case_count":packet["case_count"],"case_id_set_sha256":packet["case_id_set_sha256"],"accountable_role_types":packet["accountable_role_types"],"required_handoff_fields":FIELDS,"current_status":"WAITING_FOR_ROLE_DISPOSITION_AND_VERSIONED_ALIAS","named_owner_assignment_count":0,"accepted_handoff_count":0,"accepted_case_disposition_count":0,"counting_effect":"ZERO"})
 rows.sort(key=lambda x:(x["priority_rank"],x["source_packet_id"]));lane_counts={k:sum(x["review_priority_lane"]==k for x in rows) for k in LANES};lane_cases={k:sum(x["case_count"] for x in rows if x["review_priority_lane"]==k) for k in LANES};summary={"handoff_packet_count":len(rows),"covered_case_count":sum(x["case_count"] for x in rows),"priority_lane_count":len(LANES),"p0_packet_count":lane_counts["ALIAS_REVIEW_P0_IRREVERSIBLE_REVERSAL_REPLICATION"],"p0_case_count":lane_cases["ALIAS_REVIEW_P0_IRREVERSIBLE_REVERSAL_REPLICATION"],"p1_packet_count":lane_counts["ALIAS_REVIEW_P1_FINANCIAL_STATE_TRANSITION"],"p1_case_count":lane_cases["ALIAS_REVIEW_P1_FINANCIAL_STATE_TRANSITION"],"p2_packet_count":lane_counts["ALIAS_REVIEW_P2_POLICY_AND_INTEGRATION_INPUT"],"p2_case_count":lane_cases["ALIAS_REVIEW_P2_POLICY_AND_INTEGRATION_INPUT"],"p3_packet_count":lane_counts["ALIAS_REVIEW_P3_STATEFUL_REPORT_COMMAND"],"p3_case_count":lane_cases["ALIAS_REVIEW_P3_STATEFUL_REPORT_COMMAND"],"p4_packet_count":lane_counts["ALIAS_REVIEW_P4_READ_ONLY_EXPORT"],"p4_case_count":lane_cases["ALIAS_REVIEW_P4_READ_ONLY_EXPORT"],"accountable_role_assignment_count":sum(len(x["accountable_role_types"]) for x in rows),"required_handoff_field_count":len(FIELDS),"named_owner_assignment_count":0,"accepted_handoff_count":0,"accepted_case_disposition_count":0,"exact_non_duplicated_additive_count":0,"design_lower_bound_before_priority_handoff":src["summary"]["design_lower_bound_after_alias_packets"],"design_lower_bound_after_priority_handoff":src["summary"]["design_lower_bound_after_alias_packets"],"executed_case_count":0,"owner_approved_case_count":0,"command_ready_module_count":0,"pilot_ready_module_count":0,"risk_count":d["risk"]["summary"]["risk_count"],"mapped_risk_assignment_count":d["trace"]["summary"]["mapped_risk_assignment_count"],"new_risk_count":0}
 checks={"sources_pass":all(x.get("validation")=="PASS" for x in d.values()),"complete_partition_29_203":summary["handoff_packet_count"]==29 and summary["covered_case_count"]==203 and {x["source_packet_id"] for x in rows}=={x["packet_id"] for x in src["action_alias_packets"]},"five_lanes":summary["priority_lane_count"]==5,"lane_split":(summary["p0_packet_count"],summary["p0_case_count"],summary["p1_packet_count"],summary["p1_case_count"],summary["p2_packet_count"],summary["p2_case_count"],summary["p3_packet_count"],summary["p3_case_count"],summary["p4_packet_count"],summary["p4_case_count"])==(7,49,8,56,6,42,5,35,3,21),"roles_fields":summary["accountable_role_assignment_count"]==58 and summary["required_handoff_field_count"]==9 and all(len(x["accountable_role_types"])==2 and len(x["required_handoff_fields"])==9 for x in rows),"all_waiting_zero":all(x["current_status"].startswith("WAITING") and x["named_owner_assignment_count"]==x["accepted_handoff_count"]==x["accepted_case_disposition_count"]==0 and x["counting_effect"]=="ZERO" for x in rows),"non_additive_1404":summary["exact_non_duplicated_additive_count"]==0 and summary["design_lower_bound_before_priority_handoff"]==summary["design_lower_bound_after_priority_handoff"]==1404,"execution_readiness_zero":summary["executed_case_count"]==summary["owner_approved_case_count"]==summary["command_ready_module_count"]==summary["pilot_ready_module_count"]==0,"base_stable":summary["risk_count"]==84 and summary["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_action_alias_handoff_priority_matrix_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","scope":{"mode":"OFFLINE_ACTION_ALIAS_HANDOFF_PRIORITY_DESIGN","continuation_complete":False},"safety":{"database_connections":0,"golden_uat_or_operational_execution":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"write_access_created":0,"raw_business_values_identity_or_credentials_persisted":0},"summary":summary,"priority_lane_definitions":LANES,"handoff_field_schema":FIELDS,"handoff_packets":rows,"priority_rule":"risk-first ordering is a review queue only; it does not assign a named owner, accept an alias, or authorize execution","checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":p.stat().st_size,"sha256":sha(p)} for k,p in sorted(paths.items())]+[{"name":"builder","path":"scripts/windows/build_varanegar_action_alias_handoff_priority_matrix_20260829.py","size_bytes":Path(__file__).stat().st_size,"sha256":sha(Path(__file__))}],"limits":["Priority is a static review heuristic, not production severity or readiness.","Role types are accountability placeholders and are not named-owner assignments.","All 203 cases retain zero counting effect until explicit evidence-backed disposition."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(summary,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
