"""Chain the reporting/output traceability/risk evidence delta."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];SOURCES={"delta":"artifacts/varanegar_analysis/varanegar_reporting_output_traceability_delta_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_reporting_output_expert_playbook_checkpoint_20260829.json","builder":"scripts/windows/build_varanegar_reporting_output_traceability_delta_20260829.py","checkpoint_builder":"scripts/windows/build_varanegar_reporting_output_traceability_delta_checkpoint_20260829.py","test":"tests/test_varanegar_reporting_output_traceability_delta.py","checkpoint_test":"tests/test_varanegar_reporting_output_traceability_delta_checkpoint.py","doc":"docs/varanegar_reconstruction/REPORTING_OUTPUT_TRACEABILITY_RISK_DELTA_20260829_FA.md"}
def load(path):return json.loads(path.read_text(encoding="utf-8-sig"))
def sha(path):return hashlib.sha256(path.read_bytes()).hexdigest()
def main():
 p=argparse.ArgumentParser();p.add_argument("--output",required=True,type=Path);a=p.parse_args();paths={n:ROOT/r for n,r in SOURCES.items()};d=load(paths["delta"]);prev=load(paths["previous"]);s=d["summary"];checks={"sources_pass":d["validation"]==prev["validation"]=="PASS","scope":s["reporting_output_evidence_count"]==5 and s["requirement_contract_delta_count"]==10,"links":s["module_evidence_link_count"]==30 and s["risk_evidence_link_count"]==40 and s["unique_linked_risk_count"]==8,"base_stable":s["base_risk_count"]==84 and s["base_mapped_risk_assignment_count"]==343,"no_promotion":s["new_risk_count"]==s["runtime_readiness_promotions"]==0,"safety_zero":set(v for k,v in d["safety"].items() if k!="mode")=={0}};failed=sorted(k for k,v in checks.items() if not v);out={"artifact":"varanegar_reporting_output_traceability_delta_checkpoint_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","previous_checkpoint":{"path":SOURCES["previous"],"sha256":sha(paths["previous"])},"checks":checks,"failed_checks":failed,"source_manifest":[{"name":n,"path":SOURCES[n],"size_bytes":p.stat().st_size,"sha256":sha(p)} for n,p in sorted(paths.items())],"safety":{"commands_forms_queries_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"database_connections":0,"data_mutations":0,"sensitive_values_persisted":0}};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
