"""Chain the environment isolation/write-fence/execution-token contract."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
S={"contract":"artifacts/varanegar_analysis/varanegar_target_erp_environment_isolation_write_fence_execution_token_contract_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_target_erp_migration_cutover_snapshot_delta_reconciliation_checkpoint_20260829.json","builder":"scripts/windows/build_varanegar_target_erp_environment_isolation_write_fence_execution_token_contract_20260829.py","checkpoint_builder":"scripts/windows/build_varanegar_target_erp_environment_isolation_write_fence_execution_token_checkpoint_20260829.py","test":"tests/test_varanegar_target_erp_environment_isolation_write_fence_execution_token_contract.py","checkpoint_test":"tests/test_varanegar_target_erp_environment_isolation_write_fence_execution_token_checkpoint.py","doc":"docs/varanegar_reconstruction/TARGET_ERP_ENVIRONMENT_ISOLATION_WRITE_FENCE_EXECUTION_TOKEN_20260829_FA.md"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 p=argparse.ArgumentParser();p.add_argument("--output",required=True,type=Path);a=p.parse_args();paths={k:ROOT/v for k,v in S.items()};c=load(paths["contract"]);prev=load(paths["previous"]);s=c["summary"];checks={"sources_pass":c["validation"]==prev["validation"]=="PASS","coverage_14_49_4_196_56":(s["module_count"],s["target_command_count"],s["environment_count"],s["command_environment_assignment_count"],s["environment_fence_assignment_count"])==(14,49,4,196,56),"negative_gate_role_coverage":(s["command_negative_case_assignment_count"],s["command_gate_assignment_count"],s["command_role_assignment_count"])==(588,882,294),"tokens_connections_runs_readiness_zero":s["issued_execution_token_count"]==s["legacy_operational_connection_or_command_count"]==s["target_sandbox_command_run_count"]==s["target_uat_command_run_count"]==s["target_production_command_run_count"]==s["command_ready_count"]==s["pilot_ready_module_count"]==0,"base_stable":s["risk_count"]==84 and s["mapped_risk_assignment_count"]==343 and s["design_lower_bound_after_environment_contract"]==1404,"safety_zero":set(c["safety"].values())=={0}};failed=sorted(k for k,v in checks.items() if not v);out={"artifact":"varanegar_target_erp_environment_isolation_write_fence_execution_token_checkpoint_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","previous_checkpoint":{"path":S["previous"],"sha256":sha(paths["previous"])},"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"safety":{"database_connections":0,"network_reads_or_writes":0,"execution_tokens_issued_or_consumed":0,"legacy_or_target_commands_executed":0,"operational_forms_reports_queries_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"credentials_endpoints_tokens_pii_or_raw_business_values_read_or_persisted":0}};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
