from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S={"envelope":"artifacts/varanegar_analysis/varanegar_platform_outcome_envelope_20260829.json","readiness":"artifacts/varanegar_analysis/varanegar_platform_readiness_delta_20260829.json","golden":"artifacts/varanegar_analysis/varanegar_platform_golden_uat_cases_20260829.json","playbook":"artifacts/varanegar_analysis/varanegar_platform_expert_playbook_20260829.json","deployment":"artifacts/varanegar_analysis/ui/varanegar_deployment_root_reference_scan_20260827.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_platform_expert_playbook_checkpoint_20260829.json"}
E=["PF-E-01-release-recovery-outcome-envelope","PF-E-02-readiness-delta","PF-E-03-golden-uat-delta","PF-E-04-expert-playbook","PF-E-05-static-deployment-stack-boundary"];REQ=[("PF-RQ-01","versioned approval job release and recovery control records"),("PF-RQ-02","signed immutable artifact manifest and policy binding"),("PF-RQ-03","deny-first environment action resource and SoD authorization"),("PF-RQ-04","idempotent command and immutable original receipt"),("PF-RQ-05","control commit separated from external effect receipt"),("PF-RQ-06","health reconciliation and unknown-outcome readback before retry"),("PF-RQ-07","rollback as a new command with preserved history"),("PF-RQ-08","backup restore drill failover and fencing evidence separated"),("PF-RQ-09","opaque secret references and PII-safe logs/audit"),("PF-RQ-10","approved stack hosting recovery tier capacity and operational ownership gates")];MODULES=["platform","identity_authorization","configuration","integration_migration","reporting_documents","accounting","sales","inventory"];RISKS=["R-001","R-004","R-006","R-007","R-019","R-020","R-026","R-056","R-057","R-062"]
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};known={x["id"] for x in d["risk"]["risks"]};ml=[{"evidence":e,"module":m,"relationship":"PLATFORM_DESIGN_EVIDENCE"} for e in E for m in MODULES];rl=[{"evidence":e,"risk":r,"relationship":"MITIGATION_DESIGN_NOT_CLOSURE"} for e in E for r in RISKS];req=[{"id":i,"requirement":t,"status":"DESIGNED_NOT_RUNTIME_PROVEN","evidence":E} for i,t in REQ];s={"platform_evidence_count":5,"requirement_contract_delta_count":10,"module_evidence_link_count":len(ml),"risk_evidence_link_count":len(rl),"unique_linked_risk_count":10,"base_risk_count":d["risk"]["summary"]["risk_count"],"base_mapped_risk_assignment_count":d["trace"]["summary"]["mapped_risk_assignment_count"],"new_risk_count":0,"runtime_readiness_promotions":0};checks={"sources_pass":all(v["validation"]=="PASS" for v in d.values()),"five_ten":len(E)==5 and len(req)==10,"links":len(ml)==40 and len(rl)==50,"risks_exist":set(RISKS)<=known,"scope":d["envelope"]["summary"]["command_contract_count"]==6 and d["golden"]["summary"]["combined_platform_acceptance_design_count"]==42 and d["playbook"]["summary"]["playbook_count"]==7,"deployment_pinned":d["deployment"]["summary"]["selected_file_count"]==853 and d["deployment"]["summary"]["external_occurrence_count"]==0,"base_stable":s["base_risk_count"]==84 and s["base_mapped_risk_assignment_count"]==343,"no_promotion":s["new_risk_count"]==s["runtime_readiness_promotions"]==0};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_platform_traceability_delta_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","safety":{"mode":"OFFLINE_EVIDENCE_SYNTHESIS","database_connections":0,"network_reads_or_writes":0,"platform_or_recovery_actions_executed":0,"data_mutations":0,"credentials_endpoints_pii_or_raw_business_values_read_or_persisted":0},"summary":s,"policy":{"relationship":"ADDITIVE_EVIDENCE_DELTA_ONLY","base_registers_unchanged":True,"no_risk_closure_or_runtime_promotion":True},"evidence":E,"requirements":req,"module_links":ml,"risk_links":rl,"linked_existing_risks":RISKS,"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"limits":["Risk links do not close risks.","No selected platform or runtime result is claimed."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(s,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
