"""Compare report-specific assertion/effect families for all 38 P3 case pairs."""
from __future__ import annotations
import argparse,hashlib,json
from collections import Counter
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
S={"comparator":"artifacts/varanegar_analysis/varanegar_p3_alias_semantic_evidence_comparator_20260829.json","shortlist":"artifacts/varanegar_analysis/varanegar_p3_alias_baseline_candidate_shortlist_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_p3_control_outcome_vocabulary_checkpoint_20260829.json","reporting":"artifacts/varanegar_analysis/varanegar_reporting_output_golden_uat_cases_20260829.json","report_base":"artifacts/varanegar_analysis/ui/varanegar_report_target_contracts_golden_cases_20260827.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json"}
RULES={"transaction_atomicity":["transaction","rollback","roll back","partial"],"write_or_state":["write","mutation","state","event"],"audit":["audit"],"outbox":["outbox"],"source_immutability":["source varanegar","source untouched","erp state unchanged","zero erp writes"],"scope_confidentiality":["scope","disclos"],"version_concurrency":["version","stale"],"retry_idempotency":["retry","retried","command_id","command id","original result","duplicate"],"reconciliation_projection":["reconcil","cardex","ledger","projection","crosswalk"],"authorization_denial":["capability","auth_denied","denial"],"file_or_artifact_receipt":["file","artifact","export receipt"],"render_or_print_completion":["render","print","completion"],"per_item_partial_outcome":["per-item","per item","batch item","each batch","each import","child has an independent outcome"],"result_or_content_parity":["row count match","content hash","formula parity","result parity"]}
FAMILIES=tuple(RULES)+("mutation_scope_declared","history_scope_declared")
FIELDS=["case_pair_ids","family_signature_hashes","family_presence_mapping","newer_only_family_disposition","baseline_only_family_disposition","transaction_and_write_receipts","audit_outbox_receipts","file_artifact_and_render_completion_receipts","per_item_partial_outcome_receipt","result_content_parity_receipt","scope_version_retry_receipts","accountable_role_receipts","policy_version_expiry_supersession"]
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def action(x):return str(x.get("command") or x.get("surface") or x.get("command_id") or "")
def assertions(x):return list(x.get("expected_assertions") or x.get("assertions") or (x.get("expected") if isinstance(x.get("expected"),list) else []))+list(x.get("expected_side_effects") or [])
def families(x):
 text=" ".join(map(str,assertions(x))).casefold();r={name for name,words in RULES.items() if any(w in text for w in words)}
 if x.get("expected_mutation_scope"):r.add("mutation_scope_declared")
 if x.get("expected_ledger_or_history_scope"):r.add("history_scope_declared")
 return r
def sig(v):return hashlib.sha256("\n".join(sorted(v)).encode()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};new={x["case_id"]:x for x in d["reporting"]["cases"]};base={x["case_id"]:x for x in d["report_base"]["golden_cases"]};rows=[]
 for c in d["comparator"]["candidate_comparisons"]:
  for row in c["case_pair_comparisons"]:
   n=new[row["newer_case_id"]];b=base[row["baseline_case_id"]];nf=families(n);bf=families(b);rows.append({"comparison_id":c["comparison_id"],"source_packet_id":c["source_packet_id"],"newer_case_id":n["case_id"],"baseline_case_id":b["case_id"],"case_kind":row["case_kind"],"newer_effect_families":sorted(nf),"baseline_effect_families":sorted(bf),"newer_family_signature_sha256":sig(nf),"baseline_family_signature_sha256":sig(bf),"exact_family_set":nf==bf,"nonempty_family_overlap":bool(nf&bf),"overlapping_families":sorted(nf&bf),"newer_only_families":sorted(nf-bf),"baseline_only_families":sorted(bf-nf),"current_status":"WAITING_FOR_REPORT_ASSERTION_EFFECT_AND_RESULT_PARITY_DISPOSITION","accepted_pair_count":0,"counting_effect":"ZERO"})
 packets=[]
 for i,f in enumerate(FAMILIES,1):packets.append({"family_packet_id":f"P3E-{i:02d}","effect_family":f,"newer_pair_coverage_count":sum(f in x["newer_effect_families"] for x in rows),"baseline_pair_coverage_count":sum(f in x["baseline_effect_families"] for x in rows),"both_pair_coverage_count":sum(f in x["newer_effect_families"] and f in x["baseline_effect_families"] for x in rows),"newer_only_pair_count":sum(f in x["newer_only_families"] for x in rows),"baseline_only_pair_count":sum(f in x["baseline_only_families"] for x in rows),"required_disposition_fields":FIELDS,"current_status":"WAITING_FOR_REPORT_ASSERTION_EFFECT_AND_RESULT_PARITY_DISPOSITION","accepted_family_mapping_count":0,"counting_effect":"ZERO"})
 nc=Counter(f for x in rows for f in x["newer_effect_families"]);bc=Counter(f for x in rows for f in x["baseline_effect_families"]);s={"candidate_case_pair_count":len(rows),"effect_family_count":len(FAMILIES),"exact_family_set_pair_count":sum(x["exact_family_set"] for x in rows),"nonempty_family_overlap_pair_count":sum(x["nonempty_family_overlap"] for x in rows),"zero_family_overlap_pair_count":sum(not x["nonempty_family_overlap"] for x in rows),"newer_only_family_assignment_count":sum(len(x["newer_only_families"]) for x in rows),"baseline_only_family_assignment_count":sum(len(x["baseline_only_families"]) for x in rows),**{f"newer_{k}_pair_count":nc[k] for k in RULES},**{f"baseline_{k}_pair_count":bc[k] for k in RULES},"accountable_role_assignment_count":sum(len(x["accountable_role_types"]) for x in d["shortlist"]["p3_candidate_packets"] if x["candidate_baseline_action_count"]),"required_disposition_field_count":len(FIELDS),"accepted_family_mapping_count":0,"accepted_case_pair_count":0,"exact_non_duplicated_additive_count":0,"design_lower_bound_before_effect_family_matrix":1404,"design_lower_bound_after_effect_family_matrix":1404,"executed_case_count":0,"owner_approved_case_count":0,"command_ready_module_count":0,"pilot_ready_module_count":0,"risk_count":d["risk"]["summary"]["risk_count"],"mapped_risk_assignment_count":d["trace"]["summary"]["mapped_risk_assignment_count"],"new_risk_count":0}
 checks={"sources_pass":all(x.get("validation")=="PASS" for x in d.values()),"38_pairs_16_families":s["candidate_case_pair_count"]==38 and s["effect_family_count"]==16,"overlap_0_38_0":(s["exact_family_set_pair_count"],s["nonempty_family_overlap_pair_count"],s["zero_family_overlap_pair_count"])==(0,38,0),"asymmetric_174_67":(s["newer_only_family_assignment_count"],s["baseline_only_family_assignment_count"])==(174,67),"report_specific_newer":(s["newer_file_or_artifact_receipt_pair_count"],s["newer_render_or_print_completion_pair_count"],s["newer_per_item_partial_outcome_pair_count"],s["newer_result_or_content_parity_pair_count"])==(38,38,38,0),"report_specific_baseline":(s["baseline_file_or_artifact_receipt_pair_count"],s["baseline_render_or_print_completion_pair_count"],s["baseline_per_item_partial_outcome_pair_count"],s["baseline_result_or_content_parity_pair_count"])==(6,0,0,2),"material_asymmetry":(s["newer_audit_pair_count"],s["baseline_audit_pair_count"],s["newer_outbox_pair_count"],s["baseline_outbox_pair_count"],s["newer_transaction_atomicity_pair_count"],s["baseline_transaction_atomicity_pair_count"],s["newer_version_concurrency_pair_count"],s["baseline_version_concurrency_pair_count"])==(38,18,0,25,0,9,0,12),"roles_fields":s["accountable_role_assignment_count"]==10 and s["required_disposition_field_count"]==13,"all_waiting_zero":all(x["accepted_pair_count"]==0 and x["counting_effect"]=="ZERO" for x in rows) and all(x["accepted_family_mapping_count"]==0 for x in packets),"non_additive_1404":s["accepted_family_mapping_count"]==s["accepted_case_pair_count"]==s["exact_non_duplicated_additive_count"]==0 and s["design_lower_bound_before_effect_family_matrix"]==s["design_lower_bound_after_effect_family_matrix"]==1404,"execution_readiness_zero":s["executed_case_count"]==s["owner_approved_case_count"]==s["command_ready_module_count"]==s["pilot_ready_module_count"]==0,"base_stable":s["risk_count"]==84 and s["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_p3_assertion_effect_family_gap_matrix_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","scope":{"mode":"OFFLINE_P3_REPORT_ASSERTION_EFFECT_FAMILY_GAP_ANALYSIS","continuation_complete":False},"safety":{"database_connections":0,"golden_uat_or_operational_execution":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"write_access_created":0,"raw_business_values_identity_or_credentials_persisted":0},"summary":s,"classification_rules":RULES,"required_disposition_fields":FIELDS,"effect_family_gap_packets":packets,"case_pair_family_signatures":rows,"interpretation_rule":"keyword-family signatures are conservative routing evidence; file/render overlap is not result/content parity or semantic effect equivalence","checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":p.stat().st_size,"sha256":sha(p)} for k,p in sorted(paths.items())]+[{"name":"builder","path":"scripts/windows/build_varanegar_p3_assertion_effect_family_gap_matrix_20260829.py","size_bytes":Path(__file__).stat().st_size,"sha256":sha(Path(__file__))}],"limits":["Classifier uses documented assertion/effect text only.","Result/content parity requires fixtures and values, not keyword overlap.","No family mapping or case pair is accepted."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(s,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
