from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S={"envelope":"artifacts/varanegar_analysis/varanegar_platform_outcome_envelope_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_master_data_traceability_delta_checkpoint_20260829.json","builder":"scripts/windows/build_varanegar_platform_outcome_envelope_20260829.py","checkpoint_builder":"scripts/windows/build_varanegar_platform_outcome_checkpoint_20260829.py","test":"tests/test_varanegar_platform_outcome_envelope.py","checkpoint_test":"tests/test_varanegar_platform_outcome_checkpoint.py","doc":"docs/varanegar_reconstruction/PLATFORM_RELEASE_RECOVERY_OUTCOME_CONTRACT_20260829_FA.md"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d=load(paths["envelope"]);prev=load(paths["previous"]);s=d["summary"];checks={"sources_pass":d["validation"]==prev["validation"]=="PASS","six_commands":s["command_contract_count"]==6,"blueprint_three":s["blueprint_platform_command_count"]==3,"deployment_853_zero":s["deployment_file_count"]==853 and s["deployment_external_reference_count"]==0,"decisions_zero":s["stack_selected_count"]==s["database_selected_count"]==s["hosting_selected_count"]==s["approved_recovery_target_count"]==s["deployment_owner_selected_count"]==0,"runtime_zero":s["runtime_external_effect_parity_proven_count"]==s["implemented_command_count"]==s["executed_restore_drill_count"]==0,"base_stable":s["risk_count"]==84 and s["mapped_risk_assignment_count"]==343,"safety_zero":set(v for k,v in d["safety"].items() if k!="mode")=={0}};failed=sorted(k for k,v in checks.items() if not v);out={"artifact":"varanegar_platform_outcome_checkpoint_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","previous_checkpoint":{"path":S["previous"],"sha256":sha(paths["previous"])},"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"safety":{"deployments_jobs_restores_failovers_or_rollbacks_executed":0,"database_connections":0,"network_reads_or_writes":0,"data_mutations":0,"credentials_endpoints_pii_or_raw_business_values_persisted":0}};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
