"""Advance treasury outcome-contract design coverage without promoting runtime readiness."""
from __future__ import annotations
import argparse,copy,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
S={"prior":"artifacts/varanegar_analysis/varanegar_command_readiness_delta_20260829.json","treasury":"artifacts/varanegar_analysis/varanegar_treasury_command_outcome_envelope_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_treasury_command_outcome_checkpoint_20260829.json"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};mods=copy.deepcopy(d["prior"]["modules"]);m=next(x for x in mods if x["module"]=="receivables_treasury");before=m["truth_table_dimensions"]["outcome_retry_idempotency"]["target_contract"];m["truth_table_dimensions"]["outcome_retry_idempotency"]["target_contract"]=True;m["mapped_validated_evidence"].append({"key":"treasury_outcome_envelope","path":S["treasury"],"validation":"PASS"});m["legacy_open_blockers"].append("twelve-command outcome/retry envelope is designed, but runtime outcome, atomicity, retry and owner acceptance remain unproven")
 s={"module_count":len(mods),"changed_module_count":1,"outcome_target_contract_module_count_before":d["prior"]["summary"]["outcome_target_contract_module_count_after"],"outcome_target_contract_module_count_after":sum(x["truth_table_dimensions"]["outcome_retry_idempotency"]["target_contract"] for x in mods),"treasury_command_count":d["treasury"]["summary"]["command_count"],"runtime_retry_idempotency_proven_module_count":sum(x["truth_table_dimensions"]["outcome_retry_idempotency"]["runtime_proven"] for x in mods),"command_ready_module_count":sum(x["command_ready"] for x in mods),"pilot_ready_module_count":sum(x["pilot_ready"] for x in mods),"risk_count":84,"mapped_risk_assignment_count":343,"new_risk_count":0}
 checks={"sources_pass":all(x["validation"]=="PASS" for x in d.values()),"prior_treasury_false":before is False,"treasury_now_true":m["truth_table_dimensions"]["outcome_retry_idempotency"]["target_contract"] is True,"four_to_five":s["outcome_target_contract_module_count_before"]==4 and s["outcome_target_contract_module_count_after"]==5,"only_one_changed":s["changed_module_count"]==1,"runtime_zero":s["runtime_retry_idempotency_proven_module_count"]==s["command_ready_module_count"]==s["pilot_ready_module_count"]==0,"risk_trace_stable":d["risk"]["summary"]["risk_count"]==84 and d["trace"]["summary"]["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_treasury_command_readiness_delta_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","safety":{"mode":"OFFLINE_EVIDENCE_SYNTHESIS","database_connections":0,"commands_forms_reports_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"sensitive_values_persisted":0},"summary":s,"delta":{"module":"receivables_treasury","dimension":"outcome_retry_idempotency.target_contract","before":False,"after":True,"basis":S["treasury"],"runtime_readiness_effect":"NONE"},"modules":mods,"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"confidence":{"design_delta":"HIGH","runtime_readiness":"UNPROVEN"},"limits":["This is an additive design delta over the accounting delta.","No runtime, command-ready or pilot-ready promotion is claimed."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(s,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
