"""Design synthetic Golden/UAT cases for the four distribution commands."""
from __future__ import annotations
import argparse,collections,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S={"envelope":"artifacts/varanegar_analysis/varanegar_distribution_command_outcome_envelope_20260829.json","readiness":"artifacts/varanegar_analysis/varanegar_distribution_command_readiness_delta_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_distribution_command_readiness_checkpoint_20260829.json"}
BASE=[("AUTH_DENIED","authorization","actor lacks command capability","REJECTED_NO_EFFECT"),("STALE_VERSION","concurrency","distribution expected_version is stale","REJECTED_NO_EFFECT"),("DUPLICATE_COMMAND_ID","idempotency","same command_id and payload is submitted twice","COMMITTED_ORIGINAL_OUTCOME_ONLY_ONCE"),("FAULT_AFTER_FIRST_WRITE","failure_injection","inject failure after first durable-stage candidate","REJECTED_NO_EFFECT_OR_TYPED_DURABLE_EFFECT"),("SCOPE_DENIED","scope","DC/route/resource scope is denied","REJECTED_NO_EFFECT"),("SUCCESS","success","valid current state and policy snapshot","COMMITTED")]
SPECIAL={"distribution.create_or_update":("NUMBER_HISTORY_FORK","reconciliation","allocated distribution number or sale-history link conflicts","REJECTED_NO_EFFECT"),"distribution.issue_exit":("LATE_CARDEX_CHECK","failure_injection","cardex check fails after exit/voucher/item writes","REJECTED_WITH_DURABLE_EFFECT_OR_ROLLBACK_PROOF"),"distribution.merge_or_adjust_exit":("MERGE_OWNER_UNKNOWN","reconciliation","transport fails after goods-exit relation mutation","UNKNOWN_REQUIRES_READBACK"),"distribution.remove_exit":("PARTIAL_GRAPH_CLEANUP","failure_injection","fault occurs between voucher graph deletion, sale unlink, exit cancel and distribution reset","REJECTED_WITH_DURABLE_EFFECT_OR_ROLLBACK_PROOF")}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};cases=[]
 for c in d["envelope"]["commands"]:
  for code,kind,setup,outcome in BASE+[SPECIAL[c["command"]]]:
   cases.append({"case_id":f"DS-G-{c['id'].split('-')[-1]}-{code}","command_id":c["id"],"command":c["command"],"case_kind":kind,"setup":setup,"expected_outcome":outcome,"assertions":["typed outcome matches durable distribution/exit/voucher evidence","aggregate version changes at most once","sale links, history, audit and outbox reconcile before retry","no out-of-scope effect"],"status":"DESIGNED_NOT_EXECUTED"})
 s={"command_count":4,"case_count":len(cases),"case_kind_counts":dict(sorted(collections.Counter(x["case_kind"] for x in cases).items())),"executed_case_count":0,"passed_runtime_case_count":0,"owner_approved_case_count":0,"runtime_retry_idempotency_proven_module_count":0,"command_ready_module_count":0,"pilot_ready_module_count":0,"risk_count":84,"mapped_risk_assignment_count":343,"new_risk_count":0};checks={"sources_pass":all(x["validation"]=="PASS" for x in d.values()),"four_commands":len(d["envelope"]["commands"])==4,"seven_each":len(cases)==28 and all(sum(x["command_id"]==c["id"] for x in cases)==7 for c in d["envelope"]["commands"]),"unique_ids":len({x["case_id"] for x in cases})==28,"special_complete":set(SPECIAL)=={x["command"] for x in d["envelope"]["commands"]},"durable_and_unknown":any("DURABLE_EFFECT" in x["expected_outcome"] for x in cases) and any(x["expected_outcome"]=="UNKNOWN_REQUIRES_READBACK" for x in cases),"unexecuted":set(x["status"] for x in cases)=={"DESIGNED_NOT_EXECUTED"},"runtime_zero":s["executed_case_count"]==s["passed_runtime_case_count"]==s["owner_approved_case_count"]==s["runtime_retry_idempotency_proven_module_count"]==s["command_ready_module_count"]==s["pilot_ready_module_count"]==0,"base_stable":d["risk"]["summary"]["risk_count"]==84 and d["trace"]["summary"]["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_distribution_golden_uat_cases_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","safety":{"mode":"OFFLINE_SYNTHETIC_DESIGN","database_connections":0,"commands_forms_reports_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"sensitive_values_persisted":0},"summary":s,"execution_gate":{"environment":"isolated target only","requirements":["synthetic distribution/sale/exit fixtures","deny-first test identities","fault injection at each durable boundary","legacy-target effect comparator","owner-approved route and cancellation policies"],"promotion_rule":"all 28 cases executed with zero unexplained effect difference and owner approval"},"cases":cases,"risk_links":["R-002","R-005","R-006","R-007","R-008","R-023","R-034","R-036","R-043"],"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"confidence":{"design":"HIGH","runtime":"NOT_EXECUTED"},"limits":["These cases are designs, not UAT results.","Physical enlistment must be proven with controlled fault injection.","No command or procedure was executed."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(s,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
