"""Build Master Data version, quarantine, crosswalk and merge outcome contracts."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S={"customer_goods":"artifacts/varanegar_analysis/ui/varanegar_customer_goods_command_contracts_20260827.json","supplier":"artifacts/varanegar_analysis/ui/varanegar_supplier_master_command_contract_20260827.json","targets":"artifacts/varanegar_analysis/ui/varanegar_extension_target_contracts_20260827.json","master_golden":"artifacts/varanegar_analysis/ui/negin_erp_customer_goods_master_golden_cases_20260827.json","foundation_golden":"artifacts/varanegar_analysis/ui/negin_erp_foundation_context_pricing_golden_cases_20260827.json","extension_golden":"artifacts/varanegar_analysis/ui/varanegar_extension_golden_cases_20260827.json","customer_screens":"artifacts/varanegar_analysis/ui/negin_erp_customer_goods_web_screen_contract_candidates_20260827.json","supplier_screen":"artifacts/varanegar_analysis/ui/negin_erp_supplier_master_web_screen_contract_candidate_20260827.json","path":"artifacts/varanegar_analysis/ui/varanegar_distribution_path_diagnostic_contract_20260827.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_organization_context_traceability_delta_checkpoint_20260829.json"}
REQUEST=["command_id","payload_hash","correlation_id","master_type","aggregate_reference_hash","expected_version","organization_scope","policy_version","child_relation_set_hash","crosswalk_namespace","candidate_set_hash","approval_receipt_hash","reason_code"]
RESPONSE=["outcome_code","command_id","aggregate_reference_hash","new_version","decision_receipt_id","quarantine_or_crosswalk_version","audit_event_id","outbox_event_id","reconciliation_status","retryable","readback_required"]
OUTCOMES=["REJECTED_NO_EFFECT","COMMITTED_ACTIVE","RETIRED_WITH_REFERENCES_PRESERVED","QUARANTINED_AMBIGUOUS","CROSSWALK_PUBLISHED","MERGED_REVERSIBLY","UNKNOWN_REQUIRES_READBACK"]
CONTRACTS=[
 ("master_data.customer.save","customer","customer role, parent, DL/status, contacts and scoped child relations remain structured"),("master_data.customer.delete","customer","used customer is retired; transaction references and party-role lineage remain immutable"),
 ("master_data.goods.save","goods","barcode, supplier, package, batch and DC relations commit as versioned child sets"),("master_data.goods.delete","goods","delete cannot orphan pricing, barcode, package, stock or transaction references"),
 ("master_data.supplier.save","supplier","supplier role preserves payment-use, accounting group, contact/DL, status and cardex provenance"),("master_data.supplier.delete","supplier","payment/accounting/cardex use blocks physical delete; retirement retains role history"),
 ("party.save_pos_subscriber","pos_subscriber","PII-minimized subscriber role uses opaque identity reference and explicit duplicate policy"),
 ("master_data.quarantine_duplicate_candidate","duplicate_candidate","weak barcode/contact/name/route indicators create quarantine only and never identity collapse"),
 ("master_data.publish_crosswalk_version","master_crosswalk","source namespace, source mode, target type and evidence status are explicit and versioned"),
 ("master_data.merge_duplicate_candidate","master_merge","independent approval, full reference reconciliation and reversible redirect event are mandatory"),
]
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};cg=d["master_golden"]["cases"];fg=[x for x in d["foundation_golden"]["cases"] if x["target_module"]=="master_data"];eg=[x for x in d["extension_golden"]["cases"] if x["target_module"]=="master_data"];all_cases=cg+fg+eg;existing_commands={x["command"] for x in cg+fg}|{x["surface"] for x in eg};target=[x for x in d["targets"]["commands"] if x["command"]=="party.save_pos_subscriber"]
 commands=[{"command":c,"owner":"master_data","aggregate":agg,"special_rule":rule,"request_fields":REQUEST,"response_fields":RESPONSE,"allowed_outcomes":OUTCOMES,"authorization":"application service rechecks master-type capability, organization scope and steward/merge approval deny-first","idempotency":"same CommandId and PayloadHash returns original version/decision receipt; conflicting hash rejects","transaction_owner":"one application service owns aggregate/child versions, redirect or crosswalk, audit and outbox atomically","retry_rule":"read aggregate version, child-set hash, quarantine/crosswalk/merge receipt, audit and outbox before retry","privacy_policy":"only opaque reference and normalized-key hashes; no PII, barcode, contact, credential or raw master value","runtime_effect_parity":"UNPROVEN","status":"TARGET_DESIGN_ONLY_NOT_IMPLEMENTED"} for c,agg,rule in CONTRACTS]
 summary={"command_contract_count":len(commands),"request_field_count":len(REQUEST),"response_field_count":len(RESPONSE),"outcome_code_count":len(OUTCOMES),"customer_goods_reused_case_count":len(cg),"supplier_reused_case_count":len(fg),"subscriber_reused_case_count":len(eg),"existing_reused_case_count":len(all_cases),"existing_reused_command_count":len(existing_commands),"duplicate_reused_case_id_count":len(all_cases)-len({x["case_id"] for x in all_cases}),"legacy_target_form_count":d["customer_goods"]["summary"]["target_form_count"]+d["supplier"]["summary"]["target_form_count"],"legacy_selected_method_count":d["customer_goods"]["summary"]["selected_method_count"]+d["supplier"]["summary"]["selected_method_count"],"legacy_method_with_direct_commit_count":d["customer_goods"]["summary"]["method_with_data_context_commit_count"]+d["supplier"]["summary"]["method_with_data_context_commit_count"],"web_input_candidate_count":d["customer_screens"]["summary"]["input_control_candidate_count"]+d["supplier_screen"]["summary"]["input_control_candidate_count"],"web_input_without_static_text_count":d["customer_screens"]["summary"]["input_without_any_static_text_candidate_count"]+d["supplier_screen"]["summary"]["input_without_any_static_text_candidate_count"],"party_target_contract_count":len(target),"mode_dependent_distribution_code_count":d["path"]["summary"]["distribution_count"],"distinct_distribution_path_code_count":d["path"]["summary"]["distinct_path_code_count"],"legacy_path_master_row_count":d["path"]["summary"]["legacy_path_master_row_count"],"current_runtime_path_mode":d["path"]["summary"]["current_runtime_path_mode"],"runtime_effect_parity_proven_count":0,"implemented_command_count":0,"owner_approved_count":0,"automatic_merge_count":0,"command_ready_module_count":0,"pilot_ready_module_count":0,"risk_count":84,"mapped_risk_assignment_count":343,"new_risk_count":0}
 checks={"sources_pass":all(v["validation"]=="PASS" for v in d.values()),"ten_commands":len(commands)==10 and len({x["command"] for x in commands})==10,"envelope_complete":len(REQUEST)==13 and len(RESPONSE)==11 and len(OUTCOMES)==7,"reuse_reconciled":summary["customer_goods_reused_case_count"]==64 and summary["supplier_reused_case_count"]==32 and summary["subscriber_reused_case_count"]==18 and summary["existing_reused_case_count"]==114 and summary["existing_reused_command_count"]==7 and summary["duplicate_reused_case_id_count"]==0,"legacy_anchors":summary["legacy_target_form_count"]==3 and summary["legacy_selected_method_count"]==40 and summary["legacy_method_with_direct_commit_count"]==5,"screen_scope":summary["web_input_candidate_count"]==142 and summary["web_input_without_static_text_count"]==62,"subscriber_contract":summary["party_target_contract_count"]==1,"path_semantics":summary["mode_dependent_distribution_code_count"]==26086 and summary["distinct_distribution_path_code_count"]==7 and summary["legacy_path_master_row_count"]==0 and summary["current_runtime_path_mode"]=="MANUAL_INTEGER_CODE","no_automatic_merge":summary["automatic_merge_count"]==0 and "never identity collapse" in commands[7]["special_rule"] and "reversible" in commands[-1]["special_rule"],"privacy_contract":all("no PII" in x["privacy_policy"] for x in commands),"runtime_zero":summary["runtime_effect_parity_proven_count"]==summary["implemented_command_count"]==summary["owner_approved_count"]==summary["automatic_merge_count"]==summary["command_ready_module_count"]==summary["pilot_ready_module_count"]==0,"base_stable":d["risk"]["summary"]["risk_count"]==84 and d["trace"]["summary"]["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_master_data_outcome_envelope_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","safety":{"mode":"OFFLINE_AGGREGATE_AND_CONTRACT_SYNTHESIS","database_connections":0,"network_reads_or_writes":0,"master_data_commands_or_forms_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"pii_barcode_contact_or_raw_master_values_read_or_persisted":0},"summary":summary,"identity_crosswalk_contract":{"statuses":["UNRESOLVED","QUARANTINED","CANDIDATE","APPROVED","SUPERSEDED","REVERSED"],"namespace_dimensions":["source system","source entity type","source mode","target master type","policy version"],"negative_rules":["barcode/contact/name similarity is never identity proof","sentinel or placeholder remains quarantined","manual distribution integer code is not joined to a nonexistent route master","customer, supplier, personnel and subscriber roles are not flattened into one mutable row","merge never deletes transaction provenance or source identity history"]},"commands":commands,"checks":checks,"failed_checks":failed,"risk_links":["R-002","R-004","R-005","R-006","R-007","R-008","R-010","R-011","R-037","R-038"],"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"confidence":{"static_command_and_case_reconciliation":"HIGH","target_contract_design":"HIGH","runtime_master_effect_and_merge_parity":"UNPROVEN"},"limits":["No master form, command, merge, crosswalk, quarantine or operational procedure was executed.","No PII, barcode, contact, credential or raw master value was read or persisted.","Effective duplicates, merge approvals and runtime parity require isolated steward-approved UAT."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(summary,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
