"""Compare P0 alias candidates at case-kind, precondition, outcome, and assertion levels."""
from __future__ import annotations
import argparse,hashlib,json
from collections import Counter
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
S={"shortlist":"artifacts/varanegar_analysis/varanegar_p0_alias_baseline_candidate_shortlist_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_p0_alias_baseline_candidate_checkpoint_20260829.json","accounting":"artifacts/varanegar_analysis/varanegar_accounting_golden_uat_cases_20260829.json","treasury":"artifacts/varanegar_analysis/varanegar_treasury_golden_uat_cases_20260829.json","stock_base":"artifacts/varanegar_analysis/ui/varanegar_orchestrator_golden_cases_20260827.json","bank_base":"artifacts/varanegar_analysis/ui/negin_erp_bank_reconciliation_golden_cases_20260827.json","core_base":"artifacts/varanegar_analysis/ui/varanegar_golden_command_cases_20260827.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def action(x):return str(x.get("command") or x.get("surface") or x.get("command_id") or "")
def kind(x):return str(x.get("kind") or x.get("case_kind") or "").strip().casefold()
def norm(x):return " ".join(str(x or "").strip().casefold().split())
def precondition(x):return norm(x.get("input_variation") or x.get("setup") or x.get("variation") or x.get("synthetic_variation"))
def outcome(x):return norm(x.get("expected_outcome") or x.get("expected"))
def assertions(x):return tuple(norm(v) for v in (x.get("expected_assertions") or x.get("assertions") or []))
def digest(values):return hashlib.sha256("\n".join(values).encode()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};new_rows=d["accounting"]["cases"]+d["treasury"]["cases"];base_rows=d["stock_base"]["cases"]+d["bank_base"]["cases"]+d["core_base"]["cases"];comparisons=[];all_pairs=[]
 for packet in d["shortlist"]["p0_candidate_packets"]:
  for candidate in packet["candidate_baseline_actions"]:
   newer=[x for x in new_rows if action(x)==packet["newer_action_or_surface"]];baseline=[x for x in base_rows if action(x)==candidate["baseline_action"]];pairs=[]
   for n in newer:
    for b in baseline:
     if kind(n)!=kind(b):continue
     row={"newer_case_id":n["case_id"],"baseline_case_id":b["case_id"],"case_kind":kind(n),"precondition_exact":precondition(n)==precondition(b),"outcome_exact":outcome(n)==outcome(b),"assertion_list_exact":assertions(n)==assertions(b),"fully_exact":precondition(n)==precondition(b) and outcome(n)==outcome(b) and assertions(n)==assertions(b),"newer_outcome_label":outcome(n),"baseline_outcome_label":outcome(b),"newer_assertion_list_sha256":digest(assertions(n)),"baseline_assertion_list_sha256":digest(assertions(b))};pairs.append(row);all_pairs.append(row)
   comparisons.append({"comparison_id":f"P0C-{len(comparisons)+1:02d}","source_packet_id":packet["source_packet_id"],"newer_action_or_surface":packet["newer_action_or_surface"],"baseline_module":candidate["baseline_module"],"baseline_action":candidate["baseline_action"],"same_kind_pair_count":len(pairs),"precondition_exact_pair_count":sum(x["precondition_exact"] for x in pairs),"outcome_exact_pair_count":sum(x["outcome_exact"] for x in pairs),"assertion_list_exact_pair_count":sum(x["assertion_list_exact"] for x in pairs),"fully_exact_pair_count":sum(x["fully_exact"] for x in pairs),"pair_kind_distribution":dict(sorted(Counter(x["case_kind"] for x in pairs).items())),"case_pair_comparisons":pairs,"current_status":"REVIEW_REQUIRED_NOT_SEMANTIC_EQUIVALENCE","accepted_candidate_count":0,"accepted_case_pair_count":0,"counting_effect":"ZERO"})
 kinds=dict(sorted(Counter(x["case_kind"] for x in all_pairs).items()));summary={"candidate_action_comparison_count":len(comparisons),"same_kind_case_pair_count":len(all_pairs),"authorization_pair_count":kinds.get("authorization",0),"concurrency_pair_count":kinds.get("concurrency",0),"failure_injection_pair_count":kinds.get("failure_injection",0),"idempotency_pair_count":kinds.get("idempotency",0),"reconciliation_pair_count":kinds.get("reconciliation",0),"scope_pair_count":kinds.get("scope",0),"success_pair_count":kinds.get("success",0),"precondition_exact_pair_count":sum(x["precondition_exact"] for x in all_pairs),"outcome_exact_pair_count":sum(x["outcome_exact"] for x in all_pairs),"assertion_list_exact_pair_count":sum(x["assertion_list_exact"] for x in all_pairs),"fully_exact_pair_count":sum(x["fully_exact"] for x in all_pairs),"accepted_candidate_count":0,"accepted_case_pair_count":0,"exact_non_duplicated_additive_count":0,"design_lower_bound_before_comparator":d["shortlist"]["summary"]["design_lower_bound_after_shortlist"],"design_lower_bound_after_comparator":d["shortlist"]["summary"]["design_lower_bound_after_shortlist"],"executed_case_count":0,"owner_approved_case_count":0,"command_ready_module_count":0,"pilot_ready_module_count":0,"risk_count":d["risk"]["summary"]["risk_count"],"mapped_risk_assignment_count":d["trace"]["summary"]["mapped_risk_assignment_count"],"new_risk_count":0}
 checks={"sources_pass":all(x.get("validation")=="PASS" for k,x in d.items() if k!="core_base") and d["core_base"].get("validation") is None,"six_candidates_66_pairs":summary["candidate_action_comparison_count"]==6 and summary["same_kind_case_pair_count"]==66,"kind_distribution":(summary["authorization_pair_count"],summary["concurrency_pair_count"],summary["failure_injection_pair_count"],summary["idempotency_pair_count"],summary["reconciliation_pair_count"],summary["scope_pair_count"],summary["success_pair_count"])==(9,9,20,12,2,8,6),"exactness_0_2_0_0":(summary["precondition_exact_pair_count"],summary["outcome_exact_pair_count"],summary["assertion_list_exact_pair_count"],summary["fully_exact_pair_count"])==(0,2,0,0),"all_review_zero":all(x["current_status"].startswith("REVIEW_REQUIRED") and x["accepted_candidate_count"]==x["accepted_case_pair_count"]==0 and x["counting_effect"]=="ZERO" for x in comparisons),"non_additive_1404":summary["accepted_candidate_count"]==summary["accepted_case_pair_count"]==summary["exact_non_duplicated_additive_count"]==0 and summary["design_lower_bound_before_comparator"]==summary["design_lower_bound_after_comparator"]==1404,"execution_readiness_zero":summary["executed_case_count"]==summary["owner_approved_case_count"]==summary["command_ready_module_count"]==summary["pilot_ready_module_count"]==0,"base_stable":summary["risk_count"]==84 and summary["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_p0_alias_semantic_evidence_comparator_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","scope":{"mode":"OFFLINE_P0_CASE_PAIR_SEMANTIC_COMPARISON","continuation_complete":False},"safety":{"database_connections":0,"golden_uat_or_operational_execution":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"write_access_created":0,"raw_business_values_identity_or_credentials_persisted":0},"summary":summary,"pair_kind_distribution":kinds,"candidate_comparisons":comparisons,"interpretation_rule":"same kind and isolated exact labels are insufficient; a candidate requires explicit precondition, outcome, assertion, and effect disposition","checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":p.stat().st_size,"sha256":sha(p)} for k,p in sorted(paths.items())]+[{"name":"builder","path":"scripts/windows/build_varanegar_p0_alias_semantic_evidence_comparator_20260829.py","size_bytes":Path(__file__).stat().st_size,"sha256":sha(Path(__file__))}],"limits":["String equality is a conservative diagnostic and not semantic proof.","Assertion bodies are represented by hashes in pair rows.","No candidate or case pair is accepted and no case is executed."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(summary,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
