"""Checkpoint P3 report failure-injection adjudication."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
S={"packets":"artifacts/varanegar_analysis/varanegar_p3_failure_injection_adjudication_packets_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_p3_alias_semantic_evidence_checkpoint_20260829.json","builder":"scripts/windows/build_varanegar_p3_failure_injection_adjudication_packets_20260829.py","checkpoint_builder":"scripts/windows/build_varanegar_p3_failure_injection_adjudication_checkpoint_20260829.py","test":"tests/test_varanegar_p3_failure_injection_adjudication_packets.py","checkpoint_test":"tests/test_varanegar_p3_failure_injection_adjudication_checkpoint.py","doc":"docs/varanegar_reconstruction/P3_FAILURE_INJECTION_ADJUDICATION_PACKETS_20260829_FA.md"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};m=load(paths["packets"]);prev=load(paths["previous"]);s=m["summary"];checks={"sources_pass":m["validation"]==prev["validation"]=="PASS","five_six_18":(s["source_packet_count"],s["candidate_action_comparison_count"],s["failure_injection_pair_count"])==(5,6,18),"unique_15_6":(s["newer_unique_failure_case_count"],s["baseline_unique_failure_case_count"])==(15,6),"stages_0_18":(s["exact_fault_stage_label_pair_count"],s["different_or_normalized_stage_pair_count"])==(0,18),"properties_18_18_15_12":(s["baseline_retry_or_recovery_explicit_pair_count"],s["baseline_unknown_or_partial_disposition_explicit_pair_count"],s["baseline_audit_or_outbox_sensitive_pair_count"],s["baseline_file_print_or_completion_sensitive_pair_count"])==(18,18,15,12),"semantic_zero":s["outcome_exact_pair_count"]==s["assertion_list_exact_pair_count"]==s["fully_exact_pair_count"]==0,"non_additive_1404":s["accepted_failure_pair_count"]==s["exact_non_duplicated_additive_count"]==0 and s["design_lower_bound_before_failure_adjudication"]==s["design_lower_bound_after_failure_adjudication"]==1404,"execution_readiness_zero":s["executed_case_count"]==s["owner_approved_case_count"]==s["command_ready_module_count"]==s["pilot_ready_module_count"]==0,"base_stable":s["risk_count"]==84 and s["mapped_risk_assignment_count"]==343,"safety_zero":set(m["safety"].values())=={0}};failed=sorted(k for k,v in checks.items() if not v);out={"artifact":"varanegar_p3_failure_injection_adjudication_checkpoint_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","previous_checkpoint":{"path":S["previous"],"sha256":sha(paths["previous"])},"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"safety":{"database_connections":0,"golden_or_uat_execution":0,"data_mutations":0}};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
