"""Execute deterministic synthetic procure-to-pay vectors."""
from __future__ import annotations
import argparse,copy,hashlib,importlib.util,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];REFERENCE=ROOT/"scripts/windows/varanegar_procure_to_pay_reference.py"
S={"p2p_contract":"artifacts/varanegar_analysis/varanegar_target_erp_procure_to_pay_three_way_match_contract_20260901.json","p2p_checkpoint":"artifacts/varanegar_analysis/varanegar_target_erp_procure_to_pay_three_way_match_checkpoint_20260901.json","approval":"artifacts/varanegar_analysis/varanegar_target_erp_approval_delegation_escalation_sod_breakglass_contract_20260829.json","inventory":"artifacts/varanegar_analysis/varanegar_target_erp_inventory_lot_serial_expiry_costing_valuation_contract_20260829.json","semantics":"artifacts/varanegar_analysis/varanegar_target_erp_monetary_quantity_temporal_semantics_contract_20260829.json","tests":"artifacts/varanegar_analysis/varanegar_25h_final_test_result_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def module():s=importlib.util.spec_from_file_location("p2p_ref",REFERENCE);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return m
def main():
 p=argparse.ArgumentParser();p.add_argument("--output",required=True,type=Path);a=p.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};m=module();base=m.baseline()
 def changed(**kw):e=copy.deepcopy(base);e.update(kw);return e
 positive=[("POS-ORDER",base,"PURCHASE_ORDER_ACCEPTED_SCOPED_VERSIONED_AND_APPROVED"),("POS-RECEIVE",changed(operation="RECEIVE"),"RECEIPT_ACCEPTED_INSPECTED_AND_STOCK_LINKED"),("POS-SERVICE",changed(operation="SERVICE"),"SERVICE_ENTRY_ACCEPTED_MILESTONE_AND_EVIDENCE_LINKED"),("POS-MATCH",changed(operation="MATCH"),"THREE_WAY_MATCH_ACCEPTED_WITHIN_TOLERANCE"),("POS-RETURN",changed(operation="RETURN"),"RETURN_DEBIT_NOTE_OR_REVERSAL_ACCEPTED_WITH_LINEAGE"),("POS-RELEASE",changed(operation="RELEASE"),"HOLD_RELEASE_ACCEPTED_INDEPENDENTLY_APPROVED"),("POS-PAYMENT",changed(operation="PAYMENT"),"PAYMENT_ELIGIBLE_ALL_GATES_CURRENT"),("POS-RECONCILE",changed(operation="RECONCILE"),"P2P_RECONCILIATION_ACCEPTED_ACCRUAL_SUBLEDGER_AND_GL")]
 negative=[("NEG-EXTRA",dict(base,extra=True),"SCHEMA_INVALID"),("NEG-SCOPE",changed(scope_current=False),"P2P_REJECTED_SUPPLIER_ORGANIZATION_CURRENCY_SCOPE"),("NEG-VERSION",changed(expected_version_match=False),"P2P_REJECTED_VERSION_OR_IDEMPOTENCY"),("NEG-IDEMPOTENCY",changed(idempotency_current=False),"P2P_REJECTED_VERSION_OR_IDEMPOTENCY"),("NEG-UNKNOWN",changed(unknown_commit=True),"P2P_UNKNOWN_RECONCILIATION_REQUIRED"),("NEG-BLOCK",changed(blocking_unknown=True),"MANUAL_REVIEW_REQUIRED_BLOCKING_UNKNOWN"),("NEG-BUDGET",changed(budget_approval_current=False),"PURCHASE_ORDER_REJECTED_BUDGET_VERSION_OR_APPROVAL"),("NEG-PO-VERSION",changed(po_version_current=False),"PURCHASE_ORDER_REJECTED_BUDGET_VERSION_OR_APPROVAL"),("NEG-RECEIPT",changed(operation="RECEIVE",receipt_acceptance_current=False),"RECEIPT_REJECTED_ACCEPTANCE_SCOPE_OR_LINEAGE"),("NEG-SERVICE",changed(operation="SERVICE",service_acceptance_current=False),"SERVICE_ENTRY_REJECTED_ACCEPTANCE_OR_EVIDENCE"),("NEG-DUPLICATE",changed(operation="MATCH",invoice_identity_unique=False),"INVOICE_REJECTED_IDENTITY_DUPLICATE_OR_SCOPE"),("NEG-LINE",changed(operation="MATCH",line_identity_current=False),"THREE_WAY_MATCH_REJECTED_LINE_IDENTITY_OR_QUANTITY"),("NEG-QUANTITY",changed(operation="MATCH",quantity_invariants_current=False),"THREE_WAY_MATCH_REJECTED_LINE_IDENTITY_OR_QUANTITY"),("NEG-Q-TOL",changed(operation="MATCH",quantity_tolerance_current=False),"THREE_WAY_MATCH_HELD_QUANTITY_OR_PARTIAL_EXCEPTION"),("NEG-PARTIAL",changed(operation="MATCH",partial_over_under_policy_current=False),"THREE_WAY_MATCH_HELD_QUANTITY_OR_PARTIAL_EXCEPTION"),("NEG-PRICE",changed(operation="MATCH",price_tax_freight_tolerance_current=False),"THREE_WAY_MATCH_REJECTED_PRICE_TAX_FREIGHT_OR_ROUNDING"),("NEG-ROUND",changed(operation="MATCH",currency_rounding_current=False),"THREE_WAY_MATCH_REJECTED_PRICE_TAX_FREIGHT_OR_ROUNDING"),("NEG-RETURN",changed(operation="RETURN",return_lineage_current=False),"RETURN_REJECTED_ORIGINAL_LINEAGE"),("NEG-HOLD",changed(operation="RELEASE",hold_clear=False),"HOLD_RELEASE_REJECTED_UNRESOLVED_OR_UNAPPROVED"),("NEG-RELEASE",changed(operation="RELEASE",release_approved=False),"HOLD_RELEASE_REJECTED_UNRESOLVED_OR_UNAPPROVED"),("NEG-PAY-GATE",changed(operation="PAYMENT",payment_gates_current=False),"PAYMENT_BLOCKED_HOLD_GATE_OR_PERIOD"),("NEG-PERIOD",changed(operation="PAYMENT",period_current=False),"PAYMENT_BLOCKED_HOLD_GATE_OR_PERIOD"),("NEG-RECON",changed(operation="RECONCILE",accrual_ap_gl_reconciled=False),"P2P_RECONCILIATION_REJECTED_ACCRUAL_SUBLEDGER_OR_GL")]
 def run(vs):
  r=[]
  for i,e,x in vs:
   y=m.evaluate(e);r.append({"vector_id":i,"expected":x,"actual":y,"status":"PASS" if y==x else "FAIL"})
  return r
 pr=run(positive);nr=run(negative);allr=pr+nr;official=d["tests"];cs=d["p2p_contract"]["summary"]
 s={"reference_evaluator_implementation_count":1,"positive_vector_count":len(pr),"positive_pass_count":sum(x["status"]=="PASS" for x in pr),"negative_vector_count":len(nr),"negative_pass_count":sum(x["status"]=="PASS" for x in nr),"total_vector_count":len(allr),"total_pass_count":sum(x["status"]=="PASS" for x in allr),"distinct_typed_outcome_count":len({x["actual"] for x in allr}),"p2p_gate_count":cs["gate_count"],"p2p_module_gate_assignment_count":cs["module_gate_assignment_count"],"operational_procurement_ap_payment_or_matching_implementation_count":0,"operational_supplier_order_receipt_invoice_payment_or_ledger_read_count":0,"order_receive_accept_invoice_match_hold_release_pay_or_reconcile_run_count":0,"accepted_operational_receipt_count":0,"command_ready_module_count":0,"pilot_ready_module_count":0,"design_lower_bound_before_reference_evaluator":1404,"design_lower_bound_after_reference_evaluator":1404,"official_test_file_count":official["runner"]["test_file_count"],"official_passed_test_count":official["runner"]["passed_test_count"],"risk_count":d["risk"]["summary"]["risk_count"],"mapped_risk_assignment_count":d["trace"]["summary"]["mapped_risk_assignment_count"],"new_risk_count":0}
 checks={"sources_pass":all(d[k].get("validation")=="PASS" for k in ("p2p_contract","p2p_checkpoint","approval","inventory","semantics","tests")),"positive_8_of_8":s["positive_vector_count"]==s["positive_pass_count"]==8,"negative_23_of_23":s["negative_vector_count"]==s["negative_pass_count"]==23,"total_31_of_31":s["total_vector_count"]==s["total_pass_count"]==31,"distinct_outcomes_at_least_19":s["distinct_typed_outcome_count"]>=19,"coverage_24_336":(s["p2p_gate_count"],s["p2p_module_gate_assignment_count"])==(24,336),"operational_and_readiness_zero":all(s[k]==0 for k in ("operational_procurement_ap_payment_or_matching_implementation_count","operational_supplier_order_receipt_invoice_payment_or_ledger_read_count","order_receive_accept_invoice_match_hold_release_pay_or_reconcile_run_count","accepted_operational_receipt_count","command_ready_module_count","pilot_ready_module_count")),"non_additive_1404":s["design_lower_bound_before_reference_evaluator"]==s["design_lower_bound_after_reference_evaluator"]==1404,"official_tests_pass":official["validation"]=="PASS" and official["runner"]["bootstrap_excluded_test_file_count"]==0,"base_stable":s["risk_count"]==84 and s["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_target_erp_procure_to_pay_synthetic_reference_evaluator_contract_20260901","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","scope":{"mode":"pure_synthetic_procure_to_pay_reference_evaluator","continuation_complete":False,"operational_supplier_order_receipt_invoice_payment_or_ledger_read":False},"safety":{"database_connections":0,"network_reads_or_writes":0,"operational_supplier_order_receipt_invoice_payment_or_ledger_reads":0,"order_receive_accept_invoice_match_hold_release_pay_or_reconcile_actions_executed":0,"operational_forms_reports_queries_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"credentials_pii_or_raw_business_values_read_or_persisted":0},"summary":s,"positive_results":pr,"negative_results":nr,"outcome_precedence":["SCHEMA","SCOPE","VERSION_IDEMPOTENCY","UNKNOWN_COMMIT","BLOCKING_UNKNOWN","OPERATION_SPECIFIC_IDENTITY_AND_POLICY","RECONCILIATION","ACCEPTED"],"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())]+[{"name":"reference_evaluator","path":REFERENCE.relative_to(ROOT).as_posix(),"size_bytes":REFERENCE.stat().st_size,"sha256":sha(REFERENCE)},{"name":"builder","path":"scripts/windows/build_varanegar_target_erp_procure_to_pay_synthetic_reference_evaluator_contract_20260901.py","size_bytes":Path(__file__).stat().st_size,"sha256":sha(Path(__file__))}],"limits":["Only fixed synthetic booleans and operation labels were evaluated.","The evaluator is not a procurement AP payment bank sanction or matching provider.","Operational ordering receiving acceptance invoicing matching hold release payment reconciliation and readiness remain blocked."]}
 a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(s,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
