"""Chain the new 24-hour continuation gap map to the final prior baseline."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S={"gap":"artifacts/varanegar_analysis/varanegar_24h_continuation_gap_map_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_25h_final_baseline_bundle_20260829.json","builder":"scripts/windows/build_varanegar_24h_continuation_gap_map_20260829.py","checkpoint_builder":"scripts/windows/build_varanegar_24h_continuation_gap_checkpoint_20260829.py","test":"tests/test_varanegar_24h_continuation_gap_map.py","doc":"docs/varanegar_reconstruction/VARANEGAR_24H_CONTINUATION_GAP_MAP_20260829_FA.md"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(paths[k]) for k in ("gap","previous")};s=d["gap"]["summary"];checks={"sources_pass":d["gap"]["validation"]==d["previous"]["validation"]=="PASS","prior_baseline_pinned":d["gap"]["baseline"]["sha256"]==sha(paths["previous"]),"five_ranked_gaps":s["gap_count"]==5,"accounting_selected":s["selected_gap_id"]=="G24-ACCOUNTING-OUTCOME-LINEAGE","external_gate_separate":s["external_authority_required_count"]==1,"risk_not_inflated":s["new_risk_count"]==0,"zero_execution":set(v for k,v in d["gap"]["safety"].items() if k!="mode")=={0}};failed=sorted(k for k,v in checks.items() if not v);out={"artifact":"varanegar_24h_continuation_gap_checkpoint_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","previous_checkpoint":{"path":S["previous"],"sha256":sha(paths["previous"])},"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"safety":{"commands_forms_queries_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"database_connections":0,"data_mutations":0,"sensitive_values_persisted":0}};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
