"""Build organization/operation context snapshot and command outcome contracts."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S={"commands":"artifacts/varanegar_analysis/ui/varanegar_operational_context_command_contracts_20260827.json","screens":"artifacts/varanegar_analysis/ui/negin_erp_operational_context_web_screen_contract_candidates_20260827.json","golden":"artifacts/varanegar_analysis/ui/negin_erp_foundation_context_pricing_golden_cases_20260827.json","ngt_date":"artifacts/varanegar_analysis/domains/ngt_operation_date_boundary_20260829.json","order_runtime":"artifacts/varanegar_analysis/domains/order_sale_operation_date_runtime_20260829.json","order_sql":"artifacts/varanegar_analysis/domains/order_sale_operation_date_sql_20260829.json","legacy":"artifacts/varanegar_analysis/domains/organization_and_fiscal_year_20260826.json","stock_fields":"artifacts/varanegar_analysis/ui/varanegar_stock_accounting_context_full_fields_20260827.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_identity_authorization_traceability_delta_checkpoint_20260829.json"}
REQUEST=["command_id","payload_hash","correlation_id","expected_version","organization_scope","operational_year","fiscal_year","dc_scope","sale_office_scope","stock_scope","operation_date_window","calendar_timezone_policy_hash","context_relation_hash"]
RESPONSE=["outcome_code","command_id","context_snapshot_id","new_version","active_pointer","validation_trace_hash","audit_event_id","outbox_event_id","affected_context_count","retryable","readback_required"]
OUTCOMES=["REJECTED_NO_EFFECT","COMMITTED_DRAFT","PUBLISHED_ACTIVE","RETIRED_WITH_REFERENCES_PRESERVED","QUARANTINED_CONTEXT_MISMATCH","UNKNOWN_REQUIRES_READBACK"]
CONTRACTS=[
 ("organization_context.operational_year.save","operational_year","year label/range/calendar policy is versioned; operational and fiscal years remain distinct"),
 ("organization_context.operational_year.delete","operational_year","used year is retired, never physically erased or silently remapped"),
 ("organization_context.stock_dc.save","stock_dc_relation","DC, sale office, stock, ship type, account code and stock-type flags form one validated relation version"),
 ("organization_context.stock_dc.delete","stock_dc_relation","active document/reference use blocks deletion; retirement preserves lineage"),
 ("organization_context.publish_operation_date_window","operation_date_window","event timestamp, open/close boundary and replication date selector are separate typed concepts"),
 ("organization_context.activate_context_snapshot","context_snapshot","one immutable snapshot pins organization/year/DC/office/stock/date/calendar/timezone for the whole command"),
]
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};old=[x for x in d["golden"]["cases"] if x["target_module"]=="organization_context"];cmds=d["commands"]["contracts"];direct=sum(any(c=="Thunderstruck.DataContext.Commit" for m in x["methods"] for c in m["data_context_calls"]) for x in cmds)
 commands=[{"command":c,"owner":"organization_context","aggregate":agg,"special_rule":rule,"request_fields":REQUEST,"response_fields":RESPONSE,"allowed_outcomes":OUTCOMES,"authorization":"application service rechecks context administration capability and organization/DC scope server-side","idempotency":"same CommandId and PayloadHash returns original context version receipt; conflicting hash rejects","transaction_owner":"one application service owns relation/version append, active pointer, audit and outbox atomically","retry_rule":"read snapshot/version, pointer, relation validation trace, audit and outbox before retry","runtime_effect_parity":"UNPROVEN","status":"TARGET_DESIGN_ONLY_NOT_IMPLEMENTED"} for c,agg,rule in CONTRACTS]
 ns=d["ngt_date"]["summary"];os=d["order_sql"]["summary"];summary={"command_contract_count":len(commands),"request_field_count":len(REQUEST),"response_field_count":len(RESPONSE),"outcome_code_count":len(OUTCOMES),"existing_reused_case_count":len(old),"existing_reused_command_count":len({x["command"] for x in old}),"legacy_target_form_count":d["commands"]["summary"]["target_form_count"],"legacy_selected_method_count":d["commands"]["summary"]["selected_method_count"],"legacy_direct_commit_form_count":direct,"web_screen_candidate_count":d["screens"]["summary"]["screen_candidate_count"],"linked_synthetic_screen_case_count":d["screens"]["summary"]["linked_synthetic_golden_case_count"],"ngt_selected_operation_date_method_count":ns["selected_method_count"],"operation_date_setter_caller_count":ns["operation_date_setter_caller_count"],"operation_date_getter_caller_count":ns["operation_date_getter_caller_count"],"operation_date_sql_consumer_count":ns["sql_consumer_count"],"global_operation_date_sql_consumer_count":ns["sql_consumer_references_global_tbl_opr_date_count"],"operation_date_profile_count":os["operation_date_profile_count"],"null_operation_date_profile_count":os["null_oprdate_count"],"operation_date_after_last_date_count":os["oprdate_after_lastdate_count"],"configured_special_order_type_count":os["configured_special_order_type_count"],"server_command_revalidates_set_operation_date_permission":d["order_runtime"]["contract"]["server_command_revalidates_actor_set_operation_date_permission"],"runtime_effect_parity_proven_count":0,"implemented_command_count":0,"owner_approved_count":0,"command_ready_module_count":0,"pilot_ready_module_count":0,"risk_count":84,"mapped_risk_assignment_count":343,"new_risk_count":0}
 checks={"validated_sources_pass":all(d[k]["validation"]=="PASS" for k in ["commands","screens","golden","ngt_date","order_runtime","order_sql","stock_fields","risk","trace","previous"]),"legacy_structural_input":d["legacy"].get("domain")=="organization_and_fiscal_year","six_commands":len(commands)==6 and len({x["command"] for x in commands})==6,"envelope_complete":len(REQUEST)==13 and len(RESPONSE)==11 and len(OUTCOMES)==6,"reuse_64_four_commands":len(old)==64 and len({x["command"] for x in old})==4,"legacy_anchors":summary["legacy_target_form_count"]==3 and summary["legacy_selected_method_count"]==41 and summary["legacy_direct_commit_form_count"]==1,"screen_scope":summary["web_screen_candidate_count"]==3 and summary["linked_synthetic_screen_case_count"]==96,"date_boundary":summary["ngt_selected_operation_date_method_count"]==643 and summary["operation_date_setter_caller_count"]==1 and summary["operation_date_getter_caller_count"]==4 and summary["operation_date_sql_consumer_count"]==11 and summary["global_operation_date_sql_consumer_count"]==5,"profile_gaps":summary["operation_date_profile_count"]==10 and summary["null_operation_date_profile_count"]==3 and summary["operation_date_after_last_date_count"]==1 and summary["configured_special_order_type_count"]==2,"server_revalidation_gap":summary["server_command_revalidates_set_operation_date_permission"] is False,"typed_date_separation":all(x in commands[4]["special_rule"] for x in ["event timestamp","open/close boundary","replication date selector"]),"runtime_zero":summary["runtime_effect_parity_proven_count"]==summary["implemented_command_count"]==summary["owner_approved_count"]==summary["command_ready_module_count"]==summary["pilot_ready_module_count"]==0,"base_stable":d["risk"]["summary"]["risk_count"]==84 and d["trace"]["summary"]["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_organization_context_outcome_envelope_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","safety":{"mode":"OFFLINE_STATIC_AND_CONTRACT_SYNTHESIS","database_connections":0,"network_reads_or_writes":0,"organization_context_commands_or_forms_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"business_values_read_or_persisted":0},"summary":summary,"context_snapshot_contract":{"immutable_fields":["organization","operational year","fiscal year","DC","sale office","stock","operation-date window","calendar/timezone policy","StockDC relation version"],"typed_date_concepts":["business event timestamp","open/close operation boundary","document/replication date selector","server clock"],"validation_rules":["all relation members are active in the same approved organization scope","missing/null boundary rejects or quarantines; no ambient default","special order-type exception skips only its named open-date check","a command reads one ContextSnapshotId and never a mutable ambient context mid-flight"],"required_trace":["candidate relation/version ids","scope and activity decisions","date concept and boundary source","winner snapshot","policy/schema hash"]},"commands":commands,"checks":checks,"failed_checks":failed,"risk_links":["R-002","R-005","R-006","R-007","R-008","R-023","R-024","R-033","R-034"],"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"confidence":{"static_context_and_date_boundaries":"HIGH","target_contract_design":"HIGH","runtime_context_result_parity":"UNPROVEN"},"limits":["No context form, command, date change or operational procedure was executed.","No raw business values are persisted; only aggregate counts and contract rules are used.","Current effective context and command parity require isolated owner-approved UAT."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(summary,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
