"""Group 203 unmatched cases into accountable action-alias evidence packets."""
from __future__ import annotations
import argparse,hashlib,json
from collections import defaultdict
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
S={"queue":"artifacts/varanegar_analysis/varanegar_unmatched_golden_case_alias_work_queue_20260829.json","five":"artifacts/varanegar_analysis/varanegar_five_case_kind_multiplicity_disposition_packets_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_five_case_kind_multiplicity_disposition_checkpoint_20260829.json"}
FIELDS=["newer_action_or_surface","candidate_baseline_action_or_explicit_none","versioned_alias_id","case_id_set_hash","case_kind_coverage","precondition_mapping","outcome_vocabulary_mapping","assertion_and_effect_mapping","accountable_disposition_and_rationale","policy_version_and_expiry"]
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def roles(module,action):
 if module=="pricing_rules":return ["PRICING_POLICY_OWNER_ROLE","PRICING_APPLICATION_OWNER_ROLE"]
 if module=="receivables_treasury":
  second="BANK_RECONCILIATION_OWNER_ROLE" if "bank_reconciliation" in action else "INTEGRATION_REPLICATION_OWNER_ROLE" if "tour_payment" in action else "TREASURY_APPLICATION_OWNER_ROLE"
  return ["TREASURY_DOMAIN_OWNER_ROLE",second]
 if module=="accounting":return ["ACCOUNTING_DOMAIN_OWNER_ROLE","INVENTORY_ACCOUNTING_CROSS_MODULE_OWNER_ROLE" if "stock_voucher" in action else "ACCOUNTING_APPLICATION_OWNER_ROLE"]
 second="DATA_EXPORT_POLICY_OWNER_ROLE" if ".export_" in action else "BANK_STATEMENT_OWNER_ROLE" if ".import_or_command_" in action else "DOCUMENT_PRINT_OWNER_ROLE"
 return ["REPORT_RESULT_OWNER_ROLE",second]
def alias_class(module,action):
 if module=="pricing_rules":return "PRICING_RULE_ACTION_ALIAS"
 if module=="receivables_treasury":return "BANK_RECONCILIATION_ACTION_ALIAS" if "bank_reconciliation" in action else "TOUR_PAYMENT_INTEGRATION_ALIAS" if "tour_payment" in action else "TREASURY_ACTION_ALIAS"
 if module=="accounting":return "CROSS_MODULE_STOCK_ACCOUNTING_ALIAS" if "stock_voucher" in action else "ACCOUNTING_ACTION_ALIAS"
 return "REPORT_EXPORT_ACTION_ALIAS" if ".export_" in action else "REPORT_IMPORT_COMMAND_ALIAS" if ".import_or_command_" in action else "REPORT_PRINT_ACTION_ALIAS"
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};groups=defaultdict(list)
 for row in d["queue"]["work_queue"]:
  if row["gap_class"]=="ACTION_ALIAS_REQUIRED":groups[(row["module"],row["newer_action_or_surface"])].append(row)
 packets=[]
 for index,((module,action),rows) in enumerate(sorted(groups.items()),1):
  case_ids=sorted(x["newer_case_id"] for x in rows);case_hash=hashlib.sha256("\n".join(case_ids).encode()).hexdigest();packets.append({"packet_id":f"AAP-{index:02d}","module":module,"newer_action_or_surface":action,"alias_class":alias_class(module,action),"case_count":len(rows),"case_ids":case_ids,"case_id_set_sha256":case_hash,"case_kinds":sorted({x["newer_case_kind"] for x in rows}),"accountable_role_types":roles(module,action),"required_packet_fields":FIELDS,"current_status":"WAITING_FOR_VERSIONED_ALIAS_AND_OWNER_DISPOSITION","accepted_packet_count":0,"accepted_case_disposition_count":0,"counting_effect":"ZERO"})
 module_packets={m:sum(x["module"]==m for x in packets) for m in ("pricing_rules","receivables_treasury","accounting","reporting_documents")};module_cases={m:sum(x["case_count"] for x in packets if x["module"]==m) for m in module_packets};summary={"action_alias_packet_count":len(packets),"covered_unmatched_case_count":sum(x["case_count"] for x in packets),"pricing_packet_count":module_packets["pricing_rules"],"pricing_case_count":module_cases["pricing_rules"],"treasury_packet_count":module_packets["receivables_treasury"],"treasury_case_count":module_cases["receivables_treasury"],"accounting_packet_count":module_packets["accounting"],"accounting_case_count":module_cases["accounting"],"reporting_packet_count":module_packets["reporting_documents"],"reporting_case_count":module_cases["reporting_documents"],"accountable_role_assignment_count":sum(len(x["accountable_role_types"]) for x in packets),"distinct_accountable_role_type_count":len({r for x in packets for r in x["accountable_role_types"]}),"required_packet_field_count":len(FIELDS),"accepted_action_alias_packet_count":0,"accepted_case_disposition_count":0,"exact_non_duplicated_additive_count":0,"design_lower_bound_before_alias_packets":d["queue"]["summary"]["design_lower_bound_after_queue"],"design_lower_bound_after_alias_packets":d["queue"]["summary"]["design_lower_bound_after_queue"],"executed_case_count":0,"owner_approved_case_count":0,"command_ready_module_count":0,"pilot_ready_module_count":0,"risk_count":d["risk"]["summary"]["risk_count"],"mapped_risk_assignment_count":d["trace"]["summary"]["mapped_risk_assignment_count"],"new_risk_count":0}
 checks={"sources_pass":all(x.get("validation")=="PASS" for x in d.values()),"twenty_nine_packets_203_cases":summary["action_alias_packet_count"]==29 and summary["covered_unmatched_case_count"]==d["queue"]["summary"]["action_alias_required_count"]==203,"module_split":(summary["pricing_packet_count"],summary["pricing_case_count"],summary["treasury_packet_count"],summary["treasury_case_count"],summary["accounting_packet_count"],summary["accounting_case_count"],summary["reporting_packet_count"],summary["reporting_case_count"])==(4,28,11,77,6,42,8,56),"seven_cases_each":all(x["case_count"]==7 for x in packets),"roles_and_fields":summary["accountable_role_assignment_count"]==58 and summary["required_packet_field_count"]==10 and all(len(x["accountable_role_types"])==2 and len(x["required_packet_fields"])==10 for x in packets),"all_waiting_zero":all(x["current_status"].startswith("WAITING") and x["accepted_packet_count"]==x["accepted_case_disposition_count"]==0 and x["counting_effect"]=="ZERO" for x in packets),"non_additive_1404":summary["accepted_action_alias_packet_count"]==summary["accepted_case_disposition_count"]==summary["exact_non_duplicated_additive_count"]==0 and summary["design_lower_bound_before_alias_packets"]==summary["design_lower_bound_after_alias_packets"]==1404,"execution_readiness_zero":summary["executed_case_count"]==summary["owner_approved_case_count"]==summary["command_ready_module_count"]==summary["pilot_ready_module_count"]==0,"base_stable":summary["risk_count"]==84 and summary["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_action_alias_owner_evidence_packet_matrix_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","scope":{"mode":"OFFLINE_ACTION_ALIAS_OWNER_EVIDENCE_PACKET_DESIGN","continuation_complete":False},"safety":{"database_connections":0,"golden_uat_or_operational_execution":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"write_access_created":0,"raw_business_values_identity_or_credentials_persisted":0},"summary":summary,"packet_field_schema":FIELDS,"action_alias_packets":packets,"handoff_rule":"one accepted current packet per action; case dispositions remain explicit and never inherit acceptance by name similarity alone","checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":p.stat().st_size,"sha256":sha(p)} for k,p in sorted(paths.items())]+[{"name":"builder","path":"scripts/windows/build_varanegar_action_alias_owner_evidence_packet_matrix_20260829.py","size_bytes":Path(__file__).stat().st_size,"sha256":sha(Path(__file__))}],"limits":["Packet design does not supply or accept an alias.","All 203 covered cases retain zero counting effect.","No case was executed and no readiness state was promoted."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(summary,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
