from __future__ import annotations
import argparse,collections,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S={"envelope":"artifacts/varanegar_analysis/varanegar_platform_outcome_envelope_20260829.json","readiness":"artifacts/varanegar_analysis/varanegar_platform_readiness_delta_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_platform_readiness_checkpoint_20260829.json"}
F={"PF-APR":"platform.approval_decision","PF-JOB":"platform.job_retry","PF-REL":"platform.release_publish","PF-RBK":"platform.release_rollback","PF-RST":"platform.restore_drill_attestation","PF-EXT":"platform.external_effect_receipt"};CA=[("AUTH_DENIED","authorization","REJECTED_NO_EFFECT"),("STALE_CONTROL","concurrency","REJECTED_NO_EFFECT"),("DUPLICATE_COMMAND","idempotency","ORIGINAL_RECEIPT_ONLY_ONCE"),("INVALID_MANIFEST_OR_POLICY","validation","REJECTED_NO_EFFECT"),("FAIL_AFTER_CONTROL_COMMIT","failure_injection","UNKNOWN_EXTERNAL_EFFECT_REQUIRES_READBACK"),("PARALLEL_DECISION","concurrency","ONE_VERSIONED_DECISION"),("SUCCESS","success","COMMITTED_WITH_AUDIT_OUTBOX_HEALTH_AND_RECONCILIATION_RECEIPTS")]
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};cases=[{"case_id":f"{pre}-{code}","surface":surf,"case_kind":kind,"expected_outcome":out,"assertions":["CommandId PayloadHash ExpectedControlVersion manifest and policy govern replay","control audit and outbox reconcile before external effect claim","external success requires health and reconciliation receipt; local commit alone is insufficient","no credential endpoint secret PII or raw business value appears","no operational Varanegar or target platform action is performed"],"status":"DESIGNED_NOT_EXECUTED"} for pre,surf in F.items() for code,kind,out in CA]
 s={"existing_reused_case_count":0,"delta_surface_count":6,"delta_case_count":len(cases),"combined_platform_acceptance_design_count":len(cases),"case_count_per_delta_surface":7,"case_kind_counts":dict(sorted(collections.Counter(x["case_kind"] for x in cases).items())),"executed_delta_case_count":0,"passed_runtime_case_count":0,"owner_approved_case_count":0,"deployment_restore_or_rollback_executed_count":0,"command_ready_module_count":0,"pilot_ready_module_count":0,"risk_count":84,"mapped_risk_assignment_count":343,"new_risk_count":0};checks={"sources_pass":all(v["validation"]=="PASS" for v in d.values()),"delta_42":len(cases)==42 and len({x["case_id"] for x in cases})==42,"six_by_seven":all(sum(x["surface"]==surf for x in cases)==7 for surf in F.values()),"all_unexecuted":{x["status"] for x in cases}=={"DESIGNED_NOT_EXECUTED"},"coverage_14":d["readiness"]["summary"]["outcome_target_contract_module_count_after"]==14,"runtime_zero":s["executed_delta_case_count"]==s["passed_runtime_case_count"]==s["owner_approved_case_count"]==s["deployment_restore_or_rollback_executed_count"]==s["command_ready_module_count"]==s["pilot_ready_module_count"]==0,"base_stable":d["risk"]["summary"]["risk_count"]==84 and d["trace"]["summary"]["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_platform_golden_uat_cases_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","safety":{"mode":"OFFLINE_SYNTHETIC_DESIGN","database_connections":0,"network_reads_or_writes":0,"deployments_jobs_restores_failovers_or_rollbacks_executed":0,"data_mutations":0,"credentials_endpoints_pii_or_raw_business_values_read_or_persisted":0},"summary":s,"execution_gate":{"environment":"isolated selected target only","requirements":["approved stack hosting database recovery tier and owners","signed synthetic manifests and opaque references","fault injection around control/external boundaries","restore and rollback harness with reconciliation","owner-approved service objectives"],"promotion_rule":"all 42 cases execute with zero unexplained control/external-effect difference and owner approval"},"cases":cases,"checks":checks,"failed_checks":failed,"risk_links":["R-001","R-004","R-006","R-007","R-019","R-020","R-026","R-056","R-057","R-062"],"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"limits":["These are designs, not UAT results.","No platform or recovery action was executed."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(s,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
