"""Build chained checkpoint for RPT-18 healthy-cardex report."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
S={"contract":"artifacts/varanegar_analysis/domains/healthy_cardex_report_contract_20260829.json","boundary":"artifacts/varanegar_analysis/domains/healthy_cardex_report_boundary_20260829.json","catalog":"artifacts/varanegar_analysis/domains/healthy_cardex_sql_catalog_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_return_report_checkpoint_20260829.json","il_extractor":"scripts/windows/extract_varanegar_healthy_cardex_report_boundary_20260829.py","sql_extractor":"scripts/sql/extract_varanegar_healthy_cardex_sql_catalog_20260829.py","builder":"scripts/windows/build_varanegar_healthy_cardex_report_contract_20260829.py","checkpoint_builder":"scripts/windows/build_varanegar_healthy_cardex_checkpoint_20260829.py","test":"tests/test_varanegar_healthy_cardex_report_contract.py","doc":"docs/varanegar_reconstruction/HEALTHY_CARDEX_REPORT_AND_PRINT_ATTEMPT_BOUNDARY_20260829_FA.md"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(paths[k]) for k in("contract","boundary","catalog","previous")};c=d["contract"];checks={"sources_pass":all(d[k]["validation"]=="PASS" for k in d),"two_exact_queries":c["summary"]["exact_query_binding_count"]==2,"print_attempt_before_render":c["summary"]["print_attempt_before_render_count"]==1,"dynamic_where_caveated":c["summary"]["dynamic_where_query_count"]==1,"parity_not_claimed":c["summary"]["result_parity_proven_count"]==0,"risk_stable":c["summary"]["risk_count"]==84,"safe_clone":d["catalog"]["safety"]["database_updateability"]=="READ_ONLY" and d["catalog"]["safety"]["can_update"]==0 and d["catalog"]["safety"]["denies_data_writes"]==1,"zero_execution":set(v for k,v in c["safety"].items() if k!="mode")=={0}};failed=sorted(k for k,v in checks.items() if not v);p={"artifact":"varanegar_healthy_cardex_checkpoint_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","previous_checkpoint":{"path":S["previous"],"sha256":sha(paths["previous"])},"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"safety":{"report_or_procedure_executions":0,"ui_or_export_actions":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"sensitive_values_persisted":0}};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(p,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(p["validation"]);return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
