"""Chain the 42 accounting Golden/UAT designs."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S={"cases":"artifacts/varanegar_analysis/varanegar_accounting_golden_uat_cases_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_command_readiness_delta_checkpoint_20260829.json","builder":"scripts/windows/build_varanegar_accounting_golden_uat_cases_20260829.py","checkpoint_builder":"scripts/windows/build_varanegar_accounting_golden_uat_checkpoint_20260829.py","test":"tests/test_varanegar_accounting_golden_uat_cases.py","doc":"docs/varanegar_reconstruction/ACCOUNTING_GOLDEN_UAT_CASES_20260829_FA.md"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(paths[k]) for k in ("cases","previous")};s=d["cases"]["summary"];checks={"sources_pass":d["cases"]["validation"]==d["previous"]["validation"]=="PASS","six_commands":s["command_count"]==6,"forty_two_cases":s["case_count"]==42,"runtime_owner_zero":s["executed_case_count"]==s["passed_runtime_case_count"]==s["owner_approved_case_count"]==0,"false_family_removed":s["rejected_false_command_case_count"]==1,"risk_stable":s["risk_count"]==84 and s["new_risk_count"]==0,"zero_execution":set(v for k,v in d["cases"]["safety"].items() if k!="mode")=={0}};failed=sorted(k for k,v in checks.items() if not v);out={"artifact":"varanegar_accounting_golden_uat_checkpoint_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","previous_checkpoint":{"path":S["previous"],"sha256":sha(paths["previous"])},"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"safety":{"commands_forms_queries_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"database_connections":0,"data_mutations":0,"sensitive_values_persisted":0}};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
