"""Execute deterministic synthetic output-rendering vectors."""
from __future__ import annotations
import argparse,copy,hashlib,importlib.util,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];REFERENCE=ROOT/"scripts/windows/varanegar_output_rendering_reference.py"
S={"output_contract":"artifacts/varanegar_analysis/varanegar_target_erp_output_print_pdf_label_barcode_rendering_integrity_contract_20260829.json","output_checkpoint":"artifacts/varanegar_analysis/varanegar_target_erp_output_print_pdf_label_barcode_rendering_integrity_checkpoint_20260829.json","semantics":"artifacts/varanegar_analysis/varanegar_target_erp_monetary_quantity_temporal_semantics_contract_20260829.json","numbering":"artifacts/varanegar_analysis/varanegar_target_erp_document_numbering_series_void_rollover_contract_20260829.json","authorization":"artifacts/varanegar_analysis/varanegar_target_erp_command_authorization_scope_decision_trace_contract_20260829.json","file_integrity":"artifacts/varanegar_analysis/varanegar_target_erp_file_attachment_import_export_integrity_contract_20260829.json","tests":"artifacts/varanegar_analysis/varanegar_25h_final_test_result_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def module():s=importlib.util.spec_from_file_location("out_ref",REFERENCE);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return m
def main():
 p=argparse.ArgumentParser();p.add_argument("--output",required=True,type=Path);a=p.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};m=module();base=m.baseline()
 def changed(**kw):e=copy.deepcopy(base);e.update(kw);return e
 positive=[("POS-FILE",base,"OUTPUT_RENDER_ACCEPTED_DETERMINISTIC_AND_SCOPED"),("POS-PRINT",changed(delivery_state="PRINT_ACK"),"PRINT_ACKNOWLEDGED_AND_RECONCILED"),("POS-UNKNOWN",changed(delivery_state="PRINT_UNKNOWN"),"PRINT_UNKNOWN_RECONCILIATION_REQUIRED"),("POS-PREVIEW",changed(copy_state="PREVIEW"),"PREVIEW_ACCEPTED_WATERMARKED_AND_NONFINAL"),("POS-REPRINT",changed(copy_state="REPRINT"),"REPRINT_ACCEPTED_WATERMARKED_AND_LINKED"),("POS-NO-BARCODE",changed(barcode_present=False),"OUTPUT_RENDER_ACCEPTED_DETERMINISTIC_AND_SCOPED")]
 negative=[("NEG-EXTRA",dict(base,extra=True),"SCHEMA_INVALID"),("NEG-TEMPLATE",changed(template_current=False),"OUTPUT_REJECTED_TEMPLATE_OR_DATA_SNAPSHOT"),("NEG-DATA",changed(data_snapshot_current=False),"OUTPUT_REJECTED_TEMPLATE_OR_DATA_SNAPSHOT"),("NEG-RENDERER",changed(renderer_current=False),"OUTPUT_REJECTED_RENDERER_OR_DEPENDENCY"),("NEG-FONT",changed(font_embedding_ok=False),"OUTPUT_REJECTED_FONT_GLYPH_OR_RTL"),("NEG-RTL",changed(rtl_bidi_ok=False),"OUTPUT_REJECTED_FONT_GLYPH_OR_RTL"),("NEG-LOCALE",changed(locale_current=False),"OUTPUT_REJECTED_LOCALE_CALENDAR_OR_NUMERIC_SEMANTICS"),("NEG-NUMERIC",changed(numeric_semantics_current=False),"OUTPUT_REJECTED_LOCALE_CALENDAR_OR_NUMERIC_SEMANTICS"),("NEG-LAYOUT",changed(layout_ok=False),"OUTPUT_REJECTED_LAYOUT_PAGINATION_OR_MEDIA"),("NEG-PAGE",changed(pagination_ok=False),"OUTPUT_REJECTED_LAYOUT_PAGINATION_OR_MEDIA"),("NEG-BARCODE-PAYLOAD",changed(barcode_payload_current=False),"BARCODE_REJECTED_PAYLOAD_CHECK_DIGIT_OR_SCAN"),("NEG-CHECK",changed(check_digit_ok=False),"BARCODE_REJECTED_PAYLOAD_CHECK_DIGIT_OR_SCAN"),("NEG-QUIET",changed(quiet_zone_ok=False),"BARCODE_REJECTED_PAYLOAD_CHECK_DIGIT_OR_SCAN"),("NEG-DECODE",changed(machine_decode_ok=False),"BARCODE_REJECTED_PAYLOAD_CHECK_DIGIT_OR_SCAN"),("NEG-QR",changed(qr_payload_current=False),"QR_REJECTED_PAYLOAD_SIGNATURE_OR_EXPIRY"),("NEG-AUTH",changed(authorization_redaction_current=False),"OUTPUT_REJECTED_AUTHORIZATION_REDACTION_OR_AUDIENCE"),("NEG-WATERMARK",changed(copy_state="COPY",watermark_current=False),"OUTPUT_REJECTED_COPY_WATERMARK_OR_LINEAGE"),("NEG-LINEAGE",changed(copy_state="REPRINT",lineage_current=False),"OUTPUT_REJECTED_COPY_WATERMARK_OR_LINEAGE"),("NEG-PDF",changed(pdf_archival_digest_signature_current=False),"PDF_REJECTED_ARCHIVAL_DIGEST_OR_SIGNATURE"),("NEG-ACCESS",changed(accessibility_current=False),"OUTPUT_REJECTED_ACCESSIBILITY_OR_READING_ORDER"),("NEG-UNKNOWN",changed(blocking_unknown=True),"MANUAL_REVIEW_REQUIRED_BLOCKING_UNKNOWN")]
 def run(vs):
  r=[]
  for i,e,x in vs:
   y=m.evaluate(e);r.append({"vector_id":i,"expected":x,"actual":y,"status":"PASS" if y==x else "FAIL"})
  return r
 pr=run(positive);nr=run(negative);allr=pr+nr;official=d["tests"];cs=d["output_contract"]["summary"]
 s={"reference_evaluator_implementation_count":1,"positive_vector_count":len(pr),"positive_pass_count":sum(x["status"]=="PASS" for x in pr),"negative_vector_count":len(nr),"negative_pass_count":sum(x["status"]=="PASS" for x in nr),"total_vector_count":len(allr),"total_pass_count":sum(x["status"]=="PASS" for x in allr),"distinct_typed_outcome_count":len({x["actual"] for x in allr}),"output_gate_count":cs["gate_count"],"output_module_gate_assignment_count":cs["module_gate_assignment_count"],"operational_renderer_pdf_barcode_printer_or_signer_implementation_count":0,"operational_template_snapshot_document_output_barcode_or_receipt_read_count":0,"render_print_scan_sign_or_delivery_run_count":0,"accepted_operational_receipt_count":0,"command_ready_module_count":0,"pilot_ready_module_count":0,"design_lower_bound_before_reference_evaluator":1404,"design_lower_bound_after_reference_evaluator":1404,"official_test_file_count":official["runner"]["test_file_count"],"official_passed_test_count":official["runner"]["passed_test_count"],"risk_count":d["risk"]["summary"]["risk_count"],"mapped_risk_assignment_count":d["trace"]["summary"]["mapped_risk_assignment_count"],"new_risk_count":0}
 checks={"sources_pass":all(d[k].get("validation")=="PASS" for k in ("output_contract","output_checkpoint","semantics","numbering","authorization","file_integrity","tests")),"positive_6_of_6":s["positive_vector_count"]==s["positive_pass_count"]==6,"negative_21_of_21":s["negative_vector_count"]==s["negative_pass_count"]==21,"total_27_of_27":s["total_vector_count"]==s["total_pass_count"]==27,"distinct_outcomes_at_least_15":s["distinct_typed_outcome_count"]>=15,"coverage_24_336":(s["output_gate_count"],s["output_module_gate_assignment_count"])==(24,336),"operational_and_readiness_zero":all(s[k]==0 for k in ("operational_renderer_pdf_barcode_printer_or_signer_implementation_count","operational_template_snapshot_document_output_barcode_or_receipt_read_count","render_print_scan_sign_or_delivery_run_count","accepted_operational_receipt_count","command_ready_module_count","pilot_ready_module_count")),"non_additive_1404":s["design_lower_bound_before_reference_evaluator"]==s["design_lower_bound_after_reference_evaluator"]==1404,"official_tests_pass":official["validation"]=="PASS" and official["runner"]["bootstrap_excluded_test_file_count"]==0,"base_stable":s["risk_count"]==84 and s["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_target_erp_output_rendering_synthetic_reference_evaluator_contract_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","scope":{"mode":"pure_synthetic_output_rendering_reference_evaluator","continuation_complete":False,"operational_template_snapshot_document_output_barcode_or_receipt_read":False},"safety":{"database_connections":0,"network_reads_or_writes":0,"operational_template_data_snapshot_document_output_barcode_or_print_receipt_reads":0,"render_print_scan_sign_download_or_delivery_actions_executed":0,"operational_forms_reports_queries_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"credentials_certificates_tokens_pii_or_raw_business_values_read_or_persisted":0},"summary":s,"positive_results":pr,"negative_results":nr,"outcome_precedence":["SCHEMA","TEMPLATE_DATA","RENDERER_DEPENDENCY","FONT_RTL","LOCALE_NUMERIC","LAYOUT_PAGINATION","BARCODE_SCAN","QR_PAYLOAD","AUTHORIZATION_REDACTION","COPY_WATERMARK_LINEAGE","PDF_ARCHIVAL_DIGEST_SIGNATURE","ACCESSIBILITY","BLOCKING_UNKNOWN","PRINT_DELIVERY","ACCEPTED"],"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())]+[{"name":"reference_evaluator","path":REFERENCE.relative_to(ROOT).as_posix(),"size_bytes":REFERENCE.stat().st_size,"sha256":sha(REFERENCE)},{"name":"builder","path":"scripts/windows/build_varanegar_target_erp_output_rendering_synthetic_reference_evaluator_contract_20260829.py","size_bytes":Path(__file__).stat().st_size,"sha256":sha(Path(__file__))}],"limits":["Only fixed synthetic booleans and states were evaluated; no output was rendered opened printed scanned or signed.","The evaluator is not a renderer PDF validator barcode scanner printer driver or signing provider.","Operational output golden parity delivery and readiness remain blocked pending isolated artifacts and owner approval."]}
 a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(s,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
