"""Build integration/migration package, receipt, ordering and quarantine contracts."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
S={"pos_contract":"artifacts/varanegar_analysis/ui/negin_erp_pos_receipt_replication_contract_20260827.json","pos_graph":"artifacts/varanegar_analysis/ui/varanegar_pos_replication_transitive_graph_20260827.json","ngt_sale":"artifacts/varanegar_analysis/domains/ngt_sale_replication_boundary_20260829.json","ngt_sale_runtime":"artifacts/varanegar_analysis/domains/ngt_sale_replication_runtime_boundary_20260829.json","ngt_payment":"artifacts/varanegar_analysis/domains/ngt_payment_replication_boundary_20260829.json","ngt_payment_runtime":"artifacts/varanegar_analysis/domains/ngt_payment_replication_runtime_boundary_20260829.json","ngt_compensation":"artifacts/varanegar_analysis/domains/ngt_replication_compensation_boundary_20260829.json","ngt_compensation_runtime":"artifacts/varanegar_analysis/domains/ngt_replication_compensation_runtime_boundary_20260829.json","rule_transport":"artifacts/varanegar_analysis/domains/rule_replication_transport_boundary_20260828.json","migration":"artifacts/varanegar_analysis/ui/negin_erp_varanegar_migration_contract_20260827.json","extension_golden":"artifacts/varanegar_analysis/ui/varanegar_extension_golden_cases_20260827.json","treasury_golden":"artifacts/varanegar_analysis/varanegar_treasury_golden_uat_cases_20260829.json","pricing_golden":"artifacts/varanegar_analysis/varanegar_pricing_rule_golden_uat_cases_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_pricing_rule_traceability_delta_checkpoint_20260829.json"}
REQUEST=["command_id","payload_hash","correlation_id","source_system","package_or_capture_id","source_contract_hash","source_watermark","sequence_number","previous_receipt_hash","center_or_organization_scope","actor_context","operation_kind","expected_checkpoint","deadline_at"]
RESPONSE=["outcome_code","command_id","package_or_capture_id","item_receipts","accepted_sequence","aggregate_effect_receipts","crosswalk_receipts","reconciliation_receipt","quarantine_case_ids","compensation_receipt","retryable","next_checkpoint"]
OUTCOMES=["REJECTED_NO_EFFECT","STAGED_VALIDATED","APPLIED_RECONCILED","PARTIALLY_QUARANTINED","COMPENSATED","DUPLICATE_ORIGINAL_RECEIPT","UNKNOWN_BLOCKING"]
CONTRACTS=[
 {"command":"integration.pos_receipt.accept_and_apply_batch","owner":"integration_migration","legacy_or_design_anchor":"POS session send plus target POS receipt batch contract","atomic_unit":"one independently idempotent receipt effect; batch acknowledgement follows reconciliation","special_rule":"accepted items are never replayed; every other item is explicitly quarantined"},
 {"command":"integration.ngt_sale.apply_and_write_crosswalk","owner":"integration_migration","legacy_or_design_anchor":"NGT sale replication procedures and three runtime crosswalk setters","atomic_unit":"one source entity/version, target sale effect, immutable history and crosswalk receipt","special_rule":"multiple histories to the same target are history, not duplicate target effects"},
 {"command":"integration.ngt_payment.apply_and_write_crosswalk","owner":"integration_migration","legacy_or_design_anchor":"NGT payment replication and runtime crosswalk write-back","atomic_unit":"one payment source/version with payment, allocation and crosswalk receipts","special_rule":"missing target, split effect or unknown write-back blocks acknowledgement"},
 {"command":"integration.ngt_receipt.compensate","owner":"integration_migration","legacy_or_design_anchor":"type-20 rollback request and active compensation procedures","atomic_unit":"one original receipt identity plus append-only compensation receipt","special_rule":"compensation is a new idempotent command; it never erases original history"},
 {"command":"integration.rule_package.deliver_and_acknowledge","owner":"integration_migration","legacy_or_design_anchor":"rule outbox, package sender/receiver and transactional receive script","atomic_unit":"local outbox publication is separate from authenticated ordered center delivery","special_rule":"transport retry reuses package identity; database acknowledgement waits for durable verified receipt"},
 {"command":"integration.migration.import_ordered_slice","owner":"integration_migration","legacy_or_design_anchor":"twelve-slice target migration contract","atomic_unit":"one capture, ordered slice, mapping version and importer version","special_rule":"resume only from a durable slice checkpoint; blocking_unknown forbids the next slice"},
]
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 p=argparse.ArgumentParser();p.add_argument("--output",required=True,type=Path);a=p.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};valid=["pos_contract","pos_graph","ngt_sale","ngt_sale_runtime","ngt_payment","ngt_payment_runtime","ngt_compensation","ngt_compensation_runtime","extension_golden","treasury_golden","pricing_golden","risk","trace","previous"]
 ext=[x for x in d["extension_golden"]["cases"] if x.get("surface")=="pos.replicate_session_sales_receipts"];tre=[x for x in d["treasury_golden"]["cases"] if x.get("command")=="tour_payment.replicate_and_write_crosswalk"];pri=[x for x in d["pricing_golden"]["cases"] if x.get("surface")=="pricing_rules.publish_version_and_replicate"];rep=d["rule_transport"]["summary"]
 commands=[{**x,"request_fields":REQUEST,"response_fields":RESPONSE,"allowed_outcomes":OUTCOMES,"authorization":"application service rechecks operation and source/target scope deny-first","idempotency":"same CommandId and PayloadHash returns the original durable receipt; conflicting hash rejects","ordering":"sequence and previous receipt hash must form a contiguous source stream or quarantine","retry_rule":"read package, item, effect, crosswalk, reconciliation and acknowledgement receipts before retry","status":"TARGET_DESIGN_ONLY_NOT_IMPLEMENTED","runtime_effect_parity":"UNPROVEN"} for x in CONTRACTS]
 summary={"command_contract_count":len(commands),"request_field_count":len(REQUEST),"response_field_count":len(RESPONSE),"outcome_code_count":len(OUTCOMES),"existing_reused_case_count":len(ext)+len(tre)+len(pri),"existing_pos_case_count":len(ext),"existing_payment_case_count":len(tre),"existing_rule_publication_case_count":len(pri),"pos_state_count":len(d["pos_contract"]["batch_states"]),"pos_reconciliation_check_count":len(d["pos_contract"]["reconciliation_checks"]),"pos_graph_node_count":d["pos_graph"]["summary"]["node_count"],"pos_graph_unexpanded_frontier_count":d["pos_graph"]["summary"]["unexpanded_frontier_count"],"ngt_sale_multi_history_entity_count":d["ngt_sale"]["summary"]["multi_history_entity_count"],"ngt_sale_multi_target_entity_count":d["ngt_sale"]["summary"]["multi_target_entity_count"],"ngt_payment_crosswalk_setter_count":d["ngt_payment_runtime"]["summary"]["crosswalk_setter_candidate_count"],"ngt_compensation_blocker_candidate_count":d["ngt_compensation"]["summary"]["type_10_receipt_with_blocker_candidate_count"],"migration_slice_count":d["migration"]["slice_count"],"rule_transport_unproven_gate_count":sum(not rep[k] for k in ["replication_package_content_authentication_proven","replication_receipt_idempotency_proven","received_package_ordering_and_gap_check_proven","package_center_scope_preexecution_validation_proven","rejected_package_quarantine_and_retry_safety_proven","rollback_failure_observability_proven"]),"runtime_effect_parity_proven_count":0,"implemented_command_count":0,"owner_approved_count":0,"command_ready_module_count":0,"pilot_ready_module_count":0,"risk_count":84,"mapped_risk_assignment_count":343,"new_risk_count":0}
 checks={"validated_sources_pass":all(d[k]["validation"]=="PASS" for k in valid),"legacy_design_inputs_structural":d["rule_transport"]["summary"]["target_method_contract_count"]==49 and d["migration"]["slice_count"]==12,"six_commands":len(commands)==6 and len({x["command"] for x in commands})==6,"envelope_complete":len(REQUEST)==14 and len(RESPONSE)==12 and len(OUTCOMES)==7,"reuse_34":summary["existing_reused_case_count"]==34 and (len(ext),len(tre),len(pri))==(20,7,7),"pos_boundary":summary["pos_state_count"]==9 and summary["pos_reconciliation_check_count"]==9 and summary["pos_graph_node_count"]==500 and summary["pos_graph_unexpanded_frontier_count"]==160,"ngt_history_not_target_duplicate":summary["ngt_sale_multi_history_entity_count"]==138 and summary["ngt_sale_multi_target_entity_count"]==0,"ngt_payment_and_compensation":summary["ngt_payment_crosswalk_setter_count"]==2 and summary["ngt_compensation_blocker_candidate_count"]==342,"six_transport_gaps":summary["rule_transport_unproven_gate_count"]==6,"ordered_migration":summary["migration_slice_count"]==12 and commands[-1]["special_rule"].startswith("resume only"),"runtime_zero":summary["runtime_effect_parity_proven_count"]==summary["implemented_command_count"]==summary["owner_approved_count"]==summary["command_ready_module_count"]==summary["pilot_ready_module_count"]==0,"base_stable":d["risk"]["summary"]["risk_count"]==84 and d["trace"]["summary"]["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_integration_migration_outcome_envelope_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","safety":{"mode":"OFFLINE_STATIC_AND_CONTRACT_SYNTHESIS","database_connections":0,"network_reads_or_writes":0,"packages_files_or_ftp_transfers_executed":0,"commands_forms_reports_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"sensitive_values_or_payloads_persisted":0},"summary":summary,"stage_model":["STAGED","VALIDATED","READY_TO_APPLY","APPLIED","RECONCILED","ACKNOWLEDGED","QUARANTINED_OR_UNKNOWN"],"global_invariants":["package/capture identity and content hash are immutable","source/center/organization scope is verified before execution","sequence and previous receipt hash are contiguous","each item and effect is independently idempotent","crosswalk write-back has its own durable receipt","acknowledgement follows zero-difference reconciliation or explicit quarantine","compensation appends history and never deletes the original effect","unknown outcome blocks acknowledgement and downstream slices","migration resume starts only at a durable completed slice checkpoint"],"commands":commands,"legacy_input_classification":{"rule_transport":"LEGACY_STATIC_INPUT_WITHOUT_VALIDATION_GATE","migration_contract":"TARGET_DESIGN_INPUT_WITHOUT_VALIDATION_GATE"},"checks":checks,"failed_checks":failed,"risk_links":["R-002","R-005","R-006","R-007","R-008","R-023","R-029","R-034","R-036","R-043"],"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"confidence":{"static_replication_and_migration_boundaries":"HIGH","target_contract_design":"HIGH","runtime_effect_parity":"UNPROVEN"},"limits":["No source snapshot, package, FTP transfer, procedure, form or target import was executed.","The POS transitive graph is truncated at its safety cap and cannot prove a complete mutation set.","No raw package, business row, credential or principal identity is persisted."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(summary,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
