"""Compare P2 policy/lifecycle candidates with normalized legacy case schemas."""
from __future__ import annotations
import argparse,hashlib,json
from collections import Counter
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
S={"shortlist":"artifacts/varanegar_analysis/varanegar_p2_alias_baseline_candidate_shortlist_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_p2_alias_baseline_candidate_checkpoint_20260829.json","pricing":"artifacts/varanegar_analysis/varanegar_pricing_rule_golden_uat_cases_20260829.json","treasury":"artifacts/varanegar_analysis/varanegar_treasury_golden_uat_cases_20260829.json","extension":"artifacts/varanegar_analysis/ui/varanegar_extension_golden_cases_20260827.json","foundation":"artifacts/varanegar_analysis/ui/negin_erp_foundation_context_pricing_golden_cases_20260827.json","bank":"artifacts/varanegar_analysis/ui/negin_erp_bank_reconciliation_golden_cases_20260827.json","core":"artifacts/varanegar_analysis/ui/varanegar_golden_command_cases_20260827.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def action(x):return str(x.get("command") or x.get("surface") or x.get("command_id") or "")
def kind(x):
 k=str(x.get("kind") or x.get("case_kind") or x.get("category") or "").strip().casefold();return {"happy_path":"success","invariant":"validation","fault_injection":"failure_injection"}.get(k,k)
def norm(x):return " ".join(str(x or "").strip().casefold().split())
def pre(x):return norm(x.get("input_variation") or x.get("setup") or x.get("variation") or x.get("synthetic_variation"))
def outcome(x):
 v=x.get("expected_outcome") if x.get("expected_outcome") is not None else x.get("expected");return norm(v) if not isinstance(v,list) else ""
def assertions(x):
 v=x.get("expected_assertions") or x.get("assertions") or (x.get("expected") if isinstance(x.get("expected"),list) else []);return tuple(norm(z) for z in v)
def digest(v):return hashlib.sha256("\n".join(v).encode()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};new=d["pricing"]["cases"]+d["treasury"]["cases"];base=d["extension"]["cases"]+d["foundation"]["cases"]+d["bank"]["cases"]+d["core"]["cases"];comparisons=[];allpairs=[]
 for p in d["shortlist"]["p2_candidate_packets"]:
  for c in p["candidate_baseline_actions"]:
   pairs=[]
   for n in new:
    if action(n)!=p["newer_action_or_surface"]:continue
    for b in base:
     if action(b)!=c["baseline_action"] or kind(n)!=kind(b):continue
     row={"newer_case_id":n["case_id"],"baseline_case_id":b["case_id"],"case_kind":kind(n),"precondition_exact":pre(n)==pre(b),"outcome_exact":outcome(n)==outcome(b),"assertion_list_exact":assertions(n)==assertions(b),"fully_exact":pre(n)==pre(b) and outcome(n)==outcome(b) and assertions(n)==assertions(b),"newer_outcome_label":outcome(n),"baseline_outcome_label":outcome(b),"newer_assertion_list_sha256":digest(assertions(n)),"baseline_assertion_list_sha256":digest(assertions(b))};pairs.append(row);allpairs.append(row)
   comparisons.append({"comparison_id":f"P2C-{len(comparisons)+1:02d}","source_packet_id":p["source_packet_id"],"newer_action_or_surface":p["newer_action_or_surface"],"baseline_action":c["baseline_action"],"same_kind_pair_count":len(pairs),"precondition_exact_pair_count":sum(x["precondition_exact"] for x in pairs),"outcome_exact_pair_count":sum(x["outcome_exact"] for x in pairs),"assertion_list_exact_pair_count":sum(x["assertion_list_exact"] for x in pairs),"fully_exact_pair_count":sum(x["fully_exact"] for x in pairs),"pair_kind_distribution":dict(sorted(Counter(x["case_kind"] for x in pairs).items())),"case_pair_comparisons":pairs,"current_status":"REVIEW_REQUIRED_NOT_SEMANTIC_EQUIVALENCE","accepted_candidate_count":0,"accepted_case_pair_count":0,"counting_effect":"ZERO"})
 k=Counter(x["case_kind"] for x in allpairs);s={"candidate_action_comparison_count":len(comparisons),"zero_pair_candidate_comparison_count":sum(not x["same_kind_pair_count"] for x in comparisons),"same_kind_case_pair_count":len(allpairs),"authorization_pair_count":k["authorization"],"concurrency_pair_count":k["concurrency"],"failure_injection_pair_count":k["failure_injection"],"idempotency_pair_count":k["idempotency"],"scope_pair_count":k["scope"],"success_pair_count":k["success"],"validation_pair_count":k["validation"],"precondition_exact_pair_count":sum(x["precondition_exact"] for x in allpairs),"outcome_exact_pair_count":sum(x["outcome_exact"] for x in allpairs),"assertion_list_exact_pair_count":sum(x["assertion_list_exact"] for x in allpairs),"fully_exact_pair_count":sum(x["fully_exact"] for x in allpairs),"accepted_candidate_count":0,"accepted_case_pair_count":0,"exact_non_duplicated_additive_count":0,"design_lower_bound_before_comparator":1404,"design_lower_bound_after_comparator":1404,"executed_case_count":0,"owner_approved_case_count":0,"command_ready_module_count":0,"pilot_ready_module_count":0,"risk_count":d["risk"]["summary"]["risk_count"],"mapped_risk_assignment_count":d["trace"]["summary"]["mapped_risk_assignment_count"],"new_risk_count":0}
 checks={"sources_pass":all(x.get("validation")=="PASS" for key,x in d.items() if key!="core") and d["core"].get("validation") is None,"seven_candidates_73_pairs":s["candidate_action_comparison_count"]==7 and s["same_kind_case_pair_count"]==73,"one_zero_pair_candidate":s["zero_pair_candidate_comparison_count"]==1,"kind_distribution":(s["authorization_pair_count"],s["concurrency_pair_count"],s["failure_injection_pair_count"],s["idempotency_pair_count"],s["scope_pair_count"],s["success_pair_count"],s["validation_pair_count"])==(7,11,15,10,2,6,22),"exactness_0_2_0_0":(s["precondition_exact_pair_count"],s["outcome_exact_pair_count"],s["assertion_list_exact_pair_count"],s["fully_exact_pair_count"])==(0,2,0,0),"all_review_zero":all(x["accepted_candidate_count"]==x["accepted_case_pair_count"]==0 and x["counting_effect"]=="ZERO" for x in comparisons),"non_additive_1404":s["design_lower_bound_before_comparator"]==s["design_lower_bound_after_comparator"]==1404 and s["exact_non_duplicated_additive_count"]==0,"execution_readiness_zero":s["executed_case_count"]==s["owner_approved_case_count"]==s["command_ready_module_count"]==s["pilot_ready_module_count"]==0,"base_stable":s["risk_count"]==84 and s["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_p2_alias_semantic_evidence_comparator_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","scope":{"mode":"OFFLINE_P2_NORMALIZED_CASE_PAIR_SEMANTIC_COMPARISON","continuation_complete":False},"safety":{"database_connections":0,"golden_uat_or_operational_execution":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"write_access_created":0,"raw_business_values_identity_or_credentials_persisted":0},"summary":s,"pair_kind_distribution":dict(sorted(k.items())),"candidate_comparisons":comparisons,"normalization":{"category":{"happy_path":"success","invariant":"validation","fault_injection":"failure_injection"},"legacy_expected_list":"assertion_list_only_not_outcome_label"},"interpretation_rule":"normalized kind/schema alignment is diagnostic only; two isolated outcome labels do not establish precondition, assertion, or effect equivalence","checks":checks,"failed_checks":failed,"source_manifest":[{"name":key,"path":S[key],"size_bytes":p.stat().st_size,"sha256":sha(p)} for key,p in sorted(paths.items())]+[{"name":"builder","path":"scripts/windows/build_varanegar_p2_alias_semantic_evidence_comparator_20260829.py","size_bytes":Path(__file__).stat().st_size,"sha256":sha(Path(__file__))}],"limits":["Legacy expected lists are treated as assertions, not outcome labels.","One validate-transition candidate has no comparable normalized kind.","No candidate or pair is accepted."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(s,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
