"""Build a reproducible inventory of target-ERP contracts and remaining domain gaps."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];AN=ROOT/"artifacts/varanegar_analysis"
S={"previous":"artifacts/varanegar_analysis/varanegar_target_erp_project_job_costing_synthetic_reference_evaluator_checkpoint_20260901.json","official_tests":"artifacts/varanegar_analysis/varanegar_25h_final_test_result_20260829.json","final_bundle":"artifacts/varanegar_analysis/varanegar_25h_final_baseline_bundle_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json","knowledge":"docs/VARANEGAR_KNOWLEDGE_FA.md","readme":"docs/varanegar_reconstruction/README_FA.md"}
GAPS=[
 {"gap_id":"ERP-GAP-03","priority":"P1","domain":"budget_planning_forecast_commitment_and_variance","reason":"budget versions scenarios approvals commitments forecast and actual variance need a dedicated contract","dependencies":["configuration","approval","fiscal","accounting","p2p"],"minimum_package":["contract","synthetic budget evaluator","tests","checkpoint"],"runtime_status":"NOT_PROVEN"},
 {"gap_id":"ERP-GAP-04","priority":"P1","domain":"intercompany_elimination_consolidation_and_multi_entity_close","reason":"cross-entity matching elimination currency translation minority interest and group close remain uncovered","dependencies":["organization scope","fiscal","accounting","semantics","master data"],"minimum_package":["contract","synthetic consolidation evaluator","tests","checkpoint"],"runtime_status":"NOT_PROVEN"},
 {"gap_id":"ERP-GAP-05","priority":"P1","domain":"lease_accounting_right_of_use_and_liability","reason":"lease schedule discount modification reassessment impairment and ROU liability GL are not explicit","dependencies":["fixed assets","semantics","fiscal","approval","accounting"],"minimum_package":["contract","synthetic schedule evaluator","tests","checkpoint"],"runtime_status":"NOT_PROVEN"},
 {"gap_id":"ERP-GAP-06","priority":"P1","domain":"service_case_field_service_warranty_and_maintenance","reason":"case entitlement SLA dispatch work order parts labor warranty and service billing need a coherent lifecycle","dependencies":["inventory","o2c","payroll","observability","approval"],"minimum_package":["contract","synthetic service evaluator","tests","checkpoint"],"runtime_status":"NOT_PROVEN"},
 {"gap_id":"ERP-GAP-07","priority":"P2","domain":"crm_lead_opportunity_quote_forecast_and_consent","reason":"pre-order commercial lifecycle and forecast lineage are not a dedicated target contract","dependencies":["o2c","privacy","master data","approval"],"minimum_package":["contract","synthetic opportunity evaluator","tests","checkpoint"],"runtime_status":"NOT_PROVEN"},
 {"gap_id":"ERP-GAP-08","priority":"P2","domain":"data_warehouse_semantic_metrics_and_regulatory_reporting","reason":"certified metrics lineage restatement and regulatory report submission remain external to read-model design","dependencies":["provenance","report parity","fiscal","privacy","evidence"],"minimum_package":["contract","metric conformance vectors","tests","checkpoint"],"runtime_status":"NOT_PROVEN"},
]
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 p=argparse.ArgumentParser();p.add_argument("--output",required=True,type=Path);a=p.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items() if S[k].endswith(".json")}
 excluded={"varanegar_target_erp_domain_coverage_gap_register_20260901.json","varanegar_target_erp_contract_portfolio_invariant_audit_20260901.json","varanegar_target_erp_contract_portfolio_invariant_audit_checkpoint_20260901.json"};contracts=sorted(x for x in AN.glob("varanegar_target_erp_*contract*.json") if x.name not in excluded);rows=[]
 for x in contracts:
  q=load(x);s=q.get("summary",{});rows.append({"artifact":x.relative_to(ROOT).as_posix(),"validation":q.get("validation"),"mode":q.get("scope",{}).get("mode"),"command_ready_module_count":s.get("command_ready_module_count",0),"pilot_ready_module_count":s.get("pilot_ready_module_count",0),"accepted_operational_receipt_count":s.get("accepted_operational_receipt_count",0)})
 official=d["official_tests"];summary={"target_erp_contract_artifact_count":len(rows),"passing_contract_artifact_count":sum(x["validation"]=="PASS" for x in rows),"design_or_synthetic_contract_count":sum(bool(x["mode"]) for x in rows),"remaining_gap_count":len(GAPS),"p0_gap_count":sum(x["priority"]=="P0" for x in GAPS),"p1_gap_count":sum(x["priority"]=="P1" for x in GAPS),"p2_gap_count":sum(x["priority"]=="P2" for x in GAPS),"operational_contract_receipt_count":sum(x["accepted_operational_receipt_count"] for x in rows),"command_ready_module_count":max((x["command_ready_module_count"] for x in rows),default=0),"pilot_ready_module_count":max((x["pilot_ready_module_count"] for x in rows),default=0),"official_test_file_count":official["runner"]["test_file_count"],"official_passed_test_count":official["runner"]["passed_test_count"],"risk_count":d["risk"]["summary"]["risk_count"],"mapped_risk_assignment_count":d["trace"]["summary"]["mapped_risk_assignment_count"],"design_lower_bound":1404}
 checks={"sources_pass":all(d[k].get("validation")=="PASS" for k in ("previous","official_tests","final_bundle")),"all_target_contracts_pass":summary["target_erp_contract_artifact_count"]==summary["passing_contract_artifact_count"] and summary["target_erp_contract_artifact_count"]>=54,"gap_priorities_0_4_2":(summary["p0_gap_count"],summary["p1_gap_count"],summary["p2_gap_count"])==(0,4,2),"gap_packages_bounded":all(x["minimum_package"] and x["runtime_status"]=="NOT_PROVEN" for x in GAPS),"runtime_and_readiness_zero":summary["operational_contract_receipt_count"]==summary["command_ready_module_count"]==summary["pilot_ready_module_count"]==0,"official_tests_pass_no_exclusion":official["validation"]=="PASS" and official["runner"]["bootstrap_excluded_test_file_count"]==0,"baseline_stable":(summary["risk_count"],summary["mapped_risk_assignment_count"],summary["design_lower_bound"])==(84,343,1404)};failed=sorted(k for k,v in checks.items() if not v)
 manifest=[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())]+[{"name":f"target_contract_{i:03d}","path":x.relative_to(ROOT).as_posix(),"size_bytes":x.stat().st_size,"sha256":sha(x)} for i,x in enumerate(contracts,1)]+[{"name":"builder","path":"scripts/windows/build_varanegar_target_erp_domain_coverage_gap_register_20260901.py","size_bytes":Path(__file__).stat().st_size,"sha256":sha(Path(__file__))}]
 out={"artifact":"varanegar_target_erp_domain_coverage_gap_register_20260901","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","scope":{"mode":"TARGET_ERP_DESIGN_COVERAGE_INVENTORY_AND_GAP_PRIORITIZATION","operational_runtime_certification":False,"provider_selection":False},"summary":summary,"completed_contract_inventory":rows,"remaining_domain_gaps":GAPS,"prioritization_rule":["P0 closes core inventory accounting or end-to-end margin dependencies","P1 closes planning multi-entity statutory asset or service dependencies","P2 extends commercial analytics or reporting after core controls"],"safety":{"database_connections":0,"network_reads_or_writes":0,"operational_records_or_business_values_read":0,"operational_forms_reports_queries_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"credentials_pii_or_raw_business_values_persisted":0},"checks":checks,"failed_checks":failed,"source_manifest":manifest,"limits":["Presence of a passing design or synthetic contract is not runtime capability.","Gap priority is an architectural sequencing recommendation, not business-owner approval.","Operational UAT provider selection and regulatory acceptance require separate evidence and authorization."]}
 a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(summary,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
