"""Execute deterministic synthetic document-numbering state vectors."""
from __future__ import annotations
import argparse,copy,hashlib,importlib.util,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];REFERENCE=ROOT/"scripts/windows/varanegar_numbering_reference.py"
S={"numbering":"artifacts/varanegar_analysis/varanegar_target_erp_document_numbering_series_void_rollover_contract_20260829.json","numbering_checkpoint":"artifacts/varanegar_analysis/varanegar_target_erp_document_numbering_series_void_rollover_checkpoint_20260829.json","concurrency":"artifacts/varanegar_analysis/varanegar_target_erp_optimistic_concurrency_version_fencing_contract_20260829.json","idempotency":"artifacts/varanegar_analysis/varanegar_target_erp_command_idempotency_outbox_inbox_convergence_contract_20260829.json","tests":"artifacts/varanegar_analysis/varanegar_25h_final_test_result_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def module():
 s=importlib.util.spec_from_file_location("numbering_ref",REFERENCE);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return m
def main():
 p=argparse.ArgumentParser();p.add_argument("--output",required=True,type=Path);a=p.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};m=module();base=m.baseline()
 def changed(**kw):e=copy.deepcopy(base);e.update(kw);return e
 positive=[("POS-COMMIT",base,"NUMBER_COMMITTED_UNIQUE_AND_MONOTONIC"),("POS-DRAFT",changed(allocation_stage="DRAFT"),"DRAFT_ACCEPTED_NUMBER_NOT_ALLOCATED"),("POS-RESERVE",changed(allocation_stage="RESERVED"),"RESERVATION_ACCEPTED_NOT_COMMITTED"),("POS-REPLAY",changed(idempotency_receipt_exists=True),"IDEMPOTENT_REPLAY_EXISTING_NUMBER"),("POS-VOID",changed(allocation_stage="RESERVED",reservation_expired=True,void_receipt_present=True),"GAP_RECORDED_WITH_IMMUTABLE_VOID"),("POS-OFFLINE",changed(allocation_stage="RESERVED",offline_mode=True),"OFFLINE_RESERVATION_ACCEPTED_SCOPED_RANGE"),("POS-ROLLOVER",changed(rollover_requested=True),"ROLLOVER_ACCEPTED_CLOSED_AND_RECONCILED")]
 negative=[("NEG-EXTRA",dict(base,extra=1),"SCHEMA_INVALID"),("NEG-SCOPE",changed(scope_complete=False),"ALLOCATION_REJECTED_SCOPE_INCOMPLETE"),("NEG-SERIES",changed(series_active=False),"ALLOCATION_REJECTED_SERIES_OR_PERIOD"),("NEG-FISCAL",changed(fiscal_period_open=False),"ALLOCATION_REJECTED_SERIES_OR_PERIOD"),("NEG-FINGERPRINT",changed(idempotency_receipt_exists=True,same_command_fingerprint=False),"CONFLICT_FINGERPRINT_OR_IDEMPOTENCY_KEY"),("NEG-UNKNOWN",changed(commit_status="UNKNOWN"),"ALLOCATION_UNKNOWN_RECONCILIATION_REQUIRED"),("NEG-VERSION",changed(observed_sequence_version=11),"ALLOCATION_REJECTED_SEQUENCE_VERSION"),("NEG-FENCE",changed(candidate_fencing_token=20),"ALLOCATION_REJECTED_STALE_FENCING_TOKEN"),("NEG-VOID",changed(allocation_stage="RESERVED",reservation_expired=True),"VOID_RECEIPT_REQUIRED_EXPIRED_RESERVATION"),("NEG-NUMBER",changed(candidate_number=100),"ALLOCATION_REJECTED_DUPLICATE_OR_NONMONOTONIC"),("NEG-OFFLINE-EXPIRED",changed(allocation_stage="RESERVED",offline_mode=True,offline_range_expired=True),"OFFLINE_RANGE_REJECTED_BOUNDARY_EXPIRY_OR_OVERLAP"),("NEG-OFFLINE-BOUNDARY",changed(allocation_stage="RESERVED",offline_mode=True,candidate_number=201),"OFFLINE_RANGE_REJECTED_BOUNDARY_EXPIRY_OR_OVERLAP"),("NEG-ROLLOVER",changed(rollover_requested=True,open_reservation_count=1),"ROLLOVER_REJECTED_OPEN_RESERVATION_OR_GAP")]
 def run(vs):return [{"vector_id":i,"expected":x,"actual":m.evaluate(e),"status":"PASS" if m.evaluate(e)==x else "FAIL"} for i,e,x in vs]
 pr=run(positive);nr=run(negative);o=d["tests"]
 s={"reference_evaluator_implementation_count":1,"positive_vector_count":len(pr),"positive_pass_count":sum(x["status"]=="PASS" for x in pr),"negative_vector_count":len(nr),"negative_pass_count":sum(x["status"]=="PASS" for x in nr),"total_vector_count":len(pr)+len(nr),"total_pass_count":sum(x["status"]=="PASS" for x in pr+nr),"distinct_typed_outcome_count":len({x["actual"] for x in pr+nr}),"numbering_gate_count":d["numbering"]["summary"]["gate_count"],"numbering_module_gate_assignment_count":d["numbering"]["summary"]["module_gate_assignment_count"],"operational_numbering_implementation_count":0,"operational_number_series_gap_or_identifier_read_count":0,"reserve_commit_void_offline_or_rollover_run_count":0,"accepted_operational_receipt_count":0,"command_ready_module_count":0,"pilot_ready_module_count":0,"design_lower_bound_before_reference_evaluator":1404,"design_lower_bound_after_reference_evaluator":1404,"official_test_file_count":o["runner"]["test_file_count"],"official_passed_test_count":o["runner"]["passed_test_count"],"risk_count":d["risk"]["summary"]["risk_count"],"mapped_risk_assignment_count":d["trace"]["summary"]["mapped_risk_assignment_count"],"new_risk_count":0}
 checks={"sources_pass":all(d[k].get("validation")=="PASS" for k in ("numbering","numbering_checkpoint","concurrency","idempotency","tests")),"positive_7_of_7":s["positive_vector_count"]==s["positive_pass_count"]==7,"negative_13_of_13":s["negative_vector_count"]==s["negative_pass_count"]==13,"total_20_of_20":s["total_vector_count"]==s["total_pass_count"]==20,"coverage_20_280":(s["numbering_gate_count"],s["numbering_module_gate_assignment_count"])==(20,280),"operational_and_readiness_zero":s["operational_numbering_implementation_count"]==s["operational_number_series_gap_or_identifier_read_count"]==s["reserve_commit_void_offline_or_rollover_run_count"]==s["accepted_operational_receipt_count"]==s["command_ready_module_count"]==s["pilot_ready_module_count"]==0,"non_additive_1404":s["design_lower_bound_before_reference_evaluator"]==s["design_lower_bound_after_reference_evaluator"]==1404,"official_tests_pass":o["validation"]=="PASS" and o["runner"]["bootstrap_excluded_test_file_count"]==0,"base_stable":s["risk_count"]==84 and s["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_target_erp_numbering_synthetic_reference_evaluator_contract_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","scope":{"mode":"pure_synthetic_document_numbering_state_reference","continuation_complete":False,"operational_number_series_gap_or identifier_read":False},"safety":{"database_connections":0,"network_reads_or_writes":0,"operational_document_number_series_gap_identifier_or_record_reads":0,"number_reservation_commit_void_offline_range_or_rollover_actions_executed":0,"operational_forms_reports_queries_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"credentials_endpoints_pii_or_raw_business_values_read_or_persisted":0},"summary":s,"positive_results":pr,"negative_results":nr,"outcome_precedence":["SCHEMA","SCOPE_SERIES_FISCAL","IDEMPOTENCY_RECEIPT","UNKNOWN_COMMIT","SEQUENCE_VERSION","FENCING","ROLLOVER","DRAFT","VOID","MONOTONICITY","OFFLINE_RANGE","RESERVE_OR_COMMIT"],"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())]+[{"name":"reference_evaluator","path":REFERENCE.relative_to(ROOT).as_posix(),"size_bytes":REFERENCE.stat().st_size,"sha256":sha(REFERENCE)},{"name":"builder","path":"scripts/windows/build_varanegar_target_erp_numbering_synthetic_reference_evaluator_contract_20260829.py","size_bytes":Path(__file__).stat().st_size,"sha256":sha(Path(__file__))}],"limits":["Only fixed synthetic states versions numbers ranges and booleans were evaluated.","The evaluator is not a sequence database fiscal offline numbering or document implementation.","Operational numbering remains blocked pending authenticated current scoped receipts."]}
 a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(s,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
