"""Build evidence-first treasury incident playbooks from the command envelope and Golden designs."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S={"envelope":"artifacts/varanegar_analysis/varanegar_treasury_command_outcome_envelope_20260829.json","golden":"artifacts/varanegar_analysis/varanegar_treasury_golden_uat_cases_20260829.json","payment":"artifacts/varanegar_analysis/domains/ngt_payment_settlement_boundary_20260829.json","undo":"artifacts/varanegar_analysis/domains/received_cheque_undo_boundary_20260829.json","delete":"artifacts/varanegar_analysis/domains/received_cheque_delete_boundary_20260829.json","bank":"artifacts/varanegar_analysis/ui/negin_erp_bank_reconciliation_implementation_readiness_20260827.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_treasury_golden_uat_checkpoint_20260829.json"}
COMMON=["capture correlation/command id, actor capability, DC/fiscal/date scope and expected version without PII","verify every source hash and stop on drift","read aggregate, ordered history, crosswalk, audit/outbox and relevant reconciliation totals","compare typed outcome with durable evidence; transport or message text never proves rollback","classify NATURAL_BEHAVIOR, DATA_DEBT, BUG or UNPROVEN","stop before repair; define an isolated synthetic replay when evidence is insufficient"]
PLAYBOOKS=[
{"id":"TR-PB-01","incident":"treasury edit returned an ambiguous result","focus":"UI transaction and optional inline SQL may have diverged","extra":"read receipt/cheque/draft version plus linked detail totals before retry","risk_ids":["R-005","R-006","R-007"]},
{"id":"TR-PB-02","incident":"received-cheque Undo appears to select the wrong leaf","focus":"runtime form and cession/delete branch are not statically proven","extra":"compare current pointer with ordered history; preserve branch evidence and never infer latest by maximum id","risk_ids":["R-008","R-043"]},
{"id":"TR-PB-03","incident":"received cheque is absent after Delete but outcome is unknown","focus":"legacy delete has no explicit transaction signal","extra":"absence is not success proof; require immutable delete receipt plus history and dependent-link reconciliation","risk_ids":["R-005","R-007","R-023"]},
{"id":"TR-PB-04","incident":"tour payment allocation does not equal header amount","focus":"57 underallocated clone rows exist without overallocations","extra":"recompute header/detail allocation by payment identity and quarantine unresolved residuals","risk_ids":["R-005","R-036"]},
{"id":"TR-PB-05","incident":"back-office receipt exists but NGT crosswalk is missing or partial","focus":"replication IL exposes Commit before and after crosswalk setters","extra":"read both systems by source identity; classify durable split effect and block blind replication retry","risk_ids":["R-006","R-007","R-023"]},
{"id":"TR-PB-06","incident":"bank reconciliation Confirm is partial or summary disagrees","focus":"legacy nested static transaction state and target multi-instrument atomicity need runtime proof","extra":"compare session version, every typed link, cardex, summary, audit and outbox; quarantine session on any unexplained difference","risk_ids":["R-007","R-036","R-043"]},
]
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};pbs=[{**x,"steps":COMMON+[x["extra"]],"stop_conditions":["source hash drift","repair or write required","PII/raw business values would be persisted","owner policy required"],"runtime_diagnosis":"NOT_PERFORMED"} for x in PLAYBOOKS];s={"playbook_count":len(pbs),"minimum_step_count":min(len(x["steps"]) for x in pbs),"treasury_command_count":d["envelope"]["summary"]["command_count"],"golden_case_count":d["golden"]["summary"]["case_count"],"underallocated_clone_count":d["payment"]["summary"]["underallocated_count"],"undo_tail_count":d["undo"]["summary"]["undo_command_tail_count"],"receipt_delete_batch_count":d["delete"]["summary"]["receipt_delete_batch_count"],"runtime_incidents_diagnosed_count":0,"repairs_performed_count":0,"owner_approved_count":0,"risk_count":84,"mapped_risk_assignment_count":343,"new_risk_count":0}
 risks={x["id"] for x in d["risk"]["risks"]};checks={"sources_pass":all(x["validation"]=="PASS" for x in d.values()),"six_playbooks":s["playbook_count"]==6,"seven_steps_each":all(len(x["steps"])==7 for x in pbs),"four_way_classification":all("NATURAL_BEHAVIOR, DATA_DEBT, BUG or UNPROVEN" in x["steps"][4] for x in pbs),"all_risks_exist":all(r in risks for x in pbs for r in x["risk_ids"]),"twelve_and_eighty_four":s["treasury_command_count"]==12 and s["golden_case_count"]==84,"aggregate_facts_pinned":s["underallocated_clone_count"]==57 and s["receipt_delete_batch_count"]==19,"runtime_repair_zero":s["runtime_incidents_diagnosed_count"]==s["repairs_performed_count"]==s["owner_approved_count"]==0,"risk_trace_stable":d["risk"]["summary"]["risk_count"]==84 and d["trace"]["summary"]["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_treasury_expert_playbook_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","safety":{"mode":"OFFLINE_EVIDENCE_SYNTHESIS","database_connections":0,"commands_forms_reports_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"sensitive_values_persisted":0},"summary":s,"playbooks":pbs,"diagnostic_result_contract":{"allowed":["NATURAL_BEHAVIOR","DATA_DEBT","BUG","UNPROVEN"],"requires_named_incident_evidence":True,"repair_is_separate_authorized_work":True},"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"confidence":{"playbook_structure":"HIGH","incident_specific_diagnosis":"REQUIRES_INCIDENT_EVIDENCE"},"limits":["No named runtime incident was diagnosed.","No repair, retry or UAT was executed.","Clone aggregate counts are evidence for a diagnostic branch, not production-current truth."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(s,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
