"""Separate target transaction/effect design from legacy/static and runtime proof."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S={"identity":"artifacts/varanegar_analysis/varanegar_identity_authorization_outcome_envelope_20260829.json","integration":"artifacts/varanegar_analysis/varanegar_integration_migration_outcome_envelope_20260829.json","identity_readiness":"artifacts/varanegar_analysis/varanegar_identity_authorization_readiness_delta_20260829.json","integration_readiness":"artifacts/varanegar_analysis/varanegar_integration_migration_readiness_delta_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_24h_continuation_consolidated_checkpoint_20260829.json"}
def L(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def H(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();p={k:ROOT/v for k,v in S.items()};d={k:L(v) for k,v in p.items()};ic=d["identity"]["commands"];gc=d["integration"]["commands"]
 rows=[]
 for x in ic:rows.append({"module":"identity_authorization","command":x["command"],"target_transaction_design":bool(x.get("transaction_owner")),"target_mutation_effect_design":bool(x.get("aggregate") and x.get("special_rule")),"complete_legacy_static_transaction_and_mutation_proof":False,"runtime_atomicity_and_effect_parity":"UNPROVEN","evidence_boundary":"target assignment/revocation, audit, outbox and session-epoch unit exists; exact implemented mutation set does not"})
 for x in gc:rows.append({"module":"integration_migration","command":x["command"],"target_transaction_design":bool(x.get("atomic_unit")),"target_mutation_effect_design":bool(x.get("response_fields") and "aggregate_effect_receipts" in x["response_fields"]),"complete_legacy_static_transaction_and_mutation_proof":False,"runtime_atomicity_and_effect_parity":"UNPROVEN","evidence_boundary":"target item/effect/crosswalk/reconciliation/ack unit exists; source graph/frontier and external effects remain incomplete"})
 s={"module_count":2,"command_count":len(rows),"identity_command_count":len(ic),"integration_command_count":len(gc),"command_with_target_transaction_design_count":sum(x["target_transaction_design"] for x in rows),"command_with_target_mutation_effect_design_count":sum(x["target_mutation_effect_design"] for x in rows),"command_with_complete_legacy_static_proof_count":0,"identity_mutating_endpoint_without_declared_authorization_count":d["identity"]["summary"]["mutating_endpoint_without_declared_authorization_count"],"identity_scope_mismatch_count":d["identity"]["summary"]["scope_consistency_mismatch_count"],"integration_pos_unexpanded_frontier_count":d["integration"]["summary"]["pos_graph_unexpanded_frontier_count"],"integration_compensation_blocker_candidate_count":d["integration"]["summary"]["ngt_compensation_blocker_candidate_count"],"integration_rule_transport_unproven_gate_count":d["integration"]["summary"]["rule_transport_unproven_gate_count"],"implemented_command_count":0,"runtime_atomicity_proven_command_count":0,"runtime_effect_parity_proven_command_count":0,"executed_case_count":0,"owner_approved_case_count":0,"risk_count":84,"mapped_risk_assignment_count":343,"new_risk_count":0}
 checks={"sources_pass":all(v["validation"]=="PASS" for v in d.values()),"twelve_commands":s["command_count"]==s["identity_command_count"]+s["integration_command_count"]==12,"target_design_complete":s["command_with_target_transaction_design_count"]==s["command_with_target_mutation_effect_design_count"]==12,"legacy_static_not_promoted":s["command_with_complete_legacy_static_proof_count"]==0,"known_boundaries":s["identity_mutating_endpoint_without_declared_authorization_count"]==38 and s["identity_scope_mismatch_count"]==58 and s["integration_pos_unexpanded_frontier_count"]==160 and s["integration_compensation_blocker_candidate_count"]==342 and s["integration_rule_transport_unproven_gate_count"]==6,"runtime_zero":s["implemented_command_count"]==s["runtime_atomicity_proven_command_count"]==s["runtime_effect_parity_proven_command_count"]==s["executed_case_count"]==s["owner_approved_case_count"]==0,"base_stable":d["risk"]["summary"]["risk_count"]==84 and d["trace"]["summary"]["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_identity_integration_transaction_mutation_boundary_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","safety":{"mode":"OFFLINE_EXISTING_ARTIFACT_CROSSWALK","database_connections":0,"network_reads_or_writes":0,"operational_commands_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"credentials_pii_or_raw_business_values_read_or_persisted":0},"summary":s,"classification":{"target_design":"PROVEN_FOR_TWELVE_COMMANDS","complete_legacy_static_transaction_and_mutation_proof":"NOT_PROVEN","runtime_atomicity_effect_and_result_parity":"NOT_PROVEN"},"commands":rows,"checks":checks,"failed_checks":failed,"risk_links":["R-001","R-006","R-007","R-025","R-027","R-056","R-057","R-058","R-059","R-062"],"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":H(v)} for k,v in sorted(p.items())],"limits":["Target design does not become legacy/static or runtime proof.","No identity assignment, package, migration, compensation or external effect was executed."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(s,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
