"""Chain the synthetic privacy/rights reference evaluator."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
S={"contract":"artifacts/varanegar_analysis/varanegar_target_erp_privacy_rights_synthetic_reference_evaluator_contract_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_target_erp_privacy_consent_legal_basis_data_subject_rights_checkpoint_20260829.json","reference":"scripts/windows/varanegar_privacy_rights_reference.py","builder":"scripts/windows/build_varanegar_target_erp_privacy_rights_synthetic_reference_evaluator_contract_20260829.py","checkpoint_builder":"scripts/windows/build_varanegar_target_erp_privacy_rights_synthetic_reference_evaluator_checkpoint_20260829.py","reference_test":"tests/test_varanegar_privacy_rights_reference.py","test":"tests/test_varanegar_target_erp_privacy_rights_synthetic_reference_evaluator_contract.py","checkpoint_test":"tests/test_varanegar_target_erp_privacy_rights_synthetic_reference_evaluator_checkpoint.py","doc":"docs/varanegar_reconstruction/TARGET_ERP_PRIVACY_RIGHTS_SYNTHETIC_REFERENCE_EVALUATOR_20260829_FA.md"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 p=argparse.ArgumentParser();p.add_argument("--output",required=True,type=Path);a=p.parse_args();paths={k:ROOT/v for k,v in S.items()};c=load(paths["contract"]);prev=load(paths["previous"]);s=c["summary"]
 checks={"sources_pass":c["validation"]==prev["validation"]=="PASS","vectors_30_of_30":s["total_vector_count"]==s["total_pass_count"]==30,"positive_9_negative_21":s["positive_pass_count"]==9 and s["negative_pass_count"]==21,"coverage_24_336":(s["privacy_gate_count"],s["privacy_module_gate_assignment_count"])==(24,336),"operational_and_readiness_zero":all(s[k]==0 for k in ("operational_privacy_consent_rights_or_disposition_implementation_count","operational_person_subject_identifier_or_sensitive_data_read_count","consent_rights_disposition_sharing_or_breach_run_count","accepted_operational_receipt_count","command_ready_module_count","pilot_ready_module_count")),"base_stable":s["risk_count"]==84 and s["mapped_risk_assignment_count"]==343 and s["design_lower_bound_after_reference_evaluator"]==1404,"safety_zero":set(c["safety"].values())=={0}};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_target_erp_privacy_rights_synthetic_reference_evaluator_checkpoint_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","previous_checkpoint":{"path":S["previous"],"sha256":sha(paths["previous"])},"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"safety":{"database_connections":0,"network_reads_or_writes":0,"operational_person_subject_identifier_contact_employee_financial_or_sensitive_data_reads":0,"consent_capture_withdrawal_rights_disposition_sharing_or_breach_actions_executed":0,"operational_forms_reports_queries_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"credentials_endpoints_pii_or_raw_business_values_read_or_persisted":0}}
 a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
