from __future__ import annotations
import argparse,copy,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S={"base":"artifacts/varanegar_analysis/varanegar_identity_authorization_readiness_delta_20260829.json","envelope":"artifacts/varanegar_analysis/varanegar_organization_context_outcome_envelope_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_organization_context_outcome_checkpoint_20260829.json"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};mods=copy.deepcopy(d["base"]["modules"]);x=next(v for v in mods if v["module"]=="organization_context");before=x["truth_table_dimensions"]["outcome_retry_idempotency"]["target_contract"];x["mapped_validated_evidence"].append({"key":"organization_context_outcome","path":S["envelope"],"validation":d["envelope"]["validation"]});x["truth_table_dimensions"]["outcome_retry_idempotency"]["target_contract"]=True;x["synthetic_golden_case_count"]=64;x["truth_table_dimensions"]["golden_cases"]["synthetic_design_count"]=64;x["legacy_open_blockers"].extend(["business owner must approve organization/year/DC/office/stock relation and retirement policy","runtime ContextSnapshot parity and server-side set-operation-date authorization are unproven","three null date profiles and one after-last profile require typed target disposition","calendar/timezone and special-order exception rules require isolated UAT"])
 summary={"module_count":len(mods),"changed_module_count":1,"outcome_target_contract_module_count_before":sum(v["truth_table_dimensions"]["outcome_retry_idempotency"]["target_contract"] for v in d["base"]["modules"]),"outcome_target_contract_module_count_after":sum(v["truth_table_dimensions"]["outcome_retry_idempotency"]["target_contract"] for v in mods),"organization_context_command_contract_count":d["envelope"]["summary"]["command_contract_count"],"mapped_existing_golden_case_count":64,"runtime_context_parity_proven_module_count":0,"runtime_retry_idempotency_proven_module_count":0,"command_ready_module_count":0,"pilot_ready_module_count":0,"risk_count":84,"mapped_risk_assignment_count":343,"new_risk_count":0};checks={"sources_pass":all(v["validation"]=="PASS" for v in d.values()),"fourteen_modules":len(mods)==14,"organization_false_to_true":before is False and x["truth_table_dimensions"]["outcome_retry_idempotency"]["target_contract"] is True,"eleven_to_twelve":summary["outcome_target_contract_module_count_before"]==11 and summary["outcome_target_contract_module_count_after"]==12,"one_changed":sum(v["truth_table_dimensions"]["outcome_retry_idempotency"]["target_contract"]!=w["truth_table_dimensions"]["outcome_retry_idempotency"]["target_contract"] for v,w in zip(d["base"]["modules"],mods))==1,"scope":summary["organization_context_command_contract_count"]==6 and summary["mapped_existing_golden_case_count"]==64,"runtime_zero":summary["runtime_context_parity_proven_module_count"]==summary["runtime_retry_idempotency_proven_module_count"]==summary["command_ready_module_count"]==summary["pilot_ready_module_count"]==0,"base_stable":d["risk"]["summary"]["risk_count"]==84 and d["trace"]["summary"]["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_organization_context_readiness_delta_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","safety":{"mode":"OFFLINE_DESIGN_DELTA","database_connections":0,"network_reads_or_writes":0,"organization_context_commands_or_forms_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"business_values_persisted":0},"summary":summary,"modules":mods,"promotion_boundary":{"changed":"organization_context outcome/retry target contract and 64 synthetic-design mappings only","unchanged":["runtime authorization","runtime transaction atomicity","effective ContextSnapshot parity","calendar/timezone parity","owner approval","command readiness","pilot readiness"]},"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"confidence":{"design_delta":"HIGH","runtime_readiness":"NOT_PROVEN"},"limits":["Design coverage is not implementation readiness.","No context or date command was executed.","The 64 mapped cases remain synthetic and unexecuted."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(summary,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
