"""Chain the target ERP privacy/consent/data-subject-rights contract."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
S={"contract":"artifacts/varanegar_analysis/varanegar_target_erp_privacy_consent_legal_basis_data_subject_rights_contract_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_target_erp_output_rendering_synthetic_reference_evaluator_checkpoint_20260829.json","builder":"scripts/windows/build_varanegar_target_erp_privacy_consent_legal_basis_data_subject_rights_contract_20260829.py","checkpoint_builder":"scripts/windows/build_varanegar_target_erp_privacy_consent_legal_basis_data_subject_rights_checkpoint_20260829.py","test":"tests/test_varanegar_target_erp_privacy_consent_legal_basis_data_subject_rights_contract.py","checkpoint_test":"tests/test_varanegar_target_erp_privacy_consent_legal_basis_data_subject_rights_checkpoint.py","doc":"docs/varanegar_reconstruction/TARGET_ERP_PRIVACY_CONSENT_LEGAL_BASIS_DATA_SUBJECT_RIGHTS_20260829_FA.md"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 p=argparse.ArgumentParser();p.add_argument("--output",required=True,type=Path);a=p.parse_args();paths={k:ROOT/v for k,v in S.items()};c=load(paths["contract"]);prev=load(paths["previous"]);s=c["summary"]
 checks={"sources_pass":c["validation"]==prev["validation"]=="PASS","coverage_14_196_168":(s["module_count"],s["module_dimension_assignment_count"],s["module_stage_assignment_count"])==(14,196,168),"failure_gate_role_coverage":(s["module_failure_assignment_count"],s["module_gate_assignment_count"],s["module_role_assignment_count"])==(252,336,112),"runtime_and_readiness_zero":all(s[k]==0 for k in ("operational_person_subject_identifier_contact_employee_financial_or_sensitive_data_read_count","jurisdiction_legal_basis_consent_or_processor_provider_selected_count","consent_capture_withdrawal_rights_disposition_sharing_or_breach_run_count","accepted_operational_receipt_count","privacy_or_legal_owner_approved_module_count","command_ready_module_count","pilot_ready_module_count")),"base_stable":s["risk_count"]==84 and s["mapped_risk_assignment_count"]==343 and s["design_lower_bound_after_privacy_contract"]==1404,"safety_zero":set(c["safety"].values())=={0}};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_target_erp_privacy_consent_legal_basis_data_subject_rights_checkpoint_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","previous_checkpoint":{"path":S["previous"],"sha256":sha(paths["previous"])},"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"safety":{"database_connections":0,"network_reads_or_writes":0,"operational_person_subject_identifier_contact_employee_financial_or_sensitive_data_reads":0,"consent_capture_withdrawal_rights_disposition_sharing_or_breach_actions_executed":0,"operational_forms_reports_queries_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"credentials_endpoints_pii_or_raw_business_values_read_or_persisted":0}}
 a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
