"""Build chained checkpoint for RPT-09 batch print."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
S={"contract":"artifacts/varanegar_analysis/domains/print_batch_contract_20260829.json","runtime":"artifacts/varanegar_analysis/domains/print_batch_runtime_boundary_20260829.json","completion":"artifacts/varanegar_analysis/domains/print_completion_runtime_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_healthy_cardex_checkpoint_20260829.json","runtime_extractor":"scripts/windows/extract_varanegar_print_batch_runtime_boundary_20260829.py","completion_extractor":"scripts/windows/extract_varanegar_print_completion_runtime_20260829.py","builder":"scripts/windows/build_varanegar_print_batch_contract_20260829.py","checkpoint_builder":"scripts/windows/build_varanegar_print_batch_checkpoint_20260829.py","test":"tests/test_varanegar_print_batch_contract.py","doc":"docs/varanegar_reconstruction/PRINT_BATCH_PARTIAL_SUCCESS_AND_COMPLETION_BOUNDARY_20260829_FA.md"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(paths[k]) for k in("contract","runtime","completion","previous")};c=d["contract"];checks={"sources_pass":all(d[k]["validation"]=="PASS" for k in d),"seven_render_four_gated_three_render_only":c["summary"]["render_path_count"]==7 and c["summary"]["completion_gated_render_path_count"]==4 and c["summary"]["render_only_path_count"]==3,"partial_success_contract":c["batch_orchestration"]["transaction_owner"]=="NONE_IN_SELECTED_UI_ORCHESTRATOR" and "PER_OUTPUT" in c["batch_orchestration"]["partial_success"],"completion_commit_without_local_rollback":c["summary"]["completion_commit_path_count"]==2 and c["summary"]["completion_local_rollback_path_count"]==0,"five_golden_cases":len(c["golden_cases"])==5,"parity_not_claimed":c["summary"]["result_parity_proven_count"]==0,"risk_stable":c["summary"]["risk_count"]==84,"zero_execution":set(v for k,v in c["safety"].items() if k!="mode")=={0}};failed=sorted(k for k,v in checks.items() if not v);p={"artifact":"varanegar_print_batch_checkpoint_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","previous_checkpoint":{"path":S["previous"],"sha256":sha(paths["previous"])},"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"safety":{"forms_reports_templates_or_commands_executed":0,"assemblies_loaded_or_executed":0,"database_connections":0,"data_mutations":0,"sensitive_values_persisted":0}};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(p,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(p["validation"]);return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
