"""Chain the distribution expert incident playbooks."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S={"playbook":"artifacts/varanegar_analysis/varanegar_distribution_expert_playbook_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_distribution_golden_uat_checkpoint_20260829.json","builder":"scripts/windows/build_varanegar_distribution_expert_playbook_20260829.py","checkpoint_builder":"scripts/windows/build_varanegar_distribution_expert_playbook_checkpoint_20260829.py","test":"tests/test_varanegar_distribution_expert_playbook.py","doc":"docs/varanegar_reconstruction/DISTRIBUTION_EXPERT_INCIDENT_PLAYBOOK_20260829_FA.md"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d=load(paths["playbook"]);prev=load(paths["previous"]);s=d["summary"];checks={"sources_pass":d["validation"]==prev["validation"]=="PASS","five_playbooks":s["playbook_count"]==5,"eight_steps":s["minimum_step_count"]==8,"four_and_twenty_eight":s["distribution_command_count"]==4 and s["golden_case_count"]==28,"runtime_zero":s["runtime_incidents_diagnosed_count"]==s["repairs_performed_count"]==s["owner_approved_count"]==0,"base_stable":s["risk_count"]==84 and s["mapped_risk_assignment_count"]==343 and s["new_risk_count"]==0,"safety_zero":set(v for k,v in d["safety"].items() if k!="mode")=={0}};failed=sorted(k for k,v in checks.items() if not v);out={"artifact":"varanegar_distribution_expert_playbook_checkpoint_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","previous_checkpoint":{"path":S["previous"],"sha256":sha(paths["previous"])},"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"safety":{"commands_forms_queries_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"database_connections":0,"data_mutations":0,"sensitive_values_persisted":0}};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
