"""Build a canonical accounting/treasury/distribution reconciliation and quarantine contract."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
S={"accounting":"artifacts/varanegar_analysis/varanegar_accounting_command_inventory_correction_20260829.json","treasury":"artifacts/varanegar_analysis/varanegar_treasury_command_outcome_envelope_20260829.json","distribution":"artifacts/varanegar_analysis/varanegar_distribution_command_outcome_envelope_20260829.json","idempotency":"artifacts/varanegar_analysis/domains/idempotency_guard_boundary_20260829.json","sale_accounting":"artifacts/varanegar_analysis/domains/sale_accounting_crosswalk_boundary_20260829.json","payment":"artifacts/varanegar_analysis/domains/ngt_payment_settlement_boundary_20260829.json","payment_runtime":"artifacts/varanegar_analysis/domains/ngt_payment_replication_runtime_boundary_20260829.json","pointer":"artifacts/varanegar_analysis/ui/varanegar_voucher_status_pointer_diagnostic_contract_20260827.json","shell":"artifacts/varanegar_analysis/ui/varanegar_empty_voucher_shell_diagnostic_contract_20260827.json","exit":"artifacts/varanegar_analysis/domains/distribution_exit_lifecycle_boundary_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_distribution_traceability_delta_checkpoint_20260829.json"}
EDGES=[
{"edge":"command_to_command_receipt","from":"module command intent","to":"immutable command receipt","identity":["command_id","payload_hash","command_family"],"invariant":"same key/same payload returns original typed outcome; conflicting payload is rejected","prohibited_inference":"natural table uniqueness is not a command receipt"},
{"edge":"sale_to_accounting_source","from":"active numbered non-cancelled sale","to":"accounting source lines","identity":["sale source identity","scope","business date"],"invariant":"accounting source belongs to a current active sale and is balanced","prohibited_inference":"a cancelled or snapshot-only sale must not be synthesized into accounting"},
{"edge":"accounting_source_to_batch_journal","from":"accounting source","to":"one batch link and one active journal","identity":["source identity","batch identity","journal identity"],"invariant":"one source has one batch; a batch may aggregate many sources; each source link resolves to one active journal","prohibited_inference":"one batch does not imply one source"},
{"edge":"distribution_to_sale_link","from":"distribution aggregate","to":"sale link/history","identity":["distribution identity","sale identity","expected versions"],"invariant":"link changes are versioned and represented in ordered history","prohibited_inference":"current distribution status alone does not reconstruct sale-link history"},
{"edge":"distribution_to_exit","from":"distribution plus stock scope","to":"one active exit or explicit cancelled lifecycle","identity":["distribution identity","stock DC","fiscal year","exit identity"],"invariant":"active natural key remains unique and cancelled state remains distinguishable from physical absence","prohibited_inference":"missing current exit is not proof of successful cancellation"},
{"edge":"exit_to_type60_voucher","from":"active/cancelled exit","to":"type-60 voucher or deletion evidence","identity":["exit identity","voucher DocRef","voucher type","scope"],"invariant":"active exit resolves to its voucher graph; cancelled exit resolves to immutable delete evidence","prohibited_inference":"voucher absence without deletion evidence is not a matched cancellation"},
{"edge":"ngt_payment_to_backoffice_receipt","from":"NGT payment","to":"back-office receipt crosswalk","identity":["payment identity","receipt ref","receipt unique id","source scope"],"invariant":"crosswalk identity and allocation semantics are reconciled independently","prohibited_inference":"receipt amount equality is not a valid invariant because receipt scope can differ"},
]
INVARIANTS=[
{"id":"XRI-01","rule":"CommandId plus canonical PayloadHash is unique and immutable across modules."},
{"id":"XRI-02","rule":"Company/DC/fiscal-year/business-date/resource scope is explicit on every edge."},
{"id":"XRI-03","rule":"Source identity and crosswalk type are immutable; display numbers are attributes, not universal keys."},
{"id":"XRI-04","rule":"Aggregate versions and ordered event positions are recorded; latest is never reconstructed with MAX(id)."},
{"id":"XRI-05","rule":"Sale accounting sources are balanced and single-batch-linked, while multi-source batches remain valid."},
{"id":"XRI-06","rule":"Active distribution exit and type-60 voucher graph reconcile by source identity and scope."},
{"id":"XRI-07","rule":"Cancelled exit requires cancellation state plus type-60 delete evidence; physical absence alone is insufficient."},
{"id":"XRI-08","rule":"NGT payment/receipt identity and allocation are separate checks; amount equality is not assumed."},
{"id":"XRI-09","rule":"Typed outcome, durable effects, audit and outbox are reconciled before any retry."},
{"id":"XRI-10","rule":"Numbered empty voucher shells, pointer forks and partial crosswalks are quarantined, never auto-repaired."},
]
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};sa=d["sale_accounting"]["summary"];pay=d["payment"]["summary"];ptr=d["pointer"]["summary"];ex=d["exit"]["summary"]
 schema={"receipt_identity":["reconciliation_id","command_id","correlation_id","payload_hash","command_family"],"scope":["company","dc","fiscal_year","operation_date","resource_scope"],"source":["source_module","source_type","source_identity","source_version"],"target":["target_module","target_type","target_identity","target_version"],"edge":["edge_type","crosswalk_type","edge_version"],"outcome":["outcome_code","committed","durable_effect_summary","retryable"],"evidence":["source_hashes","observed_at","audit_identity","outbox_identity"],"comparison":["identity_match","scope_match","version_match","state_match","amount_or_balance_rule","effect_match"],"classification":["MATCHED","EXPECTED_ABSENCE","PARTIAL_DURABLE_EFFECT","IDENTITY_CONFLICT","VERSION_FORK","UNPROVEN"],"quarantine":["UNKNOWN_COMMAND_OUTCOME","POINTER_HISTORY_FORK","NUMBERED_EMPTY_SHELL","SOURCE_ONLY","TARGET_ONLY","DUPLICATE_OR_CONFLICTING_CROSSWALK","SCOPE_OR_VERSION_MISMATCH","MISSING_DELETE_OR_AUDIT_EVIDENCE"]}
 summary={"module_count":3,"source_command_count":d["accounting"]["summary"]["corrected_command_count"]+d["treasury"]["summary"]["command_count"]+d["distribution"]["summary"]["command_count"],"edge_type_count":len(EDGES),"invariant_count":len(INVARIANTS),"schema_section_count":len(schema),"classification_count":len(schema["classification"]),"quarantine_reason_count":len(schema["quarantine"]),"selected_legacy_command_without_idempotency_count":d["idempotency"]["summary"]["selected_command_count"]-d["idempotency"]["summary"]["selected_command_with_explicit_idempotency_parameter_count"],"sale_accounting_source_count":sa["sale_accounting_source_count"],"sale_accounting_unbalanced_count":sa["unbalanced_sale_accounting_source_count"],"sale_accounting_multi_batch_source_count":sa["sale_accounting_source_with_multiple_batch_count"],"accounting_link_without_journal_count":sa["accounting_link_without_journal_count"],"snapshot_without_accounting_source_count":sa["snapshot_without_accounting_source_count"],"payment_receipt_linked_count":pay["receipt_linked_count"],"payment_receipt_amount_scope_differs_count":pay["receipt_amount_scope_differs_count"],"voucher_pointer_not_maximum_count":ptr["current_pointer_not_maximum_count"],"numbered_empty_shell_count":d["shell"]["summary"]["numbered_shell_count"],"cancelled_exit_without_type60_delete_count":ex["cancelled_exit_without_type60_delete_count"],"runtime_reconciliation_executed_count":0,"owner_approved_count":0,"risk_count":84,"mapped_risk_assignment_count":343,"new_risk_count":0}
 checks={"sources_pass":all(x["validation"]=="PASS" for x in d.values()),"three_modules_twenty_two_commands":summary["module_count"]==3 and summary["source_command_count"]==22,"seven_edges_ten_invariants":summary["edge_type_count"]==7 and summary["invariant_count"]==10,"schema_complete":summary["schema_section_count"]==10 and summary["classification_count"]==6 and summary["quarantine_reason_count"]==8,"legacy_retry_gap":summary["selected_legacy_command_without_idempotency_count"]==10,"sale_accounting_integrity_pinned":summary["sale_accounting_unbalanced_count"]==summary["sale_accounting_multi_batch_source_count"]==summary["accounting_link_without_journal_count"]==0,"amount_equality_rejected":summary["payment_receipt_linked_count"]==274 and summary["payment_receipt_amount_scope_differs_count"]==270,"pointer_and_shell_quarantine":summary["voucher_pointer_not_maximum_count"]==1094 and summary["numbered_empty_shell_count"]==1,"exit_delete_evidence_pinned":summary["cancelled_exit_without_type60_delete_count"]==0,"base_stable":d["risk"]["summary"]["risk_count"]==84 and d["trace"]["summary"]["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_cross_module_reconciliation_contract_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","safety":{"mode":"OFFLINE_EVIDENCE_SYNTHESIS","database_connections":0,"commands_forms_reports_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"sensitive_values_persisted":0},"summary":summary,"cross_module_edges":EDGES,"reconciliation_invariants":INVARIANTS,"target_reconciliation_receipt_schema":schema,"promotion_gate":{"environment":"isolated target","rule":"all cross-module Golden fixtures reconcile with zero unexplained durable-effect difference and owner-approved policy snapshots"},"risk_links":["R-002","R-005","R-006","R-007","R-008","R-023","R-034","R-036","R-043","R-048"],"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"confidence":{"schema_and_static_invariants":"HIGH","runtime_cross_module_parity":"UNPROVEN"},"limits":["Aggregate evidence is clone/static evidence, not production-current certification.","No cross-module command or query was executed.","Expected absence requires an explicit rule; it is never inferred from missing target rows alone."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(summary,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
