from __future__ import annotations
import argparse,copy,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S={"base":"artifacts/varanegar_analysis/varanegar_master_data_readiness_delta_20260829.json","envelope":"artifacts/varanegar_analysis/varanegar_platform_outcome_envelope_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_platform_outcome_checkpoint_20260829.json"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};mods=copy.deepcopy(d["base"]["modules"]);x=next(v for v in mods if v["module"]=="platform");before=x["truth_table_dimensions"]["outcome_retry_idempotency"]["target_contract"];x["mapped_validated_evidence"].append({"key":"platform_outcome","path":S["envelope"],"validation":d["envelope"]["validation"]});x["truth_table_dimensions"]["outcome_retry_idempotency"]["target_contract"]=True;x["legacy_open_blockers"].extend(["stack/database/hosting and deployment owner remain unselected","RPO/RTO is a proposal, not approved service policy","external effect, rollback, restore and failover receipts are not runtime proven"])
 summary={"module_count":len(mods),"changed_module_count":1,"outcome_target_contract_module_count_before":sum(v["truth_table_dimensions"]["outcome_retry_idempotency"]["target_contract"] for v in d["base"]["modules"]),"outcome_target_contract_module_count_after":sum(v["truth_table_dimensions"]["outcome_retry_idempotency"]["target_contract"] for v in mods),"platform_command_contract_count":d["envelope"]["summary"]["command_contract_count"],"mapped_existing_golden_case_count":0,"runtime_external_effect_parity_proven_module_count":0,"approved_recovery_policy_count":0,"command_ready_module_count":0,"pilot_ready_module_count":0,"risk_count":84,"mapped_risk_assignment_count":343,"new_risk_count":0};checks={"sources_pass":all(v["validation"]=="PASS" for v in d.values()),"fourteen":len(mods)==14,"platform_false_true":before is False and x["truth_table_dimensions"]["outcome_retry_idempotency"]["target_contract"] is True,"thirteen_fourteen":summary["outcome_target_contract_module_count_before"]==13 and summary["outcome_target_contract_module_count_after"]==14,"one_changed":sum(v["truth_table_dimensions"]["outcome_retry_idempotency"]["target_contract"]!=w["truth_table_dimensions"]["outcome_retry_idempotency"]["target_contract"] for v,w in zip(d["base"]["modules"],mods))==1,"scope":summary["platform_command_contract_count"]==6,"runtime_zero":summary["runtime_external_effect_parity_proven_module_count"]==summary["approved_recovery_policy_count"]==summary["command_ready_module_count"]==summary["pilot_ready_module_count"]==0,"base_stable":d["risk"]["summary"]["risk_count"]==84 and d["trace"]["summary"]["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_platform_readiness_delta_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","safety":{"mode":"OFFLINE_DESIGN_DELTA","database_connections":0,"network_reads_or_writes":0,"deployments_jobs_restores_failovers_or_rollbacks_executed":0,"data_mutations":0,"credentials_endpoints_pii_or_raw_business_values_persisted":0},"summary":summary,"modules":mods,"promotion_boundary":{"changed":"platform provider-neutral outcome/retry target contract only","unchanged":["selected stack/database/hosting","approved RPO/RTO","deployment owner","runtime external-effect parity","command readiness","pilot readiness"]},"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"limits":["Fourteen-module design coverage is not implementation readiness.","No platform operation or recovery drill was executed."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(summary,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
