"""Chain the Manual Voucher semantic correction."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S={"boundary":"artifacts/varanegar_analysis/varanegar_manual_voucher_static_boundary_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_accounting_command_outcome_checkpoint_20260829.json","builder":"scripts/windows/build_varanegar_manual_voucher_static_boundary_20260829.py","checkpoint_builder":"scripts/windows/build_varanegar_manual_voucher_checkpoint_20260829.py","test":"tests/test_varanegar_manual_voucher_static_boundary.py","doc":"docs/varanegar_reconstruction/MANUAL_VOUCHER_SAVE_CANCEL_STATIC_BOUNDARY_20260829_FA.md"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(paths[k]) for k in ("boundary","previous")};s=d["boundary"]["summary"];checks={"sources_pass":d["boundary"]["validation"]==d["previous"]["validation"]=="PASS","one_false_candidate_rejected":s["rejected_mutating_command_candidate_count"]==1,"save_generic":s["generic_save_command_count"]==1,"cancel_close_only":s["ui_close_only_method_count"]==1,"exact_persistence_still_open":s["exact_adapter_or_procedure_resolved_count"]==0,"runtime_zero":s["runtime_effect_parity_proven_count"]==0,"risk_stable":s["risk_count"]==84 and s["new_risk_count"]==0,"zero_execution":set(v for k,v in d["boundary"]["safety"].items() if k!="mode")=={0}};failed=sorted(k for k,v in checks.items() if not v);out={"artifact":"varanegar_manual_voucher_checkpoint_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","previous_checkpoint":{"path":S["previous"],"sha256":sha(paths["previous"])},"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"safety":{"commands_forms_queries_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"database_connections":0,"data_mutations":0,"sensitive_values_persisted":0}};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
