"""Build accounting diagnostic playbooks and target ERP contracts from corrected evidence."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S={"inventory":"artifacts/varanegar_analysis/varanegar_accounting_command_inventory_correction_20260829.json","generic":"artifacts/varanegar_analysis/varanegar_manual_voucher_generic_save_20260829.json","golden":"artifacts/varanegar_analysis/varanegar_accounting_golden_uat_cases_20260829.json","pointer":"artifacts/varanegar_analysis/ui/varanegar_voucher_status_pointer_diagnostic_contract_20260827.json","shell":"artifacts/varanegar_analysis/ui/varanegar_empty_voucher_shell_diagnostic_contract_20260827.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_report_golden_fixture_checkpoint_20260829.json"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
COMMON=["capture correlation id, fiscal/DC scope, business date and expected version without PII","verify source hashes and stop on drift","read current pointer, ordered history, durable effects and audit/outbox","compare typed outcome to committed evidence; do not infer rollback from message text","classify NATURAL_BEHAVIOR, DATA_DEBT, BUG or UNPROVEN","stop before repair; design isolated UAT when static evidence is insufficient"]
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};pbs=[
 {"id":"ACC-PB-01","incident":"transfer returns error","critical_branch":"SetVoucherNo cleanup may already be durable","steps":COMMON+["if cleanup changed, return BUSINESS_ERROR_WITH_DURABLE_EFFECT and block blind retry"],"risk_links":["R-005","R-007","R-021"]},
 {"id":"ACC-PB-02","incident":"current voucher status disagrees with latest history","critical_branch":"pointer is not MAX(history) by definition","steps":COMMON+["preserve fork; never advance pointer automatically to maximum event"],"risk_links":["R-007","R-023","R-084"]},
 {"id":"ACC-PB-03","incident":"numbered voucher shell has no line","critical_branch":"zero ledger effect does not authorize number reuse or line synthesis","steps":COMMON+["quarantine shell and request accountant disposition"],"risk_links":["R-007","R-021","R-084"]},
 {"id":"ACC-PB-04","incident":"Manual Voucher save outcome is ambiguous","critical_branch":"generic V2/Fararu/CRUD runtime branch is unproven","steps":COMMON+["read back by command/source identity before retry; record selected persistence branch in target"],"risk_links":["R-005","R-007","R-023"]},
 {"id":"ACC-PB-05","incident":"operator closed Manual Voucher form and expects financial cancellation","critical_branch":"InternalCancelCommand is UI-close only","steps":COMMON+["classify as no financial command; locate separately evidenced reversal path before any mutation"],"risk_links":["R-002","R-023"]},
 ]
 contract={"state_machine":{"states":["DRAFT","ISSUED","CONFIRMED","TRANSFERRED","DELETED_OR_REVERSED_BY_EXPLICIT_COMMAND","QUARANTINED"],"rule":"UI close is never a state transition; history and current pointer are separate dimensions"},"command_schema":["command_id","actor_capabilities","resource_scope","fiscal_year","operation_date","expected_version","policy_snapshot_version","source_identity","requested_transition"],"authorization":"deny-first action plus resource/DC/fiscal scope rechecked server-side","unit_of_work":"one explicit transaction owner; audit and outbox atomic with state change","idempotency":"unique command_id; duplicate returns original typed outcome","outcome_schema":["outcome_code","committed","aggregate_version","durable_effect_summary","retryable","correlation_id"],"lineage":"immutable events; current pointer is explicit and never reconstructed as MAX(history)","quarantine":["pointer/history fork","empty numbered shell","ambiguous durable effect","unresolved generic runtime branch"],"acceptance_gate":"42 synthetic cases executed in isolated target, zero unexplained effect differences, owner approval"}
 checks={"sources_pass":all(d[k]["validation"]=="PASS" for k in d),"five_incidents":len(pbs)==5,"six_step_minimum":all(len(x["steps"])>=7 for x in pbs),"typed_four_way_classification":all("NATURAL_BEHAVIOR, DATA_DEBT, BUG or UNPROVEN" in x["steps"][4] for x in pbs),"ui_close_not_state":contract["state_machine"]["rule"].startswith("UI close is never"),"target_contract_nine_sections":len(contract)==9,"golden_42":d["golden"]["summary"]["case_count"]==42,"pointer_shell_pinned":d["pointer"]["summary"]["current_pointer_not_maximum_count"]==1094 and d["shell"]["summary"]["numbered_shell_count"]==1,"risk_trace_stable":d["risk"]["summary"]["risk_count"]==84 and d["trace"]["summary"]["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_accounting_expert_playbook_contract_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","safety":{"mode":"OFFLINE_EVIDENCE_SYNTHESIS","database_connections":0,"commands_forms_reports_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"sensitive_values_persisted":0},"summary":{"playbook_count":5,"target_contract_section_count":len(contract),"golden_case_gate_count":42,"runtime_incidents_diagnosed_count":0,"repairs_performed_count":0,"risk_count":84,"mapped_risk_assignment_count":343,"new_risk_count":0},"playbooks":pbs,"target_erp_contract":contract,"evidence_classification":{"CONFIRMED":"hash-pinned static path or persisted aggregate contract","STRONG_INFERENCE":"control/data flow implied but runtime branch not observed","HYPOTHESIS":"incident-specific explanation requiring evidence","REJECTED":"UI close as financial cancel; error text as rollback proof; MAX(history) as current pointer"},"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"confidence":{"playbook_structure":"HIGH","incident_specific_diagnosis":"REQUIRES_INCIDENT_EVIDENCE","runtime_parity":"UNPROVEN"},"limits":["No named production incident was diagnosed.","No repair or UAT was executed.","Owner disposition remains required for quarantined historical states."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
