"""Build a static baseline-action shortlist for the five P3 report-command handoffs."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
S={"priority":"artifacts/varanegar_analysis/varanegar_action_alias_handoff_priority_matrix_20260829.json","owner":"artifacts/varanegar_analysis/varanegar_action_alias_owner_evidence_packet_matrix_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_p2_final_evidence_gap_status_checkpoint_20260829.json","reporting":"artifacts/varanegar_analysis/varanegar_reporting_output_golden_uat_cases_20260829.json","report_base":"artifacts/varanegar_analysis/ui/varanegar_report_target_contracts_golden_cases_20260827.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json"}
C={"AAP-25":["statement.vn_sds_treasury_ui_statement_formstatement.create_or_update","statement.vn_sds_treasury_ui_statement_formstatementdataentry.create_or_update"],"AAP-26":["document.vn_sds_sales_ui_printbatch_formprintbatch.mark_print_completed"],"AAP-27":["report.vn_sds_stock_ui_vchhealthycardex_formvchhealthycardex.export_file"],"AAP-28":["document.vn_sds_sales_ui_retsale_formreportretsale.mark_print_completed"],"AAP-29":["document.vn_sds_sales_ui_sale_formreportfactor.mark_print_completed"]}
FIELDS=["source_packet_and_case_set_hash","searched_baseline_modules","candidate_baseline_action_or_explicit_none","candidate_baseline_case_ids","category_to_kind_normalization","case_kind_overlap","precondition_equivalence_disposition","outcome_vocabulary_mapping","assertion_and_effect_mapping","versioned_alias_or_new_action_disposition","accountable_role_receipts","policy_version_expiry_and_supersession"]
NORM={"happy_path":"success","export":"success","fault_injection":"failure_injection","partial_failure":"failure_injection","versioning":"concurrency"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def action(x):return str(x.get("command") or x.get("surface") or x.get("command_id") or "")
def kind(x):
 k=str(x.get("kind") or x.get("case_kind") or x.get("category") or "").strip().casefold();return NORM.get(k,k)
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};base=d["report_base"]["golden_cases"];priority={x["source_packet_id"]:x for x in d["priority"]["handoff_packets"]};owner={x["packet_id"]:x for x in d["owner"]["action_alias_packets"]};ids=sorted(k for k,v in priority.items() if v["priority_rank"]==3);packets=[]
 for pid in ids:
  p=priority[pid];o=owner[pid];nk={kind({"kind":x}) for x in o["case_kinds"]};candidates=[]
  for act in C[pid]:
   match=[x for x in base if action(x)==act];bk={kind(x) for x in match if kind(x)};candidates.append({"baseline_module":"reporting_documents","baseline_action":act,"baseline_case_count":len(match),"baseline_case_ids":sorted(x["case_id"] for x in match),"baseline_case_kinds":sorted(bk),"overlapping_case_kinds":sorted(nk&bk),"overlapping_case_kind_count":len(nk&bk),"exact_action_string_match":act.casefold()==p["newer_action_or_surface"].casefold(),"candidate_status":"REVIEW_REQUIRED_NOT_SEMANTIC_EQUIVALENCE"})
  packets.append({"shortlist_id":f"P3S-{len(packets)+1:02d}","source_packet_id":pid,"module":p["module"],"newer_action_or_surface":p["newer_action_or_surface"],"newer_case_count":p["case_count"],"newer_case_id_set_sha256":p["case_id_set_sha256"],"newer_case_kinds":sorted(nk),"searched_baseline_modules":["reporting_documents"],"searched_baseline_case_count":len(base),"candidate_class":"REPORT_COMMAND_OR_RENDER_FAMILY_REVIEW" if candidates else "EXPLICIT_NONE_AFTER_RECONSTRUCTED_BASELINE_SEARCH","candidate_baseline_action_count":len(candidates),"candidate_baseline_actions":candidates,"accountable_role_types":p["accountable_role_types"],"required_disposition_fields":FIELDS,"current_status":"WAITING_FOR_EVIDENCE_BACKED_CANDIDATE_DISPOSITION","accepted_candidate_action_count":0,"accepted_case_disposition_count":0,"counting_effect":"ZERO"})
 allc=[x for p in packets for x in p["candidate_baseline_actions"]];s={"p3_packet_count":len(packets),"p3_case_count":sum(x["newer_case_count"] for x in packets),"candidate_bearing_packet_count":sum(bool(x["candidate_baseline_action_count"]) for x in packets),"explicit_none_packet_count":sum(not x["candidate_baseline_action_count"] for x in packets),"candidate_baseline_action_reference_count":len(allc),"candidate_baseline_case_reference_count":sum(x["baseline_case_count"] for x in allc),"candidate_case_kind_overlap_reference_count":sum(x["overlapping_case_kind_count"] for x in allc),"exact_action_string_match_count":sum(x["exact_action_string_match"] for x in allc),"searched_baseline_case_reference_count":sum(x["searched_baseline_case_count"] for x in packets),"accountable_role_assignment_count":sum(len(x["accountable_role_types"]) for x in packets),"required_disposition_field_count":len(FIELDS),"accepted_candidate_action_count":0,"accepted_case_disposition_count":0,"exact_non_duplicated_additive_count":0,"design_lower_bound_before_shortlist":1404,"design_lower_bound_after_shortlist":1404,"executed_case_count":0,"owner_approved_case_count":0,"command_ready_module_count":0,"pilot_ready_module_count":0,"risk_count":d["risk"]["summary"]["risk_count"],"mapped_risk_assignment_count":d["trace"]["summary"]["mapped_risk_assignment_count"],"new_risk_count":0}
 checks={"sources_pass":all(x.get("validation")=="PASS" for x in d.values()),"p3_5_35":s["p3_packet_count"]==5 and s["p3_case_count"]==35,"candidate_split_5_0":(s["candidate_bearing_packet_count"],s["explicit_none_packet_count"])==(5,0),"refs_6_31_26":(s["candidate_baseline_action_reference_count"],s["candidate_baseline_case_reference_count"],s["candidate_case_kind_overlap_reference_count"])==(6,31,26),"no_exact_action":s["exact_action_string_match_count"]==0,"search_875":s["searched_baseline_case_reference_count"]==875,"roles_fields":s["accountable_role_assignment_count"]==10 and s["required_disposition_field_count"]==12,"all_review_zero":all(x["accepted_candidate_action_count"]==x["accepted_case_disposition_count"]==0 and x["counting_effect"]=="ZERO" for x in packets),"non_additive_1404":s["design_lower_bound_before_shortlist"]==s["design_lower_bound_after_shortlist"]==1404 and s["exact_non_duplicated_additive_count"]==0,"execution_readiness_zero":s["executed_case_count"]==s["owner_approved_case_count"]==s["command_ready_module_count"]==s["pilot_ready_module_count"]==0,"base_stable":s["risk_count"]==84 and s["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_p3_alias_baseline_candidate_shortlist_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","scope":{"mode":"OFFLINE_P3_BASELINE_CANDIDATE_SHORTLIST","continuation_complete":False},"safety":{"database_connections":0,"golden_uat_or_operational_execution":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"write_access_created":0,"raw_business_values_identity_or_credentials_persisted":0},"summary":s,"category_to_kind_normalization":NORM,"required_disposition_fields":FIELDS,"p3_candidate_packets":packets,"interpretation_rule":"report command/render family similarity and normalized kind overlap are shortlist evidence only, never result parity, semantic equivalence, or acceptance","checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":p.stat().st_size,"sha256":sha(p)} for k,p in sorted(paths.items())]+[{"name":"builder","path":"scripts/windows/build_varanegar_p3_alias_baseline_candidate_shortlist_20260829.py","size_bytes":Path(__file__).stat().st_size,"sha256":sha(Path(__file__))}],"limits":["Normalization aligns versioning/concurrency and partial/fault failure only for comparison.","Print, export, completion and statement mutation remain distinct until disposition.","No case is executed and no candidate is accepted."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(s,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
