"""Apply the Pricing Rules outcome-contract design delta to module readiness."""
from __future__ import annotations
import argparse, copy, hashlib, json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
S={"base":"artifacts/varanegar_analysis/varanegar_reporting_output_readiness_delta_20260829.json","envelope":"artifacts/varanegar_analysis/varanegar_pricing_rule_outcome_envelope_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_pricing_rule_outcome_checkpoint_20260829.json"}
def load(p): return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 p=argparse.ArgumentParser();p.add_argument("--output",required=True,type=Path);a=p.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};modules=copy.deepcopy(d["base"]["modules"]);pricing=next(x for x in modules if x["module"]=="pricing_rules");before=pricing["truth_table_dimensions"]["outcome_retry_idempotency"]["target_contract"]
 pricing["mapped_validated_evidence"].append({"key":"pricing_rule_outcome","path":S["envelope"],"validation":d["envelope"]["validation"]});pricing["truth_table_dimensions"]["outcome_retry_idempotency"]["target_contract"]=True;pricing["legacy_open_blockers"].extend(["owner-approved precedence, qualification, closure and explain policies remain unproven","legacy MAX(Id)+1 must be replaced by an atomic allocator and parallel-writer proof","stored executable condition SQL must be replaced by an allowlisted versioned AST/DSL","replication authentication, ordering, idempotent receipt and quarantine remain unproven"])
 summary={"module_count":len(modules),"changed_module_count":1,"outcome_target_contract_module_count_before":sum(x["truth_table_dimensions"]["outcome_retry_idempotency"]["target_contract"] for x in d["base"]["modules"]),"outcome_target_contract_module_count_after":sum(x["truth_table_dimensions"]["outcome_retry_idempotency"]["target_contract"] for x in modules),"pricing_command_contract_count":d["envelope"]["summary"]["command_contract_count"],"runtime_retry_idempotency_proven_module_count":0,"command_ready_module_count":0,"pilot_ready_module_count":0,"risk_count":84,"mapped_risk_assignment_count":343,"new_risk_count":0}
 checks={"sources_pass":all(x["validation"]=="PASS" for x in d.values()),"fourteen_modules":len(modules)==14,"pricing_false_to_true":before is False and pricing["truth_table_dimensions"]["outcome_retry_idempotency"]["target_contract"] is True,"seven_to_eight":summary["outcome_target_contract_module_count_before"]==7 and summary["outcome_target_contract_module_count_after"]==8,"seven_commands":summary["pricing_command_contract_count"]==7,"one_changed":sum(x["truth_table_dimensions"]["outcome_retry_idempotency"]["target_contract"]!=y["truth_table_dimensions"]["outcome_retry_idempotency"]["target_contract"] for x,y in zip(d["base"]["modules"],modules))==1,"runtime_zero":summary["runtime_retry_idempotency_proven_module_count"]==summary["command_ready_module_count"]==summary["pilot_ready_module_count"]==0,"base_stable":d["risk"]["summary"]["risk_count"]==84 and d["trace"]["summary"]["mapped_risk_assignment_count"]==343}
 failed=sorted(k for k,v in checks.items() if not v);out={"artifact":"varanegar_pricing_rule_readiness_delta_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","safety":{"mode":"OFFLINE_DESIGN_DELTA","database_connections":0,"commands_forms_reports_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"sensitive_values_persisted":0},"summary":summary,"modules":modules,"promotion_boundary":{"changed":"pricing_rules outcome/retry target contract design only","unchanged":["runtime authorization","runtime atomic allocation","runtime effect parity","runtime retry/idempotency","owner approval","command readiness","pilot readiness"]},"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"confidence":{"design_delta":"HIGH","runtime_readiness":"NOT_PROVEN"},"limits":["Design coverage is not implementation readiness.","No pricing rule command or validation was executed.","Owner-approved precedence and qualification policies remain external gates."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(summary,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__": raise SystemExit(main())
