"""Build evidence-first distribution incident playbooks."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S={"envelope":"artifacts/varanegar_analysis/varanegar_distribution_command_outcome_envelope_20260829.json","golden":"artifacts/varanegar_analysis/varanegar_distribution_golden_uat_cases_20260829.json","lifecycle":"artifacts/varanegar_analysis/domains/distribution_exit_lifecycle_boundary_20260829.json","runtime":"artifacts/varanegar_analysis/domains/distribution_exit_runtime_boundary_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_distribution_golden_uat_checkpoint_20260829.json"}
COMMON=["capture correlation/command id, actor capability, route/DC/fiscal/date scope and expected version without PII","verify source hashes and stop on drift","read distribution state/history, exit lifecycle, type-60 voucher graph, sale links and audit/outbox","compare typed outcome with durable evidence; message or transport status never proves rollback","classify NATURAL_BEHAVIOR, DATA_DEBT, BUG or UNPROVEN","stop before repair or replay","design isolated synthetic fault injection if physical enlistment is still uncertain"]
PB=[
{"id":"DS-PB-01","incident":"create/update returned a number or history conflict","focus":"number allocation and multi-table history writes lack explicit idempotency","extra":"compare source identity, distribution number, sale links and ordered history; quarantine duplicate identity","risks":["R-005","R-006","R-007"]},
{"id":"DS-PB-02","incident":"Issue Exit failed after a late cardex check","focus":"exit/voucher/item/history writes precede the cardex post-check and procedure has no local transaction","extra":"read every durable effect and return typed durable-effect outcome unless one rollback boundary is proven","risks":["R-007","R-034","R-036"]},
{"id":"DS-PB-03","incident":"Merge/Adjust Exit result is unknown","focus":"UI and adapter expose no explicit transaction owner or idempotency key","extra":"reconcile goods-exit relation projection by distribution/source identity before retry","risks":["R-005","R-006","R-023"]},
{"id":"DS-PB-04","incident":"Remove Exit left a partial graph","focus":"voucher delete, sale unlink, soft cancel and distribution reset depend on caller atomicity","extra":"compare cancel flag/date, type-60 delete log, sale links, distribution status and history; block blind remove retry","risks":["R-007","R-034","R-043"]},
{"id":"DS-PB-05","incident":"distribution or exit is absent while audit/history remains","focus":"eight logged exits and six distributions are historically absent; direct physical-delete paths are separate from soft cancel","extra":"classify historical absence only after correlating generic log, type-60 delete evidence and status chain; never synthesize current state","risks":["R-008","R-023","R-043"]},
]
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};pbs=[{**x,"steps":COMMON+[x["extra"]],"stop_conditions":["hash drift","write/repair required","raw sensitive values would be persisted","owner policy required"],"runtime_diagnosis":"NOT_PERFORMED"} for x in PB];life=d["lifecycle"]["summary"];s={"playbook_count":len(pbs),"minimum_step_count":min(len(x["steps"]) for x in pbs),"distribution_command_count":d["envelope"]["summary"]["command_count"],"golden_case_count":d["golden"]["summary"]["case_count"],"active_exit_count":life["current_active_exit_count"],"cancelled_exit_count":life["current_cancelled_exit_count"],"logged_exit_absent_count":life["logged_exit_absent_count"],"historically_absent_distribution_count":life["historically_absent_distribution_count"],"runtime_incidents_diagnosed_count":0,"repairs_performed_count":0,"owner_approved_count":0,"risk_count":84,"mapped_risk_assignment_count":343,"new_risk_count":0};risks={x["id"] for x in d["risk"]["risks"]};checks={"sources_pass":all(x["validation"]=="PASS" for x in d.values()),"five_playbooks":s["playbook_count"]==5,"eight_steps":all(len(x["steps"])==8 for x in pbs),"four_way":all("NATURAL_BEHAVIOR, DATA_DEBT, BUG or UNPROVEN" in x["steps"][4] for x in pbs),"all_risks_exist":all(r in risks for x in pbs for r in x["risks"]),"four_and_twenty_eight":s["distribution_command_count"]==4 and s["golden_case_count"]==28,"lifecycle_counts":s["logged_exit_absent_count"]==8 and s["historically_absent_distribution_count"]==6,"runtime_zero":s["runtime_incidents_diagnosed_count"]==s["repairs_performed_count"]==s["owner_approved_count"]==0,"base_stable":d["risk"]["summary"]["risk_count"]==84 and d["trace"]["summary"]["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_distribution_expert_playbook_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","safety":{"mode":"OFFLINE_EVIDENCE_SYNTHESIS","database_connections":0,"commands_forms_reports_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"sensitive_values_persisted":0},"summary":s,"playbooks":pbs,"diagnostic_result_contract":{"allowed":["NATURAL_BEHAVIOR","DATA_DEBT","BUG","UNPROVEN"],"requires_named_incident_evidence":True,"repair_is_separate_authorized_work":True},"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"confidence":{"structure":"HIGH","incident_diagnosis":"REQUIRES_INCIDENT_EVIDENCE"},"limits":["No named incident was diagnosed.","No repair, command or UAT was executed.","Clone aggregates are not production-current truth."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(s,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
