"""Build adjudication packets for the 19 P1 bank failure-injection pairs."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
S={"comparator":"artifacts/varanegar_analysis/varanegar_p1_alias_semantic_evidence_comparator_20260829.json","shortlist":"artifacts/varanegar_analysis/varanegar_p1_alias_baseline_candidate_shortlist_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_p1_alias_semantic_evidence_checkpoint_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json"}
FIELDS=["newer_and_baseline_case_ids","fault_stage_mapping","transaction_boundary_receipt","durable_write_set_receipt","rollback_or_unknown_outcome_disposition","retry_idempotency_receipt","audit_outbox_receipt","bank_cardex_or_link_reconciliation","outcome_vocabulary_mapping","assertion_effect_mapping","accountable_role_receipts","policy_version_expiry_supersession"]
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def stage(case_id):
 n=case_id.casefold().replace("-","_");return "fault_after_"+n.split("fault_after_",1)[1] if "fault_after_" in n else n.rsplit(".",1)[-1]
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};short={x["source_packet_id"]:x for x in d["shortlist"]["p1_candidate_packets"]};grouped={}
 for comparison in d["comparator"]["candidate_comparisons"]:
  failure=[x for x in comparison["case_pair_comparisons"] if x["case_kind"]=="failure_injection"]
  if not failure:continue
  packet=grouped.setdefault(comparison["source_packet_id"],{"source_packet_id":comparison["source_packet_id"],"newer_action_or_surface":comparison["newer_action_or_surface"],"accountable_role_types":short[comparison["source_packet_id"]]["accountable_role_types"],"candidate_failure_comparisons":[]})
  for row in failure:
   bs=stage(row["baseline_case_id"]);ns=stage(row["newer_case_id"]);bo=row["baseline_outcome_label"]
   packet["candidate_failure_comparisons"].append({"comparison_id":comparison["comparison_id"],"baseline_action":comparison["baseline_action"],"newer_case_id":row["newer_case_id"],"baseline_case_id":row["baseline_case_id"],"newer_fault_stage":ns,"baseline_fault_stage":bs,"fault_stage_exact":ns==bs,"fault_stage_relation":"EXACT_LABEL_STILL_SEMANTIC_REVIEW" if ns==bs else "GENERIC_OR_DIFFERENT_NEWER_TO_DETAILED_BASELINE_STAGE_REVIEW","newer_outcome_label":row["newer_outcome_label"],"baseline_outcome_label":bo,"outcome_exact":row["outcome_exact"],"assertion_list_exact":row["assertion_list_exact"],"baseline_retry_or_convergence_explicit":("retry" in bo or "converge" in bo),"baseline_no_partial_effect_explicit":"no partial" in bo,"audit_or_outbox_sensitive_stage":("audit" in bs or "outbox" in bs),"required_disposition_fields":FIELDS,"current_status":"WAITING_FOR_FAILURE_STAGE_AND_DURABLE_EFFECT_DISPOSITION","accepted_pair_count":0,"counting_effect":"ZERO"})
 packets=[]
 for i,p in enumerate(sorted(grouped.values(),key=lambda x:x["source_packet_id"]),1):p.update({"adjudication_packet_id":f"P1F-{i:02d}","failure_pair_count":len(p["candidate_failure_comparisons"]),"accepted_pair_count":0,"current_status":"WAITING_FOR_FAILURE_STAGE_AND_DURABLE_EFFECT_DISPOSITION","counting_effect":"ZERO"});packets.append(p)
 pairs=[x for p in packets for x in p["candidate_failure_comparisons"]];summary={"source_packet_count":len(packets),"candidate_action_comparison_count":len({x["comparison_id"] for x in pairs}),"failure_injection_pair_count":len(pairs),"newer_unique_failure_case_count":len({x["newer_case_id"] for x in pairs}),"baseline_unique_failure_case_count":len({x["baseline_case_id"] for x in pairs}),"exact_fault_stage_label_pair_count":sum(x["fault_stage_exact"] for x in pairs),"generic_or_different_to_detailed_stage_pair_count":sum(not x["fault_stage_exact"] for x in pairs),"baseline_retry_or_convergence_explicit_pair_count":sum(x["baseline_retry_or_convergence_explicit"] for x in pairs),"baseline_no_partial_effect_explicit_pair_count":sum(x["baseline_no_partial_effect_explicit"] for x in pairs),"audit_or_outbox_sensitive_stage_pair_count":sum(x["audit_or_outbox_sensitive_stage"] for x in pairs),"outcome_exact_pair_count":sum(x["outcome_exact"] for x in pairs),"assertion_list_exact_pair_count":sum(x["assertion_list_exact"] for x in pairs),"fully_exact_pair_count":sum(x["fault_stage_exact"] and x["outcome_exact"] and x["assertion_list_exact"] for x in pairs),"accountable_role_assignment_count":sum(len(x["accountable_role_types"]) for x in packets),"required_disposition_field_count":len(FIELDS),"accepted_failure_pair_count":0,"exact_non_duplicated_additive_count":0,"design_lower_bound_before_failure_adjudication":d["comparator"]["summary"]["design_lower_bound_after_comparator"],"design_lower_bound_after_failure_adjudication":d["comparator"]["summary"]["design_lower_bound_after_comparator"],"executed_case_count":0,"owner_approved_case_count":0,"command_ready_module_count":0,"pilot_ready_module_count":0,"risk_count":d["risk"]["summary"]["risk_count"],"mapped_risk_assignment_count":d["trace"]["summary"]["mapped_risk_assignment_count"],"new_risk_count":0}
 checks={"sources_pass":all(x.get("validation")=="PASS" for x in d.values()),"four_packets_four_candidates_19_pairs":(summary["source_packet_count"],summary["candidate_action_comparison_count"],summary["failure_injection_pair_count"])==(4,4,19),"unique_cases_5_15":(summary["newer_unique_failure_case_count"],summary["baseline_unique_failure_case_count"])==(5,15),"stage_split_0_19":(summary["exact_fault_stage_label_pair_count"],summary["generic_or_different_to_detailed_stage_pair_count"])==(0,19),"baseline_properties_15_16_9":(summary["baseline_retry_or_convergence_explicit_pair_count"],summary["baseline_no_partial_effect_explicit_pair_count"],summary["audit_or_outbox_sensitive_stage_pair_count"])==(15,16,9),"no_exact_semantic_pair":summary["outcome_exact_pair_count"]==summary["assertion_list_exact_pair_count"]==summary["fully_exact_pair_count"]==0,"roles_fields":summary["accountable_role_assignment_count"]==8 and summary["required_disposition_field_count"]==12,"all_waiting_zero":all(p["current_status"].startswith("WAITING") and p["accepted_pair_count"]==0 and p["counting_effect"]=="ZERO" for p in packets),"non_additive_1404":summary["accepted_failure_pair_count"]==summary["exact_non_duplicated_additive_count"]==0 and summary["design_lower_bound_before_failure_adjudication"]==summary["design_lower_bound_after_failure_adjudication"]==1404,"execution_readiness_zero":summary["executed_case_count"]==summary["owner_approved_case_count"]==summary["command_ready_module_count"]==summary["pilot_ready_module_count"]==0,"base_stable":summary["risk_count"]==84 and summary["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_p1_failure_injection_adjudication_packets_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","scope":{"mode":"OFFLINE_P1_BANK_FAILURE_INJECTION_ADJUDICATION_DESIGN","continuation_complete":False},"safety":{"database_connections":0,"golden_uat_or_operational_execution":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"write_access_created":0,"raw_business_values_identity_or_credentials_persisted":0},"summary":summary,"required_disposition_fields":FIELDS,"failure_adjudication_packets":packets,"priority_rule":"generic fault-after-first-write or partial-instrument labels must not absorb detailed bank state, link, cardex, cleanup, audit, outbox, rollback, or retry semantics","checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":p.stat().st_size,"sha256":sha(p)} for k,p in sorted(paths.items())]+[{"name":"builder","path":"scripts/windows/build_varanegar_p1_failure_injection_adjudication_packets_20260829.py","size_bytes":Path(__file__).stat().st_size,"sha256":sha(Path(__file__))}],"limits":["Fault-stage labels are design evidence, not executed rollback proof.","No fault-stage, outcome, or assertion tuple is exact.","No candidate, case pair, or owner disposition is accepted."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(summary,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
