"""Build non-duplicating configuration Golden/UAT delta cases."""
from __future__ import annotations
import argparse,collections,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S={"envelope":"artifacts/varanegar_analysis/varanegar_configuration_outcome_envelope_20260829.json","readiness":"artifacts/varanegar_analysis/varanegar_configuration_readiness_delta_20260829.json","existing":"artifacts/varanegar_analysis/ui/varanegar_extension_golden_cases_20260827.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_configuration_readiness_checkpoint_20260829.json"}
F={"CF-PRE":("configuration.resolve_precedence","deterministic multi-table scope precedence"),"CF-NULL":("configuration.resolve_null_removed","typed null semantics and removed-reference quarantine"),"CF-SEC":("configuration.publish_secret_reference","secret reference validation without secret value"),"CF-ROL":("configuration.rollout_ack_and_rollback","consumer acknowledgement and rollback-by-new-version")}
CASES=[("AUTH_DENIED","authorization","REJECTED_NO_EFFECT"),("STALE_VERSION","concurrency","REJECTED_NO_EFFECT"),("DUPLICATE_COMMAND","idempotency","ORIGINAL_RECEIPT_ONLY_ONCE"),("INVALID_OR_AMBIGUOUS","validation","REJECTED_OR_QUARANTINED"),("FAIL_AFTER_POINTER_OR_OUTBOX","failure_injection","ROLLED_BACK_OR_UNKNOWN_REQUIRES_READBACK"),("PARALLEL_OR_PARTIAL_ACK","concurrency","DETERMINISTIC_VERSION_AND_PER_CONSUMER_OUTCOME"),("SUCCESS","success","PUBLISHED_WITH_RESOLUTION_AND_ACK_RECEIPTS")]
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 p=argparse.ArgumentParser();p.add_argument("--output",required=True,type=Path);a=p.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};old=[x for x in d["existing"]["cases"] if str(x.get("surface","")).startswith("configuration.")];special={"CF-PRE":"equal candidates use the approved stable tuple or reject; never storage or iteration order","CF-NULL":"INHERIT, EXPLICIT_NULL and VALUE remain distinct; active references to removed candidates quarantine","CF-SEC":"fixture carries only a synthetic vault handle/hash and asserts no secret appears in command, result, audit or logs","CF-ROL":"partial consumer acknowledgement remains visible and rollback publishes a new version without rewriting history"};cases=[]
 for prefix,(surface,focus) in F.items():
  for code,kind,expected in CASES:cases.append({"case_id":f"{prefix}-{code}","surface":surface,"case_kind":kind,"focus":focus,"expected_outcome":expected,"assertions":["CommandId, PayloadHash, ExpectedVersion and publish scope govern replay","version/pointer/audit/outbox effects reconcile atomically","ResolutionTrace and per-consumer acknowledgement are preserved",special[prefix],"source Varanegar and read-only evidence remain untouched"],"status":"DESIGNED_NOT_EXECUTED"})
 summary={"existing_reused_case_count":len(old),"existing_reused_command_count":len({x["surface"] for x in old}),"delta_surface_count":len(F),"delta_case_count":len(cases),"combined_configuration_acceptance_design_count":len(old)+len(cases),"case_count_per_delta_surface":7,"case_kind_counts":dict(sorted(collections.Counter(x["case_kind"] for x in cases).items())),"executed_delta_case_count":0,"passed_runtime_case_count":0,"owner_approved_case_count":0,"runtime_retry_idempotency_proven_module_count":0,"command_ready_module_count":0,"pilot_ready_module_count":0,"risk_count":84,"mapped_risk_assignment_count":343,"new_risk_count":0}
 checks={"sources_pass":all(v["validation"]=="PASS" for v in d.values()),"reuse_54_three_commands":len(old)==54 and len({x["surface"] for x in old})==3,"delta_28":len(cases)==28 and all(sum(x["surface"]==surface for x in cases)==7 for surface,_ in F.values()),"unique_ids":len({x["case_id"] for x in cases})==28,"no_old_collision":not ({x["case_id"] for x in cases}&{x["case_id"] for x in old}),"combined_82":summary["combined_configuration_acceptance_design_count"]==82,"all_unexecuted":{x["status"] for x in cases}=={"DESIGNED_NOT_EXECUTED"},"ten_contract_modules":d["readiness"]["summary"]["outcome_target_contract_module_count_after"]==10,"runtime_zero":summary["executed_delta_case_count"]==summary["passed_runtime_case_count"]==summary["owner_approved_case_count"]==summary["runtime_retry_idempotency_proven_module_count"]==summary["command_ready_module_count"]==summary["pilot_ready_module_count"]==0,"base_stable":d["risk"]["summary"]["risk_count"]==84 and d["trace"]["summary"]["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_configuration_golden_uat_cases_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","safety":{"mode":"OFFLINE_SYNTHETIC_DESIGN","database_connections":0,"network_reads_or_writes":0,"configuration_commands_or_forms_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"secret_or_business_values_read_or_persisted":0},"summary":summary,"reuse_manifest":{"source":S["existing"],"policy":"reuse 54 existing general/web-service/article-template cases; do not duplicate them"},"execution_gate":{"environment":"isolated target only","requirements":["typed synthetic configuration schema and scopes","synthetic vault adapter with no real secret","parallel publish and stale-version harness","fault injection at append/pointer/outbox/consumer-ack boundaries","owner-approved precedence, null, retirement and rollback policies"],"promotion_rule":"all 82 reused plus delta obligations execute with zero unexplained effective-value or rollout difference and owner approval"},"cases":cases,"checks":checks,"failed_checks":failed,"risk_links":["R-002","R-005","R-006","R-007","R-008","R-023","R-031","R-034","R-036","R-043"],"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"confidence":{"design":"HIGH","runtime":"NOT_EXECUTED"},"limits":["These are acceptance designs, not UAT results.","No configuration publish, secret lookup or rollback was executed.","No real configuration or secret value is present in fixtures or artifacts."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(summary,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
