"""Build outcome-vocabulary adjudication packets for 36 non-failure P1 pairs."""
from __future__ import annotations
import argparse,hashlib,json
from collections import defaultdict
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
S={"comparator":"artifacts/varanegar_analysis/varanegar_p1_alias_semantic_evidence_comparator_20260829.json","shortlist":"artifacts/varanegar_analysis/varanegar_p1_alias_baseline_candidate_shortlist_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_p1_failure_injection_adjudication_checkpoint_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json"}
FIELDS=["control_kind","source_packet_and_case_ids","newer_outcome_label","baseline_outcome_label","label_equivalence_disposition","precondition_equivalence","assertion_effect_equivalence","denial_or_commit_effect_class","retry_or_current_version_contract","accountable_role_receipts","policy_version_expiry_supersession"]
KINDS=("authorization","concurrency","idempotency","scope","success")
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};roles={x["source_packet_id"]:x["accountable_role_types"] for x in d["shortlist"]["p1_candidate_packets"]};grouped=defaultdict(list)
 for c in d["comparator"]["candidate_comparisons"]:
  for row in c["case_pair_comparisons"]:
   if row["case_kind"]=="failure_injection":continue
   grouped[row["case_kind"]].append({"source_packet_id":c["source_packet_id"],"comparison_id":c["comparison_id"],"newer_action_or_surface":c["newer_action_or_surface"],"baseline_action":c["baseline_action"],**row})
 packets=[]
 for i,k in enumerate(KINDS,1):
  rows=grouped[k];ids=sorted({x["source_packet_id"] for x in rows});nv=sorted({x["newer_outcome_label"] for x in rows});bv=sorted({x["baseline_outcome_label"] for x in rows});packets.append({"outcome_packet_id":f"P1O-{i:02d}","control_kind":k,"source_packet_ids":ids,"accountable_role_types":sorted({r for pid in ids for r in roles[pid]}),"case_pair_count":len(rows),"newer_outcome_vocabulary":nv,"baseline_outcome_vocabulary":bv,"newer_outcome_vocabulary_count":len(nv),"baseline_outcome_vocabulary_count":len(bv),"outcome_label_exact_pair_count":sum(x["outcome_exact"] for x in rows),"outcome_label_mapping_required_pair_count":sum(not x["outcome_exact"] for x in rows),"assertion_list_exact_pair_count":sum(x["assertion_list_exact"] for x in rows),"full_disposition_required_pair_count":len(rows),"pair_rows":rows,"required_disposition_fields":FIELDS,"current_status":"WAITING_FOR_OUTCOME_VOCABULARY_AND_EFFECT_DISPOSITION","accepted_pair_count":0,"counting_effect":"ZERO"})
 rows=[x for p in packets for x in p["pair_rows"]];summary={"control_kind_packet_count":len(packets),"non_failure_case_pair_count":len(rows),"authorization_pair_count":len(grouped["authorization"]),"concurrency_pair_count":len(grouped["concurrency"]),"idempotency_pair_count":len(grouped["idempotency"]),"scope_pair_count":len(grouped["scope"]),"success_pair_count":len(grouped["success"]),"global_newer_outcome_vocabulary_count":len({x["newer_outcome_label"] for x in rows}),"global_baseline_outcome_vocabulary_count":len({x["baseline_outcome_label"] for x in rows}),"per_kind_newer_outcome_vocabulary_count":sum(p["newer_outcome_vocabulary_count"] for p in packets),"per_kind_baseline_outcome_vocabulary_count":sum(p["baseline_outcome_vocabulary_count"] for p in packets),"generic_rejected_no_effect_pair_count":sum(x["newer_outcome_label"]=="rejected_no_effect" for x in rows),"generic_committed_original_once_pair_count":sum(x["newer_outcome_label"]=="committed_original_outcome_only_once" for x in rows),"outcome_label_exact_pair_count":sum(x["outcome_exact"] for x in rows),"outcome_label_mapping_required_pair_count":sum(not x["outcome_exact"] for x in rows),"assertion_list_exact_pair_count":sum(x["assertion_list_exact"] for x in rows),"fully_exact_pair_count":sum(x["outcome_exact"] and x["assertion_list_exact"] and x["precondition_exact"] for x in rows),"accountable_role_assignment_count":sum(len(p["accountable_role_types"]) for p in packets),"required_disposition_field_count":len(FIELDS),"accepted_outcome_pair_count":0,"exact_non_duplicated_additive_count":0,"design_lower_bound_before_outcome_adjudication":d["comparator"]["summary"]["design_lower_bound_after_comparator"],"design_lower_bound_after_outcome_adjudication":d["comparator"]["summary"]["design_lower_bound_after_comparator"],"executed_case_count":0,"owner_approved_case_count":0,"command_ready_module_count":0,"pilot_ready_module_count":0,"risk_count":d["risk"]["summary"]["risk_count"],"mapped_risk_assignment_count":d["trace"]["summary"]["mapped_risk_assignment_count"],"new_risk_count":0}
 checks={"sources_pass":all(x.get("validation")=="PASS" for x in d.values()),"five_packets_36_pairs":summary["control_kind_packet_count"]==5 and summary["non_failure_case_pair_count"]==36,"kind_distribution":(summary["authorization_pair_count"],summary["concurrency_pair_count"],summary["idempotency_pair_count"],summary["scope_pair_count"],summary["success_pair_count"])==(5,7,11,9,4),"vocabulary_counts":(summary["global_newer_outcome_vocabulary_count"],summary["global_baseline_outcome_vocabulary_count"],summary["per_kind_newer_outcome_vocabulary_count"],summary["per_kind_baseline_outcome_vocabulary_count"])==(3,16,5,16),"generic_concentration_21_11":(summary["generic_rejected_no_effect_pair_count"],summary["generic_committed_original_once_pair_count"])==(21,11),"exactness_0_36_0_0":(summary["outcome_label_exact_pair_count"],summary["outcome_label_mapping_required_pair_count"],summary["assertion_list_exact_pair_count"],summary["fully_exact_pair_count"])==(0,36,0,0),"roles_fields":summary["accountable_role_assignment_count"]==10 and summary["required_disposition_field_count"]==11,"all_waiting_zero":all(p["current_status"].startswith("WAITING") and p["accepted_pair_count"]==0 and p["counting_effect"]=="ZERO" for p in packets),"non_additive_1404":summary["accepted_outcome_pair_count"]==summary["exact_non_duplicated_additive_count"]==0 and summary["design_lower_bound_before_outcome_adjudication"]==summary["design_lower_bound_after_outcome_adjudication"]==1404,"execution_readiness_zero":summary["executed_case_count"]==summary["owner_approved_case_count"]==summary["command_ready_module_count"]==summary["pilot_ready_module_count"]==0,"base_stable":summary["risk_count"]==84 and summary["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_p1_control_outcome_vocabulary_adjudication_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","scope":{"mode":"OFFLINE_P1_CONTROL_OUTCOME_VOCABULARY_ADJUDICATION","continuation_complete":False},"safety":{"database_connections":0,"golden_uat_or_operational_execution":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"write_access_created":0,"raw_business_values_identity_or_credentials_persisted":0},"summary":summary,"required_disposition_fields":FIELDS,"outcome_adjudication_packets":packets,"interpretation_rule":"state-machine lineage and generic outcome labels do not establish effect equivalence; every pair requires explicit precondition, assertion, and durable-effect disposition","checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":p.stat().st_size,"sha256":sha(p)} for k,p in sorted(paths.items())]+[{"name":"builder","path":"scripts/windows/build_varanegar_p1_control_outcome_vocabulary_adjudication_20260829.py","size_bytes":Path(__file__).stat().st_size,"sha256":sha(Path(__file__))}],"limits":["Vocabulary mapping is design evidence, not runtime parity.","No equal outcome labels exist in the 36 control pairs.","No pair or owner disposition is accepted."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(summary,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
