"""Consolidate evidence-gap status for all eight P1 alias packets."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
S={"shortlist":"artifacts/varanegar_analysis/varanegar_p1_alias_baseline_candidate_shortlist_20260829.json","comparator":"artifacts/varanegar_analysis/varanegar_p1_alias_semantic_evidence_comparator_20260829.json","failure":"artifacts/varanegar_analysis/varanegar_p1_failure_injection_adjudication_packets_20260829.json","outcome":"artifacts/varanegar_analysis/varanegar_p1_control_outcome_vocabulary_adjudication_20260829.json","effect":"artifacts/varanegar_analysis/varanegar_p1_assertion_effect_family_gap_matrix_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_p1_assertion_effect_family_gap_checkpoint_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json"}
FIELDS=["source_packet_and_case_set_hash","candidate_references_or_explicit_none","versioned_alias_or_new_action_decision","state_machine_command_capability_disposition","precondition_equivalence","outcome_vocabulary_mapping","assertion_effect_equivalence","transaction_durable_effect_receipts","fault_stage_rollback_retry_receipts","audit_outbox_source_immutability_receipts","accountable_role_receipts","policy_version_expiry","conflict_and_supersession_reference"]
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};comparisons=d["comparator"]["candidate_comparisons"];effects=d["effect"]["case_pair_family_signatures"];rows=[]
 for p in d["shortlist"]["p1_candidate_packets"]:
  pid=p["source_packet_id"];cs=[x for x in comparisons if x["source_packet_id"]==pid];pairs=[x for c in cs for x in c["case_pair_comparisons"]];ef=[x for x in effects if x["source_packet_id"]==pid];failure=[x for x in pairs if x["case_kind"]=="failure_injection"]
  if p["candidate_class"]=="EXPLICIT_NONE_AFTER_RECONSTRUCTED_BASELINE_SEARCH":gap="NO_BASELINE_CANDIDATE_NEW_ACTION_OR_EXTERNAL_ALIAS_EVIDENCE_REQUIRED";route="EXTERNAL_ALIAS_OR_NEW_ACTION_DECISION_REQUIRED"
  else:gap="STATE_MACHINE_MAPPING_NOT_SEMANTICALLY_CLOSED";route="EXTERNAL_SEMANTIC_EQUIVALENCE_DECISION_REQUIRED"
  rows.append({"status_id":f"P1G-{len(rows)+1:02d}","source_packet_id":pid,"module":p["module"],"newer_action_or_surface":p["newer_action_or_surface"],"case_count":p["newer_case_count"],"case_id_set_sha256":p["newer_case_id_set_sha256"],"candidate_class":p["candidate_class"],"candidate_baseline_action_count":p["candidate_baseline_action_count"],"same_kind_case_pair_count":len(pairs),"failure_injection_pair_count":len(failure),"control_pair_count":len(pairs)-len(failure),"outcome_exact_pair_count":sum(x["outcome_exact"] for x in pairs),"assertion_list_exact_pair_count":sum(x["assertion_list_exact"] for x in pairs),"fully_exact_pair_count":sum(x["fully_exact"] for x in pairs),"exact_effect_family_set_pair_count":sum(x["exact_family_set"] for x in ef),"zero_effect_family_overlap_pair_count":sum(not x["nonempty_family_overlap"] for x in ef),"evidence_gap_class":gap,"required_decision_route":route,"accountable_role_types":p["accountable_role_types"],"required_closure_fields":FIELDS,"analysis_packetization_status":"COMPLETE_CURRENT_STATIC_SCOPE","semantic_disposition_status":"UNRESOLVED_EXTERNAL_EVIDENCE_REQUIRED","named_owner_assignment_count":0,"accepted_alias_or_new_action_decision_count":0,"accepted_case_disposition_count":0,"counting_effect":"ZERO"})
 s={"p1_status_packet_count":len(rows),"p1_case_count":sum(x["case_count"] for x in rows),"accounting_packet_count":sum(x["module"]=="accounting" for x in rows),"accounting_case_count":sum(x["case_count"] for x in rows if x["module"]=="accounting"),"treasury_packet_count":sum(x["module"]=="receivables_treasury" for x in rows),"treasury_case_count":sum(x["case_count"] for x in rows if x["module"]=="receivables_treasury"),"analysis_packetization_complete_count":sum(x["analysis_packetization_status"].startswith("COMPLETE") for x in rows),"candidate_bearing_packet_count":sum(x["candidate_baseline_action_count"]>0 for x in rows),"explicit_none_packet_count":sum(x["candidate_baseline_action_count"]==0 for x in rows),"state_machine_mapping_packet_count":sum(x["candidate_class"]=="EXPLICIT_STATE_MACHINE_COMMAND_CAPABILITY_MAPPING_REVIEW" for x in rows),"external_alias_or_new_action_decision_packet_count":sum(x["required_decision_route"]=="EXTERNAL_ALIAS_OR_NEW_ACTION_DECISION_REQUIRED" for x in rows),"external_semantic_equivalence_decision_packet_count":sum(x["required_decision_route"]=="EXTERNAL_SEMANTIC_EQUIVALENCE_DECISION_REQUIRED" for x in rows),"same_kind_case_pair_count":sum(x["same_kind_case_pair_count"] for x in rows),"failure_injection_pair_count":sum(x["failure_injection_pair_count"] for x in rows),"control_pair_count":sum(x["control_pair_count"] for x in rows),"outcome_exact_pair_count":sum(x["outcome_exact_pair_count"] for x in rows),"assertion_list_exact_pair_count":sum(x["assertion_list_exact_pair_count"] for x in rows),"fully_exact_pair_count":sum(x["fully_exact_pair_count"] for x in rows),"exact_effect_family_set_pair_count":sum(x["exact_effect_family_set_pair_count"] for x in rows),"zero_effect_family_overlap_pair_count":sum(x["zero_effect_family_overlap_pair_count"] for x in rows),"accountable_role_assignment_count":sum(len(x["accountable_role_types"]) for x in rows),"required_closure_field_count":len(FIELDS),"semantic_disposition_closed_packet_count":0,"named_owner_assignment_count":0,"accepted_alias_or_new_action_decision_count":0,"accepted_case_disposition_count":0,"exact_non_duplicated_additive_count":0,"design_lower_bound_before_p1_status":1404,"design_lower_bound_after_p1_status":1404,"executed_case_count":0,"owner_approved_case_count":0,"command_ready_module_count":0,"pilot_ready_module_count":0,"risk_count":d["risk"]["summary"]["risk_count"],"mapped_risk_assignment_count":d["trace"]["summary"]["mapped_risk_assignment_count"],"new_risk_count":0}
 checks={"sources_pass":all(x.get("validation")=="PASS" for x in d.values()),"eight_56":s["p1_status_packet_count"]==8 and s["p1_case_count"]==56,"module_split":(s["accounting_packet_count"],s["accounting_case_count"],s["treasury_packet_count"],s["treasury_case_count"])==(2,14,6,42),"packetized_not_disposed":s["analysis_packetization_complete_count"]==8 and s["semantic_disposition_closed_packet_count"]==0,"candidate_split":(s["candidate_bearing_packet_count"],s["explicit_none_packet_count"],s["state_machine_mapping_packet_count"])==(4,4,4),"decision_routes_4_4":(s["external_alias_or_new_action_decision_packet_count"],s["external_semantic_equivalence_decision_packet_count"])==(4,4),"pairs_55_19_36":(s["same_kind_case_pair_count"],s["failure_injection_pair_count"],s["control_pair_count"])==(55,19,36),"semantic_exactness_zero":(s["outcome_exact_pair_count"],s["assertion_list_exact_pair_count"],s["fully_exact_pair_count"],s["exact_effect_family_set_pair_count"],s["zero_effect_family_overlap_pair_count"])==(0,0,0,0,0),"roles_fields":s["accountable_role_assignment_count"]==16 and s["required_closure_field_count"]==13,"all_unresolved_zero":all(x["semantic_disposition_status"].startswith("UNRESOLVED") and x["named_owner_assignment_count"]==x["accepted_alias_or_new_action_decision_count"]==x["accepted_case_disposition_count"]==0 and x["counting_effect"]=="ZERO" for x in rows),"non_additive_1404":s["accepted_alias_or_new_action_decision_count"]==s["accepted_case_disposition_count"]==s["exact_non_duplicated_additive_count"]==0 and s["design_lower_bound_before_p1_status"]==s["design_lower_bound_after_p1_status"]==1404,"execution_readiness_zero":s["executed_case_count"]==s["owner_approved_case_count"]==s["command_ready_module_count"]==s["pilot_ready_module_count"]==0,"base_stable":s["risk_count"]==84 and s["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_p1_final_evidence_gap_status_matrix_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","scope":{"mode":"OFFLINE_P1_FINAL_EVIDENCE_GAP_STATUS","continuation_complete":False},"safety":{"database_connections":0,"golden_uat_or_operational_execution":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"write_access_created":0,"raw_business_values_identity_or_credentials_persisted":0},"summary":s,"required_closure_fields":FIELDS,"p1_status_packets":rows,"closure_rule":"analysis packetization may be complete while semantic disposition remains unresolved; state-machine lineage cannot replace explicit effect-equivalence receipts","checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":p.stat().st_size,"sha256":sha(p)} for k,p in sorted(paths.items())]+[{"name":"builder","path":"scripts/windows/build_varanegar_p1_final_evidence_gap_status_matrix_20260829.py","size_bytes":Path(__file__).stat().st_size,"sha256":sha(Path(__file__))}],"limits":["This closes current static packetization, not semantic disposition.","Four explicit-none packets require alias-or-new-action decisions and four mapped packets require equivalence decisions.","No owner receipt, UAT execution, alias, new action, or readiness is accepted."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(s,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
