"""Build additive integration/migration evidence and risk traceability."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S={"envelope":"artifacts/varanegar_analysis/varanegar_integration_migration_outcome_envelope_20260829.json","readiness":"artifacts/varanegar_analysis/varanegar_integration_migration_readiness_delta_20260829.json","golden":"artifacts/varanegar_analysis/varanegar_integration_migration_golden_uat_cases_20260829.json","playbook":"artifacts/varanegar_analysis/varanegar_integration_migration_expert_playbook_20260829.json","pos":"artifacts/varanegar_analysis/ui/negin_erp_pos_receipt_replication_contract_20260827.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_integration_migration_expert_playbook_checkpoint_20260829.json"}
E=["IM-E-01-outcome-receipt-envelope","IM-E-02-readiness-delta","IM-E-03-golden-uat-delta","IM-E-04-expert-playbook","IM-E-05-pos-ngt-transport-static-boundaries"]
REQ=[("IM-RQ-01","immutable package/capture identity and content authentication"),("IM-RQ-02","deny-first center and organization scope"),("IM-RQ-03","contiguous sequence and previous receipt hash"),("IM-RQ-04","per-item and per-effect idempotent receipts"),("IM-RQ-05","crosswalk write-back receipt"),("IM-RQ-06","reconciliation before acknowledgement"),("IM-RQ-07","unknown outcome quarantine and read-back"),("IM-RQ-08","append-only compensation linked to original"),("IM-RQ-09","ordered migration slice checkpoints and deterministic rerun"),("IM-RQ-10","no source write-back, silent repair or unauthorized cutover")]
MODULES=["integration_migration","sales","inventory","receivables_treasury","pricing_rules","accounting","organization_context"]
RISKS=["R-002","R-005","R-006","R-007","R-008","R-023","R-029","R-034","R-036"]
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 p=argparse.ArgumentParser();p.add_argument("--output",required=True,type=Path);a=p.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};known={x["id"] for x in d["risk"]["risks"]};ml=[{"evidence":e,"module":m,"relationship":"INTEGRATION_MIGRATION_DESIGN_EVIDENCE"} for e in E for m in MODULES];rl=[{"evidence":e,"risk":r,"relationship":"MITIGATION_DESIGN_NOT_CLOSURE"} for e in E for r in RISKS];req=[{"id":i,"requirement":text,"status":"DESIGNED_NOT_RUNTIME_PROVEN","evidence":E} for i,text in REQ]
 summary={"integration_migration_evidence_count":len(E),"requirement_contract_delta_count":len(req),"module_evidence_link_count":len(ml),"risk_evidence_link_count":len(rl),"unique_linked_risk_count":len(RISKS),"base_risk_count":d["risk"]["summary"]["risk_count"],"base_mapped_risk_assignment_count":d["trace"]["summary"]["mapped_risk_assignment_count"],"new_risk_count":0,"runtime_readiness_promotions":0};checks={"sources_pass":all(v["validation"]=="PASS" for v in d.values()),"five_ten":len(E)==5 and len(req)==10,"links":len(ml)==35 and len(rl)==45 and len(RISKS)==9,"risks_exist":set(RISKS)<=known,"scope":d["envelope"]["summary"]["command_contract_count"]==6 and d["golden"]["summary"]["combined_integration_acceptance_design_count"]==69 and d["playbook"]["summary"]["playbook_count"]==7,"base_stable":summary["base_risk_count"]==84 and summary["base_mapped_risk_assignment_count"]==343,"no_promotion":summary["new_risk_count"]==summary["runtime_readiness_promotions"]==0};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_integration_migration_traceability_delta_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","safety":{"mode":"OFFLINE_EVIDENCE_SYNTHESIS","database_connections":0,"network_reads_or_writes":0,"packages_or_transfers_executed":0,"commands_forms_reports_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"sensitive_values_or_payloads_persisted":0},"summary":summary,"policy":{"relationship":"ADDITIVE_EVIDENCE_DELTA_ONLY","base_registers_unchanged":True,"no_risk_closure_or_runtime_promotion":True},"evidence":E,"requirements":req,"module_links":ml,"risk_links":rl,"linked_existing_risks":RISKS,"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"confidence":{"design_trace":"HIGH","runtime_effect_parity":"UNPROVEN"},"limits":["Risk links do not close risks.","The 84-risk and 343-assignment base registers remain unchanged.","No runtime integration, migration or incident result is claimed."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(summary,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
