"""Apply the accounting evidence correction as an acyclic delta to the 14-module ledger."""
from __future__ import annotations
import argparse,copy,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S={"base":"artifacts/varanegar_analysis/varanegar_command_readiness_ledger_20260829.json","accounting":"artifacts/varanegar_analysis/varanegar_accounting_command_inventory_correction_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_accounting_command_inventory_correction_checkpoint_20260829.json"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};rows=copy.deepcopy(d["base"]["modules"]);acc=next(x for x in rows if x["module"]=="accounting");before=acc["truth_table_dimensions"]["outcome_retry_idempotency"]["target_contract"];acc["mapped_validated_evidence"].append({"key":"accounting_correction","path":S["accounting"],"validation":d["accounting"]["validation"]});acc["truth_table_dimensions"]["outcome_retry_idempotency"]["target_contract"]=d["accounting"]["summary"]["accounting_target_outcome_contract_present"];acc["legacy_open_blockers"].append("manual-voucher runtime branch, effect parity and a real reversal command remain unproven")
 design=sum(x["truth_table_dimensions"]["outcome_retry_idempotency"]["target_contract"] for x in rows);checks={"sources_pass":all(d[k]["validation"]=="PASS" for k in d),"fourteen_modules":len(rows)==14,"accounting_delta_false_to_true":before is False and acc["truth_table_dimensions"]["outcome_retry_idempotency"]["target_contract"] is True,"corrected_six_commands":d["accounting"]["summary"]["corrected_command_count"]==6,"design_contract_count_four":design==4,"runtime_still_zero":not any(x["truth_table_dimensions"]["outcome_retry_idempotency"]["runtime_proven"] for x in rows),"readiness_still_zero":not any(x["command_ready"] or x["pilot_ready"] for x in rows),"risk_stable":d["risk"]["summary"]["risk_count"]==84,"trace_stable":d["trace"]["summary"]["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_command_readiness_delta_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","safety":{"mode":"OFFLINE_ACYCLIC_EVIDENCE_DELTA","database_connections":0,"commands_forms_reports_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"sensitive_values_persisted":0},"summary":{"module_count":14,"changed_module_count":1,"outcome_target_contract_module_count_before":3,"outcome_target_contract_module_count_after":design,"accounting_corrected_command_count":6,"runtime_retry_idempotency_proven_module_count":0,"command_ready_module_count":0,"pilot_ready_module_count":0,"risk_count":84,"mapped_risk_assignment_count":343,"new_risk_count":0},"delta":{"module":"accounting","dimension":"outcome_retry_idempotency.target_contract","before":before,"after":True,"basis":S["accounting"],"runtime_readiness_effect":"NONE"},"modules":rows,"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"confidence":{"design_delta":"HIGH_STATIC","runtime_readiness":"UNPROVEN"},"limits":["This is an acyclic delta; the historical base ledger remains unchanged.","Design coverage does not imply command readiness.","No UAT, owner approval or operational command was executed."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
