"""Build review packets for the five residual same-action case gaps."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
S={"queue":"artifacts/varanegar_analysis/varanegar_unmatched_golden_case_alias_work_queue_20260829.json","core":"artifacts/varanegar_analysis/ui/varanegar_golden_command_cases_20260827.json","distribution":"artifacts/varanegar_analysis/varanegar_distribution_golden_uat_cases_20260829.json","treasury":"artifacts/varanegar_analysis/varanegar_treasury_golden_uat_cases_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_unmatched_golden_case_alias_work_queue_checkpoint_20260829.json"}
SPECS=[
 {"queue_id":"UGA-029","case_id":"DS-G-01-NUMBER_HISTORY_FORK","priority":4,"candidate":"RECONCILIATION_SPECIALIZATION_CANDIDATE","refs":["distribution.create_or_update.number_race","distribution.create_or_update.valid_create"],"roles":["DISTRIBUTION_DOMAIN_OWNER_ROLE","NUMBERING_POLICY_OWNER_ROLE"]},
 {"queue_id":"UGA-030","case_id":"DS-G-02-LATE_CARDEX_CHECK","priority":1,"candidate":"LATE_FAILURE_STAGE_SPECIALIZATION_CANDIDATE","refs":["distribution.issue_exit.fault_after_first_write","distribution.issue_exit.negative_cardex","distribution.issue_exit.batch_mismatch"],"roles":["DISTRIBUTION_TRANSACTION_OWNER_ROLE","INVENTORY_CARDEX_OWNER_ROLE"]},
 {"queue_id":"UGA-031","case_id":"DS-G-03-MERGE_OWNER_UNKNOWN","priority":2,"candidate":"AMBIGUOUS_DURABLE_OUTCOME_SPECIALIZATION_CANDIDATE","refs":["distribution.merge_or_adjust_exit.fault_after_first_write","distribution.merge_or_adjust_exit.valid_merge"],"roles":["DISTRIBUTION_TRANSACTION_OWNER_ROLE","RECOVERY_POLICY_OWNER_ROLE"]},
 {"queue_id":"UGA-032","case_id":"DS-G-04-PARTIAL_GRAPH_CLEANUP","priority":3,"candidate":"MULTI_STAGE_REVERSAL_FAILURE_SPECIALIZATION_CANDIDATE","refs":["distribution.remove_exit.fault_after_first_write","distribution.remove_exit.partial_exit_set","distribution.remove_exit.valid_reverse"],"roles":["DISTRIBUTION_TRANSACTION_OWNER_ROLE","INVENTORY_VOUCHER_OWNER_ROLE"]},
 {"queue_id":"UGA-054","case_id":"TR-G-04-UNDO_HISTORY_BRANCH","priority":5,"candidate":"UNDO_WORKFLOW_BRANCH_SPECIALIZATION_CANDIDATE","refs":["received_cheque.undo.not_latest","received_cheque.undo.transfer_dependency","received_cheque.undo.latest_leaf"],"roles":["TREASURY_DOMAIN_OWNER_ROLE","CHEQUE_HISTORY_POLICY_OWNER_ROLE"]},
]
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};queue={x["queue_id"]:x for x in d["queue"]["work_queue"]};base={x["case_id"]:x for x in d["core"]["cases"]};new={x["case_id"]:x for x in d["distribution"]["cases"]+d["treasury"]["cases"]};packets=[]
 for spec in SPECS:
  qrow=queue[spec["queue_id"]];n=new[spec["case_id"]];refs=[base[x] for x in spec["refs"]];same_kind_count=sum(x["command"].casefold()==n["command"].casefold() and x["kind"].casefold()==n["case_kind"].casefold() for x in d["core"]["cases"])
  packets.append({"packet_id":f"KMG-{spec['priority']:02d}","priority":spec["priority"],"queue_id":spec["queue_id"],"module":qrow["module"],"newer_case_id":n["case_id"],"action":n["command"],"newer_kind":n["case_kind"],"baseline_same_action_kind_case_count":same_kind_count,"gap_type":"SAME_KIND_MULTIPLICITY_GAP" if same_kind_count else "KIND_ABSENT_FROM_SAME_ACTION_BASELINE","candidate_disposition":spec["candidate"],"nearest_baseline_case_ids":spec["refs"],"nearest_baseline_expected_outcomes":[x["expected_outcome"] for x in refs],"newer_expected_outcome":n["expected_outcome"],"exact_expected_outcome_match_count":sum(x["expected_outcome"].casefold()==n["expected_outcome"].casefold() for x in refs),"exact_assertion_list_match_count":sum(x["assertions"]==n["assertions"] for x in refs),"accountable_role_types":spec["roles"],"required_disposition_evidence":["explicit comparison of setup/precondition and failure stage","versioned legacy-to-target outcome vocabulary mapping","assertion and durable-effect equivalence matrix","decision among EXACT_NEW, SEMANTIC_REPLACEMENT, EXACT_REUSE or UNRESOLVED","accountable role rationale, policy version and expiry"],"current_disposition":"UNRESOLVED","accepted_semantic_disposition":False,"counting_effect":"ZERO"})
 packets.sort(key=lambda x:x["priority"]);summary={"packet_count":len(packets),"distribution_packet_count":sum(x["module"]=="distribution" for x in packets),"treasury_packet_count":sum(x["module"]=="receivables_treasury" for x in packets),"kind_absent_packet_count":sum(x["gap_type"]=="KIND_ABSENT_FROM_SAME_ACTION_BASELINE" for x in packets),"same_kind_multiplicity_packet_count":sum(x["gap_type"]=="SAME_KIND_MULTIPLICITY_GAP" for x in packets),"nearest_baseline_reference_count":sum(len(x["nearest_baseline_case_ids"]) for x in packets),"exact_expected_outcome_match_count":sum(x["exact_expected_outcome_match_count"] for x in packets),"exact_assertion_list_match_count":sum(x["exact_assertion_list_match_count"] for x in packets),"external_owner_disposition_required_count":5,"accepted_semantic_disposition_count":0,"exact_non_duplicated_additive_count":0,"design_lower_bound_before_disposition":d["queue"]["summary"]["design_lower_bound_after_queue"],"design_lower_bound_after_disposition":d["queue"]["summary"]["design_lower_bound_after_queue"],"executed_case_count":0,"owner_approved_case_count":0,"command_ready_module_count":0,"pilot_ready_module_count":0,"risk_count":d["risk"]["summary"]["risk_count"],"mapped_risk_assignment_count":d["trace"]["summary"]["mapped_risk_assignment_count"],"new_risk_count":0}
 checks={"validated_sources_pass":all(d[k].get("validation")=="PASS" for k in d if k!="core"),"legacy_core_pinned":d["core"].get("validation") is None and d["core"]["summary"]["case_count"]==77,"five_packets_4_1":summary["packet_count"]==5 and summary["distribution_packet_count"]==4 and summary["treasury_packet_count"]==1,"gap_split_3_2":summary["kind_absent_packet_count"]==3 and summary["same_kind_multiplicity_packet_count"]==2,"thirteen_references":summary["nearest_baseline_reference_count"]==13,"no_exact_contract_match":summary["exact_expected_outcome_match_count"]==summary["exact_assertion_list_match_count"]==0,"all_unresolved":all(x["current_disposition"]=="UNRESOLVED" and not x["accepted_semantic_disposition"] and x["counting_effect"]=="ZERO" for x in packets),"non_additive_1404":summary["exact_non_duplicated_additive_count"]==0 and summary["design_lower_bound_before_disposition"]==summary["design_lower_bound_after_disposition"]==1404,"execution_readiness_zero":summary["executed_case_count"]==summary["owner_approved_case_count"]==summary["command_ready_module_count"]==summary["pilot_ready_module_count"]==0,"base_stable":summary["risk_count"]==84 and summary["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_five_case_kind_multiplicity_disposition_packets_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","scope":{"mode":"OFFLINE_REVIEW_ONLY_KIND_AND_MULTIPLICITY_DISPOSITION","continuation_complete":False},"safety":{"database_connections":0,"golden_uat_or_operational_execution":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"write_access_created":0,"raw_business_values_identity_or_credentials_persisted":0},"summary":summary,"disposition_packets":packets,"priority_policy":"ambiguous/late durable-effect failures before numbering/reconciliation and workflow specializations","checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":p.stat().st_size,"sha256":sha(p)} for k,p in sorted(paths.items())]+[{"name":"builder","path":"scripts/windows/build_varanegar_five_case_kind_multiplicity_disposition_packets_20260829.py","size_bytes":Path(__file__).stat().st_size,"sha256":sha(Path(__file__))}],"limits":["Candidate disposition labels are review hypotheses, not accepted classifications.","All five packets require accountable external disposition.","No case was executed and no count or readiness state was promoted."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(summary,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
