"""Chain the migration cutover snapshot/delta reconciliation contract."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
S={"contract":"artifacts/varanegar_analysis/varanegar_target_erp_migration_cutover_snapshot_delta_reconciliation_contract_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_target_erp_evidence_redaction_synthetic_reference_validator_checkpoint_20260829.json","builder":"scripts/windows/build_varanegar_target_erp_migration_cutover_snapshot_delta_reconciliation_contract_20260829.py","checkpoint_builder":"scripts/windows/build_varanegar_target_erp_migration_cutover_snapshot_delta_reconciliation_checkpoint_20260829.py","test":"tests/test_varanegar_target_erp_migration_cutover_snapshot_delta_reconciliation_contract.py","checkpoint_test":"tests/test_varanegar_target_erp_migration_cutover_snapshot_delta_reconciliation_checkpoint.py","doc":"docs/varanegar_reconstruction/TARGET_ERP_MIGRATION_CUTOVER_SNAPSHOT_DELTA_RECONCILIATION_20260829_FA.md"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 p=argparse.ArgumentParser();p.add_argument("--output",required=True,type=Path);a=p.parse_args();paths={k:ROOT/v for k,v in S.items()};c=load(paths["contract"]);prev=load(paths["previous"]);s=c["summary"];checks={"sources_pass":c["validation"]==prev["validation"]=="PASS","coverage_14_168_168_252_84":(s["module_count"],s["module_phase_assignment_count"],s["module_reconciliation_assignment_count"],s["module_gate_assignment_count"],s["module_role_assignment_count"])==(14,168,168,252,84),"snapshot_delta_reconcile_cutover_readiness_zero":s["authorized_snapshot_capture_count"]==s["snapshot_captured_or_read_count"]==s["delta_batch_captured_or_applied_count"]==s["module_reconciliation_run_count"]==s["blocking_unknown_zero_proven_module_count"]==s["cutover_accepted_module_count"]==s["target_write_enabled_module_count"]==s["command_ready_module_count"]==s["pilot_ready_module_count"]==0,"base_stable":s["risk_count"]==84 and s["mapped_risk_assignment_count"]==343 and s["design_lower_bound_after_cutover_contract"]==1404,"safety_zero":set(c["safety"].values())=={0}};failed=sorted(k for k,v in checks.items() if not v);out={"artifact":"varanegar_target_erp_migration_cutover_snapshot_delta_reconciliation_checkpoint_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","previous_checkpoint":{"path":S["previous"],"sha256":sha(paths["previous"])},"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"safety":{"database_connections":0,"network_reads_or_writes":0,"snapshots_deltas_imports_reconciliations_fences_or_cutovers_executed":0,"operational_forms_reports_queries_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"credentials_endpoints_pii_or_raw_business_values_read_or_persisted":0}};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
