"""Build evidence-first Master Data incident playbooks."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S={"envelope":"artifacts/varanegar_analysis/varanegar_master_data_outcome_envelope_20260829.json","golden":"artifacts/varanegar_analysis/varanegar_master_data_golden_uat_cases_20260829.json","path":"artifacts/varanegar_analysis/ui/varanegar_distribution_path_diagnostic_contract_20260827.json","customer_goods":"artifacts/varanegar_analysis/ui/varanegar_customer_goods_command_contracts_20260827.json","supplier":"artifacts/varanegar_analysis/ui/varanegar_supplier_master_command_contract_20260827.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_master_data_golden_uat_checkpoint_20260829.json"}
COMMON=["capture incident time, command/receipt, master type/version and opaque aggregate/candidate/child/crosswalk hashes without PII, barcode, contact or raw master values","verify artifact, schema, privacy, duplicate and crosswalk policy hashes and stop on drift","read immutable aggregate, child-set, quarantine/crosswalk/merge, audit and outbox receipts","recompute candidate evidence and namespace/mode decisions; never infer identity from weak similarity","classify NATURAL_BEHAVIOR, DATA_DEBT, BUG or UNPROVEN","quarantine ambiguous, sentinel, cross-namespace, partial-child or incomplete-merge outcomes before retry","stop before save, delete, merge, crosswalk approval, redirect rewrite, reindex or reference repair","design isolated synthetic-master and fault-injection reproduction when the boundary remains unproven"]
BASE=[
 ("MD-PB-01","two master records share one or more weak duplicate indicators","duplicate candidate evidence","compare only normalized hashes and provenance; similarity creates quarantine, never automatic merge",["R-004","R-010","R-037"]),
 ("MD-PB-02","sentinel, placeholder or malformed key is treated as a real identifier","sentinel quarantine","preserve source value class and namespace status; never map sentinel to a target identity",["R-002","R-010","R-037"]),
 ("MD-PB-03","distribution path code appears orphaned or maps to a wrong route","mode-dependent crosswalk","pin source mode and exact code; manual integer code is not a legacy route-master foreign key",["R-002","R-011","R-037"]),
 ("MD-PB-04","master header commits but child barcode/package/contact/account relations are partial","structured child-set atomicity","compare child-set hashes and receipts; incomplete aggregate is UNKNOWN_REQUIRES_READBACK",["R-006","R-007","R-037"]),
 ("MD-PB-05","supplier is flattened into a generic party and loses payment/accounting/cardex semantics","typed supplier role","verify supplier-role version and dependency receipts; never repair by copying generic party fields",["R-005","R-007","R-038"]),
 ("MD-PB-06","merge redirects some references but not others or cannot be reversed","reversible merge receipt","reconcile every reference class and reversal edge before retry; do not delete source identity history",["R-006","R-008","R-010"]),
 ("MD-PB-07","PII appears in search, audit, outbox or role boundaries collapse","privacy and party-role separation","use opaque hashes and typed roles; stop and classify any raw identity exposure without reproducing it",["R-004","R-037","R-038"]),
]
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};play=[{"id":i,"incident":inc,"focus":focus,"steps":COMMON+[extra],"stop_conditions":["evidence/schema/privacy/policy hash drift","save, delete, merge, approval, redirect or reference repair required","master-data steward decision required","PII, barcode, contact or raw master value would be read or persisted"],"risks":risks,"runtime_diagnosis":"NOT_PERFORMED"} for i,inc,focus,extra,risks in BASE];known={x["id"] for x in d["risk"]["risks"]};summary={"playbook_count":len(play),"minimum_step_count":min(len(x["steps"]) for x in play),"command_contract_count":d["envelope"]["summary"]["command_contract_count"],"combined_acceptance_design_count":d["golden"]["summary"]["combined_master_data_acceptance_design_count"],"mode_dependent_distribution_code_count":d["path"]["summary"]["distribution_count"],"legacy_master_command_method_count":d["customer_goods"]["summary"]["selected_method_count"]+d["supplier"]["summary"]["selected_method_count"],"runtime_incidents_diagnosed_count":0,"saves_deletes_merges_crosswalks_or_repairs_performed_count":0,"owner_approved_count":0,"pii_or_raw_master_values_persisted_count":0,"risk_count":84,"mapped_risk_assignment_count":343,"new_risk_count":0};checks={"sources_pass":all(v["validation"]=="PASS" for v in d.values()),"seven_playbooks":len(play)==7,"nine_steps":all(len(x["steps"])==9 for x in play),"four_way":all("NATURAL_BEHAVIOR, DATA_DEBT, BUG or UNPROVEN" in x["steps"][4] for x in play),"risks_exist":all(r in known for x in play for r in x["risks"]),"scope":summary["command_contract_count"]==10 and summary["combined_acceptance_design_count"]==149 and summary["mode_dependent_distribution_code_count"]==26086 and summary["legacy_master_command_method_count"]==40,"quarantine_crosswalk_merge_privacy":any("quarantine" in x["focus"] for x in play) and any("crosswalk" in x["focus"] for x in play) and any("merge" in x["focus"] for x in play) and any("privacy" in x["focus"] for x in play),"runtime_zero":summary["runtime_incidents_diagnosed_count"]==summary["saves_deletes_merges_crosswalks_or_repairs_performed_count"]==summary["owner_approved_count"]==summary["pii_or_raw_master_values_persisted_count"]==0,"base_stable":d["risk"]["summary"]["risk_count"]==84 and d["trace"]["summary"]["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_master_data_expert_playbook_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","safety":{"mode":"OFFLINE_EVIDENCE_SYNTHESIS","database_connections":0,"network_reads_or_writes":0,"master_data_commands_or_forms_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"pii_barcode_contact_or_raw_master_values_read_or_persisted":0},"summary":summary,"playbooks":play,"diagnostic_result_contract":{"allowed":["NATURAL_BEHAVIOR","DATA_DEBT","BUG","UNPROVEN"],"requires_named_incident_evidence":True,"save_delete_merge_crosswalk_or_repair_is_separate_authorized_work":True},"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"confidence":{"structure":"HIGH","incident_diagnosis":"REQUIRES_INCIDENT_EVIDENCE"},"limits":["No named incident was diagnosed.","No save, delete, merge, crosswalk, redirect or repair was performed.","No PII, barcode, contact or current master identity is claimed."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(summary,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
