"""Execute deterministic synthetic approval-governance vectors."""
from __future__ import annotations
import argparse,copy,hashlib,importlib.util,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];REFERENCE=ROOT/"scripts/windows/varanegar_approval_reference.py"
S={"approval_contract":"artifacts/varanegar_analysis/varanegar_target_erp_approval_delegation_escalation_sod_breakglass_contract_20260829.json","approval_checkpoint":"artifacts/varanegar_analysis/varanegar_target_erp_approval_delegation_escalation_sod_breakglass_checkpoint_20260829.json","authorization":"artifacts/varanegar_analysis/varanegar_target_erp_command_authorization_scope_decision_trace_contract_20260829.json","configuration":"artifacts/varanegar_analysis/varanegar_target_erp_configuration_policy_immutability_change_audit_contract_20260829.json","concurrency":"artifacts/varanegar_analysis/varanegar_target_erp_optimistic_concurrency_version_fencing_contract_20260829.json","tests":"artifacts/varanegar_analysis/varanegar_25h_final_test_result_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def module():s=importlib.util.spec_from_file_location("app_ref",REFERENCE);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return m
def main():
 p=argparse.ArgumentParser();p.add_argument("--output",required=True,type=Path);a=p.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};m=module();base=m.baseline()
 def changed(**kw):e=copy.deepcopy(base);e.update(kw);return e
 positive=[("POS-APPROVE",base,"APPROVAL_GRANTED_QUORUM_SEQUENCE_AND_SOD_MET"),("POS-REJECT",changed(action="REJECT"),"APPROVAL_REJECTED_REASON_AND_LINEAGE_RETAINED"),("POS-DELEGATE",changed(action="DELEGATE",delegation_used=True),"DELEGATION_ACCEPTED_BOUNDED_CURRENT_AND_ACCEPTED"),("POS-ESCALATE",changed(action="ESCALATE",timeout_reached=True),"ESCALATION_REQUIRED_TIMEOUT_WITHOUT_AUTO_DECISION"),("POS-BREAKGLASS",changed(action="BREAK_GLASS",break_glass=True),"BREAK_GLASS_ACCEPTED_INCIDENT_SCOPED_EXPIRING_AND_REVIEWABLE"),("POS-EXECUTE",changed(action="EXECUTE"),"EXECUTION_TOKEN_ACCEPTED_SINGLE_USE_SCOPED_AND_FENCED")]
 negative=[("NEG-EXTRA",dict(base,extra=True),"SCHEMA_INVALID"),("NEG-FINGERPRINT",changed(request_fingerprint_current=False),"APPROVAL_REJECTED_POLICY_SCOPE_THRESHOLD_OR_VERSION"),("NEG-POLICY",changed(policy_current=False),"APPROVAL_REJECTED_POLICY_SCOPE_THRESHOLD_OR_VERSION"),("NEG-THRESHOLD",changed(threshold_current=False),"APPROVAL_REJECTED_POLICY_SCOPE_THRESHOLD_OR_VERSION"),("NEG-QUAL",changed(approver_qualified=False),"APPROVAL_REJECTED_QUALIFICATION_SOD_OR_CONFLICT"),("NEG-SOD",changed(sod_separated=False),"APPROVAL_REJECTED_QUALIFICATION_SOD_OR_CONFLICT"),("NEG-CONFLICT",changed(conflict_clear=False),"APPROVAL_REJECTED_QUALIFICATION_SOD_OR_CONFLICT"),("NEG-DELEGATE-SCOPE",changed(action="DELEGATE",delegation_used=True,delegation_scope_current=False),"DELEGATION_REJECTED_SCOPE_LIMIT_EXPIRY_REVOCATION_OR_QUALIFICATION"),("NEG-DELEGATE-ACCEPT",changed(action="DELEGATE",delegation_used=True,delegation_accepted=False),"DELEGATION_REJECTED_SCOPE_LIMIT_EXPIRY_REVOCATION_OR_QUALIFICATION"),("NEG-DELEGATE-EXPIRE",changed(action="DELEGATE",delegation_used=True,delegation_expiry_current=False),"DELEGATION_REJECTED_SCOPE_LIMIT_EXPIRY_REVOCATION_OR_QUALIFICATION"),("NEG-DELEGATE-REVOKE",changed(action="DELEGATE",delegation_used=True,delegation_not_revoked=False),"DELEGATION_REJECTED_SCOPE_LIMIT_EXPIRY_REVOCATION_OR_QUALIFICATION"),("NEG-SUBDELEGATE",changed(action="DELEGATE",delegation_used=True,subdelegation_current=False),"DELEGATION_REJECTED_SCOPE_LIMIT_EXPIRY_REVOCATION_OR_QUALIFICATION"),("NEG-AUTO",changed(action="ESCALATE",timeout_reached=True,auto_decision_attempted=True),"ESCALATION_REJECTED_AUTO_DECISION"),("NEG-ESCALATE-TIME",changed(action="ESCALATE",timeout_reached=False),"ESCALATION_REJECTED_TIMEOUT_OR_ROUTE"),("NEG-ESCALATE-ROUTE",changed(action="ESCALATE",timeout_reached=True,escalation_route_current=False),"ESCALATION_REJECTED_TIMEOUT_OR_ROUTE"),("NEG-BREAK-INCIDENT",changed(action="BREAK_GLASS",break_glass=True,incident_current=False),"BREAK_GLASS_REJECTED_JUSTIFICATION_SCOPE_LIMIT_OR_REVIEW"),("NEG-BREAK-LIMIT",changed(action="BREAK_GLASS",break_glass=True,limit_expiry_current=False),"BREAK_GLASS_REJECTED_JUSTIFICATION_SCOPE_LIMIT_OR_REVIEW"),("NEG-BREAK-REVIEW",changed(action="BREAK_GLASS",break_glass=True,post_review_current=False),"BREAK_GLASS_REJECTED_JUSTIFICATION_SCOPE_LIMIT_OR_REVIEW"),("NEG-TOKEN",changed(action="EXECUTE",token_current_single_use_scoped_fenced=False),"EXECUTION_REJECTED_TOKEN_EFFECT_OR_RECONCILIATION"),("NEG-EFFECT",changed(action="EXECUTE",effect_reconciled=False),"EXECUTION_REJECTED_TOKEN_EFFECT_OR_RECONCILIATION"),("NEG-QUORUM",changed(quorum_met=False),"APPROVAL_REJECTED_QUORUM_OR_SEQUENCE"),("NEG-SEQUENCE",changed(sequence_current=False),"APPROVAL_REJECTED_QUORUM_OR_SEQUENCE"),("NEG-UNKNOWN",changed(blocking_unknown=True),"MANUAL_REVIEW_REQUIRED_BLOCKING_UNKNOWN")]
 def run(vs):
  r=[]
  for i,e,x in vs:
   y=m.evaluate(e);r.append({"vector_id":i,"expected":x,"actual":y,"status":"PASS" if y==x else "FAIL"})
  return r
 pr=run(positive);nr=run(negative);allr=pr+nr;official=d["tests"];cs=d["approval_contract"]["summary"]
 s={"reference_evaluator_implementation_count":1,"positive_vector_count":len(pr),"positive_pass_count":sum(x["status"]=="PASS" for x in pr),"negative_vector_count":len(nr),"negative_pass_count":sum(x["status"]=="PASS" for x in nr),"total_vector_count":len(allr),"total_pass_count":sum(x["status"]=="PASS" for x in allr),"distinct_typed_outcome_count":len({x["actual"] for x in allr}),"approval_gate_count":cs["gate_count"],"approval_module_gate_assignment_count":cs["module_gate_assignment_count"],"operational_approval_workflow_or_token_implementation_count":0,"operational_user_role_request_decision_delegation_or_effect_read_count":0,"approve_delegate_escalate_breakglass_or_execute_run_count":0,"accepted_operational_receipt_count":0,"command_ready_module_count":0,"pilot_ready_module_count":0,"design_lower_bound_before_reference_evaluator":1404,"design_lower_bound_after_reference_evaluator":1404,"official_test_file_count":official["runner"]["test_file_count"],"official_passed_test_count":official["runner"]["passed_test_count"],"risk_count":d["risk"]["summary"]["risk_count"],"mapped_risk_assignment_count":d["trace"]["summary"]["mapped_risk_assignment_count"],"new_risk_count":0}
 checks={"sources_pass":all(d[k].get("validation")=="PASS" for k in ("approval_contract","approval_checkpoint","authorization","configuration","concurrency","tests")),"positive_6_of_6":s["positive_vector_count"]==s["positive_pass_count"]==6,"negative_23_of_23":s["negative_vector_count"]==s["negative_pass_count"]==23,"total_29_of_29":s["total_vector_count"]==s["total_pass_count"]==29,"distinct_outcomes_at_least_14":s["distinct_typed_outcome_count"]>=14,"coverage_24_336":(s["approval_gate_count"],s["approval_module_gate_assignment_count"])==(24,336),"operational_and_readiness_zero":all(s[k]==0 for k in ("operational_approval_workflow_or_token_implementation_count","operational_user_role_request_decision_delegation_or_effect_read_count","approve_delegate_escalate_breakglass_or_execute_run_count","accepted_operational_receipt_count","command_ready_module_count","pilot_ready_module_count")),"non_additive_1404":s["design_lower_bound_before_reference_evaluator"]==s["design_lower_bound_after_reference_evaluator"]==1404,"official_tests_pass":official["validation"]=="PASS" and official["runner"]["bootstrap_excluded_test_file_count"]==0,"base_stable":s["risk_count"]==84 and s["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_target_erp_approval_synthetic_reference_evaluator_contract_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","scope":{"mode":"pure_synthetic_approval_delegation_escalation_sod_breakglass_reference_evaluator","continuation_complete":False,"operational_user_role_request_decision_delegation_token_or_effect_read":False},"safety":{"database_connections":0,"network_reads_or_writes":0,"operational_user_role_approval_request_decision_delegation_or_effect_reads":0,"approval_reject_delegate_escalate_breakglass_or_execute_actions_executed":0,"operational_forms_reports_queries_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"credentials_tokens_pii_or_raw_business_values_read_or_persisted":0},"summary":s,"positive_results":pr,"negative_results":nr,"outcome_precedence":["SCHEMA","REQUEST_POLICY_THRESHOLD","QUALIFICATION_SOD_CONFLICT","DELEGATION_SCOPE_ACCEPTANCE_EXPIRY_REVOCATION","NO_AUTO_DECISION","BLOCKING_UNKNOWN","ESCALATION","BREAK_GLASS","EXECUTION_TOKEN_EFFECT","QUORUM_SEQUENCE","ACCEPTED"],"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())]+[{"name":"reference_evaluator","path":REFERENCE.relative_to(ROOT).as_posix(),"size_bytes":REFERENCE.stat().st_size,"sha256":sha(REFERENCE)},{"name":"builder","path":"scripts/windows/build_varanegar_target_erp_approval_synthetic_reference_evaluator_contract_20260829.py","size_bytes":Path(__file__).stat().st_size,"sha256":sha(Path(__file__))}],"limits":["Only fixed synthetic booleans and action labels were evaluated.","The evaluator is not an identity approval notification workflow token or execution provider.","Operational approval delegation escalation break glass execution and readiness remain blocked pending isolated receipts and owner approval."]}
 a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(s,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
