"""Build identity/authorization command, decision and session outcome contracts."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path

ROOT=Path(__file__).resolve().parents[2]
S={
 "gap":"artifacts/varanegar_analysis/ui/varanegar_identity_access_navigation_gap_contract_20260827.json",
 "role_uat":"artifacts/varanegar_analysis/ui/negin_erp_role_uat_cases_20260827.json",
 "sod":"artifacts/varanegar_analysis/ui/negin_erp_role_sod_contract_20260827.json",
 "endpoint":"artifacts/varanegar_analysis/domains/ngt_authorization_endpoint_coverage_20260828.json",
 "effective":"artifacts/varanegar_analysis/domains/ngt_authorization_effective_boundary_20260828.json",
 "manual":"artifacts/varanegar_analysis/domains/ngt_authorization_manual_guard_boundary_20260829.json",
 "short_circuit":"artifacts/varanegar_analysis/domains/ngt_authorization_role_short_circuit_20260829.json",
 "owner":"artifacts/varanegar_analysis/domains/ngt_owner_scope_effective_boundary_20260829.json",
 "order_runtime":"artifacts/varanegar_analysis/domains/order_sale_authorization_runtime_20260829.json",
 "risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json",
 "trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json",
 "previous":"artifacts/varanegar_analysis/varanegar_configuration_traceability_delta_checkpoint_20260829.json",
}
REQUEST=["command_id","payload_hash","correlation_id","policy_version","principal_reference_hash","expected_assignment_version","capability","action_scope","data_scope","owner_scope","reason_code","expiry","approval_receipt_hash"]
RESPONSE=["outcome_code","command_id","assignment_version","decision_receipt_id","decision_trace_hash","audit_event_id","outbox_event_id","session_epoch","revocation_receipt_id","retryable","readback_required"]
OUTCOMES=["REJECTED_NO_EFFECT","COMMITTED_ACTIVE","COMMITTED_PENDING_APPROVAL","REVOKED_AND_INVALIDATED","QUARANTINED_SCOPE_MISMATCH","EXPIRED_NO_EFFECT","UNKNOWN_REQUIRES_READBACK"]
CONTRACTS=[
 ("identity.publish_role_policy_version","role_policy","owner-approved immutable capability/deny/SoD policy; aggregate legacy rights never become grants"),
 ("identity.assign_principal_capabilities","principal_assignment","deny-first direct assignment with no self-grant and independent approval for privileged capability"),
 ("identity.assign_group_membership","group_membership","group expansion cannot override explicit deny and must remain inside the same application/owner boundary"),
 ("identity.assign_data_scope","data_scope_assignment","action capability and data scope are separate; repository lookup is owner-filtered"),
 ("identity.revoke_grant_and_sessions","revocation","revoke assignment and advance session epoch atomically; stale tokens fail closed"),
 ("identity.issue_break_glass_grant","break_glass","time-bounded, reasoned, independently approved, non-renewing and fully audited"),
]
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()}
 commands=[{"command":c,"owner":"identity_authorization","aggregate":agg,"special_rule":rule,"request_fields":REQUEST,"response_fields":RESPONSE,"allowed_outcomes":OUTCOMES,"authorization":"authenticated application service re-evaluates policy, capability, owner and data scope deny-first","idempotency":"same CommandId and PayloadHash returns the original assignment/decision receipt; conflicting hash rejects","transaction_owner":"one application service owns assignment/revocation, audit, outbox and session epoch atomically","retry_rule":"read assignment version, policy version, audit, outbox and session epoch before retry","identity_data_policy":"only opaque principal reference hashes; no name, identifier, membership row, credential or permission value","runtime_effect_parity":"UNPROVEN","status":"TARGET_DESIGN_ONLY_NOT_IMPLEMENTED"} for c,agg,rule in CONTRACTS]
 es=d["effective"]["summary"];ep=d["endpoint"]["summary"];ow=d["owner"]["summary"];gap=d["gap"]["summary"]
 summary={"command_contract_count":len(commands),"request_field_count":len(REQUEST),"response_field_count":len(RESPONSE),"outcome_code_count":len(OUTCOMES),"existing_reused_uat_case_count":d["role_uat"]["summary"]["synthetic_uat_case_count"],"role_template_count":d["role_uat"]["summary"]["role_template_count"],"sod_rule_count":d["role_uat"]["summary"]["sod_case_count"],"authorization_node_count":ep["attribute_declared_endpoint_count"],"endpoint_without_declared_authorization_count":ep["endpoint_with_no_ngt_standard_claims_or_anonymous_declaration_count"],"mutating_endpoint_without_declared_authorization_count":ep["mutating_endpoint_with_no_ngt_standard_claims_or_anonymous_declaration_count"],"endpoint_with_named_manual_decision_count":d["manual"]["summary"]["endpoint_with_manual_authorization_decision_candidate_count"],"admin_role_short_circuit_present":d["short_circuit"]["summary"]["admin_role_short_circuits_base_authorization"],"admin_role_current_assignment_subject_count":es["admin_role_current_assignment_subject_count"],"scope_consistency_mismatch_count":ow["scope_consistency_mismatch_count"],"authorization_repository_owner_filtered":ow["authorization_permission_repository_path_is_owner_filtered"],"identity_access_route_candidate_count":gap["identity_access_route_candidate_count"],"effective_user_or_group_grant_proven_count":gap["effective_user_or_group_grant_proven_count"],"owner_approved_case_count":0,"production_assignment_count":0,"implemented_command_count":0,"runtime_effect_parity_proven_count":0,"command_ready_module_count":0,"pilot_ready_module_count":0,"risk_count":84,"mapped_risk_assignment_count":343,"new_risk_count":0}
 checks={"validated_sources_pass":all(d[k]["validation"]=="PASS" for k in ["gap","role_uat","owner","order_runtime","risk","trace","previous"]),"provisional_sod_only":d["sod"]["status"]=="PROVISIONAL_TEMPLATES_REQUIRE_BUSINESS_OWNER_SIGNOFF","six_commands":len(commands)==6 and len({x["command"] for x in commands})==6,"envelope_complete":len(REQUEST)==13 and len(RESPONSE)==11 and len(OUTCOMES)==7,"reuse_184":summary["existing_reused_uat_case_count"]==184 and summary["role_template_count"]==15 and summary["sod_rule_count"]==10,"endpoint_gap":summary["authorization_node_count"]==784 and summary["endpoint_without_declared_authorization_count"]==60 and summary["mutating_endpoint_without_declared_authorization_count"]==38 and summary["endpoint_with_named_manual_decision_count"]==0,"admin_gap":summary["admin_role_short_circuit_present"] is True and summary["admin_role_current_assignment_subject_count"]==3,"scope_gap":summary["scope_consistency_mismatch_count"]==58 and summary["authorization_repository_owner_filtered"] is False,"no_false_grant_proof":summary["effective_user_or_group_grant_proven_count"]==0,"privacy_contract":all("opaque principal reference hashes" in x["identity_data_policy"] for x in commands),"runtime_zero":summary["owner_approved_case_count"]==summary["production_assignment_count"]==summary["implemented_command_count"]==summary["runtime_effect_parity_proven_count"]==summary["command_ready_module_count"]==summary["pilot_ready_module_count"]==0,"base_stable":d["risk"]["summary"]["risk_count"]==84 and d["trace"]["summary"]["mapped_risk_assignment_count"]==343}
 failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_identity_authorization_outcome_envelope_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","safety":{"mode":"OFFLINE_STATIC_AND_CONTRACT_SYNTHESIS","database_connections":0,"network_reads_or_writes":0,"identity_or_authorization_commands_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"identity_values_credentials_or_raw_grants_read_or_persisted":0},"summary":summary,"decision_contract":{"ordered_checks":["authenticated fresh session","explicit deny and policy status","application and owner boundary","action capability","data scope","SoD and self-grant exclusion","expiry and break-glass approval"],"deny_precedence":"explicit deny wins over direct, group, admin or inherited allow","required_trace":["policy version","opaque principal hash","capability","owner/data scope hashes","allow/deny source hashes","decision and reason","session epoch"]},"commands":commands,"checks":checks,"failed_checks":failed,"risk_links":["R-002","R-003","R-004","R-006","R-007","R-024","R-057","R-058","R-059"],"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"confidence":{"static_authorization_and_scope_boundaries":"HIGH","target_contract_design":"HIGH","effective_runtime_grants_and_revocation_parity":"UNPROVEN"},"limits":["No identity, authorization, role, scope, revocation or session command was executed.","No names, identifiers, credentials, membership rows or raw permission values are persisted.","Current effective grants and authenticated runtime parity require owner-approved isolated UAT."]}
 a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(summary,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
