"""Build a non-duplicating integration/migration Golden/UAT delta."""
from __future__ import annotations
import argparse,collections,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S={"envelope":"artifacts/varanegar_analysis/varanegar_integration_migration_outcome_envelope_20260829.json","readiness":"artifacts/varanegar_analysis/varanegar_integration_migration_readiness_delta_20260829.json","extension":"artifacts/varanegar_analysis/ui/varanegar_extension_golden_cases_20260827.json","treasury":"artifacts/varanegar_analysis/varanegar_treasury_golden_uat_cases_20260829.json","pricing":"artifacts/varanegar_analysis/varanegar_pricing_rule_golden_uat_cases_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_integration_migration_readiness_checkpoint_20260829.json"}
F={"IM-PKG":("integration.package.authenticate_and_scope","package authentication and pre-execution scope"),"IM-ORD":("integration.package.order_and_acknowledge","sequence, gap and idempotent receipt"),"IM-SALE":("integration.ngt_sale.apply_and_write_crosswalk","multi-history, target and crosswalk reconciliation"),"IM-COMP":("integration.ngt_receipt.compensate","append-only compensation and repeated rollback safety"),"IM-MIG":("integration.migration.import_ordered_slice","snapshot consistency, ordered slices and rerun determinism")}
CASES=[("AUTH_OR_SCOPE_DENIED","authorization","REJECTED_NO_EFFECT"),("HASH_OR_SEQUENCE_INVALID","validation","REJECTED_OR_QUARANTINED_NO_APPLY"),("DUPLICATE_COMMAND","idempotency","ORIGINAL_RECEIPT_ONLY_ONCE"),("PARTIAL_EFFECT","failure_injection","PARTIALLY_QUARANTINED_OR_UNKNOWN_BLOCKING"),("ACK_OR_CROSSWALK_FAILURE","failure_injection","NO_FALSE_ACKNOWLEDGEMENT"),("PARALLEL_OR_OUT_OF_ORDER","concurrency","DETERMINISTIC_SERIALIZED_OR_QUARANTINED"),("SUCCESS","success","APPLIED_RECONCILED_TYPED_RECEIPT")]
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 p=argparse.ArgumentParser();p.add_argument("--output",required=True,type=Path);a=p.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};ext=[x for x in d["extension"]["cases"] if x.get("surface")=="pos.replicate_session_sales_receipts"];tre=[x for x in d["treasury"]["cases"] if x.get("command")=="tour_payment.replicate_and_write_crosswalk"];pri=[x for x in d["pricing"]["cases"] if x.get("surface")=="pricing_rules.publish_version_and_replicate"];old=ext+tre+pri
 special={"IM-PKG":"transport success without authenticated content and verified center scope never reaches apply","IM-ORD":"a duplicate returns the original receipt; a gap or fork quarantines without advancing acknowledgement","IM-SALE":"multiple histories to the same target remain history; a second target or missing crosswalk is blocking","IM-COMP":"compensation appends one receipt linked to the original and never deletes or repeats the original effect","IM-MIG":"same capture, mapping and importer yields identical hashes; mixed snapshot or failed prior slice blocks progress"};cases=[]
 for prefix,(surface,focus) in F.items():
  for code,kind,expected in CASES:cases.append({"case_id":f"{prefix}-{code}","surface":surface,"case_kind":kind,"focus":focus,"expected_outcome":expected,"assertions":["CommandId, PayloadHash, source scope and sequence are checked before effect","package/item/effect/crosswalk/reconciliation/ack receipts are distinct","unknown effect blocks acknowledgement and downstream progress",special[prefix],"source Varanegar and read-only evidence remain untouched"],"status":"DESIGNED_NOT_EXECUTED"})
 summary={"existing_reused_case_count":len(old),"existing_pos_case_count":len(ext),"existing_payment_case_count":len(tre),"existing_rule_publication_case_count":len(pri),"delta_surface_count":len(F),"delta_case_count":len(cases),"combined_integration_acceptance_design_count":len(old)+len(cases),"case_count_per_delta_surface":7,"case_kind_counts":dict(sorted(collections.Counter(x["case_kind"] for x in cases).items())),"executed_delta_case_count":0,"passed_runtime_case_count":0,"owner_approved_case_count":0,"runtime_retry_idempotency_proven_module_count":0,"command_ready_module_count":0,"pilot_ready_module_count":0,"risk_count":84,"mapped_risk_assignment_count":343,"new_risk_count":0}
 checks={"sources_pass":all(v["validation"]=="PASS" for v in d.values()),"reuse_34":len(old)==34 and (len(ext),len(tre),len(pri))==(20,7,7),"delta_35":len(cases)==35 and all(sum(x["surface"]==surface for x in cases)==7 for surface,_ in F.values()),"unique_ids":len({x["case_id"] for x in cases})==35,"no_old_collision":not ({x["case_id"] for x in cases}&{x["case_id"] for x in old}),"combined_69":summary["combined_integration_acceptance_design_count"]==69,"all_unexecuted":{x["status"] for x in cases}=={"DESIGNED_NOT_EXECUTED"},"nine_contract_modules":d["readiness"]["summary"]["outcome_target_contract_module_count_after"]==9,"runtime_zero":summary["executed_delta_case_count"]==summary["passed_runtime_case_count"]==summary["owner_approved_case_count"]==summary["runtime_retry_idempotency_proven_module_count"]==summary["command_ready_module_count"]==summary["pilot_ready_module_count"]==0,"base_stable":d["risk"]["summary"]["risk_count"]==84 and d["trace"]["summary"]["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_integration_migration_golden_uat_cases_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","safety":{"mode":"OFFLINE_SYNTHETIC_DESIGN","database_connections":0,"network_reads_or_writes":0,"packages_or_transfers_executed":0,"commands_forms_reports_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"sensitive_values_or_payloads_persisted":0},"summary":summary,"reuse_manifest":{"sources":[S["extension"],S["treasury"],S["pricing"]],"policy":"reuse 34 existing POS/payment/rule-publication cases; do not duplicate them"},"execution_gate":{"environment":"isolated target only","requirements":["signed synthetic packages and immutable capture manifests","stub transport and center endpoints","parallel/out-of-order delivery harness","fault injection at stage/apply/crosswalk/reconcile/ack/compensation boundaries","owner-approved migration slice and reconciliation values"],"promotion_rule":"all 69 reused plus delta obligations execute with zero unexplained effect difference and owner approval"},"cases":cases,"checks":checks,"failed_checks":failed,"risk_links":["R-002","R-005","R-006","R-007","R-008","R-023","R-029","R-034","R-036","R-043"],"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"confidence":{"design":"HIGH","runtime":"NOT_EXECUTED"},"limits":["These are acceptance designs, not UAT results.","No package, compensation or migration slice was executed.","Publication/package cases are target obligations, not claims of distinct legacy UI commands."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(summary,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
