"""Correct the accounting command inventory after resolving Manual Voucher semantics."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S={"prior_truth":"artifacts/varanegar_analysis/varanegar_accounting_command_outcome_truth_20260829.json","manual_boundary":"artifacts/varanegar_analysis/varanegar_manual_voucher_static_boundary_20260829.json","generic_save":"artifacts/varanegar_analysis/varanegar_manual_voucher_generic_save_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_manual_voucher_generic_save_checkpoint_20260829.json"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};prior=d["prior_truth"]["truth_table"];kept=[x for x in prior if x["command_id"]!="accounting.manual_voucher.cancel"]
 manual=next(x for x in kept if x["command_id"]=="accounting.manual_voucher.save");manual.update({"business_handler":"Application.BusinessLayer.Handler.IBusinessHandler<ManualVoucherAdapter,...>.SaveCommand","adapter":"ManualVoucherAdapter -> BaseDataV2Adapter generic binding","procedure_or_sql":"generic entity-metadata persistence; no named ManualVoucher procedure literal","transaction_owner":"UI opens Transaction.Begin; context-taking generic Insert/Update/Delete each contain Commit","outcome_contract":"VALIDATION_REJECTED or generic CRUD committed outcome; runtime branch and effect parity unproven","retry_contract":"command-id plus read-back required; no blind retry because selected paths have no explicit rollback signal","confidence":"HIGH_STATIC_GENERIC_BINDING_RUNTIME_BRANCH_UNPROVEN","unproven":["V2/Fararu/CRUD runtime branch","exact table mutation set","runtime authorization","effect parity"]})
 removed=[{"candidate":"accounting.manual_voucher.cancel","classification":"REJECTED_UI_CLOSE_ONLY","evidence":"InternalCancelCommand has three instructions and only Form.Close","target_erp_effect":"no financial cancel/reversal API"}]
 checks={"sources_pass":all(d[k]["validation"]=="PASS" for k in d),"prior_seven":len(prior)==7,"one_removed":len(removed)==1 and len(kept)==6,"cancel_absent":not any(x["command_id"]=="accounting.manual_voucher.cancel" for x in kept),"manual_save_resolved":manual["adapter"].startswith("ManualVoucherAdapter") and "Commit" in manual["transaction_owner"],"external_four_preserved":sum(x["command_id"].startswith("accounting.external_voucher") for x in kept)==4,"runtime_not_overclaimed":not any(x["runtime_effect_parity_proven"] or x["owner_approved"] for x in kept),"risk_stable":d["risk"]["summary"]["risk_count"]==84};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_accounting_command_inventory_correction_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","safety":{"mode":"OFFLINE_EVIDENCE_RECONCILIATION","database_connections":0,"commands_forms_reports_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"sensitive_values_persisted":0},"summary":{"prior_candidate_count":7,"corrected_command_count":6,"rejected_false_command_candidate_count":1,"external_voucher_command_count":4,"stock_voucher_command_count":1,"manual_voucher_command_count":1,"accounting_target_outcome_contract_present":True,"runtime_effect_parity_proven_count":0,"owner_approved_count":0,"risk_count":84,"new_risk_count":0},"removed_candidates":removed,"corrected_truth_table":kept,"semantic_rules":["UI close is not financial cancel","generic persistence is mutation-capable even without a named procedure literal","Commit signal does not prove branch execution or effect parity","retry requires typed outcome and durable read-back"],"erp_target_delta":{"accounting_outcome_contract":"DESIGN_PRESENT","manual_save":"explicit create/update command with expected version and idempotency key","manual_cancel":"ABSENT_UNTIL_A_REAL_REVERSAL_COMMAND_IS_EVIDENCED"},"risk_links":["R-002","R-005","R-007","R-023","R-084"],"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"confidence":{"corrected_inventory":"HIGH_STATIC","runtime_branch_and_effect":"UNPROVEN"},"limits":["The original seven-candidate artifact remains historical evidence; this artifact is the authoritative correction.","No command or procedure was executed.","A real manual-voucher reversal path remains undiscovered, not disproven globally."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
