"""Execute deterministic synthetic manufacturing vectors."""
from __future__ import annotations
import argparse,copy,hashlib,importlib.util,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];REFERENCE=ROOT/"scripts/windows/varanegar_manufacturing_reference.py"
S={"mfg_contract":"artifacts/varanegar_analysis/varanegar_target_erp_manufacturing_mrp_shopfloor_quality_contract_20260901.json","mfg_checkpoint":"artifacts/varanegar_analysis/varanegar_target_erp_manufacturing_mrp_shopfloor_quality_checkpoint_20260901.json","inventory":"artifacts/varanegar_analysis/varanegar_target_erp_inventory_lot_serial_expiry_costing_valuation_contract_20260829.json","concurrency":"artifacts/varanegar_analysis/varanegar_target_erp_optimistic_concurrency_version_fencing_contract_20260829.json","fiscal":"artifacts/varanegar_analysis/varanegar_target_erp_fiscal_period_close_reopen_adjustment_lock_contract_20260829.json","tests":"artifacts/varanegar_analysis/varanegar_25h_final_test_result_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def module():s=importlib.util.spec_from_file_location("mfg_ref",REFERENCE);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return m
def main():
 p=argparse.ArgumentParser();p.add_argument("--output",required=True,type=Path);a=p.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};m=module();base=m.baseline()
 def changed(**kw):e=copy.deepcopy(base);e.update(kw);return e
 positive=[("POS-PLAN",base,"MRP_PLAN_ACCEPTED_PEGGED_NETTED_AND_FENCED"),("POS-RELEASE",changed(operation="RELEASE"),"PRODUCTION_ORDER_ACCEPTED_VERSIONED_APPROVED_AND_RELEASED"),("POS-MATERIAL",changed(operation="MATERIAL"),"MATERIAL_EXECUTION_ACCEPTED_RESERVED_ISSUED_AND_BALANCED"),("POS-OUTPUT",changed(operation="OUTPUT"),"OUTPUT_ACCEPTED_YIELD_GENEALOGY_AND_QUALITY"),("POS-QUALITY",changed(operation="QUALITY"),"QUALITY_DISPOSITION_ACCEPTED_INSPECTED_AND_RELEASED"),("POS-COST",changed(operation="COST"),"COSTING_ACCEPTED_STANDARD_ACTUAL_OVERHEAD_AND_VARIANCE"),("POS-RECON",changed(operation="RECONCILE"),"MANUFACTURING_RECONCILIATION_ACCEPTED_WIP_INVENTORY_COGS_GL")]
 negative=[("NEG-EXTRA",dict(base,extra=True),"SCHEMA_INVALID"),("NEG-SCOPE",changed(scope_current=False),"MANUFACTURING_REJECTED_ITEM_PLANT_OR_OWNER_SCOPE"),("NEG-VERSION",changed(expected_version_match=False),"MANUFACTURING_REJECTED_VERSION_OR_IDEMPOTENCY"),("NEG-IDEMPOTENCY",changed(idempotency_current=False),"MANUFACTURING_REJECTED_VERSION_OR_IDEMPOTENCY"),("NEG-UNKNOWN",changed(unknown_commit=True),"MANUFACTURING_UNKNOWN_RECONCILIATION_REQUIRED"),("NEG-BLOCK",changed(blocking_unknown=True),"MANUAL_REVIEW_REQUIRED_BLOCKING_UNKNOWN"),("NEG-PLAN-POLICY",changed(mrp_pegging_policy_current=False),"MRP_PLAN_REJECTED_BOM_ROUTING_POLICY_OR_PEGGING"),("NEG-PLAN-BOM",changed(bom_routing_version_current=False),"MRP_PLAN_REJECTED_BOM_ROUTING_POLICY_OR_PEGGING"),("NEG-RELEASE",changed(operation="RELEASE",order_version_approval_current=False),"PRODUCTION_ORDER_REJECTED_BOM_ROUTING_VERSION_OR_APPROVAL"),("NEG-RELEASE-BOM",changed(operation="RELEASE",bom_routing_version_current=False),"PRODUCTION_ORDER_REJECTED_BOM_ROUTING_VERSION_OR_APPROVAL"),("NEG-MATERIAL",changed(operation="MATERIAL",material_balance_current=False),"MATERIAL_EXECUTION_REJECTED_SHORTAGE_BACKFLUSH_OR_WIP"),("NEG-WIP",changed(operation="MATERIAL",wip_transition_current=False),"MATERIAL_EXECUTION_REJECTED_SHORTAGE_BACKFLUSH_OR_WIP"),("NEG-OUTPUT",changed(operation="OUTPUT",labor_machine_output_current=False),"OUTPUT_REJECTED_YIELD_GENEALOGY_OR_QUALITY"),("NEG-GENEALOGY",changed(operation="OUTPUT",genealogy_current=False),"OUTPUT_REJECTED_YIELD_GENEALOGY_OR_QUALITY"),("NEG-OUTPUT-QUALITY",changed(operation="OUTPUT",quality_clear=False),"OUTPUT_REJECTED_YIELD_GENEALOGY_OR_QUALITY"),("NEG-QUALITY",changed(operation="QUALITY",quality_clear=False),"QUALITY_DISPOSITION_REJECTED_GENEALOGY_HOLD_OR_APPROVAL"),("NEG-COST",changed(operation="COST",cost_version_variance_current=False),"COSTING_REJECTED_COST_VERSION_VARIANCE_OR_PERIOD"),("NEG-PERIOD",changed(operation="COST",period_current=False),"COSTING_REJECTED_COST_VERSION_VARIANCE_OR_PERIOD"),("NEG-RECON",changed(operation="RECONCILE",wip_inventory_cogs_gl_reconciled=False),"MANUFACTURING_RECONCILIATION_REJECTED_WIP_COST_OR_GL")]
 def run(vs):
  r=[]
  for i,e,x in vs:
   y=m.evaluate(e);r.append({"vector_id":i,"expected":x,"actual":y,"status":"PASS" if y==x else "FAIL"})
  return r
 pr=run(positive);nr=run(negative);allr=pr+nr;official=d["tests"];cs=d["mfg_contract"]["summary"]
 s={"reference_evaluator_implementation_count":1,"positive_vector_count":len(pr),"positive_pass_count":sum(x["status"]=="PASS" for x in pr),"negative_vector_count":len(nr),"negative_pass_count":sum(x["status"]=="PASS" for x in nr),"total_vector_count":len(allr),"total_pass_count":sum(x["status"]=="PASS" for x in allr),"distinct_typed_outcome_count":len({x["actual"] for x in allr}),"manufacturing_gate_count":cs["gate_count"],"manufacturing_module_gate_assignment_count":cs["module_gate_assignment_count"],"operational_mrp_mes_quality_costing_or_shopfloor_implementation_count":0,"operational_bom_routing_order_material_wip_quality_cost_or_ledger_read_count":0,"plan_release_material_output_quality_cost_or_reconcile_run_count":0,"accepted_operational_receipt_count":0,"command_ready_module_count":0,"pilot_ready_module_count":0,"design_lower_bound_before_reference_evaluator":1404,"design_lower_bound_after_reference_evaluator":1404,"official_test_file_count":official["runner"]["test_file_count"],"official_passed_test_count":official["runner"]["passed_test_count"],"risk_count":d["risk"]["summary"]["risk_count"],"mapped_risk_assignment_count":d["trace"]["summary"]["mapped_risk_assignment_count"],"new_risk_count":0}
 checks={"sources_pass":all(d[k].get("validation")=="PASS" for k in ("mfg_contract","mfg_checkpoint","inventory","concurrency","fiscal","tests")),"positive_7_of_7":s["positive_vector_count"]==s["positive_pass_count"]==7,"negative_19_of_19":s["negative_vector_count"]==s["negative_pass_count"]==19,"total_26_of_26":s["total_vector_count"]==s["total_pass_count"]==26,"distinct_outcomes_at_least_19":s["distinct_typed_outcome_count"]>=19,"coverage_24_336":(s["manufacturing_gate_count"],s["manufacturing_module_gate_assignment_count"])==(24,336),"operational_and_readiness_zero":all(s[k]==0 for k in ("operational_mrp_mes_quality_costing_or_shopfloor_implementation_count","operational_bom_routing_order_material_wip_quality_cost_or_ledger_read_count","plan_release_material_output_quality_cost_or_reconcile_run_count","accepted_operational_receipt_count","command_ready_module_count","pilot_ready_module_count")),"non_additive_1404":s["design_lower_bound_before_reference_evaluator"]==s["design_lower_bound_after_reference_evaluator"]==1404,"official_tests_pass":official["validation"]=="PASS" and official["runner"]["bootstrap_excluded_test_file_count"]==0,"base_stable":s["risk_count"]==84 and s["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_target_erp_manufacturing_synthetic_reference_evaluator_contract_20260901","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","scope":{"mode":"pure_synthetic_manufacturing_reference_evaluator","continuation_complete":False,"operational_bom_routing_order_material_wip_quality_cost_or_ledger_read":False},"safety":{"database_connections":0,"network_reads_or_writes":0,"operational_bom_routing_order_material_wip_quality_cost_or_ledger_reads":0,"plan_release_material_output_quality_cost_or_reconcile_actions_executed":0,"operational_forms_reports_queries_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"credentials_pii_or_raw_business_values_read_or_persisted":0},"summary":s,"positive_results":pr,"negative_results":nr,"outcome_precedence":["SCHEMA","SCOPE","VERSION_IDEMPOTENCY","UNKNOWN_COMMIT","BLOCKING_UNKNOWN","OPERATION_POLICY_VERSION_BALANCE_QUALITY","RECONCILIATION","ACCEPTED"],"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())]+[{"name":"reference_evaluator","path":REFERENCE.relative_to(ROOT).as_posix(),"size_bytes":REFERENCE.stat().st_size,"sha256":sha(REFERENCE)},{"name":"builder","path":"scripts/windows/build_varanegar_target_erp_manufacturing_synthetic_reference_evaluator_contract_20260901.py","size_bytes":Path(__file__).stat().st_size,"sha256":sha(Path(__file__))}],"limits":["Only fixed synthetic booleans and operation labels were evaluated.","No operational BOM routing order material WIP quality cost or ledger was used.","Operational planning release execution quality costing reconciliation and readiness remain blocked."]}
 a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(s,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
