"""Execute deterministic synthetic project/job-costing vectors."""
from __future__ import annotations
import argparse,copy,hashlib,importlib.util,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];REFERENCE=ROOT/"scripts/windows/varanegar_project_job_costing_reference.py"
S={"project_contract":"artifacts/varanegar_analysis/varanegar_target_erp_project_job_costing_revenue_billing_contract_20260901.json","project_checkpoint":"artifacts/varanegar_analysis/varanegar_target_erp_project_job_costing_revenue_billing_checkpoint_20260901.json","p2p":"artifacts/varanegar_analysis/varanegar_target_erp_procure_to_pay_three_way_match_contract_20260901.json","o2c":"artifacts/varanegar_analysis/varanegar_target_erp_order_to_cash_credit_collections_contract_20260901.json","payroll":"artifacts/varanegar_analysis/varanegar_target_erp_workforce_time_payroll_contract_20260901.json","fiscal":"artifacts/varanegar_analysis/varanegar_target_erp_fiscal_period_close_reopen_adjustment_lock_contract_20260829.json","tests":"artifacts/varanegar_analysis/varanegar_25h_final_test_result_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def module():s=importlib.util.spec_from_file_location("project_ref",REFERENCE);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return m
def main():
 p=argparse.ArgumentParser();p.add_argument("--output",required=True,type=Path);a=p.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};m=module();base=m.baseline()
 def changed(**kw):e=copy.deepcopy(base);e.update(kw);return e
 positive=[("POS-COMMIT",base,"COMMITMENT_ACCEPTED_FUNDED_AND_BALANCED"),("POS-COST",changed(operation="POST_COST"),"PROJECT_COST_ACCEPTED_APPROVED_AND_ALLOCATED"),("POS-MEASURE",changed(operation="MEASURE"),"PROGRESS_ACCEPTED_WBS_AND_EVIDENCE_CURRENT"),("POS-BILL",changed(operation="BILL"),"PROJECT_BILLING_ACCEPTED_TERMS_AND_PROGRESS"),("POS-REVENUE",changed(operation="RECOGNIZE_REVENUE"),"PROJECT_REVENUE_ACCEPTED_POLICY_PROGRESS_AND_PERIOD"),("POS-RECON",changed(operation="RECONCILE"),"PROJECT_RECONCILIATION_ACCEPTED_COST_REVENUE_BILLING_GL")]
 negative=[("NEG-EXTRA",dict(base,extra=True),"SCHEMA_INVALID"),("NEG-SCOPE",changed(scope_current=False),"PROJECT_REJECTED_SCOPE_OR_WBS_VERSION"),("NEG-WBS",changed(wbs_version_current=False),"PROJECT_REJECTED_SCOPE_OR_WBS_VERSION"),("NEG-VERSION",changed(expected_version_match=False),"PROJECT_REJECTED_VERSION_OR_IDEMPOTENCY"),("NEG-IDEMPOTENCY",changed(idempotency_current=False),"PROJECT_REJECTED_VERSION_OR_IDEMPOTENCY"),("NEG-UNKNOWN",changed(unknown_commit=True),"PROJECT_UNKNOWN_RECONCILIATION_REQUIRED"),("NEG-BLOCK",changed(blocking_unknown=True),"MANUAL_REVIEW_REQUIRED_BLOCKING_UNKNOWN"),("NEG-BUDGET",changed(funding_budget_current=False),"COMMITMENT_REJECTED_BUDGET_OR_BALANCE"),("NEG-COMMIT",changed(commitment_balance_current=False),"COMMITMENT_REJECTED_BUDGET_OR_BALANCE"),("NEG-TIME",changed(operation="POST_COST",time_expense_approved=False),"PROJECT_COST_REJECTED_APPROVAL_ALLOCATION_OR_PERIOD"),("NEG-ALLOC",changed(operation="POST_COST",cost_allocation_current=False),"PROJECT_COST_REJECTED_APPROVAL_ALLOCATION_OR_PERIOD"),("NEG-COST-PERIOD",changed(operation="POST_COST",period_current=False),"PROJECT_COST_REJECTED_APPROVAL_ALLOCATION_OR_PERIOD"),("NEG-MEASURE",changed(operation="MEASURE",progress_measure_current=False),"PROGRESS_REJECTED_MEASURE_OR_EVIDENCE"),("NEG-BILL-TERMS",changed(operation="BILL",billing_terms_current=False),"PROJECT_BILLING_REJECTED_TERMS_OR_PROGRESS"),("NEG-BILL-PROGRESS",changed(operation="BILL",progress_measure_current=False),"PROJECT_BILLING_REJECTED_TERMS_OR_PROGRESS"),("NEG-REV-POLICY",changed(operation="RECOGNIZE_REVENUE",revenue_policy_current=False),"PROJECT_REVENUE_REJECTED_POLICY_PROGRESS_OR_PERIOD"),("NEG-REV-PERIOD",changed(operation="RECOGNIZE_REVENUE",period_current=False),"PROJECT_REVENUE_REJECTED_POLICY_PROGRESS_OR_PERIOD"),("NEG-RECON",changed(operation="RECONCILE",project_subledger_gl_reconciled=False),"PROJECT_RECONCILIATION_REJECTED_SUBLEDGER_OR_GL")]
 def run(vs):
  r=[]
  for i,e,x in vs:y=m.evaluate(e);r.append({"vector_id":i,"expected":x,"actual":y,"status":"PASS" if y==x else "FAIL"})
  return r
 pr=run(positive);nr=run(negative);allr=pr+nr;official=d["tests"];cs=d["project_contract"]["summary"]
 s={"reference_evaluator_implementation_count":1,"positive_vector_count":len(pr),"positive_pass_count":sum(x["status"]=="PASS" for x in pr),"negative_vector_count":len(nr),"negative_pass_count":sum(x["status"]=="PASS" for x in nr),"total_vector_count":len(allr),"total_pass_count":sum(x["status"]=="PASS" for x in allr),"distinct_typed_outcome_count":len({x["actual"] for x in allr}),"project_gate_count":cs["gate_count"],"project_module_gate_assignment_count":cs["module_gate_assignment_count"],"operational_project_costing_billing_or_revenue_implementation_count":0,"operational_project_or_ledger_read_count":0,"commit_cost_measure_bill_recognize_or_reconcile_run_count":0,"accepted_operational_receipt_count":0,"command_ready_module_count":0,"pilot_ready_module_count":0,"design_lower_bound_before_reference_evaluator":1404,"design_lower_bound_after_reference_evaluator":1404,"official_test_file_count":official["runner"]["test_file_count"],"official_passed_test_count":official["runner"]["passed_test_count"],"risk_count":d["risk"]["summary"]["risk_count"],"mapped_risk_assignment_count":d["trace"]["summary"]["mapped_risk_assignment_count"],"new_risk_count":0}
 checks={"sources_pass":all(d[k].get("validation")=="PASS" for k in ("project_contract","project_checkpoint","p2p","o2c","payroll","fiscal","tests")),"positive_6_of_6":s["positive_vector_count"]==s["positive_pass_count"]==6,"negative_18_of_18":s["negative_vector_count"]==s["negative_pass_count"]==18,"total_24_of_24":s["total_vector_count"]==s["total_pass_count"]==24,"distinct_outcomes_at_least_16":s["distinct_typed_outcome_count"]>=16,"coverage_20_280":(s["project_gate_count"],s["project_module_gate_assignment_count"])==(20,280),"operational_and_readiness_zero":all(s[k]==0 for k in ("operational_project_costing_billing_or_revenue_implementation_count","operational_project_or_ledger_read_count","commit_cost_measure_bill_recognize_or_reconcile_run_count","accepted_operational_receipt_count","command_ready_module_count","pilot_ready_module_count")),"non_additive_1404":s["design_lower_bound_before_reference_evaluator"]==s["design_lower_bound_after_reference_evaluator"]==1404,"official_tests_pass":official["validation"]=="PASS" and official["runner"]["bootstrap_excluded_test_file_count"]==0,"base_stable":s["risk_count"]==84 and s["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_target_erp_project_job_costing_synthetic_reference_evaluator_contract_20260901","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","scope":{"mode":"pure_synthetic_project_job_costing_reference_evaluator","operational_runtime_certification":False},"safety":{"database_connections":0,"network_reads_or_writes":0,"operational_project_or_ledger_reads":0,"operational_actions_executed":0,"operational_forms_reports_queries_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"credentials_pii_or_raw_business_values_read_or_persisted":0},"summary":s,"positive_results":pr,"negative_results":nr,"outcome_precedence":["SCHEMA","SCOPE_WBS","VERSION_IDEMPOTENCY","UNKNOWN_COMMIT","BLOCKING_UNKNOWN","OPERATION_POLICY_APPROVAL_PERIOD","RECONCILIATION","ACCEPTED"],"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())]+[{"name":"reference_evaluator","path":REFERENCE.relative_to(ROOT).as_posix(),"size_bytes":REFERENCE.stat().st_size,"sha256":sha(REFERENCE)},{"name":"builder","path":"scripts/windows/build_varanegar_target_erp_project_job_costing_synthetic_reference_evaluator_contract_20260901.py","size_bytes":Path(__file__).stat().st_size,"sha256":sha(Path(__file__))}],"limits":["Only fixed synthetic booleans and operation labels were evaluated.","No operational project contract WBS budget cost billing revenue or ledger data was used.","Operational posting billing recognition reconciliation and readiness remain blocked."]}
 a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(s,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
