"""Build chained checkpoint for RPT-01/RPT-02 Treasury Crystal viewers."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
S={"contract":"artifacts/varanegar_analysis/domains/treasury_crystal_viewer_contract_20260829.json","boundary":"artifacts/varanegar_analysis/domains/treasury_crystal_viewer_boundary_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_dashboard_shell_checkpoint_20260829.json","extractor":"scripts/windows/extract_varanegar_treasury_crystal_viewer_boundary_20260829.py","builder":"scripts/windows/build_varanegar_treasury_crystal_viewer_contract_20260829.py","checkpoint_builder":"scripts/windows/build_varanegar_treasury_crystal_viewer_checkpoint_20260829.py","test":"tests/test_varanegar_treasury_crystal_viewer_contract.py","doc":"docs/varanegar_reconstruction/TREASURY_CRYSTAL_VIEWER_EXTERNAL_DOCUMENT_BOUNDARY_20260829_FA.md"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(paths[k]) for k in ("contract","boundary","previous")};c=d["contract"];checks={"sources_pass":all(x["validation"]=="PASS" for x in d.values()),"two_external_viewers_no_query_owner":c["summary"]["viewer_count"]==2 and c["summary"]["independent_query_owner_count"]==0,"template_parity_not_claimed":c["summary"]["template_query_formula_result_parity_proven_count"]==0,"permission_and_lifecycle":c["summary"]["multi_viewer_permission_boundary_count"]==1 and c["summary"]["document_close_lifecycle_count"]==1,"six_golden_cases":len(c["golden_cases"])==6,"risk_stable":c["summary"]["risk_count"]==84,"zero_execution":set(v for k,v in c["safety"].items() if k!="mode")=={0}};failed=sorted(k for k,v in checks.items() if not v);out={"artifact":"varanegar_treasury_crystal_viewer_checkpoint_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","previous_checkpoint":{"path":S["previous"],"sha256":sha(paths["previous"])},"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"safety":{"reports_templates_forms_or_queries_executed":0,"assemblies_loaded_or_executed":0,"database_connections":0,"data_mutations":0,"credentials_or_sensitive_values_persisted":0}};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
