"""Build adjudication packets for 15 normalized P2 failure-injection pairs."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
S={"comparator":"artifacts/varanegar_analysis/varanegar_p2_alias_semantic_evidence_comparator_20260829.json","shortlist":"artifacts/varanegar_analysis/varanegar_p2_alias_baseline_candidate_shortlist_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_p2_alias_semantic_evidence_checkpoint_20260829.json","extension":"artifacts/varanegar_analysis/ui/varanegar_extension_golden_cases_20260827.json","foundation":"artifacts/varanegar_analysis/ui/negin_erp_foundation_context_pricing_golden_cases_20260827.json","bank":"artifacts/varanegar_analysis/ui/negin_erp_bank_reconciliation_golden_cases_20260827.json","core":"artifacts/varanegar_analysis/ui/varanegar_golden_command_cases_20260827.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json"}
FIELDS=["newer_and_baseline_case_ids","fault_stage_mapping","transaction_boundary_receipt","durable_write_set_receipt","rollback_or_unknown_outcome_disposition","retry_idempotency_receipt","audit_outbox_receipt","pricing_or_cheque_reconciliation","outcome_vocabulary_mapping","assertion_effect_mapping","accountable_role_receipts","policy_version_expiry_supersession"]
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def stage(cid):
 n=cid.casefold().replace("-","_");return "fault_after_"+n.split("fault_after_",1)[1] if "fault_after_" in n else n.rsplit(".",1)[-1]
def assertions(x):return x.get("expected_assertions") or x.get("assertions") or (x.get("expected") if isinstance(x.get("expected"),list) else [])
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};base=[]
 for k in ("extension","foundation","bank","core"):base+=d[k]["cases"]
 by={x["case_id"]:x for x in base};roles={x["source_packet_id"]:x["accountable_role_types"] for x in d["shortlist"]["p2_candidate_packets"]};grouped={}
 for c in d["comparator"]["candidate_comparisons"]:
  for row in c["case_pair_comparisons"]:
   if row["case_kind"]!="failure_injection":continue
   p=grouped.setdefault(c["source_packet_id"],{"source_packet_id":c["source_packet_id"],"newer_action_or_surface":c["newer_action_or_surface"],"accountable_role_types":roles[c["source_packet_id"]],"candidate_failure_comparisons":[]});text=" ".join(map(str,assertions(by[row["baseline_case_id"]]))).casefold();bs=stage(row["baseline_case_id"]);ns=stage(row["newer_case_id"]);p["candidate_failure_comparisons"].append({"comparison_id":c["comparison_id"],"baseline_action":c["baseline_action"],"newer_case_id":row["newer_case_id"],"baseline_case_id":row["baseline_case_id"],"newer_fault_stage":ns,"baseline_fault_stage":bs,"fault_stage_exact":ns==bs,"fault_stage_relation":"EXACT_LABEL_STILL_SEMANTIC_REVIEW" if ns==bs else "NORMALIZED_OR_DIFFERENT_TO_DETAILED_STAGE_REVIEW","outcome_exact":row["outcome_exact"],"assertion_list_exact":row["assertion_list_exact"],"baseline_retry_or_convergence_explicit":("retry" in text or "converg" in text),"baseline_no_partial_effect_explicit":"no partial" in text,"baseline_audit_or_outbox_sensitive":("audit" in text or "outbox" in text),"required_disposition_fields":FIELDS,"current_status":"WAITING_FOR_FAILURE_STAGE_AND_DURABLE_EFFECT_DISPOSITION","accepted_pair_count":0,"counting_effect":"ZERO"})
 packets=[]
 for i,p in enumerate(sorted(grouped.values(),key=lambda x:x["source_packet_id"]),1):p.update({"adjudication_packet_id":f"P2F-{i:02d}","failure_pair_count":len(p["candidate_failure_comparisons"]),"accepted_pair_count":0,"current_status":"WAITING_FOR_FAILURE_STAGE_AND_DURABLE_EFFECT_DISPOSITION","counting_effect":"ZERO"});packets.append(p)
 pairs=[x for p in packets for x in p["candidate_failure_comparisons"]];s={"source_packet_count":len(packets),"candidate_action_comparison_count":len({x["comparison_id"] for x in pairs}),"failure_injection_pair_count":len(pairs),"newer_unique_failure_case_count":len({x["newer_case_id"] for x in pairs}),"baseline_unique_failure_case_count":len({x["baseline_case_id"] for x in pairs}),"exact_fault_stage_label_pair_count":sum(x["fault_stage_exact"] for x in pairs),"different_or_normalized_stage_pair_count":sum(not x["fault_stage_exact"] for x in pairs),"baseline_retry_or_convergence_explicit_pair_count":sum(x["baseline_retry_or_convergence_explicit"] for x in pairs),"baseline_no_partial_effect_explicit_pair_count":sum(x["baseline_no_partial_effect_explicit"] for x in pairs),"baseline_audit_or_outbox_sensitive_pair_count":sum(x["baseline_audit_or_outbox_sensitive"] for x in pairs),"outcome_exact_pair_count":sum(x["outcome_exact"] for x in pairs),"assertion_list_exact_pair_count":sum(x["assertion_list_exact"] for x in pairs),"fully_exact_pair_count":sum(x["fault_stage_exact"] and x["outcome_exact"] and x["assertion_list_exact"] for x in pairs),"accountable_role_assignment_count":sum(len(x["accountable_role_types"]) for x in packets),"required_disposition_field_count":len(FIELDS),"accepted_failure_pair_count":0,"exact_non_duplicated_additive_count":0,"design_lower_bound_before_failure_adjudication":1404,"design_lower_bound_after_failure_adjudication":1404,"executed_case_count":0,"owner_approved_case_count":0,"command_ready_module_count":0,"pilot_ready_module_count":0,"risk_count":d["risk"]["summary"]["risk_count"],"mapped_risk_assignment_count":d["trace"]["summary"]["mapped_risk_assignment_count"],"new_risk_count":0}
 checks={"sources_pass":all(x.get("validation")=="PASS" for k,x in d.items() if k!="core") and d["core"].get("validation") is None,"five_packets_six_candidates_15":(s["source_packet_count"],s["candidate_action_comparison_count"],s["failure_injection_pair_count"])==(5,6,15),"unique_5_11":(s["newer_unique_failure_case_count"],s["baseline_unique_failure_case_count"])==(5,11),"stages_2_13":(s["exact_fault_stage_label_pair_count"],s["different_or_normalized_stage_pair_count"])==(2,13),"properties_10_10_13":(s["baseline_retry_or_convergence_explicit_pair_count"],s["baseline_no_partial_effect_explicit_pair_count"],s["baseline_audit_or_outbox_sensitive_pair_count"])==(10,10,13),"semantic_zero":s["outcome_exact_pair_count"]==s["assertion_list_exact_pair_count"]==s["fully_exact_pair_count"]==0,"roles_fields":s["accountable_role_assignment_count"]==10 and s["required_disposition_field_count"]==12,"non_additive_1404":s["accepted_failure_pair_count"]==s["exact_non_duplicated_additive_count"]==0 and s["design_lower_bound_before_failure_adjudication"]==s["design_lower_bound_after_failure_adjudication"]==1404,"execution_readiness_zero":s["executed_case_count"]==s["owner_approved_case_count"]==s["command_ready_module_count"]==s["pilot_ready_module_count"]==0,"base_stable":s["risk_count"]==84 and s["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_p2_failure_injection_adjudication_packets_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","scope":{"mode":"OFFLINE_P2_FAILURE_INJECTION_ADJUDICATION_DESIGN","continuation_complete":False},"safety":{"database_connections":0,"golden_uat_or_operational_execution":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"write_access_created":0,"raw_business_values_identity_or_credentials_persisted":0},"summary":s,"required_disposition_fields":FIELDS,"failure_adjudication_packets":packets,"priority_rule":"normalized labels must not absorb pricing version, commit-before-response, replication, audit/outbox, cheque state, rollback, or retry differences","checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":p.stat().st_size,"sha256":sha(p)} for k,p in sorted(paths.items())]+[{"name":"builder","path":"scripts/windows/build_varanegar_p2_failure_injection_adjudication_packets_20260829.py","size_bytes":Path(__file__).stat().st_size,"sha256":sha(Path(__file__))}],"limits":["Failure properties are parsed from documented assertions, not runtime execution.","Two exact stage labels still lack outcome/assertion equivalence.","No pair is accepted."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(s,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
