"""Build the distribution command outcome/retry envelope from pinned static evidence."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
S={"anchors":"artifacts/varanegar_analysis/ui/varanegar_distribution_sql_anchor_contracts_20260827.json","runtime":"artifacts/varanegar_analysis/domains/distribution_exit_runtime_boundary_20260829.json","lifecycle":"artifacts/varanegar_analysis/domains/distribution_exit_lifecycle_boundary_20260829.json","semantics":"artifacts/varanegar_analysis/ui/varanegar_distribution_sql_semantics_20260827.json","mutation":"artifacts/varanegar_analysis/ui/varanegar_distribution_mutation_source_model_20260827.json","outcome":"artifacts/varanegar_analysis/domains/command_outcome_commit_matrix_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_treasury_traceability_delta_checkpoint_20260829.json"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};anchors={x["command"]:x for x in d["anchors"]["commands"]}
 specs={
 "distribution.create_or_update":{"transaction_owner":"caller/ambient or procedure route is not pinned as one physical transaction","outcome_gap":"number allocation, distribution row, sale links and history can span multiple writes","retry":"read distribution identity, expected version, sale links and history before retry"},
 "distribution.issue_exit":{"transaction_owner":"ordinary UI DataContext commits after nested Business/Adapter call; physical enlistment is unproven","outcome_gap":"procedure has no local transaction and performs exit, type-60 voucher, sale and history writes before a later cardex check","retry":"read exit, type-60 voucher graph, sale links, distribution status and audit before retry"},
 "distribution.merge_or_adjust_exit":{"transaction_owner":"UNPROVEN: UI has no explicit context/commit and adapter procedure has no local commit","outcome_gap":"merge/adjust writes goods-exit relation rows without an observed idempotency key","retry":"read the relation projection by distribution/source identity before retry"},
 "distribution.remove_exit":{"transaction_owner":"ordinary UI DataContext commits after validation and nested remove call; physical enlistment is unproven","outcome_gap":"procedure deletes voucher graph, unlinks sales, soft-cancels exit and resets distribution without local begin/commit","retry":"read cancellation flag/date, voucher deletion evidence, sale links, distribution status and history before retry"},
 }
 commands=[]
 for i,name in enumerate(["distribution.create_or_update","distribution.issue_exit","distribution.merge_or_adjust_exit","distribution.remove_exit"],1):
  x=anchors[name];s=specs[name];commands.append({"id":f"DS-CMD-{i:02d}","command":name,"evidence_level":"STATIC_UI_BUSINESS_ADAPTER_SQL_CHAIN","ui_to_business_chain":x["ui_to_business_chain"],"sql_objects":x["sql_objects"],"mutation_statement_evidence_count":x["mutation_statement_evidence_count"],"mutation_set":x["mutated_references"],"ledger_and_history_refs":x["ledger_and_history_references"],"explicit_idempotency_parameter_observed":x["explicit_idempotency_parameter_observed"],**s})
 target={"request_fields":["command_id","actor_capabilities","distribution_id_or_source_identity","resource_scope","fiscal_year","operation_date","expected_version","policy_snapshot_version","requested_transition"],"guard_order":["authenticate","authorize action","authorize DC/route/resource scope","validate state/version/date","check idempotency","begin one unit of work","apply mutation","append audit/outbox","reconcile post-condition","commit"],"outcome_codes":["COMMITTED","REJECTED_NO_EFFECT","REJECTED_WITH_DURABLE_EFFECT","UNKNOWN_REQUIRES_READBACK"],"response_fields":["outcome_code","committed","distribution_version","exit_id","voucher_identity","durable_effect_summary","retryable","correlation_id","original_command_id"],"atomicity":"one application-service transaction owns distribution, exit, voucher graph, sale links, history, audit and outbox","idempotency":"unique command_id plus source identity; duplicate same payload returns original outcome and conflicting payload is rejected","readback":"ambiguous paths reconcile distribution state, exit lifecycle, voucher graph, sale links, history and audit/outbox before retry"}
 life=d["lifecycle"]["summary"];run=d["runtime"]["managed_exit_contract"];oc=next(x for x in d["outcome"]["cases"] if x["case_id"]=="OC-07");summary={"command_count":len(commands),"command_without_explicit_idempotency_count":sum(not x["explicit_idempotency_parameter_observed"] for x in commands),"command_with_unproven_physical_transaction_owner_count":len(commands),"target_outcome_code_count":len(target["outcome_codes"]),"current_active_exit_count":life["current_active_exit_count"],"current_cancelled_exit_count":life["current_cancelled_exit_count"],"cancelled_exit_without_type60_delete_count":life["cancelled_exit_without_type60_delete_count"],"logged_exit_absent_count":life["logged_exit_absent_count"],"historically_absent_distribution_count":life["historically_absent_distribution_count"],"runtime_effect_parity_proven_count":0,"executed_acceptance_case_count":0,"owner_approved_count":0,"risk_count":84,"mapped_risk_assignment_count":343,"new_risk_count":0}
 checks={"sources_pass":all(x["validation"]=="PASS" for x in d.values()),"four_commands":summary["command_count"]==d["anchors"]["summary"]["selected_command_count"]==4,"all_lack_idempotency":summary["command_without_explicit_idempotency_count"]==4,"caller_dependent_atomicity":oc["outcome_classification"]=="CALLER_DEPENDENT_ATOMICITY" and run["physical_transaction_enlistment_across_ui_and_nested_adapter_contexts_proven"] is False,"issue_and_remove_ui_routes":run["normal_ui_route_selection_proven_for_issue_and_remove"],"merge_owner_unproven":run["merge_ui_delegates_without_explicit_context_or_commit"],"lifecycle_reconciliation_pinned":summary["cancelled_exit_without_type60_delete_count"]==0 and summary["logged_exit_absent_count"]==8 and summary["historically_absent_distribution_count"]==6,"mutation_model_pinned":d["mutation"]["summary"]["resolved_object_count"]==16 and d["semantics"]["summary"]["execution_result_or_effect_parity_proven_count"]==0,"base_stable":d["risk"]["summary"]["risk_count"]==84 and d["trace"]["summary"]["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_distribution_command_outcome_envelope_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","safety":{"mode":"OFFLINE_EVIDENCE_SYNTHESIS","database_connections":0,"commands_forms_reports_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"sensitive_values_persisted":0},"summary":summary,"commands":commands,"target_outcome_retry_envelope":target,"risk_links":["R-002","R-005","R-006","R-007","R-008","R-023","R-034","R-036","R-043"],"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"confidence":{"static_command_chain":"HIGH","physical_transaction_enlistment":"UNPROVEN","runtime_effect_parity":"UNPROVEN"},"limits":["Current aggregate cleanliness does not prove every historical route was atomic.","No stored procedure, form, report or command was executed.","No runtime retry, effect parity or owner acceptance is claimed."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(summary,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
