"""Build a design-only snapshot/delta migration cutover reconciliation contract."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
S={"blueprint":"artifacts/varanegar_analysis/ui/negin_personal_erp_blueprint_20260827.json","migration_outcome":"artifacts/varanegar_analysis/varanegar_integration_migration_outcome_envelope_20260829.json","migration_readiness":"artifacts/varanegar_analysis/varanegar_integration_migration_readiness_delta_20260829.json","migration_golden":"artifacts/varanegar_analysis/varanegar_integration_migration_golden_uat_cases_20260829.json","reconciliation":"artifacts/varanegar_analysis/varanegar_cross_module_reconciliation_contract_20260829.json","transaction":"artifacts/varanegar_analysis/varanegar_target_erp_transaction_owner_saga_compensation_contract_20260829.json","redaction_checkpoint":"artifacts/varanegar_analysis/varanegar_target_erp_evidence_redaction_synthetic_reference_validator_checkpoint_20260829.json","tests":"artifacts/varanegar_analysis/varanegar_25h_final_test_result_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json"}
CUTOVER_PHASES=[("MCP-01","scope_contract_and_source_authorization_frozen"),("MCP-02","source_snapshot_boundary_and_watermark_pinned"),("MCP-03","snapshot_manifest_hash_count_and_schema_validated"),("MCP-04","target_empty_or_declared_baseline_precondition_validated"),("MCP-05","initial_snapshot_import_isolated_and_receipted"),("MCP-06","delta_capture_range_gap_overlap_and_order_validated"),("MCP-07","delta_batches_applied_idempotently_to_pinned_watermark"),("MCP-08","module_and_cross_module_invariants_reconciled"),("MCP-09","blocking_unknown_zero_and_explained_differences_approved"),("MCP-10","business_owner_and_independent_reviewer_acceptance"),("MCP-11","rollback_abort_and_reentry_boundary_proven"),("MCP-12","controlled_write_enablement_and_legacy_fence_decision")]
RECONCILIATION_DIMENSIONS=["SOURCE_TARGET_AGGREGATE_COUNT","CANONICAL_CONTENT_HASH","REFERENCE_AND_FOREIGN_KEY_CLOSURE","CURRENT_POINTER_AND_HISTORY_COHERENCE","FINANCIAL_DEBIT_CREDIT_AND_BALANCE_INVARIANT","INVENTORY_QUANTITY_VALUE_AND_RESERVATION_INVARIANT","RECEIVABLE_PAYABLE_PAYMENT_ALLOCATION_INVARIANT","ORDER_SALE_RETURN_DISTRIBUTION_LIFECYCLE_INVARIANT","OUTBOX_INBOX_IDEMPOTENCY_AND_WATERMARK_CONVERGENCE","REPORT_PROJECTION_AND_DOCUMENT_REFERENCE_COHERENCE","QUARANTINE_REASON_OWNER_AND_RETRY_STATE","UNEXPLAINED_AND_BLOCKING_UNKNOWN_COUNT"]
SNAPSHOT_FIELDS=["snapshot_id","source_authorization_receipt_sha256","source_system_version_sha256","source_schema_version_sha256","scope_contract_sha256","module_id_set_sha256","snapshot_started_at","snapshot_completed_at","source_watermark_type","source_watermark_value_sha256","record_count_map_sha256","canonical_hash_map_sha256","file_or_segment_manifest_sha256","segment_count","encryption_and_key_reference_policy_sha256","redaction_attestation_sha256","retention_policy_sha256","producer_role_receipt_reference","independent_reviewer_receipt_reference","typed_outcome","supersedes_snapshot_sha256","snapshot_manifest_sha256"]
DELTA_FIELDS=["delta_batch_id","snapshot_manifest_sha256","module_id","range_start_exclusive_sha256","range_end_inclusive_sha256","previous_batch_receipt_sha256","event_or_record_count","canonical_batch_hash_sha256","schema_contract_version_sha256","ordering_policy_sha256","gap_count","overlap_count","duplicate_count","apply_attempt_number","apply_started_at","apply_completed_at","typed_outcome","operator_role_receipt_reference","reviewer_role_receipt_reference","delta_receipt_sha256"]
DECISION_FIELDS=["cutover_decision_id","scope_contract_sha256","snapshot_manifest_sha256","last_delta_receipt_set_sha256","target_reconciliation_receipt_set_sha256","source_fence_receipt_sha256","target_write_enablement_receipt_sha256","rollback_boundary_reference_sha256","unexplained_difference_count","blocking_unknown_count","quarantined_item_count","accepted_exception_set_sha256","business_owner_receipt_reference","migration_operator_receipt_reference","independent_reviewer_receipt_reference","decided_at","typed_outcome","decision_sha256"]
GATES=[("MCG-01","authorized_current_source_not_stale_clone"),("MCG-02","scope_schema_mapping_and_transform_versions_pinned"),("MCG-03","snapshot_boundary_watermark_and_manifest_complete"),("MCG-04","all_segments_hash_count_and_redaction_valid"),("MCG-05","target_baseline_precondition_and_write_fence_valid"),("MCG-06","initial_import_receipts_complete_and_idempotent"),("MCG-07","delta_ranges_ordered_gapless_nonoverlapping_and_monotonic"),("MCG-08","delta_duplicate_replay_returns_original_receipt"),("MCG-09","snapshot_delta_boundary_has_no_loss_or_double_apply"),("MCG-10","all_module_reconciliation_dimensions_evaluated"),("MCG-11","cross_module_reference_and_financial_invariants_reconciled"),("MCG-12","unexplained_and_blocking_unknown_counts_zero"),("MCG-13","quarantine_has_reason_owner_retry_and_expiry"),("MCG-14","operator_reviewer_and_business_owner_separated"),("MCG-15","rollback_abort_cleanup_and_reentry_proven"),("MCG-16","source_fence_and_target_enablement_are_durable_and_ordered"),("MCG-17","retention_redaction_and_evidence_custody_current"),("MCG-18","final_owner_and_independent_cutover_receipts_current")]
ROLES=["MIGRATION_SCOPE_OWNER_ROLE","SOURCE_SNAPSHOT_OPERATOR_ROLE","TARGET_IMPORT_OPERATOR_ROLE","MODULE_RECONCILIATION_OWNER_ROLE","BUSINESS_CUTOVER_OWNER_ROLE","INDEPENDENT_MIGRATION_REVIEWER_ROLE"]
OUTCOMES=["SNAPSHOT_ACCEPTED_DELTA_PENDING","DELTA_APPLIED_RECONCILIATION_PENDING","CUTOVER_ACCEPTED_ALL_INVARIANTS_CURRENT","STALE_OR_UNAUTHORIZED_SOURCE_REJECTED","SNAPSHOT_MANIFEST_OR_SEGMENT_INVALID","DELTA_GAP_OVERLAP_ORDER_OR_REPLAY_CONFLICT","RECONCILIATION_MISMATCH_OR_BLOCKING_UNKNOWN","QUARANTINE_OR_OWNER_DECISION_REQUIRED","ROLLBACK_OR_REENTRY_UNPROVEN","SOURCE_FENCE_OR_TARGET_ENABLEMENT_ORDER_INVALID"]
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def sh(values):return hashlib.sha256(json.dumps(sorted(values),separators=(",",":")).encode()).hexdigest()
def main():
 p=argparse.ArgumentParser();p.add_argument("--output",required=True,type=Path);a=p.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};mods=d["blueprint"]["modules"]
 plans=[{"module_id":m["id"],"owned_concept_set_sha256":sh(m["owns"]),"dependency_module_id_set_sha256":sh(m["depends_on"]),"snapshot_status":"NOT_CAPTURED","delta_status":"NOT_CAPTURED","reconciliation_status":"UNEXECUTED","cutover_status":"BLOCKED"} for m in mods]
 phases=[{"module_id":m["id"],"phase_id":i,"status":"UNEXECUTED","accepted_receipt_count":0} for m in mods for i,_ in CUTOVER_PHASES]
 dims=[{"module_id":m["id"],"reconciliation_dimension":x,"status":"UNEXECUTED","blocking_unknown_count":None,"accepted_receipt_count":0} for m in mods for x in RECONCILIATION_DIMENSIONS]
 gates=[{"module_id":m["id"],"gate_id":i,"status":"UNMET","accepted_evidence_count":0} for m in mods for i,_ in GATES]
 roles=[{"module_id":m["id"],"role_type":r,"status":"UNASSIGNED","role_receipt_reference":None} for m in mods for r in ROLES];o=d["tests"]
 s={"module_count":len(mods),"cutover_phase_count":len(CUTOVER_PHASES),"module_phase_assignment_count":len(phases),"reconciliation_dimension_count":len(RECONCILIATION_DIMENSIONS),"module_reconciliation_assignment_count":len(dims),"snapshot_manifest_field_count":len(SNAPSHOT_FIELDS),"delta_batch_receipt_field_count":len(DELTA_FIELDS),"cutover_decision_field_count":len(DECISION_FIELDS),"gate_count":len(GATES),"module_gate_assignment_count":len(gates),"role_type_count":len(ROLES),"module_role_assignment_count":len(roles),"typed_outcome_count":len(OUTCOMES),"authorized_snapshot_capture_count":0,"snapshot_captured_or_read_count":0,"delta_batch_captured_or_applied_count":0,"module_reconciliation_run_count":0,"blocking_unknown_zero_proven_module_count":0,"owner_approved_module_count":0,"cutover_accepted_module_count":0,"target_write_enabled_module_count":0,"command_ready_module_count":0,"pilot_ready_module_count":0,"design_lower_bound_before_cutover_contract":1404,"design_lower_bound_after_cutover_contract":1404,"official_test_file_count":o["runner"]["test_file_count"],"official_passed_test_count":o["runner"]["passed_test_count"],"risk_count":d["risk"]["summary"]["risk_count"],"mapped_risk_assignment_count":d["trace"]["summary"]["mapped_risk_assignment_count"],"new_risk_count":0}
 checks={"sources_pass":all(d[k].get("validation")=="PASS" for k in ("migration_outcome","migration_readiness","migration_golden","reconciliation","transaction","redaction_checkpoint","tests")),"modules_14_phases_12_assignments_168":(s["module_count"],s["cutover_phase_count"],s["module_phase_assignment_count"])==(14,12,168),"dimensions_12_assignments_168":(s["reconciliation_dimension_count"],s["module_reconciliation_assignment_count"])==(12,168),"fields_22_20_18":(s["snapshot_manifest_field_count"],s["delta_batch_receipt_field_count"],s["cutover_decision_field_count"])==(22,20,18),"gates_18_assignments_252":(s["gate_count"],s["module_gate_assignment_count"])==(18,252),"roles_6_assignments_84_outcomes_10":(s["role_type_count"],s["module_role_assignment_count"],s["typed_outcome_count"])==(6,84,10),"all_phase_dimension_gate_role_states_open":all(x["status"]=="UNEXECUTED" for x in phases+dims) and all(x["status"]=="UNMET" for x in gates) and all(x["status"]=="UNASSIGNED" for x in roles),"snapshot_delta_reconcile_cutover_readiness_zero":s["authorized_snapshot_capture_count"]==s["snapshot_captured_or_read_count"]==s["delta_batch_captured_or_applied_count"]==s["module_reconciliation_run_count"]==s["blocking_unknown_zero_proven_module_count"]==s["owner_approved_module_count"]==s["cutover_accepted_module_count"]==s["target_write_enabled_module_count"]==s["command_ready_module_count"]==s["pilot_ready_module_count"]==0,"non_additive_1404":s["design_lower_bound_before_cutover_contract"]==s["design_lower_bound_after_cutover_contract"]==1404,"official_tests_pass":o["validation"]=="PASS" and o["runner"]["bootstrap_excluded_test_file_count"]==0,"base_stable":s["risk_count"]==84 and s["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_target_erp_migration_cutover_snapshot_delta_reconciliation_contract_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","scope":{"mode":"target_migration_cutover_design_only","continuation_complete":False,"snapshot_delta_import_reconciliation_or_cutover_executed":False,"source_target_or_transport_selected":False},"safety":{"database_connections":0,"network_reads_or_writes":0,"snapshots_deltas_imports_reconciliations_fences_or_cutovers_executed":0,"operational_forms_reports_queries_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"credentials_endpoints_pii_or_raw_business_values_read_or_persisted":0},"summary":s,"risk_links":["R-023","R-025","R-006","R-007","R-004","R-019","R-022"],"cutover_phases":[{"phase_id":i,"phase":x} for i,x in CUTOVER_PHASES],"reconciliation_dimensions":RECONCILIATION_DIMENSIONS,"snapshot_manifest_fields":SNAPSHOT_FIELDS,"delta_batch_receipt_fields":DELTA_FIELDS,"cutover_decision_fields":DECISION_FIELDS,"gates":[{"gate_id":i,"gate":x,"failure_effect":"CUTOVER_BLOCKED"} for i,x in GATES],"role_types":ROLES,"typed_outcomes":OUTCOMES,"module_cutover_plans":plans,"module_phase_assignments":phases,"module_reconciliation_assignments":dims,"module_gate_assignments":gates,"module_role_assignments":roles,"cutover_rule":{"stale_clone_may_be_labeled_live_source":False,"snapshot_without_authorized_watermark_is_current":False,"delta_gap_overlap_or_out_of_order_may_be_applied":False,"same_delta_replay_may_create_new_effect":False,"blocking_unknown_may_be_waived_for_schedule":False,"operator_may_self_approve_reconciliation_or_cutover":False,"target_writes_may_enable_before_source_fence_and_final_receipts":False,"raw_source_target_values_may_be_persisted_in_evidence":False,"rollback_or_reentry_may_be_assumed":False,"automatic_cutover_or_readiness":False},"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())]+[{"name":"builder","path":"scripts/windows/build_varanegar_target_erp_migration_cutover_snapshot_delta_reconciliation_contract_20260829.py","size_bytes":Path(__file__).stat().st_size,"sha256":sha(Path(__file__))}],"limits":["This is a migration and cutover evidence design; no source snapshot delta target import reconciliation fence or cutover was accessed or executed.","A clone or historical snapshot is never promoted to live truth without authorized current watermark and delta reconciliation.","Cutover and readiness remain zero until all module and cross-module dimensions have current owner-reviewed receipts and blocking_unknown is zero."]}
 a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(s,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
