"""Execute deterministic synthetic vectors for the pure release reference evaluator."""
from __future__ import annotations
import argparse,copy,hashlib,importlib.util,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
REFERENCE=ROOT/"scripts/windows/varanegar_release_promotion_rollback_reference.py"
S={"release":"artifacts/varanegar_analysis/varanegar_target_erp_release_promotion_change_rollback_evidence_contract_20260829.json","release_checkpoint":"artifacts/varanegar_analysis/varanegar_target_erp_release_promotion_change_rollback_evidence_checkpoint_20260829.json","environment":"artifacts/varanegar_analysis/varanegar_target_erp_environment_isolation_write_fence_execution_token_contract_20260829.json","recovery":"artifacts/varanegar_analysis/varanegar_target_erp_backup_restore_rehearsal_evidence_contract_20260829.json","observability":"artifacts/varanegar_analysis/varanegar_target_erp_observability_slo_incident_evidence_contract_20260829.json","tests":"artifacts/varanegar_analysis/varanegar_25h_final_test_result_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def module():
 spec=importlib.util.spec_from_file_location("release_reference",REFERENCE);m=importlib.util.module_from_spec(spec);spec.loader.exec_module(m);return m
def main():
 p=argparse.ArgumentParser();p.add_argument("--output",required=True,type=Path);a=p.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};m=module()
 positives=[("POS-UAT",m.baseline("PROMOTE_SANDBOX_TO_UAT"),"UAT_PROMOTION_ACCEPTED"),("POS-PROD",m.baseline("PROMOTE_UAT_TO_PRODUCTION"),"PRODUCTION_PROMOTION_ACCEPTED"),("POS-ROLLBACK",m.baseline("ROLLBACK_PRODUCTION"),"PRODUCTION_ROLLBACK_ACCEPTED")]
 prod=m.baseline("PROMOTE_UAT_TO_PRODUCTION");rollback=m.baseline("ROLLBACK_PRODUCTION")
 specs=[("NEG-EXTRA","extra",True,"SCHEMA_INVALID"),("NEG-DIGEST-FORMAT","source_artifact_sha256","x","ARTIFACT_DIGEST_INVALID"),("NEG-DIGEST-MISMATCH","target_artifact_sha256","b"*64,"ARTIFACT_DIGEST_MISMATCH"),("NEG-SIGNATURE","signature_valid",False,"SUPPLY_CHAIN_INVALID"),("NEG-PROVENANCE","provenance_valid",False,"SUPPLY_CHAIN_INVALID"),("NEG-SBOM","sbom_valid",False,"SUPPLY_CHAIN_INVALID"),("NEG-TESTS","tests_current_zero_exclusion",False,"TEST_EVIDENCE_INVALID"),("NEG-TOKEN","environment_token_valid",False,"ENVIRONMENT_TOKEN_INVALID"),("NEG-WINDOW","change_window_valid",False,"CHANGE_WINDOW_INVALID"),("NEG-MIGRATION","migration_compatible",False,"MIGRATION_OR_RECOVERY_INVALID"),("NEG-RECOVERY","backup_restore_current",False,"MIGRATION_OR_RECOVERY_INVALID"),("NEG-CANARY","canary_threshold_ok",False,"CANARY_OR_KILL_SWITCH_INVALID"),("NEG-KILL","kill_switch_ready",False,"CANARY_OR_KILL_SWITCH_INVALID"),("NEG-REDACTION","redaction_retention_current",False,"REDACTION_OR_RETENTION_INVALID"),("NEG-UNKNOWN","blocking_unknown_count",1,"BLOCKING_UNKNOWN_PRESENT"),("NEG-RESIDUAL","residual_difference_count",1,"RESIDUAL_DIFFERENCE_PRESENT"),("NEG-HEALTH","health_pass",False,"HEALTH_SLO_OR_BUSINESS_INVARIANT_FAILED"),("NEG-SLO","slo_pass",False,"HEALTH_SLO_OR_BUSINESS_INVARIANT_FAILED"),("NEG-BUSINESS","business_invariant_pass",False,"HEALTH_SLO_OR_BUSINESS_INVARIANT_FAILED"),("NEG-UAT","uat_accepted",False,"UAT_ACCEPTANCE_MISSING"),("NEG-PROD-APPROVAL","production_approved",False,"PRODUCTION_APPROVAL_MISSING"),("NEG-ROLE-SEPARATION","independent_roles_separated",False,"INDEPENDENT_ROLE_SEPARATION_INVALID")]
 negatives=[]
 for i,key,value,expected in specs:
  e=copy.deepcopy(prod);e[key]=value;negatives.append((i,e,expected))
 unsafe=copy.deepcopy(rollback);unsafe["rollback_safe"]=False;negatives.append(("NEG-ROLLBACK-UNSAFE",unsafe,"FORWARD_FIX_REQUIRED_ROLLBACK_UNSAFE"))
 def run(vectors):return [{"vector_id":i,"expected":expected,"actual":m.evaluate(e),"status":"PASS" if m.evaluate(e)==expected else "FAIL"} for i,e,expected in vectors]
 pr=run(positives);nr=run(negatives);results=pr+nr;o=d["tests"]
 s={"reference_evaluator_implementation_count":1,"positive_vector_count":len(pr),"positive_pass_count":sum(x["status"]=="PASS" for x in pr),"negative_vector_count":len(nr),"negative_pass_count":sum(x["status"]=="PASS" for x in nr),"total_vector_count":len(results),"total_pass_count":sum(x["status"]=="PASS" for x in results),"distinct_typed_outcome_count":len({x["actual"] for x in results}),"release_gate_count":d["release"]["summary"]["gate_count"],"release_module_gate_assignment_count":d["release"]["summary"]["module_gate_assignment_count"],"operational_release_or_rollback_evaluator_implementation_count":0,"runtime_manifest_or_artifact_read_count":0,"promotion_or_rollback_run_count":0,"accepted_operational_receipt_count":0,"command_ready_module_count":0,"pilot_ready_module_count":0,"design_lower_bound_before_reference_evaluator":1404,"design_lower_bound_after_reference_evaluator":1404,"official_test_file_count":o["runner"]["test_file_count"],"official_passed_test_count":o["runner"]["passed_test_count"],"risk_count":d["risk"]["summary"]["risk_count"],"mapped_risk_assignment_count":d["trace"]["summary"]["mapped_risk_assignment_count"],"new_risk_count":0}
 checks={"sources_pass":all(d[k].get("validation")=="PASS" for k in ("release","release_checkpoint","environment","recovery","observability","tests")),"positive_3_of_3":s["positive_vector_count"]==s["positive_pass_count"]==3,"negative_23_of_23":s["negative_vector_count"]==s["negative_pass_count"]==23,"total_26_of_26":s["total_vector_count"]==s["total_pass_count"]==26,"release_coverage_20_280":(s["release_gate_count"],s["release_module_gate_assignment_count"])==(20,280),"operational_and_readiness_zero":s["operational_release_or_rollback_evaluator_implementation_count"]==s["runtime_manifest_or_artifact_read_count"]==s["promotion_or_rollback_run_count"]==s["accepted_operational_receipt_count"]==s["command_ready_module_count"]==s["pilot_ready_module_count"]==0,"non_additive_1404":s["design_lower_bound_before_reference_evaluator"]==s["design_lower_bound_after_reference_evaluator"]==1404,"official_tests_pass":o["validation"]=="PASS" and o["runner"]["bootstrap_excluded_test_file_count"]==0,"base_stable":s["risk_count"]==84 and s["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_target_erp_release_promotion_rollback_synthetic_reference_evaluator_contract_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","scope":{"mode":"pure_synthetic_release_promotion_rollback_reference_evaluator","continuation_complete":False,"operational_manifest_artifact_registry_environment_or receipt_read":False},"safety":{"database_connections":0,"network_reads_or_writes":0,"runtime_manifest_artifact_registry_environment_or_receipt_reads":0,"builds_deployments_promotions_rollbacks_or health_checks_executed":0,"operational_forms_reports_queries_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"credentials_endpoints_pii_or_raw_business_values_read_or_persisted":0},"summary":s,"positive_results":pr,"negative_results":nr,"outcome_precedence":["SCHEMA_INVALID","ARTIFACT_DIGEST_INVALID","ARTIFACT_DIGEST_MISMATCH","SUPPLY_CHAIN_INVALID","TEST_EVIDENCE_INVALID","ENVIRONMENT_TOKEN_INVALID","CHANGE_WINDOW_INVALID","MIGRATION_OR_RECOVERY_INVALID","CANARY_OR_KILL_SWITCH_INVALID","REDACTION_OR_RETENTION_INVALID","BLOCKING_UNKNOWN_PRESENT","RESIDUAL_DIFFERENCE_PRESENT","HEALTH_SLO_OR_BUSINESS_INVARIANT_FAILED","UAT_ACCEPTANCE_MISSING","PRODUCTION_APPROVAL_MISSING","INDEPENDENT_ROLE_SEPARATION_INVALID","FORWARD_FIX_REQUIRED_ROLLBACK_UNSAFE","ACCEPTED"],"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())]+[{"name":"reference_evaluator","path":REFERENCE.relative_to(ROOT).as_posix(),"size_bytes":REFERENCE.stat().st_size,"sha256":sha(REFERENCE)},{"name":"builder","path":"scripts/windows/build_varanegar_target_erp_release_promotion_rollback_synthetic_reference_evaluator_contract_20260829.py","size_bytes":Path(__file__).stat().st_size,"sha256":sha(Path(__file__))}],"limits":["Only synthetic fixed hashes booleans and counts were evaluated; no runtime release evidence was read.","The reference evaluator is not a deployment promotion rollback health or incident implementation.","Operational promotion and rollback remain blocked pending authenticated current independent receipts."]}
 a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(s,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
