"""Build additive Master Data evidence and risk traceability."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S={"envelope":"artifacts/varanegar_analysis/varanegar_master_data_outcome_envelope_20260829.json","readiness":"artifacts/varanegar_analysis/varanegar_master_data_readiness_delta_20260829.json","golden":"artifacts/varanegar_analysis/varanegar_master_data_golden_uat_cases_20260829.json","playbook":"artifacts/varanegar_analysis/varanegar_master_data_expert_playbook_20260829.json","path":"artifacts/varanegar_analysis/ui/varanegar_distribution_path_diagnostic_contract_20260827.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_master_data_expert_playbook_checkpoint_20260829.json"}
E=["MD-E-01-version-crosswalk-merge-envelope","MD-E-02-readiness-delta","MD-E-03-golden-uat-delta","MD-E-04-expert-playbook","MD-E-05-static-master-route-boundary"]
REQ=[("MD-RQ-01","versioned typed master aggregates and expected-version concurrency"),("MD-RQ-02","structured child-set ownership for barcode package supplier batch DC contact and accounting relations"),("MD-RQ-03","typed customer supplier personnel and subscriber roles with PII minimization"),("MD-RQ-04","weak/sentinel duplicate candidates quarantine without automatic merge"),("MD-RQ-05","source-system entity and mode-aware versioned crosswalk namespaces"),("MD-RQ-06","independently approved reversible merge with full reference reconciliation"),("MD-RQ-07","retirement instead of destructive delete when references exist"),("MD-RQ-08","atomic aggregate child redirect audit and outbox receipt"),("MD-RQ-09","immutable read-back and original receipt before retry"),("MD-RQ-10","bounded scoped read models and opaque search/audit values")]
MODULES=["master_data","identity_authorization","organization_context","pricing_rules","sales","inventory","distribution","integration_migration"]
RISKS=["R-002","R-004","R-005","R-006","R-007","R-008","R-010","R-011","R-037","R-038"]
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};known={x["id"] for x in d["risk"]["risks"]};ml=[{"evidence":e,"module":m,"relationship":"MASTER_DATA_DESIGN_EVIDENCE"} for e in E for m in MODULES];rl=[{"evidence":e,"risk":r,"relationship":"MITIGATION_DESIGN_NOT_CLOSURE"} for e in E for r in RISKS];req=[{"id":i,"requirement":text,"status":"DESIGNED_NOT_RUNTIME_PROVEN","evidence":E} for i,text in REQ]
 summary={"master_data_evidence_count":len(E),"requirement_contract_delta_count":len(req),"module_evidence_link_count":len(ml),"risk_evidence_link_count":len(rl),"unique_linked_risk_count":len(RISKS),"base_risk_count":d["risk"]["summary"]["risk_count"],"base_mapped_risk_assignment_count":d["trace"]["summary"]["mapped_risk_assignment_count"],"new_risk_count":0,"runtime_readiness_promotions":0};checks={"sources_pass":all(v["validation"]=="PASS" for v in d.values()),"five_ten":len(E)==5 and len(req)==10,"links":len(ml)==40 and len(rl)==50 and len(RISKS)==10,"risks_exist":set(RISKS)<=known,"scope":d["envelope"]["summary"]["command_contract_count"]==10 and d["golden"]["summary"]["combined_master_data_acceptance_design_count"]==149 and d["playbook"]["summary"]["playbook_count"]==7,"path_boundary_pinned":d["path"]["summary"]["distribution_count"]==26086 and d["path"]["summary"]["legacy_path_master_row_count"]==0,"base_stable":summary["base_risk_count"]==84 and summary["base_mapped_risk_assignment_count"]==343,"no_promotion":summary["new_risk_count"]==summary["runtime_readiness_promotions"]==0};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_master_data_traceability_delta_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","safety":{"mode":"OFFLINE_EVIDENCE_SYNTHESIS","database_connections":0,"network_reads_or_writes":0,"master_data_commands_or_forms_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"pii_barcode_contact_or_raw_master_values_read_or_persisted":0},"summary":summary,"policy":{"relationship":"ADDITIVE_EVIDENCE_DELTA_ONLY","base_registers_unchanged":True,"no_risk_closure_or_runtime_promotion":True},"evidence":E,"requirements":req,"module_links":ml,"risk_links":rl,"linked_existing_risks":RISKS,"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"confidence":{"design_trace":"HIGH","runtime_master_crosswalk_and_merge_parity":"UNPROVEN"},"limits":["Risk links do not close risks.","The 84-risk and 343-assignment base registers remain unchanged.","No runtime master, merge or incident result is claimed."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(summary,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
