"""Execute deterministic synthetic integration-message safety vectors."""
from __future__ import annotations
import argparse,copy,hashlib,importlib.util,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];REFERENCE=ROOT/"scripts/windows/varanegar_integration_message_reference.py"
S={"integration_contract":"artifacts/varanegar_analysis/varanegar_target_erp_integration_webhook_message_authenticity_replay_deadletter_contract_20260829.json","integration_checkpoint":"artifacts/varanegar_analysis/varanegar_target_erp_integration_webhook_message_authenticity_replay_deadletter_checkpoint_20260829.json","idempotency":"artifacts/varanegar_analysis/varanegar_target_erp_command_idempotency_outbox_inbox_convergence_contract_20260829.json","authorization":"artifacts/varanegar_analysis/varanegar_target_erp_command_authorization_scope_decision_trace_contract_20260829.json","capacity":"artifacts/varanegar_analysis/varanegar_target_erp_capacity_timeout_backpressure_degradation_contract_20260829.json","evidence":"artifacts/varanegar_analysis/varanegar_target_erp_evidence_logging_redaction_retention_contract_20260829.json","tests":"artifacts/varanegar_analysis/varanegar_25h_final_test_result_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def module():
 s=importlib.util.spec_from_file_location("integration_ref",REFERENCE);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return m
def main():
 p=argparse.ArgumentParser();p.add_argument("--output",required=True,type=Path);a=p.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};m=module();base=m.baseline()
 def changed(**kw):e=copy.deepcopy(base);e.update(kw);return e
 positive=[
  ("POS-INBOUND",base,"INBOUND_ACCEPTED_AUTHENTIC_SCOPED_AND_FRESH"),("POS-REPLAY",changed(inbox_dedup_status="REPLAY_MATCH"),"INBOUND_IDEMPOTENT_REPLAY_EXISTING_RESULT"),
  ("POS-ACK",changed(delivery_state="OUTBOUND_ACK"),"OUTBOUND_ACKNOWLEDGED_AND_RECONCILED"),("POS-UNKNOWN",changed(delivery_state="OUTBOUND_UNKNOWN"),"OUTBOUND_UNKNOWN_RECONCILIATION_REQUIRED"),
  ("POS-RETRY",changed(delivery_state="OUTBOUND_RETRY"),"RETRY_ACCEPTED_IDEMPOTENT_AND_BOUNDED"),("POS-POISON",changed(delivery_state="POISON",quarantined=True),"MESSAGE_QUARANTINED_POISON_OR_POLICY"),
  ("POS-DLQ",changed(delivery_state="DEADLETTER",quarantined=True),"DEADLETTER_ACCEPTED_ENCRYPTED_AND_RETAINED"),("POS-REDRIVE",changed(delivery_state="REDRIVE"),"REDRIVE_ACCEPTED_SCOPED_IDEMPOTENT_AND_CAPPED"),
 ]
 negative=[
  ("NEG-EXTRA",dict(base,extra=True),"SCHEMA_INVALID"),("NEG-TRANSPORT",changed(transport_current=False),"MESSAGE_REJECTED_TRANSPORT"),
  ("NEG-SIGNATURE",changed(signature_valid=False),"MESSAGE_REJECTED_SIGNATURE_OR_KEY"),("NEG-KEY",changed(key_current=False),"MESSAGE_REJECTED_SIGNATURE_OR_KEY"),
  ("NEG-DIGEST",changed(canonical_digest_match=False),"MESSAGE_REJECTED_CANONICAL_DIGEST"),("NEG-SCHEMA",changed(schema_compatible=False),"MESSAGE_REJECTED_SCHEMA_COMPATIBILITY"),
  ("NEG-SCOPE",changed(scope_current=False),"MESSAGE_REJECTED_TENANT_ENVIRONMENT_OR_AUDIENCE_SCOPE"),("NEG-TIME",changed(timestamp_fresh=False),"MESSAGE_REJECTED_TIMESTAMP_NONCE_OR_REPLAY"),
  ("NEG-NONCE",changed(nonce_unique=False),"MESSAGE_REJECTED_TIMESTAMP_NONCE_OR_REPLAY"),("NEG-ID",changed(message_id_consistent=False),"MESSAGE_REJECTED_MESSAGE_ID_FINGERPRINT_CONFLICT"),
  ("NEG-DEDUP",changed(inbox_dedup_status="CONFLICT"),"MESSAGE_REJECTED_MESSAGE_ID_FINGERPRINT_CONFLICT"),("NEG-ORDER",changed(ordering_current=False),"MESSAGE_REJECTED_ORDERING_OR_SEQUENCE"),
  ("NEG-UNKNOWN",changed(blocking_unknown=True),"MANUAL_REVIEW_REQUIRED_BLOCKING_UNKNOWN"),("NEG-PAYLOAD",changed(payload_policy_current=False),"MESSAGE_REJECTED_PAYLOAD_POLICY"),
  ("NEG-RETRY-IDEMPOTENCY",changed(delivery_state="OUTBOUND_RETRY",idempotent_retry_current=False),"RETRY_REJECTED_IDEMPOTENCY_OR_BUDGET"),("NEG-RETRY-BUDGET",changed(delivery_state="OUTBOUND_RETRY",retry_budget_current=False),"RETRY_REJECTED_IDEMPOTENCY_OR_BUDGET"),
  ("NEG-POISON",changed(delivery_state="POISON",quarantined=False),"POISON_MESSAGE_REJECTED_NOT_QUARANTINED"),("NEG-DLQ-ENCRYPTION",changed(delivery_state="DEADLETTER",quarantined=True,deadletter_encrypted=False),"DEADLETTER_REJECTED_QUARANTINE_OR_ENCRYPTION"),
  ("NEG-REDRIVE-AUTH",changed(delivery_state="REDRIVE",redrive_authorized=False),"REDRIVE_REJECTED_AUTHORIZATION_SCOPE_OR_LOOP"),("NEG-REDRIVE-CAP",changed(delivery_state="REDRIVE",redrive_idempotent_capped=False),"REDRIVE_REJECTED_AUTHORIZATION_SCOPE_OR_LOOP"),
  ("NEG-REDRIVE-LOOP",changed(delivery_state="REDRIVE",loop_guard_current=False),"REDRIVE_REJECTED_AUTHORIZATION_SCOPE_OR_LOOP"),
 ]
 def run(vs):
  out=[]
  for i,e,x in vs:
   actual=m.evaluate(e);out.append({"vector_id":i,"expected":x,"actual":actual,"status":"PASS" if actual==x else "FAIL"})
  return out
 pr=run(positive);nr=run(negative);allr=pr+nr;official=d["tests"];cs=d["integration_contract"]["summary"]
 s={"reference_evaluator_implementation_count":1,"positive_vector_count":len(pr),"positive_pass_count":sum(x["status"]=="PASS" for x in pr),"negative_vector_count":len(nr),"negative_pass_count":sum(x["status"]=="PASS" for x in nr),"total_vector_count":len(allr),"total_pass_count":sum(x["status"]=="PASS" for x in allr),"distinct_typed_outcome_count":len({x["actual"] for x in allr}),"integration_gate_count":cs["gate_count"],"integration_module_gate_assignment_count":cs["module_gate_assignment_count"],"operational_transport_broker_signature_or_message_implementation_count":0,"operational_endpoint_key_message_payload_or_deadletter_read_count":0,"message_send_receive_retry_quarantine_or_redrive_run_count":0,"accepted_operational_receipt_count":0,"command_ready_module_count":0,"pilot_ready_module_count":0,"design_lower_bound_before_reference_evaluator":1404,"design_lower_bound_after_reference_evaluator":1404,"official_test_file_count":official["runner"]["test_file_count"],"official_passed_test_count":official["runner"]["passed_test_count"],"risk_count":d["risk"]["summary"]["risk_count"],"mapped_risk_assignment_count":d["trace"]["summary"]["mapped_risk_assignment_count"],"new_risk_count":0}
 checks={"sources_pass":all(d[k].get("validation")=="PASS" for k in ("integration_contract","integration_checkpoint","idempotency","authorization","capacity","evidence","tests")),"positive_8_of_8":s["positive_vector_count"]==s["positive_pass_count"]==8,"negative_21_of_21":s["negative_vector_count"]==s["negative_pass_count"]==21,"total_29_of_29":s["total_vector_count"]==s["total_pass_count"]==29,"distinct_outcomes_at_least_18":s["distinct_typed_outcome_count"]>=18,"coverage_24_336":(s["integration_gate_count"],s["integration_module_gate_assignment_count"])==(24,336),"operational_and_readiness_zero":all(s[k]==0 for k in ("operational_transport_broker_signature_or_message_implementation_count","operational_endpoint_key_message_payload_or_deadletter_read_count","message_send_receive_retry_quarantine_or_redrive_run_count","accepted_operational_receipt_count","command_ready_module_count","pilot_ready_module_count")),"non_additive_1404":s["design_lower_bound_before_reference_evaluator"]==s["design_lower_bound_after_reference_evaluator"]==1404,"official_tests_pass":official["validation"]=="PASS" and official["runner"]["bootstrap_excluded_test_file_count"]==0,"base_stable":s["risk_count"]==84 and s["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_target_erp_integration_message_synthetic_reference_evaluator_contract_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","scope":{"mode":"pure_synthetic_integration_message_reference_evaluator","continuation_complete":False,"operational_endpoint_key_message_payload_or_deadletter_read":False},"safety":{"database_connections":0,"network_reads_or_writes":0,"operational_endpoint_certificate_key_message_payload_or_deadletter_reads":0,"message_send_receive_ack_retry_quarantine_or_redrive_actions_executed":0,"operational_forms_reports_queries_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"credentials_certificates_keys_tokens_pii_or_raw_business_values_read_or_persisted":0},"summary":s,"positive_results":pr,"negative_results":nr,"outcome_precedence":["SCHEMA","TRANSPORT","SIGNATURE_KEY","CANONICAL_DIGEST","SCHEMA_COMPATIBILITY","SCOPE","TIMESTAMP_NONCE_REPLAY","MESSAGE_ID_DEDUP","ORDERING","BLOCKING_UNKNOWN","PAYLOAD_POLICY","DELIVERY_STATE","RETRY_UNKNOWN","POISON_DEADLETTER","REDRIVE","ACCEPTED"],"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())]+[{"name":"reference_evaluator","path":REFERENCE.relative_to(ROOT).as_posix(),"size_bytes":REFERENCE.stat().st_size,"sha256":sha(REFERENCE)},{"name":"builder","path":"scripts/windows/build_varanegar_target_erp_integration_message_synthetic_reference_evaluator_contract_20260829.py","size_bytes":Path(__file__).stat().st_size,"sha256":sha(Path(__file__))}],"limits":["Only fixed synthetic booleans states and identifiers were evaluated.","The evaluator is not a transport broker signature verifier endpoint quarantine store or redrive service.","Operational message delivery redrive and readiness remain blocked pending isolated provider receipts and owner approval."]}
 a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(s,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
