"""Build provider-neutral Platform release, recovery and job outcome contracts."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S={"blueprint":"artifacts/varanegar_analysis/ui/negin_personal_erp_blueprint_20260827.json","stack":"artifacts/varanegar_analysis/ui/negin_erp_stack_recovery_decision_input_20260827.json","deployment":"artifacts/varanegar_analysis/ui/varanegar_deployment_root_reference_scan_20260827.json","orchestrator":"artifacts/varanegar_analysis/ui/varanegar_orchestrator_command_contracts_20260827.json","ledger":"artifacts/varanegar_analysis/varanegar_command_readiness_ledger_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_master_data_traceability_delta_checkpoint_20260829.json"}
REQ=["command_id","payload_hash","correlation_id","environment","expected_control_version","release_or_job_reference_hash","artifact_manifest_hash","policy_version","approval_receipt_hash","recovery_tier_id","requested_by_context","reason_code","evidence_set_hash"]
RESP=["outcome_code","command_id","control_version","decision_or_execution_receipt_id","artifact_manifest_hash","audit_event_id","outbox_event_id","reconciliation_status","retryable","readback_required","external_effect_status"]
OUT=["REJECTED_NO_EFFECT","APPROVED_NO_EXTERNAL_EFFECT","COMMITTED_CONTROL_PLANE_ONLY","EXTERNAL_EFFECT_CONFIRMED","FAILED_RETRYABLE","FAILED_FINAL","UNKNOWN_EXTERNAL_EFFECT_REQUIRES_READBACK","ROLLED_BACK_BY_NEW_COMMAND"]
C=[("platform.approve","approval","approval is a versioned decision and never proof that deployment occurred"),("platform.reject","approval","rejection is immutable and cannot mutate an already published external effect"),("platform.retry_job","job","retry uses the original payload hash and first reconciles the prior job/effect receipt"),("platform.publish_release","release","publication requires signed manifest, independent approval and staged health/reconciliation receipts"),("platform.rollback_release","release","rollback is a new command to a known manifest; history is never rewritten"),("platform.attest_restore_drill","recovery_drill","attestation records independently produced restore, smoke and reconciliation evidence; it never runs a restore")]
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};pm=next(x for x in d["blueprint"]["modules"] if x["id"]=="platform");pl=next(x for x in d["ledger"]["modules"] if x["module"]=="platform")
 commands=[{"command":c,"owner":"platform","aggregate":agg,"special_rule":rule,"request_fields":REQ,"response_fields":RESP,"allowed_outcomes":OUT,"authorization":"application service rechecks environment, action, SoD, approval and resource scope deny-first","idempotency":"same CommandId and PayloadHash returns the original decision/execution receipt; conflicting hash rejects","transaction_boundary":"control record, audit and outbox are atomic; external deployment/restore/job effects use staged receipts and are never claimed by local commit alone","retry_rule":"read immutable control, job, manifest, health, reconciliation and external-effect receipts before retry","secret_policy":"only secret-reference and artifact hashes; no credential, endpoint secret, PII or raw business value","status":"TARGET_DESIGN_ONLY_NOT_IMPLEMENTED"} for c,agg,rule in C]
 summary={"command_contract_count":len(commands),"request_field_count":len(REQ),"response_field_count":len(RESP),"outcome_code_count":len(OUT),"blueprint_platform_command_count":len(pm["commands"]),"orchestrator_platform_command_count":len(pl["orchestrator_command_ids"]),"deployment_file_count":d["deployment"]["summary"]["selected_file_count"],"deployment_external_reference_count":d["deployment"]["summary"]["external_occurrence_count"],"stack_selected_count":0,"database_selected_count":0,"hosting_selected_count":0,"approved_recovery_target_count":0,"deployment_owner_selected_count":0,"runtime_external_effect_parity_proven_count":0,"implemented_command_count":0,"executed_restore_drill_count":0,"command_ready_module_count":0,"pilot_ready_module_count":0,"risk_count":84,"mapped_risk_assignment_count":343,"new_risk_count":0}
 checks={"sources_pass":d["stack"]["validation"]==d["deployment"]["validation"]==d["orchestrator"]["validation"]==d["ledger"]["validation"]==d["risk"]["validation"]==d["trace"]["validation"]==d["previous"]["validation"]=="PASS","six_commands":len(commands)==len({x["command"] for x in commands})==6,"envelope":len(REQ)==13 and len(RESP)==11 and len(OUT)==8,"blueprint_anchor":pm["commands"]==["approve","reject","retry_job"] and summary["orchestrator_platform_command_count"]==0,"deployment_anchor":summary["deployment_file_count"]==853 and summary["deployment_external_reference_count"]==0,"decisions_open":d["stack"]["decision_status"]=="NEEDS_USER_DECISION_NOT_AN_APPROVED_ADR" and summary["stack_selected_count"]==summary["database_selected_count"]==summary["hosting_selected_count"]==summary["approved_recovery_target_count"]==summary["deployment_owner_selected_count"]==0,"external_boundary":all("external" in x["transaction_boundary"] for x in commands),"runtime_zero":summary["runtime_external_effect_parity_proven_count"]==summary["implemented_command_count"]==summary["executed_restore_drill_count"]==summary["command_ready_module_count"]==summary["pilot_ready_module_count"]==0,"base_stable":d["risk"]["summary"]["risk_count"]==84 and d["trace"]["summary"]["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_platform_outcome_envelope_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","safety":{"mode":"OFFLINE_PROVIDER_NEUTRAL_DESIGN","database_connections":0,"network_reads_or_writes":0,"deployments_jobs_restores_failovers_or_rollbacks_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"credentials_endpoints_pii_or_raw_business_values_read_or_persisted":0},"summary":summary,"decision_boundary":{"status":"UNSELECTED_REQUIRES_USER_AND_OWNER_DECISION","open":["long-term support/deployment owner","SQL Server or PostgreSQL","Windows host/server or Linux VM/container","approved RPO/RTO and support window","capacity/concurrency target","first-release offline requirement"],"proposals_are_not_approvals":True},"commands":commands,"checks":checks,"failed_checks":failed,"risk_links":["R-001","R-004","R-006","R-007","R-019","R-020","R-026","R-056","R-057","R-062"],"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"confidence":{"provider_neutral_control_contract":"HIGH","selected_stack_recovery_and_runtime_parity":"UNPROVEN"},"limits":["No technology, database, hosting, recovery tier or deployment owner is selected.","No deployment, job retry, restore, failover or rollback was executed.","A control-plane commit never proves an external effect."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(summary,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
