"""Build configuration version, precedence, secret and rollout outcome contracts."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S={"precedence":"artifacts/varanegar_analysis/domains/configuration_precedence_boundary_20260829.json","ngt_runtime":"artifacts/varanegar_analysis/domains/ngt_configuration_runtime_boundary_20260829.json","policy_snapshot":"artifacts/varanegar_analysis/domains/order_sale_policy_config_snapshot_20260829.json","policy_runtime":"artifacts/varanegar_analysis/domains/order_sale_policy_flag_runtime_20260829.json","policy_sql":"artifacts/varanegar_analysis/domains/order_sale_policy_flag_sql_20260829.json","navigation":"artifacts/varanegar_analysis/ui/varanegar_system_configuration_navigation_contract_20260827.json","legacy":"artifacts/varanegar_analysis/domains/configuration_and_rule_flags_20260826.json","targets":"artifacts/varanegar_analysis/ui/varanegar_extension_target_contracts_20260827.json","golden":"artifacts/varanegar_analysis/ui/varanegar_extension_golden_cases_20260827.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_integration_migration_traceability_delta_checkpoint_20260829.json"}
REQUEST=["command_id","payload_hash","correlation_id","configuration_family","aggregate_id","expected_version","actor_scope","organization_scope","effective_window","schema_version","public_value_hash","secret_reference_hash","rollout_plan_hash"]
RESPONSE=["outcome_code","command_id","aggregate_id","new_version","effective_pointer","resolution_trace_hash","audit_event_id","outbox_event_id","consumer_ack_summary","rollback_version","retryable"]
OUTCOMES=["REJECTED_NO_EFFECT","COMMITTED_DRAFT","PUBLISHED_ACTIVE","PUBLISHED_PARTIAL_ACK","ROLLED_FORWARD_TO_PRIOR_CONTENT","UNKNOWN_REQUIRES_READBACK"]
CONTRACTS=[
 {"command":"configuration.publish_general_version","owner":"configuration","aggregate":"general_configuration","anchor":"FormGeneralConfig.SaveCommand and target extension contract","special_rule":"typed allowlisted keys only; effective value includes a deterministic resolution trace"},
 {"command":"configuration.publish_web_service_version","owner":"configuration","aggregate":"web_service_configuration","anchor":"FormWebServiceConfig.SaveCommand and target extension contract","special_rule":"public endpoint policy and vault secret reference are separate; secret values never enter payload, result or audit"},
 {"command":"configuration.save_accounting_article_template_version","owner":"accounting","aggregate":"accounting_article_template","anchor":"FormArticleTemplate Save/Delete and target extension contract","special_rule":"used historical templates are immutable; retirement is a versioned transition"},
 {"command":"configuration.publish_scoped_override_version","owner":"configuration","aggregate":"scoped_configuration_override","anchor":"General/Server/App/Device/DC tables and NGT runtime selectors","special_rule":"scope lattice and tie breaker are explicit; TOP 1 without order is forbidden"},
 {"command":"configuration.rollback_by_new_version","owner":"configuration","aggregate":"configuration_rollout","anchor":"target version and consumer acknowledgement design","special_rule":"rollback copies approved prior content into a new version; history and failed acknowledgements remain immutable"},
]
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 p=argparse.ArgumentParser();p.add_argument("--output",required=True,type=Path);a=p.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};valid=["precedence","ngt_runtime","policy_snapshot","policy_runtime","policy_sql","navigation","targets","golden","risk","trace","previous"];target=[x for x in d["targets"]["commands"] if x["command"] in {"configuration.publish_general_version","configuration.publish_web_service_version","configuration.save_accounting_article_template_version"}];cases=[x for x in d["golden"]["cases"] if str(x.get("surface","")).startswith("configuration.")];commits=sum(any(y["called_member"]=="Commit" for y in x["source_evidence"]["source_direct_data_access_calls"]) for x in target)
 commands=[{**x,"request_fields":REQUEST,"response_fields":RESPONSE,"allowed_outcomes":OUTCOMES,"authorization":"application service rechecks family, publish/retire and scope capability deny-first","idempotency":"same CommandId and PayloadHash returns original version/rollout receipt; conflicting hash rejects","transaction_owner":"one application service owns version append, effective pointer, audit and outbox atomically","rollout_rule":"consumer delivery is asynchronous; activation state preserves per-consumer acknowledgement and unknown outcomes","retry_rule":"read version, pointer, audit, outbox and consumer acknowledgements before retry","runtime_effect_parity":"UNPROVEN","status":"TARGET_DESIGN_ONLY_NOT_IMPLEMENTED"} for x in CONTRACTS]
 s0=d["precedence"]["summary"];summary={"command_contract_count":len(commands),"request_field_count":len(REQUEST),"response_field_count":len(RESPONSE),"outcome_code_count":len(OUTCOMES),"existing_reused_case_count":len(cases),"existing_command_contract_count":len(target),"legacy_direct_commit_anchor_count":commits,"multi_table_resolver_module_count":s0["multi_configuration_table_resolver_module_count"],"top_one_without_order_resolver_count":s0["resolver_with_top_one_without_order_count"],"app_device_current_mismatch_count":s0["app_device_same_name_current_mismatch_count"],"active_reference_to_removed_device_setting_count":s0["active_child_to_removed_device_setting_reference_count"],"delivery_semantic_mismatch_count":s0["configuration_delivery_semantic_mismatch_count"],"runtime_selection_method_count":d["ngt_runtime"]["summary"]["runtime_selection_method_count"],"scope_aware_runtime_selection_method_count":d["ngt_runtime"]["summary"]["scope_aware_runtime_selection_method_count"],"runtime_is_removed_signal_method_count":d["ngt_runtime"]["summary"]["runtime_selection_method_with_is_removed_signal_count"],"policy_flag_count":d["policy_sql"]["summary"]["selected_policy_flag_count"],"policy_flag_without_runtime_reference_count":d["policy_runtime"]["summary"]["flag_without_runtime_member_reference_count"],"null_policy_cell_count":d["policy_snapshot"]["summary"]["null_policy_cell_count"],"general_config_key_count":d["navigation"]["summary"]["general_config_key_count"],"server_config_key_count":d["navigation"]["summary"]["server_config_key_count"],"runtime_effective_value_or_precedence_proven_count":d["navigation"]["summary"]["runtime_effective_value_or_precedence_proven_count"],"runtime_effect_parity_proven_count":0,"implemented_command_count":0,"owner_approved_count":0,"command_ready_module_count":0,"pilot_ready_module_count":0,"risk_count":84,"mapped_risk_assignment_count":343,"new_risk_count":0}
 checks={"validated_sources_pass":all(d[k]["validation"]=="PASS" for k in valid),"legacy_structural_input":d["legacy"].get("domain")=="configuration_and_rule_flags","five_commands":len(commands)==5 and len({x["command"] for x in commands})==5,"envelope_complete":len(REQUEST)==13 and len(RESPONSE)==11 and len(OUTCOMES)==6,"reuse_54":len(cases)==54 and len(target)==3,"commit_anchors":commits==2,"precedence_gaps":summary["multi_table_resolver_module_count"]==97 and summary["top_one_without_order_resolver_count"]==14 and summary["app_device_current_mismatch_count"]==18,"removed_and_delivery_gaps":summary["active_reference_to_removed_device_setting_count"]==51 and summary["delivery_semantic_mismatch_count"]==7,"runtime_selection":summary["runtime_selection_method_count"]==92 and summary["scope_aware_runtime_selection_method_count"]==72 and summary["runtime_is_removed_signal_method_count"]==13,"policy_gaps":summary["policy_flag_count"]==19 and summary["policy_flag_without_runtime_reference_count"]==2 and summary["null_policy_cell_count"]==5,"no_false_precedence_proof":summary["runtime_effective_value_or_precedence_proven_count"]==0,"secret_and_rollback":all(word in commands[1]["special_rule"] for word in ["vault","secret"]) and commands[-1]["special_rule"].startswith("rollback copies"),"runtime_zero":summary["runtime_effect_parity_proven_count"]==summary["implemented_command_count"]==summary["owner_approved_count"]==summary["command_ready_module_count"]==summary["pilot_ready_module_count"]==0,"base_stable":d["risk"]["summary"]["risk_count"]==84 and d["trace"]["summary"]["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_configuration_outcome_envelope_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","safety":{"mode":"OFFLINE_STATIC_AND_CONTRACT_SYNTHESIS","database_connections":0,"network_reads_or_writes":0,"configuration_commands_or_forms_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"secret_or_business_values_read_or_persisted":0},"summary":summary,"lifecycle":["DRAFT","VALIDATED","PUBLISHED","PARTIALLY_ACKNOWLEDGED","SUPERSEDED","RETIRED"],"resolution_contract":{"ordered_dimensions":["configuration_family","organization/DC/device/application scope specificity","effective window","published version","stable version id tie breaker"],"null_semantics":"typed per key: INHERIT, EXPLICIT_NULL or VALUE; never silently coalesce unknown null","removed_semantics":"removed candidate is excluded but active references quarantine until an approved replacement exists","required_trace":["candidate version ids","scope match decisions","null/removed decisions","winner","policy/schema hash"]},"commands":commands,"checks":checks,"failed_checks":failed,"risk_links":["R-002","R-005","R-006","R-007","R-008","R-023","R-031","R-034","R-036","R-043"],"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"confidence":{"static_precedence_and_consumer_boundaries":"HIGH","target_contract_design":"HIGH","runtime_effective_value_and_rollout_parity":"UNPROVEN"},"limits":["No configuration form, command, consumer refresh or endpoint test was executed.","No configuration or secret value is persisted; only aggregate counts and contract rules are used.","Runtime precedence and consumer acknowledgement parity require isolated target tests."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(summary,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
