"""Map distribution continuation evidence to existing modules, requirements and risks."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S={"envelope":"artifacts/varanegar_analysis/varanegar_distribution_command_outcome_envelope_20260829.json","readiness":"artifacts/varanegar_analysis/varanegar_distribution_command_readiness_delta_20260829.json","golden":"artifacts/varanegar_analysis/varanegar_distribution_golden_uat_cases_20260829.json","playbook":"artifacts/varanegar_analysis/varanegar_distribution_expert_playbook_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_distribution_expert_playbook_checkpoint_20260829.json"}
M=[
{"id":"DS-E24-01","source":"envelope","modules":["distribution","inventory","sales","platform","integration_migration"],"requirements":["distribution.command.outcome_retry_envelope","distribution.issue_exit.late_cardex_effect","distribution.remove_exit.graph_atomicity","distribution.merge.transaction_owner"],"risks":["R-005","R-006","R-007","R-023","R-034","R-036","R-043"]},
{"id":"DS-E24-02","source":"readiness","modules":["distribution","platform","integration_migration"],"requirements":["distribution.command.readiness_design"],"risks":["R-006","R-007","R-026"]},
{"id":"DS-E24-03","source":"golden","modules":["distribution","inventory","sales","platform","integration_migration"],"requirements":["distribution.synthetic_acceptance_28"],"risks":["R-002","R-005","R-006","R-007","R-023","R-034","R-036","R-043"]},
{"id":"DS-E24-04","source":"playbook","modules":["distribution","inventory","sales","platform","integration_migration"],"requirements":["distribution.incident.playbook"],"risks":["R-005","R-006","R-007","R-023","R-034","R-036","R-043"]},
]
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};risks={x["id"] for x in d["risk"]["risks"]};mods={x["module"]:{r["id"] for r in x["risks"]} for x in d["trace"]["modules"]};reqs=sorted({r for x in M for r in x["requirements"]});linked=sorted({r for x in M for r in x["risks"]});s={"distribution_evidence_count":len(M),"requirement_contract_delta_count":len(reqs),"module_evidence_link_count":sum(len(x["modules"]) for x in M),"risk_evidence_link_count":sum(len(x["risks"]) for x in M),"unique_linked_risk_count":len(linked),"base_risk_count":84,"base_mapped_risk_assignment_count":343,"new_risk_count":0,"runtime_readiness_promotions":0}
 checks={"sources_pass":all(x["validation"]=="PASS" for x in d.values()),"four_evidence":s["distribution_evidence_count"]==4,"seven_requirements":s["requirement_contract_delta_count"]==7,"link_counts":s["module_evidence_link_count"]==18 and s["risk_evidence_link_count"]==25,"nine_existing":s["unique_linked_risk_count"]==9 and set(linked)<=risks,"module_consistent":all(any(r in mods[m] for m in x["modules"]) for x in M for r in x["risks"]),"base_stable":d["risk"]["summary"]["risk_count"]==84 and d["trace"]["summary"]["mapped_risk_assignment_count"]==343,"runtime_zero":d["readiness"]["summary"]["command_ready_module_count"]==0 and d["golden"]["summary"]["executed_case_count"]==0 and d["playbook"]["summary"]["runtime_incidents_diagnosed_count"]==0};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_distribution_traceability_delta_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","safety":{"mode":"OFFLINE_EVIDENCE_SYNTHESIS","database_connections":0,"commands_forms_reports_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"sensitive_values_persisted":0},"summary":s,"policy":{"relationship":"ADDITIVE_EVIDENCE_DELTA_ONLY","base_registers_unchanged":True,"no_risk_closure_or_runtime_promotion":True},"mappings":M,"requirements":reqs,"linked_existing_risks":linked,"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"confidence":{"design_trace":"HIGH","runtime_effect_parity":"UNPROVEN"},"limits":["Risk links do not close risks.","The 84-risk and 343-assignment base registers remain unchanged.","No runtime UAT or diagnosis is claimed."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(s,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
