"""Chain the 88 report Golden fixture designs."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S={"fixtures":"artifacts/varanegar_analysis/varanegar_report_golden_fixture_design_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_accounting_golden_uat_checkpoint_20260829.json","builder":"scripts/windows/build_varanegar_report_golden_fixture_design_20260829.py","checkpoint_builder":"scripts/windows/build_varanegar_report_golden_fixture_checkpoint_20260829.py","test":"tests/test_varanegar_report_golden_fixture_design.py","doc":"docs/varanegar_reconstruction/REPORT_GOLDEN_FIXTURE_DESIGN_20260829_FA.md"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(paths[k]) for k in ("fixtures","previous")};s=d["fixtures"]["summary"];checks={"sources_pass":d["fixtures"]["validation"]==d["previous"]["validation"]=="PASS","twenty_surfaces":s["report_surface_count"]==20,"eighty_base":s["base_case_count"]==80,"eight_command_cases":s["command_partial_failure_case_count"]==8,"eighty_eight_total":s["case_count"]==88,"runtime_parity_owner_zero":s["executed_case_count"]==s["result_parity_proven_surface_count"]==s["owner_approved_surface_count"]==0,"risk_stable":s["risk_count"]==84 and s["new_risk_count"]==0,"zero_execution":set(v for k,v in d["fixtures"]["safety"].items() if k!="mode")=={0}};failed=sorted(k for k,v in checks.items() if not v);out={"artifact":"varanegar_report_golden_fixture_checkpoint_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","previous_checkpoint":{"path":S["previous"],"sha256":sha(paths["previous"])},"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"safety":{"commands_forms_queries_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"database_connections":0,"data_mutations":0,"sensitive_values_persisted":0}};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
