"""Design isolated synthetic Golden/UAT cases for the corrected accounting command inventory."""
from __future__ import annotations
import argparse,hashlib,json
from collections import Counter
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S={"inventory":"artifacts/varanegar_analysis/varanegar_accounting_command_inventory_correction_20260829.json","readiness":"artifacts/varanegar_analysis/varanegar_command_readiness_delta_20260829.json","golden_base":"artifacts/varanegar_analysis/varanegar_golden_uat_evidence_ledger_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_command_readiness_delta_checkpoint_20260829.json"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
BASE=[("authorization","auth_denied","actor lacks command capability","AUTH_DENIED",["zero business writes","sanitized denial audit"]),("concurrency","stale_version","expected version differs","STALE_STATE",["zero writes","current version returned"]),("idempotency","duplicate_command_id","same command id after response loss","REPLAY_PRIOR_RESULT",["one logical effect","same outcome envelope"]),("failure_injection","fault_after_first_write","isolated fault after first durable statement","ROLLED_BACK_OR_TYPED_AMBIGUOUS",["no unexplained partial effect","read-back resolves outcome"]),("scope","scope_denied","aggregate outside fiscal/DC/resource scope","SCOPE_DENIED",["zero writes"]),("success","valid_transition","valid synthetic preconditions","COMMITTED",["one version advance","audit/outbox correlated"])]
SPECIAL={"accounting.external_voucher.generate":("policy","policy_changed_after_preflight","policy version changes between preflight and mutation","POLICY_VERSION_CONFLICT",["zero unversioned issue"]),"accounting.external_voucher.confirm":("workflow","already_confirmed","header already confirmed","ALREADY_APPLIED",["no duplicate history"]),"accounting.external_voucher.delete":("workflow","transferred_batch","batch already transferred","WORKFLOW_REJECTED",["zero deletion","lineage retained"]),"accounting.external_voucher.transfer":("reconciliation","business_error_after_cleanup","validation fails after SetVoucherNo cleanup","BUSINESS_ERROR_WITH_DURABLE_EFFECT",["cleanup effect captured","retry blocked pending read-back"]),"stock_voucher.confirm_or_unconfirm":("reconciliation","route_and_projection_check","route selected with cardex/on-hand projection constraint","COMMITTED_OR_VALIDATION_REJECTED",["selected route recorded","header/cardex/projection reconcile"]),"accounting.manual_voucher.save":("validation","unbalanced_or_missing_dimension","debit/credit or required ledger dimension invalid","VALIDATION_REJECTED",["zero writes","field-safe validation result"])}
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};cmds=[x["command_id"] for x in d["inventory"]["corrected_truth_table"]];cases=[]
 for cmd in cmds:
  for kind,suffix,variation,outcome,assertions in [*BASE,SPECIAL[cmd]]:
   cases.append({"case_id":f"{cmd}.{suffix}","command_id":cmd,"kind":kind,"fixture":"anonymous synthetic aggregate with no production identifier or value","input_variation":variation,"prior_state":"explicit version/state/policy snapshot in isolated target fixture","expected_outcome":outcome,"expected_assertions":assertions,"expected_side_effects":["typed outcome envelope","immutable audit correlation","outbox only when committed"],"execution_status":"DESIGNED_NOT_EXECUTED","owner_approval":"NOT_OBSERVED"})
 kinds=dict(sorted(Counter(x["kind"] for x in cases).items()));checks={"sources_pass":all(d[k]["validation"]=="PASS" for k in d),"six_corrected_commands":len(cmds)==6,"forty_two_cases":len(cases)==42,"seven_per_command":all(sum(x["command_id"]==c for x in cases)==7 for c in cmds),"manual_cancel_absent":not any("manual_voucher.cancel" in x["command_id"] for x in cases),"transfer_partial_effect_case":any(x["case_id"].endswith("business_error_after_cleanup") and x["expected_outcome"]=="BUSINESS_ERROR_WITH_DURABLE_EFFECT" for x in cases),"not_executed":all(x["execution_status"]=="DESIGNED_NOT_EXECUTED" for x in cases),"no_owner_approval":all(x["owner_approval"]=="NOT_OBSERVED" for x in cases),"risk_stable":d["risk"]["summary"]["risk_count"]==84};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_accounting_golden_uat_cases_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","safety":{"mode":"OFFLINE_SYNTHETIC_UAT_DESIGN_ONLY","database_connections":0,"commands_forms_reports_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"business_values_pii_or_raw_rules_persisted":0},"summary":{"command_count":6,"case_count":len(cases),"case_kind_counts":kinds,"executed_case_count":0,"passed_runtime_case_count":0,"owner_approved_case_count":0,"rejected_false_command_case_count":1,"risk_count":84,"new_risk_count":0},"execution_gate":{"environment":"isolated target test database only","fixtures":"synthetic and anonymous","authorization":"separate explicit approval required","source_system":"never execute mutations against Varanegar clone or production","promotion":"all cases plus reconciliation and owner acceptance must pass before command-ready"},"cases":cases,"removed_case_family":{"command_id":"accounting.manual_voucher.cancel","reason":"UI_CLOSE_ONLY_NOT_A_FINANCIAL_COMMAND","replacement":"none until a real reversal path is evidenced"},"risk_links":["R-002","R-005","R-007","R-021","R-023","R-084"],"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"confidence":{"case_design":"HIGH_FROM_STATIC_CONTRACTS","runtime_results":"NOT_EXECUTED","owner_acceptance":"NOT_OBSERVED"},"limits":["These are target-ERP UAT designs, not evidence of Varanegar or target execution.","Fault injection is permitted only in a separately approved isolated environment.","Customer-specific policy values are intentionally absent."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
