"""Build chained checkpoint for the 20-surface report closure ledger."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
S={"ledger":"artifacts/varanegar_analysis/varanegar_report_surface_closure_ledger_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_treasury_crystal_viewer_checkpoint_20260829.json","builder":"scripts/windows/build_varanegar_report_surface_closure_ledger_20260829.py","checkpoint_builder":"scripts/windows/build_varanegar_report_surface_closure_checkpoint_20260829.py","test":"tests/test_varanegar_report_surface_closure_ledger.py","doc":"docs/varanegar_reconstruction/REPORT_SURFACE_CLOSURE_LEDGER_20260829_FA.md"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(paths[k]) for k in ("ledger","previous")};c=d["ledger"];checks={"sources_pass":all(x["validation"]=="PASS" for x in d.values()),"twenty_ownership_closed":c["summary"]["report_surface_count"]==20 and c["summary"]["ownership_evidence_closed_count"]==20,"parity_zero":c["summary"]["result_parity_proven_count"]==0 and c["summary"]["owner_golden_value_count"]==0,"readiness_zero":c["summary"]["command_ready_count"]==0 and c["summary"]["implementation_ready_count"]==0 and c["summary"]["pilot_ready_count"]==0,"risk_stable":c["summary"]["risk_count"]==84,"zero_execution":set(v for k,v in c["safety"].items() if k!="mode")=={0}};failed=sorted(k for k,v in checks.items() if not v);out={"artifact":"varanegar_report_surface_closure_checkpoint_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","previous_checkpoint":{"path":S["previous"],"sha256":sha(paths["previous"])},"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"safety":{"reports_queries_templates_or_commands_executed":0,"assemblies_loaded_or_executed":0,"database_connections":0,"data_mutations":0,"sensitive_values_persisted":0}};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
