from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S={"audit":"artifacts/varanegar_analysis/varanegar_24h_continuation_consolidated_audit_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_platform_traceability_delta_checkpoint_20260829.json","builder":"scripts/windows/build_varanegar_24h_continuation_consolidated_audit_20260829.py","checkpoint_builder":"scripts/windows/build_varanegar_24h_continuation_consolidated_checkpoint_20260829.py","test":"tests/test_varanegar_24h_continuation_consolidated_audit.py","checkpoint_test":"tests/test_varanegar_24h_continuation_consolidated_checkpoint.py","doc":"docs/varanegar_reconstruction/VARANEGAR_24H_CONTINUATION_CONSOLIDATED_AUDIT_20260829_FA.md"}
def L(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def H(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();p={k:ROOT/v for k,v in S.items()};d=L(p["audit"]);prev=L(p["previous"]);s=d["summary"];checks={"sources_pass":d["validation"]==prev["validation"]=="PASS","non_final":d["scope"]["continuation_complete"] is False,"test_evidence_explicit":d["scope"]["test_evidence_status"] in {"BOOTSTRAP_SEED","FULL_CURRENT"} and s["official_passed_test_count"]>0,"coverage_14":s["module_count"]==s["outcome_retry_target_contract_module_count"]==14,"design_1229_playbook_78":s["synthetic_acceptance_design_obligation_count"]==1229 and s["continuation_playbook_count"]==78,"report_boundary":s["report_surface_count"]==20 and s["report_result_parity_proven_count"]==0,"runtime_zero":s["runtime_authorization_proven_module_count"]==s["runtime_atomicity_proven_module_count"]==s["runtime_effect_parity_proven_module_count"]==s["runtime_retry_idempotency_proven_module_count"]==s["executed_case_count"]==s["owner_approved_case_count"]==0,"chain_119_200":s["checkpoint_count_before_consolidated_checkpoint"]==119 and s["source_manifest_node_count_before_consolidated"]==200 and s["stale_checkpoint_count"]==s["stale_source_manifest_node_count"]==0,"base_stable":s["risk_count"]==84 and s["mapped_risk_assignment_count"]==343,"safety_zero":set(d["safety"].values())=={0}};failed=sorted(k for k,v in checks.items() if not v);out={"artifact":"varanegar_24h_continuation_consolidated_checkpoint_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","previous_checkpoint":{"path":S["previous"],"sha256":H(p["previous"])},"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":H(v)} for k,v in sorted(p.items())],"safety":{"database_connections":0,"operational_actions":0,"data_mutations":0,"write_access_created":0}};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
