"""Build chained checkpoint for RPT-03/RPT-04 dashboard shells."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
S={"contract":"artifacts/varanegar_analysis/domains/dashboard_shell_contract_20260829.json","boundary":"artifacts/varanegar_analysis/domains/dashboard_shell_boundary_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_stock_report_selector_checkpoint_20260829.json","extractor":"scripts/windows/extract_varanegar_dashboard_shell_boundary_20260829.py","builder":"scripts/windows/build_varanegar_dashboard_shell_contract_20260829.py","checkpoint_builder":"scripts/windows/build_varanegar_dashboard_shell_checkpoint_20260829.py","test":"tests/test_varanegar_dashboard_shell_contract.py","doc":"docs/varanegar_reconstruction/DASHBOARD_HOST_ZOOM_AND_WIDGET_PARITY_20260829_FA.md"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(paths[k]) for k in ("contract","boundary","previous")};c=d["contract"];checks={"sources_pass":all(x["validation"]=="PASS" for x in d.values()),"two_shells_zero_queries":c["summary"]["shell_count"]==2 and c["summary"]["query_owner_count"]==0,"five_widget_owners_deferred":c["summary"]["widget_count"]==5 and c["summary"]["widget_result_parity_proven_count"]==0,"shell_parity_reframed":c["summary"]["shell_independent_result_parity_applicable_count"]==0 and c["summary"]["routing_or_view_parity_contract_count"]==2,"six_golden_cases":len(c["golden_cases"])==6,"risk_stable":c["summary"]["risk_count"]==84,"zero_execution":set(v for k,v in c["safety"].items() if k!="mode")=={0}};failed=sorted(k for k,v in checks.items() if not v);out={"artifact":"varanegar_dashboard_shell_checkpoint_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","previous_checkpoint":{"path":S["previous"],"sha256":sha(paths["previous"])},"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"safety":{"dashboards_widgets_controls_or_queries_executed":0,"assemblies_loaded_or_executed":0,"database_connections":0,"data_mutations":0,"sensitive_values_persisted":0}};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
