from __future__ import annotations
import argparse,copy,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S={"base":"artifacts/varanegar_analysis/varanegar_configuration_readiness_delta_20260829.json","envelope":"artifacts/varanegar_analysis/varanegar_identity_authorization_outcome_envelope_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_identity_authorization_outcome_checkpoint_20260829.json"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};mods=copy.deepcopy(d["base"]["modules"]);x=next(v for v in mods if v["module"]=="identity_authorization");before=x["truth_table_dimensions"]["outcome_retry_idempotency"]["target_contract"];x["mapped_validated_evidence"].append({"key":"identity_authorization_outcome","path":S["envelope"],"validation":d["envelope"]["validation"]});x["truth_table_dimensions"]["outcome_retry_idempotency"]["target_contract"]=True;x["synthetic_golden_case_count"]=184;x["truth_table_dimensions"]["golden_cases"]["synthetic_design_count"]=184;x["legacy_open_blockers"].extend(["named identities and current effective grants remain intentionally unavailable","60 endpoint declarations and 38 mutating endpoint authorization decisions require code-owner disposition","admin short-circuit, owner-filter and 58 scope mismatches require target policy and isolated tests","revocation/session epoch and break-glass adapters are not implemented"])
 summary={"module_count":len(mods),"changed_module_count":1,"outcome_target_contract_module_count_before":sum(v["truth_table_dimensions"]["outcome_retry_idempotency"]["target_contract"] for v in d["base"]["modules"]),"outcome_target_contract_module_count_after":sum(v["truth_table_dimensions"]["outcome_retry_idempotency"]["target_contract"] for v in mods),"identity_command_contract_count":d["envelope"]["summary"]["command_contract_count"],"mapped_existing_uat_case_count":184,"runtime_authorization_proven_module_count":0,"runtime_retry_idempotency_proven_module_count":0,"command_ready_module_count":0,"pilot_ready_module_count":0,"risk_count":84,"mapped_risk_assignment_count":343,"new_risk_count":0};checks={"sources_pass":all(v["validation"]=="PASS" for v in d.values()),"fourteen_modules":len(mods)==14,"identity_false_to_true":before is False and x["truth_table_dimensions"]["outcome_retry_idempotency"]["target_contract"] is True,"ten_to_eleven":summary["outcome_target_contract_module_count_before"]==10 and summary["outcome_target_contract_module_count_after"]==11,"one_changed":sum(v["truth_table_dimensions"]["outcome_retry_idempotency"]["target_contract"]!=w["truth_table_dimensions"]["outcome_retry_idempotency"]["target_contract"] for v,w in zip(d["base"]["modules"],mods))==1,"scope":summary["identity_command_contract_count"]==6 and summary["mapped_existing_uat_case_count"]==184,"runtime_zero":summary["runtime_authorization_proven_module_count"]==summary["runtime_retry_idempotency_proven_module_count"]==summary["command_ready_module_count"]==summary["pilot_ready_module_count"]==0,"base_stable":d["risk"]["summary"]["risk_count"]==84 and d["trace"]["summary"]["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_identity_authorization_readiness_delta_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","safety":{"mode":"OFFLINE_DESIGN_DELTA","database_connections":0,"network_reads_or_writes":0,"identity_or_authorization_commands_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"identity_values_credentials_or_raw_grants_persisted":0},"summary":summary,"modules":mods,"promotion_boundary":{"changed":"identity_authorization outcome/retry target contract and 184 synthetic-design mappings only","unchanged":["effective grants","runtime authorization","owner-filter implementation","session revocation parity","owner approval","command readiness","pilot readiness"]},"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"confidence":{"design_delta":"HIGH","runtime_readiness":"NOT_PROVEN"},"limits":["Design coverage is not implementation readiness.","No identity, role, scope or session operation was executed.","All 184 mapped cases remain synthetic and unexecuted."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(summary,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
