"""Checkpoint the P2 assertion/effect-family gap matrix."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
S={"matrix":"artifacts/varanegar_analysis/varanegar_p2_assertion_effect_family_gap_matrix_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_p2_control_outcome_vocabulary_checkpoint_20260829.json","builder":"scripts/windows/build_varanegar_p2_assertion_effect_family_gap_matrix_20260829.py","checkpoint_builder":"scripts/windows/build_varanegar_p2_assertion_effect_family_gap_checkpoint_20260829.py","test":"tests/test_varanegar_p2_assertion_effect_family_gap_matrix.py","checkpoint_test":"tests/test_varanegar_p2_assertion_effect_family_gap_checkpoint.py","doc":"docs/varanegar_reconstruction/P2_ASSERTION_EFFECT_FAMILY_GAP_MATRIX_20260829_FA.md"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};m=load(paths["matrix"]);prev=load(paths["previous"]);s=m["summary"];checks={"sources_pass":m["validation"]==prev["validation"]=="PASS","73_12":s["candidate_case_pair_count"]==73 and s["effect_family_count"]==12,"overlap":(s["exact_family_set_pair_count"],s["nonempty_family_overlap_pair_count"],s["zero_family_overlap_pair_count"])==(0,64,9),"asymmetry":(s["newer_only_family_assignment_count"],s["baseline_only_family_assignment_count"])==(420,97),"audit_outbox":(s["newer_audit_pair_count"],s["baseline_audit_pair_count"],s["newer_outbox_pair_count"],s["baseline_outbox_pair_count"])==(73,36,73,14),"source_transaction_version":(s["newer_source_immutability_pair_count"],s["baseline_source_immutability_pair_count"],s["newer_transaction_atomicity_pair_count"],s["baseline_transaction_atomicity_pair_count"],s["newer_version_concurrency_pair_count"],s["baseline_version_concurrency_pair_count"])==(56,28,0,46,73,14),"non_additive_1404":s["accepted_family_mapping_count"]==s["accepted_case_pair_count"]==s["exact_non_duplicated_additive_count"]==0 and s["design_lower_bound_before_effect_family_matrix"]==s["design_lower_bound_after_effect_family_matrix"]==1404,"execution_readiness_zero":s["executed_case_count"]==s["owner_approved_case_count"]==s["command_ready_module_count"]==s["pilot_ready_module_count"]==0,"base_stable":s["risk_count"]==84 and s["mapped_risk_assignment_count"]==343,"safety_zero":set(m["safety"].values())=={0}};failed=sorted(k for k,v in checks.items() if not v);out={"artifact":"varanegar_p2_assertion_effect_family_gap_checkpoint_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","previous_checkpoint":{"path":S["previous"],"sha256":sha(paths["previous"])},"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"safety":{"database_connections":0,"golden_or_uat_execution":0,"data_mutations":0}};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
