"""Build a design-only observability, SLO, alert, and incident evidence contract."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
S={"blueprint":"artifacts/varanegar_analysis/ui/negin_personal_erp_blueprint_20260827.json","release":"artifacts/varanegar_analysis/varanegar_target_erp_release_promotion_change_rollback_evidence_contract_20260829.json","release_checkpoint":"artifacts/varanegar_analysis/varanegar_target_erp_release_promotion_change_rollback_evidence_checkpoint_20260829.json","redaction":"artifacts/varanegar_analysis/varanegar_target_erp_evidence_logging_redaction_retention_contract_20260829.json","authorization":"artifacts/varanegar_analysis/varanegar_target_erp_command_authorization_scope_decision_trace_contract_20260829.json","transaction":"artifacts/varanegar_analysis/varanegar_target_erp_transaction_owner_saga_compensation_contract_20260829.json","tests":"artifacts/varanegar_analysis/varanegar_25h_final_test_result_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json"}
SIGNALS=["SERVICE_AVAILABILITY","REQUEST_AND_COMMAND_LATENCY","ERROR_AND_TYPED_OUTCOME_RATE","RESOURCE_SATURATION","QUEUE_OUTBOX_INBOX_LAG","TRANSACTION_UNKNOWN_AND_PARTIAL_EFFECT","IDEMPOTENCY_CONFLICT_AND_REPLAY","AUTHORIZATION_DENY_AND_SCOPE_MISMATCH","RECONCILIATION_AND_RESULT_PARITY","BUSINESS_INVARIANT_HEALTH","DEPENDENCY_AND_INTEGRATION_HEALTH","BACKUP_RESTORE_AND_RECOVERY_FRESHNESS"]
STAGES=[("OBS-01","signal_scope_owner_and_cardinality_budget_frozen"),("OBS-02","sli_formula_grain_window_and_missing_data_semantics_approved"),("OBS-03","slo_target_error_budget_and_burn_windows_approved"),("OBS-04","redacted_metric_log_trace_and_receipt_schema_verified"),("OBS-05","technical_health_and_business_invariant_probes_separated"),("OBS-06","alert_threshold_dedup_suppression_and_route_approved"),("OBS-07","runbook_dependency_dashboard_and evidence links current"),("OBS-08","synthetic_failure_and alert-delivery rehearsal accepted"),("OBS-09","incident_severity_owner_commander_and_clock_started"),("OBS-10","containment_kill_switch_recovery_and_reconciliation_evidenced"),("OBS-11","post_recovery_slo_business_invariant_and_residual_diff_checked"),("OBS-12","independent_closure_review_followup_and_retention_accepted")]
SLI_FIELDS=["sli_id","module_id","signal_class","scope_hash","formula_version_hash","window_start","window_end","numerator_count","denominator_count","valid_sample_count","missing_sample_count","threshold_reference","typed_status","source_version_hash","redaction_policy_hash","observed_at","evidence_reference","sli_receipt_sha256"]
SLO_FIELDS=["slo_id","sli_id","module_id","objective_type","target_threshold","measurement_window","short_burn_window","long_burn_window","error_budget_policy_hash","missing_data_policy","maintenance_window_policy_hash","dependency_budget_policy_hash","owner_role_type","reviewer_role_type","effective_from","expires_at","policy_version_sha256","approval_receipt_sha256"]
ALERT_FIELDS=["alert_receipt_id","module_id","slo_id","signal_class","severity","window_start","window_end","observed_status","threshold_reference","burn_rate_status","dedup_key_sha256","suppression_policy_sha256","route_policy_sha256","runbook_reference_sha256","owner_role_type","delivery_status","acknowledged_at","redaction_attestation_sha256","typed_outcome","alert_receipt_sha256"]
INCIDENT_FIELDS=["incident_receipt_id","incident_reference_sha256","module_scope_sha256","severity","started_at","detected_at","acknowledged_at","contained_at","recovered_at","closed_at","commander_role_type","technical_owner_role_type","business_owner_role_type","trigger_alert_receipt_sha256","containment_receipt_sha256","recovery_receipt_sha256","reconciliation_receipt_sha256","health_and_slo_receipt_sha256","business_invariant_receipt_sha256","residual_difference_count","typed_outcome","incident_receipt_sha256"]
FAILURES=[("OBF-01","process_running_but_dependency_or_business_invariant_failed"),("OBF-02","missing_or_stale_telemetry_treated_as_healthy"),("OBF-03","unbounded_or_sensitive_metric_label_log_trace_or_baggage"),("OBF-04","sli_formula_grain_window_or denominator_changed_without_version"),("OBF-05","short_or_long_burn_rate_threshold_breached"),("OBF-06","alert_dropped_duplicated_suppressed_or_misrouted"),("OBF-07","runbook_owner_dependency_or kill_switch missing_or_stale"),("OBF-08","queue_lag_unknown_commit_or reconciliation_difference_unobserved"),("OBF-09","authorization_deny_or scope_mismatch_silently_discarded"),("OBF-10","incident_severity_clock_owner_or commander_missing"),("OBF-11","recovery_claimed_before health_slo_and_business_reconciliation"),("OBF-12","incident_auto_closed_when_process_restarted"),("OBF-13","severity_lowered_or residual_difference_waived_without_evidence"),("OBF-14","alert_or incident evidence expired_revoked_or_redaction_failed")]
GATES=[("OBG-01","signal_inventory_scope_and_owner_complete"),("OBG-02","sli_formula_grain_window_and_version_pinned"),("OBG-03","missing_data_and_staleness_fail_closed"),("OBG-04","slo_target_error_budget_and_burn_policy_approved"),("OBG-05","metric_log_trace_cardinality_and_redaction_accepted"),("OBG-06","technical_health_probe_current"),("OBG-07","business_invariant_probe_current"),("OBG-08","dependency_and_integration_health_current"),("OBG-09","transaction_idempotency_queue_and_reconciliation_signals_current"),("OBG-10","authorization_and_security_signals_current"),("OBG-11","alert_threshold_dedup_suppression_and_route_current"),("OBG-12","alert_delivery_and acknowledgement_rehearsal_accepted"),("OBG-13","runbook_dashboard_dependency_and kill_switch_current"),("OBG-14","incident_severity_clock_owner_and commander_complete"),("OBG-15","containment_and recovery_receipts_current"),("OBG-16","post_recovery_slo_and business_invariant_accepted"),("OBG-17","residual_difference_zero_or independently adjudicated"),("OBG-18","incident_closure_independently_reviewed"),("OBG-19","retention_revocation_and_redaction_receipts_current"),("OBG-20","no_blocking_unknown_or_unowned_alert")]
ROLES=["OBSERVABILITY_POLICY_OWNER_ROLE","MODULE_TECHNICAL_OWNER_ROLE","BUSINESS_INVARIANT_OWNER_ROLE","ON_CALL_RESPONDER_ROLE","INCIDENT_COMMANDER_ROLE","INDEPENDENT_INCIDENT_CLOSURE_REVIEWER_ROLE"]
OUTCOMES=["HEALTH_ACCEPTED_TECHNICAL_AND_BUSINESS_GATES_CURRENT","HEALTH_REJECTED_MISSING_OR_STALE_SIGNAL","HEALTH_REJECTED_SLO_OR_BURN_RATE","HEALTH_REJECTED_BUSINESS_INVARIANT","ALERT_OPEN_ROUTED_AND_UNACKNOWLEDGED","ALERT_ACKNOWLEDGED_UNDER_INVESTIGATION","INCIDENT_OPEN_CONTAINMENT_REQUIRED","INCIDENT_CONTAINED_RECOVERY_OR_RECONCILIATION_REQUIRED","INCIDENT_RECOVERED_CLOSURE_REVIEW_REQUIRED","INCIDENT_CLOSED_ALL_EVIDENCE_CURRENT"]
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 p=argparse.ArgumentParser();p.add_argument("--output",required=True,type=Path);a=p.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};mods=d["blueprint"]["modules"]
 plans=[{"module_id":m["id"],"observability_status":"DESIGN_ONLY","slo_status":"UNAPPROVED","incident_readiness":"BLOCKED","production_health_status":"UNKNOWN"} for m in mods]
 signals=[{"module_id":m["id"],"signal_class":x,"implementation_status":"NOT_IMPLEMENTED","accepted_receipt_count":0} for m in mods for x in SIGNALS]
 stages=[{"module_id":m["id"],"stage_id":i,"status":"UNEXECUTED","accepted_receipt_count":0} for m in mods for i,_ in STAGES]
 failures=[{"module_id":m["id"],"failure_case_id":i,"status":"UNEXECUTED","accepted_result_count":0} for m in mods for i,_ in FAILURES]
 gates=[{"module_id":m["id"],"gate_id":i,"status":"UNMET","accepted_evidence_count":0} for m in mods for i,_ in GATES]
 roles=[{"module_id":m["id"],"role_type":r,"status":"UNASSIGNED","role_receipt_reference":None} for m in mods for r in ROLES]
 o=d["tests"];s={"module_count":len(mods),"signal_class_count":len(SIGNALS),"module_signal_assignment_count":len(signals),"lifecycle_stage_count":len(STAGES),"module_stage_assignment_count":len(stages),"sli_receipt_field_count":len(SLI_FIELDS),"slo_policy_field_count":len(SLO_FIELDS),"alert_receipt_field_count":len(ALERT_FIELDS),"incident_receipt_field_count":len(INCIDENT_FIELDS),"failure_case_count":len(FAILURES),"module_failure_assignment_count":len(failures),"gate_count":len(GATES),"module_gate_assignment_count":len(gates),"role_type_count":len(ROLES),"module_role_assignment_count":len(roles),"typed_outcome_count":len(OUTCOMES),"telemetry_source_read_or_queried_count":0,"sli_implemented_count":0,"slo_approved_count":0,"alert_route_activated_count":0,"synthetic_alert_or_incident_rehearsal_count":0,"runtime_incident_observed_count":0,"health_or_business_invariant_receipt_accepted_count":0,"incident_closed_count":0,"owner_approved_module_count":0,"command_ready_module_count":0,"pilot_ready_module_count":0,"design_lower_bound_before_observability_contract":1404,"design_lower_bound_after_observability_contract":1404,"official_test_file_count":o["runner"]["test_file_count"],"official_passed_test_count":o["runner"]["passed_test_count"],"risk_count":d["risk"]["summary"]["risk_count"],"mapped_risk_assignment_count":d["trace"]["summary"]["mapped_risk_assignment_count"],"new_risk_count":0}
 checks={"sources_pass":all(d[k].get("validation")=="PASS" for k in ("release","release_checkpoint","redaction","authorization","transaction","tests")),"modules_14_signals_12_assignments_168":(s["module_count"],s["signal_class_count"],s["module_signal_assignment_count"])==(14,12,168),"stages_12_assignments_168":(s["lifecycle_stage_count"],s["module_stage_assignment_count"])==(12,168),"fields_18_18_20_22":(s["sli_receipt_field_count"],s["slo_policy_field_count"],s["alert_receipt_field_count"],s["incident_receipt_field_count"])==(18,18,20,22),"failures_14_assignments_196":(s["failure_case_count"],s["module_failure_assignment_count"])==(14,196),"gates_20_assignments_280":(s["gate_count"],s["module_gate_assignment_count"])==(20,280),"roles_6_assignments_84_outcomes_10":(s["role_type_count"],s["module_role_assignment_count"],s["typed_outcome_count"])==(6,84,10),"all_obligations_open":all(x["implementation_status"]=="NOT_IMPLEMENTED" for x in signals) and all(x["status"]=="UNEXECUTED" for x in stages+failures) and all(x["status"]=="UNMET" for x in gates) and all(x["status"]=="UNASSIGNED" for x in roles),"runtime_and_readiness_zero":all(s[k]==0 for k in ("telemetry_source_read_or_queried_count","sli_implemented_count","slo_approved_count","alert_route_activated_count","synthetic_alert_or_incident_rehearsal_count","runtime_incident_observed_count","health_or_business_invariant_receipt_accepted_count","incident_closed_count","owner_approved_module_count","command_ready_module_count","pilot_ready_module_count")),"non_additive_1404":s["design_lower_bound_before_observability_contract"]==s["design_lower_bound_after_observability_contract"]==1404,"official_tests_pass":o["validation"]=="PASS" and o["runner"]["bootstrap_excluded_test_file_count"]==0,"base_stable":s["risk_count"]==84 and s["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_target_erp_observability_slo_incident_evidence_contract_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","scope":{"mode":"observability_slo_alert_incident_design_only","continuation_complete":False,"telemetry_read_queried_or_collected":False,"monitoring_alerting_or_incident_system_selected":False},"safety":{"database_connections":0,"network_reads_or_writes":0,"telemetry_metrics_logs_traces_or_runtime_health_samples_read_or_queried":0,"alerts_sent_or_incidents_created":0,"operational_forms_reports_queries_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"credentials_endpoints_pii_or_raw_business_values_read_or_persisted":0},"summary":s,"risk_links":["R-001","R-004","R-006","R-007","R-019","R-022","R-025"],"signal_classes":SIGNALS,"lifecycle_stages":[{"stage_id":i,"stage":x} for i,x in STAGES],"sli_receipt_fields":SLI_FIELDS,"slo_policy_fields":SLO_FIELDS,"alert_receipt_fields":ALERT_FIELDS,"incident_receipt_fields":INCIDENT_FIELDS,"failure_cases":[{"failure_case_id":i,"failure_case":x} for i,x in FAILURES],"gates":[{"gate_id":i,"gate":x,"failure_effect":"HEALTH_OR_INCIDENT_CLOSURE_BLOCKED"} for i,x in GATES],"role_types":ROLES,"typed_outcomes":OUTCOMES,"module_observability_plans":plans,"module_signal_assignments":signals,"module_stage_assignments":stages,"module_failure_assignments":failures,"module_gate_assignments":gates,"module_role_assignments":roles,"observability_rule":{"process_running_is_success":False,"technical_health_is_business_invariant_success":False,"missing_or_stale_telemetry_is_healthy":False,"sensitive_or_unbounded_labels_logs_traces_allowed":False,"single_window_threshold_replaces_short_and_long_burn_windows":False,"alert_without_owner_route_and_runbook_is_actionable":False,"authorization_denies_or_reconciliation_unknowns_may_be_silently_dropped":False,"process_restart_automatically_closes_incident":False,"severity_or_residual_difference_may_be_lowered_or_waived_without_evidence":False,"automatic_health_incident_closure_or_readiness":False},"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())]+[{"name":"builder","path":"scripts/windows/build_varanegar_target_erp_observability_slo_incident_evidence_contract_20260829.py","size_bytes":Path(__file__).stat().st_size,"sha256":sha(Path(__file__))}],"limits":["This is an evidence design; no telemetry source was read or queried and no alert or incident was created.","No monitoring alerting tracing logging on-call incident or dashboard provider is selected.","Production health remains unknown until technical SLO business invariant and independent incident evidence are current."]}
 a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(s,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
