"""Build non-duplicating Organization Context Golden/UAT delta cases."""
from __future__ import annotations
import argparse,collections,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S={"envelope":"artifacts/varanegar_analysis/varanegar_organization_context_outcome_envelope_20260829.json","readiness":"artifacts/varanegar_analysis/varanegar_organization_context_readiness_delta_20260829.json","existing":"artifacts/varanegar_analysis/ui/negin_erp_foundation_context_pricing_golden_cases_20260827.json","date":"artifacts/varanegar_analysis/domains/ngt_operation_date_boundary_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_organization_context_readiness_checkpoint_20260829.json"}
F={"OC-YEAR":("organization_context.year_lifecycle","operational/fiscal year distinction and retirement"),"OC-REL":("organization_context.dc_office_stock_relation","same-scope active DC/office/stock/ship/account relation"),"OC-DATE":("organization_context.operation_date_semantics","event, boundary, selector and server-clock separation"),"OC-SNAP":("organization_context.context_snapshot","immutable snapshot and no ambient mid-command drift"),"OC-SPEC":("organization_context.special_order_exception","narrow named exception without bypassing other date consumers")}
CASES=[("AUTH_DENIED","authorization","REJECTED_NO_EFFECT"),("STALE_VERSION","concurrency","REJECTED_NO_EFFECT"),("DUPLICATE_COMMAND","idempotency","ORIGINAL_RECEIPT_ONLY_ONCE"),("INVALID_OR_MISSING_CONTEXT","validation","REJECTED_OR_QUARANTINED"),("FAIL_AFTER_POINTER_OR_OUTBOX","failure_injection","ROLLED_BACK_OR_UNKNOWN_REQUIRES_READBACK"),("PARALLEL_CONTEXT_CHANGE","concurrency","ONE_VERSIONED_SNAPSHOT_AND_NO_MIXED_CONTEXT"),("SUCCESS","success","PUBLISHED_WITH_VALIDATION_AND_AUDIT_RECEIPTS")]
SPECIAL={"OC-YEAR":"operational and fiscal year references remain distinct; used years retire with lineage","OC-REL":"all relation members are active and in one approved scope; no head-office/DC sentinel is inferred","OC-DATE":"event timestamp, open/close boundary, selector and server clock remain typed and missing boundary fails closed","OC-SNAP":"the command pins one ContextSnapshotId and never re-reads mutable ambient session context","OC-SPEC":"order-type exception skips only its named open-date check while price, credit, EVC and other consumers still receive the pinned date"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};old=[x for x in d["existing"]["cases"] if x["target_module"]=="organization_context"];cases=[]
 for prefix,(surface,focus) in F.items():
  for code,kind,expected in CASES:cases.append({"case_id":f"{prefix}-{code}","surface":surface,"case_kind":kind,"focus":focus,"expected_outcome":expected,"assertions":["CommandId, PayloadHash, ExpectedVersion and ContextSnapshotId govern replay","relation/version, pointer, audit and outbox effects reconcile atomically",SPECIAL[prefix],"validation trace identifies typed date/source and relation decisions","source Varanegar/NGT and read-only evidence remain untouched"],"status":"DESIGNED_NOT_EXECUTED"})
 summary={"existing_reused_case_count":len(old),"existing_reused_command_count":len({x["command"] for x in old}),"delta_surface_count":len(F),"delta_case_count":len(cases),"combined_organization_context_acceptance_design_count":len(old)+len(cases),"case_count_per_delta_surface":7,"case_kind_counts":dict(sorted(collections.Counter(x["case_kind"] for x in cases).items())),"executed_delta_case_count":0,"passed_runtime_case_count":0,"owner_approved_case_count":0,"runtime_context_parity_proven_module_count":0,"command_ready_module_count":0,"pilot_ready_module_count":0,"risk_count":84,"mapped_risk_assignment_count":343,"new_risk_count":0};checks={"sources_pass":all(v["validation"]=="PASS" for v in d.values()),"reuse_64_four_commands":len(old)==64 and len({x["command"] for x in old})==4,"delta_35":len(cases)==35 and all(sum(x["surface"]==surface for x in cases)==7 for surface,_ in F.values()),"unique_ids":len({x["case_id"] for x in cases})==35,"no_old_collision":not ({x["case_id"] for x in cases}&{x["case_id"] for x in old}),"combined_99":summary["combined_organization_context_acceptance_design_count"]==99,"all_unexecuted":{x["status"] for x in cases}=={"DESIGNED_NOT_EXECUTED"},"twelve_contract_modules":d["readiness"]["summary"]["outcome_target_contract_module_count_after"]==12,"date_contract":d["date"]["summary"]["sql_consumer_count"]==11 and d["date"]["summary"]["sql_consumer_references_global_tbl_opr_date_count"]==5,"runtime_zero":summary["executed_delta_case_count"]==summary["passed_runtime_case_count"]==summary["owner_approved_case_count"]==summary["runtime_context_parity_proven_module_count"]==summary["command_ready_module_count"]==summary["pilot_ready_module_count"]==0,"base_stable":d["risk"]["summary"]["risk_count"]==84 and d["trace"]["summary"]["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_organization_context_golden_uat_cases_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","safety":{"mode":"OFFLINE_SYNTHETIC_DESIGN","database_connections":0,"network_reads_or_writes":0,"organization_context_commands_or_forms_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"business_values_read_or_persisted":0},"summary":summary,"reuse_manifest":{"source":S["existing"],"policy":"reuse 64 existing operational-year and StockDC save/delete cases; do not duplicate them"},"execution_gate":{"environment":"isolated target only","requirements":["synthetic organization/year/DC/office/stock relation catalog","owner-approved calendar/timezone, retirement and exception policies","parallel context activation and stale-version harness","fault injection at version/pointer/audit/outbox boundaries","server-side authorization and immutable ContextSnapshot propagation"],"promotion_rule":"all 99 reused plus delta obligations execute with zero unexplained context/date/result difference and owner approval"},"cases":cases,"checks":checks,"failed_checks":failed,"risk_links":["R-002","R-005","R-006","R-007","R-008","R-023","R-024","R-033","R-034"],"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"confidence":{"design":"HIGH","runtime":"NOT_EXECUTED"},"limits":["These are acceptance designs, not UAT results.","No context, date, year or relation command was executed.","No real business value appears in fixtures or artifacts."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(summary,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
