from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S={"queue":"artifacts/varanegar_analysis/varanegar_unmatched_golden_case_alias_work_queue_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_distribution_treasury_semantic_alias_candidate_checkpoint_20260829.json","builder":"scripts/windows/build_varanegar_unmatched_golden_case_alias_work_queue_20260829.py","checkpoint_builder":"scripts/windows/build_varanegar_unmatched_golden_case_alias_work_queue_checkpoint_20260829.py","test":"tests/test_varanegar_unmatched_golden_case_alias_work_queue.py","checkpoint_test":"tests/test_varanegar_unmatched_golden_case_alias_work_queue_checkpoint.py","doc":"docs/varanegar_reconstruction/UNMATCHED_GOLDEN_CASE_ALIAS_WORK_QUEUE_20260829_FA.md"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};w=load(paths["queue"]);prev=load(paths["previous"]);s=w["summary"];checks={"sources_pass":w["validation"]==prev["validation"]=="PASS","queue_208":s["unmatched_newer_work_queue_count"]==208,"module_split":(s["pricing_queue_count"],s["distribution_queue_count"],s["treasury_queue_count"],s["accounting_queue_count"],s["reporting_queue_count"])==(28,4,78,42,56),"gap_split":s["action_alias_required_count"]==203 and s["action_match_kind_or_multiplicity_gap_count"]==5,"non_additive_1404":s["accepted_alias_or_semantic_disposition_count"]==s["exact_non_duplicated_additive_count"]==0 and s["design_lower_bound_before_queue"]==s["design_lower_bound_after_queue"]==1404,"execution_readiness_zero":s["executed_case_count"]==s["owner_approved_case_count"]==s["command_ready_module_count"]==s["pilot_ready_module_count"]==0,"base_stable":s["risk_count"]==84 and s["mapped_risk_assignment_count"]==343,"safety_zero":set(w["safety"].values())=={0}};failed=sorted(k for k,v in checks.items() if not v);out={"artifact":"varanegar_unmatched_golden_case_alias_work_queue_checkpoint_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","previous_checkpoint":{"path":S["previous"],"sha256":sha(paths["previous"])},"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"safety":{"database_connections":0,"golden_or_uat_execution":0,"data_mutations":0}};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
