"""Design anonymous result-parity fixtures for all 20 closed report surfaces."""
from __future__ import annotations
import argparse,hashlib,json
from collections import Counter
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S={"reports":"artifacts/varanegar_analysis/varanegar_report_surface_closure_ledger_20260829.json","golden":"artifacts/varanegar_analysis/varanegar_golden_uat_evidence_ledger_20260829.json","playbooks":"artifacts/varanegar_analysis/varanegar_expert_incident_playbook_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_accounting_golden_uat_checkpoint_20260829.json"}
BASE=[("empty_scope","valid scope with no eligible row","EMPTY_WITH_SCHEMA_OR_DOCUMENT_STATE"),("single_valid","one anonymous eligible aggregate","ONE_DETERMINISTIC_RESULT"),("cancel_delete_boundary","active plus cancelled/deleted/absent-line variants","STATUS_FILTER_PARITY"),("cross_scope","same fixture outside DC/fiscal/user scope","ZERO_VISIBLE_OR_DENIED")]
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def assertions(cls):
 if cls=="EXACT_QUERY_REFERENCE_REPORT":return ["ordered schema and typed values equal","filter/date/DC/fiscal scope equal","null and aggregate formula equal"]
 if cls in {"EXTERNAL_DOCUMENT_VIEWER","EXTERNAL_TEMPLATE_PRINT_SHELL","EXTERNAL_TEMPLATE_TRANSACTIONAL_OUTPUT"}:return ["template/document hash and route equal","parameter and connection binding equal","render metadata/page count or explicit unavailable state equal"]
 if cls in {"HOST_OR_VIEW_SHELL","SELECTOR_OR_ROUTE"}:return ["route/host selection equal","filter propagation equal","no independent value-parity claim"]
 if cls=="TRANSACTIONAL_OUTPUT_ORCHESTRATOR":return ["selected documents and ordering equal","per-item success/failure equal","completion audit only after successful output"]
 if cls=="BANK_READ_AND_SUMMARY_SHELL":return ["read envelope and summary formula equal","scope/date/filter equal","no import mutation"]
 return ["read envelope equal","command outcome and durable effect reconciled","partial failure and retry deterministic"]
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};cases=[]
 for s in d["reports"]["surfaces"]:
  for suffix,fixture,outcome in BASE:
   cases.append({"case_id":f'{s["contract_id"]}.{suffix}',"contract_id":s["contract_id"],"legacy_type":s["legacy_type"],"ownership_class":s["ownership_class"],"fixture":"anonymous synthetic; "+fixture,"expected_outcome":outcome,"assertions":assertions(s["ownership_class"]),"execution_status":"DESIGNED_NOT_EXECUTED","owner_approval":"NOT_OBSERVED"})
  if s["command_surface_present"]:cases.append({"case_id":f'{s["contract_id"]}.command_partial_failure',"contract_id":s["contract_id"],"legacy_type":s["legacy_type"],"ownership_class":s["ownership_class"],"fixture":"anonymous synthetic batch/import/output with one forced child failure","expected_outcome":"TYPED_PARTIAL_OR_ATOMIC_FAILURE_PER_PINNED_CONTRACT","assertions":["durable effects match outcome","failed child retry does not duplicate success","audit reflects actual completion"],"execution_status":"DESIGNED_NOT_EXECUTED","owner_approval":"NOT_OBSERVED"})
 counts=dict(sorted(Counter(x["ownership_class"] for x in cases).items()));checks={"sources_pass":all(d[k]["validation"]=="PASS" for k in d),"twenty_surfaces":len(d["reports"]["surfaces"])==20,"eighty_base_cases":sum(not x["case_id"].endswith("command_partial_failure") for x in cases)==80,"eight_command_cases":sum(x["case_id"].endswith("command_partial_failure") for x in cases)==8,"eighty_eight_total":len(cases)==88,"every_surface_covered":{x["contract_id"] for x in cases}=={x["contract_id"] for x in d["reports"]["surfaces"]},"no_false_independent_parity":all("no independent value-parity claim" in x["assertions"] for x in cases if x["ownership_class"] in {"HOST_OR_VIEW_SHELL","SELECTOR_OR_ROUTE"} and not x["case_id"].endswith("command_partial_failure")),"not_executed_or_approved":all(x["execution_status"]=="DESIGNED_NOT_EXECUTED" and x["owner_approval"]=="NOT_OBSERVED" for x in cases),"risk_stable":d["risk"]["summary"]["risk_count"]==84};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_report_golden_fixture_design_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","safety":{"mode":"OFFLINE_ANONYMOUS_FIXTURE_DESIGN_ONLY","database_connections":0,"commands_forms_reports_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"business_values_pii_or_raw_rules_persisted":0},"summary":{"report_surface_count":20,"base_case_count":80,"command_partial_failure_case_count":8,"case_count":88,"ownership_case_counts":counts,"executed_case_count":0,"result_parity_proven_surface_count":0,"owner_approved_surface_count":0,"risk_count":84,"new_risk_count":0},"promotion_gate":{"fixture_approval":"named owner approves anonymous fixture semantics","legacy_capture":"isolated read/render capture with source hashes","target_capture":"same fixture, scope and parameters","comparison":"typed values/schema/render/route/effect assertions by ownership class","acceptance":"zero unexplained difference plus owner signoff"},"cases":cases,"risk_links":["R-002","R-004","R-007","R-017","R-021","R-023","R-031","R-059","R-084"],"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"confidence":{"fixture_coverage":"HIGH_DESIGN","result_parity":"NOT_EXECUTED","owner_acceptance":"NOT_OBSERVED"},"limits":["These fixtures are designs, not captured report results.","Template-owned formulas/layout require the actual approved template at UAT time.","Host/selector shells are tested for routing and propagation, not invented independent values."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
