from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S={"envelope":"artifacts/varanegar_analysis/varanegar_organization_context_outcome_envelope_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_identity_authorization_traceability_delta_checkpoint_20260829.json","builder":"scripts/windows/build_varanegar_organization_context_outcome_envelope_20260829.py","checkpoint_builder":"scripts/windows/build_varanegar_organization_context_outcome_checkpoint_20260829.py","test":"tests/test_varanegar_organization_context_outcome_envelope.py","checkpoint_test":"tests/test_varanegar_organization_context_outcome_checkpoint.py","doc":"docs/varanegar_reconstruction/ORGANIZATION_CONTEXT_SNAPSHOT_DATE_CONTRACT_20260829_FA.md"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d=load(paths["envelope"]);prev=load(paths["previous"]);s=d["summary"];checks={"sources_pass":d["validation"]==prev["validation"]=="PASS","six_commands":s["command_contract_count"]==6,"reuse_64":s["existing_reused_case_count"]==64 and s["existing_reused_command_count"]==4,"date_boundary":s["operation_date_sql_consumer_count"]==11 and s["global_operation_date_sql_consumer_count"]==5,"profile_gap":s["null_operation_date_profile_count"]==3 and s["operation_date_after_last_date_count"]==1,"server_revalidation_gap":s["server_command_revalidates_set_operation_date_permission"] is False,"runtime_zero":s["runtime_effect_parity_proven_count"]==s["implemented_command_count"]==s["owner_approved_count"]==0,"base_stable":s["risk_count"]==84 and s["mapped_risk_assignment_count"]==343,"safety_zero":set(v for k,v in d["safety"].items() if k!="mode")=={0}};failed=sorted(k for k,v in checks.items() if not v);out={"artifact":"varanegar_organization_context_outcome_checkpoint_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","previous_checkpoint":{"path":S["previous"],"sha256":sha(paths["previous"])},"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"safety":{"organization_context_commands_or_forms_executed":0,"assemblies_loaded_or_executed":0,"database_connections":0,"network_reads_or_writes":0,"data_mutations":0,"business_values_persisted":0}};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
