"""Execute deterministic synthetic order-to-cash vectors."""
from __future__ import annotations
import argparse,copy,hashlib,importlib.util,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];REFERENCE=ROOT/"scripts/windows/varanegar_order_to_cash_reference.py"
S={"o2c_contract":"artifacts/varanegar_analysis/varanegar_target_erp_order_to_cash_credit_collections_contract_20260901.json","o2c_checkpoint":"artifacts/varanegar_analysis/varanegar_target_erp_order_to_cash_credit_collections_checkpoint_20260901.json","pricing":"artifacts/varanegar_analysis/varanegar_pricing_rule_expert_playbook_20260829.json","treasury":"artifacts/varanegar_analysis/varanegar_treasury_expert_playbook_20260829.json","inventory":"artifacts/varanegar_analysis/varanegar_target_erp_inventory_lot_serial_expiry_costing_valuation_contract_20260829.json","tests":"artifacts/varanegar_analysis/varanegar_25h_final_test_result_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def module():s=importlib.util.spec_from_file_location("o2c_ref",REFERENCE);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return m
def main():
 p=argparse.ArgumentParser();p.add_argument("--output",required=True,type=Path);a=p.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};m=module();base=m.baseline()
 def changed(**kw):e=copy.deepcopy(base);e.update(kw);return e
 positive=[("POS-ORDER",base,"SALES_ORDER_ACCEPTED_SCOPED_PRICED_CREDIT_APPROVED"),("POS-FULFILL",changed(operation="FULFILL"),"FULFILLMENT_ACCEPTED_ALLOCATED_SHIPPED_AND_DELIVERED"),("POS-INVOICE",changed(operation="INVOICE"),"INVOICE_ACCEPTED_SCHEDULE_TAX_AND_LINEAGE"),("POS-RETURN",changed(operation="RETURN"),"RETURN_CREDIT_REFUND_ACCEPTED_WITH_ORIGINAL_LINEAGE"),("POS-CASH",changed(operation="CASH"),"CASH_RECEIPT_ACCEPTED_IDENTIFIED_AND_CUSTODIED"),("POS-ALLOCATE",changed(operation="ALLOCATE"),"CASH_ALLOCATION_ACCEPTED_BALANCED_AND_VERSIONED"),("POS-COLLECT",changed(operation="COLLECT"),"DISPUTE_COLLECTION_ACTION_ACCEPTED_APPROVED_AND_EVIDENCED"),("POS-REVENUE",changed(operation="REVENUE"),"REVENUE_RECOGNITION_ACCEPTED_OBLIGATION_AND_PERIOD"),("POS-RECON",changed(operation="RECONCILE"),"O2C_RECONCILIATION_ACCEPTED_AR_CASH_REVENUE_AND_GL")]
 negative=[("NEG-EXTRA",dict(base,extra=True),"SCHEMA_INVALID"),("NEG-SCOPE",changed(scope_current=False),"O2C_REJECTED_CUSTOMER_ORGANIZATION_CURRENCY_SCOPE"),("NEG-VERSION",changed(expected_version_match=False),"O2C_REJECTED_VERSION_OR_IDEMPOTENCY"),("NEG-IDEMPOTENCY",changed(idempotency_current=False),"O2C_REJECTED_VERSION_OR_IDEMPOTENCY"),("NEG-UNKNOWN",changed(unknown_commit=True),"O2C_UNKNOWN_RECONCILIATION_REQUIRED"),("NEG-BLOCK",changed(blocking_unknown=True),"MANUAL_REVIEW_REQUIRED_BLOCKING_UNKNOWN"),("NEG-ORDER",changed(order_version_pricing_approved=False),"SALES_ORDER_REJECTED_VERSION_PRICE_OR_APPROVAL"),("NEG-CREDIT",changed(credit_current=False),"CREDIT_REJECTED_LIMIT_EXPOSURE_OR_OVERRIDE"),("NEG-FULFILL",changed(operation="FULFILL",allocation_delivery_current=False),"FULFILLMENT_REJECTED_ALLOCATION_DELIVERY_OR_CREDIT"),("NEG-FULFILL-CREDIT",changed(operation="FULFILL",credit_current=False),"FULFILLMENT_REJECTED_ALLOCATION_DELIVERY_OR_CREDIT"),("NEG-INVOICE",changed(operation="INVOICE",invoice_identity_lineage_current=False),"INVOICE_REJECTED_IDENTITY_SCHEDULE_TAX_OR_LINEAGE"),("NEG-RETURN",changed(operation="RETURN",return_lineage_current=False),"RETURN_CREDIT_REFUND_REJECTED_LINEAGE"),("NEG-CASH",changed(operation="CASH",cash_identity_custody_current=False),"CASH_RECEIPT_REJECTED_IDENTITY_OR_CUSTODY"),("NEG-ALLOC-ID",changed(operation="ALLOCATE",cash_identity_custody_current=False),"CASH_RECEIPT_REJECTED_IDENTITY_OR_CUSTODY"),("NEG-ALLOC-BAL",changed(operation="ALLOCATE",cash_allocation_balanced=False),"CASH_ALLOCATION_REJECTED_AMOUNT_IDENTITY_OR_REVERSAL"),("NEG-COLLECT",changed(operation="COLLECT",dispute_collection_approved=False),"DISPUTE_COLLECTION_REJECTED_UNAPPROVED_OR_UNEVIDENCED"),("NEG-AGING",changed(operation="REVENUE",aging_ecl_current=False),"REVENUE_OR_ECL_REJECTED_CUTOFF_OBLIGATION_OR_PERIOD"),("NEG-REVENUE",changed(operation="REVENUE",revenue_obligation_period_current=False),"REVENUE_OR_ECL_REJECTED_CUTOFF_OBLIGATION_OR_PERIOD"),("NEG-RECON",changed(operation="RECONCILE",ar_cash_revenue_gl_reconciled=False),"O2C_RECONCILIATION_REJECTED_AR_CASH_REVENUE_OR_GL")]
 def run(vs):
  r=[]
  for i,e,x in vs:
   y=m.evaluate(e);r.append({"vector_id":i,"expected":x,"actual":y,"status":"PASS" if y==x else "FAIL"})
  return r
 pr=run(positive);nr=run(negative);allr=pr+nr;official=d["tests"];cs=d["o2c_contract"]["summary"]
 s={"reference_evaluator_implementation_count":1,"positive_vector_count":len(pr),"positive_pass_count":sum(x["status"]=="PASS" for x in pr),"negative_vector_count":len(nr),"negative_pass_count":sum(x["status"]=="PASS" for x in nr),"total_vector_count":len(allr),"total_pass_count":sum(x["status"]=="PASS" for x in allr),"distinct_typed_outcome_count":len({x["actual"] for x in allr}),"o2c_gate_count":cs["gate_count"],"o2c_module_gate_assignment_count":cs["module_gate_assignment_count"],"operational_sales_credit_logistics_billing_treasury_or_collection_implementation_count":0,"operational_customer_order_shipment_invoice_cash_receivable_or_ledger_read_count":0,"order_fulfill_invoice_return_cash_allocate_collect_revenue_or_reconcile_run_count":0,"accepted_operational_receipt_count":0,"command_ready_module_count":0,"pilot_ready_module_count":0,"design_lower_bound_before_reference_evaluator":1404,"design_lower_bound_after_reference_evaluator":1404,"official_test_file_count":official["runner"]["test_file_count"],"official_passed_test_count":official["runner"]["passed_test_count"],"risk_count":d["risk"]["summary"]["risk_count"],"mapped_risk_assignment_count":d["trace"]["summary"]["mapped_risk_assignment_count"],"new_risk_count":0}
 checks={"sources_pass":all(d[k].get("validation")=="PASS" for k in ("o2c_contract","o2c_checkpoint","pricing","treasury","inventory","tests")),"positive_9_of_9":s["positive_vector_count"]==s["positive_pass_count"]==9,"negative_19_of_19":s["negative_vector_count"]==s["negative_pass_count"]==19,"total_28_of_28":s["total_vector_count"]==s["total_pass_count"]==28,"distinct_outcomes_at_least_19":s["distinct_typed_outcome_count"]>=19,"coverage_24_336":(s["o2c_gate_count"],s["o2c_module_gate_assignment_count"])==(24,336),"operational_and_readiness_zero":all(s[k]==0 for k in ("operational_sales_credit_logistics_billing_treasury_or_collection_implementation_count","operational_customer_order_shipment_invoice_cash_receivable_or_ledger_read_count","order_fulfill_invoice_return_cash_allocate_collect_revenue_or_reconcile_run_count","accepted_operational_receipt_count","command_ready_module_count","pilot_ready_module_count")),"non_additive_1404":s["design_lower_bound_before_reference_evaluator"]==s["design_lower_bound_after_reference_evaluator"]==1404,"official_tests_pass":official["validation"]=="PASS" and official["runner"]["bootstrap_excluded_test_file_count"]==0,"base_stable":s["risk_count"]==84 and s["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_target_erp_order_to_cash_synthetic_reference_evaluator_contract_20260901","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","scope":{"mode":"pure_synthetic_order_to_cash_reference_evaluator","continuation_complete":False,"operational_customer_order_shipment_invoice_cash_receivable_or_ledger_read":False},"safety":{"database_connections":0,"network_reads_or_writes":0,"operational_customer_order_shipment_invoice_cash_receivable_or_ledger_reads":0,"order_fulfill_invoice_return_cash_allocate_collect_revenue_or_reconcile_actions_executed":0,"operational_forms_reports_queries_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"credentials_pii_or_raw_business_values_read_or_persisted":0},"summary":s,"positive_results":pr,"negative_results":nr,"outcome_precedence":["SCHEMA","SCOPE","VERSION_IDEMPOTENCY","UNKNOWN_COMMIT","BLOCKING_UNKNOWN","OPERATION_SPECIFIC_POLICY_AND_IDENTITY","RECONCILIATION","ACCEPTED"],"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())]+[{"name":"reference_evaluator","path":REFERENCE.relative_to(ROOT).as_posix(),"size_bytes":REFERENCE.stat().st_size,"sha256":sha(REFERENCE)},{"name":"builder","path":"scripts/windows/build_varanegar_target_erp_order_to_cash_synthetic_reference_evaluator_contract_20260901.py","size_bytes":Path(__file__).stat().st_size,"sha256":sha(Path(__file__))}],"limits":["Only fixed synthetic booleans and operation labels were evaluated.","The evaluator is not a sales credit logistics billing treasury collection bank or accounting provider.","Operational ordering fulfillment billing cash allocation collection revenue recognition reconciliation and readiness remain blocked."]}
 a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(s,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
