"""Build an additive Pricing Rules evidence/requirements/risk trace delta."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S={"envelope":"artifacts/varanegar_analysis/varanegar_pricing_rule_outcome_envelope_20260829.json","readiness":"artifacts/varanegar_analysis/varanegar_pricing_rule_readiness_delta_20260829.json","golden":"artifacts/varanegar_analysis/varanegar_pricing_rule_golden_uat_cases_20260829.json","playbook":"artifacts/varanegar_analysis/varanegar_pricing_rule_expert_playbook_20260829.json","source":"artifacts/varanegar_analysis/ui/varanegar_pricing_rule_command_contracts_20260827.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_pricing_rule_expert_playbook_checkpoint_20260829.json"}
EVIDENCE=["PR-E-01-command-outcome-envelope","PR-E-02-readiness-delta","PR-E-03-golden-uat-delta","PR-E-04-expert-playbook","PR-E-05-static-command-contracts"]
REQS=[("PR-RQ-01","application-service authorization recheck"),("PR-RQ-02","immutable rule lifecycle"),("PR-RQ-03","allowlisted versioned DSL"),("PR-RQ-04","side-effect-free compile/explain"),("PR-RQ-05","deterministic precedence tuple"),("PR-RQ-06","atomic allocation and unique identity"),("PR-RQ-07","CommandId/PayloadHash idempotency"),("PR-RQ-08","atomic audit and outbox"),("PR-RQ-09","authenticated ordered idempotent replication"),("PR-RQ-10","calculation and decision provenance")]
MODULES=["pricing_rules","sales","inventory","master_data","reporting_documents","organization_context"]
RISKS=["R-002","R-005","R-006","R-007","R-008","R-023","R-028","R-036"]
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 p=argparse.ArgumentParser();p.add_argument("--output",required=True,type=Path);a=p.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};known={x["id"] for x in d["risk"]["risks"]};module_links=[{"evidence":e,"module":m,"relationship":"PRICING_RULE_DESIGN_EVIDENCE"} for e in EVIDENCE for m in MODULES];risk_links=[{"evidence":e,"risk":r,"relationship":"MITIGATION_DESIGN_NOT_CLOSURE"} for e in EVIDENCE for r in RISKS];requirements=[{"id":i,"requirement":text,"status":"DESIGNED_NOT_RUNTIME_PROVEN","evidence":EVIDENCE} for i,text in REQS]
 summary={"pricing_rule_evidence_count":len(EVIDENCE),"requirement_contract_delta_count":len(requirements),"module_evidence_link_count":len(module_links),"risk_evidence_link_count":len(risk_links),"unique_linked_risk_count":len(RISKS),"base_risk_count":d["risk"]["summary"]["risk_count"],"base_mapped_risk_assignment_count":d["trace"]["summary"]["mapped_risk_assignment_count"],"new_risk_count":0,"runtime_readiness_promotions":0}
 checks={"sources_pass":all(x["validation"]=="PASS" for x in d.values()),"five_evidence_ten_requirements":len(EVIDENCE)==5 and len(requirements)==10,"links":len(module_links)==30 and len(risk_links)==40 and len(RISKS)==8,"risks_exist":set(RISKS)<=known,"scope_counts":d["envelope"]["summary"]["command_contract_count"]==7 and d["golden"]["summary"]["combined_pricing_acceptance_design_count"]==92 and d["playbook"]["summary"]["playbook_count"]==7,"base_stable":summary["base_risk_count"]==84 and summary["base_mapped_risk_assignment_count"]==343,"no_promotion":summary["new_risk_count"]==summary["runtime_readiness_promotions"]==0};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_pricing_rule_traceability_delta_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","safety":{"mode":"OFFLINE_EVIDENCE_SYNTHESIS","database_connections":0,"commands_forms_reports_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"sensitive_values_or_raw_rule_text_persisted":0},"summary":summary,"policy":{"relationship":"ADDITIVE_EVIDENCE_DELTA_ONLY","base_registers_unchanged":True,"no_risk_closure_or_runtime_promotion":True},"evidence":EVIDENCE,"requirements":requirements,"module_links":module_links,"risk_links":risk_links,"linked_existing_risks":RISKS,"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"confidence":{"design_trace":"HIGH","runtime_effect_parity":"UNPROVEN"},"limits":["Risk links do not close risks.","The 84-risk and 343-assignment base registers remain unchanged.","No runtime pricing outcome or incident diagnosis is claimed."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(summary,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
