"""Build evidence-first Organization Context incident playbooks."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S={"envelope":"artifacts/varanegar_analysis/varanegar_organization_context_outcome_envelope_20260829.json","golden":"artifacts/varanegar_analysis/varanegar_organization_context_golden_uat_cases_20260829.json","date":"artifacts/varanegar_analysis/domains/ngt_operation_date_boundary_20260829.json","order_sql":"artifacts/varanegar_analysis/domains/order_sale_operation_date_sql_20260829.json","commands":"artifacts/varanegar_analysis/ui/varanegar_operational_context_command_contracts_20260827.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_organization_context_golden_uat_checkpoint_20260829.json"}
COMMON=["capture incident time, command/receipt, ContextSnapshotId/version and hashed organization/year/DC/office/stock/date-policy references without raw business values","verify artifact, schema, calendar/timezone and deployment hashes and stop on drift","read immutable context version, active pointer, relation validation trace, audit and outbox receipts","recompute relation eligibility and typed date source without consulting mutable ambient session state","classify NATURAL_BEHAVIOR, DATA_DEBT, BUG or UNPROVEN","quarantine mixed-context, missing-boundary, retired-relation or partial-receipt outcomes before retry","stop before context/date change, pointer rewrite, relation repair, cache/session refresh or business command replay","design isolated synthetic-context and fault-injection reproduction when the boundary remains unproven"]
BASE=[
 ("OC-PB-01","one command shows values from different years, DCs or operation dates","mid-command ambient context drift","compare every effect receipt to one ContextSnapshotId; mixed snapshots are quarantined",["R-002","R-007","R-024"]),
 ("OC-PB-02","date validation accepts or rejects around a missing, closed or after-last boundary","operation-date window","separate missing, null, closed, equal/after-last and exception outcomes; never substitute server today",["R-002","R-023","R-033"]),
 ("OC-PB-03","replicated document date differs from the business event date","event versus selector semantics","compare typed source branches; event timestamp and replication selector equality is not an invariant",["R-002","R-005","R-023"]),
 ("OC-PB-04","office, stock, ship type or account scope disagrees with DC","StockDC relation version","rebuild the candidate relation from one version and quarantine inactive/cross-scope members",["R-007","R-008","R-034"]),
 ("OC-PB-05","retired year or context is still referenced or a delete loses history","year/context lifecycle","preserve references and classify retirement versus physical absence; never remap a historical document",["R-007","R-008","R-023"]),
 ("OC-PB-06","special order type bypasses more date rules than intended","narrow exception boundary","pin the named skipped open-date check and verify price, EVC, credit and other date consumers still use the snapshot",["R-002","R-033","R-034"]),
 ("OC-PB-07","context version commits but pointer, audit, outbox or cache state is partial","atomic context publication","read all receipts before retry; never synthesize activation or refresh a session during diagnosis",["R-006","R-007","R-024"]),
]
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};play=[{"id":i,"incident":inc,"focus":focus,"steps":COMMON+[extra],"stop_conditions":["evidence/schema/calendar/deployment hash drift","context/date change, pointer rewrite, repair, cache refresh or replay required","business owner date/relation policy required","raw organization or business values would be persisted"],"risks":risks,"runtime_diagnosis":"NOT_PERFORMED"} for i,inc,focus,extra,risks in BASE];known={x["id"] for x in d["risk"]["risks"]};summary={"playbook_count":len(play),"minimum_step_count":min(len(x["steps"]) for x in play),"command_contract_count":d["envelope"]["summary"]["command_contract_count"],"combined_acceptance_design_count":d["golden"]["summary"]["combined_organization_context_acceptance_design_count"],"operation_date_sql_consumer_count":d["date"]["summary"]["sql_consumer_count"],"null_operation_date_profile_count":d["order_sql"]["summary"]["null_oprdate_count"],"runtime_incidents_diagnosed_count":0,"context_date_replays_or_repairs_performed_count":0,"owner_approved_count":0,"business_values_persisted_count":0,"risk_count":84,"mapped_risk_assignment_count":343,"new_risk_count":0};checks={"sources_pass":all(v["validation"]=="PASS" for v in d.values()),"seven_playbooks":len(play)==7,"nine_steps":all(len(x["steps"])==9 for x in play),"four_way":all("NATURAL_BEHAVIOR, DATA_DEBT, BUG or UNPROVEN" in x["steps"][4] for x in play),"risks_exist":all(r in known for x in play for r in x["risks"]),"scope":summary["command_contract_count"]==6 and summary["combined_acceptance_design_count"]==99 and summary["operation_date_sql_consumer_count"]==11 and summary["null_operation_date_profile_count"]==3,"context_date_relation_exception":any("ambient context" in x["focus"] for x in play) and any("operation-date" in x["focus"] for x in play) and any("StockDC" in x["focus"] for x in play) and any("exception" in x["focus"] for x in play),"runtime_zero":summary["runtime_incidents_diagnosed_count"]==summary["context_date_replays_or_repairs_performed_count"]==summary["owner_approved_count"]==summary["business_values_persisted_count"]==0,"base_stable":d["risk"]["summary"]["risk_count"]==84 and d["trace"]["summary"]["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_organization_context_expert_playbook_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","safety":{"mode":"OFFLINE_EVIDENCE_SYNTHESIS","database_connections":0,"network_reads_or_writes":0,"organization_context_commands_or_forms_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"business_values_read_or_persisted":0},"summary":summary,"playbooks":play,"diagnostic_result_contract":{"allowed":["NATURAL_BEHAVIOR","DATA_DEBT","BUG","UNPROVEN"],"requires_named_incident_evidence":True,"context_date_replay_or_repair_is_separate_authorized_work":True},"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"confidence":{"structure":"HIGH","incident_diagnosis":"REQUIRES_INCIDENT_EVIDENCE"},"limits":["No named incident was diagnosed.","No context/date command, replay, pointer change, repair or cache refresh was performed.","No production-current effective context is claimed."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(summary,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
