"""Compare assertion/effect-family coverage for all 66 P0 candidate case pairs."""
from __future__ import annotations
import argparse,hashlib,json
from collections import Counter
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
S={"comparator":"artifacts/varanegar_analysis/varanegar_p0_alias_semantic_evidence_comparator_20260829.json","shortlist":"artifacts/varanegar_analysis/varanegar_p0_alias_baseline_candidate_shortlist_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_p0_control_outcome_vocabulary_checkpoint_20260829.json","accounting":"artifacts/varanegar_analysis/varanegar_accounting_golden_uat_cases_20260829.json","treasury":"artifacts/varanegar_analysis/varanegar_treasury_golden_uat_cases_20260829.json","stock_base":"artifacts/varanegar_analysis/ui/varanegar_orchestrator_golden_cases_20260827.json","bank_base":"artifacts/varanegar_analysis/ui/negin_erp_bank_reconciliation_golden_cases_20260827.json","core_base":"artifacts/varanegar_analysis/ui/varanegar_golden_command_cases_20260827.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json"}
RULES={"transaction_atomicity":["transaction","rollback","roll back","partial"],"write_or_state":["write","mutation","state","event"],"audit":["audit"],"outbox":["outbox"],"source_immutability":["source varanegar","source untouched"],"scope_confidentiality":["scope","disclos"],"version_concurrency":["version","stale"],"retry_idempotency":["retry","command_id","original result","duplicate"],"reconciliation_projection":["reconcil","cardex","ledger","projection","crosswalk"],"authorization_denial":["capability","auth","denial"]}
FAMILIES=tuple(RULES)+("mutation_scope_declared","history_scope_declared")
FIELDS=["case_pair_ids","family_signature_hashes","family_presence_mapping","newer_only_family_disposition","baseline_only_family_disposition","transaction_and_write_receipts","audit_outbox_receipts","source_immutability_receipt","scope_version_retry_receipts","reconciliation_projection_receipt","accountable_role_receipts","policy_version_expiry_supersession"]
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def action(x):return str(x.get("command") or x.get("surface") or x.get("command_id") or "")
def kind(x):return str(x.get("kind") or x.get("case_kind") or "").casefold()
def families(x):
 values=list(x.get("expected_assertions") or x.get("assertions") or [])+list(x.get("expected_side_effects") or []);text=" ".join(map(str,values)).casefold();result={name for name,words in RULES.items() if any(word in text for word in words)}
 if x.get("expected_mutation_scope"):result.add("mutation_scope_declared")
 if x.get("expected_ledger_or_history_scope"):result.add("history_scope_declared")
 return result
def sig(values):return hashlib.sha256("\n".join(sorted(values)).encode()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};new_rows=d["accounting"]["cases"]+d["treasury"]["cases"];base_rows=d["stock_base"]["cases"]+d["bank_base"]["cases"]+d["core_base"]["cases"];pair_rows=[]
 for comparison in d["comparator"]["candidate_comparisons"]:
  newer=[x for x in new_rows if action(x)==comparison["newer_action_or_surface"]];baseline=[x for x in base_rows if action(x)==comparison["baseline_action"]]
  for n in newer:
   for b in baseline:
    if kind(n)!=kind(b):continue
    nf=families(n);bf=families(b);pair_rows.append({"comparison_id":comparison["comparison_id"],"source_packet_id":comparison["source_packet_id"],"newer_case_id":n["case_id"],"baseline_case_id":b["case_id"],"case_kind":kind(n),"newer_effect_families":sorted(nf),"baseline_effect_families":sorted(bf),"newer_family_signature_sha256":sig(nf),"baseline_family_signature_sha256":sig(bf),"exact_family_set":nf==bf,"nonempty_family_overlap":bool(nf&bf),"overlapping_families":sorted(nf&bf),"newer_only_families":sorted(nf-bf),"baseline_only_families":sorted(bf-nf),"current_status":"WAITING_FOR_ASSERTION_EFFECT_FAMILY_DISPOSITION","accepted_pair_count":0,"counting_effect":"ZERO"})
 family_packets=[]
 for i,family in enumerate(FAMILIES,1):
  family_packets.append({"family_packet_id":f"P0E-{i:02d}","effect_family":family,"newer_pair_coverage_count":sum(family in x["newer_effect_families"] for x in pair_rows),"baseline_pair_coverage_count":sum(family in x["baseline_effect_families"] for x in pair_rows),"both_pair_coverage_count":sum(family in x["newer_effect_families"] and family in x["baseline_effect_families"] for x in pair_rows),"newer_only_pair_count":sum(family in x["newer_only_families"] for x in pair_rows),"baseline_only_pair_count":sum(family in x["baseline_only_families"] for x in pair_rows),"required_disposition_fields":FIELDS,"current_status":"WAITING_FOR_ASSERTION_EFFECT_FAMILY_DISPOSITION","accepted_family_mapping_count":0,"counting_effect":"ZERO"})
 nc=Counter(f for x in pair_rows for f in x["newer_effect_families"]);bc=Counter(f for x in pair_rows for f in x["baseline_effect_families"]);summary={"candidate_case_pair_count":len(pair_rows),"effect_family_count":len(FAMILIES),"exact_family_set_pair_count":sum(x["exact_family_set"] for x in pair_rows),"nonempty_family_overlap_pair_count":sum(x["nonempty_family_overlap"] for x in pair_rows),"zero_family_overlap_pair_count":sum(not x["nonempty_family_overlap"] for x in pair_rows),"newer_only_family_assignment_count":sum(len(x["newer_only_families"]) for x in pair_rows),"baseline_only_family_assignment_count":sum(len(x["baseline_only_families"]) for x in pair_rows),"newer_audit_pair_count":nc["audit"],"baseline_audit_pair_count":bc["audit"],"newer_outbox_pair_count":nc["outbox"],"baseline_outbox_pair_count":bc["outbox"],"newer_source_immutability_pair_count":nc["source_immutability"],"baseline_source_immutability_pair_count":bc["source_immutability"],"newer_transaction_atomicity_pair_count":nc["transaction_atomicity"],"baseline_transaction_atomicity_pair_count":bc["transaction_atomicity"],"newer_version_concurrency_pair_count":nc["version_concurrency"],"baseline_version_concurrency_pair_count":bc["version_concurrency"],"newer_mutation_scope_declared_pair_count":nc["mutation_scope_declared"],"baseline_mutation_scope_declared_pair_count":bc["mutation_scope_declared"],"newer_history_scope_declared_pair_count":nc["history_scope_declared"],"baseline_history_scope_declared_pair_count":bc["history_scope_declared"],"accountable_role_assignment_count":sum(len(x["accountable_role_types"]) for x in d["shortlist"]["p0_candidate_packets"] if x["candidate_baseline_action_count"]),"required_disposition_field_count":len(FIELDS),"accepted_family_mapping_count":0,"accepted_case_pair_count":0,"exact_non_duplicated_additive_count":0,"design_lower_bound_before_effect_family_matrix":d["comparator"]["summary"]["design_lower_bound_after_comparator"],"design_lower_bound_after_effect_family_matrix":d["comparator"]["summary"]["design_lower_bound_after_comparator"],"executed_case_count":0,"owner_approved_case_count":0,"command_ready_module_count":0,"pilot_ready_module_count":0,"risk_count":d["risk"]["summary"]["risk_count"],"mapped_risk_assignment_count":d["trace"]["summary"]["mapped_risk_assignment_count"],"new_risk_count":0}
 checks={"sources_pass":all(x.get("validation")=="PASS" for k,x in d.items() if k!="core_base") and d["core_base"].get("validation") is None,"sixty_six_pairs_12_families":summary["candidate_case_pair_count"]==66 and summary["effect_family_count"]==12,"overlap_0_65_1":(summary["exact_family_set_pair_count"],summary["nonempty_family_overlap_pair_count"],summary["zero_family_overlap_pair_count"])==(0,65,1),"asymmetric_assignments_294_125":(summary["newer_only_family_assignment_count"],summary["baseline_only_family_assignment_count"])==(294,125),"audit_outbox":(summary["newer_audit_pair_count"],summary["baseline_audit_pair_count"],summary["newer_outbox_pair_count"],summary["baseline_outbox_pair_count"])==(66,50,66,14),"source_transaction":(summary["newer_source_immutability_pair_count"],summary["baseline_source_immutability_pair_count"],summary["newer_transaction_atomicity_pair_count"],summary["baseline_transaction_atomicity_pair_count"])==(0,53,6,29),"version_and_scopes":(summary["newer_version_concurrency_pair_count"],summary["baseline_version_concurrency_pair_count"],summary["newer_mutation_scope_declared_pair_count"],summary["baseline_mutation_scope_declared_pair_count"],summary["newer_history_scope_declared_pair_count"],summary["baseline_history_scope_declared_pair_count"])==(55,0,0,13,0,13),"roles_fields":summary["accountable_role_assignment_count"]==6 and summary["required_disposition_field_count"]==12,"all_waiting_zero":all(x["current_status"].startswith("WAITING") and x["accepted_pair_count"]==0 and x["counting_effect"]=="ZERO" for x in pair_rows) and all(x["accepted_family_mapping_count"]==0 and x["counting_effect"]=="ZERO" for x in family_packets),"non_additive_1404":summary["accepted_family_mapping_count"]==summary["accepted_case_pair_count"]==summary["exact_non_duplicated_additive_count"]==0 and summary["design_lower_bound_before_effect_family_matrix"]==summary["design_lower_bound_after_effect_family_matrix"]==1404,"execution_readiness_zero":summary["executed_case_count"]==summary["owner_approved_case_count"]==summary["command_ready_module_count"]==summary["pilot_ready_module_count"]==0,"base_stable":summary["risk_count"]==84 and summary["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_p0_assertion_effect_family_gap_matrix_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","scope":{"mode":"OFFLINE_P0_ASSERTION_EFFECT_FAMILY_GAP_ANALYSIS","continuation_complete":False},"safety":{"database_connections":0,"golden_uat_or_operational_execution":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"write_access_created":0,"raw_business_values_identity_or_credentials_persisted":0},"summary":summary,"classification_rules":RULES,"required_disposition_fields":FIELDS,"effect_family_gap_packets":family_packets,"case_pair_family_signatures":pair_rows,"interpretation_rule":"keyword-family signatures are a conservative routing heuristic; overlap is not semantic assertion or effect equivalence","checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":p.stat().st_size,"sha256":sha(p)} for k,p in sorted(paths.items())]+[{"name":"builder","path":"scripts/windows/build_varanegar_p0_assertion_effect_family_gap_matrix_20260829.py","size_bytes":Path(__file__).stat().st_size,"sha256":sha(Path(__file__))}],"limits":["The classifier uses documented assertion/effect text only and does not execute any case.","Table/object names are not persisted; only field-presence families are recorded.","No family mapping or case pair is accepted."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(summary,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
