"""Build a 20-surface report ownership/parity/readiness traceability ledger."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
BASE={"gaps":"artifacts/varanegar_analysis/ui/varanegar_report_evidence_gaps_20260827.json","target":"artifacts/varanegar_analysis/ui/varanegar_report_target_contracts_golden_cases_20260827.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_treasury_crystal_viewer_checkpoint_20260829.json"}
E={
 "treasury_viewer":"artifacts/varanegar_analysis/domains/treasury_crystal_viewer_contract_20260829.json","dashboard":"artifacts/varanegar_analysis/domains/dashboard_shell_contract_20260829.json","party":"artifacts/varanegar_analysis/domains/party_cardex_reference_contract_20260829.json","call_center":"artifacts/varanegar_analysis/domains/call_center_report_contract_20260829.json","print_batch":"artifacts/varanegar_analysis/domains/print_batch_contract_20260829.json","sale_invoice":"artifacts/varanegar_analysis/varanegar_sale_invoice_print_checkpoint_20260829.json","return_template":"artifacts/varanegar_analysis/domains/return_report_template_boundary_20260829.json","production_order":"artifacts/varanegar_analysis/domains/production_order_report_contract_20260829.json","production_detail":"artifacts/varanegar_analysis/domains/production_detail_report_contract_20260829.json","stock_reference":"artifacts/varanegar_analysis/domains/stock_report_reference_contract_20260829.json","stock_selector":"artifacts/varanegar_analysis/domains/stock_report_selector_contract_20260829.json","healthy_cardex":"artifacts/varanegar_analysis/domains/healthy_cardex_report_contract_20260829.json","bank_read":"artifacts/varanegar_analysis/ui/negin_erp_bank_reconciliation_read_model_contract_20260827.json","bank_summary":"artifacts/varanegar_analysis/ui/varanegar_bank_reconciliation_summary_ui_boundary_20260827.json","bank_readiness":"artifacts/varanegar_analysis/ui/negin_erp_bank_reconciliation_implementation_readiness_20260827.json","bank_state":"artifacts/varanegar_analysis/ui/negin_erp_bank_reconciliation_state_machine_contract_20260827.json","bank_envelope":"artifacts/varanegar_analysis/ui/negin_erp_bank_reconciliation_command_envelope_20260827.json","bank_transaction":"artifacts/varanegar_analysis/ui/varanegar_bank_reconciliation_transaction_boundary_20260827.json"}
MAP={
 "RPT-01":("EXTERNAL_DOCUMENT_VIEWER",["treasury_viewer"]),"RPT-02":("EXTERNAL_DOCUMENT_VIEWER",["treasury_viewer"]),"RPT-03":("HOST_OR_VIEW_SHELL",["dashboard"]),"RPT-04":("HOST_OR_VIEW_SHELL",["dashboard"]),"RPT-05":("EXACT_QUERY_REFERENCE_REPORT",["party"]),"RPT-06":("EXACT_QUERY_REFERENCE_REPORT",["call_center"]),"RPT-07":("EXACT_QUERY_REFERENCE_REPORT",["party"]),"RPT-08":("EXACT_QUERY_REFERENCE_REPORT",["party"]),"RPT-09":("TRANSACTIONAL_OUTPUT_ORCHESTRATOR",["print_batch"]),"RPT-10":("EXTERNAL_TEMPLATE_PRINT_SHELL",["sale_invoice"]),"RPT-11":("EXTERNAL_TEMPLATE_TRANSACTIONAL_OUTPUT",["return_template"]),"RPT-12":("EXTERNAL_TEMPLATE_TRANSACTIONAL_OUTPUT",["sale_invoice"]),"RPT-13":("EXACT_QUERY_REFERENCE_REPORT",["production_order"]),"RPT-14":("EXACT_QUERY_REFERENCE_REPORT",["production_detail"]),"RPT-15":("EXACT_QUERY_REFERENCE_REPORT",["stock_reference"]),"RPT-16":("SELECTOR_OR_ROUTE",["stock_selector"]),"RPT-17":("SELECTOR_OR_ROUTE",["stock_selector"]),"RPT-18":("EXACT_QUERY_REFERENCE_REPORT",["healthy_cardex"]),"RPT-19":("BANK_READ_AND_SUMMARY_SHELL",["bank_read","bank_summary"]),"RPT-20":("BANK_COMMAND_AND_IMPORT_ORCHESTRATOR",["bank_readiness","bank_state","bank_envelope","bank_transaction"])}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def build():
 sources={**BASE,**E};paths={k:ROOT/v for k,v in sources.items()};d={k:load(p) for k,p in paths.items()};gaps={x["contract_id"]:x for x in d["gaps"]["reports"]};targets={x["contract_id"]:x for x in d["target"]["contracts"]};rows=[]
 for rid in sorted(MAP,key=lambda x:int(x.split("-")[1])):
  ownership,keys=MAP[rid];artifacts=[{"key":k,"path":E[k],"validation":d[k].get("validation"),"status":d[k].get("status")} for k in keys];is_command=bool(targets[rid].get("command_surfaces"));rows.append({"contract_id":rid,"legacy_type":gaps[rid]["legacy_type"],"ownership_class":ownership,"ownership_evidence_status":"CLOSED_HASH_PINNED_OR_VALIDATED_CONTRACT" if all(x["validation"]=="PASS" for x in artifacts) else "INVALID_EVIDENCE","evidence":artifacts,"independent_result_parity_applicable":ownership in {"EXACT_QUERY_REFERENCE_REPORT","EXTERNAL_TEMPLATE_TRANSACTIONAL_OUTPUT","BANK_READ_AND_SUMMARY_SHELL"},"result_parity_proven":False,"owner_golden_values_present":False,"command_surface_present":is_command or ownership in {"TRANSACTIONAL_OUTPUT_ORCHESTRATOR","EXTERNAL_TEMPLATE_TRANSACTIONAL_OUTPUT","BANK_COMMAND_AND_IMPORT_ORCHESTRATOR"},"command_ready":False,"implementation_ready":False,"pilot_ready":False,"next_gate":"FROZEN_PRIVACY_SAFE_UAT_PER_QUERY_OR_TEMPLATE" if ownership in {"EXACT_QUERY_REFERENCE_REPORT","EXTERNAL_TEMPLATE_TRANSACTIONAL_OUTPUT","BANK_READ_AND_SUMMARY_SHELL"} else "ROUTING_PERMISSION_FAILURE_OR_COMMAND_TRUTH_TABLE_GATE"})
 counts={k:sum(x["ownership_class"]==k for x in rows) for k in sorted({x["ownership_class"] for x in rows})};checks={"all_sources_pass":all(d[k].get("validation")=="PASS" for k in sources),"twenty_unique_surfaces":len(rows)==20 and len({x["contract_id"] for x in rows})==20,"all_baseline_surfaces_mapped":set(gaps)==set(MAP),"all_ownership_closed":all(x["ownership_evidence_status"].startswith("CLOSED") for x in rows),"result_parity_not_overclaimed":not any(x["result_parity_proven"] for x in rows),"command_readiness_not_overclaimed":not any(x["command_ready"] for x in rows),"implementation_not_overclaimed":not any(x["implementation_ready"] or x["pilot_ready"] for x in rows),"risk_stable":d["risk"]["summary"]["risk_count"]==84};failed=sorted(k for k,v in checks.items() if not v)
 return {"artifact":"varanegar_report_surface_closure_ledger_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","safety":{"mode":"OFFLINE_EXISTING_ARTIFACT_TRACEABILITY_ONLY","database_connections":0,"reports_templates_forms_queries_or_commands_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"sensitive_values_persisted":0},"summary":{"report_surface_count":len(rows),"ownership_evidence_closed_count":sum(x["ownership_evidence_status"].startswith("CLOSED") for x in rows),"result_parity_proven_count":sum(x["result_parity_proven"] for x in rows),"owner_golden_value_count":sum(x["owner_golden_values_present"] for x in rows),"command_surface_count":sum(x["command_surface_present"] for x in rows),"command_ready_count":sum(x["command_ready"] for x in rows),"implementation_ready_count":sum(x["implementation_ready"] for x in rows),"pilot_ready_count":sum(x["pilot_ready"] for x in rows),"risk_count":d["risk"]["summary"]["risk_count"],"ownership_class_counts":counts,"validation_error_count":len(failed)},"interpretation":{"ownership_closed":"The runtime owner/boundary is classified and linked to validated evidence.","result_parity":"Still requires exact template/query outputs and owner-approved frozen UAT where applicable.","command_ready":"Still requires complete authorization, transaction, mutation, outcome and retry proof.","important":"Ownership closure is not implementation, pilot or parity readiness."},"surfaces":rows,"checks":checks,"failed_checks":failed,"risk_links":["R-002","R-004","R-007","R-017","R-021","R-023","R-031","R-059","R-084"],"source_manifest":[{"name":k,"path":sources[k],"size_bytes":p.stat().st_size,"sha256":sha(p)} for k,p in sorted(paths.items())],"confidence":{"ownership_traceability":"CONFIRMED_BY_VALIDATED_ARTIFACTS","runtime_result_parity_command_and_pilot_readiness":"UNPROVEN"},"limits":["This ledger executes no legacy behavior and does not upgrade result parity.","RPT-19/RPT-20 reuse the existing validated bank package without repeating its analysis.","RPT-10/RPT-12 reuse the existing sale-invoice template/print checkpoint."]}
def main():
 p=argparse.ArgumentParser();p.add_argument("--output",required=True,type=Path);a=p.parse_args();x=build();a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(x,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(x["validation"]);print(json.dumps(x["summary"]));return 0 if x["validation"]=="PASS" else 1
if __name__=="__main__":raise SystemExit(main())
