"""Build chained checkpoint for the RPT-06 call-center report."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
S={"contract":"artifacts/varanegar_analysis/domains/call_center_report_contract_20260829.json","binding":"artifacts/varanegar_analysis/domains/call_center_report_query_binding_20260829.json","catalog":"artifacts/varanegar_analysis/domains/call_center_report_sql_catalog_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_production_order_report_checkpoint_20260829.json","binding_extractor":"scripts/windows/extract_varanegar_call_center_report_query_binding_20260829.py","catalog_extractor":"scripts/sql/extract_varanegar_call_center_report_sql_catalog_20260829.py","builder":"scripts/windows/build_varanegar_call_center_report_contract_20260829.py","checkpoint_builder":"scripts/windows/build_varanegar_call_center_report_checkpoint_20260829.py","test":"tests/test_varanegar_call_center_report_contract.py","doc":"docs/varanegar_reconstruction/CALL_CENTER_REPORT_TYPE_SCOPE_AND_PARITY_20260829_FA.md"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(paths[k]) for k in ("contract","binding","catalog","previous")};c=d["contract"];checks={"sources_pass":all(x["validation"]=="PASS" for x in d.values()),"zero_candidate_to_exact_query":c["summary"]["prior_sql_candidate_count"]==0 and c["summary"]["exact_query_binding_count"]==1,"four_params_ten_dependencies":c["summary"]["parameter_count"]==4 and c["summary"]["dependency_count"]==10,"type_mapping_not_invented":c["query_contract"]["mode_to_type_value_mapping"].startswith("UNPROVEN"),"six_golden_cases":len(c["golden_cases"])==6,"parity_not_claimed":c["summary"]["result_parity_proven_count"]==0,"risk_stable":c["summary"]["risk_count"]==84,"zero_execution":set(v for k,v in c["safety"].items() if k!="mode")=={0}};failed=sorted(k for k,v in checks.items() if not v);out={"artifact":"varanegar_call_center_report_checkpoint_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","previous_checkpoint":{"path":S["previous"],"sha256":sha(paths["previous"])},"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"safety":{"form_report_procedure_query_or_export_executed":0,"assemblies_loaded_or_executed":0,"database_connections_by_checkpoint":0,"data_mutations":0,"sensitive_values_persisted":0}};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
