"""Chain the hash-pinned Manual Voucher generic-save extraction."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S={"runtime":"artifacts/varanegar_analysis/varanegar_manual_voucher_generic_save_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_manual_voucher_checkpoint_20260829.json","extractor":"scripts/windows/extract_varanegar_manual_voucher_generic_save_20260829.py","checkpoint_builder":"scripts/windows/build_varanegar_manual_voucher_generic_save_checkpoint_20260829.py","test":"tests/test_varanegar_manual_voucher_generic_save.py","doc":"docs/varanegar_reconstruction/MANUAL_VOUCHER_GENERIC_SAVE_TRANSACTION_20260829_FA.md"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(paths[k]) for k in ("runtime","previous")};s=d["runtime"]["summary"];checks={"sources_pass":d["runtime"]["validation"]==d["previous"]["validation"]=="PASS","five_hashes":s["assembly_count"]==5 and s["source_hash_mismatch_count"]==0,"generic_overloads":s["generic_save_overload_count"]==2,"crud_commit_owner":s["context_crud_overload_count"]==s["context_crud_overload_with_commit_count"]==3,"no_explicit_rollback":s["selected_method_with_explicit_rollback_count"]==0,"zero_execution":set(v for k,v in d["runtime"]["safety"].items() if k!="mode")=={0}};failed=sorted(k for k,v in checks.items() if not v);out={"artifact":"varanegar_manual_voucher_generic_save_checkpoint_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","previous_checkpoint":{"path":S["previous"],"sha256":sha(paths["previous"])},"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"safety":{"commands_forms_queries_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"database_connections":0,"data_mutations":0,"sensitive_values_persisted":0}};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
