"""Consolidate final evidence-gap status for the three P4 export packets."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
S={"shortlist":"artifacts/varanegar_analysis/varanegar_p4_alias_baseline_candidate_shortlist_20260829.json","comparator":"artifacts/varanegar_analysis/varanegar_p4_alias_semantic_evidence_comparator_20260829.json","failure":"artifacts/varanegar_analysis/varanegar_p4_failure_injection_adjudication_packets_20260829.json","outcome":"artifacts/varanegar_analysis/varanegar_p4_control_outcome_vocabulary_adjudication_20260829.json","effect":"artifacts/varanegar_analysis/varanegar_p4_assertion_effect_family_gap_matrix_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_p4_assertion_effect_family_gap_checkpoint_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json"}
FIELDS=["source_packet_and_case_set_hash","report_contract_and_candidate_reference","versioned_alias_or_export_action_decision","read_model_export_artifact_boundary_disposition","precondition_equivalence","outcome_vocabulary_mapping","assertion_effect_equivalence","file_artifact_and_source_immutability_receipts","fault_stage_retry_quarantine_receipts","presentation_integrity_receipt","pinned_query_watermark_receipt","frozen_fixture_result_content_parity_receipt","accountable_role_receipts","policy_version_conflict_expiry_supersession"]
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};comparisons=d["comparator"]["candidate_comparisons"];effects=d["effect"]["case_pair_family_signatures"];rows=[]
 for p in d["shortlist"]["p4_candidate_packets"]:
  pid=p["source_packet_id"];cs=[x for x in comparisons if x["source_packet_id"]==pid];pairs=[x for c in cs for x in c["case_pair_comparisons"]];ef=[x for x in effects if x["source_packet_id"]==pid];failure=[x for x in pairs if x["case_kind"]=="failure_injection"];read_candidate=any(x["baseline_action"].endswith(".read") for x in p["candidate_baseline_actions"])
  rows.append({"status_id":f"P4G-{len(rows)+1:02d}","source_packet_id":pid,"module":p["module"],"newer_action_or_surface":p["newer_action_or_surface"],"case_count":p["newer_case_count"],"candidate_baseline_action_count":p["candidate_baseline_action_count"],"read_model_candidate":read_candidate,"same_kind_case_pair_count":len(pairs),"failure_injection_pair_count":len(failure),"control_pair_count":len(pairs)-len(failure),"outcome_exact_pair_count":sum(x["outcome_exact"] for x in pairs),"assertion_list_exact_pair_count":sum(x["assertion_list_exact"] for x in pairs),"fully_exact_pair_count":sum(x["fully_exact"] for x in pairs),"exact_effect_family_set_pair_count":sum(x["exact_family_set"] for x in ef),"zero_effect_family_overlap_pair_count":sum(not x["nonempty_family_overlap"] for x in ef),"evidence_gap_class":"EXPORT_EFFECT_AND_FROZEN_FIXTURE_RESULT_PARITY_NOT_CLOSED","required_decision_route":"EXTERNAL_EXPORT_EFFECT_AND_RESULT_PARITY_DECISION_REQUIRED","accountable_role_types":p["accountable_role_types"],"required_closure_fields":FIELDS,"analysis_packetization_status":"COMPLETE_CURRENT_STATIC_SCOPE","semantic_disposition_status":"UNRESOLVED_EXTERNAL_EVIDENCE_REQUIRED","result_parity_status":"UNPROVEN_FROZEN_FIXTURE_AND_RESULT_RECEIPT_REQUIRED","accepted_case_disposition_count":0,"result_parity_proven_count":0,"counting_effect":"ZERO"})
 s={"p4_status_packet_count":len(rows),"p4_case_count":sum(x["case_count"] for x in rows),"analysis_packetization_complete_count":sum(x["analysis_packetization_status"].startswith("COMPLETE") for x in rows),"candidate_bearing_packet_count":sum(x["candidate_baseline_action_count"]>0 for x in rows),"read_model_candidate_packet_count":sum(x["read_model_candidate"] for x in rows),"export_file_candidate_packet_count":sum(not x["read_model_candidate"] for x in rows),"external_export_effect_and_result_parity_decision_packet_count":sum(x["required_decision_route"]=="EXTERNAL_EXPORT_EFFECT_AND_RESULT_PARITY_DECISION_REQUIRED" for x in rows),"same_kind_case_pair_count":sum(x["same_kind_case_pair_count"] for x in rows),"failure_injection_pair_count":sum(x["failure_injection_pair_count"] for x in rows),"control_pair_count":sum(x["control_pair_count"] for x in rows),"outcome_exact_pair_count":sum(x["outcome_exact_pair_count"] for x in rows),"assertion_list_exact_pair_count":sum(x["assertion_list_exact_pair_count"] for x in rows),"fully_exact_pair_count":sum(x["fully_exact_pair_count"] for x in rows),"exact_effect_family_set_pair_count":sum(x["exact_effect_family_set_pair_count"] for x in rows),"zero_effect_family_overlap_pair_count":sum(x["zero_effect_family_overlap_pair_count"] for x in rows),"accountable_role_assignment_count":sum(len(x["accountable_role_types"]) for x in rows),"required_closure_field_count":len(FIELDS),"semantic_disposition_closed_packet_count":0,"result_parity_proven_packet_count":0,"accepted_case_disposition_count":0,"exact_non_duplicated_additive_count":0,"design_lower_bound_before_p4_status":1404,"design_lower_bound_after_p4_status":1404,"executed_case_count":0,"owner_approved_case_count":0,"command_ready_module_count":0,"pilot_ready_module_count":0,"risk_count":d["risk"]["summary"]["risk_count"],"mapped_risk_assignment_count":d["trace"]["summary"]["mapped_risk_assignment_count"],"new_risk_count":0}
 checks={"sources_pass":all(x.get("validation")=="PASS" for x in d.values()),"three_21":s["p4_status_packet_count"]==3 and s["p4_case_count"]==21,"packetized_not_disposed":s["analysis_packetization_complete_count"]==3 and s["semantic_disposition_closed_packet_count"]==s["result_parity_proven_packet_count"]==0,"candidate_split":(s["candidate_bearing_packet_count"],s["read_model_candidate_packet_count"],s["export_file_candidate_packet_count"],s["external_export_effect_and_result_parity_decision_packet_count"])==(3,1,2,3),"pairs_14_6_8":(s["same_kind_case_pair_count"],s["failure_injection_pair_count"],s["control_pair_count"])==(14,6,8),"semantic_exactness_zero":(s["outcome_exact_pair_count"],s["assertion_list_exact_pair_count"],s["fully_exact_pair_count"],s["exact_effect_family_set_pair_count"],s["zero_effect_family_overlap_pair_count"])==(0,0,0,0,0),"roles_fields":s["accountable_role_assignment_count"]==6 and s["required_closure_field_count"]==14,"all_unresolved_zero":all(x["semantic_disposition_status"].startswith("UNRESOLVED") and x["result_parity_status"].startswith("UNPROVEN") and x["accepted_case_disposition_count"]==x["result_parity_proven_count"]==0 and x["counting_effect"]=="ZERO" for x in rows),"non_additive_1404":s["accepted_case_disposition_count"]==s["exact_non_duplicated_additive_count"]==0 and s["design_lower_bound_before_p4_status"]==s["design_lower_bound_after_p4_status"]==1404,"execution_readiness_zero":s["executed_case_count"]==s["owner_approved_case_count"]==s["command_ready_module_count"]==s["pilot_ready_module_count"]==0,"base_stable":s["risk_count"]==84 and s["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_p4_final_evidence_gap_status_matrix_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","scope":{"mode":"OFFLINE_P4_FINAL_READ_ONLY_EXPORT_EVIDENCE_GAP_STATUS","continuation_complete":False},"safety":{"database_connections":0,"golden_uat_or_operational_execution":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"write_access_created":0,"raw_business_values_identity_or_credentials_persisted":0},"summary":s,"required_closure_fields":FIELDS,"p4_status_packets":rows,"closure_rule":"read-model ownership, export artifact semantics and frozen-fixture result parity are separate gates; static packetization closes none of them","checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":p.stat().st_size,"sha256":sha(p)} for k,p in sorted(paths.items())]+[{"name":"builder","path":"scripts/windows/build_varanegar_p4_final_evidence_gap_status_matrix_20260829.py","size_bytes":Path(__file__).stat().st_size,"sha256":sha(Path(__file__))}],"limits":["This closes current static packetization only.","The bank read candidate is not an export-equivalence proof.","No execution, result parity, acceptance, or readiness is claimed."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(s,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
