"""Checkpoint P4 export control outcome-vocabulary adjudication."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
S={"matrix":"artifacts/varanegar_analysis/varanegar_p4_control_outcome_vocabulary_adjudication_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_p4_failure_injection_adjudication_checkpoint_20260829.json","builder":"scripts/windows/build_varanegar_p4_control_outcome_vocabulary_adjudication_20260829.py","checkpoint_builder":"scripts/windows/build_varanegar_p4_control_outcome_vocabulary_checkpoint_20260829.py","test":"tests/test_varanegar_p4_control_outcome_vocabulary_adjudication.py","checkpoint_test":"tests/test_varanegar_p4_control_outcome_vocabulary_checkpoint.py","doc":"docs/varanegar_reconstruction/P4_CONTROL_OUTCOME_VOCABULARY_ADJUDICATION_20260829_FA.md"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};m=load(paths["matrix"]);prev=load(paths["previous"]);s=m["summary"];checks={"sources_pass":m["validation"]==prev["validation"]=="PASS","three_8":s["control_kind_packet_count"]==3 and s["non_failure_case_pair_count"]==8,"distribution":(s["authorization_pair_count"],s["idempotency_pair_count"],s["success_pair_count"])==(3,2,3),"vocab":(s["global_newer_outcome_vocabulary_count"],s["global_baseline_outcome_vocabulary_count"],s["per_kind_newer_outcome_vocabulary_count"],s["per_kind_baseline_outcome_vocabulary_count"])==(3,1,3,3),"generic_3_2":(s["generic_rejected_no_effect_pair_count"],s["generic_committed_original_once_pair_count"])==(3,2),"exactness":(s["outcome_label_exact_pair_count"],s["outcome_label_mapping_required_pair_count"],s["assertion_list_exact_pair_count"],s["fully_exact_pair_count"])==(0,8,0,0),"non_additive_1404":s["accepted_outcome_pair_count"]==s["result_parity_proven_packet_count"]==s["exact_non_duplicated_additive_count"]==0 and s["design_lower_bound_before_outcome_adjudication"]==s["design_lower_bound_after_outcome_adjudication"]==1404,"execution_readiness_zero":s["executed_case_count"]==s["owner_approved_case_count"]==s["command_ready_module_count"]==s["pilot_ready_module_count"]==0,"base_stable":s["risk_count"]==84 and s["mapped_risk_assignment_count"]==343,"safety_zero":set(m["safety"].values())=={0}};failed=sorted(k for k,v in checks.items() if not v);out={"artifact":"varanegar_p4_control_outcome_vocabulary_checkpoint_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","previous_checkpoint":{"path":S["previous"],"sha256":sha(paths["previous"])},"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"safety":{"database_connections":0,"golden_or_uat_execution":0,"data_mutations":0}};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
