"""Build non-duplicating identity and authorization Golden/UAT delta cases."""
from __future__ import annotations
import argparse,collections,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S={"envelope":"artifacts/varanegar_analysis/varanegar_identity_authorization_outcome_envelope_20260829.json","readiness":"artifacts/varanegar_analysis/varanegar_identity_authorization_readiness_delta_20260829.json","existing":"artifacts/varanegar_analysis/ui/negin_erp_role_uat_cases_20260827.json","sod":"artifacts/varanegar_analysis/ui/negin_erp_role_sod_contract_20260827.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_identity_authorization_readiness_checkpoint_20260829.json"}
F={"IA-DENY":("identity.explicit_deny_precedence","direct/group/inherited allow versus explicit deny"),"IA-SCOPE":("identity.owner_application_data_scope","owner-filtered application/action/data scope"),"IA-END":("identity.endpoint_default_deny","endpoint authorization declaration and server decision"),"IA-ADMIN":("identity.admin_short_circuit","admin capability without ambient bypass"),"IA-SESS":("identity.revocation_session_epoch","atomic revoke, stale token and retry read-back"),"IA-SOD":("identity.sod_break_glass","self-grant exclusion, independent approval and expiry")}
CASES=[("AUTH_DENIED","authorization","REJECTED_NO_EFFECT"),("STALE_POLICY_OR_VERSION","concurrency","REJECTED_NO_EFFECT"),("DUPLICATE_COMMAND","idempotency","ORIGINAL_RECEIPT_ONLY_ONCE"),("SCOPE_OR_POLICY_MISMATCH","validation","REJECTED_OR_QUARANTINED"),("FAIL_AFTER_ASSIGNMENT_OR_EPOCH","failure_injection","ROLLED_BACK_OR_UNKNOWN_REQUIRES_READBACK"),("PARALLEL_GRANT_REVOKE","concurrency","ONE_VERSIONED_DECISION_AND_NO_STALE_ALLOW"),("SUCCESS","success","COMMITTED_WITH_DECISION_AND_AUDIT_RECEIPTS")]
SPECIAL={"IA-DENY":"explicit deny wins over every direct, group, inherited or admin allow and the explain trace names only hashed sources","IA-SCOPE":"application, owner, action and data scopes all match; an owner-unfiltered repository result is rejected","IA-END":"mutating route without approved declaration and application-service decision fails closed","IA-ADMIN":"admin is an explicit capability set subject to scope, SoD, expiry and audit; no ambient bypass","IA-SESS":"revoke and session epoch commit atomically; a token on an older epoch cannot authorize","IA-SOD":"self-grant and incompatible duties reject; break-glass is independently approved, time-bounded and non-renewing"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};old=d["existing"]["cases"];cases=[]
 for prefix,(surface,focus) in F.items():
  for code,kind,expected in CASES:cases.append({"case_id":f"{prefix}-{code}","surface":surface,"case_kind":kind,"focus":focus,"expected_outcome":expected,"assertions":["CommandId, PayloadHash, ExpectedAssignmentVersion and PolicyVersion govern replay","decision, assignment/revocation, audit, outbox and session epoch reconcile atomically","no name, identifier, credential, membership row or raw permission value enters fixture or receipt",SPECIAL[prefix],"source Varanegar/NGT and read-only evidence remain untouched"],"status":"DESIGNED_NOT_EXECUTED"})
 summary={"existing_reused_case_count":len(old),"existing_role_template_count":d["existing"]["summary"]["role_template_count"],"delta_surface_count":len(F),"delta_case_count":len(cases),"combined_identity_acceptance_design_count":len(old)+len(cases),"case_count_per_delta_surface":7,"case_kind_counts":dict(sorted(collections.Counter(x["case_kind"] for x in cases).items())),"executed_delta_case_count":0,"passed_runtime_case_count":0,"owner_approved_case_count":0,"production_assignment_count":0,"runtime_authorization_proven_module_count":0,"command_ready_module_count":0,"pilot_ready_module_count":0,"risk_count":84,"mapped_risk_assignment_count":343,"new_risk_count":0};checks={"sources_pass":all(v.get("validation","PASS")=="PASS" for k,v in d.items() if k!="sod"),"sod_provisional":d["sod"]["status"]=="PROVISIONAL_TEMPLATES_REQUIRE_BUSINESS_OWNER_SIGNOFF","reuse_184":len(old)==184 and summary["existing_role_template_count"]==15,"delta_42":len(cases)==42 and all(sum(x["surface"]==surface for x in cases)==7 for surface,_ in F.values()),"unique_ids":len({x["case_id"] for x in cases})==42,"no_old_collision":not ({x["case_id"] for x in cases}&{x["case_id"] for x in old}),"combined_226":summary["combined_identity_acceptance_design_count"]==226,"all_unexecuted":{x["status"] for x in cases}=={"DESIGNED_NOT_EXECUTED"},"eleven_contract_modules":d["readiness"]["summary"]["outcome_target_contract_module_count_after"]==11,"runtime_zero":summary["executed_delta_case_count"]==summary["passed_runtime_case_count"]==summary["owner_approved_case_count"]==summary["production_assignment_count"]==summary["runtime_authorization_proven_module_count"]==summary["command_ready_module_count"]==summary["pilot_ready_module_count"]==0,"base_stable":d["risk"]["summary"]["risk_count"]==84 and d["trace"]["summary"]["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_identity_authorization_golden_uat_cases_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","safety":{"mode":"OFFLINE_SYNTHETIC_DESIGN","database_connections":0,"network_reads_or_writes":0,"identity_or_authorization_commands_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"identity_values_credentials_or_raw_grants_read_or_persisted":0},"summary":summary,"reuse_manifest":{"source":S["existing"],"policy":"reuse all 184 provisional role/capability/deny/context/SoD cases; do not duplicate them"},"execution_gate":{"environment":"isolated target only","requirements":["synthetic principals represented only by opaque fixture hashes","owner-approved policy, role templates, SoD and break-glass rules","authenticated token/session epoch harness","parallel grant/revoke and stale-policy harness","fault injection at assignment/audit/outbox/session boundaries","mechanical endpoint declaration and application-service authorization coverage"],"promotion_rule":"all 226 reused plus delta obligations execute with zero unexplained decision/scope/session difference and owner approval"},"cases":cases,"checks":checks,"failed_checks":failed,"risk_links":["R-002","R-003","R-004","R-006","R-007","R-024","R-057","R-058","R-059"],"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"confidence":{"design":"HIGH","runtime":"NOT_EXECUTED"},"limits":["These are acceptance designs, not authenticated UAT results.","No identity, assignment, revocation, token or break-glass operation was executed.","No real principal, credential, membership or permission data appears in fixtures."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(summary,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
