"""Build the non-additive work queue for unmatched newer Golden/UAT cases."""
from __future__ import annotations
import argparse,hashlib,json
from collections import Counter,defaultdict
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
S={"core":"artifacts/varanegar_analysis/ui/varanegar_golden_command_cases_20260827.json","orchestrator":"artifacts/varanegar_analysis/ui/varanegar_orchestrator_golden_cases_20260827.json","master":"artifacts/varanegar_analysis/ui/negin_erp_customer_goods_master_golden_cases_20260827.json","extension":"artifacts/varanegar_analysis/ui/varanegar_extension_golden_cases_20260827.json","report_base":"artifacts/varanegar_analysis/ui/varanegar_report_target_contracts_golden_cases_20260827.json","foundation":"artifacts/varanegar_analysis/ui/negin_erp_foundation_context_pricing_golden_cases_20260827.json","bank":"artifacts/varanegar_analysis/ui/negin_erp_bank_reconciliation_golden_cases_20260827.json","pricing":"artifacts/varanegar_analysis/varanegar_pricing_rule_golden_uat_cases_20260829.json","distribution":"artifacts/varanegar_analysis/varanegar_distribution_golden_uat_cases_20260829.json","treasury":"artifacts/varanegar_analysis/varanegar_treasury_golden_uat_cases_20260829.json","accounting":"artifacts/varanegar_analysis/varanegar_accounting_golden_uat_cases_20260829.json","reporting":"artifacts/varanegar_analysis/varanegar_reporting_output_golden_uat_cases_20260829.json","feasibility":"artifacts/varanegar_analysis/varanegar_golden_uat_crosswalk_feasibility_matrix_20260829.json","candidates":"artifacts/varanegar_analysis/varanegar_distribution_treasury_semantic_alias_candidate_packets_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_distribution_treasury_semantic_alias_candidate_checkpoint_20260829.json"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def module(command):
 if command.startswith("master_data."):return "master_data"
 if command.startswith(("order.","sales_return.")):return "sales"
 if command.startswith("distribution."):return "distribution"
 if command.startswith("received_cheque."):return "receivables_treasury"
 if command.startswith(("payable_cheque.","supplier_")):return "procurement_payables"
 if command.startswith(("stock_voucher.","inventory.")):return "inventory"
 raise ValueError(command)
def action(x):return str(x.get("command") or x.get("surface") or x.get("command_id") or "")
def kind(x):return str(x.get("kind") or x.get("case_kind") or "")
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};base=defaultdict(list)
 for source in ("core","orchestrator","master"):
  for row in d[source]["cases"]:base[module(row["command"])].append(row)
 for row in d["extension"]["cases"]:base[row["target_module"]].append(row)
 for row in d["report_base"]["golden_cases"]:base[row["target_module"]].append(row)
 for row in d["foundation"]["cases"]:base[row["target_module"]].append(row)
 base["receivables_treasury"].extend(d["bank"]["cases"])
 newer={"pricing_rules":list(d["pricing"]["cases"]),"distribution":list(d["distribution"]["cases"]),"receivables_treasury":list(d["treasury"]["cases"]),"accounting":list(d["accounting"]["cases"]),"reporting_documents":list(d["reporting"]["cases"])}
 newer["pricing_rules"]=[row for row in d["foundation"]["cases"] if row["target_module"]=="pricing_rules"]+newer["pricing_rules"]
 queue=[]
 for m in ("pricing_rules","distribution","receivables_treasury","accounting","reporting_documents"):
  base_ids={x["case_id"] for x in base[m]};new_ids={x["case_id"] for x in newer[m]};exact=base_ids&new_ids;old=[x for x in base[m] if x["case_id"] not in exact];fresh=[x for x in newer[m] if x["case_id"] not in exact];base_pairs=Counter((action(x).casefold(),kind(x).casefold()) for x in old);used=Counter();remaining=[]
  for x in sorted(fresh,key=lambda row:row["case_id"]):
   key=(action(x).casefold(),kind(x).casefold())
   if used[key]<base_pairs[key]:used[key]+=1
   else:remaining.append(x)
  base_actions=Counter(action(x).casefold() for x in old)
  for x in remaining:
   act=action(x).casefold();knd=kind(x).casefold();gap="ACTION_MATCH_KIND_OR_MULTIPLICITY_GAP" if base_actions[act] else "ACTION_ALIAS_REQUIRED"
   queue.append({"queue_id":f"UGA-{len(queue)+1:03d}","module":m,"newer_case_id":x["case_id"],"newer_action_or_surface":action(x),"newer_case_kind":kind(x),"gap_class":gap,"baseline_same_action_case_count":base_actions[act],"baseline_same_action_kind_case_count":base_pairs[(act,knd)],"current_disposition":"UNRESOLVED","accepted_alias_or_semantic_disposition":False,"counting_effect":"ZERO_UNTIL_ACCEPTED_CASE_LEVEL_SEMANTIC_DISPOSITION","required_packet_fields":["baseline_case_id_or_explicit_none","newer_case_id","versioned_action_or_surface_alias","precondition_equivalence","outcome_vocabulary_mapping","assertion_and_effect_class_mapping","disposition_state","accountable_role","rationale","policy_version_and_expiry"]})
 queue.sort(key=lambda x:(x["module"],x["newer_case_id"]));module_counts=Counter(x["module"] for x in queue);gap_counts=Counter(x["gap_class"] for x in queue);summary={"unmatched_newer_work_queue_count":len(queue),"pricing_queue_count":module_counts["pricing_rules"],"distribution_queue_count":module_counts["distribution"],"treasury_queue_count":module_counts["receivables_treasury"],"accounting_queue_count":module_counts["accounting"],"reporting_queue_count":module_counts["reporting_documents"],"action_alias_required_count":gap_counts["ACTION_ALIAS_REQUIRED"],"action_match_kind_or_multiplicity_gap_count":gap_counts["ACTION_MATCH_KIND_OR_MULTIPLICITY_GAP"],"distinct_unmatched_newer_action_count":len({(x["module"],x["newer_action_or_surface"].casefold()) for x in queue}),"accepted_alias_or_semantic_disposition_count":0,"exact_non_duplicated_additive_count":0,"design_lower_bound_before_queue":d["feasibility"]["summary"]["design_lower_bound_after_crosswalk"],"design_lower_bound_after_queue":d["feasibility"]["summary"]["design_lower_bound_after_crosswalk"],"executed_case_count":0,"owner_approved_case_count":0,"command_ready_module_count":0,"pilot_ready_module_count":0,"risk_count":d["risk"]["summary"]["risk_count"],"mapped_risk_assignment_count":d["trace"]["summary"]["mapped_risk_assignment_count"],"new_risk_count":0}
 checks={"validated_sources_pass":all(d[k].get("validation")=="PASS" for k in d if k!="core"),"legacy_core_pinned":d["core"].get("validation") is None and d["core"]["summary"]["case_count"]==77,"queue_208":summary["unmatched_newer_work_queue_count"]==d["feasibility"]["summary"]["unmatched_newer_case_count"]-d["candidates"]["summary"]["candidate_packet_count"]==208,"module_split_28_4_78_42_56":(summary["pricing_queue_count"],summary["distribution_queue_count"],summary["treasury_queue_count"],summary["accounting_queue_count"],summary["reporting_queue_count"])==(28,4,78,42,56),"gap_split_203_5":summary["action_alias_required_count"]==203 and summary["action_match_kind_or_multiplicity_gap_count"]==5,"thirty_four_actions":summary["distinct_unmatched_newer_action_count"]==34,"all_unresolved_non_additive":all(x["current_disposition"]=="UNRESOLVED" and not x["accepted_alias_or_semantic_disposition"] for x in queue) and summary["exact_non_duplicated_additive_count"]==0,"lower_bound_1404":summary["design_lower_bound_before_queue"]==summary["design_lower_bound_after_queue"]==1404,"execution_readiness_zero":summary["executed_case_count"]==summary["owner_approved_case_count"]==summary["command_ready_module_count"]==summary["pilot_ready_module_count"]==0,"base_stable":summary["risk_count"]==84 and summary["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_unmatched_golden_case_alias_work_queue_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","scope":{"mode":"OFFLINE_UNMATCHED_CASE_ALIAS_DISPOSITION_QUEUE","continuation_complete":False},"safety":{"database_connections":0,"golden_uat_or_operational_execution":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"write_access_created":0,"raw_business_values_identity_or_credentials_persisted":0},"summary":summary,"work_queue":queue,"priority_rule":"ACTION_MATCH_KIND_OR_MULTIPLICITY_GAP first, then action aliases grouped by module/action and accountable owner","checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":p.stat().st_size,"sha256":sha(p)} for k,p in sorted(paths.items())]+[{"name":"builder","path":"scripts/windows/build_varanegar_unmatched_golden_case_alias_work_queue_20260829.py","size_bytes":Path(__file__).stat().st_size,"sha256":sha(Path(__file__))}],"limits":["All 208 cases remain unresolved and add zero.","Queue ordering is not owner disposition.","No case was executed and no readiness state was promoted."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(summary,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
