"""Build chained checkpoint for RPT-05/RPT-07/RPT-08 party cardex."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
S={"contract":"artifacts/varanegar_analysis/domains/party_cardex_reference_contract_20260829.json","boundary":"artifacts/varanegar_analysis/domains/party_cardex_query_bindings_20260829.json","catalog":"artifacts/varanegar_analysis/domains/party_cardex_sql_catalog_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_print_batch_checkpoint_20260829.json","boundary_extractor":"scripts/windows/extract_varanegar_party_cardex_query_bindings_20260829.py","catalog_extractor":"scripts/sql/extract_varanegar_party_cardex_sql_catalog_20260829.py","builder":"scripts/windows/build_varanegar_party_cardex_reference_contract_20260829.py","checkpoint_builder":"scripts/windows/build_varanegar_party_cardex_checkpoint_20260829.py","test":"tests/test_varanegar_party_cardex_reference_contract.py","doc":"docs/varanegar_reconstruction/PARTY_CARDEX_SCOPE_FORMULA_AND_RECONCILIATION_20260829_FA.md"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(paths[k]) for k in ("contract","boundary","catalog","previous")};c=d["contract"];checks={"sources_pass":all(x["validation"]=="PASS" for x in d.values()),"three_reports_six_methods_five_objects":c["summary"]["report_count"]==3 and c["summary"]["exact_method_binding_count"]==6 and c["summary"]["resolved_sql_object_count"]==5,"centralized_branch_explicit":c["summary"]["centralized_external_request_branch_count"]==1,"six_golden_cases":len(c["golden_cases"])==6,"reconciliation_contract_present":len(c["reconciliation_contract"]["classification"])==7,"parity_not_claimed":c["summary"]["result_parity_proven_count"]==0,"risk_stable":c["summary"]["risk_count"]==84,"zero_execution":set(v for k,v in c["safety"].items() if k!="mode")=={0}};failed=sorted(k for k,v in checks.items() if not v);out={"artifact":"varanegar_party_cardex_checkpoint_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","previous_checkpoint":{"path":S["previous"],"sha256":sha(paths["previous"])},"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"safety":{"forms_reports_views_procedures_or_remote_requests_executed":0,"assemblies_loaded_or_executed":0,"database_connections_by_checkpoint":0,"data_mutations":0,"sensitive_values_persisted":0}};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
