from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S={"envelope":"artifacts/varanegar_analysis/varanegar_platform_outcome_envelope_20260829.json","golden":"artifacts/varanegar_analysis/varanegar_platform_golden_uat_cases_20260829.json","stack":"artifacts/varanegar_analysis/ui/negin_erp_stack_recovery_decision_input_20260827.json","deployment":"artifacts/varanegar_analysis/ui/varanegar_deployment_root_reference_scan_20260827.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_platform_golden_uat_checkpoint_20260829.json"}
COMMON=["capture incident time environment command and opaque release/job/control/receipt hashes without credentials endpoints PII or raw values","verify artifact manifest policy approval recovery-tier and schema hashes; stop on drift","read immutable control job audit outbox health reconciliation and external-effect receipts","separate local control commit from external effect and classify missing acknowledgement as unknown","classify NATURAL_BEHAVIOR, DATA_DEBT, BUG or UNPROVEN","quarantine ambiguous manifest job restore failover or rollback outcome before retry","stop before deployment retry restore failover rollback secret rotation repair or traffic change","design isolated provider-approved reproduction with fault injection when evidence remains incomplete"]
B=[("PF-PB-01","release control committed but health/reconciliation receipt is absent","partial release","read external receipt; never infer deployment from local commit",["R-006","R-007","R-026"]),("PF-PB-02","job retry may duplicate an external effect","retry/idempotency","reconcile original payload and effect receipt before retry",["R-006","R-007"]),("PF-PB-03","audit/outbox and control state disagree","control-plane atomicity","pin version and classify unknown before any repair",["R-004","R-007"]),("PF-PB-04","backup exists but restore capability is claimed without drill evidence","restore proof","backup presence is not restore proof; require isolated smoke and reconciliation receipts",["R-019","R-026"]),("PF-PB-05","failover or rollback risks split-brain/mixed version","failover boundary","require fencing manifest and per-consumer version receipts",["R-007","R-019"]),("PF-PB-06","secret endpoint PII or raw business value appears in logs","privacy/secrets","stop and preserve only opaque hashes without reproducing exposure",["R-004","R-056"]),("PF-PB-07","unsafe transport or HTTP method exposes a state-changing operation","transport/auth","deny by default and require authenticated command/action scope",["R-001","R-057","R-062"])]
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};known={x["id"] for x in d["risk"]["risks"]};play=[{"id":i,"incident":inc,"focus":focus,"steps":COMMON+[extra],"stop_conditions":["manifest policy approval or receipt drift","deployment retry restore failover rollback repair or traffic change required","platform/security/business owner decision required","credential endpoint PII or raw value would be read or persisted"],"risks":risks,"runtime_diagnosis":"NOT_PERFORMED"} for i,inc,focus,extra,risks in B]
 s={"playbook_count":len(play),"minimum_step_count":min(len(x["steps"]) for x in play),"command_contract_count":d["envelope"]["summary"]["command_contract_count"],"combined_acceptance_design_count":d["golden"]["summary"]["combined_platform_acceptance_design_count"],"deployment_file_count":d["deployment"]["summary"]["selected_file_count"],"approved_stack_or_recovery_decision_count":0,"runtime_incidents_diagnosed_count":0,"platform_operations_or_repairs_performed_count":0,"credentials_endpoints_pii_or_raw_values_persisted_count":0,"risk_count":84,"mapped_risk_assignment_count":343,"new_risk_count":0};checks={"sources_pass":all(v["validation"]=="PASS" for v in d.values()),"seven_nine":len(play)==7 and all(len(x["steps"])==9 for x in play),"four_way":all("NATURAL_BEHAVIOR, DATA_DEBT, BUG or UNPROVEN" in x["steps"][4] for x in play),"risks_exist":all(r in known for x in play for r in x["risks"]),"scope":s["command_contract_count"]==6 and s["combined_acceptance_design_count"]==42 and s["deployment_file_count"]==853,"runtime_zero":s["approved_stack_or_recovery_decision_count"]==s["runtime_incidents_diagnosed_count"]==s["platform_operations_or_repairs_performed_count"]==s["credentials_endpoints_pii_or_raw_values_persisted_count"]==0,"base_stable":d["risk"]["summary"]["risk_count"]==84 and d["trace"]["summary"]["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_platform_expert_playbook_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","safety":{"mode":"OFFLINE_EVIDENCE_SYNTHESIS","database_connections":0,"network_reads_or_writes":0,"deployments_jobs_restores_failovers_rollbacks_or_repairs_executed":0,"data_mutations":0,"credentials_endpoints_pii_or_raw_business_values_read_or_persisted":0},"summary":s,"playbooks":play,"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"limits":["No named incident was diagnosed.","No platform or recovery action was performed."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(s,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
