from __future__ import annotations
import argparse, hashlib, json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
S={"matrix":"artifacts/varanegar_analysis/varanegar_golden_uat_crosswalk_feasibility_matrix_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_cross_gate_golden_uat_refinement_checkpoint_20260829.json","builder":"scripts/windows/build_varanegar_golden_uat_crosswalk_feasibility_matrix_20260829.py","checkpoint_builder":"scripts/windows/build_varanegar_golden_uat_crosswalk_feasibility_checkpoint_20260829.py","test":"tests/test_varanegar_golden_uat_crosswalk_feasibility_matrix.py","checkpoint_test":"tests/test_varanegar_golden_uat_crosswalk_feasibility_checkpoint.py","doc":"docs/varanegar_reconstruction/GOLDEN_UAT_CROSSWALK_FEASIBILITY_MATRIX_20260829_FA.md"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};m=load(paths["matrix"]);prev=load(paths["previous"]);s=m["summary"]
 checks={"sources_pass":m["validation"]==prev["validation"]=="PASS","five_modules_511_baseline":s["unresolved_module_count"]==5 and s["reconstructed_baseline_case_count"]==511,"represented_302_overlap_64":s["newer_represented_case_count"]==302 and s["exact_case_id_overlap_count"]==64,"unmatched_447_238_candidate_30":s["unmatched_baseline_case_count"]==447 and s["unmatched_newer_case_count"]==238 and s["candidate_casefold_action_kind_row_overlap_count"]==30,"non_additive_1404":s["exact_non_duplicated_additive_count"]==0 and s["design_lower_bound_before_crosswalk"]==s["design_lower_bound_after_crosswalk"]==1404,"acceptance_execution_readiness_zero":s["accepted_semantic_equivalence_count"]==s["accepted_crosswalk_packet_count"]==s["executed_case_count"]==s["owner_approved_case_count"]==s["command_ready_module_count"]==s["pilot_ready_module_count"]==0,"base_stable":s["risk_count"]==84 and s["mapped_risk_assignment_count"]==343,"safety_zero":set(m["safety"].values())=={0}}
 failed=sorted(k for k,v in checks.items() if not v);out={"artifact":"varanegar_golden_uat_crosswalk_feasibility_checkpoint_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","previous_checkpoint":{"path":S["previous"],"sha256":sha(paths["previous"])},"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":p.stat().st_size,"sha256":sha(p)} for k,p in sorted(paths.items())],"safety":{"database_connections":0,"golden_or_uat_execution":0,"data_mutations":0}}
 a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
