"""Build a design-only environment isolation, write-fence, and execution-token contract."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
S={"blueprint":"artifacts/varanegar_analysis/ui/negin_personal_erp_blueprint_20260827.json","authorization":"artifacts/varanegar_analysis/varanegar_target_erp_command_authorization_scope_decision_trace_contract_20260829.json","transaction":"artifacts/varanegar_analysis/varanegar_target_erp_transaction_owner_saga_compensation_contract_20260829.json","redaction":"artifacts/varanegar_analysis/varanegar_target_erp_evidence_logging_redaction_retention_contract_20260829.json","cutover":"artifacts/varanegar_analysis/varanegar_target_erp_migration_cutover_snapshot_delta_reconciliation_contract_20260829.json","cutover_checkpoint":"artifacts/varanegar_analysis/varanegar_target_erp_migration_cutover_snapshot_delta_reconciliation_checkpoint_20260829.json","tests":"artifacts/varanegar_analysis/varanegar_25h_final_test_result_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json"}
ENVIRONMENTS=[("LEGACY_OPERATIONAL_REFERENCE","READ_ONLY_REFERENCE_ONLY_NEVER_COMMAND_TARGET"),("TARGET_SYNTHETIC_SANDBOX","SYNTHETIC_NON_PRODUCTION_COMMAND_CANDIDATE"),("TARGET_ISOLATED_UAT","OWNER_AUTHORIZED_NON_PRODUCTION_UAT_CANDIDATE"),("TARGET_PRODUCTION","PROMOTION_GATED_NOT_AUTHORIZED")]
FENCE_CONTROLS=["EXPLICIT_ENVIRONMENT_ID_NOT_HOSTNAME_INFERENCE","LEGACY_TRANSPORT_READ_ONLY_AND_COMMAND_SURFACE_ABSENT","TARGET_DATABASE_PRINCIPAL_ENVIRONMENT_SCOPED","NETWORK_EGRESS_AND_DESTINATION_ALLOWLIST","ONE_SHOT_TIME_BOUND_EXECUTION_TOKEN","COMMAND_MODULE_AND_RESOURCE_ALLOWLIST","CANONICAL_REQUEST_FINGERPRINT_PINNED","IDEMPOTENCY_KEY_AND_RECEIPT_REQUIRED","EXPECTED_VERSION_AND_OPTIMISTIC_CONCURRENCY_REQUIRED","TRANSACTION_OWNER_AND_OUTBOX_POLICY_PINNED","AUTHORIZATION_DECISION_AND_SOD_RECEIPTS_CURRENT","DATA_REDACTION_AND_AUDIT_SCHEMA_PINNED","KILL_SWITCH_REVOCATION_AND_INCIDENT_ROUTE_TESTED","PRODUCTION_PROMOTION_RECEIPT_SEPARATE_FROM_UAT_SUCCESS"]
NEGATIVE_CASES=[("EFN-01","missing_or_unknown_environment_id"),("EFN-02","hostname_path_or_connection_string_environment_inference_attempt"),("EFN-03","legacy_operational_command_or_write_attempt"),("EFN-04","target_sandbox_token_replayed_in_uat_or_production"),("EFN-05","expired_revoked_used_or_superseded_execution_token"),("EFN-06","command_module_or_resource_not_in_token_allowlist"),("EFN-07","request_fingerprint_or_idempotency_key_mismatch"),("EFN-08","authorization_sod_or_policy_receipt_stale"),("EFN-09","expected_version_or_transaction_policy_mismatch"),("EFN-10","network_destination_or_egress_not_allowlisted"),("EFN-11","break_glass_or_admin_bypass_without_independent_receipt"),("EFN-12","uat_success_used_as_automatic_production_promotion")]
TOKEN_FIELDS=["token_id","environment_id","environment_class","module_id","target_command_id","tenant_reference_sha256","organization_context_reference_sha256","resource_scope_reference_set_sha256","canonical_request_fingerprint_sha256","idempotency_key_sha256","expected_version_set_sha256","authorization_decision_receipt_sha256","transaction_policy_version_sha256","redaction_policy_version_sha256","issued_at","not_before","expires_at","single_use_nonce_sha256","independent_approval_receipt_reference","token_sha256"]
GATES=[("EFG-01","environment_identity_explicit_and_attested"),("EFG-02","legacy_command_and_write_surface_absent"),("EFG-03","legacy_reference_transport_read_only_proven"),("EFG-04","target_principal_and_storage_environment_scoped"),("EFG-05","network_destination_and_egress_allowlist_proven"),("EFG-06","one_shot_token_signature_freshness_and_revocation_valid"),("EFG-07","command_module_resource_and_context_allowlists_exact"),("EFG-08","request_fingerprint_idempotency_and_expected_versions_exact"),("EFG-09","authorization_sod_and_policy_receipts_current"),("EFG-10","transaction_outbox_and_compensation_policy_pinned"),("EFG-11","redaction_audit_and_retention_policy_pinned"),("EFG-12","finite_deadline_attempt_limit_and_cancellation_pinned"),("EFG-13","kill_switch_and_revocation_propagation_tested"),("EFG-14","negative_environment_and_token_cases_executed"),("EFG-15","sandbox_and_uat_use_no_production_data_or_endpoints"),("EFG-16","production_change_window_and rollback receipt current"),("EFG-17","uat_acceptance_does_not_auto_promote_production"),("EFG-18","security_operations_business_and_independent_approvals_current")]
ROLES=["ENVIRONMENT_POLICY_OWNER_ROLE","SECURITY_TOKEN_ISSUER_ROLE","UAT_EXECUTION_OPERATOR_ROLE","PRODUCTION_CHANGE_OPERATOR_ROLE","BUSINESS_COMMAND_OWNER_ROLE","INDEPENDENT_PROMOTION_APPROVER_ROLE"]
OUTCOMES=["TOKEN_VALID_FOR_EXACT_NON_PRODUCTION_COMMAND","DENY_UNKNOWN_OR_MISMATCHED_ENVIRONMENT","DENY_LEGACY_COMMAND_OR_WRITE_ATTEMPT","DENY_TOKEN_EXPIRED_REVOKED_USED_OR_SUPERSEDED","DENY_COMMAND_MODULE_RESOURCE_OR_CONTEXT_SCOPE","DENY_FINGERPRINT_IDEMPOTENCY_OR_VERSION_MISMATCH","DENY_POLICY_AUTHORIZATION_OR_SOD_RECEIPT","DENY_NETWORK_OR_PRINCIPAL_FENCE","DENY_BREAK_GLASS_OR_PROMOTION_APPROVAL","DENY_PRODUCTION_NOT_SEPARATELY_AUTHORIZED"]
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 p=argparse.ArgumentParser();p.add_argument("--output",required=True,type=Path);a=p.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};mods=d["blueprint"]["modules"]
 commands=[]
 for m in mods:
  for name in m["commands"]:commands.append({"target_command_id":f"TCMD-{len(commands)+1:03d}","module_id":m["id"],"command_name":name,"execution_token_status":"NOT_ISSUED","runtime_environment_fence_status":"UNPROVEN","command_execution_count":0,"command_readiness":False})
 env_assign=[{"target_command_id":c["target_command_id"],"environment_id":e,"authorization_status":"NOT_AUTHORIZED","execution_count":0} for c in commands for e,_ in ENVIRONMENTS]
 fence_assign=[{"environment_id":e,"fence_control":f,"status":"UNPROVEN","accepted_attestation_count":0} for e,_ in ENVIRONMENTS for f in FENCE_CONTROLS]
 negatives=[{"target_command_id":c["target_command_id"],"negative_case_id":i,"status":"UNEXECUTED","accepted_result_count":0} for c in commands for i,_ in NEGATIVE_CASES]
 gates=[{"target_command_id":c["target_command_id"],"gate_id":i,"status":"UNMET","accepted_evidence_count":0} for c in commands for i,_ in GATES]
 roles=[{"target_command_id":c["target_command_id"],"role_type":r,"status":"UNASSIGNED","role_receipt_reference":None} for c in commands for r in ROLES];o=d["tests"]
 s={"module_count":len(mods),"target_command_count":len(commands),"environment_count":len(ENVIRONMENTS),"command_environment_assignment_count":len(env_assign),"fence_control_count":len(FENCE_CONTROLS),"environment_fence_assignment_count":len(fence_assign),"negative_case_count":len(NEGATIVE_CASES),"command_negative_case_assignment_count":len(negatives),"execution_token_field_count":len(TOKEN_FIELDS),"gate_count":len(GATES),"command_gate_assignment_count":len(gates),"role_type_count":len(ROLES),"command_role_assignment_count":len(roles),"typed_outcome_count":len(OUTCOMES),"issued_execution_token_count":0,"legacy_operational_connection_or_command_count":0,"target_sandbox_command_run_count":0,"target_uat_command_run_count":0,"target_production_command_run_count":0,"accepted_runtime_fence_attestation_count":0,"owner_approved_command_count":0,"command_ready_count":0,"pilot_ready_module_count":0,"design_lower_bound_before_environment_contract":1404,"design_lower_bound_after_environment_contract":1404,"official_test_file_count":o["runner"]["test_file_count"],"official_passed_test_count":o["runner"]["passed_test_count"],"risk_count":d["risk"]["summary"]["risk_count"],"mapped_risk_assignment_count":d["trace"]["summary"]["mapped_risk_assignment_count"],"new_risk_count":0}
 checks={"sources_pass":all(d[k].get("validation")=="PASS" for k in ("authorization","transaction","redaction","cutover","cutover_checkpoint","tests")),"coverage_14_modules_49_commands_4_envs_196":(s["module_count"],s["target_command_count"],s["environment_count"],s["command_environment_assignment_count"])==(14,49,4,196),"fences_14_assignments_56":(s["fence_control_count"],s["environment_fence_assignment_count"])==(14,56),"negative_12_assignments_588":(s["negative_case_count"],s["command_negative_case_assignment_count"])==(12,588),"token_fields_20_gates_18_assignments_882":(s["execution_token_field_count"],s["gate_count"],s["command_gate_assignment_count"])==(20,18,882),"roles_6_assignments_294_outcomes_10":(s["role_type_count"],s["command_role_assignment_count"],s["typed_outcome_count"])==(6,294,10),"all_authorization_fence_negative_gate_role_states_open":all(x["authorization_status"]=="NOT_AUTHORIZED" for x in env_assign) and all(x["status"]=="UNPROVEN" for x in fence_assign) and all(x["status"]=="UNEXECUTED" for x in negatives) and all(x["status"]=="UNMET" for x in gates) and all(x["status"]=="UNASSIGNED" for x in roles),"tokens_connections_runs_fence_readiness_zero":s["issued_execution_token_count"]==s["legacy_operational_connection_or_command_count"]==s["target_sandbox_command_run_count"]==s["target_uat_command_run_count"]==s["target_production_command_run_count"]==s["accepted_runtime_fence_attestation_count"]==s["owner_approved_command_count"]==s["command_ready_count"]==s["pilot_ready_module_count"]==0,"non_additive_1404":s["design_lower_bound_before_environment_contract"]==s["design_lower_bound_after_environment_contract"]==1404,"official_tests_pass":o["validation"]=="PASS" and o["runner"]["bootstrap_excluded_test_file_count"]==0,"base_stable":s["risk_count"]==84 and s["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_target_erp_environment_isolation_write_fence_execution_token_contract_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","scope":{"mode":"environment_isolation_and_execution_token_design_only","continuation_complete":False,"connection_token_or_command_execution_authorized":False,"environment_endpoint_principal_or_provider_selected":False},"safety":{"database_connections":0,"network_reads_or_writes":0,"execution_tokens_issued_or_consumed":0,"legacy_or_target_commands_executed":0,"operational_forms_reports_queries_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"credentials_endpoints_tokens_pii_or_raw_business_values_read_or_persisted":0},"summary":s,"risk_links":["R-001","R-004","R-006","R-007","R-023","R-025"],"environments":[{"environment_id":e,"policy":x} for e,x in ENVIRONMENTS],"fence_controls":FENCE_CONTROLS,"negative_cases":[{"negative_case_id":i,"negative_case":x} for i,x in NEGATIVE_CASES],"execution_token_fields":TOKEN_FIELDS,"gates":[{"gate_id":i,"gate":x,"failure_effect":"EXECUTION_DENIED"} for i,x in GATES],"role_types":ROLES,"typed_outcomes":OUTCOMES,"target_commands":commands,"command_environment_assignments":env_assign,"environment_fence_assignments":fence_assign,"command_negative_case_assignments":negatives,"command_gate_assignments":gates,"command_role_assignments":roles,"environment_and_token_rule":{"legacy_operational_write_or_command_allowed":False,"legacy_reference_read_without_explicit_read_only_transport_allowed":False,"environment_may_be_inferred_from_hostname_path_or_connection_string":False,"sandbox_or_uat_token_may_be_replayed_in_production":False,"expired_revoked_used_or_superseded_token_allowed":False,"break_glass_or_admin_bypasses_independent_approval":False,"uat_success_automatically_promotes_production":False,"production_command_allowed_without_separate_change_and_rollback_receipt":False,"secret_endpoint_or_raw_business_value_may_be_persisted_in_token_or_evidence":False,"automatic_execution_authorization_or_readiness":False},"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())]+[{"name":"builder","path":"scripts/windows/build_varanegar_target_erp_environment_isolation_write_fence_execution_token_contract_20260829.py","size_bytes":Path(__file__).stat().st_size,"sha256":sha(Path(__file__))}],"limits":["This is an execution safety design; no endpoint credential principal connection token command or environment was accessed or selected.","Legacy operational Varanegar is never a command target and target production remains separately blocked.","No environment is authorized until runtime fence negative tests and independent approvals produce current receipts."]}
 a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(s,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
