"""Build outcome-vocabulary packets for 58 non-failure P2 pairs."""
from __future__ import annotations
import argparse,hashlib,json
from collections import defaultdict
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
S={"comparator":"artifacts/varanegar_analysis/varanegar_p2_alias_semantic_evidence_comparator_20260829.json","shortlist":"artifacts/varanegar_analysis/varanegar_p2_alias_baseline_candidate_shortlist_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_p2_failure_injection_adjudication_checkpoint_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json"}
FIELDS=["control_kind","source_packet_and_case_ids","newer_outcome_label","baseline_outcome_label","label_equivalence_disposition","precondition_equivalence","assertion_effect_equivalence","denial_or_commit_effect_class","retry_or_current_version_contract","accountable_role_receipts","policy_version_expiry_supersession"]
KINDS=("authorization","concurrency","idempotency","scope","success","validation")
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};roles={x["source_packet_id"]:x["accountable_role_types"] for x in d["shortlist"]["p2_candidate_packets"]};g=defaultdict(list)
 for c in d["comparator"]["candidate_comparisons"]:
  for row in c["case_pair_comparisons"]:
   if row["case_kind"]=="failure_injection":continue
   g[row["case_kind"]].append({"source_packet_id":c["source_packet_id"],"comparison_id":c["comparison_id"],"newer_action_or_surface":c["newer_action_or_surface"],"baseline_action":c["baseline_action"],**row})
 packets=[]
 for i,k in enumerate(KINDS,1):
  rows=g[k];ids=sorted({x["source_packet_id"] for x in rows});nv=sorted({x["newer_outcome_label"] for x in rows});bv=sorted({x["baseline_outcome_label"] for x in rows});packets.append({"outcome_packet_id":f"P2O-{i:02d}","control_kind":k,"source_packet_ids":ids,"accountable_role_types":sorted({r for pid in ids for r in roles[pid]}),"case_pair_count":len(rows),"newer_outcome_vocabulary":nv,"baseline_outcome_vocabulary":bv,"newer_outcome_vocabulary_count":len(nv),"baseline_outcome_vocabulary_count":len(bv),"outcome_label_exact_pair_count":sum(x["outcome_exact"] for x in rows),"outcome_label_mapping_required_pair_count":sum(not x["outcome_exact"] for x in rows),"assertion_list_exact_pair_count":sum(x["assertion_list_exact"] for x in rows),"pair_rows":rows,"required_disposition_fields":FIELDS,"current_status":"WAITING_FOR_OUTCOME_VOCABULARY_AND_EFFECT_DISPOSITION","accepted_pair_count":0,"counting_effect":"ZERO"})
 rows=[x for p in packets for x in p["pair_rows"]];s={"control_kind_packet_count":len(packets),"non_failure_case_pair_count":len(rows),"authorization_pair_count":len(g["authorization"]),"concurrency_pair_count":len(g["concurrency"]),"idempotency_pair_count":len(g["idempotency"]),"scope_pair_count":len(g["scope"]),"success_pair_count":len(g["success"]),"validation_pair_count":len(g["validation"]),"global_newer_outcome_vocabulary_count":len({x["newer_outcome_label"] for x in rows}),"global_baseline_outcome_vocabulary_count":len({x["baseline_outcome_label"] for x in rows}),"per_kind_newer_outcome_vocabulary_count":sum(p["newer_outcome_vocabulary_count"] for p in packets),"per_kind_baseline_outcome_vocabulary_count":sum(p["baseline_outcome_vocabulary_count"] for p in packets),"generic_rejected_no_effect_pair_count":sum(x["newer_outcome_label"]=="rejected_no_effect" for x in rows),"generic_committed_original_once_pair_count":sum(x["newer_outcome_label"]=="committed_original_outcome_only_once" for x in rows),"outcome_label_exact_pair_count":sum(x["outcome_exact"] for x in rows),"outcome_label_mapping_required_pair_count":sum(not x["outcome_exact"] for x in rows),"assertion_list_exact_pair_count":sum(x["assertion_list_exact"] for x in rows),"fully_exact_pair_count":sum(x["fully_exact"] for x in rows),"accountable_role_assignment_count":sum(len(p["accountable_role_types"]) for p in packets),"required_disposition_field_count":len(FIELDS),"accepted_outcome_pair_count":0,"exact_non_duplicated_additive_count":0,"design_lower_bound_before_outcome_adjudication":1404,"design_lower_bound_after_outcome_adjudication":1404,"executed_case_count":0,"owner_approved_case_count":0,"command_ready_module_count":0,"pilot_ready_module_count":0,"risk_count":d["risk"]["summary"]["risk_count"],"mapped_risk_assignment_count":d["trace"]["summary"]["mapped_risk_assignment_count"],"new_risk_count":0}
 checks={"sources_pass":all(x.get("validation")=="PASS" for x in d.values()),"six_58":s["control_kind_packet_count"]==6 and s["non_failure_case_pair_count"]==58,"distribution":(s["authorization_pair_count"],s["concurrency_pair_count"],s["idempotency_pair_count"],s["scope_pair_count"],s["success_pair_count"],s["validation_pair_count"])==(7,11,10,2,6,22),"vocab":(s["global_newer_outcome_vocabulary_count"],s["global_baseline_outcome_vocabulary_count"],s["per_kind_newer_outcome_vocabulary_count"],s["per_kind_baseline_outcome_vocabulary_count"])==(6,23,9,27),"generic_38_2":(s["generic_rejected_no_effect_pair_count"],s["generic_committed_original_once_pair_count"])==(38,2),"exactness_2_56_0_0":(s["outcome_label_exact_pair_count"],s["outcome_label_mapping_required_pair_count"],s["assertion_list_exact_pair_count"],s["fully_exact_pair_count"])==(2,56,0,0),"roles_fields":s["accountable_role_assignment_count"]==22 and s["required_disposition_field_count"]==11,"non_additive_1404":s["accepted_outcome_pair_count"]==s["exact_non_duplicated_additive_count"]==0 and s["design_lower_bound_before_outcome_adjudication"]==s["design_lower_bound_after_outcome_adjudication"]==1404,"execution_readiness_zero":s["executed_case_count"]==s["owner_approved_case_count"]==s["command_ready_module_count"]==s["pilot_ready_module_count"]==0,"base_stable":s["risk_count"]==84 and s["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_p2_control_outcome_vocabulary_adjudication_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","scope":{"mode":"OFFLINE_P2_CONTROL_OUTCOME_VOCABULARY_ADJUDICATION","continuation_complete":False},"safety":{"database_connections":0,"golden_uat_or_operational_execution":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"write_access_created":0,"raw_business_values_identity_or_credentials_persisted":0},"summary":s,"required_disposition_fields":FIELDS,"outcome_adjudication_packets":packets,"interpretation_rule":"normalized schema and isolated outcome equality do not prove effect equivalence; every pair needs explicit precondition/assertion/effect disposition","checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":p.stat().st_size,"sha256":sha(p)} for k,p in sorted(paths.items())]+[{"name":"builder","path":"scripts/windows/build_varanegar_p2_control_outcome_vocabulary_adjudication_20260829.py","size_bytes":Path(__file__).stat().st_size,"sha256":sha(Path(__file__))}],"limits":["Vocabulary mapping is design evidence only.","Two equal outcomes lack precondition/assertion equivalence.","No pair is accepted."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(s,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
