"""Build evidence-first configuration expert playbooks."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S={"envelope":"artifacts/varanegar_analysis/varanegar_configuration_outcome_envelope_20260829.json","golden":"artifacts/varanegar_analysis/varanegar_configuration_golden_uat_cases_20260829.json","precedence":"artifacts/varanegar_analysis/domains/configuration_precedence_boundary_20260829.json","runtime":"artifacts/varanegar_analysis/domains/ngt_configuration_runtime_boundary_20260829.json","navigation":"artifacts/varanegar_analysis/ui/varanegar_system_configuration_navigation_contract_20260827.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_configuration_golden_uat_checkpoint_20260829.json"}
COMMON=["capture CommandId, aggregate/version, configuration family, scope, effective window, schema/policy/public-value/secret-reference/rollout hashes without configuration or secret values","verify evidence, schema and policy hashes and stop on drift","read version, effective pointer, ResolutionTrace, audit, outbox and per-consumer acknowledgement receipts","recompute candidate eligibility and precedence from typed metadata; never infer winner from storage order","classify NATURAL_BEHAVIOR, DATA_DEBT, BUG or UNPROVEN","quarantine ambiguous, removed-reference, secret-policy or partial-ack outcomes before retry","stop before publish, pointer rewrite, secret access, acknowledgement synthesis, rollback or cache repair","design isolated synthetic/fault-injection reproduction when the boundary remains unproven"]
BASE=[("CF-PB-01","different consumers resolve different effective values","multi-table precedence and scope","compare candidate sets and ResolutionTrace; a missing trace or unapproved winner is UNPROVEN",["R-002","R-031","R-036"]),("CF-PB-02","result changes between identical reads","TOP 1 without ORDER BY or unstable tie","pin the exact resolver and candidates; replace storage-order dependence with the approved stable tuple",["R-002","R-005","R-034"]),("CF-PB-03","null value inherits, clears or disables unexpectedly","typed null semantics","distinguish INHERIT, EXPLICIT_NULL and VALUE by key schema; never coalesce unknown null silently",["R-002","R-006","R-031"]),("CF-PB-04","active child references a removed device setting","removed candidate and referential lifecycle","preserve the reference and quarantine until an approved replacement/version exists; never reactivate silently",["R-007","R-008","R-036"]),("CF-PB-05","secret or endpoint configuration is exposed or rejected","public endpoint policy versus secret reference","verify only vault-handle metadata and policy; stop if any secret value appears in evidence, result or log",["R-006","R-023","R-036"]),("CF-PB-06","some consumers acknowledge a version and others do not","partial rollout acknowledgement","compare per-consumer version/hash/receipt; do not call the rollout globally active from a partial fold",["R-005","R-007","R-034"]),("CF-PB-07","rollback leaves mixed consumer versions or loses history","rollback-by-new-version","read pointer/outbox/ack receipts, publish prior content as a new version and retain every failed acknowledgement",["R-005","R-007","R-036"])]
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 p=argparse.ArgumentParser();p.add_argument("--output",required=True,type=Path);a=p.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};play=[{"id":i,"incident":inc,"focus":focus,"steps":COMMON+[extra],"stop_conditions":["evidence/schema/policy hash drift","write, publish, ack synthesis, rollback or cache repair required","owner policy required","configuration or secret values would be persisted"],"risks":risks,"runtime_diagnosis":"NOT_PERFORMED"} for i,inc,focus,extra,risks in BASE];known={x["id"] for x in d["risk"]["risks"]};summary={"playbook_count":len(play),"minimum_step_count":min(len(x["steps"]) for x in play),"command_contract_count":d["envelope"]["summary"]["command_contract_count"],"combined_acceptance_design_count":d["golden"]["summary"]["combined_configuration_acceptance_design_count"],"runtime_incidents_diagnosed_count":0,"publishes_acks_rollbacks_or_repairs_performed_count":0,"owner_approved_count":0,"risk_count":84,"mapped_risk_assignment_count":343,"new_risk_count":0}
 checks={"sources_pass":all(v["validation"]=="PASS" for v in d.values()),"seven_playbooks":len(play)==7,"nine_steps":all(len(x["steps"])==9 for x in play),"four_way":all("NATURAL_BEHAVIOR, DATA_DEBT, BUG or UNPROVEN" in x["steps"][4] for x in play),"risks_exist":all(r in known for x in play for r in x["risks"]),"scope":summary["command_contract_count"]==5 and summary["combined_acceptance_design_count"]==82,"precedence_secret_rollback":any("TOP 1" in " ".join([x["incident"],x["focus"],*x["steps"]]) for x in play) and any("secret" in x["focus"] for x in play) and any("rollback-by-new-version" in x["focus"] for x in play),"runtime_zero":summary["runtime_incidents_diagnosed_count"]==summary["publishes_acks_rollbacks_or_repairs_performed_count"]==summary["owner_approved_count"]==0,"base_stable":d["risk"]["summary"]["risk_count"]==84 and d["trace"]["summary"]["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_configuration_expert_playbook_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","safety":{"mode":"OFFLINE_EVIDENCE_SYNTHESIS","database_connections":0,"network_reads_or_writes":0,"configuration_commands_or_forms_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"secret_or_business_values_read_or_persisted":0},"summary":summary,"playbooks":play,"diagnostic_result_contract":{"allowed":["NATURAL_BEHAVIOR","DATA_DEBT","BUG","UNPROVEN"],"requires_named_incident_evidence":True,"publish_ack_rollback_or_repair_is_separate_authorized_work":True},"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"confidence":{"structure":"HIGH","incident_diagnosis":"REQUIRES_INCIDENT_EVIDENCE"},"limits":["No named incident was diagnosed.","No configuration publish, acknowledgement, rollback, secret access or repair was executed.","No production-current effective configuration is claimed."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(summary,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
