"""Build synthetic conformance evidence for the pure redaction reference validator."""
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
from varanegar_evidence_redaction_reference import ALLOWED_FIELDS,FORBIDDEN_FIELD_CODES,validate_evidence

ROOT=Path(__file__).resolve().parents[2]
S={"redaction":"artifacts/varanegar_analysis/varanegar_target_erp_evidence_logging_redaction_retention_contract_20260829.json","redaction_checkpoint":"artifacts/varanegar_analysis/varanegar_target_erp_evidence_logging_redaction_retention_checkpoint_20260829.json","tests":"artifacts/varanegar_analysis/varanegar_25h_final_test_result_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json"}
NEGATIVE_MUTATIONS=[
 ("RLN-01","credential","PROHIBITED_CREDENTIAL_FIELD"),("RLN-02","auth_token","PROHIBITED_TOKEN_FIELD"),
 ("RLN-03","identity_pii","PROHIBITED_IDENTITY_PII_FIELD"),("RLN-04","business_identifier","PROHIBITED_BUSINESS_IDENTIFIER_FIELD"),
 ("RLN-05","commercial_value","PROHIBITED_COMMERCIAL_VALUE_FIELD"),("RLN-06","payment_value","PROHIBITED_PAYMENT_FIELD"),
 ("RLN-07","payload","PROHIBITED_PAYLOAD_FIELD"),("RLN-08","sql_or_rule","PROHIBITED_SQL_RULE_FIELD"),
 ("RLN-09","file_or_binary","PROHIBITED_FILE_BINARY_FIELD"),("RLN-10","endpoint_or_path","PROHIBITED_ENDPOINT_PATH_FIELD"),
 ("RLN-11","crypto_material","PROHIBITED_CRYPTO_MATERIAL_FIELD"),("RLN-12","stack_or_dump","PROHIBITED_STACK_DUMP_FIELD"),
 ("RLN-13","backup_log_message_export","PROHIBITED_BULK_CONTENT_FIELD"),("RLN-14","unknown_nested","UNKNOWN_OR_NESTED_PAYLOAD"),
]
GATES=["REFERENCE_MODULE_IMPORTS_WITHOUT_IO","POSITIVE_ENVELOPE_ALLOWLIST_COMPLETE","HASH_FIELDS_LOWERCASE_HEX64","OPAQUE_REFERENCE_NON_RAW_SHAPE","COUNT_STATUS_TIME_ROLE_BOOLEAN_TYPES_VALID","EACH_NEGATIVE_MUTATION_ADDS_EXACTLY_ONE_FIELD","EXPECTED_REJECTION_CODE_MATCHES","NO_REAL_LOG_PAYLOAD_OR_RUNTIME_SAMPLE_USED"]
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def baseline(seed):
 h=hashlib.sha256(seed.encode()).hexdigest();v=hashlib.sha256((seed+":version").encode()).hexdigest();return {"domain_sha256":h,"opaque_reference":"REF:"+hashlib.sha256((seed+":ref").encode()).hexdigest(),"aggregate_count":7,"status":"SYNTHETIC_ACCEPTED","version_sha256":v,"observed_at":"2030-01-02T03:04:05+00:00","role_type":"SYNTHETIC_REVIEWER_ROLE","gate_passed":True}
def main():
 p=argparse.ArgumentParser();p.add_argument("--output",required=True,type=Path);a=p.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};channels=d["redaction"]["evidence_channels"];positive=[];negative=[]
 for channel in channels:
  base=baseline(channel);result=validate_evidence(channel,base);positive.append({"evidence_channel":channel,"field_set":sorted(base),"field_set_sha256":hashlib.sha256(json.dumps(sorted(base),separators=(",",":")).encode()).hexdigest(),"accepted":result["accepted"],"actual_code":result["code"],"status":"PASS" if result=={"accepted":True,"code":"ALLOWLISTED_HASH_ONLY_EVIDENCE_ACCEPTED"} else "FAIL"})
  for vector,field,expected in NEGATIVE_MUTATIONS:
   payload=dict(base);payload[field]={"synthetic":"nested"} if field=="unknown_nested" else "SYNTHETIC_FORBIDDEN_TOKEN";result=validate_evidence(channel,payload);negative.append({"evidence_channel":channel,"negative_vector_id":vector,"mutated_field":field,"changed_field_count":1,"expected_code":expected,"actual_code":result["code"],"accepted":result["accepted"],"status":"PASS" if not result["accepted"] and result["code"]==expected else "FAIL"})
 gate_assign=[{"evidence_channel":c,"gate":g,"status":"PASS_SYNTHETIC_REFERENCE_ONLY"} for c in channels for g in GATES];o=d["tests"];s={"evidence_channel_count":len(channels),"allowed_field_count":len(ALLOWED_FIELDS),"prohibited_field_code_count":len(FORBIDDEN_FIELD_CODES),"negative_mutation_count":len(NEGATIVE_MUTATIONS),"positive_execution_count":len(positive),"positive_pass_count":sum(x["status"]=="PASS" for x in positive),"negative_execution_count":len(negative),"negative_pass_count":sum(x["status"]=="PASS" for x in negative),"synthetic_execution_count":len(positive)+len(negative),"synthetic_pass_count":sum(x["status"]=="PASS" for x in positive+negative),"gate_count":len(GATES),"channel_gate_assignment_count":len(gate_assign),"reference_validator_implementation_count":1,"operational_logging_redaction_implementation_count":0,"real_log_or_runtime_sample_scan_count":0,"accepted_runtime_attestation_count":0,"command_ready_count":0,"pilot_ready_module_count":0,"design_lower_bound_before_reference_validator":1404,"design_lower_bound_after_reference_validator":1404,"official_test_file_count":o["runner"]["test_file_count"],"official_passed_test_count":o["runner"]["passed_test_count"],"risk_count":d["risk"]["summary"]["risk_count"],"mapped_risk_assignment_count":d["trace"]["summary"]["mapped_risk_assignment_count"],"new_risk_count":0}
 checks={"sources_pass":all(d[k].get("validation")=="PASS" for k in ("redaction","redaction_checkpoint","tests")),"channels_10_allowed_8_codes_13_mutations_14":(s["evidence_channel_count"],s["allowed_field_count"],s["prohibited_field_code_count"],s["negative_mutation_count"])==(10,8,13,14),"positive_10_of_10":s["positive_execution_count"]==s["positive_pass_count"]==10,"negative_140_of_140":s["negative_execution_count"]==s["negative_pass_count"]==140,"total_150_of_150":s["synthetic_execution_count"]==s["synthetic_pass_count"]==150,"gates_8_assignments_80":(s["gate_count"],s["channel_gate_assignment_count"])==(8,80),"exact_one_field_mutation":all(x["changed_field_count"]==1 for x in negative),"reference_one_operational_runtime_zero":s["reference_validator_implementation_count"]==1 and s["operational_logging_redaction_implementation_count"]==s["real_log_or_runtime_sample_scan_count"]==s["accepted_runtime_attestation_count"]==s["command_ready_count"]==s["pilot_ready_module_count"]==0,"non_additive_1404":s["design_lower_bound_before_reference_validator"]==s["design_lower_bound_after_reference_validator"]==1404,"official_tests_pass":o["validation"]=="PASS" and o["runner"]["bootstrap_excluded_test_file_count"]==0,"base_stable":s["risk_count"]==84 and s["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_target_erp_evidence_redaction_synthetic_reference_validator_contract_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","scope":{"mode":"pure_synthetic_reference_validator_without_io","continuation_complete":False,"operational_logging_redaction_implemented_or_executed":False},"safety":{"database_connections":0,"network_reads_or_writes":0,"real_logs_traces_backups_messages_exports_or_runtime_samples_read":0,"operational_scanners_or_logging_pipelines_executed":0,"operational_forms_reports_queries_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"credentials_tokens_identity_pii_or_raw_business_values_read_or_persisted":0},"summary":s,"risk_links":["R-004","R-001","R-023"],"allowed_fields":sorted(ALLOWED_FIELDS),"forbidden_field_codes":FORBIDDEN_FIELD_CODES,"negative_mutations":[{"negative_vector_id":i,"mutated_field":f,"expected_code":e} for i,f,e in NEGATIVE_MUTATIONS],"gates":GATES,"positive_results":positive,"negative_results":negative,"channel_gate_assignments":gate_assign,"reference_rule":{"validator_has_io":False,"unknown_field_or_nested_payload_allowed":False,"mutation_changes_exactly_one_field":True,"synthetic_pass_proves_operational_redaction":False,"automatic_runtime_attestation_or_readiness":False},"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())]+[{"name":"builder","path":"scripts/windows/build_varanegar_target_erp_evidence_redaction_synthetic_reference_validator_contract_20260829.py","size_bytes":Path(__file__).stat().st_size,"sha256":sha(Path(__file__))},{"name":"reference_validator","path":"scripts/windows/varanegar_evidence_redaction_reference.py","size_bytes":(ROOT/"scripts/windows/varanegar_evidence_redaction_reference.py").stat().st_size,"sha256":sha(ROOT/"scripts/windows/varanegar_evidence_redaction_reference.py")}],"limits":["Only synthetic tokens are validated; no real log trace message file backup export or runtime sample is read.","The pure reference validator is not an operational logging redaction implementation or security scanner.","Synthetic PASS does not create runtime attestation command readiness or pilot readiness."]}
 a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(s,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
