from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];S={"packets":"artifacts/varanegar_analysis/varanegar_distribution_treasury_semantic_alias_candidate_packets_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_golden_uat_crosswalk_feasibility_checkpoint_20260829.json","builder":"scripts/windows/build_varanegar_distribution_treasury_semantic_alias_candidate_packets_20260829.py","checkpoint_builder":"scripts/windows/build_varanegar_distribution_treasury_semantic_alias_candidate_checkpoint_20260829.py","test":"tests/test_varanegar_distribution_treasury_semantic_alias_candidate_packets.py","checkpoint_test":"tests/test_varanegar_distribution_treasury_semantic_alias_candidate_checkpoint.py","doc":"docs/varanegar_reconstruction/DISTRIBUTION_TREASURY_SEMANTIC_ALIAS_CANDIDATE_PACKETS_20260829_FA.md"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 q=argparse.ArgumentParser();q.add_argument("--output",required=True,type=Path);a=q.parse_args();paths={k:ROOT/v for k,v in S.items()};p=load(paths["packets"]);prev=load(paths["previous"]);s=p["summary"];checks={"sources_pass":p["validation"]==prev["validation"]=="PASS","thirty_24_6":s["candidate_packet_count"]==30 and s["distribution_candidate_packet_count"]==24 and s["treasury_candidate_packet_count"]==6,"five_outcome_zero_assertion":s["expected_outcome_label_exact_equal_count"]==5 and s["assertion_list_exact_equal_count"]==s["fully_exact_candidate_count"]==0,"all_review_none_accepted":s["review_required_packet_count"]==30 and s["accepted_semantic_equivalence_count"]==0,"non_additive_1404":s["exact_non_duplicated_additive_count"]==0 and s["design_lower_bound_before_alias_review"]==s["design_lower_bound_after_alias_review"]==1404,"execution_readiness_zero":s["executed_case_count"]==s["owner_approved_case_count"]==s["command_ready_module_count"]==s["pilot_ready_module_count"]==0,"base_stable":s["risk_count"]==84 and s["mapped_risk_assignment_count"]==343,"safety_zero":set(p["safety"].values())=={0}};failed=sorted(k for k,v in checks.items() if not v);out={"artifact":"varanegar_distribution_treasury_semantic_alias_candidate_checkpoint_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","previous_checkpoint":{"path":S["previous"],"sha256":sha(paths["previous"])},"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"safety":{"database_connections":0,"golden_or_uat_execution":0,"data_mutations":0}};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
