"""Build ten evidence-first expert diagnostic playbooks without operational execution."""
from __future__ import annotations
import argparse, hashlib, json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
S={"commands":"artifacts/varanegar_analysis/varanegar_command_readiness_ledger_20260829.json","reports":"artifacts/varanegar_analysis/varanegar_report_surface_closure_ledger_20260829.json","golden":"artifacts/varanegar_analysis/varanegar_golden_uat_evidence_ledger_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json","previous":"artifacts/varanegar_analysis/varanegar_golden_uat_evidence_checkpoint_20260829.json"}
BASE=["ثبت شناسه رخداد، زمان کسب‌وکاری، سال مالی، DC و نقش بدون PII","تثبیت hash و نسخه شواهد؛ توقف در صورت drift","بازسازی timeline فقط از read model/history/audit","مقایسه precondition، scope، state و side-effect مورد انتظار","طبقه‌بندی نتیجه: رفتار طبیعی، بدهی داده، bug، یا اثبات‌نشده","توقف پیش از هر repair و طراحی UAT ایزوله در صورت نیاز"]
CASES=[
 ("PB-01","ORDER_CONVERSION_INCOMPLETE","سفارش تبدیل‌نشده یا ناقص","sales",["R-005","R-007","R-023"],["order/sale state","conversion attempt/history","stock/payment prerequisites"]),
 ("PB-02","CANCELLED_SALE_INCONSISTENT","فروش لغوشده با موجودی/پرداخت/حواله ناسازگار","sales",["R-007","R-026","R-034"],["sale cancel state","voucher/exit links","payment and stock projections"]),
 ("PB-03","INVOICE_VOUCHER_ACCOUNTING_MISMATCH","اختلاف فاکتور، Voucher و سند حسابداری","accounting",["R-007","R-021","R-084"],["invoice snapshot","voucher lineage","balanced accounting source"]),
 ("PB-04","STOCK_CARDEX_MISMATCH","اختلاف StockGoods و Cardex","inventory",["R-007","R-031","R-033"],["stock obligations","voucher item/detail","cardex projection and batch"]),
 ("PB-05","CHEQUE_RECEIPT_HISTORY_GAP","تاریخچه ناقص چک یا Receipt","treasury",["R-007","R-023","R-036"],["current cheque/receipt state","undo/delete history","settlement/payment links"]),
 ("PB-06","REPLICATION_DUPLICATE_OR_MISSING","Replication تکراری، ناقص یا بدون Target","integration",["R-004","R-005","R-034"],["source event identity","outbox/inbox attempt","target/compensation/tombstone"]),
 ("PB-07","REPORT_OPERATIONAL_DIFFERENCE","اختلاف گزارش و جدول عملیاتی","reporting",["R-002","R-017","R-059"],["report owner/query/template","filter and scope envelope","snapshot/projection/current-state semantics"]),
 ("PB-08","DISCOUNT_REWARD_NOT_CALCULATED","تخفیف یا جایزه محاسبه‌نشده","pricing",["R-002","R-023","R-057"],["rule snapshot and family","input dataset/query template","priority/exclusion/effect trace"]),
 ("PB-09","AUTH_SCOPE_DATE_REJECTED","خطای Permission، Scope یا OperationDate","authorization",["R-003","R-023","R-026"],["effective deny-first rights","resource scope","operation/final date and feature policy"]),
 ("PB-10","COMMITTED_WITH_ERROR_OR_PARTIAL","Commit موفق همراه پیام خطا یا Partial Success","transaction",["R-005","R-007","R-034"],["transaction owner","commit/rollback evidence","durable effect, response and retry identity"]),
]
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 p=argparse.ArgumentParser();p.add_argument("--output",required=True,type=Path);a=p.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};known={x["id"] for x in d["risk"]["risks"]}
 rows=[{"playbook_id":i,"incident_class":c,"title_fa":t,"domain":m,"risk_links":rs,"evidence_to_collect":ev,"diagnostic_steps":BASE,"decision_rule":{"NATURAL_BEHAVIOR":"state/filter/snapshot semantics fully explain observation","DATA_DEBT":"broken or missing lineage/history without contradicted code contract","BUG":"observed deterministic behavior contradicts pinned contract","UNPROVEN":"runtime/result evidence is insufficient"},"stop_conditions":["source drift","write access or operational execution required","PII/raw business value would need persistence","repair requested without separate authorization"],"erp_target_effect":["immutable correlation and audit identity","explicit state/precondition/outcome contract","reconciliation case and quarantine path"]} for i,c,t,m,rs,ev in CASES]
 checks={"inputs_pass":all(d[k]["validation"]=="PASS" for k in ("commands","reports","golden","risk","trace","previous")),"ten_required_scenarios":len(rows)==10,"unique_ids":len({x["playbook_id"] for x in rows})==10,"risk_links_exist":all(set(x["risk_links"])<=known for x in rows),"classification_complete":all(len(x["decision_rule"])==4 for x in rows),"safe_stop_present":all(len(x["stop_conditions"])==4 for x in rows),"risk_stable":d["risk"]["summary"]["risk_count"]==84,"trace_stable":d["trace"]["summary"]["mapped_risk_assignment_count"]==343}
 failed=sorted(k for k,v in checks.items() if not v);out={"artifact":"varanegar_expert_incident_playbook_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","safety":{"mode":"OFFLINE_EVIDENCE_SYNTHESIS","database_connections":0,"commands_forms_reports_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"sensitive_values_persisted":0},"summary":{"playbook_count":len(rows),"covered_required_scenario_count":10,"classification_count":4,"risk_count":84,"new_risk_count":0,"runtime_repairs_performed":0},"playbooks":rows,"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())],"confidence":{"structure_and_traceability":"HIGH","incident_specific_runtime_diagnosis":"REQUIRES_CASE_EVIDENCE"},"limits":["Playbooks guide evidence collection; they do not diagnose an unnamed production incident.","No repair, UAT, operational query, form or command was executed.","Customer-specific settings and external targets remain runtime-dependent."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
