"""Execute deterministic synthetic privacy/rights vectors."""
from __future__ import annotations
import argparse,copy,hashlib,importlib.util,json
from datetime import datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];REFERENCE=ROOT/"scripts/windows/varanegar_privacy_rights_reference.py"
S={"privacy_contract":"artifacts/varanegar_analysis/varanegar_target_erp_privacy_consent_legal_basis_data_subject_rights_contract_20260829.json","privacy_checkpoint":"artifacts/varanegar_analysis/varanegar_target_erp_privacy_consent_legal_basis_data_subject_rights_checkpoint_20260829.json","authorization":"artifacts/varanegar_analysis/varanegar_target_erp_command_authorization_scope_decision_trace_contract_20260829.json","master_data":"artifacts/varanegar_analysis/varanegar_target_erp_master_data_identity_dedup_merge_supersession_contract_20260829.json","evidence":"artifacts/varanegar_analysis/varanegar_target_erp_evidence_logging_redaction_retention_contract_20260829.json","tests":"artifacts/varanegar_analysis/varanegar_25h_final_test_result_20260829.json","risk":"artifacts/varanegar_analysis/ui/negin_erp_risk_register_20260829.json","trace":"artifacts/varanegar_analysis/ui/negin_erp_requirements_traceability_20260829.json"}
def load(p):return json.loads(p.read_text(encoding="utf-8-sig"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def module():s=importlib.util.spec_from_file_location("prv_ref",REFERENCE);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return m
def main():
 p=argparse.ArgumentParser();p.add_argument("--output",required=True,type=Path);a=p.parse_args();paths={k:ROOT/v for k,v in S.items()};d={k:load(v) for k,v in paths.items()};m=module();base=m.baseline()
 def changed(**kw):e=copy.deepcopy(base);e.update(kw);return e
 positive=[("POS-PROCESS",base,"PROCESSING_ACCEPTED_PURPOSE_BASIS_SCOPE_AND_NECESSITY"),("POS-CONSENT",changed(consent_required=True),"PROCESSING_ACCEPTED_PURPOSE_BASIS_SCOPE_AND_NECESSITY"),("POS-ACCESS",changed(requested_action="ACCESS"),"RIGHTS_RESPONSE_ACCEPTED_VERIFIED_COMPLETE_AND_SAFE"),("POS-ERASE",changed(requested_action="ERASE"),"ERASURE_ACCEPTED_VERIFIED_AND_PROPAGATABLE"),("POS-HOLD",changed(requested_action="ERASE",legal_hold=True),"ERASURE_REJECTED_LEGAL_HOLD_OR_CONFLICTING_OBLIGATION"),("POS-SHARE",changed(requested_action="SHARE"),"SHARING_ACCEPTED_RECIPIENT_PROCESSOR_AND_TRANSFER_SCOPED"),("POS-AUTOMATED",changed(requested_action="AUTOMATED_DECISION"),"AUTOMATED_DECISION_ACCEPTED_EXPLAINED_AND_REVIEWABLE"),("POS-BREACH",changed(requested_action="BREACH_RESPONSE"),"BREACH_RESPONSE_ACCEPTED_SCOPED_AND_EVIDENCED"),("POS-DISPOSE",changed(requested_action="DISPOSE"),"DISPOSITION_ACCEPTED_VERIFIED_AND_PROPAGATED")]
 negative=[("NEG-EXTRA",dict(base,extra=True),"SCHEMA_INVALID"),("NEG-INVENTORY",changed(inventory_current=False),"PRIVACY_ACTION_REJECTED_INVENTORY_OR_SUBJECT_LINKAGE"),("NEG-SUBJECT",changed(subject_linkage_current=False),"PRIVACY_ACTION_REJECTED_INVENTORY_OR_SUBJECT_LINKAGE"),("NEG-PURPOSE",changed(purpose_current=False),"PROCESSING_REJECTED_PURPOSE_BASIS_SCOPE_OR_JURISDICTION"),("NEG-BASIS",changed(legal_basis_current=False),"PROCESSING_REJECTED_PURPOSE_BASIS_SCOPE_OR_JURISDICTION"),("NEG-JURISDICTION",changed(jurisdiction_policy_current=False),"PROCESSING_REJECTED_PURPOSE_BASIS_SCOPE_OR_JURISDICTION"),("NEG-NOTICE",changed(notice_current=False),"PROCESSING_REJECTED_NOTICE"),("NEG-CONSENT",changed(consent_required=True,consent_current=False),"CONSENT_REJECTED_OR_WITHDRAWAL_PROPAGATION_REQUIRED"),("NEG-WITHDRAWN",changed(consent_required=True,consent_withdrawn=True),"CONSENT_REJECTED_OR_WITHDRAWAL_PROPAGATION_REQUIRED"),("NEG-MINIMIZE",changed(minimization_current=False),"PROCESSING_REJECTED_MINIMIZATION_OR_SENSITIVE_GUARD"),("NEG-SENSITIVE",changed(sensitive_guard_current=False),"PROCESSING_REJECTED_MINIMIZATION_OR_SENSITIVE_GUARD"),("NEG-IDENTITY",changed(requested_action="ACCESS",identity_verified=False),"RIGHTS_REQUEST_REJECTED_IDENTITY_SCOPE_OR_REPRESENTATIVE"),("NEG-REPRESENTATIVE",changed(requested_action="ACCESS",representative_current=False),"RIGHTS_REQUEST_REJECTED_IDENTITY_SCOPE_OR_REPRESENTATIVE"),("NEG-DISCOVERY",changed(requested_action="ERASE",record_discovery_complete=False),"RIGHTS_REQUEST_REJECTED_INCOMPLETE_RECORD_DISCOVERY"),("NEG-THIRD-PARTY",changed(requested_action="ACCESS",third_party_redaction_current=False),"RIGHTS_RESPONSE_REJECTED_THIRD_PARTY_OR_PRIVILEGE_REVIEW"),("NEG-CONFLICT",changed(requested_action="ERASE",conflicting_obligation=True),"ERASURE_REJECTED_LEGAL_HOLD_OR_CONFLICTING_OBLIGATION"),("NEG-SHARE",changed(requested_action="SHARE",recipient_processor_scope_current=False),"SHARING_REJECTED_RECIPIENT_PROCESSOR_OR_TRANSFER_SCOPE"),("NEG-AUTOMATED",changed(requested_action="AUTOMATED_DECISION",human_review_current=False),"AUTOMATED_DECISION_HUMAN_REVIEW_REQUIRED"),("NEG-BREACH",changed(requested_action="BREACH_RESPONSE",breach_evidence_current=False),"BREACH_RESPONSE_REQUIRED_SCOPED_AND_EVIDENCED"),("NEG-DISPOSE",changed(requested_action="DISPOSE",retention_disposition_current=False),"DISPOSITION_REJECTED_RETENTION_HOLD_OR_VERIFICATION"),("NEG-UNKNOWN",changed(blocking_unknown=True),"MANUAL_REVIEW_REQUIRED_BLOCKING_UNKNOWN")]
 def run(vs):
  r=[]
  for i,e,x in vs:
   y=m.evaluate(e);r.append({"vector_id":i,"expected":x,"actual":y,"status":"PASS" if y==x else "FAIL"})
  return r
 pr=run(positive);nr=run(negative);allr=pr+nr;official=d["tests"];cs=d["privacy_contract"]["summary"]
 s={"reference_evaluator_implementation_count":1,"positive_vector_count":len(pr),"positive_pass_count":sum(x["status"]=="PASS" for x in pr),"negative_vector_count":len(nr),"negative_pass_count":sum(x["status"]=="PASS" for x in nr),"total_vector_count":len(allr),"total_pass_count":sum(x["status"]=="PASS" for x in allr),"distinct_typed_outcome_count":len({x["actual"] for x in allr}),"privacy_gate_count":cs["gate_count"],"privacy_module_gate_assignment_count":cs["module_gate_assignment_count"],"operational_privacy_consent_rights_or_disposition_implementation_count":0,"operational_person_subject_identifier_or_sensitive_data_read_count":0,"consent_rights_disposition_sharing_or_breach_run_count":0,"accepted_operational_receipt_count":0,"command_ready_module_count":0,"pilot_ready_module_count":0,"design_lower_bound_before_reference_evaluator":1404,"design_lower_bound_after_reference_evaluator":1404,"official_test_file_count":official["runner"]["test_file_count"],"official_passed_test_count":official["runner"]["passed_test_count"],"risk_count":d["risk"]["summary"]["risk_count"],"mapped_risk_assignment_count":d["trace"]["summary"]["mapped_risk_assignment_count"],"new_risk_count":0}
 checks={"sources_pass":all(d[k].get("validation")=="PASS" for k in ("privacy_contract","privacy_checkpoint","authorization","master_data","evidence","tests")),"positive_9_of_9":s["positive_vector_count"]==s["positive_pass_count"]==9,"negative_21_of_21":s["negative_vector_count"]==s["negative_pass_count"]==21,"total_30_of_30":s["total_vector_count"]==s["total_pass_count"]==30,"distinct_outcomes_at_least_18":s["distinct_typed_outcome_count"]>=18,"coverage_24_336":(s["privacy_gate_count"],s["privacy_module_gate_assignment_count"])==(24,336),"operational_and_readiness_zero":all(s[k]==0 for k in ("operational_privacy_consent_rights_or_disposition_implementation_count","operational_person_subject_identifier_or_sensitive_data_read_count","consent_rights_disposition_sharing_or_breach_run_count","accepted_operational_receipt_count","command_ready_module_count","pilot_ready_module_count")),"non_additive_1404":s["design_lower_bound_before_reference_evaluator"]==s["design_lower_bound_after_reference_evaluator"]==1404,"official_tests_pass":official["validation"]=="PASS" and official["runner"]["bootstrap_excluded_test_file_count"]==0,"base_stable":s["risk_count"]==84 and s["mapped_risk_assignment_count"]==343};failed=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_target_erp_privacy_rights_synthetic_reference_evaluator_contract_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not failed else "FAIL","scope":{"mode":"pure_synthetic_jurisdiction_neutral_privacy_rights_reference_evaluator","continuation_complete":False,"legal_advice_or_jurisdiction_determination":False,"operational_person_subject_identifier_or_sensitive_data_read":False},"safety":{"database_connections":0,"network_reads_or_writes":0,"operational_person_subject_identifier_contact_employee_financial_or_sensitive_data_reads":0,"consent_capture_withdrawal_rights_disposition_sharing_or_breach_actions_executed":0,"operational_forms_reports_queries_or_procedures_executed":0,"assemblies_loaded_or_executed":0,"data_mutations":0,"credentials_endpoints_pii_or_raw_business_values_read_or_persisted":0},"summary":s,"positive_results":pr,"negative_results":nr,"outcome_precedence":["SCHEMA","INVENTORY_SUBJECT_LINKAGE","PURPOSE_BASIS_JURISDICTION","NOTICE","CONSENT_WITHDRAWAL","MINIMIZATION_SENSITIVE_GUARD","RIGHTS_IDENTITY_REPRESENTATIVE","RECORD_DISCOVERY","THIRD_PARTY_REDACTION","LEGAL_HOLD_CONFLICT","SHARING_SCOPE","AUTOMATED_DECISION","BREACH","RETENTION_DISPOSITION","BLOCKING_UNKNOWN","ACCEPTED"],"checks":checks,"failed_checks":failed,"source_manifest":[{"name":k,"path":S[k],"size_bytes":v.stat().st_size,"sha256":sha(v)} for k,v in sorted(paths.items())]+[{"name":"reference_evaluator","path":REFERENCE.relative_to(ROOT).as_posix(),"size_bytes":REFERENCE.stat().st_size,"sha256":sha(REFERENCE)},{"name":"builder","path":"scripts/windows/build_varanegar_target_erp_privacy_rights_synthetic_reference_evaluator_contract_20260829.py","size_bytes":Path(__file__).stat().st_size,"sha256":sha(Path(__file__))}],"limits":["This is jurisdiction-neutral synthetic engineering evidence and not legal advice.","Only fixed booleans and action labels were evaluated; no personal sensitive employee financial or business data was read.","Operational privacy processing rights disposition sharing breach response and readiness remain blocked pending applicable legal review and approved receipts."]}
 a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(s,ensure_ascii=False));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
