"""Resolve Manual Voucher generic save dispatch using static PE/CLR metadata and IL only."""
from __future__ import annotations
import argparse,hashlib,json,sys
from datetime import datetime
from pathlib import Path
import dnfile
from dncil.cil.body.reader import read_method_body_from_bytes
from dncil.clr.token import Token
sys.path.insert(0,str(Path(__file__).resolve().parent))
from extract_varanegar_targeted_il_contracts import _full_type_name,_owner_maps,_resolve_token,_text  # noqa:E402
EXPECTED={"VN.SDS.Treasury.UI.dll":"c9a4b7433fdf9d5a955f4248de8f7bff08965df616f111e4ed3085a8d834f2db","VN.SDS.Treasury.Business.dll":"20a2739beaa0543060323de2dac69abee119c527d8fa29a252a59778e5006408","VN.SDS.Treasury.DataAccess.dll":"c5717cfcca6772fbdc3cafaf1d90b0709be1448e193e2cb11f64b8d0004e8b82","VN.SDS.Treasury.IBusiness.dll":"0fd3844820d1c0937df9fd784e39eaf847593a8a4a9c90c6f4c86e3accb04e66","Application.BusinessLayer.dll":"3322cee4550c172c87142085c4c89bccc4bb2fd3dd583040385920b6a7ff5408"}
UI="VN.SDS.Treasury.UI.ManualVoucher.FormManualVoucherDataEntry2";HANDLER="VN.SDS.Treasury.IBusiness.ManualVoucher.IManualVoucherHandler";ADAPTER="VN.SDS.Treasury.DataAccess.DataAdapter.ManualVoucher.ManualVoucherAdapter";GEN_HANDLER="Application.BusinessLayer.Handler.IBusinessHandler`6";GEN_ADAPTER="Application.BusinessLayer.DataAdapter.BaseDataV2Adapter`4"
def cu(b,i):
 x=b[i]
 if x<128:return x,i+1
 if x<192:return ((x&63)<<8)|b[i+1],i+2
 return ((x&31)<<24)|(b[i+1]<<16)|(b[i+2]<<8)|b[i+3],i+4
def typename(pe,v):
 tag=v&3;rid=v>>2;tab=("TypeDef","TypeRef","TypeSpec")[tag];r=getattr(pe.net.mdtables,tab).rows[rid-1];return f"{_text(getattr(r,'TypeNamespace',''))}.{_text(getattr(r,'TypeName',''))}".strip(".")
def generic(pe,ts):
 b=bytes(ts.Signature.value);i=2;v,i=cu(b,i);root=typename(pe,v);n=b[i];i+=1;args=[]
 for _ in range(n):i+=1;v,i=cu(b,i);args.append(typename(pe,v))
 return {"generic_type":root,"arguments":args}
def method(pe,t,name,ordinal=0):return [i.row for i in t.MethodList or [] if _text(i.row.Name)==name][ordinal]
def body_contract(pe,m):
 owners,fields=_owner_maps(pe);body=read_method_body_from_bytes(pe.get_data(m.Rva,65536));calls=[]
 for ins in body.instructions:
  if ins.mnemonic in {"call","callvirt","newobj"} and isinstance(ins.operand,Token):calls.append({"offset":ins.offset,"member":_resolve_token(pe,ins.operand,owners,fields)})
 return {"method":_text(m.Name),"signature_sha256":hashlib.sha256(bytes(m.Signature.value)).hexdigest(),"instruction_count":len(body.instructions),"branch_count":sum(ins.mnemonic.startswith("br") or ins.mnemonic in {"leave","leave.s","switch"} for ins in body.instructions),"ordered_calls":calls,"commit_offsets":[x["offset"] for x in calls if x["member"].endswith("DataContext.Commit")],"rollback_offsets":[x["offset"] for x in calls if x["member"].endswith(("DataContext.RollBack","DataContext.Rollback"))],"raw_literals_persisted":False}
def main():
 p=argparse.ArgumentParser();p.add_argument("--source-directory",required=True,type=Path);p.add_argument("--output",required=True,type=Path);a=p.parse_args();pes={};sources=[];errors=[]
 for f,h in EXPECTED.items():
  path=a.source_directory/f;raw=path.read_bytes();actual=hashlib.sha256(raw).hexdigest();sources.append({"file":f,"size_bytes":len(raw),"sha256":actual,"expected_sha256":h,"hash_match":actual==h});errors+=[] if actual==h else [f"hash_mismatch:{f}"];pes[f]=dnfile.dnPE(str(path))
 ui=pes["VN.SDS.Treasury.UI.dll"];ut=next(x for x in ui.net.mdtables.TypeDef.rows if _full_type_name(x)==UI);um=method(ui,ut,"SaveCommand");ub=read_method_body_from_bytes(ui.get_data(um.Rva,65536));save_ref=next(ui.net.mdtables.MemberRef.rows[i.operand.rid-1] for i in ub.instructions if i.mnemonic=="callvirt" and isinstance(i.operand,Token) and i.operand.table==10 and _text(ui.net.mdtables.MemberRef.rows[i.operand.rid-1].Name)=="SaveCommand");ui_binding=generic(ui,save_ref.Class.row);ui_contract=body_contract(ui,um);ins=list(ub.instructions);ui_tx_mode=next((ins[n-1].mnemonic for n,x in enumerate(ins) if x.mnemonic=="newobj" and isinstance(x.operand,Token) and _resolve_token(ui,x.operand,*_owner_maps(ui)).endswith("DataContext..ctor")),None)
 ib=pes["VN.SDS.Treasury.IBusiness.dll"];ht=next(x for x in ib.net.mdtables.TypeDef.rows if _full_type_name(x)==HANDLER);handler_binding=generic(ib,ht.Extends.row)
 da=pes["VN.SDS.Treasury.DataAccess.dll"];at=next(x for x in da.net.mdtables.TypeDef.rows if _full_type_name(x)==ADAPTER);adapter_binding=generic(da,at.Extends.row)
 app=pes["Application.BusinessLayer.dll"];ght=next(x for x in app.net.mdtables.TypeDef.rows if _full_type_name(x)==GEN_HANDLER);save_methods=[i.row for i in ght.MethodList if _text(i.row.Name)=="SaveCommand"];generic_save=[body_contract(app,x) for x in save_methods];gat=next(x for x in app.net.mdtables.TypeDef.rows if _full_type_name(x)==GEN_ADAPTER);adapter_ops={n:body_contract(app,method(app,gat,n,0)) for n in ("Insert","Update","Delete")}
 expected_args=[ADAPTER,"VN.SDS.Common.Treasury.Entity.ManualVoucher.ManualVoucherEntity","VN.SDS.Common.Treasury.EntityHelper.ManualVoucher.ManualVoucherEntityHelper","VN.SDS.Common.Treasury.Entity.ManualVoucher.ManualVoucherViewEntity","VN.SDS.Common.Treasury.EntityHelper.ManualVoucher.ManualVoucherViewEntityHelper","VN.SDS.Treasury.IBusiness.ManualVoucher.IManualVoucherValidator"]
 checks={"all_hashes_match":all(x["hash_match"] for x in sources),"ui_binds_exact_generic_handler":ui_binding=={"generic_type":GEN_HANDLER,"arguments":expected_args},"handler_inherits_same_generic":handler_binding=={"generic_type":GEN_HANDLER,"arguments":expected_args},"adapter_inherits_expected_generic":adapter_binding["generic_type"]==GEN_ADAPTER and adapter_binding["arguments"]==expected_args[1:5],"ui_starts_begin_mode":ui_tx_mode=="ldc.i4.0","ui_has_no_commit":not ui_contract["commit_offsets"],"two_generic_save_overloads":len(generic_save)==2,"generic_handler_dispatches_crud":all(any(x["member"].endswith(f".{n}") for m in generic_save for x in m["ordered_calls"]) for n in ("Insert","Update","Delete")),"context_overloads_commit":all(len(x["commit_offsets"])==1 for x in adapter_ops.values()),"selected_paths_no_explicit_rollback":not any(x["rollback_offsets"] for x in [ui_contract,*generic_save,*adapter_ops.values()])};errors+=sorted(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_manual_voucher_generic_save_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not errors else "FAIL","source":sources,"safety":{"mode":"STATIC_HASH_PINNED_PE_CLR_METADATA_AND_IL_ONLY","assemblies_loaded_or_executed":0,"commands_forms_or_procedures_executed":0,"database_connections":0,"raw_literals_or_business_values_persisted":0,"data_mutations":0},"summary":{"assembly_count":len(sources),"selected_ui_method_count":1,"generic_save_overload_count":len(generic_save),"context_crud_overload_count":len(adapter_ops),"context_crud_overload_with_commit_count":sum(bool(x["commit_offsets"]) for x in adapter_ops.values()),"selected_method_with_explicit_rollback_count":sum(bool(x["rollback_offsets"]) for x in [ui_contract,*generic_save,*adapter_ops.values()]),"source_hash_mismatch_count":sum(not x["hash_match"] for x in sources),"validation_error_count":len(errors)},"resolved_chain":{"ui_method":UI+".SaveCommand","ui_transaction_mode_operand":ui_tx_mode,"ui_generic_binding":ui_binding,"handler_generic_binding":handler_binding,"adapter_generic_binding":adapter_binding,"generic_save_dispatch":"first overload delegates to policy-aware overload; policy-aware overload selects SaveV2 or Insert/Update/Delete","context_crud_commit_owner":"BaseDataV2Adapter context-taking Insert/Update/Delete overloads each contain one DataContext.Commit","exact_named_procedure":"NONE_GENERIC_ENTITY_METADATA_PERSISTENCE"},"ui_method":ui_contract,"generic_save_methods":generic_save,"context_crud_methods":adapter_ops,"checks":checks,"validation_errors":errors,"confidence":{"generic_type_binding":"CONFIRMED_STATIC_METADATA","call_and_commit_order":"CONFIRMED_STATIC_IL","branch_selected_at_runtime":"UNPROVEN","physical_effect_parity":"UNPROVEN"},"limits":["No assembly was loaded or executed; only PE/CLR metadata and IL bytes were read.","The runtime branch among V2, Fararu, Insert, Update and Delete is configuration/state dependent.","Generic entity persistence exposes no named ManualVoucher stored-procedure literal in the selected path.","Absence of an explicit rollback call does not prove provider disposal or an outer boundary cannot roll back."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(out["summary"]));return 0 if not errors else 1
if __name__=="__main__":raise SystemExit(main())
