"""Extract hash-pinned RPT-01/RPT-02 Crystal viewer ownership and permission boundaries."""
from __future__ import annotations
import argparse,hashlib,json,sys
from datetime import datetime
from pathlib import Path
import dnfile
from dncil.cil.body.reader import read_method_body_from_bytes
from dncil.clr.token import StringToken,Token
sys.path.insert(0,str(Path(__file__).resolve().parent))
from extract_varanegar_targeted_il_contracts import _full_type_name,_owner_maps,_resolve_token,_text  # noqa:E402
FILE="TreasuryOld.Forms.dll";EXPECTED="df03abc8dc0e4b62976b7114676b8b9fa53a78205670a63db1424f04e91ea63b";TARGETS={"TreasuryOld.Forms.frmReportPreview":{"ShowReport","frmReportPreview_SizeChanged"},"TreasuryOld.Forms.frmReportPreviewMultiReport":{"ShowReport","rptPermission","SetDrillDown","frmReportPreviewMultiReport_FormClosing"}}
def sha(b):return hashlib.sha256(b).hexdigest()
def main():
 p=argparse.ArgumentParser();p.add_argument("--source-directory",required=True,type=Path);p.add_argument("--output",required=True,type=Path);a=p.parse_args();path=a.source_directory/FILE;raw=path.read_bytes();pe=dnfile.dnPE(str(path));owners,fields=_owner_maps(pe);types={_full_type_name(x):x for x in pe.net.mdtables.TypeDef.rows};rows=[];errors=[]
 for type_name,names in TARGETS.items():
  t=types.get(type_name)
  if not t:errors.append(f"type_{type_name}");continue
  for idx in t.MethodList or []:
   m=idx.row;name=_text(getattr(m,"Name",""))
   if name not in names or not m.Rva:continue
   body=read_method_body_from_bytes(pe.get_data(m.Rva,65536));calls=[];literal_count=0
   for ins in body.instructions:
    if ins.mnemonic in {"call","callvirt","newobj"} and isinstance(ins.operand,Token):calls.append({"offset":ins.offset,"member":_resolve_token(pe,ins.operand,owners,fields)})
    if isinstance(ins.operand,StringToken):literal_count+=1
   members=[x["member"] for x in calls];rows.append({"type":type_name,"method":name,"instruction_count":len(body.instructions),"parameter_count":len(getattr(m,"ParamList",[]) or []),"ordered_calls":calls,"literal_fingerprint_count":literal_count,"raw_literals_persisted":False,"sets_report_source":any("set_ReportSource" in x for x in members),"loads_report_document":any("ReportDocument.Load" in x for x in members),"rebinds_table_connection":any("Table.ApplyLogOnInfo" in x for x in members) and any("Table.set_Location" in x for x in members),"reads_live_connection":any("Transaction.get_Connection" in x for x in members),"sets_print_export_visibility":any("set_ShowPrintButton" in x or "set_ShowExportButton" in x for x in members),"reads_report_permissions":any("get_Print" in x or "get_Export" in x for x in members),"closes_report_document":any("ReportDocument.Close" in x for x in members),"shows_modal":any("Form.ShowDialog" in x for x in members)})
 if sha(raw)!=EXPECTED:errors.append("hash_mismatch")
 single=next((x for x in rows if x["type"].endswith("frmReportPreview") and x["method"]=="ShowReport"),{});multi=next((x for x in rows if x["type"].endswith("frmReportPreviewMultiReport") and x["method"]=="ShowReport"),{});permission=next((x for x in rows if x["method"]=="rptPermission"),{});closing=next((x for x in rows if x["method"]=="frmReportPreviewMultiReport_FormClosing"),{})
 checks={"six_selected_methods":len(rows)==6,"single_binds_external_document":single.get("sets_report_source") and single.get("rebinds_table_connection") and single.get("reads_live_connection") and not single.get("loads_report_document"),"single_modal_viewer":single.get("shows_modal"),"multi_binds_external_documents":multi.get("sets_report_source") and multi.get("rebinds_table_connection") and multi.get("reads_live_connection") and not multi.get("loads_report_document"),"multi_permission_boundary":permission.get("sets_print_export_visibility") and permission.get("reads_report_permissions"),"multi_closes_documents":closing.get("closes_report_document")};errors.extend(k for k,v in checks.items() if not v)
 out={"artifact":"varanegar_treasury_crystal_viewer_boundary_20260829","schema_version":1,"generated_at":datetime.now().astimezone().isoformat(),"validation":"PASS" if not errors else "FAIL","source":{"file":FILE,"size_bytes":len(raw),"sha256":sha(raw),"expected_sha256":EXPECTED,"hash_matches":sha(raw)==EXPECTED},"safety":{"mode":"STATIC_PE_CLR_METADATA_AND_IL","database_connections":0,"reports_templates_forms_or_queries_executed":0,"assemblies_loaded_or_executed":0,"credentials_connection_strings_business_values_or_identities_persisted":0,"data_mutations":0},"summary":{"viewer_type_count":2,"selected_method_count":len(rows),"external_document_binding_method_count":sum(x["sets_report_source"] and not x["loads_report_document"] for x in rows),"permission_method_count":sum(x["sets_print_export_visibility"] for x in rows),"document_close_method_count":sum(x["closes_report_document"] for x in rows),"validation_error_count":len(errors)},"ownership":{"RPT-01":{"role":"SINGLE_EXTERNAL_CRYSTAL_DOCUMENT_VIEWER","template_query_formula_layout_owner":"CALLER_SUPPLIED_REPORT_DOCUMENT","viewer_owned":["connection rebinding","viewer source","zoom/refresh-button state","modal lifecycle"]},"RPT-02":{"role":"MULTI_EXTERNAL_CRYSTAL_DOCUMENT_VIEWER","template_query_formula_layout_owner":"CALLER_SUPPLIED_REPORT_DOCUMENTS","viewer_owned":["per-tab connection rebinding","viewer sources","drilldown","print/export visibility","document close lifecycle"]}},"methods":sorted(rows,key=lambda x:(x["type"],x["method"])),"checks":checks,"validation_errors":errors,"confidence":{"viewer_connection_permission_and_lifecycle":"CONFIRMED_STATIC_IL","template_identity_query_formula_and_result_parity":"UNPROVEN"},"limits":["No Crystal document, template, form or query was loaded or executed.","Connection APIs are named in IL; no credential or connection-string value is persisted.","Absence of ReportDocument.Load in selected viewer methods means loading/creation is caller-owned, not absent system-wide."]};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(a.output.resolve());print(out["validation"]);print(json.dumps(out["summary"]));return 0 if not errors else 1
if __name__=="__main__":raise SystemExit(main())
