[CmdletBinding()]
param(
  [switch]$IncludeNgtAuthorization
)

$ErrorActionPreference = 'Stop'
$root = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$python = Join-Path $root '.venv\Scripts\python.exe'
$ui = Join-Path $root 'artifacts\varanegar_analysis\ui'
$domain = Join-Path $root 'artifacts\varanegar_analysis\domains'
$riskOutput = if ($IncludeNgtAuthorization) {
  Join-Path $ui 'negin_erp_risk_register_20260829.json'
} else {
  Join-Path $ui 'negin_erp_risk_register_20260827.json'
}
$traceOutput = if ($IncludeNgtAuthorization) {
  Join-Path $ui 'negin_erp_requirements_traceability_20260829.json'
} else {
  Join-Path $ui 'negin_erp_requirements_traceability_20260827.json'
}

$riskArgs = @(
  (Join-Path $PSScriptRoot 'build_negin_erp_risk_register.py'),
  '--matrix', (Join-Path $ui 'negin_erp_module_readiness_matrix_20260827.json'),
  '--migration', (Join-Path $ui 'negin_erp_varanegar_migration_contract_20260827.json'),
  '--roles', (Join-Path $ui 'negin_erp_role_sod_contract_20260827.json'),
  '--side-effects', (Join-Path $ui 'varanegar_command_side_effects_20260827.json'),
  '--gaps', (Join-Path $ui 'varanegar_form_evidence_gaps_20260827.json'),
  '--roots', (Join-Path $ui 'varanegar_root_entrypoints_20260827.json'),
  '--reports', (Join-Path $ui 'varanegar_report_execution_contracts_20260827.json'),
  '--drift', (Join-Path $ui 'varanegar_runtime_drift_baseline_20260827.json'),
  '--backlog', (Join-Path $ui 'negin_erp_p0_backlog_20260827.json'),
  '--extension-semantics', (Join-Path $ui 'varanegar_extension_sql_semantics_20260827.json'),
  '--extension-gap-paths', (Join-Path $ui 'varanegar_extension_gap_paths_20260827.json'),
  '--pos-transitive-graph', (Join-Path $ui 'varanegar_pos_replication_transitive_graph_20260827.json'),
  '--pos-source-model', (Join-Path $ui 'varanegar_pos_source_model_20260827.json'),
  '--report-target-contracts', (Join-Path $ui 'varanegar_report_target_contracts_golden_cases_20260827.json'),
  '--report-evidence-gaps', (Join-Path $ui 'varanegar_report_evidence_gaps_20260827.json'),
  '--report-generic-semantics', (Join-Path $ui 'varanegar_report_generic_sql_semantics_20260827.json'),
  '--treasury-command-paths', (Join-Path $ui 'varanegar_treasury_edit_command_paths_20260827.json'),
  '--treasury-source-model', (Join-Path $ui 'varanegar_treasury_edit_source_model_20260827.json'),
  '--treasury-trigger-semantics', (Join-Path $ui 'varanegar_treasury_trigger_semantics_20260827.json'),
  '--treasury-view-lineage', (Join-Path $ui 'varanegar_treasury_view_column_lineage_20260827.json'),
  '--treasury-target-contracts', (Join-Path $ui 'negin_erp_treasury_edit_target_contracts_20260827.json'),
  '--treasury-validation-contracts', (Join-Path $ui 'varanegar_treasury_edit_validation_contracts_20260827.json'),
  '--treasury-trigger-transitive-graph', (Join-Path $ui 'varanegar_treasury_trigger_transitive_graph_20260827.json'),
  '--treasury-web-field-contracts', (Join-Path $ui 'varanegar_treasury_web_field_contract_candidates_20260827.json'),
  '--order-sale-command-contracts', (Join-Path $ui 'varanegar_order_sale_entry_command_contracts_20260827.json'),
  '--order-sale-dependency-graph', (Join-Path $ui 'varanegar_order_sale_command_dependency_graph_20260827.json'),
  '--order-sale-sql-semantics', (Join-Path $ui 'varanegar_order_sale_sql_semantics_20260827.json'),
  '--order-sale-source-model', (Join-Path $ui 'varanegar_order_sale_mutation_source_model_20260827.json'),
  '--order-sale-trigger-transitive-graph', (Join-Path $ui 'varanegar_order_sale_trigger_transitive_graph_20260827.json'),
  '--order-sale-web-screens', (Join-Path $ui 'negin_erp_order_sale_web_screen_contract_candidates_20260827.json'),
  '--stock-voucher-command-contract', (Join-Path $ui 'varanegar_stock_voucher_command_contract_20260827.json'),
  '--distribution-sql-semantics', (Join-Path $ui 'varanegar_distribution_sql_semantics_20260827.json'),
  '--distribution-source-model', (Join-Path $ui 'varanegar_distribution_mutation_source_model_20260827.json'),
  '--distribution-trigger-transitive-graph', (Join-Path $ui 'varanegar_distribution_trigger_transitive_graph_20260827.json'),
  '--supplier-invoice-command-contract', (Join-Path $ui 'varanegar_supplier_invoice_command_contract_20260827.json'),
  '--supplier-invoice-source-model', (Join-Path $ui 'varanegar_supplier_invoice_relation_source_model_20260827.json'),
  '--supplier-invoice-trigger-transitive-graph', (Join-Path $ui 'varanegar_supplier_invoice_relation_trigger_transitive_graph_20260827.json'),
  '--accounting-voucher-entrypoints', (Join-Path $ui 'varanegar_accounting_voucher_entrypoint_contracts_20260827.json'),
  '--accounting-voucher-sql-candidates', (Join-Path $ui 'varanegar_accounting_voucher_sql_candidates_20260827.json'),
  '--customer-goods-command-contracts', (Join-Path $ui 'varanegar_customer_goods_command_contracts_20260827.json'),
  '--customer-goods-web-screens', (Join-Path $ui 'negin_erp_customer_goods_web_screen_contract_candidates_20260827.json'),
  '--supplier-master-command-contract', (Join-Path $ui 'varanegar_supplier_master_command_contract_20260827.json'),
  '--supplier-master-web-screen', (Join-Path $ui 'negin_erp_supplier_master_web_screen_contract_candidate_20260827.json'),
  '--operational-context-command-contracts', (Join-Path $ui 'varanegar_operational_context_command_contracts_20260827.json'),
  '--operational-context-web-screens', (Join-Path $ui 'negin_erp_operational_context_web_screen_contract_candidates_20260827.json'),
  '--pricing-rule-command-contracts', (Join-Path $ui 'varanegar_pricing_rule_command_contracts_20260827.json'),
  '--pricing-rule-web-screens', (Join-Path $ui 'negin_erp_pricing_rule_web_screen_contract_candidates_20260827.json'),
  '--final-date-boundary', (Join-Path $ui 'varanegar_final_date_management_boundary_20260827.json'),
  '--final-date-diagnostic', (Join-Path $ui 'varanegar_final_date_diagnostic_contract_20260827.json'),
  '--stock-reconciliation-diagnostic', (Join-Path $ui 'varanegar_stock_reconciliation_diagnostic_contract_20260827.json'),
  '--distribution-path-diagnostic', (Join-Path $ui 'varanegar_distribution_path_diagnostic_contract_20260827.json'),
  '--sales-return-amount-diagnostic', (Join-Path $ui 'varanegar_sales_return_amount_diagnostic_contract_20260827.json'),
  '--returned-cheque-cross-customer-diagnostic', (Join-Path $ui 'varanegar_returned_cheque_cross_customer_diagnostic_contract_20260827.json'),
  '--received-cheque-projection-legal-diagnostic', (Join-Path $ui 'varanegar_received_cheque_projection_and_legal_type_diagnostic_contract_20260827.json'),
  '--payable-cheque-leaf-usage-diagnostic', (Join-Path $ui 'varanegar_payable_cheque_leaf_usage_diagnostic_contract_20260827.json'),
  '--voucher-status-pointer-diagnostic', (Join-Path $ui 'varanegar_voucher_status_pointer_diagnostic_contract_20260827.json'),
  '--empty-voucher-shell-diagnostic', (Join-Path $ui 'varanegar_empty_voucher_shell_diagnostic_contract_20260827.json'),
  '--ngt-return-crosswalk-diagnostic', (Join-Path $ui 'varanegar_ngt_return_crosswalk_diagnostic_contract_20260827.json'),
  '--supplier-receipt-component-diagnostic', (Join-Path $ui 'varanegar_supplier_receipt_component_diagnostic_contract_20260827.json'),
  '--voucher-creation-policy', (Join-Path $domain 'voucher_creation_atomicity_and_policy_20260828.json'),
  '--rule-replication-transport', (Join-Path $domain 'rule_replication_transport_boundary_20260828.json'),
  '--output', $riskOutput
)
if ($IncludeNgtAuthorization) {
  $riskArgs += @(
    '--ngt-authorization-effective',
    (Join-Path $domain 'ngt_authorization_effective_boundary_20260828.json'),
    '--ngt-owner-scope-effective',
    (Join-Path $domain 'ngt_owner_scope_effective_boundary_20260829.json'),
    '--ngt-operation-date-boundary',
    (Join-Path $domain 'ngt_operation_date_boundary_20260829.json'),
    '--configuration-precedence-boundary',
    (Join-Path $domain 'configuration_precedence_boundary_20260829.json'),
    '--ngt-configuration-runtime-boundary',
    (Join-Path $domain 'ngt_configuration_runtime_boundary_20260829.json'),
    '--ngt-order-persistence-boundary',
    (Join-Path $domain 'ngt_order_persistence_boundary_20260829.json'),
    '--ngt-order-runtime-boundary',
    (Join-Path $domain 'ngt_order_runtime_boundary_20260829.json'),
    '--ngt-tour-call-state-boundary',
    (Join-Path $domain 'ngt_tour_call_state_boundary_20260829.json'),
    '--ngt-tour-call-runtime-boundary',
    (Join-Path $domain 'ngt_tour_call_runtime_boundary_20260829.json'),
    '--ngt-tour-call-authorization-endpoints',
    (Join-Path $domain 'ngt_authorization_endpoint_coverage_20260828.json'),
    '--ngt-payment-settlement-boundary',
    (Join-Path $domain 'ngt_payment_settlement_boundary_20260829.json'),
    '--ngt-payment-runtime-boundary',
    (Join-Path $domain 'ngt_payment_runtime_boundary_20260829.json'),
    '--ngt-payment-replication-boundary',
    (Join-Path $domain 'ngt_payment_replication_boundary_20260829.json'),
    '--ngt-payment-replication-runtime-boundary',
    (Join-Path $domain 'ngt_payment_replication_runtime_boundary_20260829.json'),
    '--ngt-replication-compensation-boundary',
    (Join-Path $domain 'ngt_replication_compensation_boundary_20260829.json'),
    '--ngt-replication-compensation-runtime-boundary',
    (Join-Path $domain 'ngt_replication_compensation_runtime_boundary_20260829.json'),
    '--ngt-return-replication-boundary',
    (Join-Path $domain 'ngt_return_replication_boundary_20260829.json'),
    '--ngt-return-runtime-boundary',
    (Join-Path $domain 'ngt_return_runtime_boundary_20260829.json'),
    '--ngt-sale-replication-boundary',
    (Join-Path $domain 'ngt_sale_replication_boundary_20260829.json'),
    '--ngt-sale-replication-runtime-boundary',
    (Join-Path $domain 'ngt_sale_replication_runtime_boundary_20260829.json'),
    '--ngt-order-history-boundary',
    (Join-Path $domain 'ngt_order_history_target_boundary_20260829.json'),
    '--ngt-order-history-runtime-boundary',
    (Join-Path $domain 'ngt_order_history_runtime_boundary_20260829.json'),
    '--ngt-order-deletion-boundary',
    (Join-Path $domain 'ngt_order_target_deletion_boundary_20260829.json'),
    '--ngt-order-delete-log-boundary',
    (Join-Path $domain 'ngt_order_delete_log_boundary_20260829.json'),
    '--supplier-cost-apply-boundary',
    (Join-Path $domain 'supplier_cost_apply_boundary_20260829.json'),
    '--supplier-cost-apply-runtime-boundary',
    (Join-Path $domain 'supplier_cost_apply_runtime_boundary_20260829.json'),
    '--supplier-unapply-delete-boundary',
    (Join-Path $domain 'supplier_unapply_delete_boundary_20260829.json'),
    '--supplier-unapply-delete-runtime-boundary',
    (Join-Path $domain 'supplier_unapply_delete_runtime_boundary_20260829.json'),
    '--payable-cheque-undo-boundary',
    (Join-Path $domain 'payable_cheque_undo_boundary_20260829.json'),
    '--payable-cheque-undo-runtime-boundary',
    (Join-Path $domain 'payable_cheque_undo_runtime_boundary_20260829.json'),
    '--received-cheque-undo-boundary',
    (Join-Path $domain 'received_cheque_undo_boundary_20260829.json'),
    '--received-cheque-undo-runtime-boundary',
    (Join-Path $domain 'received_cheque_undo_runtime_boundary_20260829.json'),
    '--received-cheque-delete-boundary',
    (Join-Path $domain 'received_cheque_delete_boundary_20260829.json'),
    '--received-cheque-delete-runtime-boundary',
    (Join-Path $domain 'received_cheque_delete_runtime_boundary_20260829.json'),
    '--stock-voucher-state-boundary',
    (Join-Path $domain 'stock_voucher_state_boundary_20260829.json'),
    '--stock-voucher-state-runtime-boundary',
    (Join-Path $domain 'stock_voucher_state_runtime_boundary_20260829.json'),
    '--stock-projection-validation-boundary',
    (Join-Path $domain 'stock_projection_validation_boundary_20260829.json'),
    '--distribution-exit-lifecycle-boundary',
    (Join-Path $domain 'distribution_exit_lifecycle_boundary_20260829.json'),
    '--distribution-exit-runtime-boundary',
    (Join-Path $domain 'distribution_exit_runtime_boundary_20260829.json'),
    '--sale-conversion-state-boundary',
    (Join-Path $domain 'sale_conversion_state_boundary_20260829.json'),
    '--sale-conversion-runtime-boundary',
    (Join-Path $domain 'sale_conversion_runtime_boundary_20260829.json'),
    '--order-sale-policy-flag-sql',
    (Join-Path $domain 'order_sale_policy_flag_sql_20260829.json'),
    '--order-sale-policy-flag-runtime',
    (Join-Path $domain 'order_sale_policy_flag_runtime_20260829.json'),
    '--order-sale-policy-gate-runtime',
    (Join-Path $domain 'order_sale_policy_gate_runtime_20260829.json'),
    '--order-sale-policy-config-snapshot',
    (Join-Path $domain 'order_sale_policy_config_snapshot_20260829.json'),
    '--order-sale-operation-date-sql',
    (Join-Path $domain 'order_sale_operation_date_sql_20260829.json'),
    '--order-sale-operation-date-runtime',
    (Join-Path $domain 'order_sale_operation_date_runtime_20260829.json'),
    '--order-sale-authorization-sql',
    (Join-Path $domain 'order_sale_authorization_sql_20260829.json'),
    '--order-sale-authorization-runtime',
    (Join-Path $domain 'order_sale_authorization_runtime_20260829.json'),
    '--datacontext-transaction-runtime',
    (Join-Path $domain 'datacontext_transaction_runtime_20260829.json'),
    '--order-sale-evc-sql-boundary',
    (Join-Path $domain 'order_sale_evc_sql_boundary_20260829.json'),
    '--order-sale-evc-runtime-boundary',
    (Join-Path $domain 'order_sale_evc_runtime_boundary_20260829.json'),
    '--discount-v2-query-contracts',
    (Join-Path $domain 'discount_v2_query_contracts_20260829.json'),
    '--discount-v2-dataset-sql',
    (Join-Path $domain 'discount_v2_dataset_sql_20260829.json'),
    '--discount-v2-engine-runtime',
    (Join-Path $domain 'discount_v2_engine_runtime_20260829.json'),
    '--discount-v2-dynamic-rule-sql',
    (Join-Path $domain 'discount_v2_dynamic_rule_sql_20260829.json'),
    '--discount-v2-condition-families',
    (Join-Path $domain 'discount_v2_condition_families_20260829.json'),
    '--discount-rule-authoring-boundary',
    (Join-Path $domain 'discount_rule_authoring_boundary_20260829.json'),
    '--discount-rule-authorization-boundary',
    (Join-Path $domain 'discount_rule_authorization_boundary_20260829.json'),
    '--sale-cancellation-boundary',
    (Join-Path $domain 'sale_cancellation_boundary_20260829.json'),
    '--sale-cancellation-runtime-boundary',
    (Join-Path $domain 'sale_cancellation_runtime_boundary_20260829.json'),
    '--return-issue-cancel-boundary',
    (Join-Path $domain 'return_issue_cancel_boundary_20260829.json'),
    '--return-issue-cancel-runtime-boundary',
    (Join-Path $domain 'return_issue_cancel_runtime_boundary_20260829.json'),
    '--sale-voucher-snapshot-boundary',
    (Join-Path $domain 'sale_voucher_snapshot_boundary_20260829.json'),
    '--sale-voucher-snapshot-runtime-boundary',
    (Join-Path $domain 'sale_voucher_snapshot_runtime_boundary_20260829.json'),
    '--sale-accounting-crosswalk-boundary',
    (Join-Path $domain 'sale_accounting_crosswalk_boundary_20260829.json'),
    '--sale-invoice-print-boundary',
    (Join-Path $domain 'sale_invoice_print_audit_boundary_20260829.json'),
    '--sale-invoice-print-runtime-boundary',
    (Join-Path $domain 'sale_invoice_print_runtime_boundary_20260829.json'),
    '--idempotency-guard-boundary',
    (Join-Path $domain 'idempotency_guard_boundary_20260829.json')
  )
}
& $python @riskArgs
if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

$traceArgs = @(
  (Join-Path $PSScriptRoot 'build_negin_erp_requirements_traceability.py'),
  '--readiness', (Join-Path $ui 'negin_erp_module_readiness_matrix_20260827.json'),
  '--risks', $riskOutput,
  '--backlog', (Join-Path $ui 'negin_erp_p0_backlog_20260827.json'),
  '--core-golden', (Join-Path $ui 'varanegar_golden_command_cases_20260827.json'),
  '--orchestrator-golden', (Join-Path $ui 'varanegar_orchestrator_golden_cases_20260827.json'),
  '--extension-golden', (Join-Path $ui 'varanegar_extension_golden_cases_20260827.json'),
  '--report-golden', (Join-Path $ui 'varanegar_report_target_contracts_golden_cases_20260827.json'),
  '--master-golden', (Join-Path $ui 'negin_erp_customer_goods_master_golden_cases_20260827.json'),
  '--foundation-golden', (Join-Path $ui 'negin_erp_foundation_context_pricing_golden_cases_20260827.json'),
  '--activity', (Join-Path $root 'artifacts\varanegar_analysis\three_month_operational_activity_20260826.json'),
  '--output', $traceOutput
)
& $python @traceArgs
exit $LASTEXITCODE
