"""Validate and fingerprint the durable Varanegar night-analysis bundle.

This validator is offline. It reads project artifacts, documents, and builders;
it never connects to Varanegar, SQL Server, a network share, or the live UI.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from datetime import datetime
from pathlib import Path
from typing import Any


UI_ARTIFACTS: dict[str, str] = {
    "ui/varanegar_ui_inventory_20260827.json": "varanegar_windows_ui_inventory",
    "ui/varanegar_binary_inventory_20260827.json": "varanegar_binary_module_inventory",
    "ui/varanegar_assembly_contracts_20260827.json": "varanegar_dotnet_metadata_contracts",
    "ui/varanegar_targeted_il_contracts_20260827.json": "varanegar_targeted_ui_il_contracts",
    "ui/varanegar_ui_sql_contracts_20260827.json": "varanegar_ui_to_sql_contracts",
    "ui/varanegar_ui_capability_matrix_20260827.json": "varanegar_ui_capability_matrix",
    "ui/varanegar_form_catalog_20260827.json": "varanegar_dotnet_form_catalog",
    "ui/varanegar_workflow_catalog_20260827.json": "varanegar_workflow_form_contract_catalog",
    "ui/varanegar_report_catalog_20260827.json": "varanegar_report_form_contract_catalog",
    "ui/varanegar_menu_route_catalog_20260827.json": "varanegar_static_menu_form_access_route_catalog",
    "ui/varanegar_menu_form_crosswalk_20260827.json": "varanegar_menu_form_runtime_crosswalk",
    "ui/varanegar_route_authorization_matrix_20260827.json": "varanegar_open_route_anonymous_authorization_matrix",
    "ui/varanegar_identity_access_navigation_gap_contract_20260827.json": "varanegar_identity_access_administration_navigation_gap_contract",
    "ui/varanegar_system_configuration_navigation_contract_20260827.json": "varanegar_system_configuration_navigation_and_effective_setting_contract",
    "ui/varanegar_final_date_management_boundary_20260827.json": "varanegar_cross_domain_final_date_management_command_boundary",
    "ui/varanegar_final_date_diagnostic_contract_20260827.json": "varanegar_final_and_operation_date_incident_diagnostic_contract",
    "ui/varanegar_stock_reconciliation_diagnostic_contract_20260827.json": "varanegar_stock_reconciliation_incident_diagnostic_contract",
    "ui/varanegar_distribution_path_diagnostic_contract_20260827.json": "varanegar_distribution_path_runtime_and_migration_diagnostic_contract",
    "ui/varanegar_sales_return_amount_diagnostic_contract_20260827.json": "varanegar_sales_return_amount_runtime_and_migration_diagnostic_contract",
    "ui/varanegar_returned_cheque_cross_customer_diagnostic_contract_20260827.json": "varanegar_returned_cheque_cross_customer_diagnostic_contract",
    "ui/varanegar_received_cheque_projection_and_legal_type_diagnostic_contract_20260827.json": "varanegar_received_cheque_projection_and_legal_type_diagnostic_contract",
    "ui/varanegar_payable_cheque_leaf_usage_diagnostic_contract_20260827.json": "varanegar_payable_cheque_leaf_usage_diagnostic_contract",
    "ui/varanegar_voucher_status_pointer_diagnostic_contract_20260827.json": "varanegar_voucher_status_pointer_diagnostic_contract",
    "ui/varanegar_empty_voucher_shell_diagnostic_contract_20260827.json": "varanegar_empty_voucher_shell_diagnostic_contract",
    "ui/varanegar_ngt_return_crosswalk_diagnostic_contract_20260827.json": "varanegar_ngt_mobile_return_crosswalk_diagnostic_contract",
    "ui/varanegar_supplier_receipt_component_diagnostic_contract_20260827.json": "varanegar_supplier_invoice_receipt_relation_component_diagnostic_contract",
    "ui/varanegar_runtime_drift_baseline_20260827.json": "varanegar_runtime_drift_baseline",
    "ui/varanegar_active_page_contracts_20260827.json": "varanegar_active_page_field_filter_validation_contracts",
    "ui/varanegar_state_machine_catalog_20260827.json": "varanegar_state_machine_catalog",
    "ui/varanegar_command_side_effects_20260827.json": "varanegar_active_command_side_effect_contracts",
    "ui/varanegar_golden_command_cases_20260827.json": "varanegar_target_erp_golden_command_cases",
    "ui/varanegar_report_execution_contracts_20260827.json": "varanegar_report_preview_export_print_execution_contracts",
    "ui/negin_personal_erp_blueprint_20260827.json": "negin_personal_erp_evidence_backed_blueprint",
    "ui/negin_erp_varanegar_migration_contract_20260827.json": "negin_erp_varanegar_migration_contract",
    "ui/negin_erp_role_sod_contract_20260827.json": "negin_erp_identity_free_role_and_sod_contract",
    "ui/varanegar_data_entry_il_contracts_20260827.json": "varanegar_all_data_entry_form_il_contracts",
    "ui/varanegar_high_impact_call_graph_20260827.json": "varanegar_high_impact_form_to_business_dataaccess_call_graph",
    "ui/varanegar_orchestrator_command_contracts_20260827.json": "varanegar_high_impact_orchestrator_target_command_contracts",
    "ui/varanegar_orchestrator_golden_cases_20260827.json": "negin_erp_high_impact_orchestrator_synthetic_golden_cases",
    "ui/varanegar_all_form_call_contracts_20260827.json": "varanegar_all_high_confidence_form_compact_call_contracts",
    "ui/varanegar_form_evidence_gaps_20260827.json": "varanegar_complete_form_evidence_gap_catalog",
    "ui/varanegar_priority_gap_routes_20260827.json": "varanegar_priority_form_gap_static_route_evidence",
    "ui/varanegar_priority_gap_call_graph_20260827.json": "varanegar_priority_form_gap_parent_and_datalayer_call_graph",
    "ui/varanegar_root_entrypoints_20260827.json": "varanegar_unresolved_root_entrypoint_all_assembly_scan",
    "ui/varanegar_deployment_root_reference_scan_20260827.json": "varanegar_unresolved_root_deployment_exact_reference_scan",
    "ui/varanegar_priority_gap_declared_fields_20260827.json": "varanegar_priority_gap_declared_field_metadata",
    "ui/varanegar_bank_reconciliation_source_model_20260827.json": "varanegar_bank_reconciliation_clone_source_catalog_model",
    "ui/varanegar_bank_reconciliation_command_guards_20260827.json": "varanegar_bank_reconciliation_command_guard_contracts",
    "ui/varanegar_bank_reconciliation_permission_catalog_20260827.json": "varanegar_bank_reconciliation_permission_alias_catalog_boundary",
    "ui/varanegar_bank_reconciliation_delete_semantics_20260827.json": "varanegar_bank_reconciliation_delete_unmatch_discard_semantics",
    "ui/varanegar_bank_reconciliation_unmatch_sql_semantics_20260827.json": "varanegar_bank_reconciliation_unmatch_redacted_sql_delete_semantics",
    "ui/varanegar_bank_reconciliation_discard_cancel_boundary_20260827.json": "varanegar_bank_reconciliation_setup_discard_rows_versus_cancel_session_boundary",
    "ui/varanegar_bank_reconciliation_integrity_aggregates_20260827.json": "varanegar_bank_reconciliation_privacy_safe_integrity_aggregate_snapshot",
    "ui/varanegar_bank_reconciliation_type_alias_aggregates_20260827.json": "varanegar_bank_reconciliation_privacy_safe_type_alias_aggregate_snapshot",
    "ui/varanegar_special_options_district_assessment_20260827.json": "varanegar_special_options_district_static_and_clone_catalog_assessment",
    "ui/varanegar_bank_statement_import_boundary_20260827.json": "varanegar_bank_statement_import_parser_file_and_office_boundary",
    "ui/varanegar_bank_statement_parser_row_contract_20260827.json": "varanegar_bank_statement_parser_row_mapping_dedup_and_atomicity_contract",
    "ui/varanegar_bank_statement_persistence_boundary_20260827.json": "varanegar_bank_statement_import_header_detail_persistence_boundary",
    "ui/negin_erp_bank_reconciliation_golden_cases_20260827.json": "negin_erp_bank_reconciliation_synthetic_golden_cases",
    "ui/varanegar_bank_reconciliation_transaction_boundary_20260827.json": "varanegar_bank_reconciliation_nested_static_transaction_boundary",
    "ui/varanegar_bank_reconciliation_cardex_sql_boundary_20260827.json": "varanegar_bank_reconciliation_cardex_sql_boundary",
    "ui/varanegar_bank_reconciliation_confirm_cardex_semantics_20260827.json": "varanegar_bank_reconciliation_confirm_cardex_redacted_mutation_semantics",
    "ui/varanegar_bank_reconciliation_confirm_orchestration_20260827.json": "varanegar_bank_reconciliation_confirm_ui_entity_cardex_orchestration_contract",
    "ui/negin_erp_bank_reconciliation_differential_acceptance_20260827.json": "negin_erp_bank_reconciliation_differential_acceptance_obligations",
    "ui/negin_erp_bank_reconciliation_owner_decision_register_20260827.json": "negin_erp_bank_reconciliation_owner_decision_register",
    "ui/negin_erp_bank_statement_profile_target_contract_20260827.json": "negin_erp_bank_statement_versioned_profile_catalog_target_contract",
    "ui/negin_erp_bank_reconciliation_read_model_contract_20260827.json": "negin_erp_bank_reconciliation_scoped_read_model_and_summary_contract",
    "ui/negin_erp_bank_statement_staging_target_contract_20260827.json": "negin_erp_bank_statement_isolated_parser_and_atomic_staging_target_contract",
    "ui/negin_erp_bank_reconciliation_state_machine_contract_20260827.json": "negin_erp_bank_reconciliation_decision_gated_target_state_machine_contract",
    "ui/negin_erp_bank_reconciliation_command_envelope_20260827.json": "negin_erp_bank_reconciliation_uniform_atomic_command_envelope_contract",
    "ui/negin_erp_bank_reconciliation_authenticated_uat_runbook_20260827.json": "negin_erp_bank_reconciliation_identity_safe_authenticated_uat_execution_runbook",
    "ui/negin_erp_bank_reconciliation_evidence_request_pack_20260827.json": "negin_erp_bank_reconciliation_least_privilege_evidence_and_access_request_pack",
    "ui/varanegar_bank_reconciliation_matching_boundary_20260827.json": "varanegar_bank_reconciliation_matching_ui_dataaccess_catalog_boundary",
    "ui/varanegar_bank_reconciliation_summary_ui_boundary_20260827.json": "varanegar_bank_reconciliation_summary_output_to_ui_presentation_boundary",
    "ui/varanegar_bank_reconciliation_summary_sql_semantics_20260827.json": "varanegar_bank_reconciliation_summary_redacted_sql_formula_semantics",
    "ui/varanegar_bank_reconciliation_profile_state_boundary_20260827.json": "varanegar_bank_reconciliation_profile_and_state_boundary",
    "ui/negin_erp_bank_reconciliation_role_uat_20260827.json": "negin_erp_bank_reconciliation_identity_free_role_uat_contract",
    "ui/varanegar_unresolved_root_closure_contract_20260827.json": "varanegar_three_unresolved_root_evidence_closure_contract",
    "ui/negin_erp_bank_reconciliation_implementation_readiness_20260827.json": "negin_erp_bank_reconciliation_evidence_backed_implementation_readiness_contract",
    "ui/negin_erp_p0_backlog_20260827.json": "negin_personal_erp_p0_evidence_backed_backlog",
    "ui/negin_erp_module_readiness_matrix_20260827.json": "negin_personal_erp_module_evidence_and_readiness_matrix",
    "ui/negin_erp_risk_register_20260827.json": "negin_personal_erp_evidence_backed_risk_register",
    "ui/varanegar_navigation_module_map_20260827.json": "varanegar_complete_navigation_tree_target_module_hint_map",
    "ui/varanegar_scope_freeze_catalog_20260827.json": "varanegar_unmatched_configured_route_scope_freeze_catalog",
    "ui/varanegar_present_package_route_types_20260827.json": "varanegar_present_package_unmatched_route_typedef_and_il_resolution",
    "ui/varanegar_extension_capability_map_20260827.json": "varanegar_route_backed_extension_capability_map",
    "ui/varanegar_extension_dependency_graph_20260827.json": "varanegar_extension_ui_business_dataaccess_dependency_graph",
    "ui/varanegar_extension_command_paths_20260827.json": "varanegar_material_extension_method_command_guard_dependency_paths",
    "ui/varanegar_extension_target_contracts_20260827.json": "negin_erp_material_extension_target_command_query_contracts",
    "ui/varanegar_extension_golden_cases_20260827.json": "negin_erp_material_extension_synthetic_golden_cases",
    "ui/varanegar_extension_sql_surface_20260827.json": "varanegar_material_extension_clone_sql_catalog_surface",
    "ui/varanegar_extension_data_boundary_assessment_20260827.json": "varanegar_extension_legacy_data_boundary_and_clone_catalog_assessment",
    "ui/varanegar_extension_gap_paths_20260827.json": "varanegar_three_extension_gap_related_type_and_il_paths",
    "ui/varanegar_extension_sql_anchor_contracts_20260827.json": "varanegar_material_extension_selected_sql_anchor_contracts",
    "ui/varanegar_extension_sql_semantics_20260827.json": "varanegar_selected_extension_sql_module_redacted_semantic_footprints",
    "ui/negin_erp_pos_receipt_replication_contract_20260827.json": "negin_erp_pos_receipt_replication_batch_state_and_reconciliation_contract",
    "ui/varanegar_pos_replication_transitive_graph_20260827.json": "varanegar_pos_receipt_replication_bounded_transitive_sql_graph",
    "ui/negin_erp_requirements_traceability_20260827.json": "negin_personal_erp_requirement_evidence_test_risk_traceability_matrix",
    "ui/varanegar_pos_source_model_20260827.json": "varanegar_pos_receipt_replication_clone_source_catalog_model",
    "ui/negin_erp_stack_recovery_decision_input_20260827.json": "negin_personal_erp_stack_and_recovery_adr_decision_input",
    "ui/varanegar_ui_checkpoint_20260827_0300.json": "varanegar_windows_ui_inventory",
    "ui/varanegar_ui_checkpoint_comparison_20260827_0300.json": "varanegar_read_only_ui_checkpoint_semantic_comparison",
    "ui/varanegar_ui_checkpoint_20260827_0545.json": "varanegar_windows_ui_inventory",
    "ui/varanegar_ui_checkpoint_comparison_20260827_0545.json": "varanegar_read_only_ui_checkpoint_semantic_comparison",
    "ui/varanegar_ui_checkpoint_20260827_0740.json": "varanegar_windows_ui_inventory",
    "ui/varanegar_ui_checkpoint_comparison_20260827_0740.json": "varanegar_read_only_ui_checkpoint_semantic_comparison",
    "ui/negin_erp_end_to_end_process_atlas_20260827.json": "negin_personal_erp_end_to_end_process_evidence_atlas",
    "ui/varanegar_report_target_contracts_golden_cases_20260827.json": "negin_personal_erp_report_target_contracts_and_synthetic_golden_cases",
    "ui/varanegar_report_dependency_graph_20260827.json": "varanegar_report_ui_business_dataaccess_static_dependency_graph",
    "ui/varanegar_report_sql_candidates_20260827.json": "varanegar_report_clone_sql_catalog_name_candidate_surface",
    "ui/varanegar_report_method_paths_20260827.json": "varanegar_report_scoped_ui_business_dataaccess_method_paths",
    "ui/varanegar_report_evidence_gaps_20260827.json": "varanegar_report_evidence_gap_and_closure_register",
    "ui/varanegar_report_shell_entrypoints_20260827.json": "varanegar_unresolved_report_shell_all_assembly_entrypoint_scan",
    "ui/varanegar_report_shell_caller_paths_20260827.json": "varanegar_report_shell_caller_to_dataaccess_scoped_paths",
    "ui/varanegar_report_generic_bindings_20260827.json": "varanegar_report_shell_generic_handler_entityhelper_bindings",
    "ui/varanegar_report_generic_sql_candidates_20260827.json": "varanegar_generic_report_binding_clone_sql_name_candidates",
    "ui/varanegar_report_generic_sql_semantics_20260827.json": "varanegar_unique_generic_report_sql_redacted_semantic_footprints",
    "ui/negin_erp_role_uat_cases_20260827.json": "negin_erp_identity_free_role_scope_sod_synthetic_uat_cases",
    "ui/varanegar_data_entry_field_dictionary_20260827.json": "varanegar_data_entry_static_control_field_dictionary",
    "ui/varanegar_data_entry_declared_fields_20260827.json": "varanegar_data_entry_declared_control_field_metadata",
    "ui/varanegar_data_entry_base_template_contracts_20260827.json": "varanegar_data_entry_shared_base_template_field_and_method_contracts",
    "ui/varanegar_data_entry_field_types_20260827.json": "varanegar_data_entry_declared_field_clr_type_resolution",
    "ui/varanegar_data_entry_field_binding_candidates_20260827.json": "varanegar_data_entry_static_field_to_property_binding_candidates",
    "ui/varanegar_data_entry_field_sql_columns_20260827.json": "varanegar_data_entry_field_property_to_clone_column_candidates",
    "ui/varanegar_treasury_edit_command_paths_20260827.json": "varanegar_treasury_edit_static_transaction_field_setter_and_inline_sql_paths",
    "ui/varanegar_treasury_edit_source_model_20260827.json": "varanegar_treasury_edit_clone_catalog_source_model",
    "ui/varanegar_treasury_trigger_semantics_20260827.json": "varanegar_treasury_edit_trigger_redacted_semantic_footprints",
    "ui/varanegar_treasury_view_column_lineage_20260827.json": "varanegar_treasury_writable_view_catalog_resolved_column_lineage",
    "ui/negin_erp_treasury_edit_target_contracts_20260827.json": "negin_erp_treasury_edit_target_command_contracts_and_unexecuted_acceptance_obligations",
    "ui/varanegar_treasury_edit_validation_contracts_20260827.json": "varanegar_treasury_edit_static_validation_configuration_balance_and_date_contracts",
    "ui/varanegar_treasury_trigger_transitive_graph_20260827.json": "varanegar_treasury_trigger_bounded_transitive_sql_dependency_graph",
    "ui/varanegar_treasury_web_field_contract_candidates_20260827.json": "varanegar_treasury_edit_merged_web_field_contract_candidates",
    "ui/varanegar_treasury_ui_label_candidates_20260827.json": "varanegar_treasury_static_ui_label_candidates",
    "ui/negin_erp_treasury_web_screen_contract_candidates_20260827.json": "negin_erp_treasury_web_screen_contract_candidates",
    "ui/varanegar_order_sale_entry_command_contracts_20260827.json": "varanegar_order_sale_return_entry_static_command_validation_contracts",
    "ui/varanegar_order_sale_ui_label_candidates_20260827.json": "varanegar_order_sale_return_static_ui_label_candidates",
    "ui/varanegar_order_sale_full_field_metadata_20260827.json": "varanegar_order_sale_return_complete_declared_field_type_and_label_metadata",
    "ui/varanegar_order_sale_layout_bindings_20260827.json": "varanegar_order_sale_return_static_layout_item_control_bindings",
    "ui/negin_erp_order_sale_web_screen_contract_candidates_20260827.json": "negin_erp_order_sale_return_web_screen_contract_candidates",
    "ui/varanegar_order_sale_command_dependency_graph_20260827.json": "varanegar_order_sale_return_bounded_business_dataaccess_dependency_graph",
    "ui/varanegar_order_sale_sql_semantics_20260827.json": "varanegar_order_sale_return_sql_redacted_semantic_footprints",
    "ui/varanegar_order_sale_mutation_source_model_20260827.json": "varanegar_order_sale_return_resolved_mutation_target_clone_catalog_model",
    "ui/varanegar_order_sale_trigger_transitive_graph_20260827.json": "varanegar_order_sale_return_trigger_bounded_transitive_sql_dependency_graph",
    "ui/varanegar_stock_voucher_command_contract_20260827.json": "varanegar_stock_voucher_static_command_validation_transition_contract",
    "ui/varanegar_distribution_sql_anchor_contracts_20260827.json": "varanegar_distribution_to_exit_sql_anchor_contracts",
    "ui/varanegar_distribution_sql_semantics_20260827.json": "varanegar_distribution_to_exit_sql_redacted_semantic_footprints",
    "ui/varanegar_distribution_mutation_source_model_20260827.json": "varanegar_distribution_to_exit_resolved_mutation_target_clone_catalog_model",
    "ui/varanegar_distribution_trigger_transitive_graph_20260827.json": "varanegar_distribution_to_exit_trigger_transitive_graph",
    "ui/varanegar_supplier_invoice_command_contract_20260827.json": "varanegar_supplier_invoice_return_static_command_validation_trigger_guard_contract",
    "ui/varanegar_supplier_invoice_sql_anchor_contracts_20260827.json": "varanegar_supplier_invoice_relation_inline_sql_catalog_anchor_contracts",
    "ui/varanegar_supplier_invoice_relation_source_model_20260827.json": "varanegar_supplier_invoice_relation_clone_catalog_source_model",
    "ui/varanegar_supplier_invoice_relation_trigger_transitive_graph_20260827.json": "varanegar_supplier_invoice_relation_trigger_transitive_graph",
    "ui/varanegar_stock_supplier_ui_label_candidates_20260827.json": "varanegar_stock_voucher_supplier_invoice_return_static_ui_label_candidates",
    "ui/varanegar_stock_supplier_full_field_metadata_20260827.json": "varanegar_stock_voucher_supplier_invoice_return_complete_declared_field_type_and_label_metadata",
    "ui/varanegar_stock_supplier_layout_bindings_20260827.json": "varanegar_stock_voucher_supplier_invoice_return_static_layout_item_control_bindings",
    "ui/negin_erp_stock_supplier_web_screen_contract_candidates_20260827.json": "negin_erp_stock_voucher_supplier_invoice_return_web_screen_contract_candidates",
    "ui/varanegar_accounting_voucher_entrypoint_contracts_20260827.json": "varanegar_accounting_external_stock_confirm_manual_voucher_static_entrypoint_contracts",
    "ui/varanegar_accounting_voucher_sql_candidates_20260827.json": "varanegar_accounting_external_manual_create_voucher_clone_sql_name_candidate_surface",
    "ui/varanegar_customer_goods_command_contracts_20260827.json": "varanegar_customer_goods_master_data_static_command_validation_permission_contracts",
    "ui/varanegar_customer_ui_label_candidates_20260827.json": "varanegar_customer_master_static_ui_label_candidates",
    "ui/varanegar_customer_full_field_metadata_20260827.json": "varanegar_customer_master_complete_declared_field_type_and_label_metadata",
    "ui/varanegar_customer_layout_bindings_20260827.json": "varanegar_customer_master_static_layout_item_control_bindings",
    "ui/varanegar_goods_ui_label_candidates_20260827.json": "varanegar_goods_master_static_ui_label_candidates",
    "ui/varanegar_goods_full_field_metadata_20260827.json": "varanegar_goods_master_complete_declared_field_type_and_label_metadata",
    "ui/varanegar_goods_layout_bindings_20260827.json": "varanegar_goods_master_static_layout_item_control_bindings",
    "ui/negin_erp_customer_goods_web_screen_contract_candidates_20260827.json": "negin_erp_customer_goods_master_data_web_screen_contract_candidates",
    "ui/negin_erp_customer_goods_master_golden_cases_20260827.json": "negin_erp_customer_goods_master_data_synthetic_golden_cases",
    "ui/varanegar_supplier_master_command_contract_20260827.json": "varanegar_supplier_master_static_command_validation_permission_relation_contract",
    "ui/varanegar_supplier_ui_label_candidates_20260827.json": "varanegar_supplier_master_static_ui_label_candidates",
    "ui/varanegar_supplier_full_field_metadata_20260827.json": "varanegar_supplier_master_complete_declared_field_type_and_label_metadata",
    "ui/varanegar_supplier_layout_bindings_20260827.json": "varanegar_supplier_master_static_layout_item_control_bindings",
    "ui/negin_erp_supplier_master_web_screen_contract_candidate_20260827.json": "negin_erp_supplier_master_data_web_screen_contract_candidate",
    "ui/varanegar_operational_context_command_contracts_20260827.json": "varanegar_operational_year_stock_dc_and_stock_accounting_static_command_contracts",
    "ui/varanegar_operational_context_main_ui_labels_20260827.json": "varanegar_operational_year_stock_dc_static_ui_label_candidates",
    "ui/varanegar_operational_context_main_full_fields_20260827.json": "varanegar_operational_year_stock_dc_complete_field_metadata",
    "ui/varanegar_operational_context_main_layout_20260827.json": "varanegar_operational_year_stock_dc_static_layout_bindings",
    "ui/varanegar_stock_accounting_context_ui_labels_20260827.json": "varanegar_stock_accounting_context_static_ui_label_candidates",
    "ui/varanegar_stock_accounting_context_full_fields_20260827.json": "varanegar_stock_accounting_context_complete_field_metadata",
    "ui/varanegar_stock_accounting_context_layout_20260827.json": "varanegar_stock_accounting_context_static_layout_bindings",
    "ui/negin_erp_operational_context_web_screen_contract_candidates_20260827.json": "negin_erp_operational_year_stock_dc_and_stock_accounting_web_screen_contract_candidates",
    "ui/negin_erp_morning_readiness_handoff_20260827.json": "negin_erp_varanegar_morning_evidence_readiness_handoff",
    "ui/varanegar_ui_checkpoint_20260827_0900.json": "varanegar_windows_ui_inventory",
    "ui/varanegar_ui_checkpoint_comparison_20260827_0900.json": "varanegar_read_only_ui_checkpoint_semantic_comparison",
    "ui/varanegar_pricing_rule_command_contracts_20260827.json": "varanegar_contextual_price_and_discount_rule_static_command_scope_precedence_contracts",
    "ui/varanegar_pricing_rule_ui_labels_20260827.json": "varanegar_contextual_price_discount_static_ui_label_candidates",
    "ui/varanegar_pricing_rule_full_fields_20260827.json": "varanegar_contextual_price_discount_complete_field_metadata",
    "ui/varanegar_pricing_rule_layout_20260827.json": "varanegar_contextual_price_discount_static_layout_bindings",
    "ui/negin_erp_pricing_rule_web_screen_contract_candidates_20260827.json": "negin_erp_contextual_price_and_discount_rule_web_screen_contract_candidates",
    "ui/negin_erp_foundation_context_pricing_golden_cases_20260827.json": "negin_erp_supplier_operational_context_and_pricing_synthetic_golden_cases",
}

DOCUMENTS = (
    "UI_RUNTIME_INVENTORY_20260827_FA.md",
    "DOTNET_RUNTIME_ARCHITECTURE_20260827_FA.md",
    "UI_CAPABILITY_MATRIX_20260827_FA.md",
    "FORM_CATALOG_20260827_FA.md",
    "WORKFLOW_CATALOG_20260827_FA.md",
    "REPORT_CATALOG_20260827_FA.md",
    "MENU_ROUTE_CROSSWALK_20260827_FA.md",
    "AUTHORIZATION_ROUTE_MATRIX_20260827_FA.md",
    "RUNTIME_DRIFT_BASELINE_20260827_FA.md",
    "ACTIVE_PAGE_CONTRACTS_20260827_FA.md",
    "STATE_MACHINE_CATALOG_20260827_FA.md",
    "COMMAND_SIDE_EFFECTS_20260827_FA.md",
    "GOLDEN_COMMAND_CASES_20260827_FA.md",
    "REPORT_EXECUTION_CONTRACTS_20260827_FA.md",
    "TARGET_ERP_BLUEPRINT_20260827_FA.md",
    "NIGHT_EVIDENCE_BUNDLE_20260827_FA.md",
    "MIGRATION_CONTRACT_20260827_FA.md",
    "ROLE_AND_SOD_CONTRACT_20260827_FA.md",
    "DATA_ENTRY_IL_CATALOG_20260827_FA.md",
    "HIGH_IMPACT_CALL_GRAPH_20260827_FA.md",
    "ORCHESTRATOR_COMMAND_CONTRACTS_20260827_FA.md",
    "ORCHESTRATOR_GOLDEN_CASES_20260827_FA.md",
    "ALL_FORM_CALL_CONTRACTS_20260827_FA.md",
    "FORM_EVIDENCE_GAPS_20260827_FA.md",
    "PRIORITY_FORM_GAP_RESOLUTION_20260827_FA.md",
    "DEPLOYMENT_ROOT_REFERENCE_SCAN_20260827_FA.md",
    "PRIORITY_FORM_DECLARED_FIELDS_20260827_FA.md",
    "BANK_RECONCILIATION_SOURCE_MODEL_20260827_FA.md",
    "BANK_RECONCILIATION_COMMAND_GUARDS_20260827_FA.md",
    "BANK_RECONCILIATION_PERMISSION_CATALOG_20260827_FA.md",
    "BANK_RECONCILIATION_DELETE_SEMANTICS_20260827_FA.md",
    "BANK_RECONCILIATION_UNMATCH_SQL_SEMANTICS_20260827_FA.md",
    "BANK_RECONCILIATION_DISCARD_CANCEL_BOUNDARY_20260827_FA.md",
    "BANK_RECONCILIATION_INTEGRITY_AGGREGATES_20260827_FA.md",
    "BANK_RECONCILIATION_TYPE_ALIAS_AGGREGATES_20260827_FA.md",
    "SPECIAL_OPTIONS_DISTRICT_ASSESSMENT_20260827_FA.md",
    "BANK_STATEMENT_IMPORT_BOUNDARY_20260827_FA.md",
    "BANK_STATEMENT_PARSER_ROW_AND_ATOMICITY_20260827_FA.md",
    "BANK_STATEMENT_PERSISTENCE_BOUNDARY_20260827_FA.md",
    "BANK_RECONCILIATION_GOLDEN_CASES_20260827_FA.md",
    "BANK_RECONCILIATION_TRANSACTION_BOUNDARY_20260827_FA.md",
    "BANK_RECONCILIATION_CARDEX_SQL_BOUNDARY_20260827_FA.md",
    "BANK_RECONCILIATION_CONFIRM_CARDEX_SEMANTICS_20260827_FA.md",
    "BANK_RECONCILIATION_CONFIRM_ORCHESTRATION_20260827_FA.md",
    "BANK_RECONCILIATION_DIFFERENTIAL_ACCEPTANCE_20260827_FA.md",
    "BANK_RECONCILIATION_OWNER_DECISION_PACK_20260827_FA.md",
    "BANK_STATEMENT_PROFILE_TARGET_CONTRACT_20260827_FA.md",
    "BANK_RECONCILIATION_READ_MODEL_TARGET_CONTRACT_20260827_FA.md",
    "BANK_STATEMENT_STAGING_TARGET_CONTRACT_20260827_FA.md",
    "BANK_RECONCILIATION_TARGET_STATE_MACHINE_20260827_FA.md",
    "BANK_RECONCILIATION_COMMAND_ENVELOPE_20260827_FA.md",
    "BANK_RECONCILIATION_AUTHENTICATED_UAT_RUNBOOK_20260827_FA.md",
    "BANK_RECONCILIATION_EVIDENCE_ACCESS_REQUEST_PACK_20260827_FA.md",
    "BANK_RECONCILIATION_END_TO_END_EVIDENCE_MAP_20260827_FA.md",
    "BANK_RECONCILIATION_MATCHING_BOUNDARY_20260827_FA.md",
    "BANK_RECONCILIATION_SUMMARY_UI_BOUNDARY_20260827_FA.md",
    "BANK_RECONCILIATION_SUMMARY_SQL_SEMANTICS_20260827_FA.md",
    "BANK_RECONCILIATION_PROFILE_STATE_BOUNDARY_20260827_FA.md",
    "BANK_RECONCILIATION_ROLE_UAT_CONTRACT_20260827_FA.md",
    "UNRESOLVED_ROOT_CLOSURE_CONTRACT_20260827_FA.md",
    "BANK_RECONCILIATION_IMPLEMENTATION_READINESS_20260827_FA.md",
    "P0_IMPLEMENTATION_BACKLOG_20260827_FA.md",
    "MODULE_READINESS_MATRIX_20260827_FA.md",
    "RISK_REGISTER_20260827_FA.md",
    "NAVIGATION_MODULE_MAP_20260827_FA.md",
    "SCOPE_FREEZE_CATALOG_20260827_FA.md",
    "EXTENDED_ROUTE_TYPE_RESOLUTION_20260827_FA.md",
    "EXTENSION_CAPABILITY_MAP_20260827_FA.md",
    "EXTENSION_DEPENDENCY_GRAPH_20260827_FA.md",
    "EXTENSION_COMMAND_PATHS_20260827_FA.md",
    "EXTENSION_TARGET_CONTRACTS_20260827_FA.md",
    "EXTENSION_GOLDEN_CASES_20260827_FA.md",
    "EXTENSION_SQL_AND_DATA_BOUNDARIES_20260827_FA.md",
    "EXTENSION_GAP_PATHS_20260827_FA.md",
    "EXTENSION_SQL_ANCHOR_CONTRACTS_20260827_FA.md",
    "EXTENSION_SQL_SEMANTICS_20260827_FA.md",
    "POS_RECEIPT_REPLICATION_CONTRACT_20260827_FA.md",
    "POS_RECEIPT_TRANSITIVE_SQL_GRAPH_20260827_FA.md",
    "REQUIREMENTS_TRACEABILITY_MATRIX_20260827_FA.md",
    "POS_SOURCE_MODEL_AND_SNAPSHOT_BOUNDARY_20260827_FA.md",
    "STACK_AND_RECOVERY_DECISION_INPUT_20260827_FA.md",
    "UI_CHECKPOINT_0300_20260827_FA.md",
    "END_TO_END_PROCESS_ATLAS_20260827_FA.md",
    "REPORT_TARGET_CONTRACTS_AND_GOLDEN_CASES_20260827_FA.md",
    "REPORT_DEPENDENCY_GRAPH_20260827_FA.md",
    "REPORT_SQL_CANDIDATES_20260827_FA.md",
    "REPORT_METHOD_PATHS_20260827_FA.md",
    "REPORT_EVIDENCE_GAPS_20260827_FA.md",
    "REPORT_SHELL_ENTRYPOINTS_20260827_FA.md",
    "REPORT_SHELL_CALLER_PATHS_20260827_FA.md",
    "REPORT_GENERIC_BINDINGS_20260827_FA.md",
    "REPORT_GENERIC_SQL_CANDIDATES_20260827_FA.md",
    "REPORT_GENERIC_SQL_SEMANTICS_20260827_FA.md",
    "ROLE_UAT_CASES_20260827_FA.md",
    "IDENTITY_ACCESS_ADMINISTRATION_NAVIGATION_GAP_20260827_FA.md",
    "SYSTEM_CONFIGURATION_NAVIGATION_AND_PRECEDENCE_20260827_FA.md",
    "FINAL_DATE_MANAGEMENT_CROSS_DOMAIN_BOUNDARY_20260827_FA.md",
    "FINAL_DATE_INCIDENT_DIAGNOSTIC_PLAYBOOK_20260827_FA.md",
    "STOCK_RECONCILIATION_INCIDENT_PLAYBOOK_20260827_FA.md",
    "DATA_ENTRY_FIELD_DICTIONARY_20260827_FA.md",
    "DATA_ENTRY_DECLARED_FIELDS_20260827_FA.md",
    "DATA_ENTRY_BASE_TEMPLATE_CONTRACTS_20260827_FA.md",
    "DATA_ENTRY_FIELD_TYPES_20260827_FA.md",
    "DATA_ENTRY_FIELD_BINDING_CANDIDATES_20260827_FA.md",
    "DATA_ENTRY_FIELD_SQL_COLUMN_CANDIDATES_20260827_FA.md",
    "TREASURY_EDIT_COMMAND_AND_VIEW_TRIGGER_BOUNDARY_20260827_FA.md",
    "ORDER_SALE_WEB_SCREEN_AND_COMMAND_BOUNDARY_20260827_FA.md",
    "STOCK_VOUCHER_AND_DISTRIBUTION_EXIT_BOUNDARY_20260827_FA.md",
    "SUPPLIER_INVOICE_RETURN_AND_TRIGGER_GUARD_BOUNDARY_20260827_FA.md",
    "UI_CHECKPOINT_0545_TO_0900_20260827_FA.md",
    "ACCOUNTING_VOUCHER_ENTRYPOINTS_AND_AUTOMATION_BOUNDARY_20260827_FA.md",
    "CUSTOMER_GOODS_MASTER_WEB_SCREEN_BOUNDARY_20260827_FA.md",
    "SUPPLIER_MASTER_WEB_SCREEN_BOUNDARY_20260827_FA.md",
    "OPERATIONAL_CONTEXT_AND_STOCK_DC_WEB_BOUNDARY_20260827_FA.md",
    "MORNING_HANDOFF_0900_20260827_FA.md",
    "CONTEXTUAL_PRICE_DISCOUNT_WEB_BOUNDARY_20260827_FA.md",
    "NGT_RETURN_CROSSWALK_DIAGNOSTIC_20260827_FA.md",
    "SUPPLIER_RECEIPT_COMPONENT_DIAGNOSTIC_20260827_FA.md",
)

SCRIPTS = (
    "windows/extract_varanegar_ui_inventory.ps1",
    "windows/extract_varanegar_binary_inventory.ps1",
    "windows/extract_varanegar_assembly_contracts.py",
    "windows/extract_varanegar_targeted_il_contracts.py",
    "sql/extract_varanegar_ui_sql_contracts.py",
    "windows/build_varanegar_ui_capability_matrix.py",
    "windows/build_varanegar_form_catalog.py",
    "windows/build_varanegar_workflow_catalog.py",
    "windows/build_varanegar_report_catalog.py",
    "sql/extract_varanegar_menu_route_catalog.py",
    "windows/build_varanegar_menu_form_crosswalk.py",
    "sql/extract_varanegar_route_authorization_matrix.py",
    "windows/build_varanegar_runtime_drift_baseline.py",
    "windows/build_varanegar_active_page_contracts.py",
    "windows/build_varanegar_state_machine_catalog.py",
    "sql/extract_varanegar_command_side_effects.py",
    "windows/build_varanegar_golden_command_cases.py",
    "windows/build_varanegar_report_execution_contracts.py",
    "windows/build_varanegar_target_erp_blueprint.py",
    "windows/validate_varanegar_night_evidence_bundle.py",
    "windows/build_varanegar_migration_contract.py",
    "windows/build_negin_erp_sod_role_contract.py",
    "windows/extract_varanegar_data_entry_il_contracts.py",
    "windows/extract_varanegar_high_impact_call_graph.py",
    "windows/build_varanegar_orchestrator_command_contracts.py",
    "windows/build_varanegar_orchestrator_golden_cases.py",
    "windows/extract_varanegar_all_form_call_contracts.py",
    "windows/build_varanegar_form_evidence_gap_catalog.py",
    "sql/extract_varanegar_priority_gap_routes.py",
    "windows/extract_varanegar_priority_gap_call_graph.py",
    "windows/extract_varanegar_root_entrypoints.py",
    "windows/extract_varanegar_deployment_root_reference_scan.py",
    "windows/extract_varanegar_priority_gap_declared_fields.py",
    "sql/extract_varanegar_bank_reconciliation_source_model.py",
    "windows/extract_varanegar_bank_reconciliation_command_guards.py",
    "sql/extract_varanegar_bank_reconciliation_permission_catalog.py",
    "sql/extract_varanegar_bank_reconciliation_delete_semantics.py",
    "sql/extract_varanegar_bank_reconciliation_unmatch_sql_semantics.py",
    "windows/extract_varanegar_bank_reconciliation_discard_cancel_boundary.py",
    "sql/extract_varanegar_bank_reconciliation_integrity_aggregates.py",
    "sql/extract_varanegar_bank_reconciliation_type_alias_aggregates.py",
    "sql/extract_varanegar_special_options_district_assessment.py",
    "windows/extract_varanegar_bank_statement_import_boundary.py",
    "windows/extract_varanegar_bank_statement_parser_row_contract.py",
    "sql/extract_varanegar_bank_statement_persistence_boundary.py",
    "windows/build_negin_erp_bank_reconciliation_golden_cases.py",
    "windows/extract_varanegar_bank_reconciliation_transaction_boundary.py",
    "sql/extract_varanegar_bank_reconciliation_cardex_sql_boundary.py",
    "sql/extract_varanegar_bank_reconciliation_confirm_cardex_semantics.py",
    "windows/extract_varanegar_bank_reconciliation_confirm_orchestration.py",
    "windows/build_negin_erp_bank_reconciliation_differential_acceptance.py",
    "windows/build_negin_erp_bank_reconciliation_owner_decision_pack.py",
    "windows/build_negin_erp_bank_statement_profile_target_contract.py",
    "windows/build_negin_erp_bank_reconciliation_read_model_contract.py",
    "windows/build_negin_erp_bank_statement_staging_target_contract.py",
    "windows/build_negin_erp_bank_reconciliation_state_machine_contract.py",
    "windows/build_negin_erp_bank_reconciliation_command_envelope.py",
    "windows/build_negin_erp_bank_reconciliation_authenticated_uat_runbook.py",
    "windows/build_negin_erp_bank_reconciliation_evidence_request_pack.py",
    "sql/extract_varanegar_bank_reconciliation_matching_boundary.py",
    "windows/extract_varanegar_bank_reconciliation_summary_ui_boundary.py",
    "sql/extract_varanegar_bank_reconciliation_summary_sql_semantics.py",
    "windows/extract_varanegar_bank_reconciliation_profile_state_boundary.py",
    "windows/build_negin_erp_bank_reconciliation_role_uat.py",
    "windows/build_varanegar_unresolved_root_closure_contract.py",
    "windows/build_negin_erp_bank_reconciliation_implementation_readiness.py",
    "windows/build_negin_erp_p0_backlog.py",
    "windows/build_negin_erp_module_readiness_matrix.py",
    "windows/build_negin_erp_risk_register.py",
    "windows/build_varanegar_navigation_module_map.py",
    "windows/build_varanegar_scope_freeze_catalog.py",
    "windows/extract_varanegar_present_package_route_types.py",
    "windows/build_varanegar_extension_capability_map.py",
    "windows/extract_varanegar_extension_dependency_graph.py",
    "windows/extract_varanegar_extension_command_paths.py",
    "windows/build_varanegar_extension_target_contracts.py",
    "windows/build_varanegar_extension_golden_cases.py",
    "sql/extract_varanegar_extension_sql_surface.py",
    "windows/build_varanegar_extension_data_boundary_assessment.py",
    "windows/extract_varanegar_extension_gap_paths.py",
    "windows/build_varanegar_extension_sql_anchor_contracts.py",
    "sql/extract_varanegar_extension_sql_semantics.py",
    "windows/build_negin_erp_pos_receipt_replication_contract.py",
    "sql/extract_varanegar_pos_replication_transitive_graph.py",
    "windows/build_negin_erp_requirements_traceability.py",
    "sql/extract_varanegar_pos_source_model.py",
    "windows/build_negin_erp_stack_and_recovery_decision_input.py",
    "windows/build_varanegar_ui_checkpoint_comparison.py",
    "windows/build_negin_erp_end_to_end_process_atlas.py",
    "windows/build_varanegar_report_target_contracts_and_golden_cases.py",
    "windows/extract_varanegar_report_dependency_graph.py",
    "sql/extract_varanegar_report_sql_candidates.py",
    "windows/extract_varanegar_report_method_paths.py",
    "windows/build_varanegar_report_evidence_gap_register.py",
    "windows/extract_varanegar_report_shell_entrypoints.py",
    "windows/extract_varanegar_report_shell_caller_paths.py",
    "windows/extract_varanegar_report_generic_bindings.py",
    "sql/extract_varanegar_report_generic_sql_candidates.py",
    "sql/extract_varanegar_report_generic_sql_semantics.py",
    "windows/build_negin_erp_role_uat_cases.py",
    "windows/build_varanegar_identity_access_navigation_gap_contract.py",
    "windows/build_varanegar_system_configuration_navigation_contract.py",
    "windows/build_varanegar_final_date_management_boundary.py",
    "sql/extract_varanegar_final_date_diagnostic_contract.py",
    "sql/extract_varanegar_stock_reconciliation_diagnostic_contract.py",
    "sql/extract_varanegar_distribution_path_diagnostic_contract.py",
    "sql/extract_varanegar_sales_return_amount_diagnostic_contract.py",
    "sql/extract_varanegar_returned_cheque_cross_customer_diagnostic_contract.py",
    "sql/extract_varanegar_received_cheque_projection_and_legal_type_diagnostic_contract.py",
    "sql/extract_varanegar_payable_cheque_leaf_usage_diagnostic_contract.py",
    "sql/extract_varanegar_voucher_status_pointer_diagnostic_contract.py",
    "sql/extract_varanegar_empty_voucher_shell_diagnostic_contract.py",
    "sql/extract_varanegar_ngt_return_crosswalk_diagnostic_contract.py",
    "sql/extract_varanegar_supplier_receipt_component_diagnostic_contract.py",
    "windows/build_varanegar_data_entry_field_dictionary.py",
    "windows/extract_varanegar_data_entry_declared_fields.py",
    "windows/extract_varanegar_data_entry_base_template_contracts.py",
    "windows/extract_varanegar_data_entry_field_types.py",
    "windows/build_varanegar_data_entry_field_binding_candidates.py",
    "sql/extract_varanegar_data_entry_field_sql_column_candidates.py",
    "windows/build_varanegar_treasury_edit_command_paths.py",
    "sql/extract_varanegar_treasury_edit_source_model.py",
    "sql/extract_varanegar_treasury_trigger_semantics.py",
    "sql/extract_varanegar_treasury_view_column_lineage.py",
    "windows/build_negin_erp_treasury_edit_target_contracts.py",
    "windows/build_varanegar_treasury_edit_validation_contracts.py",
    "sql/extract_varanegar_treasury_trigger_transitive_graph.py",
    "windows/build_varanegar_treasury_web_field_contract_candidates.py",
    "windows/extract_varanegar_treasury_ui_label_candidates.py",
    "windows/build_negin_erp_treasury_web_screen_contract_candidates.py",
    "windows/build_varanegar_order_sale_entry_command_contracts.py",
    "windows/extract_varanegar_order_sale_ui_label_candidates.py",
    "windows/extract_varanegar_order_sale_full_field_metadata.py",
    "windows/extract_varanegar_order_sale_layout_bindings.py",
    "windows/build_negin_erp_order_sale_web_screen_contract_candidates.py",
    "windows/extract_varanegar_order_sale_command_dependency_graph.py",
    "sql/extract_varanegar_order_sale_sql_semantics.py",
    "sql/extract_varanegar_order_sale_mutation_source_model.py",
    "windows/build_varanegar_stock_voucher_command_contract.py",
    "windows/build_varanegar_distribution_sql_anchor_contracts.py",
    "windows/build_varanegar_supplier_invoice_command_contract.py",
    "windows/build_varanegar_supplier_invoice_sql_anchor_contracts.py",
    "windows/build_negin_erp_stock_supplier_web_screen_contract_candidates.py",
    "windows/build_varanegar_accounting_voucher_entrypoint_contracts.py",
    "sql/extract_varanegar_accounting_voucher_sql_candidates.py",
    "windows/build_varanegar_customer_goods_command_contracts.py",
    "windows/build_negin_erp_customer_goods_web_screen_contract_candidates.py",
    "windows/build_negin_erp_customer_goods_master_golden_cases.py",
    "windows/build_varanegar_supplier_master_command_contract.py",
    "windows/build_negin_erp_supplier_master_web_screen_contract_candidate.py",
    "windows/build_varanegar_operational_context_command_contracts.py",
    "windows/build_negin_erp_operational_context_web_screen_contract_candidates.py",
    "windows/build_negin_erp_morning_readiness_handoff.py",
    "windows/build_varanegar_pricing_rule_command_contracts.py",
    "windows/build_negin_erp_pricing_rule_web_screen_contract_candidates.py",
    "windows/build_negin_erp_foundation_context_pricing_golden_cases.py",
)


def _sha(raw: bytes) -> str:
    return hashlib.sha256(raw).hexdigest()


def _entry(path: Path) -> dict[str, Any]:
    raw = path.read_bytes()
    return {"path": path.as_posix(), "bytes": len(raw), "sha256": _sha(raw)}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--project-root", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()

    project = args.project_root.resolve()
    artifact_root = project / "artifacts" / "varanegar_analysis"
    docs_root = project / "docs" / "varanegar_reconstruction"
    scripts_root = project / "scripts"
    errors: list[str] = []

    domain_manifest_path = artifact_root / "manifest_20260826.json"
    domain_manifest = json.loads(domain_manifest_path.read_text(encoding="utf-8-sig"))
    if domain_manifest.get("validation") != "PASS":
        errors.append("18-domain reconstruction manifest is not PASS")
    if domain_manifest.get("domain_count") != 18:
        errors.append("18-domain reconstruction manifest count changed")

    artifact_rows: list[dict[str, Any]] = []
    for relative, expected_artifact in UI_ARTIFACTS.items():
        path = artifact_root / relative
        if not path.is_file():
            errors.append(f"missing artifact: {relative}")
            continue
        payload = json.loads(path.read_text(encoding="utf-8-sig"))
        actual = payload.get("artifact") or payload.get("bundle")
        if actual != expected_artifact:
            errors.append(f"artifact identity mismatch: {relative}")
        if payload.get("schema_version") != 1:
            errors.append(f"schema version mismatch: {relative}")
        if (
            relative == "ui/varanegar_ui_checkpoint_comparison_20260827_0900.json"
            and payload.get("comparison_status") != "NO_SEMANTIC_UI_DRIFT"
        ):
            errors.append("final 0900 UI checkpoint is not stable against the 0740 method baseline")
        row = _entry(path)
        row.update(
            {
                "artifact": actual,
                "schema_version": payload.get("schema_version"),
                "safety_mode": (payload.get("safety") or {}).get("mode"),
                "summary": payload.get("summary"),
            }
        )
        artifact_rows.append(row)

    readme = (docs_root / "README_FA.md").read_text(encoding="utf-8")
    discovery = (docs_root / "DISCOVERY_LOG_FA.md").read_text(encoding="utf-8")
    document_rows = []
    for name in DOCUMENTS:
        path = docs_root / name
        if not path.is_file():
            errors.append(f"missing document: {name}")
            continue
        if name not in readme:
            errors.append(f"document not indexed by README: {name}")
        if name not in discovery:
            errors.append(f"document not recorded in discovery log: {name}")
        document_rows.append(_entry(path))

    script_rows = []
    for relative in SCRIPTS:
        path = scripts_root / relative
        if not path.is_file():
            errors.append(f"missing builder/extractor: {relative}")
            continue
        script_rows.append(_entry(path))

    # Cross-artifact gates that define whether the bundle still represents the
    # same evidence-backed reconstruction checkpoint.
    by_artifact = {row["artifact"]: row for row in artifact_rows}
    expected_summaries = {
        "varanegar_dotnet_form_catalog": ("form_candidate_count", 445),
        "varanegar_state_machine_catalog": ("state_count", 22),
        "varanegar_active_command_side_effect_contracts": ("command_trace_count", 11),
        "varanegar_target_erp_golden_command_cases": ("case_count", 77),
        "varanegar_report_preview_export_print_execution_contracts": ("surface_count", 20),
        "varanegar_all_data_entry_form_il_contracts": ("selected_form_count", 141),
        "varanegar_high_impact_form_to_business_dataaccess_call_graph": ("selected_form_count", 12),
        "negin_erp_high_impact_orchestrator_synthetic_golden_cases": ("case_count", 154),
        "varanegar_all_high_confidence_form_compact_call_contracts": ("selected_form_count", 442),
        "varanegar_complete_form_evidence_gap_catalog": ("form_candidate_count", 445),
        "varanegar_priority_form_gap_static_route_evidence": ("target_class_count", 7),
        "varanegar_priority_form_gap_parent_and_datalayer_call_graph": ("priority_gap_count", 7),
        "varanegar_unresolved_root_entrypoint_all_assembly_scan": ("target_root_count", 3),
        "negin_personal_erp_p0_evidence_backed_backlog": ("item_count", 26),
        "negin_personal_erp_module_evidence_and_readiness_matrix": ("module_count", 14),
        "negin_personal_erp_evidence_backed_risk_register": ("risk_count", 46),
        "varanegar_complete_navigation_tree_target_module_hint_map": ("route_count", 836),
        "varanegar_unmatched_configured_route_scope_freeze_catalog": ("candidate_count", 239),
        "varanegar_present_package_unmatched_route_typedef_and_il_resolution": ("candidate_count", 34),
        "varanegar_route_backed_extension_capability_map": ("capability_count", 32),
        "varanegar_extension_ui_business_dataaccess_dependency_graph": ("capability_count", 32),
        "varanegar_material_extension_method_command_guard_dependency_paths": ("selected_capability_count", 12),
        "varanegar_report_scoped_ui_business_dataaccess_method_paths": ("report_surface_count", 20),
        "varanegar_report_evidence_gap_and_closure_register": ("report_surface_count", 20),
        "varanegar_unresolved_report_shell_all_assembly_entrypoint_scan": ("target_report_shell_count", 7),
        "varanegar_unique_generic_report_sql_redacted_semantic_footprints": ("selected_module_count", 5),
        "negin_erp_identity_free_role_scope_sod_synthetic_uat_cases": ("synthetic_uat_case_count", 184),
        "varanegar_identity_access_administration_navigation_gap_contract": ("identity_access_route_candidate_count", 16),
        "varanegar_system_configuration_navigation_and_effective_setting_contract": ("configured_form_route_count", 15),
        "varanegar_cross_domain_final_date_management_command_boundary": ("configured_final_date_route_count", 5),
        "varanegar_final_and_operation_date_incident_diagnostic_contract": ("finding_count", 11),
        "varanegar_stock_reconciliation_incident_diagnostic_contract": ("official_formula_mismatch_count", 0),
        "varanegar_ngt_mobile_return_crosswalk_diagnostic_contract": ("historical_result_missing_current_order_count", 1),
        "varanegar_supplier_invoice_receipt_relation_component_diagnostic_contract": ("component_scope_quantity_mismatch_goods_group_count", 0),
        "negin_personal_erp_end_to_end_process_evidence_atlas": ("unique_golden_case_count", 877),
        "varanegar_data_entry_declared_control_field_metadata": ("selected_data_entry_form_count", 141),
        "varanegar_data_entry_field_property_to_clone_column_candidates": ("strong_static_field_count", 78),
        "varanegar_treasury_edit_static_transaction_field_setter_and_inline_sql_paths": ("target_form_count", 3),
        "varanegar_treasury_edit_clone_catalog_source_model": ("target_object_count", 8),
        "varanegar_treasury_edit_trigger_redacted_semantic_footprints": ("expected_trigger_count", 29),
        "varanegar_treasury_writable_view_catalog_resolved_column_lineage": ("target_view_count", 2),
        "negin_erp_treasury_edit_target_command_contracts_and_unexecuted_acceptance_obligations": ("target_command_contract_count", 3),
        "varanegar_treasury_edit_static_validation_configuration_balance_and_date_contracts": ("target_form_count", 3),
        "varanegar_treasury_trigger_bounded_transitive_sql_dependency_graph": ("root_trigger_count", 29),
        "varanegar_treasury_edit_merged_web_field_contract_candidates": ("target_form_count", 3),
        "varanegar_treasury_static_ui_label_candidates": ("target_form_count", 3),
        "negin_erp_treasury_web_screen_contract_candidates": ("screen_candidate_count", 3),
        "varanegar_order_sale_return_entry_static_command_validation_contracts": ("target_form_count", 3),
        "varanegar_order_sale_return_static_ui_label_candidates": ("target_form_count", 3),
        "varanegar_order_sale_return_complete_declared_field_type_and_label_metadata": ("declared_field_count", 423),
        "varanegar_order_sale_return_static_layout_item_control_bindings": ("layout_binding_candidate_count", 140),
        "negin_erp_order_sale_return_web_screen_contract_candidates": ("screen_candidate_count", 3),
        "varanegar_order_sale_return_bounded_business_dataaccess_dependency_graph": ("selected_business_method_node_count", 53),
        "varanegar_order_sale_return_sql_redacted_semantic_footprints": ("selected_anchor_count", 7),
        "varanegar_order_sale_return_resolved_mutation_target_clone_catalog_model": ("target_object_count", 9),
        "varanegar_order_sale_return_trigger_bounded_transitive_sql_dependency_graph": ("root_trigger_count", 73),
        "varanegar_stock_voucher_static_command_validation_transition_contract": ("selected_method_count", 9),
        "varanegar_distribution_to_exit_sql_anchor_contracts": ("sql_object_anchor_count", 5),
        "varanegar_distribution_to_exit_sql_redacted_semantic_footprints": ("selected_anchor_count", 5),
        "varanegar_distribution_to_exit_resolved_mutation_target_clone_catalog_model": ("target_object_count", 16),
        "varanegar_distribution_to_exit_trigger_transitive_graph": ("root_trigger_count", 87),
        "varanegar_supplier_invoice_return_static_command_validation_trigger_guard_contract": ("selected_method_count", 19),
        "varanegar_supplier_invoice_relation_inline_sql_catalog_anchor_contracts": ("resolved_durable_mutation_target_count", 1),
        "varanegar_supplier_invoice_relation_clone_catalog_source_model": ("target_object_count", 1),
        "varanegar_supplier_invoice_relation_trigger_transitive_graph": ("root_trigger_count", 4),
        "varanegar_stock_voucher_supplier_invoice_return_static_ui_label_candidates": ("target_form_count", 3),
        "varanegar_stock_voucher_supplier_invoice_return_complete_declared_field_type_and_label_metadata": ("declared_field_count", 288),
        "varanegar_stock_voucher_supplier_invoice_return_static_layout_item_control_bindings": ("layout_binding_candidate_count", 67),
        "negin_erp_stock_voucher_supplier_invoice_return_web_screen_contract_candidates": ("input_control_candidate_count", 94),
        "varanegar_accounting_external_stock_confirm_manual_voucher_static_entrypoint_contracts": ("target_command_candidate_count", 7),
        "varanegar_accounting_external_manual_create_voucher_clone_sql_name_candidate_surface": ("candidate_object_count", 128),
        "varanegar_customer_goods_master_data_static_command_validation_permission_contracts": ("selected_method_count", 21),
        "varanegar_customer_master_static_ui_label_candidates": ("target_form_count", 1),
        "varanegar_customer_master_complete_declared_field_type_and_label_metadata": ("declared_field_count", 263),
        "varanegar_customer_master_static_layout_item_control_bindings": ("layout_binding_candidate_count", 66),
        "varanegar_goods_master_static_ui_label_candidates": ("target_form_count", 1),
        "varanegar_goods_master_complete_declared_field_type_and_label_metadata": ("declared_field_count", 178),
        "varanegar_goods_master_static_layout_item_control_bindings": ("layout_binding_candidate_count", 56),
        "negin_erp_customer_goods_master_data_web_screen_contract_candidates": ("input_control_candidate_count", 130),
        "negin_erp_customer_goods_master_data_synthetic_golden_cases": ("case_count", 64),
        "varanegar_supplier_master_static_command_validation_permission_relation_contract": ("selected_method_count", 19),
        "varanegar_supplier_master_static_ui_label_candidates": ("target_form_count", 1),
        "varanegar_supplier_master_complete_declared_field_type_and_label_metadata": ("declared_field_count", 41),
        "varanegar_supplier_master_static_layout_item_control_bindings": ("layout_binding_candidate_count", 14),
        "negin_erp_supplier_master_data_web_screen_contract_candidate": ("input_control_candidate_count", 12),
        "varanegar_operational_year_stock_dc_and_stock_accounting_static_command_contracts": ("selected_method_count", 41),
        "varanegar_operational_year_stock_dc_static_ui_label_candidates": ("target_form_count", 2),
        "varanegar_operational_year_stock_dc_complete_field_metadata": ("declared_field_count", 69),
        "varanegar_operational_year_stock_dc_static_layout_bindings": ("layout_binding_candidate_count", 23),
        "varanegar_stock_accounting_context_static_ui_label_candidates": ("target_form_count", 1),
        "varanegar_stock_accounting_context_complete_field_metadata": ("declared_field_count", 14),
        "varanegar_stock_accounting_context_static_layout_bindings": ("layout_binding_candidate_count", 3),
        "negin_erp_operational_year_stock_dc_and_stock_accounting_web_screen_contract_candidates": ("input_control_candidate_count", 26),
        "negin_erp_varanegar_morning_evidence_readiness_handoff": ("synthetic_golden_case_count", 877),
        "varanegar_contextual_price_and_discount_rule_static_command_scope_precedence_contracts": ("selected_method_count", 56),
        "varanegar_contextual_price_discount_static_ui_label_candidates": ("target_form_count", 2),
        "varanegar_contextual_price_discount_complete_field_metadata": ("declared_field_count", 236),
        "varanegar_contextual_price_discount_static_layout_bindings": ("layout_binding_candidate_count", 45),
        "negin_erp_contextual_price_and_discount_rule_web_screen_contract_candidates": ("input_control_candidate_count", 40),
        "negin_erp_supplier_operational_context_and_pricing_synthetic_golden_cases": ("case_count", 192),
    }
    for artifact, (field, expected) in expected_summaries.items():
        actual = (by_artifact.get(artifact, {}).get("summary") or {}).get(field)
        if actual != expected:
            errors.append(f"checkpoint count mismatch: {artifact}.{field}")

    blueprint = json.loads(
        (artifact_root / "ui" / "negin_personal_erp_blueprint_20260827.json").read_text(
            encoding="utf-8"
        )
    )
    if blueprint.get("module_count") != 14 or len(blueprint.get("phases", [])) != 7:
        errors.append("target blueprint module/phase gate failed")
    if blueprint.get("architecture_style", {}).get("stack_status") != "not_selected_by_user":
        errors.append("target blueprint incorrectly claims a selected stack")

    component_hashes = {
        "domain_manifest": _entry(domain_manifest_path)["sha256"],
        "artifacts": {row["path"]: row["sha256"] for row in artifact_rows},
        "documents": {row["path"]: row["sha256"] for row in document_rows},
        "scripts": {row["path"]: row["sha256"] for row in script_rows},
        "indexes": {
            "README_FA.md": _entry(docs_root / "README_FA.md")["sha256"],
            "DISCOVERY_LOG_FA.md": _entry(docs_root / "DISCOVERY_LOG_FA.md")["sha256"],
        },
    }
    bundle_sha = _sha(
        json.dumps(component_hashes, sort_keys=True, separators=(",", ":")).encode("utf-8")
    )
    result = {
        "artifact": "varanegar_night_analysis_evidence_bundle_manifest",
        "schema_version": 1,
        "generated_at": datetime.now().astimezone().isoformat(),
        "validation": "PASS" if not errors else "FAIL",
        "safety": {
            "mode": "OFFLINE_PROJECT_EVIDENCE_VALIDATION",
            "database_connections": 0,
            "network_reads": 0,
            "live_ui_actions": 0,
            "application_or_business_commands_executed": 0,
            "source_or_target_business_rows_changed": 0,
        },
        "counts": {
            "validated_domain_count": domain_manifest.get("domain_count"),
            "ui_artifact_count": len(artifact_rows),
            "document_count": len(document_rows),
            "builder_or_extractor_count": len(script_rows),
            "error_count": len(errors),
        },
        "bundle_sha256": bundle_sha,
        "domain_manifest": _entry(domain_manifest_path),
        "knowledge_indexes": [
            _entry(docs_root / "README_FA.md"),
            _entry(docs_root / "DISCOVERY_LOG_FA.md"),
        ],
        "artifacts": artifact_rows,
        "documents": document_rows,
        "builders_and_extractors": script_rows,
        "errors": errors,
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8")
    print(args.output.resolve())
    print(json.dumps({"validation": result["validation"], "counts": result["counts"], "bundle_sha256": bundle_sha}, ensure_ascii=False))
    return 0 if not errors else 1


if __name__ == "__main__":
    raise SystemExit(main())
