import {Bell,Bot,Check,Download,LayoutGrid,Plus,Trash2} from 'lucide-react'
import {useState,type ReactNode} from 'react'
import {AIComposer,AIResponse,Attachment,BottomNavigation,BottomSheet,Breadcrumb,BulkActionBar,Button,Card,Checkbox,Cluster,Combobox,CommandSurface,CommercialPreviewShell,ContextMenu,CustomerSummaryCard,DateTimeField,Divider,EmptyState,ErrorState,Field,FilterBar,FloatingActionButton,FormSection,Icon,IconButton,KeyValue,MetricCard,VisualMetricCard,Modal,OfflineState,OrderSummaryShell,PageHeader,PasswordInput,PatternMetrics,PermissionDeniedState,ProductCard,ProductListRow,Progress,PromptChips,QuantityControl,Radio,ResponsivePageContainer,RouteActionGroup,QuickActionTile,RouteSummaryCard,RouteStopItem,SavedRequestRow,SearchInput,SectionHeader,SegmentedControl,SegmentedTabs,Select,Skeleton,Spinner,Stack,StatusBadge,Surface,Switch,Table,Tabs,Text,TextArea,TextInput,Timeline,Toast,ToolResultCard,InsightCard,TopAppBar,ProfileChip,NotificationButton,WarningBlock} from '..'
import '../styles.css'
import './lab.css'

const sections=[['00','Overview'],['01','Foundations'],['02','Colors'],['03','Typography'],['04','Spacing / Radius'],['05','Effects'],['06','Motion'],['07','Buttons / Actions'],['08','Forms'],['09','Feedback'],['10','Cards / Data Display'],['11','Navigation'],['12','AI'],['13','Enterprise Patterns'],['14','Seller / Operational Patterns'],['15','Responsive'],['16','Accessibility'],['17','State Matrix']] as const
function LabSection({id,title,description,children}:{id:string;title:string;description?:string;children:ReactNode}){return <section id={`lab-${id}`} className="ng-lab-section"><SectionHeader title={`${id} — ${title}`} description={description}/>{children}</section>}
function Demo({title,caption,children,className}:{title:string;caption?:string;children:ReactNode;className?:string}){return <article className={`ng-demo ${className??''}`}><header><strong>{title}</strong>{caption&&<small>{caption}</small>}</header><div>{children}</div></article>}
const rows=[{name:'ردیف آلفا',state:'آماده',owner:'گروه یک',score:'۹۴'},{name:'ردیف بتا',state:'نیازمند بررسی',owner:'گروه دو',score:'۷۸'},{name:'ردیف گاما',state:'متوقف',owner:'گروه سه',score:'—'}]
const columns=[{key:'name' as const,label:'عنوان'},{key:'state' as const,label:'وضعیت',render:(v:unknown)=><StatusBadge label={String(v)} tone={v==='آماده'?'success':v==='متوقف'?'danger':'warning'}/>},{key:'owner' as const,label:'مسئول'},{key:'score' as const,label:'امتیاز',numeric:true}]

export function DesignSystemLab(){
 const[toggle,setToggle]=useState(true),[segment,setSegment]=useState('comfortable'),[qty,setQty]=useState(2),[tab,setTab]=useState('overview'),[nav,setNav]=useState('ai'),[modal,setModal]=useState(false),[sheet,setSheet]=useState(false)
 return <div className="ng-v2 ng-lab" dir="rtl" data-trace-id="NG-DS-V2-LAB">
  <TopAppBar actions={<Cluster><StatusBadge label="v2.0 · Runtime" tone="premium"/><IconButton label="اعلان‌ها"><Bell/></IconButton></Cluster>}/>
  <div className="ng-lab-layout">
   <aside className="ng-lab-rail"><div><Text as="strong" variant="label">فهرست آزمایشگاه</Text><small>Design System Lab</small></div><nav aria-label="بخش‌های آزمایشگاه">{sections.map(([id,label])=><a key={id} href={`#lab-${id}`}><span>{id}</span>{label}</a>)}</nav></aside>
   <ResponsivePageContainer><Stack gap={12}>
    <LabSection id="00" title="Overview" description="زبان بصری مشترک برای تمام تجربه‌های Negin AI؛ RTL-first، سازمانی، آرام و قابل نگاشت به Figma.">
     <div className="ng-lab-hero"><div><StatusBadge label="Enterprise Operational & AI Platform" tone="premium"/><Text as="h1" variant="display">وضوح عملیاتی،<br/><em>هوشمندی مهارشده.</em></Text><Text variant="secondary">یک بنیان واحد برای موبایل، PWA و دسکتاپ؛ با عمق کنترل‌شده، طلایی گرم و اولویت همیشگی خوانایی.</Text><Cluster><Button size="lg" startIcon={<Bot/>}>اقدام اصلی</Button><Button size="lg" variant="secondary">مرور اجزا</Button></Cluster></div><div className="ng-hero-orbit" aria-hidden="true"><span><Bot/></span><i/><i/><i/></div></div>
     <PatternMetrics/><div className="ng-principles"><Card><Icon icon={Check}/><strong>یک پوسته مشترک</strong><p>نقش‌ها دسترسی و اولویت را تغییر می‌دهند، نه معماری ناوبری را.</p></Card><Card><Icon icon={LayoutGrid}/><strong>تراکم هدفمند</strong><p>فضای کافی برای وضوح، ساختار کافی برای کار روزانه سازمانی.</p></Card><Card><Icon icon={Bot}/><strong>AI در بافت کار</strong><p>دستیار بخشی از محصول است، نه یک تجربه جدا یا تقلید از چت عمومی.</p></Card></div>
    </LabSection>
    <LabSection id="01" title="Foundations" description="Primitives ترکیب‌پذیر برای چیدمان، سطح، متن و پیمایش."><div className="ng-demo-grid"><Demo title="Surface hierarchy"><div className="ng-surface-stack">{[1,2,3,4].map(n=><Surface key={n} level={n as 1|2|3|4}>سطح {n.toLocaleString('fa-IR')}</Surface>)}</div></Demo><Demo title="Layout primitives"><Stack><Text variant="card">Stack</Text><Divider label="فاصله معنایی"/><Cluster><StatusBadge label="Cluster"/><StatusBadge label="RTL" tone="info"/><StatusBadge label="Flexible" tone="success"/></Cluster></Stack></Demo></div></LabSection>
    <LabSection id="02" title="Colors" description="رنگ‌ها نقش دارند؛ تزئین نیستند."><div className="ng-swatches">{[['Canvas','#060b15'],['Surface 1','#09111f'],['Surface 3','#101b2d'],['Text','#eef2f7'],['Muted gold','#bc9143'],['Info','#39b6d4'],['Success','#42b883'],['Warning','#d9a441'],['Danger','#df6670']].map(([n,c])=><div key={n}><i style={{background:c}}/><strong>{n}</strong><code>{c}</code></div>)}</div></LabSection>
    <LabSection id="03" title="Typography" description="Vazirmatn برای فارسی و ارقام tabular برای شاخص‌ها."><Demo title="Type scale"><Stack gap={5}><Text variant="display">نمایش شاخص محوری</Text><Text variant="page">عنوان صفحه عملیاتی</Text><Text variant="section">عنوان بخش</Text><Text variant="card">عنوان کارت و جزء</Text><Text>متن بدنه برای توضیح روشن و خوانا در کار روزانه سازمانی.</Text><Text variant="secondary">متن ثانویه برای اطلاعات پشتیبان و زمینه.</Text><Text variant="caption">شرح کوتاه و برچسب کم‌اهمیت</Text><Text variant="numeric" dir="ltr">128,450</Text></Stack></Demo></LabSection>
    <LabSection id="04" title="Spacing / Radius"><div className="ng-demo-grid"><Demo title="Spacing scale"><div className="ng-space-scale">{[4,8,12,16,20,24,32,40,48,64].map(n=><div key={n}><span style={{inlineSize:n}}/><code>{n}</code></div>)}</div></Demo><Demo title="Semantic radius"><div className="ng-radius-scale">{['control','button','card','sheet','modal','nav','floating','pill'].map(n=><span key={n} style={{borderRadius:`var(--ng-radius-${n})`}}>{n}</span>)}</div></Demo></div></LabSection>
    <LabSection id="05" title="Effects"><div className="ng-effects"><Surface>Surface elevation</Surface><Surface glass>Glass · 14px blur</Surface><div className="ng-effect-focus">Focus ring</div><div className="ng-effect-gold">Gold emphasis</div></div></LabSection>
    <LabSection id="06" title="Motion" description="بازخورد سریع ۱۲۰ms، گذار استاندارد ۱۹۰ms، پوشش ۲۵۰ms؛ سازگار با reduced motion."><Demo title="Purposeful motion"><Cluster><Button onClick={()=>setModal(true)}>نمایش Modal</Button><Button variant="secondary" onClick={()=>setSheet(true)}>نمایش Bottom Sheet</Button><Spinner/><span className="ng-motion-sample">حرکت کنترل‌شده</span></Cluster></Demo><Modal open={modal} title="Modal نمونه" onClose={()=>setModal(false)}><p>تمرکز، Escape و کلیک روی backdrop پشتیبانی می‌شوند.</p></Modal><BottomSheet open={sheet} title="Bottom Sheet نمونه" onClose={()=>setSheet(false)}><p>الگوی مناسب عملیات موبایل با ناحیه لمس کافی.</p></BottomSheet></LabSection>
    <LabSection id="07" title="Buttons / Actions"><div className="ng-demo-grid"><Demo title="Hierarchy"><Cluster><Button>اصلی</Button><Button variant="secondary">ثانویه</Button><Button variant="ghost">شفاف</Button><Button variant="destructive" startIcon={<Trash2/>}>مخرب</Button></Cluster></Demo><Demo title="Sizes & states"><Cluster><Button size="sm">کوچک</Button><Button size="lg">بزرگ</Button><Button loading>بارگذاری</Button><Button disabled>غیرفعال</Button><Button state="success">موفق</Button></Cluster></Demo><Demo title="Icon & floating"><Cluster><IconButton label="افزودن" variant="premium"><Plus/></IconButton><IconButton label="حذف" variant="destructive"><Trash2/></IconButton><FloatingActionButton label="اقدام سریع"><Plus/></FloatingActionButton></Cluster></Demo></div></LabSection>
    <LabSection id="08" title="Forms"><div className="ng-form-lab"><TextInput label="عنوان" placeholder="مقدار نمونه" help="توضیح همیشه قابل مشاهده"/><PasswordInput label="رمز عبور" defaultValue="sample-value"/><SearchInput label="جستجو" placeholder="جستجو در موارد نمونه"/><Select label="گزینش" options={[{value:'1',label:'گزینه یک'},{value:'2',label:'گزینه دو'}]}/><Combobox label="ترکیب جستجو و انتخاب" options={['گزینه آلفا','گزینه بتا']}/><TextInput label="فیلد نامعتبر" defaultValue="مقدار" error="شرح روشن خطا"/><TextArea label="یادداشت" placeholder="متن چندخطی"/><DateTimeField/></div><div className="ng-demo-grid"><Demo title="Choice controls"><Stack><Checkbox label="گزینه انتخابی" help="شرح مستقل از وضعیت رنگ" defaultChecked/><Radio label="گزینه اول" name="radio-demo" defaultChecked/><Radio label="گزینه دوم" name="radio-demo"/><Switch label="فعال‌سازی قابلیت" checked={toggle} onChange={setToggle}/></Stack></Demo><Demo title="Quantity & segmented"><Stack><QuantityControl label="تعداد نمونه" value={qty} onChange={setQty}/><SegmentedControl label="تراکم" value={segment} onChange={setSegment} items={[{id:'compact',label:'فشرده'},{id:'comfortable',label:'راحت'}]}/></Stack></Demo></div></LabSection>
    <LabSection id="09" title="Feedback"><div className="ng-status-grid">{(['neutral','premium','info','success','warning','danger','offline'] as const).map(t=><StatusBadge key={t} label={t} tone={t}/>)}</div><div className="ng-demo-grid"><Demo title="Progress & loading"><Stack><Progress value={68} label="پیشرفت نمونه"/><Spinner/><Skeleton lines={4}/></Stack></Demo><Demo title="Toast"><Stack><Toast message="عملیات با موفقیت ثبت شد" tone="success"/><Toast message="نیازمند بررسی" tone="warning"/><Toast message="اتصال برقرار نیست" tone="offline"/></Stack></Demo></div><div className="ng-state-grid"><EmptyState/><ErrorState/><OfflineState/><PermissionDeniedState/></div></LabSection>
    <LabSection id="10" title="Cards / Data Display"><div className="ng-demo-grid"><VisualMetricCard label={"\u0641\u0631\u0648\u0634 \u0627\u0645\u0631\u0648\u0632"} value="12,450,000" trend="+15%" values={[22,28,25,34,31,42]}/><VisualMetricCard label={"\u0648\u06cc\u0632\u06cc\u062a \u0627\u0645\u0631\u0648\u0632"} value="3/5" values={[10,18,26,34,45,60]}/></div><div className="ng-metrics"><MetricCard label="شاخص اول" value="۱۲۸٬۴۵۰" detail="دوره نمونه" trend="+۱۲٪" tone="success"/><MetricCard label="شاخص دوم" value="۸۷٪" detail="کیفیت نمایشی"/><MetricCard label="استثناها" value="۷" detail="نیازمند مرور" trend="۲ جدید" tone="warning"/></div><Demo title="Responsive table" caption="در موبایل به کارت داده تبدیل می‌شود"><div className="is-responsive"><Table caption="داده کاملاً ساختگی" columns={columns} rows={rows}/></div></Demo><div className="ng-demo-grid"><Demo title="Key / value"><KeyValue items={[{key:'وضعیت',value:<StatusBadge label="آماده" tone="success"/>},{key:'مالک',value:'گروه نمونه'},{key:'به‌روزرسانی',value:'امروز'}]}/></Demo><Demo title="Timeline"><Timeline items={[{title:'ایجاد شد',detail:'رویداد نمایشی',time:'۰۹:۱۵'},{title:'بررسی شد',detail:'بدون داده واقعی',time:'۱۰:۲۰'}]}/></Demo></div></LabSection>
    <LabSection id="11" title="Navigation" description="پوسته ثابت برای همه نقش‌ها؛ دستیار AI در مرکز ناوبری پایین."><Stack gap={6}><Cluster><ProfileChip name={"\u0639\u0644\u06cc \u0645\u062d\u0645\u062f\u06cc"} subtitle={"\u0648\u06cc\u0632\u06cc\u062a\u0648\u0631 \u0645\u0646\u0637\u0642\u0647 \u06a9\u0631\u062c"}/><NotificationButton count={3}><Bell/></NotificationButton></Cluster><Breadcrumb items={['خانه','ماژول‌ها','بخش نمونه']}/><CommandSurface/><Tabs value={tab} onChange={setTab} items={[{id:'overview',label:'نمای کلی',panel:<p>محتوای نمای کلی</p>},{id:'details',label:'جزئیات',panel:<p>محتوای جزئیات</p>},{id:'disabled',label:'غیرفعال',disabled:true}]}/><SegmentedTabs value={tab} onChange={setTab} items={[{id:'overview',label:'نمای کلی'},{id:'details',label:'جزئیات'}]}/><Demo title="Context menu"><ContextMenu items={['مشاهده جزئیات','ساخت نسخه','بایگانی']}/></Demo><div className="ng-nav-preview"><BottomNavigation activeId={nav} onNavigate={setNav}/></div></Stack></LabSection>
    <LabSection id="12" title="AI"><Stack gap={5}><InsightCard title={"\u0627\u0641\u0632\u0627\u06cc\u0634 \u0641\u0631\u0648\u0634 \u062f\u0631 \u0645\u0646\u0637\u0642\u0647 \u0634\u0645\u0627"} description={"\u067e\u06cc\u0634\u0646\u0647\u0627\u062f \u0647\u0648\u0634\u0645\u0646\u062f Negin AI"}/><PromptChips items={['خلاصه وضعیت نمایشی','کمک در پیدا کردن اطلاعات','توضیح این بخش']}/><AIResponse streaming><p>پاسخ نمونه با ارجاع به زمینه محصول نمایش داده می‌شود. تصمیم‌های تجاری و اعداد معتبر همچنان از سرویس‌های قابل اعتماد می‌آیند.</p></AIResponse><ToolResultCard title="نتیجه ابزار نمونه"><KeyValue items={[{key:'منبع',value:'داده آزمایشگاهی'},{key:'وضعیت',value:'قابل بررسی'}]}/></ToolResultCard><Attachment name="sample-document.pdf" type="PDF" size="128 KB"/><AIComposer/></Stack></LabSection>
    <LabSection id="13" title="Enterprise Patterns"><Stack gap={6}><PageHeader eyebrow="الگوی صفحه" title="سطح عملیاتی نمونه" description="عنوان، زمینه و اقدامات واضح بدون تحمیل معنای کسب‌وکار." actions={<Button startIcon={<Download/>}>خروجی</Button>}/><FilterBar/><BulkActionBar/><FormSection title="اطلاعات پایه" description="چیدمان تطبیقی برای فرم‌های طولانی"><TextInput label="عنوان اول"/><TextInput label="عنوان دوم"/><Select label="طبقه‌بندی" options={[{value:'1',label:'گزینه نمونه'}]}/><Field id="custom-field" label="کنترل سفارشی"><SegmentedControl label="وضعیت" value="a" onChange={()=>{}} items={[{id:'a',label:'الف'},{id:'b',label:'ب'}]}/></Field></FormSection></Stack></LabSection>
    <LabSection id="14" title="Seller / Operational Patterns" description="اجزای ارائه‌ای خنثی؛ بدون قیمت‌گذاری، اعتبار، موجودی، مسیر یا منطق ERP."><div className="ng-demo-grid"><QuickActionTile icon={<Plus/>} title={"\u0633\u0641\u0627\u0631\u0634 \u062c\u062f\u06cc\u062f"} meta={"\u062b\u0628\u062a \u0633\u0631\u06cc\u0639 \u0633\u0641\u0627\u0631\u0634"}/><RouteSummaryCard title={"\u0645\u0633\u06cc\u0631 \u0648\u06cc\u0632\u06cc\u062a \u0627\u0645\u0631\u0648\u0632"} visited={3} total={5} distance="24 km" eta="45 min"/><CustomerSummaryCard/><Card><RouteStopItem index={1}/><RouteStopItem index={2} title="ایستگاه بعدی" status="در انتظار"/></Card></div><div className="ng-products"><ProductCard/><Card><ProductListRow/><ProductListRow title="محصول نمونه دوم"/></Card></div><div className="ng-demo-grid"><OrderSummaryShell/><CommercialPreviewShell/></div><Stack><WarningBlock/><SavedRequestRow/><RouteActionGroup/></Stack></LabSection>
    <LabSection id="15" title="Responsive"><div className="ng-responsive-contracts">{[['390','Mobile','تک‌ستونه، ناوبری تمام‌عرض'],['430','Mobile+','فضای متنی بیشتر'],['768','Tablet','شبکه ۲ ستونه، ناوبری شناور'],['1024','Compact','Master/detail کارآمد'],['1440','Desktop','تراکم بالاتر و فضای سفید کنترل‌شده'],['1920','Wide','حداکثر عرض محتوا؛ بدون کشیدگی']].map(([w,n,d])=><Card key={w}><strong dir="ltr">{w}px</strong><span>{n}</span><small>{d}</small></Card>)}</div><div className="ng-responsive-demo"><aside>Master</aside><main><strong>Detail</strong><p>Container query و grid ساختار را با فضای واقعی جزء تطبیق می‌دهند.</p></main></div></LabSection>
    <LabSection id="16" title="Accessibility"><div className="ng-a11y-grid">{[['AA','کنتراست هدف'],['44px','حداقل هدف لمس'],['RTL','خواندن و جهت‌یابی'],['⌨','عملیات صفحه‌کلید'],['◉','Focus visible'],['0ms','Reduced motion']].map(([v,l])=><Card key={l}><strong>{v}</strong><span>{l}</span></Card>)}</div><p className="ng-a11y-note">وضعیت‌ها با آیکون و متن منتقل می‌شوند؛ label پایدار است؛ خطا با فیلد پیوند برنامه‌ای دارد؛ dialog از Escape پشتیبانی می‌کند.</p></LabSection>
    <LabSection id="17" title="State Matrix"><div className="ng-state-matrix"><div><strong>Default</strong><Button variant="secondary">اقدام</Button><TextInput label="فیلد" defaultValue="مقدار"/></div><div className="ng-state-sample--hover"><strong>Hover</strong><Button className="is-state-hover" variant="secondary">اقدام در اشاره‌گر</Button><Text variant="caption">افزایش سطح و مرز، بدون تغییر نقش رنگی</Text></div><div className="ng-state-sample--focus"><strong>Focus</strong><Button className="is-state-focus" variant="secondary">تمرکز صفحه‌کلید</Button><Text variant="caption">حلقه طلایی واضح و مستقل از رنگ سطح</Text></div><div className="ng-state-sample--selected"><strong>Selected</strong><Button className="is-state-selected" variant="secondary">انتخاب شده</Button><Switch label="فعال" checked onChange={()=>{}}/></div><div className="ng-state-sample--loading"><strong>Loading</strong><Button loading variant="secondary">در حال اجرا</Button><Skeleton lines={2}/></div><div className="ng-state-sample--success"><strong>Success</strong><StatusBadge label="موفق" tone="success"/><Button state="success" variant="secondary">تأیید</Button></div><div className="ng-state-sample--warning"><strong>Warning</strong><StatusBadge label="هشدار" tone="warning"/><Button state="warning" variant="secondary">بررسی</Button></div><div className="ng-state-sample--destructive"><strong>Destructive</strong><Button variant="destructive" startIcon={<Trash2/>}>حذف</Button><Text variant="caption">اقدام حساس با رنگ و آیکون مستقل</Text></div><div className="ng-state-sample--disabled"><strong>Disabled</strong><Button disabled variant="secondary">غیرفعال</Button><TextInput label="فیلد" disabled defaultValue="مقدار"/></div></div></LabSection>
   </Stack></ResponsivePageContainer>
  </div>
  <BottomNavigation activeId={nav} onNavigate={setNav}/>
 </div>
}
